### ISSUE TITLE
Task - browse nomenclature - types of the genus by subsequent designation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1001]
for the genus, the type species by subsequent designation, does not display a citation for the type designation.

**Comment by mjy** [comment]
@proceps - example data in 3i?

**Comment by proceps** [comment]
Genus Locris
https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name/333831

**Comment by mjy** [comment]
@proceps this is current dev, look OK?

![Screen Shot 2019-08-07 at 10 32 03 AM](https://user-images.githubusercontent.com/22600/62636154-a02cb800-b8fe-11e9-841d-dae03fe0e0f1.png)

**Comment by mjy** [comment]
@proceps Still a problem?

**Comment by proceps** [comment]
Yes it is still an issue

**Comment by mjy** [comment]
Fixed in `Page` branch.
