### ISSUE TITLE
Task - OTU radial - biological association

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1013]
provide citations for biological association in the same format as for assorted distribution.

**Comment by jlpereira** [comment]
You mean the possibility to add many citation to the same object?

**Comment by mjy** [comment]
@proceps Can you chime in here, seems we can close this quickly if so.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/82354525-890b1280-99c6-11ea-8087-511a1f56b5cf.png)
The first icon is missing in Biological associations in OTU radial

**Comment by mjy** [comment]
Biological associations can have many sources (citations) though, right?  Not sure this will work in present context.

**Comment by proceps** [comment]
It is the same with the distribution. One geographical area could be cited multiple times for a particular OTU. The same, I may have a host plant cited several times for one OTU.

**Comment by proceps** [comment]
partially related to the issue #1410
