### ISSUE TITLE
Data - Source - Edit 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1014]
I have a source with a Serial selected. When I click save the record, it is properly saved. I can preview the record.
I click the Edit button again. The Serial seams to be properly populated, but when I click Update record, the serial get destroyed (soft validation pops up).

**Comment by mjy** [comment]
Duplicate of  #696 I think.

**Comment by proceps** [comment]
Check this, it is quite critical, and should be easy to fix. 
When I edit source (which had serial selected), the serial is not populated back to form from the db, and once saved, the serial is destroyed.

**Comment by mjy** [comment]
See #696.  we need to resolve the expected behaviour to fix this.

**Comment by proceps** [comment]
it is not exactly related. In this case the serial is getting destroyed. The record which exists in the database (for) serial. Is not propagated into the form when you open edit. I do not see any overlap between Serial and verbatim. It seems all of this resolve properly in 3i project. Verbatim is overwritten if Serial exists. And this is an expected behavior.
