### ISSUE TITLE
display of citations

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1015]
In OSF, at species-group taxa, the references are cited chronologically, displaying the name considered as valid, in the same spelling as used in each reference. It is easy to follow from the original combination through subsequent combinations, rank changes between species and subspecies, proposed synonymies, reinstatements, down to the most recent references, that usually reflect the current status and generic placement. It is easy to gather the taxonomic history. With taxa that have few citations at a glance, and relatively rapidly with taxa that have many citations and nomenclatural issues.

Why are in TW the names and cited references split into two blocks, first names in chronological order and then again complete references in alphabetical order? Does this separation have an underlying rationale? To me it looks counterintuitive and confusing. Already when there are few citations, it takes a while to bring together cited names and corresponding references. If there are many citations, I sometimes have to scroll several screens down to find the reference corresponding to a cited name, during which I might forget the very name and its spelling, and upon scrolling up again, I perhaps cannot remember from where exactly I set off.

If there are subjective synonyms involved, it becomes even more intricate, since their citations are mixed with the valid name. Someone who wants to track the taxonomic history of a subjective synonym is almost at a loss.

The easy-to-follow organization in OSF, with complete chronological citations, separate for valid names and synonyms, becomes in TW several screens of fragmented text. If there are numerous citations and synonyms, it is practically useless. Too cumbersome and time-consuming to bring together cited names and correspondiung references, or track a particular taxon and its treament in the literature. 

I hope this will be much clearer in the public interface. As an editor and curator of OSF, I am profoundly unhappy with the current display. It is also difficult or next to impossible to spot incorrect, inconsistent, or missing data.

**Comment by mjy** [comment]
@typophyllum quick question before we dive into this in different ways, is there some combination of toggles under the "eye" that provides a view that you are more comfortable with, for example hiding relationships or combinations and only showing protonyms?

**Comment by typophyllum** [comment]
Not really.  I would like to easily track the history of a single nominal taxon, from protonym through subsequent combinations, proposed synonymies, rank changes, and misspellings, without being mixed with citations of subjective synonyms. And to see with every cited name directly the complete reference, to see whether it is e.g. a reliable taxonomic work or only a checklist.

**Comment by mjy** [comment]
@typophyllum I would like to close and have you open specific issues as improvements to the Browse taxa page, is that OK?

**Comment by typophyllum** [comment]
@mjy Yes, that would be OK.

**Comment by mjy** [comment]
Thanks.
