### ISSUE TITLE
How can I edit taxon names at citations?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1030]
In the example below the protonym ist wrong. In Thomas 1872 it is "Locusta fuliginosa" (epithet with feminine ending). This was incorrect in OSF. I cannot find out how to correct this. 

In the following two citations, Glover 1872 and Howard1902, and then again at Cockerell 1904, the nomenclator data were missing in OSF, so the protonym was arbitrarily filled in. Same problem: how can I replace this by "Locusta fuliginosa", and in the case of Cockerell 1904 with "Capnobotes fuliginosus"?

![imagen](https://user-images.githubusercontent.com/33210201/63712528-4b50d300-c814-11e9-8b9c-5b9385509b12.png)

And a related problem: when I add a new citation, I cannot select the name used in this reference (e.g. the current combination "Capnobotes fuliginosus"), but the citation is added with the incorrect protonym "Locusta fuliginosus".

Correcting and completing cited species names, as well as adding citations with names other than the protonym (including misspellings) are things I do very frequently in OSF.

**Comment by proceps** [comment]
If I understand the question right, the question is how to create a combination for the adjectival species which was moved from a feminine genus to masculine one.
1. edit each genus entry to set up a gender (at the bottom of each species page)
2. species name should be entered in the original form (not current name)
3. add adjective part of speech for the species (it will create 3 alternative forms for the species)
4. create a new combination, it will match the gender agreement.
5. if you want to create a species combination without gender agreement, you have to add a verbatim combination form, when you establish a new combination.

**Comment by typophyllum** [comment]
Thank you. In this case the original combination was incorrect in the database. I still don't understand how to edit the name at a paticular citation. For example with Tinkham 1973 is entered automatically the now correct protonym "Locusta fuliginosa". But Tinkham in fact uses the current combination "Capnobotes fuliginosus". How do I replace at the citation to Tinkam 1973 "Locusta fuliginosa" by "Capnobotes fuliginosus"?

**Comment by mjy** [comment]
Holger,

The answer is straightforwd at this point- you can't edit a taxon name at
the point of citation at this point.  You've described a very nice workflow
that we'll have to think hard about.

One thing you can do though, and this is likely the immediate answer, is to
move to Citations by source (I think we shoudl have a radial link
available, if not we can add).  There you can, I think, add a new taxon
name to the citation.  If that name replaces the Otu name then you could
also delete the citation to the Otu that corresponds.  Experiment with this
and let us know if it's a possible intermediate solution.

M

**Comment by proceps** [comment]
Holger, you have to create two combination. The one which is misspelled require a verbatim field. See an example the combination on the top and selected verbatim combination

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/63954346-93f0d200-ca48-11e9-8768-ee1ca9d07956.png)

**Comment by typophyllum** [comment]
Thanks. This works, but apparently it is not possible to add the page number (this is another question, how do I edit or add a page number at a citation?). And it is cumbersome. With this particular species I added in OSF missing nomenclator data at six or seven citations. Of course it took time to verify the correponding references, but editing the nomenclator data was done in a few seconds.

**Comment by typophyllum** [comment]
Another related problem: At the species Banza deplanata (Brunner von Wattenwyl, 1895) the original genus was wrong in OSF, and also in one subsequent citation. I corrected this in OSF and tried to repeat this in the TW Sandcastle. I had to add the missing original combination Brachymetopa deplanata, and now the real protonym is recorded as combination and the subsequent combination as protonym. I cannot find how to make Brunner von Wattenwyl 1895 the original.

![imagen](https://user-images.githubusercontent.com/33210201/63963683-ed1e2d00-ca6b-11e9-88a3-ddb0acf7b2d7.png)

**Comment by mjy** [comment]
Original combinations details are set in New Taxon Name, is this where you
added that information?  Don't add original combinations in the New
Combination task.

**Comment by typophyllum** [comment]
OK. I did it with the new combination task, since the combination was not yet recorded in the sandcastle. This was obviously wrong, but shouldn't there be a way to correct this error subsequently?

**Comment by mjy** [comment]
Do you mean turn a (some) combination into the original combination?

**Comment by typophyllum** [comment]
Yes. The problem with these cases (also adding page numbers to citations) seems to be that one cannot access the radial annotator window to add a citation for already existing citations.

**Comment by mjy** [comment]
Can you provide a screenshot where you need a radial annotator?  The
citations exist at the bottom and can be edited from there for pages.

**Comment by proceps** [comment]
if you have cases where genus is misspelled, the proper way to do it, create a protonym with a correctly spellled genus name, that would be you your valid species name.
Create two protonyms for the genera, one of them would be a misspelling of another.
Create a second protonym for a species an almost identical to the valid species, but original genus would be a misspelled one create a relationship to the valid name (Incorrect original spelling).

**Comment by mjy** [comment]
The sandbox had various things fixed this morning.

**Comment by typophyllum** [comment]
Thanks. This doesn't involve misspellings, but errors in the database (i.e. incorrect data from OSF imported to TW). In the last case a subsequent genus was incorrectly cited with the original description (Banza deplanata instead of Brachymetopa deplanata).

**Comment by proceps** [comment]
Do we still have any issues here, or it can be closed?

**Comment by mjy** [comment]
I think it's not specific enough here to stay open.  Open individual specifics as needed.
