### ISSUE TITLE
How do I add a citation to a subsequent combination?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1031]
This is partly related to my previous issue #1030.
I added the new genus Haudrhytidaspis Ingrisch 2019 (candidate for the worst genus name), selected as types pecies Rhytidaspis fusca Karny 1911, and changed the parent at this latter species to Haudrhytidaspis (would be nice if that could happen automatically)
I am unable to add a citation to Ingrisch 2019 with the new combination. I even entered the new combination separately:

![imagen](https://user-images.githubusercontent.com/33210201/63877308-bc6fc200-c99d-11e9-91b9-ee6b04f549e5.png)

When I want to add the citation, the radial annotator says that the protonym is H. fusca instead of R. fusca:

![imagen](https://user-images.githubusercontent.com/33210201/63877492-1bcdd200-c99e-11e9-9fb7-2d78eb853013.png)

... and it is added with the real protonym R. fusca instead of the combination H. fusca (would be nice if the page could refresh automatically to see the updated list of citations).

![imagen](https://user-images.githubusercontent.com/33210201/63877744-90087580-c99e-11e9-85c0-b226820a2af0.png)

**Comment by proceps** [comment]
please use the radial annotator next to the combination name "H. fusca" not the one next to protonym.
Alternatively you can click on the name of combination. And than you can use the radial annotator on the top right of the page. Each line in the nomenclatural page has its own radial annotator. If it is on a protonym, the citation is added to the proponym itself. The radial on combination adds citation to the combination. The radial on relationship, will cite this relationship (for example who established a synonymy between two species).

**Comment by typophyllum** [comment]
Thanks.
