### ISSUE TITLE
TaxonName - Does citing a invalidating relationship update cached valid name?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1033]
**Describe the bug**

When I have a name, and it has a history of 2 synonymies that have citations with years, when I create a new realtionship, then the valid name pointer stays the same.  When I add a citation that indicates that the synonym should move, then the cached record is NOT updated.

**Comment by proceps** [comment]
I saw this. At this point you have to click save button. Adding a citation does not trigger the taxon update. It is a marginal case. I will think about the solution

**Comment by mjy** [comment]
If it's an error then we fix it in the model.
