### ISSUE TITLE
Task - Edit TaxonName - type species relationship

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1039]
"Show all" button does not work

**Comment by mjy** [comment]
@jlpereira should be easy, task use `taxon_name_id` I suspect

**Comment by jlpereira** [comment]
Which is the nomenclature code of that project, @proceps ?

**Comment by proceps** [comment]
ICZN. section only visible for genera and subgenera

**Comment by proceps** [comment]
Still does not work. When I click edit, I am suggested to change the type species, I should be able to edit only the relationship type, the same behavior as for TaxonNameRelationship.

Besides, when I open Show all, all type of relationships are grayed out. All of them should be applicable. May be behavior is slightly different from TaxonNameRelationship here. In TaxonNameRelationship the rank used as a filter on a subject_taxon_name. In case of type, the filter should be on the object_taxon_name, we on the genus pages, which is an object, and the related taxon is added to the subject side (type species). So the applicable relationships should be filtered by the object_taxon_name rank.

**Comment by proceps** [comment]
Perfect! 
Only one unrelated thing. Trigger taxon name search on 2 letter, I have to type now at least 3 letters to start search.
