### ISSUE TITLE
Model - TaxonName - ColDP Concern

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1040]
As a developer I need a Concern for methods that map TW nomenclature to ColDP format

* [ ] `coldp_provisional` returns Boolean if it meets this definition
* [ ] `coldp_code` - from https://api.catalogue.life/vocab/nomcode
* [ ] `coldp_status` - from https://api.catalogue.life/vocab/nomStatus <strike> Question- is this only for "Invalid" names?</strike>
* [ ] `coldp_remarks` - What does this mean?  Notes, Confidence, etc. 

Ping #554

**Comment by mjy** [comment]
@gdower what's the current thinking with  https://api.catalogue.life/vocab/nomStatus? If we have @proceps start to map NOMEN will this be stable?

**Comment by gdower** [comment]
Can I get back to you on this on Tuesday? We haven't had a chance to discuss it on a CoL stand-up yet. Or I can ask Markus if I can chat with him about it tomorrow morning.

**Comment by mjy** [comment]
No rush.

**Comment by proceps** [comment]
@gdower @mjy What is the status of this? Do we still need the methods? On relationships or classifications? or summarized on each TN?

**Comment by gdower** [comment]
I think we can close this issue, because with the NOMEN implementation in CoL, it shouldn't be necessary to map TW nomenclature to CoL statuses. @yroskov and I will have to test that CoL's mapping of NOMEN to CoL statuses is implemented correctly, which we can test while working on 3i.
