### ISSUE TITLE
Add default tag or confidence lever.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1042]
When I add a default tag or confidence level (the button next to pin button). The confirmation message should include information which Tag or confidence level was added to the object

**Comment by mjy** [comment]
Already done for Tag, not sure confidence level.

**Comment by mjy** [comment]
@proceps I think this is done?

**Comment by proceps** [comment]
still missing tooltip (same as tag), and now it does not have green color on destroy

**Comment by proceps** [comment]
Tooltip works, but the green icon for default value is disappeared and the red icon for a an applied confidence level is now replaced with a trash can.

**Comment by jlpereira** [comment]
We're talking about the same icon? Because I don't see the trashcan

<img width="533" alt="Captura de Pantalla 2019-09-20 a la(s) 16 31 58" src="https://user-images.githubusercontent.com/16530364/65353718-39204580-dbc4-11e9-9734-59b3b2ceaa50.png">
<img width="533" alt="Captura de Pantalla 2019-09-20 a la(s) 16 32 05" src="https://user-images.githubusercontent.com/16530364/65353728-3aea0900-dbc4-11e9-945e-1aea877c893e.png">

**Comment by proceps** [comment]
![Screen Shot 2019-09-20 at 2 38 37 PM](https://user-images.githubusercontent.com/5597748/65354163-6bc24200-dbb4-11e9-8a92-829b987f179c.png)

**Comment by proceps** [comment]
![Screen Shot 2019-09-20 at 2 40 58 PM](https://user-images.githubusercontent.com/5597748/65354257-afb54700-dbb4-11e9-9799-506df8ef9e0e.png)
Same deselected (but there is a default value)

**Comment by proceps** [comment]
may be need to clean browser cache?

**Comment by jlpereira** [comment]
Yes, definitely. If the problem persist probably you have a problem with your folder, bad merge or something like that I suppose. I already tested in FF and Chrome, both works fine for me

**Comment by proceps** [comment]
this is after cache cleaning. I checked firefox. Which I practically never use. Same picture

**Comment by mjy** [comment]
Dima you might wipe your JS cache (files, not browser) completely- you've
been having problems with webbrick

**Comment by jlpereira** [comment]
@proceps follow this steps:

1- Stop rails
2- Go to public folder, and remove packs and assets folders.
3- Starts rails again

Let me know if that fix the problem

**Comment by proceps** [comment]
Yes, that what we did with Matt, seems to work...

**Comment by proceps** [comment]
tooltip show up but it is not informative,  "used on number of unidentified objects" please provide the count (the same as for tags)

**Comment by mjy** [comment]
The text is slightly wrong, but we will cap the count to make the response faster, it should read `Used on over 200 objects`.  Some tags are used 10k+ times, the exact number doesn't mattter.

**Comment by proceps** [comment]
I would prefer to see exact count. It is a simple Count query.
