### ISSUE TITLE
An ActiveRecord::StatementInvalid occurred in filter#set_id_range:

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1043]
Collection object filter error.

**Comment by mjy** [comment]
This is the user facet.

**Comment by LocoDelAssembly** [comment]
Is https://github.com/SpeciesFileGroup/taxonworks/issues/1044 same problem?

**Comment by LocoDelAssembly** [comment]
Probably https://github.com/SpeciesFileGroup/taxonworks/issues/1049 same problem as well.

**Comment by mjy** [comment]
I have this fixed on another branch.

**Comment by mjy** [comment]
Well- at least the primary, not sure about 44, 49

**Comment by mjy** [comment]
New filter addresses this.
