### ISSUE TITLE
Task - New combination - set as current placement

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1045]
When I create a new combination Aus (Bus) aus
A button set as current sets parent of aus as Aus (Aus), and not Aus (Bus)
Aus (Bus) should be set up as a parent of the species

if I save Aus (Aus) aus and set it as a current combination. the parent set up properly.

**Comment by mjy** [comment]
What if Bus i not current under Aus?

**Comment by proceps** [comment]
Well, this is up to user to define if this is current or not. I would say Bus should be set up as a parent of species. Problem now, the system sets completely different parent. Even when Bus is under Aus. If you want to be safe, it could be verified that Bus is under Aus before setting the parent.

**Comment by mjy** [comment]
@proceps, there have been changes I think?  Status?

**Comment by proceps** [comment]
Not resolved.

**Comment by proceps** [comment]
I hit this again, thought it is already fixed:
* I have species Arboridia surstyli with Arboridia (Arborifera) as the parent (originally described in different genus).
* I created a new combination Arboridia (Arborifera) surstyli and saved
* I was suggested to change the parent to Arborida (see the picture), although the parent was already properly set previously
* When I clicked the button, the parent was changed to Arboridia (Arboridia) - the wrong one, not Arboridia (Arborifera).
![image](https://user-images.githubusercontent.com/5597748/78463214-d09c4000-769f-11ea-834b-f7501b4e286e.png)

**Comment by mjy** [comment]
@jlpereira here we need to set the parent to always the second most from the left

**Comment by jlpereira** [comment]
Could you check again @proceps and let me know If this fix the problem?

**Comment by proceps** [comment]
When I did a combination Genus (Genus1) species, I am getting a button "Move species to species". Clicking the button changes nothing. So it tries to move parent to self?

**Comment by jlpereira** [comment]
Pushed new fix, @proceps

**Comment by proceps** [comment]
This works, but I am back to previous issue now. When I create combination like "Genus (Genus) species". The button sets to "Genus" not to the subgenus (the second from the last). When I click the button. the parent sets to the genus. If I refresh the combination page, the button comes back and now say to "set parent to species"

**Comment by jlpereira** [comment]
Aha, i see.

Pushed again @proceps

**Comment by proceps** [comment]
Now, I have the same combination, the species is already in the genus, but not in the subgenus. And the button suggesting moving species to subgenus is missing. When I tried a new species, it was moved to subgenus properly

I created the combination Genus species for the previous species, and I do not have a button again.

So we have several scenario:
1. Species moved to "Genus (Genus) species"
2. Species moved to "Genus (Subgenus) species"
3. Species moved to "Genus species species"
4. Subspecies moved to "Genus species subspecies"

And opposite. Subspecies moved back to species level. Subgenus moved back to Genus level.
In all cases the parent should be the second from the last. If the parent is different, the button should offer the transfer.

**Comment by mjy** [comment]
@proceps can you mock examples with ids and before/after?  We're still stumbling here.

**Comment by proceps** [comment]
So, when I have both genus and subgenus in the database, I almost always use subgenus as a target for both genus and subgenus in the combination, if they are the same.

So exampls:
1. Combination Subgenus (Subgenus) species. Expected parent - Subgenus
2. Combination with the same genus but different subgenus will be:
                      Subgenus (Another Subgenus) species. Expected parent - Another subgenus
3. Combination Genus Species is straightforward. Expected parent - Genus
4 combination Genus species subspecies - expected parent - species.

When the move button is generated, it should check if the parent is the same as the second from the last element of the combination, if it is different, offer the change.

**Comment by mjy** [comment]
@proceps You mean `Genus (Subgenus)` above, not `Subgenus (Subgenus)` right?

**Comment by jlpereira** [comment]
I think we have 2 issue here.

1 - The taxon is not moving to the correct parent.
2 - The button is still visible after moving the taxon to the new parent

Pushed another fix, let me know if one of this issue is solved @proceps

**Comment by jlpereira** [comment]
> So, when I have both genus and subgenus in the database, I almost always use subgenus as a target for both genus and subgenus in the combination, if they are the same.
> 
> So exampls:
> 
> 1. Combination Subgenus (Subgenus) species. Expected parent - Subgenus
> 2. Combination with the same genus but different subgenus will be:
>    Subgenus (Another Subgenus) species. Expected parent - Another subgenus
> 3. Combination Genus Species is straightforward. Expected parent - Genus
>    4 combination Genus species subspecies - expected parent - species.
> 
> When the move button is generated, it should check if the parent is the same as the second from the last element of the combination, if it is different, offer the change.

Now im little confused with point 1 and 4. Both have 3 taxon but different parent position. 
In the first example, the expected parent will be Subgenus or (Subgenus) ?

**Comment by proceps** [comment]
@jlpereira When I have two TaxonNames with the same name but different rank (genus and subgenus) for example "Zygina" and "Zygina (Zygina)". I have an option which one to select as a label for the genus and subgenus relationships in the combination. So if I have a combination "Zygina (Zygina) alba", I select "Zygina (Zygina)" in both relationships for the genus and for Subgenus. It does not matter which one you select. Each of them will bring the label Zygina for appropriate rank. For me this is just matter of consistency. I try to select the same taxonnameID for each selection where it is possible. In the example 1. Last element - the species - is the taxonName to modify,  Zygina (Zygina) second element before last, it is the new parent for the last element.
Example for "Zygina alba macroptera". This also has 3 elements: genus, species, and subspecies. The taxon name to change the parent is "macroptera", the parent is the second element from the right - "Zygina alba". There is no really two issues. Just the system identifies the wrong New parent taxon.

**Comment by mjy** [comment]
@proceps This isn't working.  We need numbers, not explanations.  Please provide a table with the following data, one row for every possible different combination we are working with.

* genus
  *  id of genus
  *  parent_id of genus
* subgenus
  * id of genus
  * parent_id of genus
* species
  * id of species
  * parent_id of species
* subspecies
  * id of subspecies
* current_name
   id of current name
   parent_id of current name
* show button (true or false)
* parent_id to used when button is clicked

**Comment by proceps** [comment]
Tribe Eritroneurini - id 1
Genus Erythroneura - id 2 - parent - 1
Genus Zygina - id 3 - parent 1
Subgenus Zygina - id 4 - parent 3
Species alba - id 5 - parent 2
Subspecies macroptera - id 6 - parent 5

1) I create a new combination Zygina (Zygina) alba
genus in combination - id 4, subgenus - 4, species - 5
New parent for alba (id 5) - id 4, Button to "move alba to Zygina (Zygina)"

2) I create a new combination Erythroneura (Zygina) alba
genus in combination - id 2, subgenus 4, species 5, Proposed new parent for 5 is 4 - Zygina (Zygina)

3) New combination Zygina alba macroptera
genus in combination id 3, species 5, subspecies 6, Proposed new parent for 6 is 5 - Zygina alba

Button is visible when the current parent for the last element is different from the proposed new parent (an element of the combination before the right.) It is visible in all examples.

4) New combination Erythroneura alba
genus in combination id 2, species - 5, proposed new parent - 2, same as present, the button is not visible.

**Comment by jlpereira** [comment]
Pushed again, @proceps

**Comment by proceps** [comment]
<img width="653" alt="Screen Shot 2020-04-24 at 3 06 46 PM" src="https://user-images.githubusercontent.com/5597748/80252660-4c553100-863d-11ea-8ca1-4ced47963f38.png">
Wrong label should be "move doricarni to Zygina (Hypericiella)"
The button does not work. Nothing happens. No error messages.

**Comment by jlpereira** [comment]
I think this could be related a protonym order from the response. Just to clarified:

This is the combination?

Zygina Fieber, 1866 (genus)
Zygina (Hypericiella) Dworakowska, 1970 (subgenus)
Erythroneura dorycnii Ribaut, 1936 (species)

**Comment by proceps** [comment]
Yes, this is correct. I am experimenting on the practice database. I do not need really move it.

**Comment by jlpereira** [comment]
Perfect, I pushed a sort order, im pretty sure it was that. Let me know

**Comment by proceps** [comment]
Mostly works now!
but tried this one:
<img width="659" alt="Screen Shot 2020-04-24 at 4 04 59 PM" src="https://user-images.githubusercontent.com/5597748/80256981-83c7db80-8645-11ea-8071-eda2554d3a84.png">
The label should be "Move to Zygina (Hypericiella) hyperici". I understand the label could be tricky. But the link does not work. Subspecies is not moved to "hyperici" as a parent.

**Comment by jlpereira** [comment]
Could you provide me the exact combination? Taxon name, author, rank and the position rank for the combination

**Comment by proceps** [comment]
The combination string:
Zygina (Hypericiella) hyperici bicornis
genus Zygina (Zygina) Fieber, 1866 (376430)
subgenus Zygina (Hypericiella) Dworakowska, 1970 (376412)
species Zygina (Hypericiella) hyperici (Herrich-Schäffer, 1836) (376420)
subspecies Zygina (Hypericiella) bicornis Dworakowska, 1981 (376414)

**Comment by jlpereira** [comment]
Pushed again, I think the button label should be okay now. But im not sure you could use it

Zygina (Hypericiella) hyperici (Herrich-Schäffer, 1836)
Zygina (Hypericiella) bicornis Dworakowska, 1981 (376414) 

Both are species, same rank. So I dont think its gonna be possible assign hyperici as parent of bicornis. Im missing something here?

**Comment by proceps** [comment]
Yes, you are right, I did not think about it. I will be able to use it if I move subspecies from one species to another. If it works in 90% of cases it is great. And as long as it does not assign the protonym to a wrong parent. Maybe an error message, the species cannot change the parent, or something will work. But I am closing the issue for now. Thanks.
