### ISSUE TITLE
Collection object filter - endlessly processes

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1049]
**Describe the bug**

When I attempt to search by identifier ranges, some namespaces work (e.g. Coleoptera, Odonata) and return results, and others endlessly spin and never return results (e.g. Araneae, Insect Collection).

**To Reproduce**
1. When I  go to the task "Filter - Collection objects by area and date range".
2. Then I try to filter results by "Select Identifier Range"
3. And I select "Araneae" or "Insect Collection" and set the identifier range to 0-100.
4. The subsearch never produces results, but just spins. 

![image](https://user-images.githubusercontent.com/11411328/64555906-f927ab80-d303-11e9-8a27-e5ad0f76f198.png)

**Expected behavior**
It produces results with Coleoptera and Odonata, but not with Insect Collection or Araneae.
![image](https://user-images.githubusercontent.com/11411328/64555873-e0b79100-d303-11e9-8461-1614ff9ce49b.png)

The subfilter should complete the search before I click the "Find" Button to list the results.

**Environment (please identify where you experience this bug:**
- Sandbox - Sandworm
- Chrome

**Comment by mjy** [comment]
Possibly related: https://github.com/SpeciesFileGroup/taxonworks/issues/59

**Comment by mjy** [comment]
All new filter code is live, reopen if new similar problem exists.
