### ISSUE TITLE
Task - New image - add depicted object radial annotator for each image

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1050]
Add a second radial annotator, this for the depicted object, below the image annotator.  This will let folks drop additional images onto, say, a collection object.

<img width="1140" alt="Screen Shot 2019-09-09 at 4 32 20 PM" src="https://user-images.githubusercontent.com/22600/64568079-790f3f00-d31f-11e9-9630-d254f506ea64.png">

**Comment by jlpereira** [comment]
The dropzone here its use to create image objects, not depictions

**Comment by mjy** [comment]
Seems like we might need an Image radial akin to our Otu radial?  Options for using that Image quickly 

Image -> Modal -> Here's the depictions -> add another image to this object ...

**Comment by jlpereira** [comment]
This is now accessible from Radial object -> Depictions slice
