### ISSUE TITLE
Task - edit TaxonName - rank prediction

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1054]
make rank prediction little bit more smart.
If the iczn name ends with "-idaea" it should be superfamily
If the iczn name ends with "-idae" it should be family
If the iczn name ends with "-inae" it should be subfamily
If the iczn name ends with "-ini" it should be tribe
If the iczn name ends with "-ina" it should be subtribe

**Comment by proceps** [comment]
@jlpereira I build a method Protonym.predicted_child_rank(string) which should return more precise rank of a child, after the TaxonName.name and TaxonName.parent are selected. Could you try to embed this into Edit TaxonName form?

**Comment by mjy** [comment]
This will need a new endpoint, and require another database call slowing things down slightly.

**Comment by proceps** [comment]
This script works only when a new protonym is created the first time. It is very fast, practically not depending on the DB call. But it saves time when you do not need to redefine the proper rank of the taxon.

**Comment by proceps** [comment]
This script works only when a new protonym is created the first time. It is very fast, practically not depending on the DB call. But it saves time when you do not need to redefine the proper rank of the taxon.

**Comment by mjy** [comment]
The point is the task itself runs no Ruby code, it only makes calls to the API.  Therefor we can do one of:
* Make an API request to call your Ruby code and return a JSON respons
* Rewrite all your code in Vue/JS

**Comment by mjy** [comment]
The point is the task itself runs no Ruby code, it only makes calls to the API.  Therefor we can do one of:
* Make an API request to call your Ruby code and return a JSON respons
* Rewrite all your code in Vue/JS
