### ISSUE TITLE
Task - New Task - Browse Loans [edited]

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1057]
We need a task to browse loans so they are displayed properly 
~~and so we can search for a subset of loans (e.g. all loans made to a specific individual, or all overdue loans)~~ new issue created #2127

~~Possibly merge with List Overdue Loans task?~~ new issue created #2127

**Comment by tmcelrath** [comment]
Can we also add a "Generate DWCA or CSV of Loaned Items" button?

**Comment by tmcelrath** [comment]
Related to #2123 - also the "Generate DWCA/CSV" of loaned items is high priority. DIfficult to do otherwise right now.

**Comment by mjy** [comment]
Filter was done in #2124

**Comment by mjy** [comment]
Closing as complete via loan-based filtering.
