### ISSUE TITLE
taxonworks:task generator should update user_tasks.yml to reflect the purpose of the task.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#106]
When the taxonworks:task generator modifies the user_tasks.yml file, it currently ignores information about what the task is to do (from the generator). It can, and should, update the newly added entry with information given to the generator.

**Comment by mjy** [comment]
There are two fields that could be populated, but we don't have params for them.  I think this isn't worth pursing.
