### ISSUE TITLE
User productivity stats - could be implemented on individual models, or on entire dataset.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1062]
This is a vb code used to calculate productivity of users working on the collection database.
Productivity is defined as number of specimen records entered to the database during one hour period. Total working time is calculated as time between the first and last records (CreatedOn) during period of time + 5 min (assuming that at least 5 min is required to create one record). So if you have only one record during the period, you spent 5 min on the database.

One period is calculated as set of consecutive data entries which are not separated from each other more than 60 min. So if you have 2 records in the database with interval of 45 min, the total work time will be 50 min. Two records with interval of 70 min produce two working periods 5 min each, the total work time is 10 min.

Example of statistics: 
![image](https://user-images.githubusercontent.com/5597748/64810391-eeb61d80-d560-11e9-99a6-17e6bbd7cf85.png)

Original vb script:
         objCmd.CommandText = "SELECT CreatedOn FROM dbo.tbl3iCollectionSpecimensNew WHERE CreatedBy = @myParameter ORDER BY CreatedOn DESC"

         objCmd.Connection = objConn
         objConn.Open()
         Dim dr As SqlClient.SqlDataReader = objCmd.ExecuteReader

         Dim dtable As New DataTable
         Dim row As DataRow
         Dim n, nTotal, minute, timeDif, recMax As Integer
         dtable.Columns.Add(New DataColumn("Date/Time", GetType(String)))
         dtable.Columns.Add(New DataColumn("Records", GetType(Integer)))
         dtable.Columns.Add(New DataColumn("Hours", GetType(Double)))
         dtable.Columns.Add(New DataColumn("Minutes", GetType(Integer)))
         dtable.Columns.Add(New DataColumn("Records/Hour", GetType(Integer)))
         dtable.Columns.Add(New DataColumn("Width", GetType(Integer)))
         Dim dateStart, dateEnd As Date
         n = -1
         nTotal = 0
         Do While dr.Read
            n += 1
            nTotal += 1
            If dateEnd = Nothing Then
               minute = 5
               dateEnd = CDate(dr("CreatedOn"))
            Else
               timeDif = CInt(DateDiff("n", CDate(dr("CreatedOn")), dateStart))
               If timeDif > 60 Then ' max time in between consecutive records.
                  row = dtable.NewRow()
                  row("Date/Time") = Format(dateStart, "MM/d/yyyy h:mm tt") & " - " & Format(dateEnd, "h:mm tt")
                  row("Records") = n
                  row("Hours") = CInt(minute / 6) / 10
                  row("Minutes") = minute
                  row("Records/Hour") = CInt(n * 60 / minute)
                  dtable.Rows.Add(row)
                  If CInt(n * 60 / minute) > recMax Then recMax = CInt(n * 60 / minute)
                  n = 0
                  minute = 5
                  dateEnd = CDate(dr("CreatedOn"))
               Else
                  minute += timeDif
               End If

            End If
            dateStart = CDate(dr("CreatedOn"))
         Loop
         lblTotalNumberRecords.Text = CStr(nTotal)
         If nTotal = 0 Then Exit Sub
         If dateStart <> Nothing Then
            n += 1
            row = dtable.NewRow()
            row("Date/Time") = Format(dateStart, "MM/d/yyyy h:mm tt") & " - " & Format(dateEnd, "h:mm tt")
            row("Records") = n
            row("Hours") = CInt(minute / 6) / 10
            row("Minutes") = minute
            row("Records/Hour") = CInt(n * 60 / minute)
            dtable.Rows.Add(row)
            If CInt(n * 60 / minute) > recMax Then recMax = CInt(n * 60 / minute)
         End If

**Comment by proceps** [comment]
We have nice implementation of this calculating total amount of time spent on the DB. I would like to extend it to keep track of work periods of hourly employees. When the system stores working periods for each person. Inactive time of 1 hour was proved as a good breackout (see the diagram above).

**Comment by mjy** [comment]
Confirming that  you see this for colleciton objects @proceps, it's implemented there.

**Comment by proceps** [comment]
where can I see it?

**Comment by proceps** [comment]
Can we also visualize the time spent on project for each member of the project (when I go to the project overview page)

**Comment by proceps** [comment]
Ok, I got a report page. Is it just based on "created_at" values? Or it is using the same metrics as user activity?

**Comment by mjy** [comment]
It is using your algorithim. It is not the same as activity.

**Comment by mjy** [comment]
Yes, quite easily.  But note that batch uploads break all this (e.g. DwC) unless we include origin relationships for all of them (which we do for DwC, so in theory we could exclude those records).

**Comment by proceps** [comment]
Well, ask for a date range, so it should not be matter in a longer run.
So I would like to add:
1. User activity stats and add this to the list of people in project (yes, this will show the totals stats if the person is signed in more than one project; may be to put an asteric for such users).
2. Exted the "Collection work report interface" to add a model picker at the top. (potential models: asserted distribution, biological associations, observations, taxon_names).
