### ISSUE TITLE
Bug - Task - Filter collecting events - can't double click on filtered event if no specific locality given

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1064]
**Describe the bug**
If no specific locality is given (e.g. it's a poorly defined collecting even) then no blue "Verbatim Locality" text appears, and I can't click on it to "Go to" that collecting event.

**To Reproduce**
1. When I use the "Filter collecting events" task and search by any parameters (e.g. date range of "4/20/1886-4/20/1886").
2. Then I get a set of results below.
3. And I try to click on one of the collecting events that has a blank "Verbatim Locality field"
4. I can't click on it, or double click, I have to use radial annotator to "show" record. 

Clicking on first returned record does nothing:
![image](https://user-images.githubusercontent.com/11411328/64871364-b79c4680-d60a-11e9-9529-e940efc8877c.png)

"Shown" collecting event:
![image](https://user-images.githubusercontent.com/11411328/64871417-d995c900-d60a-11e9-9112-6f8235ba9e89.png)

**Expected behavior**
I should be able to go to that record by double clicking or there should appear some blue text that I can click on. 

**Environment (please identify where you experience this bug:**
- Sandbox - Sandworm
- Chrome

**Comment by mjy** [comment]
@jlpereira Can you move the link out to the ID to fix this?
