### ISSUE TITLE
Non administrator account

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1066]
Many forms in TaxonWorks have an error message "Please sign in as a project administrator or administrator."  if a user has non administrator status.
Tasks where it was seen:
Matrix row coder
Simple type specimen
Collection object browse

**Comment by jlpereira** [comment]
That message comes from the backend. Steps to replicate?

**Comment by mjy** [comment]
Still a problem?  Need exact steps to replicate if so.

**Comment by proceps** [comment]
Once production is updated we will check. Replication is easy. On any of those mentioned task, any save operation trigger the message once you log in using an non administrative account.

**Comment by mjy** [comment]
@proceps haven't seen this for very long time, close?
