### ISSUE TITLE
Task - nomenclatural stats - Combinations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1069]
Do not break stats for valid and invalid combinations. This does not make much sense.

**Comment by mjy** [comment]
Will have to refactor back end.

**Comment by proceps** [comment]
we have all combinations in a single field now, but still have two columns (valid combinations and invalid combinations). please make just one column (combinations)

**Comment by proceps** [comment]
related to #1356

**Comment by mjy** [comment]
@proceps we can close this?
