### ISSUE TITLE
Task - Observation matrices dashboard

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1070]
The response is slow (in development, could improve somewhat in production).
I would suggest to remove auto-update when the rank is selected, and add Update button.
Keep auto-update on a TaxonName selected.
When a new TaxonName is selected, do not clear previously selected ranks.

**Comment by mjy** [comment]
How big a result are you talking about?

**Comment by proceps** [comment]
Subfamily Deltocephalinae or Typhlocybinae in 3i database. Each group is 5000-8000 species. Typhlocybinae have about 1000 taxa with scores. Deltocephalinae have about 500 taxa with scores. About 100 characters per species.

**Comment by mjy** [comment]
I think when you get the feel for what is slow or not this is not an issue.  I want quick responses for most queries, and can wait for slow if I ask for something very large.  Rendering 5k rows is going to take time, and if I ask for 5k species I can wait.  Most often I will ask for something much smaller. Asking for something big will also be rare.

@jlpereira are we showing the spinner on this interface?  Can we make sure that the user can not trigger two concurent searches?

**Comment by jlpereira** [comment]
Yah, we´re showing the spinning everytime the user picks a rank. So i think it shouldn't be possible to select another one before the request finished

**Comment by proceps** [comment]
I do not complain that it is slow. I am saying that I have to wait for initial result. That I have to click on genus, and wait for results for the genus. Than I have to wait for species. That I have to make selection for rows, and wait it again. All I am saying, that I can make all selections, and than submit for a new result. As well as when I select a new taxon, the search should preserve the previous options.
