### ISSUE TITLE
Task - Observation matrices dashboard - Code

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1071]
Change the button label "Select Matrix" to "Add OTU to Matrix" or something similar.
It is not obvious that using this option automatically adds OTU to the matrix. It should be self explanatory. Although the feature is great.

**Comment by mjy** [comment]
I thought It does NOT automatically add it to the matrix.  You have a
second step when you need to agree.

**Comment by proceps** [comment]
Yes, there is a second step, which still was not obvious for me, that it will bounce me to the row coder. And than I noticed that otu was added to the matrix, even so, I did not do any scores.

**Comment by mjy** [comment]
One TaxonName can have many Otus, thus another step you might not have seen yet in that API.  Of course if we use the MRC we have to have a row defined (matrix).  I'm not seeing the point of you accepting to add a row to a matrix, then having it removed if you don't code- or maybe I don't understand. Why else would you go to the row, when you know the number of observations etc.?
