### ISSUE TITLE
Task - Filter Collection Object (refactor)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1073]
# Biocuration 

* [x] Smart selector with biocuration types, user can click various on off, added to list; param is `biocuration_class_ids[]=`

# Biological associations

_We need fucntionality identical to the 2 nomeclature filter Taxon name relationship facets._

* [x] Biological relationship facet 
* [x] In biological relationship - double check param is `biological_relationship_ids[]=`

# Identifier
* [x] In range fields are string input, not dates
* [x] Add section "Identifiers"
* [x] Add input 'Value' (param `identifier`)
* [x] Add Boolean "Match" - 'Exact', 'Partial', param `identifier_exact`
* [x] Add Subsection 'In range'
* [x] Add fields 'Start', 'End', with params `identifier_start`, `identifier_end`
* [x] Add Subsection 'Namespace'
* [x] Add Namespace smart selector (only one value selected), param is `namespace_id`

# Tags

* [x] Add header "Tags"
* [x] Add Keyword smart selector, multiple keywords can be selected.  
* [x] Update keyword smart selector to use CVT color in some way (if it doesn't already)
* [x] param is 'keyword_ids[]='
* [ ] Add top level option (Seomwhere top right) to Tag all in this set with Default keyword

# Determinations
* [x] " Both valid" => " Both valid/invalid"
* [x] Remove "Include descendants" boolean under Determinations
* [x] Add radio button where "Invlude descendants" was- "Current/historical", options "Both", "Current only", "Historical only".  nil, true, false to param `current_determinations`
* [x] Add 'Taxon name' sub header under Determinations
* [x] Add TN Autocomplete, selects only one name, param is `ancestor_id`
* [x] Add radio button below autocomplete "Linked to" `Both valid/invalid`, `Valid only`,  `Invalid only`, values are nil, true, false for `validity`

# "User"

* [x] Add a "--None--" to User list, if selected it unsets dates, and locks both dates and target radio
* [x] Add "Target" and radio buttons "Created at", "Updated at", default to created, disabled until user is selected
* [x] Disable date range until user is selected
* [x] Params: `user_id`, `user_target` (one of 'created', 'updated'), `user_date_start`, `user_date_end`

# Collecting event
* [x] Replace 'exact' with 'Partial', change param name to be `collecting_event_wildcards[]=`

# Misc
* [x] Bind `ctrl-s` to Search button (or whatever key we've been using); Include a `ctrl-r` or similar to reset
* [ ] Disable "Search" until at least one facet has been populated? Not sure worth tracking though...
* [x] Spinner *not* covering whole result should be at top of page- maybe spinning besides a result counter that +1s up as the results load?
* [ ] Place count result at top of result page
* [x] Increase max to 1k 
* [ ] Download CSV button (csv to start, DWCA version if we can get the binding to DWCA table)
* [x] "No results" should display prominently on the screen if none returned
* [x] shapes drawn on map do not persist
* [x] instructions on map overlap shapes in distracting way.
* [x] User list does not display
* [x] Rename "Select user and date range" to "User"
* [x] Create a new sub-section "Collecting Event", move "Select date" to there and rename "Date range".  If built correctly everyting in this subsection should be a component for the CE filter (or we take from CE and put here).
* [x] Add Collecting Events facet - select one or more collecting events (passing their Ids to `collecting_event_ids` from a smart selector
* [x] Add Boolean `Collecting events are spatial`
* [x] Change `Otu` to `Determinations`, add a sub header "Otu" above the OTu selector, move descendants check below OTU autocomplete list

**Comment by mjy** [comment]
Initial competency questions (keep to under 10, these are all "AND" facets):
* What are the specimens collected in this date range
* What are the specimens collected for this taxon
* What are the specimens collected in this area
* What are the specimens collected by this collector (person)
* What are the specimens collected in this catalog number range
* What are the specimens collected in this collecting event(s)
* What are the specimens collected in this nomenclatural range
* What are the specimen on loan

**Comment by proceps** [comment]
[*] What specimens has this biological association
 [*] Show type specimens
 [*] Search for particular data attributes

**Comment by mjy** [comment]
Closing for individual issues at this point:
* #1315 
* #1316
