### ISSUE TITLE
Task - Browse taxonomy - Radial object - edit

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1088]
Both Browse nomenclature and Edit nomenclature, when you use Radial object and click edit it links to Edit nomenclature task and not Edit Taxon name (in Data). Please return the proper link. The link to Edit nomenclature is already exists in Radial.

**Comment by mjy** [comment]
Wait- we wanted the opposite prior, and we built significant tooling to make it so we could customzie this.  Why are we reverting this?

**Comment by proceps** [comment]
because this is the only way to change verbatim...

**Comment by mjy** [comment]
You mean getting to Data card for taxon name, right?

The vast majority of other uses have people wanting to get to the "default" editing spot.  I *know* we changed this based on request to have it go to Browse/edit nomenclature tasks.
