### ISSUE TITLE
As a DevOp I need a "download" infrastucture to server users files

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1093]
When a user makes a request, then they may generate a file and need to download that file.  At times a Ruby temporary file is not useful because of delays in generating the file, requesting the file, etc.

The process is roughly:

* User hits an endpoint (or DevOp triggers a rake task, for example)
* Endpoint (controller action) runs code (does stuff)
* Code triggers a job (maybe a "delayed job")
* Job finishes, in the process it deploys a file, and indexes it in a table
* User is emailed or notified that there is a file with their data available
* After period X file is wiped by
  * a cron job
  * a second delayed job (application) being triggered
* When the file is wiped, the index table is updated to remove the pointer to the file

## Bits to implement

* [x] Create a "downloads" Model (I suppose other names are possible that reference "file" specifically)
  * Fields  might be something like this:
      * job (an app generate name for the "process" that generated this file)
      * request (the request that generated this process)
      * filename
      * destroy_at (Timestamp)
      * times_downloaded (Integer) (used to check for backup cron job?)
      * <housekeeping fields>
      * project_id
      
* [x] Revisit what's going on in our delayed jobs, ensure they are firing, etc.
* [x] Ensure we have the process of writing temporary files, tar/zipping them and serving them worked out (perhaps a lib/utilities/zip.rb library with methods that take an array of file pointers)

### Devops
* [x] Update app to include a `downloads` directory, akin to `public`
* [ ] Create a cron job(?) to backup process

**Comment by mjy** [comment]
@LocoDelAssembly Can we close and add specific items to enhance what we have?

**Comment by LocoDelAssembly** [comment]
@mjy updated check list. The remaining item (backup) can be discussed outside this issue.
