### ISSUE TITLE
Task - Comprehensive digitization - radius type georeferences fail

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1094]
When I create several georeferences in the interface, then I attempt to add a point/radius (circle), then the spinner locks after the response is a `422 Unprocessable Entity `.

**Comment by jlpereira** [comment]
Works, the problem is other. "{"error_radius":[" must be less than 10 kilometers (6.6 miles)."]}"
Can we fix this? or the limit its okay? because in that case we should display a error message when the shape its not created

**Comment by mjy** [comment]
@jlpereira The radius can't be bigger in TW (it doesn't make sense), we should fail and report the message.

**Comment by mjy** [comment]
Working in new filter code.
