### ISSUE TITLE
Task - Observation matrix dashboard - Select matrix button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1096]
Expected behavior, When I select taxa and click "Select matrix" button for a taxon which already have scores, I would like first to see buttons with the matrix names, when this taxon is already added as a row, and then present a long list of other projects, if I want to add OTU to one of those. In most cases the OTU is already added to one of the matrices, I would like to have a quick navigation and not to search the right matrix in a long list, this will help prevent adding otu to a random matrix by mistake.

**Comment by jlpereira** [comment]
Take a look the new changes @proceps 
Let me know if it need more changes

**Comment by proceps** [comment]
I was originally thinking about blue button with the matrix name at the top, text to the search box, because usually it is only one or two matrices. But this may also work.
