### ISSUE TITLE
Task - Observation matrix hub - view link

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1097]
Why view link is available not for all matrices?
Any alternative way to access the nexus and TNT download?

if the View is available for the matrix, The TNT and Nexus download do not work.

**Comment by mjy** [comment]
This technically is not a bug, the view link was only provided for matrices of a certain size.  We did this to get something quick, without dealing with optimizing matrix viewing.

I think we should add downloads to the matrix hub, then you could access them regardless of whether they can be viewed.

In mx we used a windowed viewer, which let us see small sections of huge matrices.  We plan to implement that in the future.
