### ISSUE TITLE
Task - New taxon name - predictive non latin popup (was: How to enter an incorrect original spelling of a species name (diacritics, numbers, hyphen, space)?)

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1101]
If I want to enter such a spelling as a New name, a red message says "Name must be latinized, no digits or spaces allowed". Under Data > Taxon names > New, where a field vor Verbatim name is available, it creates a duplicate of the emended spelling.

**Comment by mjy** [comment]
@typophyllum You can only add non-latinized text if there is a invalidating status applied to the name, so this is a known chicken/egg issue.  

* There is a work around though- add the name as it's correct latin form (duplicating the name)
* Add the "Not latin" status under "Status"
* Update the name to the non-latin form.
* Add a relationship pointing this name to the latinized protonym.

A hack, but hopefully not too intrusive vs. the number of times it has to be done.  We will propbably add a checkbox or some such that says "Not latin", and this would add the status at time of create.

**Comment by mjy** [comment]
Agreed.

**Comment by mjy** [comment]
We have come up with a way to be unintrusive I think.
When you submit a non-latin name, then the interface will show a message (not latin), and it will prompt with a modal that says "Create this name and apply the non-latin status".  When you agree the name will be resubmitted with the status.

This way we will not clutter the interface with a checkbox that is 99% of the time not used.

**Comment by typophyllum** [comment]
Sounds good. This could replace the current error message.
