### ISSUE TITLE
Enhancement: remove soft enhancement loop in misspelled names

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1114]
Enhancement: soft validation loop for misspelled names
If taxon name is given: “misspelling of” relationship and an author role.
Then the “Taxon name author role is not required for misspellings and misapplications” soft validation appears.
And author role is removed.
Then “Taxon name author role is not selected” soft validation appears - and if added, the previous 
And it repeats.

**Comment by proceps** [comment]
It is on my list.

**Comment by proceps** [comment]
fixed
