### ISSUE TITLE
Model - TaxonName: Parenthood changes option to generate historical combinatoin

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1116]
When I move a name, then I want the option to record the prior combination.

E.g.:

* [ ] I select a new parent for an existing (already saved) name.  I am prompted prior to save to "Create historical combiantion?", with option to provide prior source (or infer prior source)

See implementation possibility in #1113

**Comment by mjy** [comment]
@proceps Can you chime in on this idea?  I think we have this option built in on some soft validation fixes?

**Comment by proceps** [comment]
It is already in the model, but something blocks it from automatically firing. I have to investigate this. The idea was to check if the combination (or original combination) does not exist to automatically create it every time you change the parent.
I would personally prefer a solution described in #666. A section similar to original combination. A button create a combination from a current placement will be an explicit and convenient solution. At the moment I am using the backward approach. I create a new combination, and use a button, to use it as a current placement.

**Comment by mjy** [comment]
Same as #1449

**Comment by proceps** [comment]
implemented now as a soft validation
