### ISSUE TITLE
Model - Serials - Uniquify serials

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1117]
We need a model for uniquifying serials.
Need to account for:
- name changes of same serial
- presence/absence of "The"
- Publication data - e.g. "The Coleopterists Bulletin" was "The Coleopterist's Bulletin" during certain date ranges but should be the same continuing publication. 
- Things like "Series A" and "Second Run"

Considerations: similar serials task.

**Comment by mjy** [comment]
Closing for https://github.com/SpeciesFileGroup/taxonworks/issues/970
