### ISSUE TITLE
Task - New Source

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1118]
`New source` will contain identical functionality to Data -> new and also add:

* [x] Ability to sort field order as user preference
* [x] Clone source for created source
* [x] Smart selectors for authors/editors, with blue pin options
* [x] Smart select for serial, with blue pin option

Bonus:

* [x] Real time prediction of existing matches
* [ ] Real time lookup from other APIs (Crossref, Zookeys (if Zookeys detected) etc.

**Comment by proceps** [comment]
combine this task with "New source from citation".

**Comment by mjy** [comment]
* [ ] Drag/drop target for PDFs etc. ('Drop document')

* [ ] Serials smart selector
* [ ] Language smart selector

Locks
* [ ] Lock BibTeX article type
* [ ] Lock Language
* [ ] Lock Serial

Hotkeys
* [ ] Same save/lock-all/unlock-all pattern as per digitize

**Comment by mjy** [comment]
Closing this for individual features.  Thanks much @jlpereira, it's looking cool.
