### ISSUE TITLE
Task - Uniquify Serials

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1119]
I want to be able to uniquify similar serials while preserving slight variations in serial names so that I can search by them. Have flag/warning for linking "preceded by" and "succeeded by" relationships.

**Comment by proceps** [comment]
related to #1117

**Comment by proceps** [comment]
I need this functionality too

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/970.
