### ISSUE TITLE
Enhancement: Task - Browse OTU asserted distributions - include option to view coordinated OTUs

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1122]
When I'm in task: Browsing Asserted Distributions, I want a toggleable option to also view  coordinated OTU asserted distributions under the "valid" or "main" OTU when browsing. 

Use case: I want to add asserted distributions to taxa that are now synonyms, but then view those asserted distributions when I'm browsing the valid name.

**Comment by proceps** [comment]
is it resolved in Browse OTU interface?

**Comment by tmcelrath** [comment]
Not sure, needs testing.

**Comment by proceps** [comment]
distribution of synonyms is included in browse OTU page already. I will close, reopen if needed
