### ISSUE TITLE
Task - matrix hub - destroy row

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1123]
Both, the trash can icon and object radial, when you click it, try to destroy OTU, not delete the row from the matrix.

Also destroy warning message not informative, "Do you want to destroy this record" with no indication what is "this" record.

**Comment by proceps** [comment]
I cannot delete anything from the matrix (row, dynamic row, otu). I believe everything is scoped to the object, not to the matrix row or column.

**Comment by proceps** [comment]
It seams that I can delete dynamic row, if it has a small number of records, but I added a large one, and now I cannot destroy it. The project "3i", the matrix "Illustrations"

**Comment by mjy** [comment]
The models *are* broken.  You can not use the same dynamic character in two matrices, and delete may have unforseen consequences.  You will not delete observations, but you create issues with matrix row/column management.

**Comment by mjy** [comment]
@jlpereira I think you might be sending the wrong ID? I'm on fix matrices branch, so if you can point me to what is sent I'll try to fix there rather than messing up your world (it's a big diff).

**Comment by mjy** [comment]
Definitely sending the wrong id.
