### ISSUE TITLE
Task - Edit matrix - Dynamic row

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1125]
I was able to add the same otu as dynamic 3 times, and now I have all taxa repeated on the list.
It should be possible to add the same otu only once.

**Comment by proceps** [comment]
I believe that the problem is that when you add or delete dynamic row, it is rebuilding the page without reload. No spinner indication that something is working on background. I was trying to add a dynamic otu, and nothing was happening. I tried three times (may be more), and decided that it did not work. Left the page. When I open the page another time. The dynamic otu was added 3 times. And now all otus in the list are replicated 3 times. May be instead of page reshaping, adding or deleting a dynamic otu should trigger the page reload. It will work much faster in the cases of larger taxa.

**Comment by jlpereira** [comment]
Steps to replicate? I already tried adding the same taxon name and I get a message of that taxon name was already taken.

**Comment by proceps** [comment]
@jlpereira I do not know how to replicate it. But I have the matrix in the 3i database:
https://sfg.taxonworks.org/tasks/observation_matrices/new_matrix/29
The taxon is added 3 times, and I do not have any possibility to delete it from there. You should saw the error notification in the mail yesterday.
It could be a timing issue, like that reported by Tommy on the people assigned as authors to the TaxonName. I saw this problem, but never could replicate it. And deleting the people was relatively easy. I am glad that Tommy was able to replicate the steps.

**Comment by mjy** [comment]
There is a destroy error being thrown backend- may be related.
