### ISSUE TITLE
Task - matrix hub - new descriptor

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1128]
When I create a new descriptor in a scope of a matrix, using a link to "new descriptor", it should be automatically added to matrix. The same should also apply to a new OTU and new collection object.

**Comment by mjy** [comment]
Seems like we need to tie this into the pinned functionality?  If you have a pinned matrix, and it is defaulted, then we see a messages saying this descriptor will be added to that matrix.

**Comment by mjy** [comment]
@jlpereira IIRC new desciptor is vue, if so please implement above.  You might ahve to make a second call after successfull save.

**Comment by proceps** [comment]
This works, but can you automatically add descriptor to the matrix, so I do not need to click the hyperlink. Expected behavior, if I come to the interface with a new descriptor from a particular matrix, once I created the descriptor, it is already a part of the matrix, without additional steps to add it.

**Comment by mjy** [comment]
@proceps.  We don't understand the steps.  Please try and se triple ticks to tell the story ` <- three of those to wrap text on top and bottom to get this effect:
```
my
  story
     steps
```

The first story should be the current behaviour, the second story should be the expected behaviour.

Include annotated screenshots.

**Comment by proceps** [comment]
I did not understand interface yesterday night. It is already working. I got confused with the hyperlink: "Add to matrix". I thought that I have to click it in order to add this descriptor to the matrix. Please change the message from "Add to matrix:" to "Matrix:" to avoid confusion. 

Partly the confusion come from the fact that I had to enter quantitative character in 2 steps. I could not understand why? Only after I saved the name, I got an access to the default unit, and had to click button again to save the selection. 
Since after saving the descriptor nothing happened (I was expecting a return back to the matrix interface). I noticed the link "Add to the matrix" on the top of the form. Only after clicking the button, I got back to the matrix. I expect that two additional steps - updating with default unit and return back to the matrix are the steps which could be eliminated to avoid confusion. I expected that just clicking save button will create a new descriptor and bring me back to the Edit matrix interface.

**Comment by jlpereira** [comment]
@proceps more changes pushed. All sections should be unlock from the start. Dont really remember why we lock it in the first time. Now you should be able to create the descriptor just adding a character directly and pressing "Add" button.

If a matrix is selected on "New descriptor" task, it should send you directly to "Edit matrix" after you create or update a descriptor

Let me know if you need another changes for your workflow here or other tasks/features

**Comment by proceps** [comment]
looks really great. Could you move default units above the save button. Otherwise save button in the middle of the form looks little bit strange. But everything is functional.

**Comment by jlpereira** [comment]
Agree, I think it didnt have too much sense split this in two sections when others type of descriptors have more options that are part of the same.

I made some code refactor there and cleanups. Now each type of descriptor that have more of one sections is unified.

Close if you think this okay now
