### ISSUE TITLE
Task - Comprehensive digitization - fixed position horizontal top bar [was vertical status bar]

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1129]
When I am on comprehensive digitiztion, then the form is long.  I want to see the current status of save/nosave based on a single vertical bar to the left of the whole form.

Likely two colors, orange/green, but might consider 3 states:

When no CO id is present - yellow
When a change is made and CO is present - orange
When *everything* is saved - green

![Screen Shot 2019-10-12 at 11 47 55 AM](https://user-images.githubusercontent.com/22600/66704934-47a2de00-ece6-11e9-9302-8cfab17fc762.png)

Also consider- SVG status endpoint (hex status)

**Comment by jlpereira** [comment]
I think we should be consistent with this and replicate what we have in other interfaces. For example, in New Taxon Name we use the warning icon in the top bar to show that there are unsaved changes.

**Comment by mjy** [comment]
Bar is fixed now.
