### ISSUE TITLE
batch load - basic DWCA occurrence records

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#113]
Our museum staff uses [GBIF's spreadsheet](https://github.com/gbif/ipt/wiki/gbif-ipt-docs/downloads/occurrence_ipt_template_v2.xlsx) to record occurrence (specimen) data.
We pared the columns down to the essentials (for us) and added a few to facilitate georeferencing. All column headers in our sheet are Darwin Core terms:

- catalogNumber
- scientificName
- taxonRank
- family
- kingdom
- individualCount
- organismQuantity
- organismQuantityType
- basisOfRecord
- eventDate
- recordedBy
- verbatimLocality
- locationRemarks
- associatedTaxa
- occurrenceRemarks
- countryCode
- stateProvince
- county
- municipality
- locality
- decimalLatitude
- decimalLongitude
- coordinateUncertaintyInMeters
- georeferencedBy
- georeferenceProtocol
- georeferenceRemarks
- geodeticDatum
- collectionID
- occurrenceID

We upload these sheets (.csv) to SCAN (Symbiota) and would like to load them into our TaxonWorks project as well. Our current workflow is to populate a sheet with about 2000-3000 rows' worth of specimens, transcribed straight from the labels. We then use OpenRefine to clean it up and cluster certain localities for efficient georeferencing. We're starting to see many of the same localities pop up again and again. It would be great if we could apply our prior georeferencing effort to current and future specimens. Maybe a workflow like this:

1. A person transcribes labels into a spreadsheet
2. Spreadsheet is loaded into TaxonWorks, which checks to see that each catalog number is unique (if matches one in database already maybe the user is asked whether this is an update or should be ignored)
3. verbatimLocality is matched against what is in the database already (which hopefully is georeferenced) and suggests (or automatically applies?) lat/long/error for each locality
4. Unmatched localities get added to a "to do" list (i.e., georeference these localities)

References:
Our [blank spreadsheet](https://docs.google.com/spreadsheets/d/1kzqHU_guLZP3J-fRPs1cC98Ua7lbOP8SXNeR2zi1LA0/edit?usp=sharing)
Our [protocol](https://scholarsphere.psu.edu/files/cj82k747v)

**Comment by TuckerJD** [comment]
In-process design document: https://docs.google.com/document/d/18iTlim9lLQXXTdkNUJGXP1WIPcRbYNfkz8dkLUq1YFw/edit?usp=sharing

**Comment by mjy** [comment]
Closed in merge of #144.  Open new issues as problems arise.  Let's patch directly on development.
