### ISSUE TITLE
Gender choice for genera sometimes doesn't allow saving

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1134]
It seems that the gender choice for genera has a bug -- **_sometimes_** it doesn't let the user choose ANY option -- I mean, I can choose, by the choice is ignored and not saved by the system.
This happened twice so far.

**To Reproduce**
1) When I am in the "Edit Taxon Name" task.
2) Then I try to select a grammatical gender in the "Gender and form" module.
3) Save and watch NOTHING happens as the orange soft validation warning is still there.

**Expected behavior**
Should mark either feminine, masculine or neuter and save this choice.

**Environment (please identify where you experience this bug:**
Chrome

**Comment by mjy** [comment]
Thanks so much @adrik29 for submitting an issue here!

@jlpereira might this be related to a autosave race condition?

**Comment by jlpereira** [comment]
I can't replicate it. Can you @mjy ?

**Comment by adrik29** [comment]
It doesn't happen ALL the time, only sometimes. I couldn't isolate a cause.

**Comment by adrik29** [comment]
And now I discovered that after a few days of "rest" the gender allows itself to be set.

**Comment by mjy** [comment]
There is a lag/latency bug I think here.  I really think we need to remove all autosave.

**Comment by proceps** [comment]
I believe it is more stable now, I cannot replicate, please re-open if still an issue
