### ISSUE TITLE
Model - Serial - add boolean contains_valid_iczn_nomenclature?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1136]
When I add a serial, then I want to know if papers published in a serial contain nomenclatural acts that are "available" for ICZN purposes.

True - By default, if a paper comes out in this serial, then it is deposited in X archives, and or meets the digital requirements for name availability.

Considerations - `is_preprint_publisher?` (if false, then we can make strong assumptions)

**Comment by proceps** [comment]
we have is_electronic_only check box on the serials. The rest would be much harder to validate. The papers which are published in electronic only format, but do not completely follow iczn recomendations, the names published in those journals could still be available, if the authors follow all ICZN recomendations.
