### ISSUE TITLE
Image resize

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1139]
Line drawings saved as TIF files in black and white format are terribly resized in TW:
![image](https://user-images.githubusercontent.com/5597748/67114834-67cd1400-f1a2-11e9-9614-c0eca49034a0.png)
Please convert them to gray-scale or color before resizing. You can see the difference in the picture the same file uploaded as "black and white" and as grayscale.

**Comment by proceps** [comment]
in VB, when resize image, if it is TIF file, I convert it first to JPG or PNG, and than I apply the folowing parameters for resizing (those parameters should also be used when resizing any other file type):
               graphics.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality
               graphics.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality
               graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic
               graphics.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.HighQuality

Is it possible to find equivalents in ImageMagic?

**Comment by mjy** [comment]
Likely not 1:1, but almost certainly there is equivalent.  Quickly off the top of my mind:

1) Find the mx code that we used, Krishna had a very nice custom thumb generating rules
2) See http://www.fmwconcepts.com/imagemagick/index.php
3) Install ImageMagick and just play with the command line (`convert` with flags)
