### ISSUE TITLE
Task - image matrix - citation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1141]
When I upload an image to the image matrix, I would like to have a "add default source button" 
![image](https://user-images.githubusercontent.com/5597748/67115389-b3cc8880-f1a3-11e9-8436-fa5721466fd9.png) next to the radial anotator when a default source is selected, 
expected behavior, once I click the button, the citation is automatically added to the image and a button change to the citation button: 
![image](https://user-images.githubusercontent.com/5597748/67115555-1e7dc400-f1a4-11e9-9086-eebee9e01eb9.png)

**Comment by mjy** [comment]
@jlpereira I suggest you change the citation button to green, with a second circle on top left, a plus in the middle, when we want to use this mode.  Then clicking will set the default citation, increment the number?
