### ISSUE TITLE
Bug - auto-complete search does not return some collection objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1143]
**Describe the bug**
Containerized collection objects do not show up on auto-complete search if searching by identifier. 

**To Reproduce**
1. When I search for an identifier (e.g. "3395") in Browse Collection Objects.
2. Then I don't see all the results for that identifier (e.g. Insect Collection 3395)
3. And I search for that taxon "Perlesta placida (Hagen, 1861)" in "Collection Object FIlter"
4. Then I see the specimen in question, without its identifier displayed. 

**Expected behavior**
I should be able to search for containerized lots by identifier and have them appear both in lists and in auto-complete searches.

**Screenshots**
List when searching by Identifier "3395" - Note INHS Insect Collection 3395 is NOT a result.
![image](https://user-images.githubusercontent.com/11411328/67119825-88e73200-f1ad-11e9-8676-45eec2facff1.png)

Collection object INHS Insect Collection 3395:
![image](https://user-images.githubusercontent.com/11411328/67119902-bdf38480-f1ad-11e9-901a-cd0941278c94.png)

Searching in "Collection Object Filter" returns the collection object, but without identifier displayed (the second row leads to that collection object).
![image](https://user-images.githubusercontent.com/11411328/67119965-e2e7f780-f1ad-11e9-886d-25e5aca78e0c.png)

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by tmcelrath** [comment]
Note that this means I cannot edit these objects in the "Comprehensive Collection Object Form" task because I can't get to it through them through the auto-complete search.

**Comment by mjy** [comment]
@tmcelrath I believe we resolved this, at least in part. Please check if you have a second.

**Comment by tmcelrath** [comment]
I can't tell if this is resolved or not - but "INHS Insect Collection 3395" does not come up when I search for that identifier.

**Comment by tmcelrath** [comment]
Possible that identifier did not get properly moved to specimens.

**Comment by mjy** [comment]
Is this a miss-matched namespace issue?

**Comment by tmcelrath** [comment]
I don't think so. I can't even find these ones by taxon anymore.

**Comment by tmcelrath** [comment]
The only way I could find this record anymore was by guessing at it's TW ID:
![image](https://user-images.githubusercontent.com/11411328/70250879-34d7e300-1744-11ea-9ede-f7dfaf1f5947.png)

**Comment by mjy** [comment]
I see- it's the virtual container issue.  Thanks for clarification.

**Comment by tmcelrath** [comment]
If possible, could this be considered "blocker"?

**Comment by mjy** [comment]
Will be the next thing I fix, hopefully live late today.

**Comment by mjy** [comment]
<img width="856" alt="Screen Shot 2019-12-05 at 12 58 17 PM" src="https://user-images.githubusercontent.com/22600/70265052-3a8ef200-175f-11ea-885a-a24d9a6740f8.png">
<img width="883" alt="Screen Shot 2019-12-05 at 12 58 28 PM" src="https://user-images.githubusercontent.com/22600/70265053-3a8ef200-175f-11ea-9fb6-18300a70e073.png">
<img width="921" alt="Screen Shot 2019-12-05 at 12 59 50 PM" src="https://user-images.githubusercontent.com/22600/70265054-3a8ef200-175f-11ea-8942-addaadabcb0e.png">

**Comment by tmcelrath** [comment]
Awesome! Looks great!
