### ISSUE TITLE
Loan Invoices

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#1144]
The INHS Invoice # needs to be the number used as the Unique Identifier.
When I search for a loan I need to be able to search by the loan invoice number and I need it to be the Unique Identifier that is used to find it.

**Comment by tmcelrath** [comment]
See INHS Gitlab Issue #9

**Comment by mjy** [comment]
You can search by loan code like `4746` in the autocomplete. Reopen if you need other identifier searches.
