### ISSUE TITLE
Bug - Specimen returned from loan not showing under collection object history

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1146]
**Describe the bug**

When I mark a collection object as "returned from loan", then that information should show up in "Browse Collection Object" task if collection object is searched for. 

**To Reproduce**
1. When I go to an existing loan.
2. Then I mark a specimen as "Returned" on date "10/22/2019
3. And I navigate to that specimen in "Browse Collection Object"
4. Then I see when it was "Sent for loan" but not that it was "Returned from Loan"

See "Loan 4629" in INHS Insect Collection production and specimen 453308 (Github was having issues with screenshots when I posted this. 

**Expected behavior**
Should be added as an attribute and displayed in "Browse Collection Object"

**Screenshots**

**Environment (please identify where you experience this bug:**
- Production
- Browser Chrome

**Comment by mjy** [comment]
@tmcelrath  Do the return data look correct or are they missing?

**Comment by tmcelrath** [comment]
Missing. Do not show up under Browse Collection Object at all, even after I've saved the loan information.

**Comment by mjy** [comment]
Probably an import error- let's close here and move to Gitlab.

**Comment by mjy** [comment]
Ah wait- you mean the data is saved to record fine?  But just not showing up on list?

**Comment by tmcelrath** [comment]
It is saved to the loan form page (e.g. I can return to the page and it is still marked as "Returned" on "10/22/2019") but when I navigate to the Collection Object, there is nothing about the specimen being "Returned".

**Comment by tmcelrath** [comment]
This is new information - as in I'm returning this specimen after it has come back from a loan - so it can't be an import error.

**Comment by mjy** [comment]
Got it.  Should be an easy fix when I get back.  Need to get to the other improvements to browse as well.  A top priority.

**Comment by tmcelrath** [comment]
Looks like you've got no meetings today. So many bugs being squashed! Thanks!
