### ISSUE TITLE
Enhancement - Comprehensive specimen digitization - Add Different Color/Sound for errors in saving

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1147]
When I save a record in comprehensive specimen digitization - the color of text and sound played when I save the record is the same for when everything is fine as for when there is a validation error (e.g. maximum elevation is smaller than minimum elevation). 

Instead, the pop-up at the bottom should be BIG RED LETTERS and play a "BAD SOUND" saying "SOMETHING IS WRONG". Possibly also highlight the offending areas. 

Requested by Michelle as well.

**Comment by mjy** [comment]
See also #1313

**Comment by tmcelrath** [comment]
I think this is done?

**Comment by tmcelrath** [comment]
Done
