### ISSUE TITLE
tasks/collection_objects/filter/set_area raises with bad(?) params - how?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#115]
This query raises. I can't replicate how it happened:

`tasks/collection_objects/filter/set_area?utf8=%E2%9C%93&area_picker_autocomplete=&drawn_area_shape=%7B%22type%22%3A%22Feature%22%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B8.4375%2C16.04581345375217%5D%2C%5B8.4375%2C16.04581345375217%5D%5D%5D%7D%2C%22properties%22%3A%7B%7D%7D&selection_object=CollectionObject`

**Comment by TuckerJD** [comment]
`"{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[8.4375,16.04581345375217],[8.4375,16.04581345375217]]]},"properties":{}}"`
On the face of it, your 'Polygon' consists of only two points, and they are identical. 
RGeo::GeoJSON.decode is apparently unable to decode the object into a valid GeoJSON Feature, and returns nil. This causes the raise for 'undefined method `geometry' for nil:NilClass'.

This *CAN* be duplicated (though not easily) by selecting the map, and clicking once (anywhere) and, _without moving the mouse_, double-click. This ends the polygon, and makes it ready for 'Set area'. In normal operation this will *not* result in a fault page, but the page will seem to stall with the spinner.

I'm looking at the code to see if there is a clean way to accommodate this action, without the raise.

**Comment by mjy** [comment]
Thanks for tracking it down, I figured it was something obscure like that.

**Comment by mjy** [comment]
@TuckerJD can we close this?

**Comment by TuckerJD** [comment]
I think so, yes: Now, if the shape does not decode to a valid RGeo object, it will simply appear as though no objects were found.
