### ISSUE TITLE
Bug - Clipboard fills not saved

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1150]
**Describe the bug**

When I fill a field using the clipboard, then save, that field acts as if nothing is in the field, and nothing is saved. 

**To Reproduce**
1. When I  go to a task (e.g. Comprehensive specimen digitization)
2. Then I use my clipboard to fill a field (e.g. "Buffered determination"
3. And I click "Save"
4. Then I see that the fields were saved, but the field filled by the clipboard command (e.g. Ctrl. 1") did not save.
4a. Note that if I then edit the field, by deleting or adding something, then the field is saved. 

Before a save: note filled out "Buffered determination" field.
![image](https://user-images.githubusercontent.com/11411328/67580280-b1ba7a80-f70b-11e9-8d37-aa99539c955d.png)

After a save: note empty "Buffered determination" field, even though a successful "All records were successfully saved" is displayed. 
![image](https://user-images.githubusercontent.com/11411328/67580363-d4e52a00-f70b-11e9-830a-2671eb24a21a.png)

**Expected behavior**
Should save the field filled using the clipboard function

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by jlpereira** [comment]
Thanks for report this, this is a major bug and its present on all new interfaces. I'm working on the fix right now.

**Comment by tmcelrath** [comment]
Nice! Thanks!
