### ISSUE TITLE
Enhancement - New task(s) - bulk changes

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1151]
We need a task to be able to change many things at once. Could be integrated with pinboard. Pin a thing, then change all of them at once. 

- add annotations
- add determinations
- change parent of multiple taxa to same taxon

Really important for adding multiple new determinations, or changing multiple taxa at once that have been moved to new parents.

**Comment by tmcelrath** [comment]
Mostly collection objects. Also taxonomic names and OTUs.

**Comment by mjy** [comment]
Match collection objects does some of this.  @tmcelrath I'm going to close this, it's too general to act on as is.  Let's make it more specific breaking out bits to new/proposed tasks.
