### ISSUE TITLE
Soft validation msg doesn't include all adjective terminations

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1152]
As a soft validation error, this msg is not accurate. There are Latin adjectives with other terminations, such as the invariable "teres" (smooth) for example.

"Adjective name should end with one of the following endings: -us, -a, -um, -is, -e, -er, -or."

**Comment by mjy** [comment]
THanks @adrik29.  Technically not a bug, but a target for future improvement.  Our bugs are cases where code is broken, preventing functionality to occur.

We'll get @proceps to make this improvment.

**Comment by proceps** [comment]
validation modified. The message updated. Please reopen if issue still exists.
