### ISSUE TITLE
Task - Filter biological associations [Was: New task - Filter/view biological association]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1156]
# Facets (in this order)

## Nomenclature
* [x] Auocomplete populates list, select lets you pick which of 3 options per name 
  * [x] subject `subject_taxon_name_id[]=`
  * [x] object `object_taxon_name_id[]=`
  * [x] both `taxon_name_id[]=`

## From
_Spatial nterface as for CO/OTU/CE
* [x] GeoJSON from Map 
* [x] Spatial via selecting a GeographicArea that has shape and using `spatial_geographic_area_id` (may have to unify this param name)
* [x] wkt

## Relationship
* [x] Pick relationship `biological_relationship_id[]=` 

## Biological property
Biological property smart selector.  Each selected in list has option to set to subject or object. If we don't have smart selector us the same approach that loads properties from Biological Relatoinship composer.
  * [x] subject `subject_biological_property_id`
  * [x] object `object_biological_property_id`

## Biological Associtions Graph
_We don't have any of these yet, so for later, though param exists._

## Members of
_all autocomplete formulated lists)
* [x] `otu_id` 
* [x] `collection_object_id` 
* [x] `collecting_event_id`

## Annotations
Shared facets for
* [x] Identifiers
* [x] Notes
* [x] Tags
* [x] Houskeeping/users
* [x] Citations

## Result columns
```
subject.order
subject.family
subject.genus
subject.object_tag
subject.biological_properties (array of tags)
biological_relationship.object_tag
object.biological_properties (array of tags)
object.order
object.family
object.genus
object.object_tag
```

* [x] Download option (inline CSV for now)

*  Display graph of result set (do this in another task)

**Comment by mjy** [comment]
@jlpereira I pushed a new branch 1156_biological_associations_filter.  Please scaffold our standard faceted filter there 'Task - Filter biological associations'.  Params coming "soon".

**Comment by mjy** [comment]
Blocking dependencies are on 2652_unified_filters

**Comment by debpaul** [comment]
Please any updates on this Filter (in terms of priority and progress)? I'm editing text for a reference to this in the manual. 

Example 
![image](https://user-images.githubusercontent.com/2990155/177426379-f3b5e3ad-9acb-414f-9dc4-8b0a6e8b53c4.png)

Where current filter doesn't show all publications possible, ... among other functions ...
