### ISSUE TITLE
Bug - CoL - CoLDP exporter is attaching species synonyms to parent ranks instead of species

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#1164]
**Describe the bug**

In the CoLDP exports, species and lower ranked synonyms are being attached to all of their parent taxa including higher ranks. In the below example the synonym, *Rhizophagus (Anomophagus) wagae*, is being attached to the subfamily Rhizophaginae, genus Rhizophagus, and subgenus Rhizophagus (Anomophagus), but not to the accepted name *Rhizophagus (Anomophagus) puncticollis* Sahlberg, 1837.

**To Reproduce**
1. When I export Monotomidae to CoLDP
2. Synonyms are attached to their parent taxa

**Data exported from TaxonWorks:**

**Name.csv**

ID | scientificName | authorship | rank | genus | specificEpithet | infraspecificEpithet | cultivarEpithet | appendedPhrase | publishedInID | publishedInPage | publishedInYear | original | code
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
448407 | Rhizophagus | Herbst, 1793 | genus |   |   |   |   |   | 46810 | pls 44–59, J–N + 392 | 1793 | true | ICZN
448406 | Rhizophaginae | Redtenbacher, 1845 | subfamily |   |   |   |   |   |   |   | 1845 | true | ICZN
448410 | Rhizophagus (Anomophagus) | Reitter, 1907 | subgenus | Rhizophagus |   |   |   |   | 47159 | 27-30 | 1907 | true | ICZN
448421 | Rhizophagus (Anomophagus) wagae | Wankowicz, 1865 | species | Rhizophagus | Rhizophagus (Anomophagus) |   |   |   | 47213 | 297-300 | 1865 | true | ICZN

**Synonym.csv**

taxonID | nameID | status
-- | -- | --
86577 | 448421 | synonym
86576 | 448421 | synonym
86580 | 448421 | synonym
86591 | 448421 | synonym

**Taxon.csv**

ID | parentID | nameID
-- | -- | --
86577 | 86576 | 448407
86576 | 85906 | 448406
86580 | 86577 | 448410
86591 | 86580 | 448421

**Screenshots**
![image](https://user-images.githubusercontent.com/8573609/68139595-ff936780-feef-11e9-953e-2c95347af2f6.png)

![image](https://user-images.githubusercontent.com/8573609/68138885-d6bea280-feee-11e9-8d45-086bab766396.png)

![image](https://user-images.githubusercontent.com/8573609/68139006-08d00480-feef-11e9-8fcf-67e6621442cb.png)

![image](https://user-images.githubusercontent.com/8573609/68139299-8562e300-feef-11e9-99c2-c36f84ac2dcb.png)

**Expected behavior**
Species and lower ranked synonyms should be attached the species that they are a synonym of, and not the parent higher ranks.

**Environment (please identify where you experience this bug:**
- sfg.taxonworks.org
- https://dev.col.plus/dataset/2061/taxon/86576 (temporary)

Ping: https://github.com/Sp2000/colplus-repo/issues/76

**Comment by mjy** [comment]
@gdower Will fix, but for the record the model that overloads parenthood with synonymy is not the best idea in the long run. Discuss later.

**Comment by mjy** [comment]
@gdower Can you confirm that the value that needs to change is the parentID in Taxon.csv?

**Comment by gdower** [comment]
Actually all [synonyms should be removed from Taxon.csv](https://github.com/SpeciesFileGroup/taxonworks/issues/1158) and it's the taxonID in Synonym.csv that should be changed to the taxon that the synonym is associated with. Currently, species-level synonyms are being attached to all of the parent uninomials of a species-level taxon instead of the species-level taxon. 

Hopefully that makes sense? If not, I could meet with you sometime this week or next week.

**Comment by gdower** [comment]
Fix confirmed
