### ISSUE TITLE
Sample descriptor - default unit

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1169]
Add default unit option for Sample descriptor

**Comment by jlpereira** [comment]
You are talking about "New descriptor" task? what default option you prefer there?

**Comment by proceps** [comment]
1. New descriptior task does not show the field "default unit". For example I have a character body length, and I always want this be measured in mm. I can put mm as a default unit.
2. When I use quantitative description in the matrix row coder, I measure the body length, I have to enter mm for each measurement. So if the descriptor have the default unit set up, this would be populated automatically every time I score this descriptor for a particular OTU.

**Comment by jlpereira** [comment]
<img width="1680" alt="Captura de Pantalla 2020-05-18 a la(s) 17 39 45" src="https://user-images.githubusercontent.com/16530364/82257587-ad1b1500-992e-11ea-933e-3f2657eb25fd.png">

I see default unit section there.

What you are saying is make a unit as default?
What you think about make this as a preference? set always the last selected? If you pick "mm", the next time will be set as "mm" by default

**Comment by proceps** [comment]
Ok, may be I selected another character which was not quantitative and default unit was hidden (which make sense). No I do not like the idea of last selected. I prefer the same unit which is inherited for the descriptor consistently used for every single scoring for this descriptor in the Matrix row coder. We have multiple people working on the project, and I already have inconsistent values in the database. Somebody decides to change it to cm or inches, and it will be prolifirated.

**Comment by jlpereira** [comment]
I was meaning this as a user preference, so it won't be changed for other user.
Lets try a different way to solve this, similar but with other step to prevent the user changes for error the default option.

1- User select the unit for the first time.
2- Now a button with the label "Set as default" will be visible beside the field
3- User press the button and that unit will be stored as default preference for that user.
4- If the user select a different unit, then the button will be visible again to make the new unit default if the user clicks on it.

What you think?

**Comment by proceps** [comment]
@jlpereira I do not like the proposal. You know I have an idea that good application should reduce the number of required action to save a single record in the database. If I already come to the trouble selecting default unit for a descriptior, I do not want another action to confirm it each time, I make scoring. Ideally, this should be the same pick list, which we already have in the interface where the default value is already selected. I do not like the idea of additional buttons. I give you few more examples of inefficiency of our interfaces. When I pin some object, I still have to go to the pinboard, to make this object default to be able to use it. This is additional 4-5 mouse clicks plus scrolling, because I tend not to delete objects in the pinboard and they tend to accumulate (because deleting are additional mouse clicks). I asked many times to make the pin object default automatically. In 99% of cases I pin something because I want to use it right away in some other interface.... Another examples are smart selectors. They slow me significantly. I like to work with forms using tab button. where I can navigate the form without touching the mouse. But smart selectors do not allow to do this. I have to jump through all the buttons and watch carefully where I am, so any form with a smart selector force me to use the mouse. Which significantly reduce the productivity. We have to very efficient forms (Edit taxon name, and Matrix row coder) with auto save functionality, And I do not want to see additional buttons there unless this is absolutely necessary.

**Comment by mjy** [comment]
We need to refactor this issue to be what it really is- it's burried @proceps .

Write out a story, not linear, use steps:

```
When I select a default unit for my descriptor
   then when I am using the matrix row coder
      and I am coding for the descriptor in question
          then that *observation* has the units selected that are the same as the default I select for the descriptor
```

Is this the issue?

**Comment by proceps** [comment]
Thanks @mjy, I think, I tried to explain the same :) In two steps somewhere above.

Anrelated to this issue question. Can we drop entirely predefined set of units. They do not make any sense. And without definition, it is extremely difficult to pic the right one. People selecting N for things. Which is something completely different. We need our units which is not possible to enter now: 3 setae, 2 carinae, 5 groves. Solution?

**Comment by mjy** [comment]
Open new issue please re units discussion.

**Comment by jlpereira** [comment]
Sorry @proceps, I had understood something completely different from what you needed. I though you wanted to create new descriptors with the same options of units. With Matt steps now i see what you're meaning. 
Now observations rows on MRC should set the descriptor unit.

For the other issues, perhaps it would be better to open separate issues and discuss them there.

**Comment by proceps** [comment]
Thanks it works.

**Comment by proceps** [comment]
Have to reopen it again. I put a test matrix with 4 descriptors. 3 of them has default unit set up. But in the row coder interface, only the first descriptor has the default unit in place. All other descriptors still have blank field for the unit...

**Comment by jlpereira** [comment]
Looking

**Comment by jlpereira** [comment]
I can't replicate it @proceps 
I created a new matrix and descriptors using different units, each one have the correct unit set.
Could you recheck this? If you replicate it, take a look at the following steps you made for it, and see if you're looking observations that are already created with a wrong unit

![Sin título](https://user-images.githubusercontent.com/16530364/82735529-c9390080-9cf8-11ea-8ccb-31b06895645d.png)
