### ISSUE TITLE
Model - TaxonName - superspecies group names not rendering correctly

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1170]
* [ ] Parens are used when they shouldn't be (species group name, not genus group)
* [ ] Parent in string is not properly referenced in string

See Orthoptera sandbox- `tasks/nomenclature/new_taxon_name?taxon_name_id=31824`

![Screen Shot 2019-11-05 at 10 16 11 AM](https://user-images.githubusercontent.com/22600/68225208-b279c900-ffb5-11e9-97b8-dc4c1f62fe17.png)

**Comment by proceps** [comment]
ICZN Art. 6.2: A specific name may be added in parentheses after the genus-group name, or be interpolated in parentheses between the genus-group name and the specific name, to denote an aggregate of species within a genus-group taxon...

**Comment by proceps** [comment]
"aggregate of species" is a species group or superspecies.
what is fusiformis? Supersuperspecies? We do not render those...

**Comment by typophyllum** [comment]
The nomenclature of genus Ceuthophilus is in fact complicated. In this case there is a subgenus Ceuthophilus (Geotettix) which has two species series, one of them the species series fusiformis. This species series in turn comprises 5 species groups, one of them being alpinus, which comprises only the species C. alpinus.

I think the genera Ceuthophilus and Isophya are the only taxa with species series in OSF (the latter genus has also a few species subgroups).

**Comment by mjy** [comment]
Suggestions to resolve?  All name strings in nomenclature are meant to comply with the rules.  If the names here are not meant to be governened as species (or genus) group names then we will have to wait until we implement concept heirarchies to allow the names to be added as OTU names.

**Comment by typophyllum** [comment]
The problem is only the species series (9 in Ceuthophilus and 1 in Isophya) or also the species groups (many)?
