### ISSUE TITLE
Task - Collection objects filter - Area/Map search

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1176]
When searching by area, collecting events having coordinates-only won't appear in search results. Also, when searching using map (circle for example), collecting events having area rather than coordinates won't show up either.

As example, in Sandcastle, searching for Buenos Aires (TDWG) will show a single record, and when using map will show multiple record EXCLUDING the one that appeared in the other search.

**Comment by mjy** [comment]
By "having cooridinates" do you mean "is georeferenced"?  Verbatim_coords are not used in spatial searches.

**Comment by LocoDelAssembly** [comment]
But if I've selected a geographic area (TDWG, has shape), is it expected to not be found if I do a "circle search" on map?

**Comment by mjy** [comment]
The intersection should be found, yes.

**Comment by mjy** [comment]
@LocoDelAssembly Can we close this?

**Comment by LocoDelAssembly** [comment]
@mjy depends on whether this is expected behaviour.
Map search:
![image](https://user-images.githubusercontent.com/4991925/68689615-68618c00-054f-11ea-9ba2-5bb396e726d3.png)
Area search (using Buenos Aires (Argentina Northeast) [TDWG Level 4] [has shape]):
![image](https://user-images.githubusercontent.com/4991925/68689882-dad26c00-054f-11ea-8151-33f6c8d7019b.png)

**Comment by mjy** [comment]
When I see that query, then I expect the result to contain the intersection of all collection objects that have events with specific `geographic_area_id` and within the provided radius.

**Comment by LocoDelAssembly** [comment]
We decided at #1177 that you cannot use both features simultaneously? (However without that fix applied and setting up both simultaneously results in zero records despite the circle and Buenos Aires overlaps)

The current behavior seems like the event has to be specifically registered as the area I'm searching, despite its lat/lng is inside the shape. And the other way around is also true, you cannot locate something registered without coordinates using a circle even if the shape of the geographic area of the event overlaps.

**Comment by mjy** [comment]
Did you click the spatial option?  If not it is searching by id, not spatially.

**Comment by LocoDelAssembly** [comment]
Also with the checkbox checked:
![image](https://user-images.githubusercontent.com/4991925/68695080-29d0cf00-0559-11ea-8431-4aaf9fc8b74e.png)
![image](https://user-images.githubusercontent.com/4991925/68695265-7916ff80-0559-11ea-922d-865bfd270564.png)

**Comment by mjy** [comment]
Found broken params, will push in a bit, thanks for this catch.

**Comment by mjy** [comment]
Spatial geo area working now, can actually test intersection for real.

**Comment by LocoDelAssembly** [comment]
Not completely sure by checking the checkbox looks like to returns all records of selected name.
![image](https://user-images.githubusercontent.com/4991925/68798328-fd8a8080-0634-11ea-8c2f-982b5861fbe9.png)

**Using map search returns nothing as expected:**

![image](https://user-images.githubusercontent.com/4991925/68798467-3cb8d180-0635-11ea-85c3-8ca20c2052f4.png)

**But when searching Buenos Aires it doesn't detect overlapping with TDWG shapes:**

![image](https://user-images.githubusercontent.com/4991925/68798663-8acdd500-0635-11ea-82b2-f0ce782f1df2.png)

**Comment by mjy** [comment]
You're right, working on restoring.

**Comment by mjy** [comment]
Pushed a tweak.

**Comment by mjy** [comment]
Can we close? :)
