### ISSUE TITLE
Task - Collection objects filter - Map/Area simultaneously

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1177]
When setting up something in either map or area and then using the opposite to do the search, it won't work (or it does as an intersection of both? See https://github.com/SpeciesFileGroup/taxonworks/issues/1176 if it is the case).

**Comment by mjy** [comment]
All facets are AND/intersection, not OR.

**Comment by LocoDelAssembly** [comment]
It is a bit confusing. If you forget to clear before switching search mode it results in an intersection that it is not visible immediatelly obvious (the UI is not showing both panes simultaneously, only one).

**Comment by jlpereira** [comment]
Now only geojson or geographic area could be selected, not both

**Comment by mjy** [comment]
It's technically OK to have both.  For example user wants Texas, and this
little spot beside Texas.

**Comment by jlpereira** [comment]
Should I revert the change?

**Comment by mjy** [comment]
I think so.

**Comment by LocoDelAssembly** [comment]
> It's technically OK to have both. For example user wants Texas, and this little spot beside Texas.
> […](#)

@mjy but isn't this working as AND/intersection? If that's so then doing something like that would result in no results? Looks like it will only find the tiniest region, provided it overlaps with all the others that have been specified.

Still, even if this would work as OR, then it is hard to notice that you are using both features:
![image](https://user-images.githubusercontent.com/4991925/68493973-51a7f600-022c-11ea-8618-52ffee317907.png)

Founds nothing, because I also chose Buenos Aires on "Area" tab but it is not indicated. For someone knowing those tabs work together might be natural, but for others it is quite likely they failed searching for something and then switched tabs to use the alternate method, without knowing they should have cleared criteria before switching tabs.

**Comment by mjy** [comment]
Yes, sorry, brain is foggy, it is AND, not OR, we should go with José's
first fix right?

**Comment by LocoDelAssembly** [comment]
> Yes, sorry, brain is foggy, it is AND, not OR, we should go with José's first fix right?
> […](#)

@mjy @jlpereira yes, although **if it is not too complicated** perhaps make the code avoid sending the data of the inactive tab/pane rather than resetting values when switching?

**Comment by mjy** [comment]
Along those lines- maybe we should highlight the facets/panes that have
values set?  Like a subtle background color?

**Comment by jlpereira** [comment]
> > Yes, sorry, brain is foggy, it is AND, not OR, we should go with José's first fix right?
> > […](#)
> 
> @mjy @jlpereira yes, although **if it is not too complicated** perhaps make the code avoid sending the data of the inactive tab/pane rather than resetting values when switching?

Possible but not so simple because the data is handle from the main filter, when the values are reset there, each component reset the state.

I think the first fix was the best approach. I gonna revert again the change
