### ISSUE TITLE
Is the first use of particular ranks of family-group names not recorded?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1178]
For example Leptysminae Brunner von Wattenwyl, 1893, originally introduced as Leptysmae, has been first used as Leptysmini by Mistshenko 1945 and as Leptysminae by Amédégnato 1974, with the appropriate suffixes for tribe and subfamily.

This information apparently wasn't imported from OSF and I cannot find out how to add it in TW.

**Comment by mjy** [comment]
@proceps Can you address please?

**Comment by proceps** [comment]
I believe it is fixed in the migration now.
