### ISSUE TITLE
Magick::ImageMagickError "cache resources exhausted `

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1181]
When we try to process an image, then we get a resources exausted raise.

It does not happen in all cases.  Pertinent file is almost certainly `/etc/ImageMagick-6/policy.xml`

```
  <policy domain="resource" name="memory" value="256MiB"/>
```

Requires a tweak to Docker file likely.

**Comment by LocoDelAssembly** [comment]
https://github.com/SpeciesFileGroup/taxonworks/commit/086722f41e9456a42aa04201e304fd7daf0c8778 should have fixed this. Will close after testing a bit more.

**Comment by LocoDelAssembly** [comment]
Problem not really solved, just making it less likely. If you make calls to OCR repeatedly it eventually fills out the disk cache. With time the cache starts to clear. I guess the release happens when the garbage collector sweeps unreferenced objects away.

**Comment by mjy** [comment]
Is tesseract gobbling mem?

**Comment by LocoDelAssembly** [comment]
@mjy we are. Please review https://github.com/SpeciesFileGroup/taxonworks/commit/241e28ccfcd9cc50d5b372e895a56ebb48af7e73 just in case I did something wrong. Could sqed need modifications like these as well?

**Comment by mjy** [comment]
Looks good to me.  There are likely some optimizations possible in SQED as well, I added an issue https://github.com/SpeciesFileGroup/sqed/issues/3 as a reminder.
