### ISSUE TITLE
Enhancement - CoL - Add species extinction status to CoLDP exports

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#1182]
**Describe the bug**

Extinction statuses are missing from Taxon table in the TaxonWorks CoLDP exports.

**To Reproduce**
1. When I export Monotomidae from Cucujoidea Species File to CoLDP format.
2. The extinct boolean column is empty and the extinct status is missing in CoL+.

**Expected behavior**
If a species is extinct, the [extinct boolean value](https://github.com/sp2000/coldp/#taxon) should be set to true. CoLDP format also allows inclusion of temporalRangeStart and temporalRangeEnd for including the geological time period when the species was extant with these [geotime](http://api-dev.col.plus/vocab/geotime) and [geotimetype](http://api-dev.col.plus/vocab/geotimetype) ENUMS based on the geochronological names from the official International Commission on Stratigraphy (ICS).

**Screenshots**
![Comparison of TaxonWorks and CoL+ with species extinction daggers missing](https://user-images.githubusercontent.com/8573609/69100719-60a85880-0a23-11ea-93c5-38490faed6c6.png)

**Environment (please identify where you experience this bug:**
- sfg.taxonworks.org

Ping: https://github.com/Sp2000/colplus-repo/issues/86

**Comment by mjy** [comment]
These will have to be added as Predicates/DataAttributes to OTUs.  This is the case where we need URIs for the ENUM predicates so we can add unambiguous matching to our "triples".

**Comment by mjy** [comment]
@gdower Are these required fields in the export?  If so it's a bug, if not it's an enhancement.

**Comment by gdower** [comment]
@mjy, it's not required although we might get emails from data providers or users pointing out that the species is extinct and not listed as extinct in CoL.

**Comment by mjy** [comment]
Can be tested on sandcastle.

**Comment by gdower** [comment]
This works and can be implemented in datasets by using the OTU annotator to set the data attribute `Extinct = 1`:

![image](https://user-images.githubusercontent.com/8573609/108761071-08a8ad80-7514-11eb-8426-30251405b9d2.png)
