### ISSUE TITLE
Enhancement - Loan Task - Confusing display

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1184]
When I am adding collection objects in loans: 
![image](https://user-images.githubusercontent.com/11411328/69349721-dd168380-0c3d-11ea-8c04-a05ef41c74f8.png)
It displays both CollectingObject unique identifiers and INHS Unique Namespace Identifiers. This is super confusing to a user - who doesn't know which one to pick. The way it used to display (with blue background around INHS Unique identifier) is better. Isn't the collection object Taxonworks unique identifier in the background anyway and mostly won't need to search by it? Personally, I don't think it should be displayed.

**Comment by tmcelrath** [comment]
Note - this will be highly confusing for any novice users - who will almost certainly pick the right one. I want to prevent this from happening.

**Comment by mjy** [comment]
Agreed, we will fix.
