### ISSUE TITLE
Task - Syncronize nomenclature to OTUs

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1186]
As a user I want to create OTUs for nomenclature that do not have them.

* [ x ] Valid/invalid scoping
* [ x ] Clade scoping

Ping @dhobern.

**Comment by proceps** [comment]
I definitely do not want to have OTUs in most cases on Combinations.
The questionable to have OTUs on misspellings and misapplications.

**Comment by mjy** [comment]
Add a new enhancement issue to provide option to exclude Combinations.  The rest is fine.
