### ISSUE TITLE
Bug - Comprehensive Digitization Form - georeference format inconsistency leads to error when georeferencing

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1192]
**Describe the bug**

When I am creating a georeference based on the verbatim georeferences - the format of the verbatim georeference can cause errors even when shown properly in the preview map. 

**To Reproduce**
1. When I transcribe a verbatim Lat/Long coordinate pair with the format "XX.XXXºN XX.XXXºW" 
2. Then I georeference it by saving, then clicking on Georeference button. 
3. And I see the same preview map regardless of format. 
4. Will not let me create georeference b/c using "ºN/ºW" format.
5. If I change format to "+/-XX.XXX +/-XX.XXX" format - this bug does not appear - even though map preview is the same. 

Format GPS coords this way (preview map is same as next one):
![image](https://user-images.githubusercontent.com/11411328/69379423-0f43d780-0c76-11ea-87ea-cb1a5f3a6761.png)
Get this error:
![image](https://user-images.githubusercontent.com/11411328/69379356-f63b2680-0c75-11ea-9062-08d063268451.png)

Format them properly:
![image](https://user-images.githubusercontent.com/11411328/69379460-2387d480-0c76-11ea-8875-2017838f6d90.png)

Get a Georeference properly in TW:
![image](https://user-images.githubusercontent.com/11411328/69379611-621d8f00-0c76-11ea-8248-441de2924c72.png)

**Expected behavior**
Should georeference from verbatim properly without regard to format. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
What, we need a univeral lat long parser? :). 

@jlpereira Can we easily extend to handle that verbatim format?  

Let's also update the error messages to display more cleanly, let me know if we need a different response.

Technically this is not a bug as we define it, i.e. given the inputs it still does something (tries, and fails to add a georeference), we just want it to be able to handle a broader range of inputs, thus enhancement.  A bug would be something in the process breaking.

**Comment by mjy** [comment]
@tmcelrath Just a note- your issues are awesome.  You don't really need to include the "Bug" in the title though. That will come as a label when we dev-types grok them and classify them. In this case perhaps "Task - Comprehensive digitization - unable to handle lat/long in format XYZ',

**Comment by proceps** [comment]
Did you check Jim's code if this is handle properly? Originally I supplied Jim with all regex to get coordinates directly from labels, and those suppose to handle majority of formats.

**Comment by mjy** [comment]
This is client side.
