### ISSUE TITLE
Data fields not updating universally?

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1193]
**Describe the bug**

When I update a field in the comprehensive digitization task - the updated fields (e.g. eventdate) do not appear in the corresponding collection object displayed row in the Collection Object Filter task. Possibly indexing issue?

**To Reproduce**
1. When I edit a specimen after it has already been created and save (and indexed?).
2. Then I update a field (e.g. eventdate or collector or preparation)
3. And I search for those specimens in collection object filter
4. Then I do not see the updated fields - but still see and download the old information. 

Current data on specimen when viewed in comprensive digitization task:
![image](https://user-images.githubusercontent.com/11411328/69434505-65ab2780-0d03-11ea-92f2-e79820b2c640.png)
![image](https://user-images.githubusercontent.com/11411328/69434543-7c517e80-0d03-11ea-988a-5c382eae76b5.png)

Shown data when searched for in collection object filter:
![image](https://user-images.githubusercontent.com/11411328/69434632-a0ad5b00-0d03-11ea-98bf-5050c8cfad08.png)
![image](https://user-images.githubusercontent.com/11411328/69434644-a99e2c80-0d03-11ea-9751-441a211fb544.png)

Note that "Preparation" and "eventdate" are not updated correctly. 

**Expected behavior**
Fields should update universally in TW

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
The rows are drawn from an index, and that index isn't rebuilt on update.   So data are OK, index is just stale.  Will bind updates in record to updates in index more closely. @LocoDelAssembly this may be a delayed job thing, but not positive.

**Comment by LocoDelAssembly** [comment]
@mjy production DelayedJob runs jobs from the coldp_export queue only (recent change, previously there was no jobs worker at all). If it is indeed a problem with this then please assign this issue to me.

**Comment by mjy** [comment]
This is mine, not delayed related directly.

**Comment by mjy** [comment]
@tmcelrath I believe this is fixed now, please confirm.

**Comment by tmcelrath** [comment]
Looks fixed. Changed one thing and re-searched - updated that one thing. Nice!
