### ISSUE TITLE
Task - Edit taxon name - Clone

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1196]
* When Clone is selected, automatically move the cursor to the textbox.
* By default, keep the original combination checkbox unchecked. It is not useful for 90% of cases. But keep the option. All other checkboxes should stay checked by default.

**Comment by mjy** [comment]
"By default, keep the original combination checkbox unchecked. It is not useful for 90% of cases. But keep the option. All other checkboxes should stay checked by default."  

Not sure I understand this part.

**Comment by proceps** [comment]
In most cases the original relationships should point to self, not to an external taxon. When you clone the original relationship, you keep the lowest rank relationship pointing to the origin, not to self, which is not very useful and have to be handled manually.
