### ISSUE TITLE
Task - New source - soft validations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1198]
make both matches and soft validations always visible (soft validations on the top)

**Comment by mjy** [comment]
We have other functionality coming (BHL previews, etc.) in that column, I don't think we should overload it and put too much there.

I would propose:
* If new source, default to matching
* If existing source, default to soft validation

**Comment by proceps** [comment]
soft validations only show problems. And it is not that many for the source. If nothing to display, that section is not needed at all.

**Comment by mjy** [comment]
That's not an argument for merging the sections...
