### ISSUE TITLE
Task - New source - People

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1199]
Next to people (authors, editors) add an object radial with direct links to (people edit and People unify).

**Comment by mjy** [comment]
Is this really going to be useful?  The state space is very tricky (saved source/not, save person/not).  I think we should not display this here, but rather in show. It will add more confusion than functionality in 80% of case.

**Comment by proceps** [comment]
it is practically the the only place where I discover problem with people (missing first name, duplicate name). And I have to navigate to completely different interface and search the name again to fix it. It is convenience to have the fixes in the right place.

**Comment by mjy** [comment]
I understand the utility, but IMO it must be balanced with probability of use, and amount of additional confusion in the state space of the form that it introduces, both from a user and a developers standpoint.  I'm not (yet) convinced of the tradeoff for something that seems like a rare-ish event, particularly one that should decrease in likelihood as the data matures.  Not saying we shouldn't do it, just need some convincing.
