### ISSUE TITLE
Task - New source - serial

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1200]
next to Serial, add an object radial to Edit Serial (in the future, also to Unify Serial).

**Comment by mjy** [comment]
I think a link out that always opens in new window is safest here.  The object radial opens in the current window.

**Comment by proceps** [comment]
We have an option of a right click to open the task in a new tab. In some cases it is a useful feature, in some others, I prefer to stay on the same tab (window).
