### ISSUE TITLE
Bug - CoL - Forma and variety names missing in CoLDP exports

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#1203]
**Describe the bug**

Forma and variety ranks are missing in the CoLDP Name table exports. Subspecies are included so this seems to be a rank-specific issue.

**To Reproduce**
1. When I export Cucujoidea to CoLDP
2. There are no forma or variety ranks in the Name table

**Screenshots**
![](https://user-images.githubusercontent.com/8573609/69099577-b3344580-0a20-11ea-86d7-36247d871d19.png)

Here's a grep of all of the names included in the above screen capture in the _Antherophagus_ genus, which only includes genus and species ranks:

```csv
grep Antherophagus *
Name.csv:453564 Antherophagus   Dejean, 1821    genus                                   46568   2 + viii + 136          true    ICZN
Name.csv:454317 Antherophagus fasciferus        Roubal, 1935    species Antherophagus                           48373   53-54           true    ICZN
Name.csv:454316 Antherophagus fasciatus Roubal, 1935    species Antherophagus                           48373   53-54           true    ICZN
Name.csv:454315 Antherophagus fursovi   Lyubarsky, 1991 species Antherophagus                           48137   63-67           true    ICZN
Name.csv:454314 Antherophagus spaceki   Roubal, 1935    species Antherophagus                           48373   53-54           true    ICZN
Name.csv:454313 Antherophagus nigricollis       Champion, 1925  species Antherophagus                           47882   101-112         true    ICZN
Name.csv:454312 Antherophagus ruficornis        Grouvelle, 1919 species Antherophagus                           47957   70-203          true    ICZN
Name.csv:454311 Antherophagus microphthalmus    Grouvelle, 1919 species Antherophagus                           47957   70-203          true    ICZN
Name.csv:454310 Antherophagus oregonus  Casey, 1924     species Antherophagus                           47878   1-347           true    ICZN
Name.csv:454309 Antherophagus pallidivestis     Casey, 1900     species Antherophagus                           47877   51-172          true    ICZN
Name.csv:454308 Antherophagus himalaicus        Champion, 1922  species Antherophagus                           47880   68-76           true    ICZN
Name.csv:454307 Antherophagus ludekingi Grouvelle, 1911 species Antherophagus                           47951   117-120         true    ICZN
Name.csv:454305 Antherophagus flavidus  Reitter, 1875   species Antherophagus                           47414   73-87           true    ICZN
Name.csv:454304 Antherophagus convexulus        LeConte, 1863   species Antherophagus                           46696   1-92            true    ICZN
Name.csv:454303 Antherophagus subnitidus        Grouvelle, 1911 species Antherophagus                           47950   97-100          true    ICZN
Name.csv:454302 Antherophagus ochraceus Melsheimer, 1844        species Antherophagus                           47089   96-126          true    ICZN
Name.csv:454301 Antherophagus caucasicus        Reitter, 1878   species Antherophagus                           48393   t. 1-4, 3-258           true    ICZN
Name.csv:454300 Antherophagus suturalis Mäklin, 1853    species Antherophagus                           48200   95-273          true    ICZN
Name.csv:454299 Antherophagus similis   Curtis, 1835    species Antherophagus                           1778                    true    ICZN
Name.csv:454298 Antherophagus canescens Grouvelle, 1916 species Antherophagus                           47954   26-29           true    ICZN
Name.csv:454297 Antherophagus silaceus  (Herbst, 1792)  species Antherophagus                           47966   i–viii + 113–197 + pls 40–43            true    ICZN
Name.csv:454296 Antherophagus nigricornis       (Fabricius, 1787)       species Antherophagus                           46575   xx + 348 + 382          true    ICZN
Name.csv:454295 Antherophagus pallens   (Linnaeus, 1758)        species Antherophagus                           9259    [i-iv] + 1-823 + [1, Emendanda, Addenda]                true    ICZN
Name.csv:454712 Antherophagus maculipennis      Villa & Villa, 1833     species Antherophagus                           48445   32-36           true    ICZN
```

**Expected behavior**
 There are forma and variety names in Cucujoidea Species File, and they should be included in the CoLDP Name table.

**Environment (please identify where you experience this bug:**
- sfg.taxonworks.org

Ping: https://github.com/Sp2000/colplus-repo/issues/86

**Comment by gdower** [comment]
@mjy, we're still missing some names with variety and forma ranks:

![image](https://user-images.githubusercontent.com/8573609/73472125-28d95d80-4350-11ea-8a9c-68c1918f0edc.png)

Here's a cross-mapping of the CoL vs TaxonWorks synonyms for _Antherophagus pallens_ (Linnaeus, 1758):

CoL | TaxonWorks | Notes
-- | -- | --
Antherophagus fasciatus Roubal, 1935 | Antherophagus nigricornis f. fasciatus Roubal, 1935: 54. | Infraspecies epithet replaced species epithet, wrong rank assignment
Antherophagus fasciferus Roubal, 1935 | Antherophagus pallens f. fasciferus Roubal, 1935: 54. | Infraspecies epithet replaced species epithet, wrong rank assignment
Antherophagus maculipennis Villa & Villa, 1833 | Antherophagus nigricornis var. maculipennis Villa & Villa, 1833: 33. | Infraspecies epithet replaced species epithet, wrong rank assignment
  | Tenebrio pallens Linnaeus, 1758: 418. | Included in Name.csv but missing in Synonym.csv
Antherophagus nigricornis (Fabricius, 1787) |   | Exporter might have misapplied a synonym
Ips nigricornis (Fabricius, 1787) | Ips nigricornis Fabricius, 1787: 46. | Authorship brackets mismatch

(I'll open/update other tickets on the last 3 rows.)

There are a few names in the export that include `var.` but with the rank set to `species` instead of `var.`:

```
grep var\\. Name.csv
448754/current  Phyconomus subtestaceus var. discoideus (Reitter, 1876) species  Phyconomus              subtestaceus                                   false   ICZN
454742/current  Cryptophagus (Micrambe) perrisi var. umbripennis        (Reitter, 1887) species  Cryptophagus    (Micrambe)      perrisi                                        false   ICZN
454740/current  Cryptophagus hesperius var. occidentalis        (Wollaston, 1864)       species  Cryptophagus            hesperius
```

**Comment by mjy** [comment]
Could have been related to original combination issue.

**Comment by proceps** [comment]
var. is invalid status in ICZN. Valid name could not be at the rank variety. It could be treated as a species or subspecies, if the rank is elevated and the name is treated as valid. If the name is a synonym of the species, the rank of the synonym is the same as the rank of valid name. When you export names of the synonyms, you should always get the original combination of the name, and not the current placement, which is always corresponds the current placement and rank of the valid name. Synonyms should be always used in the original form only or in the form of subsequent combination. Not in the form of current name, which may not be present in any publication.

**Comment by mjy** [comment]
> When you export names of the synonyms, you should always get the original combination of the name, and not the current placement, 

Understood.  The question is:

The original combination should be rendered with 'var.'?

**Comment by proceps** [comment]
Yes, In the browse nomenclature, it is rendered with "var." Esentially, you should try to replicate the CoLDP export to match the Browse nomenclature format.

**Comment by gdower** [comment]
@mjy, we're getting closer.

![image](https://user-images.githubusercontent.com/8573609/95236552-b1a47500-07cc-11eb-8d83-ac6b4a591707.png)

The matching lines between TW and CoL are in bold:

- Tenebrio pallens Linnaeus, 1758: 418.
- **Ips nigricornis Fabricius, 1787: 46.**
- Antherophagus nigricornis var. maculipennis Villa & Villa, 1833: 33.
- Antherophagus nigricornis f. fasciatus Roubal, 1935: 54.
- Antherophagus pallens f. fasciferus Roubal, 1935: 54.

The binomials for the var. and f. synonyms are getting exported, but are missing the infraspecies marker and epithet, because the rank is set to species and the infraspeciesEpithet column is empty:

ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
454316/e6f948ce19d9ba9861bb0193c660cf7f | 454316 | Antherophagus nigricornis f. fasciatus | Roubal, 1935 | species |   | Antherophagus |   | nigricornis |   |   |   |   | true | ICZN
454317/6a27534faef5c9d616f1b241709303a5 | 454317 | Antherophagus pallens f. fasciferus | Roubal, 1935 | species |   | Antherophagus |   | pallens |   |   |   |   | true | ICZN
454712/c1a1f8df978cda9517fb6b997d1c7c54 | 454712 | Antherophagus nigricornis var. maculipennis | Villa & Villa, 1833 | species |   | Antherophagus |   | nigricornis |   |   |   |   | true | ICZN

**Comment by gdower** [comment]
The rank is still set to species instead of f. and var., but it's otherwise correct.

**Comment by gdower** [comment]
In the latest version, the trinomials are present but their rank is not set as forma or variety. It should be okay to just put `f.` or `var.` in the rank field, if desired.

https://data.catalogueoflife.org/dataset/2219/name/454316-e6f948ce19d9ba9861bb0193c660cf7f
https://data.catalogueoflife.org/dataset/2219/name/454712-c1a1f8df978cda9517fb6b997d1c7c54

### Observed
ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
454316-e6f948ce19d9ba9861bb0193c660cf7f | 454316-e6f948ce19d9ba9861bb0193c660cf7f | Antherophagus nigricornis f. fasciatus | Roubal, 1935 |   |   | Antherophagus |   | nigricornis | fasciatus |   |   |   | TRUE | ICZN |   |   |  
454317-6a27534faef5c9d616f1b241709303a5 | 454317-6a27534faef5c9d616f1b241709303a5 | Antherophagus pallens f. fasciferus | Roubal, 1935 |   |   | Antherophagus |   | pallens | fasciferus |   |   |   | TRUE | ICZN |   |   |  
454712-c1a1f8df978cda9517fb6b997d1c7c54 | 454712-c1a1f8df978cda9517fb6b997d1c7c54 | Antherophagus nigricornis var. maculipennis | Villa & Villa, 1833 |   |   | Antherophagus |   | nigricornis | maculipennis |   |   |   | TRUE | ICZN |   |   |  
454303-7dfd67765163c7cc639c52e2c776d9bc | 454303-7dfd67765163c7cc639c52e2c776d9bc | Antherophagus ochraceus var. subnitidus | Grouvelle, 1911 |   |   | Antherophagus |   | ochraceus | subnitidus |   |   |   | TRUE | ICZN |   |   |  

### Expected
ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
454316-e6f948ce19d9ba9861bb0193c660cf7f | 454316-e6f948ce19d9ba9861bb0193c660cf7f | Antherophagus nigricornis f. fasciatus | Roubal, 1935 | forma |   | Antherophagus |   | nigricornis | fasciatus |   |   |   | TRUE | ICZN |   |   |  
454317-6a27534faef5c9d616f1b241709303a5 | 454317-6a27534faef5c9d616f1b241709303a5 | Antherophagus pallens f. fasciferus | Roubal, 1935 | forma |   | Antherophagus |   | pallens | fasciferus |   |   |   | TRUE | ICZN |   |   |  
454712-c1a1f8df978cda9517fb6b997d1c7c54 | 454712-c1a1f8df978cda9517fb6b997d1c7c54 | Antherophagus nigricornis var. maculipennis | Villa & Villa, 1833 | variety |   | Antherophagus |   | nigricornis | maculipennis |   |   |   | TRUE | ICZN |   |   |  
454303-7dfd67765163c7cc639c52e2c776d9bc | 454303-7dfd67765163c7cc639c52e2c776d9bc | Antherophagus ochraceus var. subnitidus | Grouvelle, 1911 | variety |   | Antherophagus |   | ochraceus | subnitidus |   |   |   | TRUE | ICZN |   |   |
