### ISSUE TITLE
Bug - CoL - Original combinations missing in CoLDP exports

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#1204]
**Describe the bug**

Original combinations are missing in the CoLDP exports. For example, the original combination *Rhizophagus adustus* is missing for *Bactridium adustum*.

`grep 'Rhizophagus adustus' Name.csv` returns 0 matches.

**To Reproduce**
1. When I export Cucujoidea Species File to CoLDP
2. Original combinations are missing in Name.tsv
3. The records relating original combinations to accepted names are missing in Synonym.tsv
4. The name relationship is missing in NameRel.tsv

[](https://user-images.githubusercontent.com/8573609/69100848-b7ae2d80-0a23-11ea-96a5-6b46596efd79.png)

**Expected behavior**
Original combinations should be included in Name.tsv, a record should be added to Synonym.tsv to relate them with accepted names in Taxon.tsv, and the name relationship should be expressed in the NameRel table.

**Environment (please identify where you experience this bug:**
- sfg.taxonworks.org

Ping: https://github.com/Sp2000/colplus-repo/issues/86

**Comment by mjy** [comment]
Makes sense, as this is not a name but a set of relationships in TW.

**Comment by gdower** [comment]
In thinking about this further, we should also add a record to NameRel with the [name relationship  type](http://api.catalogue.life/vocab/nomreltype) of basionym.

**Comment by gdower** [comment]
The original combinations are showing up in Name.csv now, but some of them are missing in Synonym.csv:

Name.csv

ID | scientificName | authorship | rank | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
448639 | Bactridium adustum | (Reitter, 1873) | species | Bactridium |   |   |   | 47142 | 27-48 |   | FALSE | ICZN |   |   |  
448639/current | Rhizophagus adustus | (Reitter, 1873) | species | Bactridium |   |   |   |   |   |   | FALSE | ICZN |   |   |  

Sample of Synonym.csv showing some original combinations:

taxonID | nameID | status | remarks | referenceID
-- | -- | -- | -- | --
86701 | 448534 | synonym |   |  
87010 | 448839 | synonym |   |  
86651 | 448482 | synonym |   |  
86789 | 448623 | synonym |   |  
86798 | 454053 | synonym |   |  
86674 | 448505 | synonym |   |  
86753 | 448584 | synonym |   |  
86712 | 448544 | synonym |   |  
86821 | 448652 | synonym |   |  
86821 | 448652/current | synonym |   |  
86789 | 448624 | synonym |   |  
86908 | 448742 | synonym |   |  
86593 | 448424 | synonym |   |  
86593 | 448424/current | synonym |   |  
87017 | 448848 | synonym |   |  
87017 | 448848/current | synonym |   |  

Synonym.csv is missing the *Rhizophagus adustus* original combination below:

taxonID | nameID | status | remarks | referenceID
-- | -- | -- | -- | --
86809 | 448639/current | synonym |   |  


![image](https://user-images.githubusercontent.com/8573609/71297974-4972c880-234b-11ea-86eb-f4a23556767c.png)

Here's the [testing dataset in the CoL Clearinghouse](https://data.catalogue.life/catalogue/3/dataset/2064/metrics) (which may still disappear), and the [otu download from sfg.taxonworks.org](https://github.com/SpeciesFileGroup/taxonworks/files/3990657/coldp_otu_id_85906_2019-12-20T22_41_27%2B00_00.zip).

We're getting closer though!

**Comment by mjy** [comment]
Add NameRel as new issue.

**Comment by gdower** [comment]
_Bactridium adustum_ (Reitter, 1873) is still missing the original combination _Rhizophagus adustus_ Reitter, 1873, because the relationship is missing in Synonym.csv:

![image](https://user-images.githubusercontent.com/8573609/73476971-fda73c00-4358-11ea-9099-cda85d858ebf.png)

There are a 123 original combinations included in Synonym.csv, but they might not be using the correct IDs. For example, here's whats in the export for one of them:

```

Synonym.csv
taxonID nameID          status
540035  623784/current  synonym

Taxon.csv
taxonID parentID nameID
540035  539176  623783

Name.csv
nameID  scientificName                  authorship              rank    genus subgenus species ...
623783  Brachypterolus pulicarius       (Linnaeus, 1758)        species Brachypterolus                                          1758    false   ICZN
623783/current  Dermestes pulicarius    (Linnaeus, 1758)        species  Dermestes               pulicarius                                     false   ICZN
623784  Brachypterolus gravidus (Illiger, 1798) species Brachypterolus                          10668   xlii + 510 + [1]                false   ICZN
```

Taxon 540035 has the name usage *Brachypterolus pulicarius* (Linnaeus, 1758) and the original  combination *Dermestes pulicarius* Linnaeus, 1758, so the Synonym.csv should have:

540035  62378**3**/current  synonym

There is no name with the NameID `623784/current` in Name.csv.

**Comment by gdower** [comment]
Original combinations like Rhizophagus adustus Reitter, 1873 aren't getting exported:

![image](https://user-images.githubusercontent.com/8573609/95252693-ede2d000-07e2-11eb-91ee-c82247ac6e3d.png)

It has the new combination:

ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
448639 | 448639 | Bactridium adustum | (Reitter, 1873) | species |   | Bactridium |   | adustus |   | 47142 | 27-48 |   | false | ICZN | http://purl.obolibrary.org/obo/NOMEN_0000224

**Comment by gdower** [comment]
The original combination is added, but the basionym the synonym and basionym relationships have the wrong IDs:

### Name.csv
  | ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
current | 448583 | 448583 | Monotoma (Monotoma) longicollis | (Gyllenhal, 1827) | species |   | Monotoma | Monotoma | longicolle |   | 47962 | 762 |   | FALSE | ICZN | http://purl.obolibrary.org/obo/NOMEN_0000224 |   |  
expected | 448583 | 448583/694e0ac8cc7bb34451d8b073d94d948e | Monotoma (Monotoma) longicollis | (Gyllenhal, 1827) | species |   | Monotoma | Monotoma | longicollis |   | 47962 | 762 |   | FALSE | ICZN | http://purl.obolibrary.org/obo/NOMEN_0000224 |   |  
current | 448583/694e0ac8cc7bb34451d8b073d94d948e | 448583 | Cerylon longicolle | Gyllenhal, 1827 | species |   | Cerylon |   | longicolle |   |   |   |   | TRUE | ICZN |   |   |  
expected | 448583/694e0ac8cc7bb34451d8b073d94d948e | 448583/694e0ac8cc7bb34451d8b073d94d948e  | Cerylon longicolle | Gyllenhal, 1827 | species |   | Cerylon |   | longicolle |   |   |   |   | TRUE | ICZN |   |   |  



### Synonym.csv
  | taxonID | nameID | status | remarks | referenceID
-- | -- | -- | -- | -- | --
current | 86753 | 448583 |   |   |  
expected | 86753 | 448583/694e0ac8cc7bb34451d8b073d94d948e |   |   |

**Comment by gdower** [comment]
This seems resolved!
