### ISSUE TITLE
"Taxon name" autocomplete renders broken html when 'I' is input"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1207]
**Describe the bug**

When in "Browse Nomenclature" I enter "i" into the search bar I get broken HTML results instead of properly rendered text. 

**To Reproduce**
1. When I go to "Browse Nomenclature" task.
2. Then I enter "I" or "i" or "<i" "or "<" into the search bar.
3. See list of results with broken HTML tags.
![image](https://user-images.githubusercontent.com/11411328/70078516-ac2c3c00-15b7-11ea-843d-b9b9298164af.png)

![image](https://user-images.githubusercontent.com/11411328/70078498-a20a3d80-15b7-11ea-9c2e-96c39bd2a004.png)

**Expected behavior**
Should render correctly, and "<" should (probably?) return no results.

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by mjy** [comment]
Easiest solution is to not fire request until 2 letters are sent.
