### ISSUE TITLE
Enhancement - CoL - Add NameRel table with references to CoLDP exports

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#1211]
**Describe the bug**

In the CoLDP format, the synonym references are missing. As @mjy suggested, Markus added a referenceID to the Synonym table, so it is now possible to add them there. However, the NameRel table fits better with the current TaxonWorks data model, so it might be better to add the NameRel table with references as an enhancement.

![](https://user-images.githubusercontent.com/8573609/69100939-e5937200-0a23-11ea-9f11-a17ab68667fd.png)

**Expected behavior**
The CoLDP exporter should add a NameRel table with name relations and their references.

**Environment (please identify where you experience this bug:**
- sfg.taxonworks.org

Ref: https://github.com/Sp2000/colplus-repo/issues/86, https://github.com/SpeciesFileGroup/taxonworks/issues/1204

**Comment by mjy** [comment]
Currently on hold to resolve 2 issues:

1) Potential mapping of NOMEN to http://api.catalogue.life/vocab/nomreltype
2) Potential changes in design of NAMEREL table to clarify directionality
