### ISSUE TITLE
Can't modify/save changes on some records - saving takes forever

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1215]
**Describe the bug**
When I try to make changes to some records (e.g. INHS Insect Collection 455139) - it does not save properly - but instead spins for 2-3 minutes and then times out (I think)

**To Reproduce**
1. When I go to "Comprehensive specimen digitization" and navigate to some records (see example above). 
2. Then I change something (e.g. add an OTU, or parse part of the locality, or add something to buffered label data)
3. And I try to save - it spins for a while (2-3 minutes) but I never get confirmation of save.
4. Upon refreshing and reloading that record - none of the changes are saved. 

Before
![image](https://user-images.githubusercontent.com/11411328/70342241-41c70600-181a-11ea-9678-848089484697.png)

Change
![image](https://user-images.githubusercontent.com/11411328/70342269-4e4b5e80-181a-11ea-8b3a-62f3b0bafc54.png)

Spinning forever:
![image](https://user-images.githubusercontent.com/11411328/70342292-599e8a00-181a-11ea-94db-081e45467b5e.png)

Record after refresh and reloading that record, NOTE change is not saved:
![image](https://user-images.githubusercontent.com/11411328/70342403-8a7ebf00-181a-11ea-91a1-af8fa3de5653.png)

**Expected behavior**
Changes should save and save quickly. 

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by mjy** [comment]
Close with a temporary fix to throttle indexing for more than 40 records.
