### ISSUE TITLE
Task - Browse Nomenclature - Edit button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1223]
The link is broken on Edit button. it does not go to edit page, instead it opens Blank New TaxonName page.

**Comment by mjy** [comment]
Screenshot of the button please.

**Comment by proceps** [comment]
Please see also issue #1088

**Comment by mjy** [comment]
```
When I go to Browse nomenclature, 
   and I click on the green round icon for 'edit'
```
<img width="73" alt="Screen Shot 2019-12-09 at 10 36 18 AM" src="https://user-images.githubusercontent.com/22600/70454311-d4acae00-1a6f-11ea-8528-38d783744a41.png">

```
      then I am taken to the new taxon name page
         and the object id is properly set (see screenshot)
            but the form is not loaded
```

<img width="846" alt="Screen Shot 2019-12-09 at 10 36 29 AM" src="https://user-images.githubusercontent.com/22600/70454373-f1e17c80-1a6f-11ea-9cb9-2022f2588d17.png">

**Comment by jlpereira** [comment]
Fixed
