### ISSUE TITLE
Entering images - caption saving

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1231]
**Image captions must be saved using "update" button, using only "save" button, it disappears**

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <UCD 2019-09-25 15:52:16 -0500>
- Production

**Comment by mjy** [comment]
Thanks. In these kind of reports adding (annotated) screenshots will help us lock down what specifically is being referenced.  There is a lot that goes on in this task.

**Comment by jlpereira** [comment]
I think this one is duplicate: #1228
