### ISSUE TITLE
Entering images - setting atributions

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1232]
**Setting attribution - I had issue with "š", in other words if I created myself as Petr Janšta and then tried to find me next time, I had to type specifically "Janš.." instead of just "Jans...". It is ok when I am using Czech keybord but not for those without **

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <UCD 2019-09-25 15:52:16 -0500>
- Production

**Comment by mjy** [comment]
If you add an alternate spelling (anntotation browser -> alternate value) then the autocomplete will search both values.
