### ISSUE TITLE
New image task - add option to add "Tags" and "Data Attributes" to created collection objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1237]
In the New Image task I want to be able to add both "Tags" and "Data Attributes" to newly created collection objects. 

Use case:
I want to add all my Lepidoptera project images and tag them with "LepProject2019" or data attribute: "Member of project" -> "object" -> "My project name"

**Comment by jlpereira** [comment]
Done
