### ISSUE TITLE
Task - Edit TaxonName - new taxon

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1238]
When I create a new TaxonName (enter the name and parent), the form does not recognizes the parent code of nomenclature any more and offers me to select ICZN, I have also to select the rank manually, the system does not pick default option.

* [x] Fix auto-recognition and selection of code based on parent CODE (note, no selection happens with "Root")
* [x] Fix Ctrl + P
* [x] Write feature spec for Ctrl + P
* [x] Fix Ctrl  + D
* [x] Write feature spec for Ctrl + D

**Comment by mjy** [comment]
@proceps this issue description could be improved ;).  Title is not indicative of the issue; there are 4(?) individual issues that could be handled seperately.  At minimum please write useful titles and give us checkboxes in the issue, at best add seperate issues (and write useful titles).

Time spent in issue triage means less time coding...
