### ISSUE TITLE
New Source task - Can't add Serials

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1241]
**Describe the bug**
I can't add serials or update them in the New Source task. Old ones won't change, new ones won't add. 

**To Reproduce**
1. When I go to "Task: New Source"
2. Then I try to add a serial from the "Serials" autocomplete
3. Then something is added.
4. But the serial is not saved to the source. 

Selecting a serial:
![image](https://user-images.githubusercontent.com/11411328/70937680-4fdf0880-200a-11ea-91ec-a24ae7c8c13b.png)

Result:
![image](https://user-images.githubusercontent.com/11411328/70937701-608f7e80-200a-11ea-8901-6029c347f496.png)

After save and refresh (note old source is "Elytra, Toyko" - so that hasn't changed even after selecting "Zootaxa"
![image](https://user-images.githubusercontent.com/11411328/70937746-78ff9900-200a-11ea-9752-285b97e06769.png)

Also note: I can still do this through the old "Data" source interface just fine - so I think it's an issue with the smart selector. 
Correction: the old data new source interface DOES NOT add the serial, but just adds it to the JOURNAL field. So that's ALSO broken. 

**Expected behavior**
Should be able to change or add a new serial. 

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by mjy** [comment]
* [ ] Let's get a feature spec added here too

**Comment by mjy** [comment]
@tmcelrath This is fixed.  Will close when we have a spec.

Note `smart-selector-serials-autocomplete`
