### ISSUE TITLE
Project admin cannot access preferences

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1242]
**Describe the bug**

As a project administrator, I cannot access the preferences screen. 

**To Reproduce**
1. When I go to "Project" tab. 
2. Then I click on "Preferences"
3. And I am an administrator.
4. Then I get redirected to my personal Dashboard page.

Screen before clicking on preferences (note that I am an administrator):
![image](https://user-images.githubusercontent.com/11411328/71102412-14654b00-217e-11ea-86b7-78f74ed5a85c.png)

Redirect after click:
![image](https://user-images.githubusercontent.com/11411328/71102329-e97af700-217d-11ea-8e01-fa6b7d501bd1.png)

**Expected behavior**
Should be able to get to the preferences page.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- (NOTE: not experienced in Sandbox)
- Chrome

**Comment by LocoDelAssembly** [comment]
@tmcelrath the problem persists if you open the browser in incognito mode?

To enter incognito mode in Chrome these are the shortcuts:
```
Windows, Linux, or Chrome OS: Press Ctrl + Shift + n.
Mac: Press ⌘ + Shift + n.
```
And then enter again into sfg.taxonworks.org

**Comment by tmcelrath** [comment]
Yes - persists in incognito mode.

**Comment by LocoDelAssembly** [comment]
```
2.6.5 :001 > User.find_by(name: 'Tommy McElrath').is_superuser?
 => false 
2.6.5 :002 > User.find_by(name: 'Tommy McElrath').administers_projects?
 => true 
```
https://github.com/SpeciesFileGroup/taxonworks/blob/a4c558ca25128a24552e373f82ba5c19aea49b3f/app/controllers/tasks/projects/preferences_controller.rb#L4

@mjy is it intentional to now allow super users to alter project preferences? (Haven't checked if the controller is able to tell whether the user is actually a member with admin rights on the project, with those includes alone could be that it is enough to be admin member of at least one project and also be superuser)

**Comment by mjy** [comment]
Administrators do *anything*.  Project administrators can modify project preferences, yes.

**Comment by mjy** [comment]
There is supposed to be one category of user that is either admin or project admin.  That's the group that should be used in this case.  I thought it was super_users, but looks like that is not the case.

**Comment by LocoDelAssembly** [comment]
Looked at the wrong `is_superuser?` I think (User vs sessions). When looking sessions code I don't see why access is not granted. Will try on a local copy and debug there. Dump transfer will be finished in around 5 minutes.

**Comment by LocoDelAssembly** [comment]
This would be the fix
```diff
hernan@hernan-pc:~/Projects/taxonworks$ git diff
diff --git a/app/controllers/tasks/projects/preferences_controller.rb b/app/controllers/tasks/projects/preferences_controller.rb
index 88f465e01..b44be8173 100644
--- a/app/controllers/tasks/projects/preferences_controller.rb
+++ b/app/controllers/tasks/projects/preferences_controller.rb
@@ -1,6 +1,5 @@
 class Tasks::Projects::PreferencesController < ApplicationController
   include TaskControllerConfiguration
-  before_action :require_administrator_sign_in
   before_action :require_superuser_sign_in
   before_action :can_administer_projects?
 
```
Sounds right?
