### ISSUE TITLE
Add "Clone" button to date annotator in Comprehensive specimen digitization form

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1245]
When I am parsing a date in Comprehensive specimen digitization form - having a "Clone" button for copying the start date to the end date would be very useful. Most collection objects have the same or very similar start and end dates - so cloning the first entry would save time. 

Spec:
<img width="355" alt="date_spec" src="https://user-images.githubusercontent.com/11411328/71105058-7d4ec200-2182-11ea-9457-d5ca31f944a6.png">

**Comment by proceps** [comment]
I would not enter the end date if it is the same with the start date. But clone button could be useful if only the day is different.

**Comment by mjy** [comment]
Idea: Maybe "click -> modal" -> [ +1 day, +2 days ] ...

**Comment by tmcelrath** [comment]
@mjy probably over-complicating it to be honest. Harder to count # of days than to just modify the cloned date.

**Comment by mjy** [comment]
Agreed

**Comment by tmcelrath** [comment]
Thanks!
