### ISSUE TITLE
Task - New combination - editing

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1247]
When I am in the Browse nomenclature Task and select a combination as a Taxon. I can click the edit green button (or use a object radial) to navigate to the Combination task. When I get to the page with Combination, I would like to have all taxon names (which are already known from the combination relationship) be selected as default taxa for appropriate ranks. At the moment the first taxon in each rank category is selected, and the previous selection is get lost.

**Comment by mjy** [comment]
@proceps Are you sure we don't just display the selected record on top?

**Comment by mjy** [comment]
@proceps Provide ID of example name please.

**Comment by proceps** [comment]
This is a combination
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=448919 (production, 3i database)
When I click edit button, the species name is missing. When I click unlock button, the species list is only 2 names (of about 20 which should be there). And those available names are wrong one

**Comment by mjy** [comment]
Remember- no more plant name in that task, this means fewer to show... in
part.

**Comment by proceps** [comment]
Yes, excellent. But, when I copy the combination string and process it as a new combination "Omolicna (Omolicna) uhleri" I have about 20 entries for the species name. If I use edit button from browse nomenclature, for an existing combination (see above). I receive only 2 entries for the species, and both are for wrong species.

**Comment by mjy** [comment]
The match is likely on a gender, and failing?

**Comment by proceps** [comment]
Not in this example. species name is "uhleri" and if combination processed as new, it returns the longer list of protonyms. Both combinations are exactly the same. In cases of gender, yes, it potentially could fail. But even in those cases I would expect to see a selected taxon as an available option in the pick list, which is selected by default.

**Comment by mjy** [comment]
Issue is that current ids are not merging into parsed result.
