### ISSUE TITLE
Source - recent and report list as a user I want to one-click open the document drop

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1253]
When there is no document in the Document column, then I want to add one.  Either (in order of @mjy preference):

* add a link that auto-opens the annotator to the Documentation slice
* add a PDF drop target on every record/inline
* add a link to open a PDF target inline (requires more form/state management, but concept maybe useful in multiple places for documents/images).

**Comment by proceps** [comment]
implemented
