### ISSUE TITLE
SQED Image box visualization issues 

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1256]
**Describe the bug**
When using the OCR/Zoom box - sometimes the "zoom" feature does not correspond with where it is being shown in the box.

**To Reproduce**
1. When I open some images in the SQED image processing task (e.g. https://sfg.taxonworks.org/tasks/accessions/breakdown/sqed_depiction/77053)
2. Then I drag the OCR box to some labels.
3. Then I don't see the labels in the zoomed-in visualization box and OCR fails.

Issue:
![image](https://user-images.githubusercontent.com/11411328/71203335-659b3a80-2263-11ea-8e4f-aae790b22394.png)

Weird bounding boxes:
![image](https://user-images.githubusercontent.com/11411328/71203623-efe39e80-2263-11ea-8a06-24754ca52ab3.png)

**Expected behavior**
Box visualized should correspond with zoom/OCR.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
See also #1437

**Comment by proceps** [comment]
is it still an issu?

**Comment by jlpereira** [comment]
If I remember well, we already fix this

**Comment by proceps** [comment]
I will close for now
