### ISSUE TITLE
Collection objects filter - Add "Search by Data Attribute" option

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1258]
When I am in the Collection Objects filter - I should be able to search by created Internal Attributes like "Country" and "Body of Water". Drop down list of created attributes would be acceptable.

**Comment by mjy** [comment]
@jlpereira do we have a generic facet for this?

**Comment by mjy** [comment]
We also need ability to handle presence alone.

**Comment by mjy** [comment]
Related: https://github.com/SpeciesFileGroup/taxonworks/issues/1431

**Comment by mjy** [comment]
Dulicate of #2922.
