### ISSUE TITLE
Clipboard activating without command keys

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1260]
**Describe the bug**
Sometimes the clipboard feature activates without pressing the appropriate command key (e.g. "Ctrl"

**To Reproduce**
1. When I set something to my clipboard.
2. Then I go about my business, entering other panes, annotators, or other pages.
3. And I use the appropriate number keys to type numbers or something else
4. The clipboard will activate without me pressing "Ctrl"

Typing "794" results in "7941000m" (with 1000m saved as Clipboard shortcut Number 4):
![image](https://user-images.githubusercontent.com/11411328/71213643-ad2cc100-2279-11ea-8eac-bcb859e80a25.png)
Clipboard:
![image](https://user-images.githubusercontent.com/11411328/71213708-dfd6b980-2279-11ea-9947-aaeca90db399.png)

**Expected behavior**
Should only "paste" when using appropriate command "Ctrl-#"

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
@tmcelrath Just to eliminate-  Do you have any browser plugins that manage fields in your browser?  Can you check your browser settings?

**Comment by tmcelrath** [comment]
Will try in incognito

**Comment by tmcelrath** [comment]
Replicated in Incognito mode. Not a browser plugin issue.

**Comment by tmcelrath** [comment]
Replicate:
1) Add some text to your clipboard
2) Go to Annotation Browser - search for some annotations.
3) Modify something with Annotation radial.
4) Go to another page by option-clicking - basically go to something else in TW and edit something.
5) Go back to Annotation page and try modifying something in the Annotation radial - if you use the number keys you will get the text without using "Ctrl"

**Comment by tmcelrath** [comment]
Currently - I'm able to reliably replicate this bug while associating "Flipped label" depictions with their correct collection objects.

**Comment by mjy** [comment]
I can not replicate :(.  Can you try in another browser?

**Comment by mjy** [comment]
@tmcelrath I'm going to close this as it seems specific to your machine/experience. IIRC you could hit escape to resolve the problem, or click another keypress?

**Comment by tmcelrath** [comment]
Does seem to be specific to me, yeah. I can't figure out how to stop it (e.g. I can't figure out what "sticky keys" are being activated) but I can make it stop happening by pressing command three times quickly. Fine if closed.

**Comment by debpaul** [comment]
@tmcelrath can you recheck this when you have a minute? (Assuming some recent fixes have been pushed to production), this might? be fixed...

**Comment by mjy** [comment]
Nothing live
