### ISSUE TITLE
Task - New source - date from CrossRef

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1266]
Day and Month are not resolved from CrossRef in the New Source task. they were resolvable with the old interface. I am working with new Zootaxa publications.

**Comment by mjy** [comment]
Exact DOI as example?

**Comment by proceps** [comment]
I did multiple. The last one: http://dx.doi.org/10.11646/zootaxa.4711.3.5

**Comment by mjy** [comment]
Remember that crossref does not return a standard set of values, it differs all the time (we closed this exact issue prior as well).  So, it didn't work before (nothing has changed in the code), you just hit responses that had values.

We can make it the parsing better.  In the case of this DOI there is no day returned, and the month is in 'dec', which isn't a valid value in our model.  I will try and get the 'dec' to convert to integer by detecting it.

**Comment by mjy** [comment]
Aha.  This is infact an interface problem, not a parsing issue.  @jlpereira the month picker must match three-letter month values as keys: `jan feb mar apr may jun jul aug sep oct nov dec`
