### ISSUE TITLE
DwC index - new fields (was: Not enough displayed/exported fields in "Collection objects filter")

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1269]
When I do a search in "Collection objects filter" I want to see more fields associated with that Collection Object. 

All fields needed are mentioned below in the comments. [EDITED TCM]

@tmcelrath - are these actually dwc fields?  Links?

Missing fields:
<strike>"Buffered" fields e.g. "verbatimDetermination" "verbatimLocalityLabel" "verbatimOther"
* [ ] verbatimDetermination
<strike>* [ ] verbatimLocalityLabel already exists - verbatim_locality from CE, not buffered</strike> 
* [ ] verbatimOther</strike>

<strike> Determination fields: "determinationOTU (or whatever it's called) and associated "determinedBy" and "determinationYear" </strike>

@tmcelrath - below are drawn from TaxonDetermination, only first, or all or what todo?

<strike>* [ ] determinedBy
* [ ] determinationYear
</strike>

<strike>Also, they should be displayed by type of field, not alphabetically. E.g. all "Locality" fields should be logically displayed e.g. "Country" then "stateProvince" then "county" then "decimalLongitude" etc ... and then "Family" then "Genus" then "specific epithet".
</strike> See #1314.

All these fields also need to be exported as well as displayed.

**Comment by tmcelrath** [comment]
Also need to search by custom "Internal Attribute" fields such as "SpecialCollection"

**Comment by mjy** [comment]
If by search you mean in the filter vs. scanning a table then add that internal attribute as a new issue.

**Comment by tmcelrath** [comment]
Right - yeah, got the issues conflated.

**Comment by tmcelrath** [comment]
You mean #1258? :)

**Comment by mjy** [comment]
@tmcelrath If you can help out by finding the DWC terms that you want each of the check boxes to fill it would be appreciated.  Can you double check that this is the list you have in mind?

**Comment by tmcelrath** [comment]
@mjy working on it - is "recordedBy" being properly parsed? Just updated a record to have two collectors and neither is exported in the "recordedBy" field.

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Identification (http://rs.tdwg.org/dwc/terms/Identification):
typeStatus: http://rs.tdwg.org/dwc/terms/typeStatus (from Type material)
identifiedBy: http://rs.tdwg.org/dwc/terms/identifiedBy (from Determinations)
dateidentified: http://rs.tdwg.org/dwc/terms/dateIdentified (from Determinations)

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Taxon (http://rs.tdwg.org/dwc/terms/Taxon):
kingdom: http://rs.tdwg.org/dwc/terms/kingdom - infraspecificEpithet (http://rs.tdwg.org/dwc/terms/infraspecificEpithet) (right now we have Family, Genus, and Species, need more)
taxonRank: http://rs.tdwg.org/dwc/terms/taxonRank

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Organism (http://rs.tdwg.org/dwc/terms/Organism):
previousIdentifications: http://rs.tdwg.org/dwc/terms/previousIdentifications (from Buffered Determinations, I think this is the closest we are going to get to our "Buffered Determinations" field, and including current determinations won't hurt anything, I don't think).

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Event (http://rs.tdwg.org/dwc/terms/Event):
verbatimEventDate: http://rs.tdwg.org/dwc/terms/verbatimEventDate (from Collecting Event Verbatim Date)
habitat: http://rs.tdwg.org/dwc/terms/habitat (from Collecting Event Verbatim Habitat)
samplingProtocol: http://rs.tdwg.org/dwc/terms/samplingProtocol (from Collecting Event Verbatim Method)
fieldNumber: http://rs.tdwg.org/dwc/terms/fieldNumber (from combination of Namespace for Trip Code + Trip Code)

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class ResourceRelationship (http://rs.tdwg.org/dwc/terms/ResourceRelationship):
relationshipOfResource: http://rs.tdwg.org/dwc/terms/relationshipOfResource (from Biological Associations)
relationshipAccordingTo: http://rs.tdwg.org/dwc/terms/relationshipAccordingTo (from Biological Associations)
relationshipEstablishedDate: http://rs.tdwg.org/dwc/terms/relationshipEstablishedDate (either from date specimen collected or from reference)
resourceID: http://rs.tdwg.org/dwc/terms/resourceID (TW IDs?)
relatedResourceID: http://rs.tdwg.org/dwc/terms/relatedResourceID (TW IDs?)
relationshipRemarks: http://rs.tdwg.org/dwc/terms/relationshipRemarks (from Collecting Event Habitat if a relationship is created - this should reference the actual description of the relationship)

This section might need more working out - would appreciate input from @mjy and @jlpereira

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Occurenence (http://rs.tdwg.org/dwc/terms/Occurrence):
recordedBy: http://rs.tdwg.org/dwc/terms/recordedBy (already in Export but not sure processed/exported correctly)
sex: http://rs.tdwg.org/dwc/terms/sex (from Biocuration)
lifestage: http://rs.tdwg.org/dwc/terms/lifeStage (from Biocuration)
associatedMedia: http://rs.tdwg.org/dwc/terms/associatedMedia (from depictions? can we grab links to images that would be publicly available?)
associatedTaxa: http://rs.tdwg.org/dwc/terms/associatedTaxa (from Biological Relationships)
otherCatalogNumbers: http://rs.tdwg.org/dwc/terms/occurrenceRemarks (from verbatim "Other Labels", I think this is the best place to put "Unknown Data" but feel free to disagree)

**Comment by tmcelrath** [comment]
Need DWCA Export fields from Class Location (http://purl.org/dc/terms/Location):
waterBody: http://rs.tdwg.org/dwc/terms/waterBody (we don't have this in Comprehensive yet, but I think Ed DeWalt will need it soon for aquatics stuff)
minimumElevationInMeters: http://rs.tdwg.org/dwc/terms/minimumElevationInMeters (from Collecting Event)
maximumElevationInMeters: http://rs.tdwg.org/dwc/terms/maximumElevationInMeters (from Collecting Event)
verbatimElevation: http://rs.tdwg.org/dwc/terms/verbatimElevation (from verbatim elevation in Collecting Event)
coordinateUncertaintyInMeters: http://rs.tdwg.org/dwc/terms/coordinateUncertaintyInMeters (from either verbatim georeference uncertainty or from uncertainty on georeference, not sure how to handle polygons)
verbatimCoordinates: http://rs.tdwg.org/dwc/terms/verbatimCoordinates (from verbatim Coordinates fields)

**Comment by tmcelrath** [comment]
Also need to add newly released DWC GBIF fields: recordedByID (https://github.com/tdwg/dwc/issues/102) and identifiedByID (https://github.com/tdwg/dwc/issues/101) (for identifiers on people): e.g. ORCID/WikiData

**Comment by mjy** [comment]
* [ ] georeferenceProtocol
