### ISSUE TITLE
Task - Edit TaxonName - Error message for synonym name

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1270]
I have a family with is treated as a synonym of another family, all children were moved to the valid family.
1. I did not see a pop up message to move children to the valid taxon and related section
2. I am getting an error message (see the picture).

![image](https://user-images.githubusercontent.com/5597748/71751689-f7996a80-2e41-11ea-8b5f-6dc6d9354433.png)

the taxon in question is in 3i database
https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=408911

**Comment by jlpereira** [comment]
Fixed, @proceps . The manage synonyms section should be visible now for FamilyGroups too. Let me know if the result you see there are correct.
