### ISSUE TITLE
Task - Digitization- Failed requests not properly handled in response

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1273]
Leads to infinite spin even when saved (sometimes). 

https://files.gitter.im/tmcelrath/mWXs/image.png
![image](https://user-images.githubusercontent.com/11411328/71832373-6956fb80-3070-11ea-954c-f7dfe412f50f.png)

**Comment by mjy** [comment]
* The 404 for the `for?` to containers is a correct response, it might not be the issue (there is no container for the object)

**Comment by tmcelrath** [comment]
Chrome environment on Production.

**Comment by mjy** [comment]
* Handling the response from the `POST` to `taxon_determinations` may be the culprit

**Comment by tmcelrath** [comment]
<img width="731" alt="Screen Shot 2020-01-06 at 11 08 52 AM" src="https://user-images.githubusercontent.com/11411328/71834500-fdc35d00-3074-11ea-8b29-e83a0dc75cb0.png">

**Comment by tmcelrath** [comment]
First I get this one:
Upon "Digitize" task load:
<img width="731" alt="Screen Shot 2020-01-06 at 11 10 35 AM" src="https://user-images.githubusercontent.com/11411328/71834656-55fa5f00-3075-11ea-84a4-8e1d7435598a.png">

**Comment by tmcelrath** [comment]
Then I get this one upon saving the whole record (for instance when doing "save and new"): 
<img width="731" alt="Screen Shot 2020-01-06 at 11 08 52 AM" src="https://user-images.githubusercontent.com/11411328/71834813-b2f61500-3075-11ea-98fd-4c2702720433.png">

**Comment by mjy** [comment]
I don't know why we are getting 503 (service not available) on `otus/select options`.  This is almost certainly the issue.

@LocoDelAssembly I'm not seeing emails on 503s.  I'm not sure that we want to get them, but something to think about.

**Comment by tmcelrath** [comment]
Sometimes a hard reset on the page works. For instance - I couldn't get a record to do "Save and Next" after two different tries - then I did a hard page reset and it worked the next time.

**Comment by LocoDelAssembly** [comment]
Is this still reproducible? Would be nice to see the response body of that 503 to have a clue where it is being generated (rails or proxy). Since it takes 1.0 minutes, looks like it is a timeout. Wonder if the ActiveRecord connection pool of 5 is too low (although it should appear in logs if it is and couldn't find anything).

**Comment by mjy** [comment]
@tmcelrath `response body` is visible via the developers panel via the network tab as well, in case you turn up some more of these.

**Comment by tmcelrath** [comment]
@LocoDelAssembly @mjy Reponse body of 503 error:
![image](https://user-images.githubusercontent.com/11411328/71922503-a7c3e780-3150-11ea-9efd-9a1e9caeb93b.png)

**Comment by tmcelrath** [comment]
Three errors again:
<img width="930" alt="Screen Shot 2020-01-07 at 1 23 24 PM" src="https://user-images.githubusercontent.com/11411328/71922643-f5405480-3150-11ea-8a6c-9c34a369125c.png">
503 error:
![image](https://user-images.githubusercontent.com/11411328/71922716-1c972180-3151-11ea-8c0e-5032a6d3b701.png)

422 error:
![image](https://user-images.githubusercontent.com/11411328/71922672-00938000-3151-11ea-8559-60a2cd926f0a.png)
404 error:
![image](https://user-images.githubusercontent.com/11411328/71922697-10ab5f80-3151-11ea-8d01-60c94d7e38dc.png)

**Comment by LocoDelAssembly** [comment]
Perfect. Thanks @tmcelrath . It is a problem with the proxy. This likely explain the [499](https://httpstatuses.com/499) errors I've seen on nginx logs too.

**Comment by tmcelrath** [comment]
Just reproduced by clicking the "Now" button. 2020 by itself seems okay, but the "now" button which added months and days causes the 1036908.json error:
![image](https://user-images.githubusercontent.com/11411328/71923906-9cbe8680-3153-11ea-8d9a-bab70dc52167.png)

**Comment by mjy** [comment]
@jlpereira You likely have to send month as three letter short code?

**Comment by LocoDelAssembly** [comment]
Still something very odd. Why 2019??? https://github.com/SpeciesFileGroup/taxonworks/blob/d54093277233d9be9578f680f4591f2b25fe2b91/app/models/taxon_determination.rb#L61 (but just checked servers and all seem to be in 2020)

**Comment by mjy** [comment]
A cached response from Varnish?

**Comment by tmcelrath** [comment]
I've done 20+ records since avoiding it and have not replicated. Decently sure that's the issue.

**Comment by LocoDelAssembly** [comment]
> A cached response from Varnish?

No, just pods born last year and still standing... Wish I had figured this out first instead of looking at sky and sea how could it be capped to 2019. Varnish wasn't caching (which would have been very unexpected to do so with this kind of request BTW), checked logs that confirmed it did connect to the backend.

We have to check other validators for errors like this. Evidently ActiveRecord validation params are not re-evaluated on every instance creation.
