### ISSUE TITLE
Add "Previous/Next by identifier" buttons to "Digitize" task

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1274]
When I am in the "Digitize" task - I want to be able to edit previous records I just entered by just clicking "Previous" or "Next" button to quickly toggle between records without having to search by identifiers each time. Similarly to "Browse Collection Objects". Could have both "by identifier" and "by TW identifier" options - but "By identifier" is more important.

**Comment by mjy** [comment]
Completely agree, been wanting this too.
