### ISSUE TITLE
Task - Digitization: Georeference needs to be able to input lat/long and circle uncertainty

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1276]
* [x] Section 1:  When I georeference, and I want to paste in new, non-verbatim based lat long, then I can not paste the values into the Georeference form.
* [x] Section 1 When I am in the georeference form then I need to be able to pick an uncertainty or enter one manually
* [x] Section 2 Geolocate input - When I paste a full value derived from GeoLocate, then I POST type 'Georeference::Geolocate' and `iframe_response: <value` (I think, have to double check)
* [x] Georeference button count does not update on first use, has to be open/closed again
* [x] If I select a Geographic Area, then when I open the Georeference modal, I should be zoomed to the corresponding shape (if it exists)

**Comment by jlpereira** [comment]
Done.
