### ISSUE TITLE
Task - Edit nomenclature - Delete author

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1280]
In the Author section of the form, I cannot delete neither original source, no the role using the trash can button. I can delete the source using radial annotator, but there is no alternative way to delete the Role.

**Comment by jlpereira** [comment]
I can't replicate it @proceps, which taxon it is?

**Comment by proceps** [comment]
Production. 3i DB.
https://sfg.taxonworks.org/tasks/nomenclature/browse?utf8=%E2%9C%93&taxon_name_id=&%5Btaxon_name_id%5D=448896

**Comment by jlpereira** [comment]
This is a backend problem, it seems to be more related with the ranks and not the roles. When you delete a role and it tries to update it. The response is: {"rank_class":["The rank of this taxon (genus) should be higher than the ranks of children"]}

This is the reason why the patch fails and the record is not updated

**Comment by mjy** [comment]
@jlpereira Is that validation message showing?

**Comment by jlpereira** [comment]
Yes, hard validation, after patch

**Comment by proceps** [comment]
The taxon does not have children. But it has wrong validation message. Probably the problem with model.

**Comment by mjy** [comment]
@jlpereira what are the params in the PATCH that throw the error?

**Comment by jlpereira** [comment]
![Captura](https://user-images.githubusercontent.com/16530364/72279135-3da9b780-3614-11ea-83f4-5dbc3894d557.PNG)

**Comment by proceps** [comment]
@jlpereira The error message should trigger only when the rank of the taxon changes. There is a validation: "if (rank_class != rank_class_was)". I do not know if this is related to another issue, where the rank is automatically changes (#1281)... But this validation should not even trigger if the rank does not change.

**Comment by mjy** [comment]
But it would trigger if existing data (other related records) are bad, and
triggered updates are cascading to those records and *they* are bad.  Not
sure if this is possible, but should be considered.
