### ISSUE TITLE
Task - Edit Nomenclature - change parent

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1281]
If I take a existing genus and change the parent taxon from tribe to order, the rank of the taxon automatically changes to family. The rank should stay the same if the only change is the parent.

**Comment by proceps** [comment]
Although it could be useful, e.g. when I change the parent of subgenus from genus to family, the rank automatically changes to the genus.

**Comment by mjy** [comment]
We need to make it work for the majority of records.  I propose to change always when no id (not saved), and never when when saved.
