### ISSUE TITLE
Georeferencing - Conflict between georeference and geographic area when both "correct"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1285]
When adding georeferences to a collecting event, AFTER the geographic area has been entered, then I get the following conflicts:
![image](https://user-images.githubusercontent.com/11411328/72908267-dfa75f00-3cfa-11ea-909d-fbc66d467ded.png)

However - both the geographic area and the georeferences are "correct". Potentially the uncertainty is conflicting with the geographic area? 

Example:
These geolocate coords:
![image](https://user-images.githubusercontent.com/11411328/72908609-5ba1a700-3cfb-11ea-9219-7e0d5cd5cb61.png)

38.610326	-89.37258	3287	38.6209060193,-89.3698139186,38.6206780193,-89.3698179186,38.6206780193,-89.3662999186,38.6213700193,-89.3662919186,38.6213670193,-89.3651009186,38.6213370193,-89.3641189186,38.6210450193,-89.3641009186,38.6206780193,-89.3639919186,38.6175820193,-89.3639979186,38.6175980193,-89.3639499186,38.6176200193,-89.3639219186,38.6176710193,-89.3638989186,38.6181000193,-89.3638939186,38.6174440193,-89.3634479186,38.6170750193,-89.3639959186,38.6170850193,-89.3625849186,38.6162210193,-89.3633379186,38.6161880193,-89.3619079186,38.6161970193,-89.3584569186,38.6161990193,-89.3580319186,38.6162140193,-89.3567089186,38.6162190193,-89.3562619186,38.6145530193,-89.3562619186,38.6142780193,-89.3562619186,38.6142820193,-89.3564399186,38.6142850193,-89.3575859186,38.6142760193,-89.3583939186,38.6133160193,-89.3583939186,38.6129320193,-89.3583939186,38.6121890193,-89.3583799186,38.6121890193,-89.3582749186,38.6118030193,-89.3580859186,38.6114190193,-89.3580549186,38.6112900193,-89.3580199186,38.6112230193,-89.3577149186,38.6101950193,-89.3577359186,38.6101890193,-89.3575479186,38.6101710193,-89.3569509186,38.6108930193,-89.3567809186,38.6109250193,-89.3564789186,38.6112210193,-89.3564789186,38.6111900193,-89.3567669186,38.6113640193,-89.3567049186,38.6114580193,-89.3566259186,38.6115370193,-89.3565259186,38.6116330193,-89.3563829186,38.6117240193,-89.3562009186,38.6117700193,-89.3560169186,38.6117950193,-89.3558179186,38.6117700193,-89.3555599186,38.6116660193,-89.3554309186,38.6115470193,-89.3552519186,38.6111010193,-89.3548749186,38.6108480193,-89.3546219186,38.6107240193,-89.3544179186,38.6106150193,-89.3542589186,38.6104950193,-89.3540159185,38.6104210193,-89.3537879185,38.6103320193,-89.3534099185,38.6100690193,-89.3533709185,38.6099960193,-89.3511979185,38.6098900193,-89.3474179185,38.6096300193,-89.3473689185,38.6093550193,-89.3473609185,38.6092330193,-89.3445849185,38.6092260193,-89.3442949185,38.6088040193,-89.3443059185,38.6078510193,-89.3442799185,38.6074490193,-89.3442759185,38.6075620193,-89.3471279185,38.6076110193,-89.3472259185,38.6079820193,-89.3483019185,38.6082210193,-89.3492509185,38.6084830193,-89.3500709185,38.6086250193,-89.3508819185,38.6085320193,-89.3508469185,38.6030390193,-89.3503029185,38.6031580193,-89.3560559186,38.6088190193,-89.3561029186,38.6089860193,-89.3559419186,38.6089830193,-89.3576299186,38.6089940193,-89.3579429186,38.6088510193,-89.3579479186,38.6085890193,-89.3579519186,38.6085770193,-89.3577959186,38.6080410193,-89.3577389186,38.6069680193,-89.3575259186,38.6059940193,-89.3574039186,38.6059860193,-89.3577539186,38.6060150193,-89.3598889186,38.6059960193,-89.3624699186,38.6059210193,-89.3636739186,38.6060210193,-89.3651019186,38.6060310193,-89.3662239186,38.6060080193,-89.3676439186,38.6060390193,-89.3689659186,38.6059970193,-89.3702699186,38.6060040193,-89.3715579186,38.6061020193,-89.3728149186,38.6062770193,-89.3728159186,38.6072460193,-89.3728199186,38.6072400193,-89.3732919186,38.6067220193,-89.3732809186,38.6067190193,-89.3738009186,38.6072340193,-89.3737989186,38.6072290193,-89.3742639186,38.6072300193,-89.3753329186,38.6069840193,-89.3753919186,38.6069940193,-89.3758539186,38.6072300193,-89.3757799186,38.6072290193,-89.3768069186,38.6066310193,-89.3767979186,38.6054560193,-89.3767779186,38.6054200193,-89.3780859186,38.6053900193,-89.3791899186,38.6057530193,-89.3792209186,38.6057570193,-89.3795499186,38.6057870193,-89.3802559186,38.6024510193,-89.3794379186,38.6024480193,-89.3796779186,38.6023930193,-89.3822649186,38.6030500193,-89.3822589186,38.6037190193,-89.3822569186,38.6046660193,-89.3822549186,38.6058030193,-89.3822449186,38.6062400193,-89.3822409186,38.6067060193,-89.3822409186,38.6071930193,-89.3822359186,38.6081420193,-89.3822079186,38.6086210193,-89.3822019186,38.6086890193,-89.3821989186,38.6086390193,-89.3837909186,38.6085580193,-89.3851029186,38.6085700193,-89.3869459186,38.6083770193,-89.3914669186,38.6084450193,-89.3914669186,38.6100310193,-89.3914599186,38.6120580193,-89.3914529186,38.6120380193,-89.3919319186,38.6126280193,-89.3919399186,38.6126190193,-89.3919039186,38.6125280193,-89.3914499186,38.6124680193,-89.3910939186,38.6122680193,-89.3897289186,38.6121660193,-89.3890309186,38.6119800193,-89.3877939186,38.6117950193,-89.3865399186,38.6115840193,-89.3851029186,38.6114240193,-89.3839949186,38.6117580193,-89.3839469186,38.6114290193,-89.3827689186,38.6115960193,-89.3827889186,38.6121910193,-89.3827559186,38.6122060193,-89.3822559186,38.6122760193,-89.3822529186,38.6125160193,-89.3822499186,38.6129980193,-89.3822519186,38.6129820193,-89.3837829186,38.6131010193,-89.3837859186,38.6142440193,-89.3837949186,38.6142860193,-89.3820859186,38.6160350193,-89.3820499186,38.6172110193,-89.3819909186,38.6172160193,-89.3795749186,38.6176950193,-89.3795529186,38.6176950193,-89.3783789186,38.6179210193,-89.3783849186,38.6180280193,-89.3783879186,38.6181950193,-89.3783919186,38.6182090193,-89.3780409186,38.6182310193,-89.3774979186,38.6180280193,-89.3774939186,38.6179270193,-89.3774919186,38.6176940193,-89.3774879186,38.6176770193,-89.3761209186,38.6176980193,-89.3753609186,38.6181190193,-89.3753729186,38.6187650193,-89.3753579186,38.6188220193,-89.3753349186,38.6190110193,-89.3753159186,38.6190160193,-89.3762959186,38.6206110193,-89.3762979186,38.6205920193,-89.3781089186,38.6204240193,-89.3817339186,38.6207530193,-89.3818209186,38.6242300193,-89.3818999186,38.6243640193,-89.3818799186,38.6244740193,-89.3818709186,38.6245960193,-89.3818669186,38.6313610193,-89.3819139186,38.6313730193,-89.3773849186,38.6365590193,-89.3773499186,38.6365310193,-89.3761959186,38.6369710193,-89.3761759186,38.6369550193,-89.3771519186,38.6376170193,-89.3771139186,38.6376200193,-89.3773479186,38.6391680193,-89.3773309186,38.6391650193,-89.3775699186,38.6391600193,-89.3786689186,38.6391590193,-89.3788989186,38.6391530193,-89.3801629186,38.6391500193,-89.3806899186,38.6391240193,-89.3819619186,38.6455460193,-89.3817999186,38.6454900193,-89.3745789186,38.6455750193,-89.3725339186,38.6446620193,-89.3725589186,38.6392090193,-89.3726929186,38.6392890193,-89.3680839186,38.6429460193,-89.3680229186,38.6429460193,-89.3608369186,38.6387280193,-89.3608659186,38.6387300193,-89.3606469186,38.6384380193,-89.3607299186,38.6383030193,-89.3607479186,38.6377350193,-89.3607609186,38.6369980193,-89.3607659186,38.6357300193,-89.3607719186,38.6347810193,-89.3607849186,38.6331230193,-89.3607989186,38.6328310193,-89.3633899186,38.6327040193,-89.3633999186,38.6322510193,-89.3634329186,38.6323750193,-89.3608099186,38.6322260193,-89.3608139186,38.6321790193,-89.3619609186,38.6305530193,-89.3620189186,38.6304270193,-89.3610229186,38.6301970193,-89.3611379186,38.6299020193,-89.3613309186,38.6297710193,-89.3614439186,38.6295270193,-89.3616879186,38.6291830193,-89.3621349186,38.6290130193,-89.3623629186,38.6282810193,-89.3632929186,38.6284380193,-89.3635039186,38.6286120193,-89.3637699186,38.6287690193,-89.3640329186,38.6288560193,-89.3641999186,38.6289480193,-89.3644259186,38.6290170193,-89.3646489186,38.6290750193,-89.3649149186,38.6291190193,-89.3652029186,38.6291410193,-89.3654509186,38.6291510193,-89.3657129186,38.6291440193,-89.3659579186,38.6291220193,-89.3661949186,38.6276110193,-89.3662669186,38.6275850193,-89.3657429186,38.6246190193,-89.3658869186,38.6246910193,-89.3665049186,38.6246910193,-89.3666359186,38.6229410193,-89.3666319186,38.6229630193,-89.3677229186,38.6229930193,-89.3679009186,38.6229770193,-89.3679159186,38.6229520193,-89.3679989186,38.6228910193,-89.3686549186,38.6228760193,-89.3697749186,38.6222260193,-89.3697879186,38.6209060193,-89.3698139186

And this geographic area:
![image](https://user-images.githubusercontent.com/11411328/72908739-8b50af00-3cfb-11ea-9249-ef63d786f0df.png)

Both are "correct" georeferences for "Carlyle" Illinois - both incorporate large amounts of uncertainty - but something is making them conflict. 

As a user - I don't want to have to "choose" between them. I want to add them both and have TW decide which to export.

**Comment by mjy** [comment]
These are conflicting and impossible assertions, and this constraint was carefully considered.  It's not likely to be dropped, sorry. Think of it as enforcing good digitization practices. 

Remember that a good georeference will ultimately let us infer the counties that it overrides.  You don't *have* to assert a geographic area. If a georeference is there we can find the intersecting counties on compute.

**Comment by tmcelrath** [comment]
Wait - what parts are conflicting? The bounding box given from Geolocate is well-within Clinton Co. Illinois boundaries. That is what I was assuming was the problem - but I guess not?

**Comment by tmcelrath** [comment]
I just tried it again with the Geolocate uncertainty set to be "outside" of the Geolocate calculated bounding box. That way, the uncertainties are nested: Clinton Co [uncertainty of point {Carlyle bounding box}]. This still wasn't allowed by TW.

**Comment by mjy** [comment]
Aha.  I think I know.  The current GeoLocate code creates both a shape as
error and a point/radius as the primary georeference.  I suspect the
point/radius size is outside the geographic area.

I'm not sure the best way to interpret GeoLocate vs. our primary/error
model, I did anticipate this being an issue.

**Comment by tmcelrath** [comment]
@mjy I can add the same Geolocate coords with an error of 10000m just fine. But if I add the same thing "e.g. Geolocate coords with error of 10000, plus the Geolocate bounding box (that only extends 3991m from the center point)" - then it won't let me add it. They should be nested within each other and compatible.

**Comment by mjy** [comment]
I have to check, but I think that error radius is calculated from the
shape, not taken from the setting in Geolocate... though that's likely not
the problem (but maybe it's a miscalculation.).

M

**Comment by tmcelrath** [comment]
@mjy Okay I think the issue might be with parsing Geolocate - I just did it _BEFORE_ I added a geographic area and it sent me to the wrong hemisphere. That might be the issue. Checks are okay but Geolocate parsing is wrong.

**Comment by mjy** [comment]
If you can paste the Geolocate values here for the example that is
hemisphere inverted that would be great.

**Comment by tmcelrath** [comment]
Creating a separate issue that describes it better.

**Comment by tmcelrath** [comment]
#1287

**Comment by debpaul** [comment]
@mjy @tmcelrath since this is "better described" in #1287 which is now closed, shall we close this ticket too? Is there a reason to leave it open?
