### ISSUE TITLE
Comprehensive digitization - Geographic area reference removed when georeference deleted

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1286]
**Describe the bug**
When I delete a georeference in the "Georeference" pane of "Comprehensive digitization" - any previously selected Geographic Area is also deleted - and so the map scopes to the west coast of Africa instead of previously scoped Geographic Area. 

**To Reproduce**
1. When I am in the Comprehensive digitization form and I add a Geographic Area (and save).
2. Then I successfully add a georeference.
3. And I subsequently delete that georeference.
4. Then the geographic area is no longer "saved" in the georeference panel. 

Geographic area (Clinton Co. (Illinois)) with a Georeference recently added:
![image](https://user-images.githubusercontent.com/11411328/72909300-690b6100-3cfc-11ea-9fd0-3ec1466e6a53.png)

After deletion of just Georeference:
![image](https://user-images.githubusercontent.com/11411328/72909397-90fac480-3cfc-11ea-85bd-24ff6a49baa3.png)

Digitize pane, showing Clinton Co. still selected after georeference deletion:
![image](https://user-images.githubusercontent.com/11411328/72909450-a7a11b80-3cfc-11ea-814b-da81b0a72a1e.png)

Scope of georeference pane when re-clicked after deletion:
![image](https://user-images.githubusercontent.com/11411328/72909487-b8ea2800-3cfc-11ea-80c0-ced50260bb84.png)

I have to either click on a different geographic area, then back to the original, or save the page and reload to get the geographic area to re-scope. 

**Expected behavior**
Geographic area should be constant regardless of georeferences. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production

**Comment by jlpereira** [comment]
Fixed
