### ISSUE TITLE
Enhancement - Add centroid georeference indicator

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1289]
When I am here:
![image](https://user-images.githubusercontent.com/11411328/73108729-ade2f380-3ec6-11ea-9ecb-298fa4d2f420.png)

I want to see an indicator that if I don't georeference any further - that a centroid calculation of the selected geographic area will be applied, like so:
<img width="396" alt="georeference_text" src="https://user-images.githubusercontent.com/11411328/73108877-31044980-3ec7-11ea-8e48-ee2b742054bd.png">

**Comment by mjy** [comment]
Experimented with this, it doesn't feel right here.  We're going to add a badge to reflect lat/long presence, and think of a way to display soft validations easily.

**Comment by mjy** [comment]
Closing for now.  Hexagon metadata was added as proxy.
