### ISSUE TITLE
Enhancement - Error should appear when "Geolocation uncertainty" is filled in but Lat/Long. is not

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1290]
When I am saving a record in Collecting Events or in Comprehensive Digitization - and the Geolocation uncertainty field has something entered but there is no lat./long entered - I cannot save the record but there is no error message letting me know why. 

I should see an error message saying "You cannot have lat/long uncertainty without a lat/long".

**Comment by mjy** [comment]
See also #1293
