### ISSUE TITLE
Task - OTU radial - Biological associations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1291]
The quick option for the related taxon picks the taxa from the wrong side of the relationship. In the example below, I enter host plants as related taxa, but instead in quick option, I see the list of recently selected focal taxa (insects) instead of recently selected plants.

![image](https://user-images.githubusercontent.com/5597748/73123743-dc111380-3f58-11ea-8680-f61c43dbd175.png)

**Comment by mjy** [comment]
We can't predict what side you're coming from, I will tweak to include a couple from both sides.

**Comment by proceps** [comment]
If I always start with object, I always add a subject, and I expect to see recently entered subjects as a recent entry, but instead, I always see the subject, which is not relevant. If I always start with subject to add an object, than I would expect to see objects as recent entries. Whatever I used to search for the last time. If this is not possible, I would prefer to see a search box as a default option. Because this is the only way I can enter information now anyway.
