### ISSUE TITLE
Grid Digitizer - Adding multiple images only adds some of them/Need to be able to add multiple images

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1301]
**Describe the bug**
When I add multiple images to the Grid DIgitizer - only some sled images are created, not all. 

**To Reproduce**
1. When I  go to Grid Digitizer
2. Then I drag multiple images or a folder of multiple images
3. And I try to go between them in the visualization screen or look at them in "Data:Images"
4. Only some of the images have been created. 

Adding these images:
![image](https://user-images.githubusercontent.com/11411328/73957077-74998300-48cb-11ea-8656-18201550a84a.png)

This happens:
![image](https://user-images.githubusercontent.com/11411328/73957190-a3175e00-48cb-11ea-99da-ff6cf9086dad.png)

Only two images created (visualized in Grid Digitizer):
![image](https://user-images.githubusercontent.com/11411328/73957319-ccd08500-48cb-11ea-8fa3-8553a82c52e6.png)
![image](https://user-images.githubusercontent.com/11411328/73957345-d5c15680-48cb-11ea-8df7-1b124a2d7f7c.png)

Only two images created (visualized in images):
![image](https://user-images.githubusercontent.com/11411328/73957219-ac082f80-48cb-11ea-8bf1-cf93c6c8dfdd.png)

**Expected behavior**
Should be able to add as many images to be added to the queue as I want and all get added - e.g. if I want to go through and parse those slides. One at a time seems restrictive. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox - INHS Insect Collection
- Chrome

**Comment by mjy** [comment]
@jlpereira To solve we're going to update Task -> New Image rather than change behaviour here.  Basically we'll add a facet there that says "Is grid digitize"

**Comment by jlpereira** [comment]
Fixed. Now dropzone will finish first the files queue before to load the first image
