### ISSUE TITLE
Grid digitizer - button text overflow

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1302]
**Describe the bug**
Button text overflow on smaller screens in Grid digitizer

**Expected behavior**
Should stay within button/buttons should resize with text. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11411328/73964843-9b11eb00-48d8-11ea-8005-a0f1c229f999.png)

**Environment (please identify where you experience this bug:**
- Sandbox - INHS Insect
- Chrome

**Comment by jlpereira** [comment]
Fixed

**Comment by jlpereira** [comment]
Sorry, not fixed yet.
