### ISSUE TITLE
Collection object radial

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1309]
As a curator I want quick access to several forms for collection objects in the context of that object.  This is the identical concept to the Otu radial.

* [x] New circle icon, perhaps solid dot at center with radial lines going outwards

Forms to start:
* [x] Biological relationships form (identical to OTU form, but starts with colleciotn object)
* [x] Taxon Determination form (identical to digitize form)
* [x] Biological Attributes form (buttons toggle, like digitize form)
* [x] Default properties

**Comment by jlpereira** [comment]
Its done. Closing
