### ISSUE TITLE
Non superuser can not see user list in Browse annotations or See Results

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1312]
**Describe the bug**
When I search in "Browse Annotations" as a non-superuser, then I can't see results, and I can't narrow by user. 

**To Reproduce**
1. When I  am in "Browse Annotations" as a non super user (e.g. Lily Hart)
2. Then I select any valid combo of "On" "For" and "Annotation Type" such as "Tags on Sources for "Sources to be checked"
3. And I hit submit. 
4. See 5 results are hit but none are listed. 

Super-user view:
![image](https://user-images.githubusercontent.com/11411328/74356707-698b9a80-4d84-11ea-8b66-9183aa0d1e4a.png)

Non-super user view:
![image](https://user-images.githubusercontent.com/11411328/74356591-3943fc00-4d84-11ea-8a34-ea52b58b3bf7.png)

**Expected behavior**
Non-super users should be able to see/filter by users and see annotation results

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Can't replicate on latest Firefox using your project in current development.  We'll need a console log or network debug list I suspect.

**Comment by tmcelrath** [comment]
Will try to get one tomorrow.

**Comment by tmcelrath** [comment]
Console debugger after hitting "Submit" button:
![Screenshot (42)](https://user-images.githubusercontent.com/11411328/74456975-3c56ef00-4e4d-11ea-8fb9-903d69109993.png)

**Comment by tmcelrath** [comment]
Console debugger before even loading any data or hitting submit:
![Screenshot (41)](https://user-images.githubusercontent.com/11411328/74457051-5e507180-4e4d-11ea-8156-a1869383f630.png)

**Comment by tmcelrath** [comment]
Also - replicated in Production on Firefox and Chrome with a non-superuser account. Not browser-related.

**Comment by mjy** [comment]
Fixed.
