### ISSUE TITLE
Updating an ICZN name at rank genus to rank Tribe is prevented

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1321]
When I have a name, and it has rank genus, and its current parent is a subfamily, and it has a proper tribe ending, when I use the Edit nomenclature task, then I can not set the rank to tribe.

Example from Opiliones data.

**Comment by adrik29** [comment]
Actually, the system didn't let me enter the "tribe" category -- it changed forcibly to "genus", I don't know how and why.

**Comment by mjy** [comment]
For new names the rank is predictive based on the parent.  We predict that most people will add genera to families, therefor the value is defaulted to genus, you can simply pick "tribe" to over-ride the value.

**Comment by adrik29** [comment]
I did, but the system kind of "locked" onto "genus" and nothing I would do would bulge this back to "tribe".

**Comment by mjy** [comment]
@jlpereira let's look into this.

**Comment by adrik29** [comment]
I understand that if the system makes some smart guesses it saves time, but they cannot be so inflexible, not allowing us to change it back to proper rank.

**Comment by mjy** [comment]
It's definitely supposed to let you over-ride on create.  *After* create is
the known bug.  Experimenting now.

**Comment by adrik29** [comment]
As an example I had added the tribe Buemarinoini, which as created the other day, and the system stubbornly changes it to genus and ignored my attempts to revert it to tribe.

https://sfg.taxonworks.org/tasks/nomenclature/browse?utf8=%E2%9C%93&taxon_name_id=&%5Btaxon_name_id%5D=636610

**Comment by adrik29** [comment]
![tribe bug](https://user-images.githubusercontent.com/46284943/75051852-66438d80-54ad-11ea-9ab6-9277af9d41df.JPG)
