### ISSUE TITLE
Quick grid specification does not match result

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#1322]
**Quick grid row setting is off by one**

Setting a 10x2 quick grid results in 9x2 grid.

**To Reproduce**
1. When I  click #
2. Then I change the row and column inputs to 10 and 2
3. And I select 10x2
4. See a 9x2 grid

- Sandbox - <sandcastle>
- Build 0628585
- Browser Safari

**Comment by mjy** [comment]
Thanks @jrflood

**Comment by mjy** [comment]
Can't replicate, can you try again?

**Comment by mjy** [comment]
Safari not technically supported :(.  Not sure if that's the issue.

**Comment by mjy** [comment]
Appears it is an issue with Safari, sorry :(.
