### ISSUE TITLE
Task - New asserted distribution - OTU/area combination already exists

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1329]
As a user, when OTU/area combination already exists, I would like to have a new citation automatically added to the OTU/area record instead of an error message. 

The same would also be useful when asserted distribution is added using the OTU radial

**Comment by mjy** [comment]
To implement:
* [ ] Add virtual param to asserted distribution - `cite_existing: true`. 
* [ ] Find way to allow user to set this to true/false
* [ ] Pass that value in the form when true/false
* [ ] Update model to check this `before_validation`

**Comment by proceps** [comment]
This is already implemented in OTU radial, but not in the New asserted distribution task
