### ISSUE TITLE
error message appears after attempts to save transcriptions

### ISSUE THREAD

**Issue by kjv5069** [SpeciesFileGroup/taxonworks#133]
The following error message appears every time I try to save changes to a transcription on TaxonWorks:
![screen shot 2017-05-16 at 1 55 24 pm](https://cloud.githubusercontent.com/assets/28738219/26120756/d3d13626-3a3f-11e7-88d3-f288bfa0c104.png)

**Comment by mjy** [comment]
Thanks for the report.  Will check into it ASAP.

**Comment by mjy** [comment]
Might be related to a problem with the determination/OTU value

**Comment by mjy** [comment]
Comment here if you still have problems.  Thanks much for filing an issue.
