### ISSUE TITLE
Task - New taxon name: add link to add new taxon as type?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1330]
For example, when I add a new genus name, currently the section "Type" only allows to search for already existing taxa as possible type species.

Would it be possible to add there a direct link to the task "New taxon name", with the corresponding parent already selected?

**Comment by mjy** [comment]
This exact issue came up this morning, uncanny.  Yes, I will design an
inline form to stub the type, then you can navigate to it.  @José Luis
Pereira <jlpereira@speedy.com.ar> I'll work up the idea shortly.

**Comment by typophyllum** [comment]
Thanks!

**Comment by proceps** [comment]
I did not have any problem editing two separate windows. Expanding form you will run to the same issue in different places. Original genus. You want to enter original genus, but it is not in the database. You want to enter the name of a senior synonym, but it is not in the system. Etc. Many records are cross connected, and it is hard to provide links to all possible connections.

**Comment by mjy** [comment]
The idea is to stub the name, not fill it out.  Just like we add new OTUs
in place we can create a new monomial in place, that way for a new genus
the record is fully complete before the species in it are done.  It's
simply letting the monomial be created and linked to the Genus in line.
It's a clean, easy addition I think to the UI.  On failed search, option
pops up to add name, click button, adds, but doesn't leave anything, and
user can continue on.

**Comment by proceps** [comment]
I am just saying that I do not like the idea. This is an unnecessary overkill. I enter a new species and the genus not in the database. I have to know that I need to enter the genus name first. What is the difference between this and entering a new type species? For the species, you cannot just stub monomial, it also requires rank and parent. It would be much cleaner to add two buttons (add syster taxon and add daughter taxon, open those stabs in a new window to allow user to enter all information associated with the taxon. It would be even more confusing when the type species is not a newly described taxon, but it is one of previously described taxa.

**Comment by proceps** [comment]
From my experience working with stub new button, I personally found it quite helpful, but dangerous at the same time. The place I use it most often is the People as authors for a new publication. If you misspelled a name you have return "Nothing is found message" and it is very tempting just to use Add new button. If you later discover that you created a duplicate name, it is relatively easy to use the task to unify people. At the moment we do not have unify taxon button or unify OTU button. And from my experience, once created, it is extremely difficult to remove either from the system. I would will be strongly oppose to creation of any taxon name on the fly.

**Comment by typophyllum** [comment]
At any rate, in the case of new genera it is about equally likely that the type species already exists or that it is also new. So it seems inconsequent to provide only for the first case (in a paper I'm currently entering in OSF the type species of three out of four new genera are new). A direct link would also save each time four or five steps (copy or memorize parent name - go to task hub - search new-name task again - enter new-name task - paste or type parent name into corresponding field). And the work flow wouldn't get interrupted.

**Comment by proceps** [comment]
I am doing this for 2 years now and my steps are:
1. Enter the genus (with all information)
2. right click on the hyperlink with the taxon name to enter it in a new tab.
3. go to edit mode
4. Atl+D to generate a species taxon.
5. go back to the genus tab and enter the type species.

If you directly enter the species name in the genus page, you still have to repeat the same steps only to update the species information.

**Comment by mjy** [comment]
Two people independently hit this exact issue at the same time.  It eliminates 3 steps from your workflow.  Seems legit and relatively easy to develop.

# New workflow

1. Enter the genus, with all information, including clicking a single button (see below) to stub the species name, select it, and ask user to pick what type.
2. No need to open a new tab, click on the hyperlink of the type species, and fill it out, no need to return to type genus because link to type species already exists.  

<img width="1592" alt="Screen Shot 2020-02-28 at 9 07 17 AM" src="https://user-images.githubusercontent.com/22600/75559970-02b7e380-5a0a-11ea-8b6e-7bb1c07007a3.png">
