### ISSUE TITLE
Points not displayed in tasks/gis/otu_distribution_data/ due to incorrect route to icons

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#134]
The colored point icons are not rendered due to their location being requested from /map_icons/mm_20<color>.png whereas they are actually relocated to images/map_icons/mm_20_<color>.png

**Comment by mjy** [comment]
@jlpereira Is this because of the "new" asset packaging?

**Comment by jlpereira** [comment]
Mmmm no. Probably is related with the asset_path. Where I can reproduce this?

**Comment by jrflood** [comment]
Actually, I may have jumped the gun on this ... I saw it in my branch which might be slightly out of date from development.  trying to get development branch going but webpack still compiling?

**Comment by jlpereira** [comment]
shouldn't be a problem webpack, because actually we have both things working separately. 

Webpack: app/javascript
Pipeline with sprockets: app/assets

Mmmmm the problem could be in other thing?

Try:
$('body').append(' <p><%= asset_path("map_icons/mm_20_black.png") %></p>')

this will get you the url of the image, and use it on the browser to look if is missing. It suppose it works.

**Comment by jrflood** [comment]
After a lengthy transition, this error does not occur on development.  My bad.

**Comment by jrflood** [comment]
I tested the wrong page :(   it does not display properly for tasks/gis/otu_distribution_data/28148 in the insect collection project

**Comment by jrflood** [comment]
I am trying to construct a sandbox example

**Comment by jrflood** [comment]
The error that occurs is:
Started GET "/map_icons/mm_20_blue.png" for 127.0.0.1 at 2017-05-22 14:20:50 -0500

ActionController::RoutingError (No route matches [GET] "/map_icons/mm_20_blue.png"):
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (3.3.0) lib/web_console/middleware.rb:131:in `call_app'

**Comment by jlpereira** [comment]
What is the js file where you're getting that error?

**Comment by jrflood** [comment]
I will probably have to use the debugger to find that out.

**Comment by jlpereira** [comment]
I found the problem on maps.js.erb

icon = '<%= asset_path("map_icons/mm_20_' + color_name + '.png")%>'

It looks like assets_path does not support variables inside

**Comment by mjy** [comment]
?  That's just a string, it should work fine.



On Mon, May 22, 2017 at 5:11 PM, José Luis Pereira <notifications@github.com

**Comment by jrflood** [comment]
It is occurring in maps.js.  the reference to the icons looks like
'/assets/map_icons/mm_20_gray-9e82d1a62a555ee7209dfa40f75ef644938e1ca283b29a5fee2529cf3d8da8ea.png'

which looks like some key has been appended to the actual file name.  this is not handled in the subsequent code when the color is not gray, since the value is not known to the js.
if no substitute color is provided, the default gray icons display correctly.  So, maybe each known color's file has to be explicitly referenced before its encrypted name can be used...not convenient, but doable.

**Comment by jlpereira** [comment]
Try this:
 
var color_name = "blue";
console.log('<%= asset_path("map_icons/mm_20_' + color_name + '.png") %>');
console.log('<%= asset_path("map_icons/mm_20_blue.png") %>');

You should see something like: 

/map_icons/mm_20_blue.png 
/assets/map_icons/mm_20_blue-68b91736a7c88b22cf06847aaab1802285c83df55665203a911e8a9bbf87ba20.png

We can't use vars there. Thinking on this right now, we can create an array with the color name as key and inside of each color the route we get using asset_path, then we could use it on other place if is need with pinColor['blue'] for example.

**Comment by jrflood** [comment]
Sorry I didn't read this until now, but it turns out I just pushed virtually what you just said (18 hour ago - LOL) 

But, yes, the reason I did that was that the calculated path was left untreated in the executable code seen in the debugger - whereas the explicit forms were all converted.
