### ISSUE TITLE
Tags displays show object tagged (not so useful) instead of (useful) definition of its keyword

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#135]
e.g., 
Tags

Rich's keyword : CollectingEvent : #36, USA, California 20 mi E Temecula, 3500 ft. N 33o28'41" W 116o50'56" slopes, mostly on grasses 6 V 2003 D. Dmitriev

Jim's keyword : CollectingEvent : #36, USA, California 20 mi E Temecula, 3500 ft. N 33o28'41" W 116o50'56" slopes, mostly on grasses 6 V 2003 D. Dmitriev

ZeroTotal : CollectingEvent : #36, USA, California 20 mi E Temecula, 3500 ft. N 33o28'41" W 116o50'56" slopes, mostly on grasses 6 V 2003 D. Dmitriev

INHS_letters : CollectingEvent : #36, USA, California 20 mi E Temecula, 3500 ft. N 33o28'41" W 116o50'56" slopes, mostly on grasses 6 V 2003 D. Dmitriev

psuc_geo_1 : CollectingEvent : #36, USA, California 20 mi E Temecula, 3500 ft. N 33o28'41" W 116o50'56" slopes, mostly on grasses 6 V 2003 D. Dmitriev

**Comment by mjy** [comment]
You mean on /tags?

Are you confusing tags and Keywords?  Tags are the link b/w object and
keyword.  Keyword is the keyword itself.

On Tue, May 23, 2017 at 12:43 PM, J. Richard Flood <notifications@github.com

**Comment by jrflood** [comment]
No, I copied the listing of the tags for this collecting event which appear on the collecting event page.  The list of tags for this collecting event are manifestly obviously for the collecting event, so why are we repeating this instead of the tag's keyword definition so that what the tag means is more obvious?

**Comment by mjy** [comment]
Got it, context is everything.  Maybe step those  the dev into the issue ('when I click on /collecting_objects/36, then I ...').  We'll find a fair number of these types of issues.

**Comment by mjy** [comment]
Closing.  Context (the thing being tagged) is not shown when on context.  Mouse over Keyword gives definition.  The "*" you see above the _Annotations_ header is a proxy for a modal fly out interface that will allow you to manage (edit/etc) all annotations (i.e. I removed the _edit_ for simplicity at this point).
