### ISSUE TITLE
Tasks - Comprehensive - Biological association search behaviour fails to unlock Add

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1352]
When I use the search to select a biological relationship then it has a different behaviour than clicking one from the quick form:

* [ ] the label appears differently
* [ ] the Add button is not always unlocked(?)

**Comment by jlpereira** [comment]
I can't replicate it, selecting a biological relationship from the list or using autocomplete are displaying the same label.

Add buttons always unlock after pick both

**Comment by jlpereira** [comment]
Closing, reopen if is needed
