### ISSUE TITLE
Taxon determinations on Collection Objects displaying in wrong "order"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1355]
**Describe the bug**
If I add two determinations with two different years, the most recent determination should be the one displayed as "current"

**To Reproduce**
1. When I add two determinations. 
2. Then I add the older one second.
4. Then the older one is displayed, not the most "current" one. 

Example
![image](https://user-images.githubusercontent.com/11411328/76122135-f956ea00-5fba-11ea-801c-351fee1b1768.png)

**Expected behavior**
Determinations should "rank" based on age. 

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
You must drag the preferred determination to the top of the list.  It is not based on age.

**Comment by tmcelrath** [comment]
Am I missing something? I can't drag them.

**Comment by mjy** [comment]
Might have been added then removed in Comprehensive in the list.

**Comment by tmcelrath** [comment]
Should I edit issue to "Can't change determination order"?

**Comment by mjy** [comment]
Sounds good.

**Comment by mjy** [comment]
@jlpereira You did something with positoin, is this resolved?

**Comment by jlpereira** [comment]
@mjy if I remember well there was some issue at the backend

**Comment by tmcelrath** [comment]
This is not resolved. Still an issue.

**Comment by tmcelrath** [comment]
Please fix ASAP

**Comment by jlpereira** [comment]
@tmcelrath this is still an issue? since Browse collection object was refactor, maybe it's already fixed. Could you let us know?

**Comment by tmcelrath** [comment]
Still an issue. Still not using the most recent one as the "current" identification.

**Comment by tmcelrath** [comment]
That same CO is still a good example. Only using the older identification for display and for export to DWC.

**Comment by mjy** [comment]
> Only using the older identification for display and for export to DWC.

I rememver, this multiple issues.

* [ ] Allow curator to update position of Determinations (top is current)
* [ ] Ensure top curation is exported to DWC
* [ ] Restore date column to comprehensive (order is correct there AFAICT)

**Comment by mjy** [comment]
We think we have it now.
