### ISSUE TITLE
Collection Object Filter - searching by user is broken for "updated"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1363]
**Describe the bug**
If I search by user and "updated" I get lots of records that user has never touched. 

**To Reproduce**
1. When I  go to collection object filter
2. Then I select any user.
3. And I search with "updated by". 
4. I see lots of records that user did not update. 

**Expected behavior**
I should only see records that user has updated. 

Search parameters:
![image](https://user-images.githubusercontent.com/11411328/76545214-61904a80-6457-11ea-97b2-1879e24e4d2a.png)

One of results (note user: Noah Clohisy is not an updater):
![image](https://user-images.githubusercontent.com/11411328/76545244-6fde6680-6457-11ea-8870-7f45d222254b.png)

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by jlpereira** [comment]
@mjy could be possible this happen because its making a reindex?

Its pointing to: /collection_objects/dwc_index
