### ISSUE TITLE
Model - Identifier - potential issue with containerization/missplacement

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1368]
We discovered a single record with a bad identifier_object_id.  That the bad value was allowed/persisted is the concern. 

* Recheck validation
* Recheck containerization and movement of identifiers

**Comment by LocoDelAssembly** [comment]
@mjy can you share the single-sample here? Why is it a bad value?

**Comment by mjy** [comment]
It was a large int to a id of that type that (likely) never existed.  I destoyed, the record, sorry (might be trace of it in error logs).  Sorry this is vague.  It's likely related to #1367 we think, which can be used to experiment to see if it can be repeated.

**Comment by tmcelrath** [comment]
INHS Insect Collection 862422 and INHS Insect Collection 862424 are two such examples (Production)

**Comment by tmcelrath** [comment]
Steps to replicate:
Create a collection object. Add values to various fields. Lock all fields and click "increment". Click "Add to container". Save. Click "Save and Next". Attempt to add identifier next in sequence. Get error (unable to save, bad identifier has been created somewhere).

**Comment by tmcelrath** [comment]
SIMPLER steps to replicate:
Steps to replicate:
Create a collection object. Add values to various fields. Lock all fields ~and click "increment"~. Click "Add to container". Save. Click "Save and Next". Attempt to add identifier next in sequence. Get error (unable to save, bad identifier has been created somewhere).

**Comment by tmcelrath** [comment]
Just to be clear - it is apparently NOT an issue with the "increment" button. I can create phantom identifiers even without it. Is it that the system thinks it needs to add both the current AND a subsequent identifier to the containerized specimen?

**Comment by tmcelrath** [comment]
INHS Insect Collection 862422, 862424, 862436, 862439  as well.

**Comment by tmcelrath** [comment]
Check INHS Insect Collection 861446- 861450 as well.
