### ISSUE TITLE
Georeferenced Locations Not Appearing in Collection Event Setup

### ISSUE THREAD

**Issue by jnodel** [SpeciesFileGroup/taxonworks#1372]
Done in Chrome:

When Georeferencing, once a location has been identified and "saved to application," it appears to be saved in TaxonWorks and reappears when returning to the GeoLocate tool later on. Yet, when creating a collection event and trying to select a Geographic Area, the location identified and "saved" does not appear and seems to not exist in the bank of options for the Geographic Areas.

**Comment by jlpereira** [comment]
Hi @jnodel

Welcome to the community and thank you for report this issue.
To help us to identify and replicate it. Could you provide us more information about this?

Which is the task where you reach this? (Task name or URL)
Could you provide us the following steps to replicate the issue? and exactly what are you doing. 

To give you a example of how to write this:

> 1- Go to New taxon name task.
> 2- On basic information section, fill name field with "Joe" text
> 3- Fill parent name with "Doe" text, and select Doe on the list
> 4- Select "Genus" rank
> 5- Press save

This will help us to find the problem more quickly.
Thanks!

**Comment by jnodel** [comment]
Hi @jlpereira 

It is in the "New geo locate georeference"

1. I enter the locality string, county, and state, for a location in USA. The map zooms to the suggested locations for that entry, and I select the location and click "Pin".
2. I then click "Save to Your Application." This does not seem to cause an issue, and is saved into the geolocator. 
<img width="798" alt="Screen Shot 2020-03-27 at 8 37 42 AM" src="https://user-images.githubusercontent.com/62450797/77756859-6f70ce80-7006-11ea-9fcb-047f045d2923.png">

3. I then tell it to create a Geo Locate, and get an error message.
<img width="332" alt="Screen Shot 2020-03-27 at 8 38 22 AM" src="https://user-images.githubusercontent.com/62450797/77756871-74358280-7006-11ea-918d-fa77276ac42e.png">
<img width="597" alt="Screen Shot 2020-03-27 at 8 38 32 AM" src="https://user-images.githubusercontent.com/62450797/77756876-77307300-7006-11ea-99ef-b4279c700bb9.png">

Yet sometimes, it still saves the location and I can find the location when I create a new collecting event. But this is not a permanent occurrence:
<img width="369" alt="Screen Shot 2020-03-27 at 8 40 10 AM" src="https://user-images.githubusercontent.com/62450797/77756956-a34bf400-7006-11ea-8e44-c647db4c7f63.png">

**Comment by jlpereira** [comment]
@jnodel I think the problem here is you didn't select a collecting event before to press the create button.

**Comment by mjy** [comment]
Probably assumes it should be set- not sure why it isn't by default.  Will check that.

**Comment by jnodel** [comment]
@jlpereira Thank you for looking into this. I tried selecting a collecting event, and when I do that and click "Create Geo Locate" it either "saves" or I get an error message as above. If it "saves," it actually doesn't save the location, as the location is still not listed when I try to add a location to a collecting event.

<img width="224" alt="Screen Shot 2020-03-30 at 5 12 30 PM" src="https://user-images.githubusercontent.com/62450797/77962553-cb0eb680-72a9-11ea-8af1-4c3cbc48a26d.png">
<img width="581" alt="Screen Shot 2020-03-30 at 5 12 40 PM" src="https://user-images.githubusercontent.com/62450797/77962571-d1049780-72a9-11ea-8dbd-b6ea8336b92f.png">

What do you think?

@mjy Thank you for looking into this. What is set?
