### ISSUE TITLE
Some Geographic Areas not Indexing correctly (improperly assigned country/stateProvince)

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1373]
**Describe the bug**

When I select certain geographic areas, the indexing is incorrect, and assigns a country as the state province and doesn't assign a country. 

**To Reproduce**
1. When I  assign this Geographic Area: https://sfg.taxonworks.org/geographic_areas/33446
2. Then I view that specimen in "Browse Collection Object"
3. See error that United States is stateProvince, not country, and Illinois is not stateProvince, and country is blank. 

![image](https://user-images.githubusercontent.com/11411328/77329477-062e4a00-6cec-11ea-9ccf-f2bb7fe451a1.png)

**Expected behavior**
Should "index" correctly. Also applies to at least the "Texas" entry in this dataset.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Confirmed. 

The issue is that gazeteer records for `ne_states` have unknown geographic_area_types.  

Solution for that gazetteer is to update the 3k+ records with a type.  Minimally updating the type of the country will fix the country issue.
