### ISSUE TITLE
Task - Matrix edit - Copy the list of characters from existing matrix.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1376]
A new interface is needed to quickly populate matrix with a list of existing characters.
The expected functionality.
1. I create a new matrix
2. I want to copy all or some descriptors from existing matrix. I open a pop up, select one of the existing matrices from the list. 
3. Show the list of the descriptors of that matrix with check boxes. Select the characters which I want to add to the new matrix (or select all button).
4. Click the button Add to add descriptors to the new matrix.

**Comment by mjy** [comment]
Good description.  

@jlpereira Use a modal as proposed.

* [ ] Smart selector for observation matrices (may need endpoint) at top
* [ ] After I select, populate table with descriptor list
* [ ] Table has: checkbox, descriptor name, descriptor type
* [ ] Button above table toggles select all/none
* [ ] Add button POSTS (1 at a time) new descriptors to the matrix

**Comment by proceps** [comment]
One more comment, this should also preserve the predefined order of the descriptors.

**Comment by jlpereira** [comment]
Pushed @proceps, let me know if this okay or you want some changes

**Comment by proceps** [comment]
That look really great. Probably the button should be called "Copy descriptors from Matrix"

The position of the button. Probably the best place for it is the Smart selector. The place where you can search for existing OTU or a descriptor. Just add another tub there "From another Matrix", if clicked, this pop-up could show up. Alternatively it could go to the top row of the hyperlinks, the place where you can create a new descriptor.

Could you create the same functionality to copy the rows to the matrix, probably this is another open issue. So for consistency, both could go to the smart selector, and be visible depending what you selected rows or columns.

**Comment by jlpereira** [comment]
Added component for copy rows from matrix and moved both to smart selectors.
Didn't test it too much, so let me know if is not working right.

**Comment by proceps** [comment]
Works really great. Few small issues:
1. When I select From another Matrix. Close the pop-up window, and click From another matrix again, the pop up does not come up. I have to switch the smart selector to something else and come back to reopen the pop-up.
2. Once the descriptors or OTUs are selected and the button clicked to add them, the pop-up should close automatically.

**Comment by jlpereira** [comment]
Meh, missed that. Fixed
