### ISSUE TITLE
Task - Observation Matrix dashboard - additional filtering options

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1377]
As a user, I would like to be able to download a partial matrix: 

1. I would like to select a particular matrix from the list
2. I would like to select an OTU scope (upper taxon), e.g. all species (OTUs, collection objects) of one genus/tribe
3. options to select All rows, only rows with scores, rows linked to valid TaxonName, rows links to OTUs, rows linked to collection objects.
4. optiontion to sort OTUs according to nomenclature
5. after all scopes are defined, I would like to click the button to generate Nexus or TNT file.

**Comment by mjy** [comment]
We will not create partial derivative exports, i.e. another mechanism to render a very specific format, that would be code duplicatoin. All exports will come from a defined matrix. 

Therefor we need more effective ways to create new matrices from existing, filters etc. Most of your suggestions are simply steps that preceed creating a new matrix.

I suggest that you break down 2,3,4 into individual new issues.

**Comment by proceps** [comment]
That is fine, this is still a mechanism to quickly populate a list of OTUs. Selecting a parent taxon is not satisfactory, since it brings a lot of synonyms, combinations, and other names which have OTUs. And names are not ordered. This is still should be a single interface to quickly filter and populate the list of OTU and not to add OTUs to the matrix one by one. Although I still see a preference of just a filter on the top of an existing matrix. I will be able to use the same filter for the interactive key for example.
For now, can we think of an interface like "Observation matrices dashboard" or extend this interface with few additional search criteria and add functionality to add all OTUs to one matrix?

**Comment by proceps** [comment]
OK, I will try to modify what is needed in this interface:
1. Add a filter for OTUs which have /have not scores
2. Add a filter for OUTs included in a particular matrix
3. Add an option to link selected OTUs to a particular matrix (check boxes, select /deselect all, add to to matrix button)

**Comment by proceps** [comment]
it is already implemented
