### ISSUE TITLE
Task - Observation matrices dashboard - Select matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1379]
Is it possible to pin the matrix (the matrix I am working in the time). And if matrix is selected as a default, clicking the button Add to the matrix, instead of opening the window with the list of matrices directly adds OTU to the matrix. Or alternatively, opens the window, and already have one matrix selected.
To implement, a Pin should be added to the matrix hub and

**Comment by proceps** [comment]
See also #1096, not the same, but also related to simplification of the selection.

**Comment by jlpereira** [comment]
<img width="1680" alt="Captura de Pantalla 2020-05-15 a la(s) 14 02 53" src="https://user-images.githubusercontent.com/16530364/82076936-f102e580-96b4-11ea-8af2-00042ed36a04.png">

The pin icon for use the default matrix it's already there

**Comment by proceps** [comment]
@jlpereira 
I could not find any place where I can pin the Matrix. Could you add a pin to the Matrix Hub and Edit Matrix?

**Comment by jlpereira** [comment]
Aha, different issue. Yah no problem, adding now

**Comment by proceps** [comment]
Pin button is present, I can select pinned matrix. But after selection, there is no link to add OTU to the matrix and proceed to the Matrix row coder interface.

Side issue, when OTU added to the matrix, please open Matrix row coder in a different browser tab, because if I need to add several, and I use the browser return button, I can get to the dashboard, but the search preferences get cleared, I have to do the search again. Which is inconvenient. I will discuss this in different issue in details.

**Comment by jlpereira** [comment]
> Pin button is present, I can select pinned matrix. But after selection, there is no link to add OTU to the matrix and proceed to the Matrix row coder interface.

You mean this checkbox? this one should add the current otu to the matrix and open MRC.
<img width="239" alt="Captura de Pantalla 2020-05-22 a la(s) 23 34 28" src="https://user-images.githubusercontent.com/16530364/82719897-f055ea80-9c84-11ea-9ccd-01503bd97565.png">

**Comment by proceps** [comment]
Yes, exactly, when I normally select the matrix, the button "Matrix row coder" is visible, but if select pinned matrix, the button is not visible.

**Comment by jlpereira** [comment]
Aha, found it. Pushing in a bit.

**Comment by jlpereira** [comment]
Should be fixed now
