### ISSUE TITLE
Task - Edit matrix - truncates the rows. 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1381]
In the Matrix Edit interface, I cannot see all OTUs linked to the matrix. See for example Scaphytopius matrix in the 3i database. It has more then hundred rows in the matrix, but Edit Matrix displays all descriptors, but only about 30 OTUs attached to the matrix.

**Comment by mjy** [comment]
@jlpereira This will have to turn into pagination.

**Comment by proceps** [comment]
@mjy can we do it without pagination, or envision and easy way to do entire list? May be extend Observation matrix dashboard, to see all OTU from a particular matrix? Probably more related to #1377

**Comment by mjy** [comment]
You have matrices with 10s of thousands of rows don't you?!

**Comment by proceps** [comment]
For images - yes, for character states, about 500 now, eventually 2000-3000.

**Comment by mjy** [comment]
So you want a table with 15k rows?  That's not going to be very performant
with all the rendering... and it's also not very user friendly, is it?

**Comment by proceps** [comment]
No, I do not want a table with 15k row, I want efficient filter select a particular genus for example. I have about 1000 genera in on subfamily, I cannot create a matrix for every single genus. And it is not efficient to assemble this matrix every time I want to see a subset.

**Comment by mjy** [comment]
Maybe you should describe what you want in th title and the description...

**Comment by proceps** [comment]
Well this one was just a bug with this particular interface. The number of rows get truncated. pagination could be a solution. For now interface randomly shows only about 30 rows. Filtering otus - another issue #1377.

**Comment by proceps** [comment]
same as #1126

**Comment by proceps** [comment]
Sorry, this is not Matrix Hub, this is "Edit Matrix" task, this is probably the confusion....
