### ISSUE TITLE
Task - Matrix row coder - rotate the matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1385]
If I remember, when originally implemented by the company, there was an option build into the code to rotate the matrix 90 deg. So I can select a particular character, and have all linked OTU/collection objects listed as rows, so that I can quickly change scoring of one particular character for all rows. If this already build into the script, could we provide this functionality in the interfaces? 
To implement.
1. Add a scoring icon next to each descriptor in the Edit Matrix.
2. Once selected show the same Matrix row coder interface, Each line has OTUs, instead of the character names, the rest of the functionality is the same.

**Comment by proceps** [comment]
is it the same as #493?

**Comment by jlpereira** [comment]
Done
