### ISSUE TITLE
Task: Transcribe Depiction Error Message

### ISSUE THREAD

**Issue by jnodel** [SpeciesFileGroup/taxonworks#1386]
**Describe the bug**

In the "Task: Transcribe Depiction" when I fill out the information for a specimen and tell it to save, I get an error message. Yet most times, the metadata I filled out saves regardless, as after I get the error message, I can go back to the "TODO list" and find that the information has saved.

**To Reproduce**
1. When I fill out information in the "Task: Transcribe Depiction"
2. Then I fill out, for example, the identifier, namespace, buffer collecting events, buffered determinations
3. And I click "Save and Next"
4. I get an error message.

<img width="724" alt="Screen Shot 2020-03-27 at 9 51 09 AM" src="https://user-images.githubusercontent.com/62450797/77762844-7e5c7e80-7010-11ea-9641-63249d9ade01.png">
<img width="677" alt="Screen Shot 2020-03-27 at 9 51 26 AM" src="https://user-images.githubusercontent.com/62450797/77762864-89afaa00-7010-11ea-9a62-9cc08c3c798a.png">

<provide a screenshot>

**Expected behavior**
I expected to get a message/notification that my work had saved.

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - Taxonworks
- Production

**Comment by mjy** [comment]
I think this has been handled, please reopen if you encounter again.
