### ISSUE TITLE
Task - Comprehensive collection object - date format

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1390]
Please change the fields for the date in the Day - Month - Year order.
Most of the specimen labels have the date in this format, and it is hard to process data in reverse order. I do mistake every second time I work with the form. This will also match to the filed order on the Source task.

**Comment by mjy** [comment]
I think that's fine, as long as it isn't month-day-year maddness.

**Comment by proceps** [comment]
Please return the date format.

**Comment by mjy** [comment]
The format follows the standard as it is rendered.  There was a long chat about this.

**Comment by proceps** [comment]
It is following the standard, which is good for the data exchange, but the task is designed for efficiend data parcing. 99.9% of the labels has data in a format DD-MM-YYYY, or MM-DD-YYYY, or something similar. The task was originally designed in YEAR-DD-MM, and it was extremely difficult to work with the data. When rendering or exporting data, the date could (and should) be exported in a preferred format.

**Comment by LordFlashmeow** [comment]
YYYY MM DD is unambiguous, and reduces the risk of confusing MM/DD and DD/MM formats.

**Comment by mjy** [comment]
Some confusion, but not all, is eliminated by validation.

**Comment by proceps** [comment]
The format is unumbiguous, but we work with specimen labels and literature, this is data exchange format, but not the format of the data presentation, at least in historical specimen labels, MM/DD, DD/MM is another issue, you have to interpret the label data and know the origin. MM/DD is mostly used in US, while DD/MM in Europe. if you have label 07/12/1950, you would have hard time resolving it. I really like to parse data the way they are presented on the label, not the "standard" way, which is designed as a standard for data exchange. At the very beginning ot TW development we agreed that the tasks should be optimized for workflow. The standards are embeded in the model, but hidded from the user in all cases where standards make data processing more complicated.

**Comment by mjy** [comment]
Closing as out of date.
