### ISSUE TITLE
Grid Digitizer not reset when new grid is added

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1393]
**Describe the bug**
Grid digitizer "type" selections (e.g. collection object to be created, "None") are not reset upon grid digitizer "Set"

**To Reproduce**
1. When I  go to grid digitizer.
2. Then I see a certain grid preset or default.
3. And I want to use a different preset so I go to the "#" symbol.
4. And I enter the number of rows and columns I want and hit "set".
5. The previous selections are still set and are not internally consistent (e.g. a checkbox means both create a collection object and don't create a collection object and mark it as "None" or one of the other dropdown options. 

**Expected behavior**
Upon hitting "set" - all checkboxes should reset to the default of "create collection object" and should all be "checked".

Grid digitizer upon opening:
![image](https://user-images.githubusercontent.com/11411328/78076351-db876580-736b-11ea-939e-d839904d389e.png)

Grid digitizer after setting a different number of columns and rows. Note how a "check" can mean different things.
![image](https://user-images.githubusercontent.com/11411328/78076444-0a054080-736c-11ea-8918-3c1dbf0d1541.png)

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox - 42a024c on 2020-03-31T01:56:43Z
- Production
- Chrome

**Comment by tmcelrath** [comment]
This is back in production, please re-open.

**Comment by debpaul** [comment]
Question, in future development, could we use "edge detect" instead of setting number of rows/columns? (Inselect already does this?) Yes, I can create a new ticket if need be.

**Comment by tmcelrath** [comment]
@debpaul probably best for new ticket

**Comment by tmcelrath** [comment]
Can I also bump this up as a bugfix? @mjy @jlpereira
