### ISSUE TITLE
Question - The “arbitrary combination of letters” option is not as a Gender/form option

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1398]
@proceps Should it be?

**Comment by proceps** [comment]
Arbitrary combination of letters is always treated as a noun in apposition

**Comment by proceps** [comment]
Arbitrary combination will be an etymology

**Comment by mjy** [comment]
Thanks.  Can you please add this to the FAQ here:  https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/faq/nomenclature.md.

If you can, answer #14 from that issue tracker on that FAQ too please.
