### ISSUE TITLE
Enhancement: Radial annotator

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#1401]
In the 'Comprehensive Collection Object Form'
Under 'Determinations'
After a determination is added, there used to be a radial annotator so that the information could be edited. I found it useful and used it often.
Please return it!
Thanks!

**Comment by tmcelrath** [comment]
Want to be able to edit determinations via radial annotator in comprehensive.

**Comment by tmcelrath** [comment]
E.g. here:
![image](https://user-images.githubusercontent.com/11411328/78386280-e710a180-75a2-11ea-8852-3af4ac7fe92a.png)

**Comment by tmcelrath** [comment]
Want to be able to edit that determination. At least be able to go to it (e.g. add date, modify determiner, etc ...)
