### ISSUE TITLE
"has already been taken" error message in Comprehensive specimen digitization

### ISSUE THREAD

**Issue by jnodel** [SpeciesFileGroup/taxonworks#1402]
**Describe the bug**

Recently, when typing in some of the verbatim information for a slide specimen for its label in the comprehensive specimen digitization tab, I have been seeing an error message. This occurs, I believe, when I'm typing in a label that has the exact same text as another slide's label.

**To Reproduce**
1. When I am working on the Collecting Event in Comprehensive Specimen Digitization 
2. Then I type in the label verbatim, i.e. "Host. Chicken Durham, N.H."
3. And I click save
4. It doesn't save, and I get the error message popping up on the bottom of the screen "has already been taken"
<img width="326" alt="Screen Shot 2020-04-03 at 12 16 15 PM" src="https://user-images.githubusercontent.com/62450797/78382469-ed078200-75a4-11ea-9c10-6d570af47eab.png">

<provide a screenshot>

**Expected behavior**

Normally I would get a message that the information I had put in had saved, even if one specimen has a label with the same text as a specimen with another label. 

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production

**Comment by mjy** [comment]
This is not a bug- it means that that exact text exists in a verbatim label, therefor it can not be re-used, as it must exist in the database already.  You should see an option to choose the existing label when it matches.

**Comment by jnodel** [comment]
Got it, thank you!
