### ISSUE TITLE
Auto-save is bad for productivity by forcing you to wait and/or to repeat inputs

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1405]
I don't know what good is auto-save supposed to do, but the inconvenience far surpasses the potential benefit.
And I'm not talking about the nerve-wrecking chime which could totally be optional.

Sometimes when I'm editing something using **Edit taxon name** for example, I have to punch the info many times because in the first ones the system is too busy doing whatever it does to fulfill the madness of auto-save and makes me wait.
Sometimes the **clone author from source** makes the name of the person to appear twice.
Sometimes when I save, the **Etymology** is lost so I have to input it again.
All those mentioned problems are very bad for the productivity, and I believe all of them are related to auto-save.
Can't we just toggle this function off? My life would improve a lot this way...

**Comment by tmcelrath** [comment]
Chime can be muted by right clicking on the tab and selecting "Mute this site"

**Comment by adrik29** [comment]
@tmcelrath -- ha! that's good to know, thanks a lot.

**Comment by proceps** [comment]
There is an issue for etymology not being saved: #649
People duplication issue: #1112

I love autosave. The only problem for me is saving page numbers. When the source is selected, and I type the page number and continue editing taxon name (go to some other fields) the form is locked for 3-4 seconds before the page number is saved. Could this save be performed on the background, and not lock the form?

**Comment by mjy** [comment]
So, list of issues:

* [ ] etymology lost
* [ ] clone from source authors are duplicated
* [ ] page number updates lock the form

**Comment by adrik29** [comment]
@proceps -- if some people love auto-save while others loathe it, there might be a on/off toggle, so each one could customize a little bit their work space. My world would be better WITHOUT it.

**Comment by mjy** [comment]
Unfortunately toggling complex functionality isn't really an option for us, it isn't a sustainable software development practice, so there will be a hard no on that option.  

@jlpereira is looking at the three issues identified above.  If afterwards we can not satisfactorily manage the balance b/w auto-save and not (it is frankly confusing because it doesn't apply to all options in this form), then we'll remove it.

**Comment by mjy** [comment]
@adrik29 when is the last time you've seen duplicate authors?

Etymology is not auto-saved, you must use ctrl-s to save it.

**Comment by mjy** [comment]
@adrik29 we're struggling to see the problems.  If you can come up with steps to always replicate a problem that would greatly help.  Alternatively can you drop screenshots here to illustrate the problem.  I think we're missing something specific to your workflow.

**Comment by adrik29** [comment]
OK, Matt, I'll try to show you something specific with screenshots.
Anyway, **Auto-save** interrupts when you are quickly entering data (a few seconds for each box -- which is annoying because it is cumulative and you have to stop what you're doing to wait for the auto-saving of auto-save).

**Comment by mjy** [comment]
We have had another complaint from users about auto-save and not, people find differing behaviour across tasks as confusing. Which ones have auto-save, which ones don't.   

Standardizing "your data are not saved unless commanded" removes this confusion.

**Comment by adrik29** [comment]
In my humble opinion:
I'm pretty sure we'll always have a good share of people like Dmitry who love autosave and people like me who hate it (just because it interrupts other actions I'm doing by jumping in front, causing disruption and frustration in my flux of work, forcing me to wait for an action that I never requested in the first place).
If you could let the user customize his settings to be able to choose.... that would be a fair option.

**Comment by proceps** [comment]
I do not like to wait either. But scrolling to click save button also takes time. You also have to understand that this form touches about 7 different tables. When you sent for example taxon name relationship, you are linking two TaxonNames. in case of error you have immediate response. In case of original combination you are setting 2-6 relationships. Authors as people require separate save. You would actually need separate saves on different actions. Like in Specimen task (about the same level of complexity). You can not create identifier (which is not base on the name space) unless you previously saved the record. You cannot create a georeference before you saved the record. Determination requires separate save. For me it is constant scrolling back and force.

**Comment by adrik29** [comment]
@proceps -- thanks for the very useful explanation from the "other side" point of view. 
So, auto-save plays a major role by pre-checking things.
Now I will think twice before loathing auto-save...

**Comment by proceps** [comment]
page save should not block editing any more.

**Comment by mjy** [comment]
@proceps I minor though important comment in all this. 

> but scrolling to click save button also takes time

1- You should *never* be scrolling or clicking the button if your arguement is efficiency, hitting `ctrl/alt-s` is trivial, and easily becomes part of ones muscle memory if practiced.  

2- Being interupted with a save, when it may not be necessary as you might need to do further work, is arguably just as much a problem as having to click ctrl-s when you feel you want/need feedback from the form.

**Comment by proceps** [comment]
Autosave checkbox is implemented on the top of the task. Autosave now could be disabled.

**Comment by adrik29** [comment]
@proceps: Wow... I'm anxious to try this new functionality. Will share this news with my coworkers. Thanks a lot!!!!
![image](https://user-images.githubusercontent.com/46284943/87707977-63a54580-c778-11ea-922f-b3d04689c8d8.png)
