### ISSUE TITLE
Incertae sedis AGAIN -- Edit taxon name

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1406]
In spite of the issue with incertae sedis is marked as resolved, I still have problems with it:

(1) it should be inCCCCCCCCCCertae with -c not -s.
Look here:
https://opiliones.fandom.com/wiki/Incertae_sedis

(2) I have a genus Gjellerupia which doesn't belong to any family in the infraorder Grassatores. Therefore it is a incertae sedis taxon.
![image](https://user-images.githubusercontent.com/46284943/78463983-31387680-76ba-11ea-8d14-264e9fb7fbde.png)

But whenever I set the incertae sedis button here:
![image](https://user-images.githubusercontent.com/46284943/78463991-444b4680-76ba-11ea-863d-7b0f7d00f491.png)

I get the msg:
![image](https://user-images.githubusercontent.com/46284943/78463970-02ba9b80-76ba-11ea-9673-587e1f59452a.png)

What is happening?

**Comment by adrik29** [comment]
Just a comment: I manage to set a genus in a superfamily as incertae sedis, but NOT in an infraorder.

**Comment by proceps** [comment]
I will check the model. Please check the task, it could be a label issue:
![image](https://user-images.githubusercontent.com/5597748/78503608-561a0180-772d-11ea-8296-ff648fe96eee.png)

**Comment by mjy** [comment]
That label is fine, it maches exactly with https://opiliones.fandom.com/wiki/Incertae_sedis.

Where exactly do we see `insertae`?  Screenshot?

**Comment by mjy** [comment]
Ah, I see..

**Comment by adrik29** [comment]
Dmitry: anyway the big problem is not the typo (because it is only in a hidden part), but the inability to use incertae sedis with infraorder, although it works fine for family.
