### ISSUE TITLE
Comp. Digitization Form - OTU in Biological Associations does not appear to save

### ISSUE THREAD

**Issue by LauraPorturas** [SpeciesFileGroup/taxonworks#1407]
Issue:
In the Comprehensive specimen digitization form under 'Biological Associations', the 'Related' OTU doesn't save.

1. When I select an OTU under the 'Related' section in 'Biological Associations', it appears as though the OTU is added to the form
<img width="403" alt="Screen Shot 2020-04-06 at 10 05 40 AM" src="https://user-images.githubusercontent.com/62353864/78569032-fab14780-77f0-11ea-97fb-836c7db39ed6.png">
2. Then I press the green 'Save' button in the top right 
3. And the associated OTU seems to disappear
<img width="401" alt="Screen Shot 2020-04-06 at 10 06 26 AM" src="https://user-images.githubusercontent.com/62353864/78569076-0bfa5400-77f1-11ea-825d-324d51070737.png">

Browser: Chrome

**Comment by mjy** [comment]
Hi @LauraPorturas, thanks for filing the issue.  You must "Add" the relationship so that it shows in the list below before saving the record.  Let us know if that works.

**Comment by LauraPorturas** [comment]
'Add' is greyed out and can't be selected, pressing it doesn't seem to do anything.

Thanks for your help,
Laura
________________________________

**Comment by mjy** [comment]
You must have all the components of the relationship selected, so that the three grayed out lines on top are filled?

**Comment by LauraPorturas** [comment]
Gah! Thank you. That was the problem.
________________________________

**Comment by mjy** [comment]
No worries, thanks for the good report with screenshots etc.!
