### ISSUE TITLE
Task - Find source - hyperlink to Citation by Source

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1411]
The hyperlink to Citation by Source does not work
![image](https://user-images.githubusercontent.com/5597748/78814490-510abb80-7994-11ea-9008-8ccb9ca50fc4.png)

If I use this link from Navigate radial, link works properly.

If I use Navigate radial, click View, click Report, click Citation by source. The hyperlink is also wrong.

**Comment by mjy** [comment]
@proceps Find source is gone, this is in recent now?
