### ISSUE TITLE
Task - New asserted distribution - Remove button Save

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1412]
Remove button Save
Rename "Save and New" to "Save"

The first button is confusing. It took me time to realize that save button creates record, but after saving and editing, you are modifying the same record. It is much easier to delete a record if it is wrong.
It would be even more friendly, if the record is created when the 3 parts are locked.

**Comment by mjy** [comment]
Not sure it was easier- we needed edit because people were forgetting page numbers.

**Comment by proceps** [comment]
Edit button could be Added to the list after the record was created. It will be more useful.

**Comment by jlpereira** [comment]
Done
