### ISSUE TITLE
Model - Source - formatting for the book

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1415]
"Author (1900) 1 BookTitleTitle. Edition. Publisher."

Volume comes first. 
Then book title, not separated from title.
Pages are not included.

This is the string which I get in TW for books.
The fields provided:
Author (person): Author
Year: 1900
Volume: 1
Title: Title
BookTitle: BookTitle
Edition: Edition
Publisher: Publisher
Pages: X+100

**Comment by proceps** [comment]
The same looks little bit better when I use "Inbook" format:
"Author (1900) Title. In: BookTitle. Publisher, p. X+20."

**Comment by mjy** [comment]
The format is BibTeX with a CSL style, find an alternate style if Zootaxa
is not OK and we'll regenerate everything.  We are *NOT* building custom
styles.

**Comment by mjy** [comment]
Here are the several thousand options to choose from: https://github.com/citation-style-language/styles

**Comment by proceps** [comment]
I tested few options:
Zootaxa
ZooKeys
Entomological Society of America
Florida Entomologist
Systematic Biology
Zoological Journal of the Linnean Society

Zootaxa has the most reasonable style. I saved those styles as commented in the Source.rb, in case somebody want to experiment. The missing pages was the main concern...

I close the issue for now.

**Comment by mjy** [comment]
There very well be better alternatives for validation purposes - did you check out any of the Chicago- style ones?

**Comment by proceps** [comment]
I checked:
Chicago-annotated-bibliography
Chicago-fullnote-bibliography-16th-edition
Chicago-library-list

In those the author names are fully spelt (not abbreviated to initials). And the title is in quotation marks. I would leave Zootaxa for now. 

Probably a suggestion for users:

When you have a book cited, use only the Title textbox for the Book title; leave Book title blank.

When the book chapter is cited: Select "in book" as the type; chapter name goes to the Title; Book name goes to the Book title textbox.
