### ISSUE TITLE
Could we have the "blue eye" filter set for specific configurations all the time?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1416]
The way TW is built now, all eye filter options are already set and frozen solid in "Browse Nomenclature". Each time I change screen, the original preset gets back.
I, for one, would love to set my filters with the tag "Origin" ON all the time. It would make it much easier for me to see things at a glance.
Is there currently any way to lock the eye filter to always have "Origins" **on** for example?
Or if there isn't, is there a chance of implementing it as a toggle?

**Comment by mjy** [comment]
This is the proposal that will evolve in #1332, sorry I didn't add a good description there.  Closing this as duplicate and pointing it there.
