### ISSUE TITLE
User - preferences - quick-recent-pinboard-search interfaces

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1417]
As a user, I found it is very inconvenient and frustrating to work with quick-recent-pinboard-search interfaces. In about 90% of cases I have to default to a search mode, since information which is displayed is irrelevant. I could find only very few occasions when recent or quick helped me. In most cases they only take display space and require extra mouse clicks to go to the search mode. Edit nomenclature probably the only place where quick is useful for relationships or statuses, since those have predefined values. But even there I tend to go the complete list more often to set more advanced status.
Could we provide a user default preference where the search is a default option?

**Comment by mjy** [comment]
In our coding speak these are "smart-selectors".

Completely agree we need to unify behaviour and make it a preference.  

Side note. Some still might be broken, perhaps in 2 ways: 1) results not being displayed (UI), 2) results not being properly returned (backend).  I think if we got Quick tuned it would work much better for you/everyone, but maybe not in all cases.

**Comment by mjy** [comment]
@jlpereira This might be a candidate for the cookie store.  

Another note, in general we have to be supremely careful about propagating preferences, this greatly complicates the application.  If we can figure out UI fixes or improvements that will work those should be preferred.

**Comment by proceps** [comment]
in distribution, in particular, where I would expect it to be the most useful. I do not understand how recent is generated. In last two days, I entered few hundred records from China, but I still do not see China in the list. Some times, something popes up, when it was entered 3-4 days ago, but I never see any Geographic area which I entered as a previous record. The thing is even more complicated, since in many cases, when I enter a new OTU-Geographic area-Citation triplet, the Combination of OTU-Geographic area may already exist in the records, in this case, only a citation a new piece of information, but I still would expect to see a suggested Geographic area as a recently used.

**Comment by proceps** [comment]
I do not like cookie settings, those tend to disappear when you clear your browser...

**Comment by mjy** [comment]
That's not the issue- the UI acts on the cookie, which is built once from the database if missing.

**Comment by jlpereira** [comment]
Why not sessionStorage? We can load the preferences on the first visit and nothing will be store on the computer after close the page.

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

**Comment by mjy** [comment]
@jlpereira right, I don't mind what local mechanism.

I am still worried about preferences everywhere vs. general improvements.  Adding preferences seems to mean we haven't fully thought out the general optimal way of doing things completely...

**Comment by proceps** [comment]
sessionStorage should work, if I made a change while editing and this stay during the day, this should work. If Quick or Recent improved and will be more helpful, the interface will stay on that option as long as it is useful.

**Comment by proceps** [comment]
could we at least search box together with recent (we do this already in few other places, authors for a source for example). In particular in OTU radial for geografic area, I need the search box be visible all the time. Now with sql update the recent are more useful. but still quite often I have to jump to the search interface, and it would be extremely useful to have it open all the time.
