### ISSUE TITLE
Task - Edit TaxonName - delete original source

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1419]
Original source is deleted without a warning. Please add a pop up.

**Comment by mjy** [comment]
Doesn't it show a soft validation?  All behaviour of trash can rows shoudl be the same?

**Comment by proceps** [comment]
Soft validation works, but all delete action should provide a warning before the item is deleted. Today I deleted something just by mistake.

**Comment by mjy** [comment]
Every single delete everywhere?

**Comment by proceps** [comment]
Yes. And it is already implemented in most of the places. On this page, I thing, this is the only place. The other option would be to implement a restore mechanism, like on Amazon. But this is much more complicated. The only places where you do not need is is pin/unpin features, where you can immediately revert the change.
