### ISSUE TITLE
Creating a New Biocuration Group or Class and New Preparation Types

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1423]
I would like to know why is it necessary to have a minimum of 20 characters for descriptions while existing some categories that can be very shortly described. For example: female or egg

**Comment by mjy** [comment]
Hi @mabecabrera, thanks for your question! The short answer- provenance and improved semantics that will lead to interoperability betwen your dataset and others.

Most of the user customization inherits from TaxonWorks "Controlled Vocabulary Term".  
There we are encouraging curators to spend a couple minutes thinking about adding something that has long term consequences to curatorial workflows, i.e. to think about what it means to tag something. It's often far more subtle than we think at first glance. For example, which of the many different versions of 'female' do you mean? http://bioportal.bioontology.org/search?utf8=✓&query=female.  I suspect it's likely a tag based on examination of terminalia (or not- perhaps exual dimorphism in antennae), as opposed to a genetic assay.  This might seen pedantic, but it can make a difference. If you are creating predicates it could be this bad: https://github.com/tdwg/dwc-qa/blob/master/data/GBIFDistinctValues/GBIF_distinct_sex_2017-02-27.csv.  Ouch! 

A good definition describes not only what you mean by the term or label, but also how a user should consistently apply it.  I.e. a naive curator could read it and act in a consistent manner without talking to the person who created it.  This is important for downstream computing/statistics/data merging etc. etc.

Finally, we strongly encourage curators to add not only a definition, but also find a URI that points to the definition you'd like others to find.  See the bioportal query above.  If you do this it means: things with this value are the same as someone data somewhere else that also points at the URI, you can combine them.

Hope this helps.

**Comment by mjy** [comment]
P.S. Moving this discussion, once resolved, to `taxonworks_doc` with an issue to add it to the FAQ would be a good idea.  I.e. record it in documentation.

**Comment by mabecabrera** [comment]
Hi Matt! Sorry for my delay. Thank you so much for your answer. I agree with you that when so many curators working here it is better to have good definitions. 

Hope to be helpfull for the team and TW!

Belén


    El lunes, 13 de abril de 2020 21:36:40 ART, Matt <notifications@github.com> escribió:  
 
 


Hi @mabecabrera, thanks for your question! The short answer- provenance and improved semantics that will lead to interoperability betwen your dataset and others.

Most of the user customization inherits from TaxonWorks "Controlled Vocabulary Term".
There we are encouraging curators to spend a couple minutes thinking about adding something that has long term consequences to curatorial workflows, i.e. to think about what it means to tag something. It's often far more subtle than we think at first glance. For example, which of the many different versions of 'female' do you mean? http://bioportal.bioontology.org/search?utf8=✓&query=female. I suspect it's likely a tag based on examination of terminalia (or not- perhaps exual dimorphism in antennae), as opposed to a genetic assay. This might seen pedantic, but it can make a difference. If you are creating predicates it could be this bad: https://github.com/tdwg/dwc-qa/blob/master/data/GBIFDistinctValues/GBIF_distinct_sex_2017-02-27.csv. Ouch!

A good definition describes not only what you mean by the term or label, but also how a user should consistently apply it. I.e. a naive curator could read it and act in a consistent manner without talking to the person who created it. This is important for downstream computing/statistics/data merging etc. etc.

Finally, we strongly encourage curators to add not only a definition, but also find a URI that points to the definition you'd like others to find. See the bioportal query above. If you do this it means: things with this value are the same as someone data somewhere else that also points at the URI, you can combine them.

Hope this helps.
