### ISSUE TITLE
Radial annotator - Identifier -> Namespace smart selector initialization

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1427]
```
When I open the radial annotator,
  and select an identifier,
     then when I choose local
         and I have no Quic namespaces
            then I should default to show the Search tab
```

**Comment by jlpereira** [comment]
In other places we handle this selecting the tab that have records. For example, if "Quick" is empty but "Pinboard" have records, that one will be selected. We gonna handle this on a different way here?

**Comment by mjy** [comment]
Sorry, wasn't fully clear.  We want the exact same experience everywhere.

Start with button on left, which should always be Quick, check for records, if none, then move one tab right, check, none, move, check, none -> Search (last on right) is selected, with cursor in the search box ready to type.
