### ISSUE TITLE
New Task - Asserted distribution change

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1433]
As a user, I need an interface to select all assorted distributions linked to a particular geographic area and reassign them (all or some) to another geographic area.

As a bonus: if OTU/geographic area combinations already exist, move the citations, and destroy the original asserted distribution records.

**Comment by mjy** [comment]
This is a good straightforward idea-  "Manage asserted distributions".  The model methods needed are very straightforward.  The form is as simple as previewing records from one, then another, then agreeing to merge.

Let's think about whether we need somethign more sophisiticated in terms of detection (what records could possibly be merged), reporting (how do I see outliers), etc.?

**Comment by proceps** [comment]
For me, I just occasionally run into something like Java. Which is an island of Indonesia. But Java also a province of Geogria, I think. We do not have a record for the Island, since it is subdivided into several provinces of Indonesia, which we do have. But not the Island. So I need to move about 100 records from Java (Georgia) to Indonesia.

**Comment by proceps** [comment]
fixed
