### ISSUE TITLE
Enhancement - New task/improvement to "New combinations" - bulk new combinations

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1441]
When I am creating a lot of new combinations from a single source (e.g. someone moves 20 taxa to a new subgenus, elevates taxa, or synonymizes) - then, when I move those taxa, I want to create that combination as a new combination, not just move the parent. 

Possibly need a model for this? Basically, creating combinations one at a time is time intensive and the workflow needs to be improved. Like, it would be good to have a task that is "from this source, I check off a bunch of members of a genus and give them a combination".

**Comment by proceps** [comment]
I believe this is resolved now with a new combination section in edit TaxonName
