### ISSUE TITLE
Task- Display total # of completed transcriptions

### ISSUE THREAD

**Issue by kjv5069** [SpeciesFileGroup/taxonworks#145]
I'm unable to find a way to view the total number of completed transcriptions. Does this exist/ if so, where can I access that? If not, it would be a beneficial enhancement.

**Comment by mjy** [comment]
Can you say a little more about what "completed" means to you?  Is it
depictions that are green on the "TODO" list?

Thanks!

**Comment by kjv5069** [comment]
That's correct. It would be very helpful if there were a way to view the total number of depictions that are green on the "TODO" list, without scrolling through the entire "TODO" list.

Thank you!

**Comment by mjy** [comment]
Done, added to the TODO list.  And the breakdown works.  OCR may be minimally better too.  Thanks for the report.
