### ISSUE TITLE
Enhancement - Collecting Object Filter - find objects "without" things

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1455]
As a user, I want to find collection objects that are missing certain things. 

Use case: I want to find collection objects that:
1) [x] lack depictions -> param `depictions`
2) [x] lack identifiers -> param `identifiers`
3) [x] lack assigned determinations -> param `determinations`
4) [x] lack assigned collecting events -> param `collecting_events`

This would allow me to find and delete collection objects that are accidentally created or have had their depictions moved but were not destroyed

**Comment by mjy** [comment]
Good issue.  Straigtforward to implement.
