### ISSUE TITLE
Browse nomenclature/taxa: problem with separation in cited names and citations

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1457]
The more citations the more confusing this gets. While experimenting in the OSF sandcastle I accidentally created (wanted to test something else) a confusing situation with just two citations. Only the page numbers indicate that the references are chronologically inverted.

![grafik](https://user-images.githubusercontent.com/33210201/80164670-04d49380-85b0-11ea-9692-904ee52826e6.png)

Would it be possible to offer the selection of an integrated display form where cited names are directly listed in chronological order with the corresponding references? The more citations a particular taxon has, the more cumbersome it becomes to jump up and down to look up the references for the cited combinations/relationships.

**Comment by proceps** [comment]
@typophyllum I had the same problem. Just yesterday pushed a change where the references are highlighted and with the mouse over, the full source is displayed in a popup. Not on the production yet.
Does this solve the issue?

**Comment by proceps** [comment]
<img width="626" alt="Screen Shot 2020-04-23 at 8 48 45 PM" src="https://user-images.githubusercontent.com/5597748/80166800-6858c400-85a4-11ea-94cc-7b630dab2738.png">

**Comment by proceps** [comment]
For citations, you have to provide the publication date for each source, this keep the order of the sources.

**Comment by typophyllum** [comment]
Yes, nice idea. This could possibly solve the issue indeed. Of course the user would need to know that mouse-over provides this information.

(In OSF it would be an close-to-impossible amount of work to investigate publication months for thousands of references. Perhaps @LocoDelAssembly could extract a list of same-author-and-year references to add the data after the migration. Wouldn't solve the issue of same year/different authors for the sequence of cited names though. It would be better to somehow import directly the curated sequences from OSF.)
