### ISSUE TITLE
Bug/Enhancement? - Georeference incompatibility too sensitive - does not allow for borders

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1458]
When I am adding a polygon as a georeference, and the borders of the polygon are the same as the borders of the geographic area, then I cannot assign those borders. 

See example of Du Bois Ill and its geographic area below:

Use case:
![image](https://user-images.githubusercontent.com/11411328/80218644-11380b00-8607-11ea-9dfb-dde885f92f70.png)

Furthermore, the polygon tool automatically snaps the polygon points to the edges of geographic areas, which automatically makes that georeference "Outside the boundaries".

Solutions: make it so that exact matches with edges do not cause "is not contained" error to appear. Is the model for georeferencing incompatible with this?

@mjy @jlpereira thoughts? I'm guessing this is a difficult situation to model?

**Comment by mjy** [comment]
Closing as outdated.
