### ISSUE TITLE
OTU radial - determination section generates an error

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1460]
OTU radial the Determinations section show that there are some records, but when the sector clicked I see an error message. "404Not found".
See https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=359784
in 3i database.

**Comment by mjy** [comment]
This is because we have OTUs from another project in your data.  See https://github.com/SpeciesFileGroup/taxonworks/issues/1439.

I will work to display the bad records ASAP.

**Comment by proceps** [comment]
This is a new records, You want to say that comprehensive task is not properly scoped to the project?

**Comment by proceps** [comment]
Actually Edit taxon Name show this specimen record, but as a type (this is not examctly the same as determination). But when I create the determination in Comprehensive, it is automatically copied down for the type selection. It should be the same OTU.

**Comment by mjy** [comment]
Don't add new issues (copying names) to existing issues (section generates 404).

**Comment by mjy** [comment]
OTU autocomplete was not scoped to project.  It is fixed now, but there are bad data.  404s are always about cross-project issues, almost 100%.  There is a prelimianry report in the Gitter log.
