### ISSUE TITLE
task - edit taxonName - link to the holotype

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1461]
When I have a holotype associated with the name, I can see the holotype record in the Quick type form, but there is no any link to open the same record in comprehensive. Additional link is required in both EditTaxonName task and Quick type task (open the same record in in Comprehensive)

**Comment by mjy** [comment]
Quick has it already - "Expanded edit"

**Comment by jlpereira** [comment]
I think what @proceps say is open the collection object of that type material.
