### ISSUE TITLE
Edit taxon name: type species of substitute names of genera

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1463]
Among the eleven forms of type designation none seems to be suitable for substitute names of homonyms. In OSF we have "inherited from replaced name".

**Comment by proceps** [comment]
There is no such form in the ICZN. It is just stated, that it should be the same as replaced genus. So there is a validation which warns you if the type designation is different.

**Comment by typophyllum** [comment]
ICZN 67.8. says the type species of old name and replacement name are identical. Without knowing the context, "inherited from replaced name" is an important piece of information. If no reason for the listed types species is mentioned, the following two cases are indistinguishable:

1) The old name has a type species which is passed on to the new name.

2) It is unknown whether the types species is based on the old or the new name.

So available information (1) is currently treated like missing data (2).

**Comment by mjy** [comment]
Can we infer the context because you have added the type specimen to type name?

**Comment by typophyllum** [comment]
I'd like to see the reason with the replacement name (or specify it in case it's missing), even if the old name has it already specified. Especially thinking of a user interface where the validation stuff isn't displayed.

**Comment by typophyllum** [comment]
I just added a new substitute name in TW, made the relationship with the homonym, and selected the type species. I find it really confusing and unsatisfactory that none of the selectable reasons applies. On the one hand the user is prompted to select a reason, but in fact is expected to leave it unspecified in this case. A twelfth option like "inherited from replaced name" would make this more consistent and logical.

**Comment by proceps** [comment]
There is no such option provided in the code. In TW, if the type is not provided for the substitute name, it will be automatically added with soft validation fixes. (We can run this only programmatically now). But we expect to see a button on the taxon edit page.
"inherited from replaced name" is not a solution. The type could be fixed for a replacement name, and if the type was not fixed for a junior homonym before, it will inherit the type fixation from the new name.
Also, there are coordinated taxa. the genus Aus and subgenus Aus (Aus), they have the same type, you can also claim the inheritance of the type from one to another. Both of them has the author, which is also the same. There are many instances when the property of one name is inherited, but again, this is bidirectional. We can only validate that this property is the same, and add the property, when it is missing using the fixes.
