### ISSUE TITLE
Book pages don't appear?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1468]
The form "New source" has a problem:

When I  add book pages in the box "Pages" they don't appear for example in the book display in "Browse Nomenclature".

![image](https://user-images.githubusercontent.com/46284943/80714524-6f636300-8acb-11ea-9c5f-ece21a55f3f6.png)

although they appear in the summary sheet:

![image](https://user-images.githubusercontent.com/46284943/80714778-c832fb80-8acb-11ea-8f52-428b55d9c852.png)

**Comment by mjy** [comment]
@proceps Was this the same issue you saw with the Zootaxa rendering?

**Comment by proceps** [comment]
same as #1326

**Comment by mjy** [comment]
Closing as duplicate of #1326.
