### ISSUE TITLE
task - Edit taxon name - TaxonNameRelationship - set to parent

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1469]
If by mistake I click "Set to parent" I go to the interface to set the relationship to Incertae sedis.
I realized the mistake and click Reset. And go back to the taxon search mode.
If I select the species, I do not receive an smart selector for the taxon name relationships.
The only option I have is still "Incertae sedis".
The only way to reset the form now is to refresh the page.

**Comment by mjy** [comment]
@jlpereira We will fix this, but we're going to move this functionality to a new section, so hold off on this.  Details in a bit.  The set to parent massively confused folks, so we're going to keep the functionality elsewhere.  We will also add, in the new section, ability to set 'source classified as'.
