### ISSUE TITLE
New Google Map georeference seems broken

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#147]
When I show a collecting event, and I click "Add" in the bar above, and I click "Add Google map georeference", then the task I'm taken to doesn't work (and I reload and it doesn't seem to be a Turbolinks problem).

Tested on Sandbox in FF Dev, latest version.

**Comment by jrflood** [comment]
The JS listener for this function seems to have been removed at some point.  All of the HTML elements to support he map are present.

**Comment by mjy** [comment]
@jrflood Did you fix this?  If so please comment/close.  You can also tag your commit messages with things like "Close <numbersign><number>" to auto tag this issue.

**Comment by jrflood** [comment]
This was actually fixed 9 days ago.
