### ISSUE TITLE
New Task - Export "paper" catalog

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1473]
As a user, I want to export my catalog project to a mostly "publication-ready" format. Minimally, this should include the following data levels:
1) All taxon names, relationships, combinations (text from "Browse nomenclature"?)
2) All asserted distributions for the OTUs linked to those taxon names.
3) All sources from taxon names, relationships, and asserted distributions

This exported catalog could include soft validation warnings (see issue: #1450 )

When exported, it should be assigned a "version" and always be available for reference as a snapshot of the catalog. 

Something like this ZooKeys paper may be a good starting point:
https://doi.org/10.3897/zookeys.920.39128

**Comment by kandako** [comment]
Would also be nice if we could also dump data associated with the OTU tied to the nomenclature (i.e., biological associations, type data, and asserted distributions).

**Comment by tmcelrath** [comment]
Root ID would be any of the families in our project. For example: https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=447962

**Comment by mjy** [comment]
All these features exist in the current implementation.  Closing for new issues highlighting individual issues.
