### ISSUE TITLE
Collection object work report

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1477]
In the task **Collection object work report** the users seems to be duplicated and the total count of records in the total line does not correspond with the summary of the listed separated events below. 

For example:
![image](https://user-images.githubusercontent.com/63611746/81019769-b93aa900-8e3d-11ea-811a-6966bc1cfe58.png)

**Comment by mjy** [comment]
@mabecabrera Sorry, I don't see the problem in the screenshot you listed.  The Total section summarizes everything in Sessions, for example Count is the sum (as it is in your screenshot), the average records per minute is across all data, etc.  

I'm not sure what you meant by "duplicated".  Multiple sessions are reported, a session is a work unit seperated by > 5 minutes of time IIRC.

**Comment by mabecabrera** [comment]
@mjy Excuse me. Checking now with Hernán we realize that there are two users with my name, and one of them is from OSF. So, my mistake. And as we were looking at the OSF working report there was no correspondence with the count of new registers made in TW. 
I´m sorry for the confusion.
