### ISSUE TITLE
Pop-up selecters not popping up

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1478]
**Describe the bug**

When I am in Collection Object to-do, and I try to assign a depiction to another object, the pop-up collection object selector does not appear.

**To Reproduce**
1. When I am in Collection Object to-do, and I am transcribing a depiction.
2. Then I see that the identifier is already taken, so I want to move that depiction to another CO.
3. And I use the radial annotator to select that depiction, edit it, and go to select the appropriate CO.
4. And I type in the identifier.
5. Then I do not see the pop-up box for the identifier, except maybe behind the CO annotator window. 

Note window popping up behind radial annotator window at the very bottom (just visible):
![image](https://user-images.githubusercontent.com/11411328/81077183-43245980-8eb2-11ea-8cf2-c87608a8d814.png)

**Expected behavior**
Pop-up should appear for me to select Collection Object.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Firefox
- Windows 10

Could not replicate on Google Chrome or Firefox on Mac OS.

See video sent in Gitter.

**Comment by jlpereira** [comment]
@tmcelrath where did you use the radial annotator? which task?

**Comment by tmcelrath** [comment]
"TODO"/Transcribe depiction.
