### ISSUE TITLE
Identifier::Local::Article number

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1492]
Idea is to add an identifier for sources when they use article numbers.

**Comment by hhopkins77** [comment]
https://link.springer.com/article/10.1186/s12898-020-00282-x

Here is an example of a paper that has this article number issue.

**Comment by proceps** [comment]
We do not need anything special here. The volume and number cover it. Sometimes BibTex put it in the wrong field. The pages numbers are still useful in all cases. And yes, for papers like this, the pagination always beings with 1.
