### ISSUE TITLE
Latency detection issues with slow connection causes grid digitizer uploads to never advance

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1496]
**Describe the bug**
When I have a slow upload speed (e.g. DSL) then sometimes the client will never receive an update on whether the upload has finished, and therefore never advance the client to the next screen, even though the upload has finished.

**To Reproduce**
1. When I upload an image in grid digitizer start screen.
2. Then I use a slow connection (most often repeated on DSL speeds)
3. And I upload an image.
4. And I see the progress bar complete.
5. But then I never see the screen advance to the "editing" screen. The image is uploaded server-side, but the client is not triggered to advance.

**Expected behavior**
The client should always advance if the image uploads.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chome, Firefox
- Windows 10

**Comment by LocoDelAssembly** [comment]
@tmcelrath do you have an estimate of the time it takes to upload the image? Size of the image?

Per chance did you see any errors con developers console? If indeed this is a speed problem, using https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Throttling probably will reproduce the problem every time (with the right sample file).

**Comment by mjy** [comment]
@jlpereira ee should also check the dropzone settings, could be timing out there?

**Comment by tmcelrath** [comment]
Image upload only takes <1 minute, only ~2.0 mb.

**Comment by tmcelrath** [comment]
@mjy @LocoDelAssembly Any progress on this? Getting another user reporting it with larger files too. Would really like fixed soon.

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/83574148-7fb79500-a4f2-11ea-9b88-2ab6a4da653b.png)
E.g. slack channel chat for insect collection :)

**Comment by mjy** [comment]
@tmcelrath can you email me an image or two that fails?

**Comment by tmcelrath** [comment]
https://uofi.box.com/s/83f3dck1u5kdjrv591bkf69d9jrt1g12

**Comment by tmcelrath** [comment]
Died about 1/3rd of the way in for me

**Comment by tmcelrath** [comment]
Lots of beefy files in this folder too: https://uofi.box.com/s/scmgm0v4g6xvvy6rthg1xfzb2nw74peo

**Comment by jlpereira** [comment]
<img width="1680" alt="Captura de Pantalla 2020-06-02 a la(s) 19 52 29" src="https://user-images.githubusercontent.com/16530364/83577481-a5e92f00-a50a-11ea-836f-4881c9e7c7f2.png">


Seems to works fine with that image on localhost, @tmcelrath 
It makes me thing we have a timeout problem, could you check this with your network tab open?

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/83577668-716d7700-a4fa-11ea-9678-8ab711104b0d.png)

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/83577701-864a0a80-a4fa-11ea-99d7-9335e77054db.png)

**Comment by jlpereira** [comment]
Perfect, after select "Images", press on "response"

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/83577927-1d16c700-a4fb-11ea-98bf-69e97a696ac5.png)

**Comment by jlpereira** [comment]
I will try this on sandcastle

**Comment by jlpereira** [comment]
I made a change for the timeout, should be 10 minutes now.
@LocoDelAssembly update sandcastle when you can to test this

**Comment by LocoDelAssembly** [comment]
Been doing some diagnostic test that involved changing nginx configs temporarily to get this data:
```
2020/06/02 18:40:46 [info] 104761#104761: *291964 client prematurely closed connection, client: 10.251.6.64, server: *.taxonworks.org, request: "POST /images HTTP/1.1", host: "sandcastle.taxonworks.org", referrer: "https://sandcastle.taxonworks.org/tasks/collection_objects/grid_digitize/index"
```
So I can confirm it is not server-side issue.

After extra confirmation with sandbox do I release a new production version @mjy @jlpereira?

**Comment by jlpereira** [comment]
I can confirm this fix has resolved the timeout issue, but for some reason the upload bandwidth of terribly slow on sandcastle, and its taking too much time to upload an image. I dont know if this is related with my ISP or not, but I hope this not another issue on production.

**Comment by LocoDelAssembly** [comment]
Same problem here (but same ISP too). 10 minutes to upload 15 MB (sub megabit speed)... Can you @tmcelrath or @mjy test on sandbox?

**Comment by tmcelrath** [comment]
@jlpereira @LocoDelAssembly got a successful upload of that image on sandbox!

**Comment by tmcelrath** [comment]
This fix was fixed/pushed to Sandbox right?

**Comment by LocoDelAssembly** [comment]
@tmcelrath yes, sandbox only.

Also just got a successful upload using a proxy (also located in Argentina, but has a VERY different Internet route to UIUC than my ISP)
![image](https://user-images.githubusercontent.com/4991925/83586026-d4263900-a521-11ea-8882-f8c0219e3953.png)

@jlpereira @mjy please let me know if it OK to release new TW version.

**Comment by jlpereira** [comment]
Yes, go ahead

**Comment by mjy** [comment]
@tmcelrath feel free to close if you think it's working

**Comment by tmcelrath** [comment]
Multiple users have confirmed no new instances of timeouts. Closing.
