### ISSUE TITLE
Pinboard/PDF Document viewer - PDF view button requires reload to appear

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1497]
**Describe the bug**

When I pin a source that has an associated PDF, the "PDF" button does not appear next to the source until I reload the page, causing confusion. 

**To Reproduce**
1. When I add a source to my pinboard that has an associated document. 
2. Then I click the green pinboard icon on the left of the screen.
3. And I navigate to the menu dropdown for that source. 
4. Then I do not see the "PDF" button.
5. Then I reload the page.
6. Repeat steps 2-3.
7. Then  I DO see the PDF button. 

Before refresh:
![image](https://user-images.githubusercontent.com/11411328/82222039-61dd1400-98e6-11ea-9647-c035078328c9.png)

After refresh:
![image](https://user-images.githubusercontent.com/11411328/82222101-74efe400-98e6-11ea-8c58-2aeba81a7eef.png)

**Expected behavior**
PDF button should appear without a refresh.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
@jlpereira might be tricky?  Do we need better data- attributes on the server side render so we can go back and update things?

**Comment by jlpereira** [comment]
Its related with the json response, we need to send if the object have a pdf
