### ISSUE TITLE
Task - new asserted distribution

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1499]
Two functions got broken in the Asserted distribution after the last migration.
1. I have locks on Source, OTU and Area. After saving the record, the Source seams to be preserved, but OTU and Geographic area get lost.
2.  clicking the button to Clone (Source/OUT). Instead of the source, I get a citation copied to the selected source.

Please check also the other issues related to the task.

**Comment by jlpereira** [comment]
1 - I cant replicate it. Could you try again to replicate it? make sure all locks are active.
2 - Fixed

**Comment by proceps** [comment]
Cannot replicate it today (on different computer). May be some browser caching issue? If 2 is fixed, the issue could be closed.

**Comment by jlpereira** [comment]
It should, reopen if not
