### ISSUE TITLE
Clipboard pastes multiple times instead of just once

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1500]
**Describe the bug**

The clipboard will paste multiple times, not just once. 

**To Reproduce**
1. When I am in Edit Nomenclature
2. Then I add something to the clipboard "e.g. sharp 1899 cucujidae"
3. And I can use it just fine on that page. 
4. Then I finish, save, and go to a new combination through the navigate radial. 
5. I complete that task, then click on the name I just finished, and it opens a page in a new tab. 
6. And if I use the clipboard now, it pastes multiple times, not just once. 
7. If I go back to the original tab, the clipboard works fine. Similarly, reloading the page fixes the problem, but reoccurs. 

URL get request seems to be firing multiple times:
![image](https://user-images.githubusercontent.com/11411328/82334272-5acd0900-99ad-11ea-850a-854a7fa3edc2.png)

Back on the original tab, get request firing only once:
![image](https://user-images.githubusercontent.com/11411328/82334512-b4cdce80-99ad-11ea-971d-501b8e927367.png)

**Expected behavior**
Clipboard should only ever fire once.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
@jlpereira grasping, but this is Turbolinks maybe?  We have to disable it somewhere?

**Comment by jlpereira** [comment]
Looking

**Comment by jlpereira** [comment]
Yep, turbolinks. Fixing

**Comment by jlpereira** [comment]
Fixed.

@tmcelrath now should be possible use back and forward buttons from chrome, firefox or any browser and not break anything. I didnt tested too much, but it should works propertly. Open again if is needed.

**Comment by tmcelrath** [comment]
Cool! Thanks! Been trying to replicate this forever, finally figured it out today. Glad I did :)

**Comment by tmcelrath** [comment]
@jlpereira are fixes for this supposed to be live in production? If so I'm still getting this error.

**Comment by mjy** [comment]
They are not.

**Comment by tmcelrath** [comment]
Okay just making sure.
