### ISSUE TITLE
Edited - Quantitative descriptor unit (count) does not exist

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1501]
Can we drop entirely predefined set of units? They do not make any sense. And without definition, it is extremely difficult to pic the right one. People selecting "N" for various things (for example, number of macrosetae). And "N" has some completely different meaning. We need to define our units which is not possible to enter now: 3 *setae*, 2 *carinae*, 5 *groves*. Solution?
If we implement project units, can we handle singular vs. plural values? 1 *seta* vs. 2 *setae*

**Comment by mjy** [comment]
No, we can not drop units, this would be completely horrible and let tons of non-standard data be entered, and would prevent us from, for example, handling your second issue (a different new one please), i.e. knowing what to pluralize automatically and what not to.  Right now the units are chosen from gem that lets us convert seemlessly across observations. 

As I understand it this is specifically a problem is for integer counts. This should be an interface issue that we can handle straightforwardly I think, see below.

We *can* and should make them less intrusive:
* [ ] Make a specific "sub" class of descriptor that is Count (perhaps UI only).  Units will not be shown (hidden), and the pertinent unit will be applied in the background.  The assumption is that this is an integer count.

Similarly, if there are issues with users not knowing what default units to choose then we can help them in the interface.

**Comment by proceps** [comment]
I asked to remove the list, because it is very long, and require a lot of scrolling to find what you need. I do not mind the list, if I have to make a selection only once, for a descriptor, and than it is autopopulated when codding the characters.
And exactly, I would like to make my selected unit (setae, for example), a default one, so again, once selected, I do not need to select it again.

**Comment by jlpereira** [comment]
> I asked to remove the list, because it is very long, and require a lot of scrolling to find what you need. I do not mind the list, if I have to make a selection only once, for a descriptor, and than it is autopopulated when codding the characters.
> And exactly, I would like to make my selected unit (setae, for example), a default one, so again, once selected, I do not need to select it again.

@proceps its the same approach I made here for the creations of new descriptors on "New descriptor" task? https://github.com/SpeciesFileGroup/taxonworks/issues/1169#issuecomment-630793637
If you mean this only for MRC, its now selecting the descriptor unit, so I dont think its gonna be necessary pick the unit again for each observation, should be set up automatically.

**Comment by proceps** [comment]
no, we need customized units. 1 seta, 2 setae, etc.

**Comment by mjy** [comment]
We do need customizable semantics, but not at this level.  The semantics at this level are "count of some thing", so the unit is "count" or "cardinatlity".  What the thing is needs to be defined at a different level, at present it's the proxy of the state.

**Comment by mjy** [comment]
Following up, your initial question is not representation, but presentation "seta" vs. "setae" and should be handled as such.

**Comment by proceps** [comment]
count is not on the list of units.

**Comment by mjy** [comment]
That *is* a problem.  I'll look into it/ handle it as a blocker.

**Comment by mjy** [comment]
@jlpereira I think there is just one UI bit here now.  It looks like we have a static list of units in MRC that we are drawing from?  This will have to be syncronized with the endpoint response 'http://127.0.0.1:3000/descriptors/units' to handle the new units I've added.

![Screen Shot 2020-06-07 at 3 53 36 PM](https://user-images.githubusercontent.com/22600/83980112-b584c100-a8d8-11ea-9589-ec635047a9c3.png)

**Comment by mjy** [comment]
@jlpereira @proceps I believe we can close this now?
