### ISSUE TITLE
View alteration request: "Fossil" to "Ichnotaxon"

### ISSUE THREAD

**Issue by rogerburks** [SpeciesFileGroup/taxonworks#1505]
**Current state:** In Taxon Name editing, in the relation to Nomenclatural Status, there are some suggestions under the `Common` tab. These include `Fossil`, although this is intended to refer to ichnotaxa (taxon names referring to the fossilized work of an organism), and not to names based on the fossilized body of an organism.

![image](https://user-images.githubusercontent.com/17787203/82472854-9df6ad00-9a7d-11ea-93c5-bd4a98f31634.png)

**The problem:** Text in the view may be confusing to new users (and maybe even to some veteran users). Users may click this for all fossil taxon names, regardless of whether they are ichnotaxa. This could promote misinformation in the database, and could produce downstream problems if future features of the database have differential results for ichnotaxa versus fossilized organisms.

**Suggestion:** Change `Fossil` to `Ichnotaxon`. Alternatively, it could be changed to a word that nomenclatural novices may not need to look up.

**Comment by proceps** [comment]
I will add ichnotaxon, as a subclass of fossil.

**Comment by proceps** [comment]
also add a collective group, which does not compete for priority

**Comment by proceps** [comment]
Ichnotaxon is added as a subclass of fossil, it is not a commonly used status, so you have to find it in the complete list of statuses. The changes should be visible after a new migration.
