### ISSUE TITLE
Married vs unmarried ladies

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1507]
In much of the Western world, married ladies adopt the husband's surname, either deleting their maiden name or adding to it.
This creates a situation where, when married ladies are authors, they can have two different names appearing in the literature. There is one who married and subsequently divorced, so during a short period her name changed.

I am currently treating those as two different authors, but this feels wrong and it spoils the statistics.
**What should I do in these cases?**

**Comment by mjy** [comment]
Use their/her/his current name as the last_name.  Use their/her/his previous name(s) as AlternateValues::AlternateSpelling values in Person -> Radial Annotator -> Alternate values.

**Comment by proceps** [comment]
I tend to treat those as two different persons. Otherwise the bibliography and TaxonName authorship is wrong. Fortunately, I know only one case like this in my group.

**Comment by mjy** [comment]
Please don't set or encourage a second standard, particularly one that encourages how things look over what they mean. This is the same person.

Taxon Name authorship is not a problem (verbatim). 

The priority is different for Sources (people trump verbatim there).  _This_ may have to change.
