### ISSUE TITLE
Improve the hyperlinks of the search interfaces.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1508]
When I make a search in the interface, for example Matrix Dashboard, or Source, I return the list of items. If I click on any item and follow the hyperlink, and then I want to return back to the filter, the filter is completely refreshed. I have to do search again. In some complicated searches, it is not easy. It is usually a good practice to embed all the search parameters into the hyperlink string. In this way the hyperlink is preserved, and if I use back button, I return to exactly the same view. In cases of paginated pages, it is even more important, because it could be not the first page, but something much further down. Look at Amazon model, as an example, all search parameters get automatically inserted into the link.

**Comment by jlpereira** [comment]
I agree, should be pretty easy add the params to the url, in fact we're displaying in on JSON Url. The only tricky part will be populate again the UI filter. We gonna need to make some calls to retrieve labels for the ids, tricky but not complicated. I will start with this the next week.

**Comment by mjy** [comment]
Possible alternative is to cache the params as recent searches (entering the inevitable "cache queries" stage of a large application) in a new table, etc.

**Comment by jlpereira** [comment]
This is already solved on the new filters interfaces.
