### ISSUE TITLE
lib/utitlities/geo.rb should not add significant digits

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1512]
When I convert lat long or elevation , then I should not add significant digits to the result.

For example:
* `123m` to meters is not `123.0`, it is `123`
* `W40` is not `40.0`

**Comment by jrflood** [comment]
Is the requirement to essentially return integer precision where the input is integer?

**Comment by mjy** [comment]
https://en.wikipedia.org/wiki/Significant_figures

**Comment by jrflood** [comment]
Has the pull request addressing this issue been merged?
