### ISSUE TITLE
Task - New source - Author and Editor smart selectors

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1515]
Quick and recent values are not updated after creating new records, unless I reload the page. At least using New and Clone buttons should refresh Recent.
I noticed the same problem with recent in other interfaces. Most importantly:
New Asserted distribution; 
New collection object (Repository, Collectors and other places)

**Comment by jlpereira** [comment]
@proceps pushed changes for new source and comprehensive form. It was already done for new asserted distribution. 

About the comprehensive task, I have some doubts if the OTU smart selector in related section of biological relationship is working right. Its making the call but its not retrieving any OTU. Not sure if its related with a wrong param, i have to check this. The others should be working fine, if you see one it doesn't, open a new issue and let me know
