### ISSUE TITLE
Task - OTU radial - asserted distribution

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1519]
When I open the Asserted distribution radial (from Browse nomenclature), which already have records (several countries linked to this OTU). It takes time to load the record. If there are many records (30-50), it may take up to minute to load them. I can add the same asserted distribution, which is already on the list, and it will be added as a citation to already existing asserted distribution. But only if I wait for the list loading (which again, may take long time). Sometimes, when I click blue pin button to  use the default source, this clears the list of existing geographic areas associated with the same OTU. The geographic areas are still there, to see them I have to reopen OTU radial. The problem is, I cannot add citations to existing geographic areas, which already exists, because those are not visible, and if Geographic area is not visible, the citation is not added to the Area automatically. It does not happen all the time, so I do not know how to replicate it.

So there are two issues here: 
1. sometimes geographic areas disappear when pin button is used.
2. Is it possible to change functionality so that I create a citation not waiting for the list to load (because sometimes it take long time). The functionality already implemented. I add new citation for OTU/Area combination and OTU/Area combination already exists with different citation. A new citation is added to OTU/Area record. But this only works if the list is loaded, if the list is not visible, I get an error message that the OTU/Area record already exists.

3. as a small addition, please add OTU radial to Edit Taxon Name task.

**Comment by proceps** [comment]
if an example needed:
https://sfg.taxonworks.org/tasks/nomenclature/browse?utf8=%E2%9C%93&taxon_name_id=&%5Btaxon_name_id%5D=340570
in 3i database, go to OTU radial click asserted distribution, there are several records there (created few days ago in the same way). Try to add default source (a source have to be pinned before).

**Comment by jlpereira** [comment]
1. Fixed
2. This is weird, but im pretty sure its a problem from the backend. It shouldn't take too much time to load it. The list is needed to handle this, because we need it to know if there is already an asserted distribution with that combination.
3. Fixed

1 and 3 pushed.

**Comment by proceps** [comment]
@jlpereira When I do migration I use the construction object.find_or_create_by. It is very handy, when I need to know if the object exists or I need to create it. I am not sure if you can do the same. But it would be really handy if I can start editing before the list is loaded. And as I said, if the list is short, less then 10 items, it does not take too much time. But if I have something like 40-50. It may take up to a minute to load the list. Could you think if we can do something about #1421, it would greatly speed up the editing.

**Comment by jlpereira** [comment]
In this case we can't use do it in that way, because this is handle with javascript and the only way we have to interact with the backend is using the endpoints.
A possibility that comes to my mind is make a call using filter parameters to know if exist an asserted distribution with the same otu and geographic area id exist. This will be used only when the list its not already loaded. But im not sure how really good could be this to solve this problem. The real question I think is why it takes a minute to load only 50 records

For #1421 I think we could use sessionStorage to save the lock and the source preference. Will be removed once you close the page, this will work for your workflow?
