### ISSUE TITLE
Task - Matrix hub - delete button needed

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1520]
Delete button needed for each matrix.
Expected behavior. 
1. Click delete button. A confirmation where you type "Delete" is required (the same functionality which we use when we Clone object)
2. Warning popup, "The matrix will be delete, but all characters, OTUs and scores will be preserved"
3. Delete all Rows and Columns from the matrix (The Characters and OTUs are not deleted).
4. Delete the matrix.

**Comment by mjy** [comment]
This won't work properly until the models are fixed.  Please do not attempt to implement.

**Comment by mjy** [comment]
Removing blockers since the matrix can simply be renamed and or ignored for now with no damage.  Adding to priority tracker.

**Comment by proceps** [comment]
Please add the warning with the text box on_delete
Click delete button. A confirmation where you type "Delete" is required (the same functionality which we use when we Clone object)
This is a complicated delete behavior. I want to make sure that the matrix is not deleted by mistake. I would like to see a two step warning like other places we have in critical places.

**Comment by mjy** [comment]
In the radial we likely need all/nothing two step deletes.
