### ISSUE TITLE
Task - New taxon name: remove "Valid by default" notation when any relationship is added?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1525]
@proceps this text is adding confusion.  It was added on request from MM IIRC.  How about we only display it when there is no relationship present?

**Comment by proceps** [comment]
We already have implemented when a status is set up, the "Valid" message disappears. TaxonName relationship is more complicated. But we can always check cached_valid_taxon_name_id == id to display this message.
