### ISSUE TITLE
Task - Comprehensive specimen - verbatim latitude and longitude

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1526]
12°27’24”N
format is not recognized, which is often used in publication

12°27'24"N - this one is recognized as valid.

**Comment by mjy** [comment]
I think you have a typo- this is literally the same?  Or you are looking at special characters for '"'?

**Comment by proceps** [comment]
different characters for single and double quotes. You can copy and paste in the comprehensive form and see the difference.

**Comment by mjy** [comment]
@jrflood please add this to the geo utilities spec

**Comment by proceps** [comment]
It looks like the library note_modules::parse-dms::index.js is read only, and the character for the seconds is not included as one of recognizable characters there.

**Comment by jrflood** [comment]
Has the pull request containing this been merged?

**Comment by mjy** [comment]
You can see the list of outstanding PRs on the Pull request tab.
