### ISSUE TITLE
Task - New/Edit Collecting event

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1530]
As a curator I want an interface nearly identical to New source interface but for Collecting Events.

* [x] Use the widget(s) in Comprehensive digitization as the starting point

# Collection objects pivot
* [x] Need a toggle to show recent table, basically full screen, of collection objects that are attrached to this CE

# Georeferences
* [ ] Isolate spatially a section for georeferences that is expanded somewhat
* [ ] Have a suggest mode that suggests georeferences based on identical or nearly matching `verbatim_locality` strings -> `/georeferences?verbatim_locality=string&exact=true` for fuzzy/not

# Labels
* [x] Include more space for label related fields.

# Auto generators
Like the Crossref and Bibtext buttons we will have some auto-generators
* [x] Georeferenced Image -> Drop image; backend will create collecting event with georeference and return collecting event. Originally #62

# Verbatim label highlight mapping
* [ ] If user types a verbatim label, and there are no other fields populated, then the form switches automatically into the highlight text breakdown mode (using hyclass).  We'll have to mock this

# Similar/Soft validation
* [x] Section as for sources, we'll mockup a new endpoint with the same verbs

# Navigation options
* [x] previous, next
* [x] next without georeference
* [ ] next without geographic area
* [ ] next without verbatim values

**Comment by tmcelrath** [comment]
Most of this issue looks done with latest release? Close @mjy or are you waiting to finish unchecked sections?

**Comment by mjy** [comment]
Thanks for the check.  I'd like to move 2-3 of the points to new independant issues before closing.

**Comment by proceps** [comment]
is it done?
