### ISSUE TITLE
Citations by source: true sorting by page numbers

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1536]
Would it be easy to fix the sorting by page numbers in the "Citations by source" module?
It goes like this:
![image](https://user-images.githubusercontent.com/46284943/83958404-a73a9480-a847-11ea-9860-22b92822efe4.png)

**Comment by mjy** [comment]
Great suggestion.  @jlpereira let's make all the columns sortable?  Seems reasonable to sort by Pages by default, Names might be useful too?

**Comment by adrik29** [comment]
Hello, Matt:
I found that this "Citations by source" module is extremely useful to check for incorrect entries in more than one way.
If you just open the article PDF e run along it, you may compare very quickly if there is any entry missing.
Also when we have more than one works by the same author in the same year, using CBS allows us to verify suffixes a, b, c quickly.
And it has another powerful feature which is to allow us to look not only at establishment of new taxa, but at other important nomenclatural acts (combinations, synonymies) and furthermore, new records.
Sorting by names would also be useful. Who knows how many creative/comfortable ways all your users find to be more productive and/or more accurate, and double-check their databases?

**Comment by jlpereira** [comment]
> Great suggestion. @jlpereira let's make all the columns sortable? Seems reasonable to sort by Pages by default, Names might be useful too?

Yah, it should be easy

**Comment by jlpereira** [comment]
Name its already sortable.

@adrik29 clicking on pages header should sort the list correctly. You will see this change on the next update.

**Comment by adrik29** [comment]
Thanks a lot, José Luis -- looking forward to using this module with the new improvements.

**Comment by proceps** [comment]
Is it resolved?

**Comment by adrik29** [comment]
@proceps -- it seems to working fine from here, even if I'm using the awful windows 10....
