### ISSUE TITLE
Comprehensive digitization - Want to be able to edit Determinations

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1539]
In the "Determinations" section of the form, I want to see the navigate radial to edit determinations that have been added, e.g. add a determiner, modify a year, etc ...

**Comment by mjy** [comment]
Funny, I thought we had an edit icon beside the rows- apparently not.  This might have been a constraint with how we save things off. @jlpereira is it possible?

**Comment by tmcelrath** [comment]
We used to have one and it was removed.

**Comment by jlpereira** [comment]
I have to check it, not remember if we had the edit option there or if we remove it for some reason. I remember there was a problem related with the position, not sure if this was already fixed
