### ISSUE TITLE
Comprehensive digitization - next/previous by identifier [was: Task Next/ Previous buttons do not navigate collection objects sequentially]

### ISSUE THREAD

**Issue by hah1009** [SpeciesFileGroup/taxonworks#1540]
**Describe the bug**
The majority of the time, within Comprehensive specimen digitization the Next/ Previous buttons do not navigate the collection objects sequentially. 

**To Reproduce**
1. Go to a collection object within Comprehensive specimen digitization
![Step 1](https://user-images.githubusercontent.com/63208032/84287940-8c4d7600-ab0e-11ea-96b7-ebd0c1cadab5.png)

2. Press the "Next" button to navigate to the following collection object
![Step 2](https://user-images.githubusercontent.com/63208032/84287970-94a5b100-ab0e-11ea-91dd-ce7fef1ede98.png)

3. Press the "Next" button again
![Step 3](https://user-images.githubusercontent.com/63208032/84287983-97080b00-ab0e-11ea-96b6-157ef1bf108d.png)

**Expected behavior**
When I click Next when I am on the page for UNHC 1045050, I expect to be brought directly to UNHC 1045051.

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox
- Production
- Browser: Chrome

**Comment by mjy** [comment]
@jlpereira we need two other buttons, in fact I thought we had these at one point - next by identifier (when present), previous by identifier.

**Comment by mjy** [comment]
Duplicated, last fix done in development.
