### ISSUE TITLE
Georeference Matcher

### ISSUE THREAD

**Issue by jnodel** [SpeciesFileGroup/taxonworks#1542]
**Describe the bug**

Locations georeferenced do not show up when searched in the georeference matcher. 

**To Reproduce**
1. When I  Go to "Geographic Area Lookup"
2. Then I search a location I've georeferenced, say Durham, NH, USA
3. And I tell it to search after inputting "Durham, NH"
4. The system tells me that there is no match. 
<img width="1150" alt="Screen Shot 2020-06-10 at 4 29 50 PM" src="https://user-images.githubusercontent.com/62450797/84315448-ac455f80-ab37-11ea-8c40-5b7903e10a1a.png">

<provide a screenshot>

**Expected behavior**
I had hoped to see a geographic area show up for Durham, or at least related data such as collecting events to the Durham input. I also tried this with other locations, and got the same result--no match. 

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production
- Browser: Chrome

**Comment by mjy** [comment]
Geographic areas only match until 2 level geopolitical subdivisions (e.g. county, parish, at a world level).
