### ISSUE TITLE
Smart selectors - search box

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1547]
Can we make Search box always visible in all tabs (Quick, Recent)?
This is particularly important for those cases where you make multiple items. For example Geographic area or People. 
Say in the source, I have two authors in the Quick/recent list, but two I need to search for. I have to bounce between Recent and Search back and force.
The same for geographic areas. In the Asserted distribution, I have an OTU with 10 geographic ares to records. 5 are on the Recent list, and 5 I have to search for, I have to bounce back and force between the sectors.
It would be much more productive if the Search box is always visible, so I can stay in the Recent section and quickly add something which is missing.

**Comment by mjy** [comment]
I'm open to evolving the smart selectors. I think you should propose a series of interfaces though before we try anything.

Alternatively- use the hotkeys to change tabs, it's trivial to change to the search tab where you are ready to type?
