### ISSUE TITLE
Consider removing uses of find_each

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1548]
Opening up this issue for discussion as well as documentation.

There are some uses of `find_each` on [app code](https://github.com/SpeciesFileGroup/taxonworks/search?q=find_each+path%3A%2Fapp%2F) and also on [rake tasks](https://github.com/SpeciesFileGroup/taxonworks/search?q=find_each+path%3A%2Flib%2F).

In the case of rake tasks I'm not much concerned about them but in the case of application code I am for things like this:
```
INFO -- :   Rendered tasks/nomenclature/browse/_summary.html.erb (Duration: 14.3ms | Allocations: 3359)
WARN -- : Scoped order is ignored, it's forced to be batch order.
INFO -- :   Rendered shared/data/all/show/_soft_validation_list.html.erb (Duration: 341.1ms | Allocations: 69305)
```

I'm unsure which `find_each` is causing the problem, but rather than fixing this I was wondering if we can get rid of them all? 

When using `find_each`, by default it retrieves objects in batches of 1,000 (and since all calls don't supply a param that is what we actually get). Given that using it causes `ORDER BY id` to be used, it makes less likely the use of any index other than the one for the PK, and also there is the additional cost of more round trips per additional batches.

Furthermore, given the warning above it might be breaking something as well, and also, it is worth noting that `each` gets a "snapshot" right there, while during the life cycle of `find_each` more records might appear (even new records created inside the block).

As a side note, I'm running an import for sandcastle on `create_citations` and this number is steadily increasing:
```
~/Projects/onedb2tw$ cat logs/production.log | grep "Scoped order" | wc -l
333292
```

Please leave me in comments what you think. Don't go and update the code unless you absolutely must and cannot wait for me to do it.

PS: Links to search result will change as soon as the code changes. Please make sure your commit messages refer this issue to keep track.

**Comment by proceps** [comment]
.find_each works much faster when you need to iterate large number of records(>1000). But you are right, if you update the record, it will be added to the list again. So, I use the construction only when I need to read the records only.
If the records get updated, I use something like "AR.pluck(:id).each" and than "AR.find(id)" construction to open each record in the array. It still work faster than AR.each construction. And again, you will find difference when you are working with thousands of records. If it is matter of few hundreds, AR.find is a reasonable approach.

**Comment by LocoDelAssembly** [comment]
@proceps done some experimentation, noticed a difference only on really very large large quantities (like Identifiers which we have like a million and a half).

However there are instances were I believe the actual amount of data retrieved would be a couple of batches and the forced `ORDER BY id` would hurt more than not having that restriction.

1. For instance in https://github.com/SpeciesFileGroup/taxonworks/blob/7912cb79581b6a233ec3357e36d44eac934c157a/app/views/asserted_distributions/_by_source_table.html.erb#L8 if we really expect several batches I believe we have a bigger problem.

2. Then on https://github.com/SpeciesFileGroup/taxonworks/blob/2e4d5ed53d82e4e3fdaf249e54424d1df387b167/app/models/serial.rb#L129 and https://github.com/SpeciesFileGroup/taxonworks/blob/2e4d5ed53d82e4e3fdaf249e54424d1df387b167/app/models/serial.rb#L143 hopefully won't return much records (but if indeed they do, the `.order(:name)` isn't working).

3. On https://github.com/SpeciesFileGroup/taxonworks/blob/6dc7e41b74329ec8ea6f1fd44efb4366fa7809e2/app/models/pinboard_item.rb#L72 `r` is `PinboardItem.where(...` and `PinboardItem.count` returns 152.

4. On https://github.com/SpeciesFileGroup/taxonworks/blob/fd1e03146ba186ccebdb0d71ee8f89309c595918/app/models/protonym/becomes.rb#L111
I'd say a name related to several thousand other taxa would be rare.

5. On https://github.com/SpeciesFileGroup/taxonworks/blob/2f52f9bb014d2370f40cf27f1a81977a3f727ad4/app/models/concerns/shared/is_data.rb#L36
It is limited by the number of supplied IDs, if more than a batch is expected, then the array is also several thousand IDs. Would be normal?

6. On https://github.com/SpeciesFileGroup/taxonworks/blob/e7227c89eb4d8e34a504ab36ee86987d1479a686/app/models/protonym.rb#L375 In this case if it is "Root" (or any other highly ranked name) it would of course result in several batches. However there is a change in ordering here, if you use descendants alone it is ordered by generations, but with `find_each` it is ` ORDER BY "taxon_names"."id"`. Doesn't seem to be a problem for this one though, and couldn't see this method being used anywhere. Does it work right? It might be using `year` instance attribute as local variable for doing computations.

7. On https://github.com/SpeciesFileGroup/taxonworks/blob/d1fe9ae2ad1b94c1ca9ae1a2c4e6837a8d62e94b/app/models/taxon_name_classification.rb#L257 I think it won't return more than one batch.

8. Same on https://github.com/SpeciesFileGroup/taxonworks/blob/9ddb63a2a99f684686fb16a8ecd80235125521ed/app/models/protonym/soft_validation_extensions.rb#L749 and https://github.com/SpeciesFileGroup/taxonworks/blob/9ddb63a2a99f684686fb16a8ecd80235125521ed/app/models/protonym/soft_validation_extensions.rb#L1056

9. Same on https://github.com/SpeciesFileGroup/taxonworks/blob/e7227c89eb4d8e34a504ab36ee86987d1479a686/app/models/taxon_name_relationship.rb#L441

10. On https://github.com/SpeciesFileGroup/taxonworks/blob/25c33ed3bd93b241c50fc6071ff60e5bc8a166c9/app/models/taxon_name.rb#L708 hopefully it shouldn't return several thousand names, but one line above is requesting a specific ordering, so `find_each` is messing up with it.

----

Except for (6.) do you agree that it is best to not use `find_each`?

**Comment by proceps** [comment]
The last one looks strange. If you believe that those are problematic, you can definitely remove them. When we are talking about less than 100 records, there is probably no significant difference in using both iterations.

**Comment by LocoDelAssembly** [comment]
```
2.7.1 :001 > sizes = Set[]; ObjectSpace.garbage_collect; Protonym.limit(2600).find_each { |obj| sizes << ObjectSpace.each_object(obj.class).to_a.size }; sizes
  Protonym Load (1.8ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 ORDER BY "taxon_names"."id" ASC LIMIT $2  [["type", "Protonym"], ["LIMIT", 1000]]
  Protonym Load (1.5ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 AND "taxon_names"."id" > $2 ORDER BY "taxon_names"."id" ASC LIMIT $3  [["type", "Protonym"], ["id", 1000], ["LIMIT", 1000]]
  Protonym Load (1.0ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 AND "taxon_names"."id" > $2 ORDER BY "taxon_names"."id" ASC LIMIT $3  [["type", "Protonym"], ["id", 2000], ["LIMIT", 600]]
 => #<Set: {1000, 2000, 2600}> 
```
```
2.7.1 :002 > sizes = Set[]; Protonym.limit(2600).find_each { |obj| ObjectSpace.garbage_collect; sizes << ObjectSpace.each_object(obj.class).to_a.size }; sizes
  Protonym Load (1.4ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 ORDER BY "taxon_names"."id" ASC LIMIT $2  [["type", "Protonym"], ["LIMIT", 1000]]
  Protonym Load (1.4ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 AND "taxon_names"."id" > $2 ORDER BY "taxon_names"."id" ASC LIMIT $3  [["type", "Protonym"], ["id", 1000], ["LIMIT", 1000]]
  Protonym Load (1.0ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 AND "taxon_names"."id" > $2 ORDER BY "taxon_names"."id" ASC LIMIT $3  [["type", "Protonym"], ["id", 2000], ["LIMIT", 600]]
 => #<Set: {1000, 2000, 1600}> 
```
(Garbage collection on each iteration)

```
2.7.1 :003 > sizes = Set[]; ObjectSpace.garbage_collect; Protonym.limit(2600).all.each { |obj| sizes << ObjectSpace.each_object(obj.class).to_a.size }; sizes
  Protonym Load (4.4ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 LIMIT $2  [["type", "Protonym"], ["LIMIT", 2600]]
 => #<Set: {2600}> 
2.7.1 :004 > sizes = Set[]; Protonym.limit(2600).all.each { |obj| ObjectSpace.garbage_collect; sizes << ObjectSpace.each_object(obj.class).to_a.size }; sizes
  Protonym Load (3.2ms)  SELECT "taxon_names".* FROM "taxon_names" WHERE "taxon_names"."type" = $1 LIMIT $2  [["type", "Protonym"], ["LIMIT", 2600]]
 => #<Set: {2600}> 
```
(Regular each with and without garbage collection on each iteration)

The query times are a bit unpredictable, sometimes `find_each` wins, other times `all.each` wins. Ignore them.

----
As you can see, the number of allocated objects for `find_each` at any given time is always at least the number of objects inside the batch instead of being allocated as they're handed over. Difference in favor of `find_each` should not be seen before hitting 1,001 records (but given the overhead involved I'd say this number is higher). For a human perceptible difference I'd expect the required number of records to be several thousands for the majority of the models (and all of the lines of code listed above).

I'll go ahead and remove all of them except for (6.) where I'll just leave a warning comment there. I'll leave rake tasks unmodified.
