### ISSUE TITLE
Nomenclature stats : suggestions

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1549]
I think that **_Nomenclature stats_**  section could be beautifully enhanced by letting us choose other filter options, for example:
(1) how many gen/spp have source citations;
(2) ditto have any asserted distributions;
(3) ditto have etymology;
(4) how many synonymies have source citations...

**Comment by mjy** [comment]
Thanks for the feedback @adrik29 .

1 - This can be answered by the Nomenclature filter I believe, but it could be added to stats too I think.
2 - Good suggestion
3 - Also doable. @jlpereira let's add this as `etymology=true|false` to the taxon name filter
4 - This can be answered by the Nomenclature filter too I think.

**Comment by proceps** [comment]
For me, this is better answered by nomenclature filter. Should we close this?

**Comment by adrik29** [comment]
@proceps -- it seems you guys are doing a super task force to deal with ALL the issues.
All of my initial questions seem to have been addressed by their future inclusion the nom. filt.
