### ISSUE TITLE
Collection object filter - Can't search by type status

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1551]
**Describe the bug**

Searching by type status does not return appropriate results. 

**To Reproduce**
1. When I go to "Collection OBject Filter"
2. Then I select a Nomenclatural Code and a kind of type (e.g. lectotype)
3. And I hit "Search"
4. See 2005 pages of results (500 records/page), at least 99% of which are not the type of type I selected. 

**Expected behavior**
I should be able to search by type status. If I select one kind of type, only that type of type is returned. If I select multiple, I want all those types returned. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Probably a bad filter param name..
