### ISSUE TITLE
Source -> Show -> Destroy is disabled 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1556]
When I am a non-administrator, then I can not destroy a Source that has related data.

**Comment by proceps** [comment]
In many cases, you probably want to see a merge functionality instead of destroy. Probably there should be restriction to destroy source which has records in other projects.

**Comment by mjy** [comment]
Points taken, but the exact use case that lead to this (and TaxonName) came from users who wanted destroy.  It is not going to be uncommon.

There are model restrictions that will check for use, most models inherit these and for Source we have lots of checks.

**Comment by mjy** [comment]
Duplicate of #1098
