### ISSUE TITLE
TaxonNameRelationship - SourceClassifiedAs for Genera/Family relationships

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1564]
Some curators want to add a Citation to the relationships that Genus A was Classified in Family B (to indicate is_origin).

Should we extend the SourceClassifiedAs Domain/Ranges to allow for this?

**Comment by proceps** [comment]
You wanted to say species classified in genus? I think it is already covered by Combinations.

**Comment by mjy** [comment]
Sorry- I'm dumb.  Fixed the example.  Genus in Family is the issue.

**Comment by proceps** [comment]
The model does not have any rank restriction for the subject. You can pup the species or genus or tribe as classified in the family. Object is restricted to Family and above. But since we did not have the editing interfaces, the functionality was never tested. I will test it, once implemented.

**Comment by mjy** [comment]
Aha!  Right.
