### ISSUE TITLE
New collection event won't create if some of previous collection event

### ISSUE THREAD

**Issue by jnodel** [SpeciesFileGroup/taxonworks#1572]
**Describe the bug**

I've been working on a number of specimens that have similar collection events. Some have that collection event with locality and date listed, but no collector, and some have the collector. So I'm trying to create two collection events, since I'm not certain that they were all collected by the same person. However, when I try to create a new event with the collector, I get the error message that a previous collection event verbatim already exists.

\
**To Reproduce**
1. When I  go to Comprehensive Specimen Collection Form
2. Then I fill in information for the collection event with the collector
3. And I tell it to save

<provide a screenshot>
<img width="1280" alt="Screen Shot 2020-06-19 at 12 52 13 PM" src="https://user-images.githubusercontent.com/62450797/85159697-d8de3300-b22b-11ea-8bd2-d0f8178b42a0.png">
<img width="1280" alt="Screen Shot 2020-06-19 at 12 52 42 PM" src="https://user-images.githubusercontent.com/62450797/85159706-da0f6000-b22b-11ea-915b-4d4029079666.png">

**Expected behavior**
I had hoped to create a new collecting event, so I would have ultimately two collecting events: once with a collector, and one without. Currently, I just have the collecting event that was created first--those without a collecting event--and so can't assign a collecting event or georeference to the other specimens
**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production
- Browser Chrome

**Comment by mjy** [comment]
@jnodel The message is indicated that the `Verbatim label` field is identical in both.  What do you have in those fields?

**Comment by jnodel** [comment]
In one field, I have:
Lee, N.H.
VI-17-1953

R.L.Blickle
Collr.

In the other field, I have:
Lee, N.H.
VI-17-1953

**Comment by mjy** [comment]
So this seems to be the real issue, the model is not seeing the difference correctly.  Elevating to a bug, thanks for catching this.

**Comment by jnodel** [comment]
Thank you!

**Comment by mjy** [comment]
Are you *sure* those are the values in your test?  I've written a spec and it seems to handle this case no problem.

**Comment by mjy** [comment]
I think I know the problem.  You have a 3rd CE with identical verbatim locality, i.e. the CE does really exists alread elsewhere.

**Comment by jnodel** [comment]
@mjy Yes, those are the values in my test. What does a 3rd CE mean, and how do I fix it so I can put in specimens with the two different collecting events?
