### ISSUE TITLE
Nexus output

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1574]
As reported by a user and has a priority for ongoing project. The Nexus export has some issues:

* [x] the "Character states" are not following the same order as in the main matrix row
* [x] measurement or states as number typed aren't shown in the list
<strike>* [ ] Species name is incomplete and overlapped</strike> Requirement of the Nexus format and to 100% ensure uniqueness.

**Comment by mjy** [comment]
@proceps what do you mean speices name is incomplete and overlapped?  The name must be formatted to be legal, this means shortening, removing spaces etc.

**Comment by proceps** [comment]
This was a request from Adilson. I do not know specific name requirements.

**Comment by mjy** [comment]
The continuous character type is already done.

Sample characters, which you still have many of, can not be exported to nexus.
