### ISSUE TITLE
Task - Observation Matrix Dashboard - add new OTU to the matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1577]
When I search for a particular TN and try to add this row to the matrix and go to the matrix row coder, I get to the row coder interface with a spinner which never stopes. This only happens when OTU was not previously added to the matrix as a row, If the OTU is already in the matrix, I can go to the row coder interface without any issues.

Observation. In 3i database I search for the name "Isaca bipars" to add this to the matrix. I got a single name in the list. I followed the normal procedure to get to the row coder in the GoLife matrix and got redirected to the row coder page with the following URL
https://sfg.taxonworks.org/tasks/observation_matrices/row_coder/index?observation_matrix_row_id=3692
That page has a spinner which never stops
I went back to dashboard and reload the page and clicked the button again to go to the row coder. The interface showed that the OTU was already added to the matrix, so the first step worked. But the row coder is redirecting to a different URL now
https://sfg.taxonworks.org/tasks/observation_matrices/row_coder/index?observation_matrix_row_id=173094

suggested problem. OTU was already in another matrix as a row, but not in this one. Once I added this OTU to the matrix, a new row was successfully created with id 173094, but the row coder was referenced to the old row id from different matrix (3692). And this caused an error in the row coder.

**Comment by mjy** [comment]
Might also be related to my known issues. @jlpereira could be confusing a matrix_row_item_id id with a matrix_row_id too.

**Comment by jlpereira** [comment]
> Might also be related to my known issues. @jlpereira could be confusing a matrix_row_item_id id with a matrix_row_id too.

Yes, im testing this and definitely something is wrong at the backend. The response after create the row sends a different object id, if I retrieve the list of rows now the id its not the same.

**Comment by jlpereira** [comment]
I think the problem is the response sends the observation matrix row item id(which is correct), but we need the row id.

**Comment by jlpereira** [comment]
I changed to reload the list after create a new row, try again @proceps
