### ISSUE TITLE
Asserted distribution JSON - remove duplicate GeOJSON, and flip `geo-json` to be false 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1581]
the ActiveRecord Model generates enormous JSON response for Asserted distribution. The reason, it includes all associated geographic area shapes.  In some tasks it could be important for the map representation of data. But in some other interfaces it just take time to load. For example OTU radial::Asserted distribution, which does not require the shapes. I have a species with 47 areas. It takes about 30 seconds to download a JSON file, which is about 5mb. And I have fast internet connection. Would it be possible to put a parameter restricting shape file load if not needed. It would greatly increase productivity.
As an example, see 
https://sfg.taxonworks.org/otus/46338/asserted_distributions.json
in 3i database. 
would it be possible to do something like:
https://sfg.taxonworks.org/otus/46338/asserted_distributions.json?shapes=false
?

**Comment by mjy** [comment]
Definitely.  We need some custom endpoints for the geojson.

**Comment by mjy** [comment]
Another point.  Remember that the annotation browser was never intended or designed to be *the* way to do things, but rather to do one thing quick, in passing.  I think we will need to re-think how it is being used ultimately, to get curators to more robust forms, not quick forms.  For example, the AD list should just include a couple records, not 47 (of course they don't need the geojson there).

**Comment by mjy** [comment]
This is partially a bug now- geo-json is being displayed 2x.  

There is a already a `geo_json` param, but it is supposed to be used to turn the geo-json on.  It's set in AD, but always on in GeographicArea.  We need to likely disable by default, and only include if requested.  This will likely require various requests to be updated.

**Comment by mjy** [comment]
`otus/46338/asserted_distributions.json?extend[]=geographic_area&embed[]=shape`
