### ISSUE TITLE
TaxonWorks updates

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1582]
When the website is updated, the web pages just stop responding. Autocomplete searched show "nothing found" message. There is no any clue that the web site get updated and you have to log in again (normally I can work on a single page for several days). When I reload the web page, I am bounced to login page. It is expected, but there is no way to return back to there previous page. The questions are: 
1. Is it possible to make autocomplete searches more informative. Instead of nothing found, show "Login is required"
2. is it possible to implement any kind of notification that the web site was update?
3. if the TW is updated, is it possible to preserve the login information? cookies?
4. If not is it possible to provide a login page in the same interface (a modal window). So, I stay in the same interface as before.

**Comment by mjy** [comment]
You shouldn't have to logout, just hard reload the page? (command-R)

**Comment by mjy** [comment]
Have other's experienced this?  I've never had to re-login.  In fact I want to clear sessions and force people to re-loging more often, rather than leaving things open (not secure).

**Comment by LocoDelAssembly** [comment]
2. Would be possible with some JS code running at intervals to send a request to get current revision (needs new endpoint). If diff detected perhaps inform the user with a modal dialog asking if you'd like to refresh or not.

3. Like @mjy every time I deploy production I go to sfg.taxonworks.org and never require to re-login (Firefox).

4. Probably harder to do than (2), given that you'll also need to set current project again?

**Comment by jlpereira** [comment]
@proceps autocomplete should display now an alert message at the button if the request fails.

**Comment by mjy** [comment]
Can we close this?
