### ISSUE TITLE
Task - Source Filter - Filter by Citation topic

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1589]
* [x] Add param `topic_ids[]=` (@mjy)
* [x] Add facet.  Idea same as Author with smart selector and multiple rows

**Comment by LocoDelAssembly** [comment]
I left issue open because there is one more thing to decide: What to do if a user selects topic(s) but then also specifies without citations? Currently it would result in zero sources returned.

Not sure whether there are other mutually exclusive facets or this is the first one.

**Comment by proceps** [comment]
No items, it is also a response. User can change the criteria and search again. I do not feel we have to predict all mutually  exclusive criteria.

**Comment by mjy** [comment]
We could in theory lock/unlock the form facet(s) based on the toggle of Citations or choice of topic?  But I agree with @proceps, the filter will simply return nothing for now and that should be fine.

Thanks btw to whoever added the facet!

**Comment by jlpereira** [comment]
Close?
