### ISSUE TITLE
Comprehensive Digitization - Containerized Objects not showing up together

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1590]
**Describe the bug**

Containerized specimens (e.g. INHS Insect Collection 835651) do not show up together in the comprehensive form under "Object details". Have they become delinked in the form?

**To Reproduce**
1. When I go to any specimen that has been containerized.
2. Then I navigate down to "Object Details"
3. Then I do not see the other object in the container. 

There are two specimens of INHS Insect Collection 835651 in their container, but they are not linked on this form.
![image](https://user-images.githubusercontent.com/11411328/86140925-0b532000-bab7-11ea-99c3-ded06b9aba52.png)

**Expected behavior**
Should appear together and be able to be easily edited in the form as previously. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by LocoDelAssembly** [comment]
@tmcelrath just deployed new TW version. This should be fixed.

**Comment by tmcelrath** [comment]
Yup, looks better!
