### ISSUE TITLE
Bug in Citations by source module

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1591]
The "Citations by source" module has a new problem.
It never loads. I get this "plz, wait a minute" msg eternally.
![image](https://user-images.githubusercontent.com/46284943/86229731-8a536180-bb66-11ea-8d3b-defd2e5ba11e.png)

**Comment by LocoDelAssembly** [comment]
@adrik29 just deployed the fix. Please let me know if you see any problems. Thanks

**Comment by adrik29** [comment]
@LocoDelAssembly = it seems to be working perfectly now! Fantastic! Cheers, adrik....
