### ISSUE TITLE
Autocomplete function

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1592]
The **autocomplete function** gives results with no alphabetical order. To make the search optimal it would be very useful that the results were shown ordered.

Example:
![image](https://user-images.githubusercontent.com/4991925/86259116-01521f80-bb92-11ea-99d9-76931a219774.png)

**Comment by mjy** [comment]
Autocompletes are intentially not alphabetic, but rather (very) predictive.  Given the input we predict, with multiple (in taxon name over 20) different queries, which name you are interested in.  For example `G alba` searches for alba names that start with the genus G.   Notice in your example we put the most probably name first, the exact match, taking spelling into account.
