### ISSUE TITLE
Browse OTU's yellow triangle for soft validation.

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1593]
In the  **Browse Nomenclature** task there is a yellow triangle that links each reference to the soft validation that works fine, but in the **Browse OTU's** task it does not do anything when clicking on it. Although when the cursor is hover the yellow triangle the legend "click to view validation " shows up.

![image](https://user-images.githubusercontent.com/4991925/86259711-bdabe580-bb92-11ea-970b-a281bbdce7ff.png)

**Comment by mjy** [comment]
Thanks for the report.

**Comment by jlpereira** [comment]
Done, this will be reflected in the next update

**Comment by mabecabrera** [comment]
Thank you!
