### ISSUE TITLE
New image task - images not uploaded in the order they are added

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1596]
**Describe the bug**

When I add a large series of images to "New Image Task" - they are not uploaded in the same "order" that they are dragged into in (e.g. filename order). This causes issues with the "Transcribe Depiction" task, as the catalog numbers are out of order. 

**To Reproduce**
1. When I go to the "New Image Task"
2. Then I drag and drop a large series of images.
3. And I fill out the rest of the form for "staged images".
4. And I hit "Apply Both"
5. Then I navigate to "Transcribe Depiction".
6. And I see that the catalog numbers are out of order on the images. 

**Expected behavior**
Images should upload in the same "order" in which they are dragged in - generally filename order. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by jlpereira** [comment]
I think its related at the parallel upload, some images can end uploaded before the others, and that can affect the order. You will see the change on the next update. Reopen if needed.

**Comment by tmcelrath** [comment]
@jlpereira Thought it was something like that. Thanks for the quick fix! I'll wait to add more images until the next update.
