### ISSUE TITLE
Task - New Source - Source of Crossref

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1597]
After creating new source from Crossref, I try to add authors as Roles. I can select the person from the search box, but the person is not displayed as selected after selection, apparently the author is still selected, but not displayed, because I can see it, but only after I saved the record.
I do not have this issue if I create source as new, not ussing Crossref.

**Comment by jlpereira** [comment]
@proceps can you provide me a DOI where are you have this issue?

**Comment by proceps** [comment]
I tried at least 5 source. The last one, I tried in local branch:
https://doi.org/10.11646/zootaxa.4286.4.13
Roles added but the source is not saved:
![image](https://user-images.githubusercontent.com/5597748/86392594-56a93200-bc61-11ea-8d9a-cd08253062c4.png)
After source save:
![image](https://user-images.githubusercontent.com/5597748/86392645-6b85c580-bc61-11ea-9be4-8d9c2a498d5a.png)
