### ISSUE TITLE
Collection Object Filter - can only download 500 records

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1598]
**Describe the bug**

If more than 500 records are returned, the CSV download only downloads 500 records. 

**To Reproduce**
1. When I go to the collection object filter.
2. Then I do a search that returns over 500 records. (Can set to display 500 or 1000, same result).
3. And I hit "Download CSV"
4. Then the resultant CSV only has 500 records.

**Expected behavior**
Should download all returned records, not just 500. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by tmcelrath** [comment]
I understand if this is not a high priority since there will be an update to this task with the DWC import/export functionality.

**Comment by mjy** [comment]
@jlpereira I think we need a custom endpoint.

@tmcelrath is this even useful now that we have DwC export?

**Comment by tmcelrath** [comment]
Yeah it is. Sometimes people just want a CSV.

**Comment by tmcelrath** [comment]
CSV can now be downloaded up to 2500 records (if display set to 2500), but only 2500 records can be displayed at a time, so CSV is limited to 2500 currently.

**Comment by tmcelrath** [comment]
Honestly not an issue now with DWC/Data attribute export. Close I think.

**Comment by mjy** [comment]
Still requested, but keeping closed for #1598
