### ISSUE TITLE
Call for Discussion - Public facing exposure for TaxonWorks data (taxon pages, etc.)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#160]
_This comment will be edited_

TaxonWorks is nearing a stage where questions are beginning to arise as to if and how data within a workbench might be displayed to public users.   This issues is a stub for dialog until the public facing project project has its own repository or issue organization.  Please comment!

# Background 
TaxonWorks is a workbench for individuals or small groups of collaborators that sits behind a login window (see the [Vision](http://taxonworks.org), and the early [FAQ](https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/FAQ.md)).  Its developers have always understood that exposing data from a workbench to the broader public has been a highly desirable goal for those using tools like TaxonWorks (but, importantly, not a universal goal).  Internally TaxonWorks will have numerous reports that people currently understand as taxon pages, i.e. summaries of everything we know about a taxon in TW in a unified view.  For many reasons, but largely as a means of building up a code base that is maintainable, TaxonWorks the workbench is just that, a workbench, it's not intended to also be a website serving tool.  The concept has been "work and revise in one place", present in another.  How then do the data get exposed beyond the workbench?

# Approach
* The internal views on the data will be built off of the internal API, thus doing the work of creating the data serving responses necessary for producing individual taxon pages.  Most of the core models already exist in design or code for how to do this on the back end.  

* TaxonWorks will expose internal endpoints via a JSON serving API.  This means that as soon as endpoints become available researchers, web developers, bioinformaticians and others can access data in a simple format. 

* Where possible internal views will be atomized as Javascript libraries that can _also_ be used internally and within external wrappers.

This API open up TaxonWorks to a world of new development:

## Examples

*  This project https://github.com/SpeciesFileGroup/matrix_row_code can be run in your browser with a simple local configuration, but persist data in a TaxonWorks instance.

* Wrappers in native scripting languages should emerge, greatly increasing the utility of data in TaxonWorks projects, for example  [Python Packages](https://python-packaging.readthedocs.io/en/latest/#), [Ruby Gems](https://rubygems.org/), [R packages](https://cran.r-project.org/web/packages/)  

* Small Javascript based widgets will be developed.   For example you might include a distribution map on your own web pages with a single line of configured code, or use an autocomplete widget to query nomenclature in TaxonWorks within Symbiota.  These widgets should live in their own repositories.

* Larger efforts can be built creating their own homepages, customizing or branding them as they want, but populating them with TaxonWorks data.

* Java libraries for integrating the matrix back end to Mesquite, or NexML using tools could be developed.

# Integrative websites 

But what about more integrative presences, like the Species File Group's (SFG) [Orthoptera Species Pages](http://orthoptera.speciesfile.org/HomePage/Orthoptera/HomePage.aspx)?  That is, pages that expose the full richness of the data, not just pieces of it here and there.  These sites are very rich, and highly complex, and take a lot of time to code and maintain.  They are also replicated in many different ways (EOL, Scratchpads, many many custom taxon pages, etc).   _How best to wrap this complexity, and maintain that wrapper for the longer term, is a question that should really be addressed by the broader community, or at least we should seek input from the bigger community._  

We (SFG, and others) would be very excited if integrative sites emerged as a consequence of an excellent API, i.e. people just ran with their own solutions.

## Hosting with the Species File Group

The SFG recognizes that just hoping for someone else to do it is not very safe bet (but properly building the API will greatly increase our odds).  The SFG is committed to working on an integrative solution for this problem as separate product, likely under the moniker "Species Files".   That is, the SFG will minimally provide lightweight wrappers around taxon pages and serve those as individual sites.  This will be a new, open source product, that will wrap the TaxonWorks API. We will almost certainly require that the data exposed/hosted in this manner be CC 0.  Ideally "Species Files" in this new sense would be citable, DOI having, publications.  As currently envisioned the "Species Files" service from the SFG will be made available to all our historically served groups (SFs, mx, 3i, early collaborators etc.) for a reasonable period of time, likely 5 years. After that time we will re-assess what's going on with respect to others producing their own, or related integrative sites, and work with the broader community to see that "Species Files" evolve into the resource that is managed on a broader global stage (EOL 9.X or some such).

# Your feedback

We need your feedback.  

* What should public sites minimally include?  
* How can we improve on past versions of our integrative homepages?
* What are the technical considerations for building out this vision?

Once this thread grows to a reasonable size we'll refine the issues raised here into another repository or individual issues.

**Comment by dimus** [comment]
I guess there are two different situations:

Cookie cutter situation where public exposure as a web-site is uniform and probably all what is required for ???~50%??? of users.

Custom presentation that uses bits and pieces of cookie-cutter + something that varies a lot.

I wonder if it is possible to avoid making 2 APIs by adding a flag to all endpoints that allows it to become public. I quite understand it is a naive suggestion, as I do know the details of API

For Cookie cutter one it would be a way to set this flag for a bunch of endpoints at the same time, and also have a prepared GUI that can talk to these things (hopefully made as a bunch of modules, so people can mix and match them if they want to)

**Comment by mjy** [comment]
Re the API- we are doing that, essentially aliasing internal endpoints with
an external route.

**Comment by redewalt** [comment]
I am author of an original Species File (http://plecoptera.speciesfile.org) and like the range of public information provided. This is one model to mimic, but I realize that this is complicated programming, but since the data addition/editing is now divorced from the front end, perhaps not so difficult as it was for SFiles. Minimally, I would like: hierarchy, name, author, year, original combination, subsequent combinations, all synonyms. I also like to have a list of references for each taxon and a distribution map. Search functions for taxon names, references, distributions.  Image are important to audience.

**Comment by mikemaehr** [comment]
I am one of those that is not that concerned with having a public facing interface or investing much into how data is exposed as long as it is exposed and/or made available. I am more concerned with having the data entry/editing organized in an efficient manner that allows for rapid gleaning of available data, its validity, and means of accessing additional information. Toward this end I think a more cookie cutter approach suggested by @dimus that includes items suggested by @redewalt with a couple of additions work. I think type (specimen, species, genus) information is critical for any taxon and should be easily accessible behind the login window as well as easily found on the "taxon page" as well as perhaps an "additional resources" link? such as might lead to DNA data, conservation status, eco relationships etc.

**Comment by mjy** [comment]
As we start to flesh out the "Page" project this issue should likely migrate to a new repo.  

As we're thinking about APIs to wrap for section components we should read this: http://www.biocase.org/whats_biocase/index.shtml

**Comment by mjy** [comment]
Closing as complete, see https://github.com/SpeciesFileGroup/taxonpages/ for more.
