### ISSUE TITLE
Smart selector - Person - new person

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1600]
![image](https://user-images.githubusercontent.com/5597748/86400548-6b3ff700-bc6e-11ea-8493-1cf50c0178d7.png)

Please reduce space. It looks like the labels are attached to the wrong field. (This is from Comprehensive task)

**Comment by jlpereira** [comment]
This is an unusual behavior and not the correct space. Where is the context of this to look if is inheriting a class

**Comment by jlpereira** [comment]
Sorry, I didnt saw the comment at the button. looking
