### ISSUE TITLE
How to quickly locate issues

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1603]
Is there a quick way that I can filter registers to easily locate validation errors such as the one depicted below?
![image](https://user-images.githubusercontent.com/46284943/86483281-1a8dd400-bd2a-11ea-9e8c-72cba82b52f8.png)

**Comment by proceps** [comment]
We have this issue open: #72. At the moment, validation works only on the record level.

**Comment by mjy** [comment]
Thanks @proceps, and thanks for the bump.  @adrik29 you can vote with an emoticon for existing issues to nudge them to a priority.

**Comment by adrik29** [comment]
Sure thing - I'll vote for it -- it will be fantastic as a productivity tool!
