### ISSUE TITLE
New source - Serial - Geminated Volume doesn't appear

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1606]
I know we are gradually adapting TW to all sorts of unorthodox stuff that happens in taxonomy.

Sometimes the periodicals cram two volumes in one. And they are indicated by linking both numbers with a hyphen or an n-dash.
I have tried both as well as slash, but they either cannot be entered or enter but do not appear in the title of the source.
Could we fix this?
In the example below, this journal has a geminated volume 161-162 -- connected by a hyphen.
I cannot reproduce this. I keep getting the source WITHOUT THE VOLUME NUMBER:
Villarreal-Manzanilla, O. & DoNascimiento (2005) Una nueva especie del género Paravima Caporiacco, 1951 (Opiliones, Laniatores, Agoristenidae) del tramo oriental de la Cordillera de La Costa, Estado Miranda, Venezuela. Memoria de la Fundación La Salle de Ciencias Naturales, 101–111. [2004]

![image](https://user-images.githubusercontent.com/46284943/86523596-1e624900-be45-11ea-83f0-b0f1b2529c87.png)
![image](https://user-images.githubusercontent.com/46284943/86523614-494c9d00-be45-11ea-96cf-e03509166270.png)

**Comment by jlpereira** [comment]
Fixed, change will be reflected on the next update

**Comment by adrik29** [comment]
Love you, guys....
