### ISSUE TITLE
Task - Edit TaxonName - hyperlink to comprehensive

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1608]
The functionality lost. When I click on comprehensive hyperlink (in Edit TaxonName), I expect to see the TaxonName as an OTU in the Smart selector for determination in Quick section. It is not there any more.

**Comment by jlpereira** [comment]
This functionality didn't exist before. The current behavior is set the taxon name on the type material section. If you want to set the OTU of the current taxon name in taxon determinations we should consider a couple of things. You want to create a OTU automatically if didnt exist? and in the case of the taxon name have more of one OTU, you want a different way to select it, like a modal on loading?
