### ISSUE TITLE
Family assignment of genera in TW - how to annotate this?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1610]
Whenever a species is ascribed to a genus this is easy to note in TW by using combinations.
How do I accomplish the same but with genera assigned to families?
I think it is very important to know which source ascribed genus x to family y.

**Comment by proceps** [comment]
in the Edit TaxonName task, there is now a special section for this, Classification. It is in lower part of form below original combination. The status "Classified as" designed specifically for the purpose you ask. Put a family-group name and do not forgot to add a citation using radial annotator.

**Comment by mjy** [comment]
@proceps Can you please add a second to the Nomenclature manual on taxonworks_doc if it doesn't exist to address this?  This is being asked in 3-4 places.

**Comment by adrik29** [comment]
@proceps ; @mjy = Thanks for this info -- I'm gonna make good use of that.

**Comment by proceps** [comment]
@mjy This was already covered in documentation. I move this and few other questions to the FAQ section.

**Comment by adrik29** [comment]
@proceps = there are some strange validation messages (are they in error or did I miss something?):

I did as oriented and everything seems right:
![image](https://user-images.githubusercontent.com/46284943/86619167-73f73c80-bf90-11ea-9420-90b3457ce839.png)

But I got the messages:
![image](https://user-images.githubusercontent.com/46284943/86619225-9426fb80-bf90-11ea-9b5a-4698f0ef0fc3.png)

**Comment by proceps** [comment]
@adrik29 This is a new function. I saw the error message. It is fixed, but not in the production yet. The priority for this TN relationship was reverted. And actually it is not required.

**Comment by adrik29** [comment]
@proceps  -- so I may safely ignore those messages, and one day they'll be gone?

**Comment by proceps** [comment]
@adrik29 Yes in this example those could just be ignored. I am still tuning the soft validation warning. Please do not hesitate to report if you see something odd.

**Comment by adrik29** [comment]
@proceps -- I think that the soft validation warnings are precious and a beautiful tool for productivity and accuracy. I'll try to keep an eye out for strange orange messages.
