### ISSUE TITLE
soundfiles and taxonworks

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#1611]
Hello, some time ago I asked about incorporation of soundfiles into taxonworks, as we know it from OrthopteraSpeciesFile.
Unfortunately I do not find my old issues, so I open a new one here.
Is there any short summary about the status of soundfile integration in particular, and the taxonworks - OSF migration in general?
Greetings from Uruguay, Klaus

**Comment by mjy** [comment]
Hi @klausriede.  Nice to hear from you.  Here is the old issue: https://github.com/SpeciesFileGroup/taxonworks/issues/244.  Nothing new to report for it, it simply hasn't become a priority yet. As the data issues (see below) are largely resolved it will likely creep back to the forefront.

There has been major improvements to the OSF/SF import process.  I'd suggest you contact @LocoDelAssembly or Maria Marta directly with specific questions regaring the current status.
