### ISSUE TITLE
Cannot copy text to the clipboard box

### ISSUE THREAD

**Issue by hah1009** [SpeciesFileGroup/taxonworks#1612]
**Describe the bug**
Within Comprehensive specimen digitization, I am no longer able to copy text to the clipboard using Alt + C + Number. When I try to do this, I am brought to the "Browse collection objects" form for the collection object I was on. 

**To Reproduce**
1. Within Comprehensive specimen digitization, highlight the desired text to copy onto the clipboard box.
2. Use Alt + C + Number.
3. I am brought to the Browse collection objects form and the text is not copied to the clipboard box.

**Expected behavior**
When I highlight text and use Alt + C + Number, I expect this text will be copied onto the clipboard.

**Screenshots**
![Step 1](https://user-images.githubusercontent.com/63208032/86813983-d1ea5980-c04e-11ea-8fb9-c71e8f33d7e2.jpg)
![Step 2](https://user-images.githubusercontent.com/63208032/86813995-d57de080-c04e-11ea-87e7-e7285162ff40.jpg)

**Environment (please identify where you experience this bug:**
*** One of ***
- Chrome

**Comment by jlpereira** [comment]
@hah1009 thanks for report this, we had a shortcut conflict using the same one for other task.
Now is fixed, you will see the change on the next update.

**Comment by hah1009** [comment]
Great, thank you!
