### ISSUE TITLE
 Browse OTUs Task - Type Specimen History

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1614]
The history of the status of a type specimen has to be clearly displayed in Browse OTUs. For example, if a syntype was chosen to be a lectotype it has to be displayed as the same specimen and not as different type specimens.

For example, in the OTU Bufonacris claraziana (Saussure, 1884) the syntype specimen is the same specimen that later is chosen as the lectotype of the species. Not a diferent one.

![image](https://user-images.githubusercontent.com/63611746/86937709-f65d3900-c115-11ea-836a-ff973427511a.png)

**Comment by mjy** [comment]
@jlpereira I think we'll just have to nest by collection_oject_id here
