### ISSUE TITLE
How to merge and/or delete author names

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1616]
When I first uploaded by database to TW, several copies of the same person's name entered the system as **placeholders** for the real one.
Gradually we are associating the sources with the unique name of each author and we are editing each taxon name so it is linked to the sources and also to the source authors (by using "clone from source" tool).

**Now my question:**
Whenever I associate a taxon with the REAL author, does the placeholder automatically **disappear**? Or does it keep appearing as a "red name" in the auto-complete list? 
If so, how can I get rid of all those junk unused names which are not linked to anything but keep haunting my otherwise useful auto-complete list?
![image](https://user-images.githubusercontent.com/46284943/87104820-6ca18e80-c22f-11ea-9444-8c3ce91d1d7e.png)

**Comment by mjy** [comment]
You want the "Uniquify people" task, it's does the merge seemlessly, though you have to grind 1x1.
