### ISSUE TITLE
Parens combined for different taxon ranks

### ISSUE THREAD

**Issue by mikemaehr** [SpeciesFileGroup/taxonworks#162]
It was observed that in the Orthoptera SF data found in the sandbox, that two sets of parens are being combined. Specifically, a subgenus followed by a species group - two taxa that should each have their own sets of parens as follows Aus (Bus) (cus) where Bus is a subgenus and cus a species group, are combined as follows: Aus (Bus cus). There are multiple examples of this found in the genus Ceuthophilus in Orthoptera. Specific case:

Ceuthophilus (Ceuthophilus brevipes) Hubbell, 1936 in TW
Ceuthophilus (Ceuthophilus) (brevipes) Scudder, 1862 in SF

(note also the different author as referred to in other issue)

**Comment by mjy** [comment]
@proceps try to reference the issue in your commit message (just add the text #162).  You can even close the issue via the issue message if you want to (`closes #162`) IIRC.
