### ISSUE TITLE
Seeing OTUs in Recent that do not exist in my project

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1626]
**Describe the bug**

When I looking at recent OTUs in Comprehensive, I am seeing newly added OTUs from other projects. 

**To Reproduce**
1. When I am in Ciomprehensive, doing digitization.
2. Then I look at my "Recent" OTUs.
3. See OTUs that are not in my project
4. Verified by going to Browse Nomenclature and Browse OTUs.

OTU/Taxon Name in Comprehensive:
![image](https://user-images.githubusercontent.com/11411328/88108371-55876880-cb6e-11ea-993f-f5ed0c7fcc5d.png)

Browse Nomenclature:
![image](https://user-images.githubusercontent.com/11411328/88108431-6c2dbf80-cb6e-11ea-92f3-2ca0515c99af.png)

**Expected behavior**
I shouldn't see OTUs from other projects. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
@proceps @LocoDelAssembly this is fairly critical.  It could be that this is a remnant of the cross-project OTU contamination that occured a while back, but we need to check the recent methods to ensure they are being scoped properly.

**Comment by LocoDelAssembly** [comment]
To confirm, is this bit of code that generates that list?
```ruby
  # @params target [String] required, one of nil, `AssertedDistribution`, `Content`, `BiologicalAssociation`, 'TaxonDetermination'
  # @return [Hash] otus optimized for user selection
  def self.select_optimized(user_id, project_id, target = nil)
    r = used_recently(user_id, project_id, target)
    h = {
      quick: [],
      pinboard: Otu.pinned_by(user_id).where(project_id: project_id).to_a,
      recent: []
    }

    if target && !r.empty?
      h[:recent] = (Otu.where('"otus"."id" IN (?)', r.first(10) ).to_a +
          Otu.where(project_id: project_id, created_by_id: user_id, created_at: 3.hours.ago..Time.now)
              .order('updated_at DESC')
              .limit(3).to_a
              ).uniq.sort{|a,b| a.otu_name <=> b.otu_name}
      h[:quick] = (Otu.pinned_by(user_id).pinboard_inserted.where(project_id: project_id).to_a +
          Otu.where('"otus"."id" IN (?)', r.first(4) ).to_a).uniq.sort{|a,b| a.otu_name <=> b.otu_name}
    else
      h[:recent] = Otu.where(project_id: project_id).order('updated_at DESC').limit(10).to_a.sort{|a,b| a.otu_name <=> b.otu_name}
      h[:quick] = GeographicArea.pinned_by(user_id).pinboard_inserted.where(pinboard_items: {project_id: project_id}).to_a.sort{|a,b| a.otu_name <=> b.otu_name}
    end

    h
  end
```

Tried to replicate in Sandcastle but couldn't replicate so far.

**Comment by tmcelrath** [comment]
If it helps, everytime I loaded the page, new names appeared. Was someone loading a large list of names to another project today?

**Comment by tmcelrath** [comment]
Still happening.

**Comment by LocoDelAssembly** [comment]
Dipemura Dworakowska, 2011 both the Protonym and the OTU  last updates are from Nov 2018 and belong to "3i World Auchenorrhyncha Database" project.

**Comment by LocoDelAssembly** [comment]
@tmcelrath do you still see this problem?

**Comment by tmcelrath** [comment]
@LocoDelAssembly don't see this problem anymore. Closing.
