### ISSUE TITLE
Task - New taxon name - moving names in synonmy section disable 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1627]
When I select all, then when I click 'Save', then no events are fired.

![Screen Shot 2020-07-22 at 11 28 38 AM](https://user-images.githubusercontent.com/22600/88202461-87e8a280-cc0e-11ea-9afd-6877c2622fbc.png)
...
![Screen Shot 2020-07-22 at 11 28 35 AM](https://user-images.githubusercontent.com/22600/88202455-86b77580-cc0e-11ea-8c68-0e94ccef8723.png)

**Comment by proceps** [comment]
I saw this but only when large number of taxa selected. I thought there is some limit set.
