### ISSUE TITLE
Strange validation messages

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1636]
I keep receiving strange validation messages.
There is nothing wrong with the entry...

![image](https://user-images.githubusercontent.com/46284943/89071230-a48e8400-d34c-11ea-9afc-9b8efa4fdb4d.png)

**Comment by proceps** [comment]
I saw this one week ago. Should be already fixed, please wait for the next TW production update.

**Comment by adrik29** [comment]
Ah, OK. I'll keep an eye out for strange validation messages.
