### ISSUE TITLE
Manage synonymy

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1637]
The Manage synonymy module is potentially very useful.
However, it is now working... I press "save" but nothing ever happens.

![image](https://user-images.githubusercontent.com/46284943/89177141-2d7e0900-d561-11ea-8bdf-b5f280e84f48.png)

**Comment by jlpereira** [comment]
Duplicate issue #1627 

Already fixed, will be reflected on the next update
