### ISSUE TITLE
Requested new feature - New Biological Associations task

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1638]
It would be extremely helpful in curating papers that contain long lists of host records, to have a task similar to the New Asserted Distributions task.  Here you can lock in a source (paper) and an OTU, and then punch in the geographic areas.  I am thinking that if one could lock in the source and the OTU, and then pick the biological association (compared with, primary host, etc.), one could then enter the OTU's for the associations only, without having to repeat the other information.

**Comment by mjy** [comment]
Thanks very much @JimWoolley for your first ever Github issue!  Glad to have it here.

@jlpereira I think we're going to try and build a stick and ball style "composer" on this task.  E.g. something like this (picked at random as the first I could find, not advocating for this library) - https://visjs.github.io/vis-network/examples/network/data/datasets.html.

Off the top of my head we're going to need to polish up this endpoint:

* [ ] POST `/biological_associations_graph`.  This allows us to add Citations to groups of biological associations, not just individual ones.

As a user I want to be able to:

* [ ] Add more than one biological relationship to the same OTU, so we can compose statements like  A eating B on C.  This is two BiologicalAssociations, and on BiologicalAssociationGraph to link the two
* [ ] Citation can be added to individual associations
* [ ] Multiple associations (including "select all") in the window can be selected and cited collectively (add citation to BiologicalAssociationGraph)

**Comment by proceps** [comment]
This could be extremely powerful tool, especially in combination with another task #1156

**Comment by JimWoolley** [comment]
Thanks, Matt, for putting a bit more flesh on the bones of this idea.

I am happy to help with road-testing, looking at a prototype etc.

Agreed, in combination with a filter/view biological associations task this could be very powerful tool indeed.


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

979-845-9349
979-845-3699 (lab)
