### ISSUE TITLE
After new combination, clicking on name goes to the combination, not the valid name (protonym)

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1639]
I'm not sure this is actually a bug, but it is potentially confusing, especially for those learning the TW interface.

I am working in Production version, using Safari 13.1.1 as the browser

When I create a New Combination using the N.C. task, and move the species to the new parent,

then when I click on the taxon name (see screen shot one)

It takes me to the combination, not the valid name (protonym), (see screen shot two). 

I would expect to land on the valid name.

![Screen Shot 2020-08-04 at 8 39 17 AM](https://user-images.githubusercontent.com/30122486/89301455-51a81b80-d62f-11ea-9247-6bb81c5ee1ce.png)
![Screen Shot 2020-08-04 at 8 40 59 AM](https://user-images.githubusercontent.com/30122486/89301523-5d93dd80-d62f-11ea-8763-2e6df477c735.png)

**Comment by mjy** [comment]
@proceps if you agree will get @jlpereira to link to "valid" taxon for the combination *from that point only*.

**Comment by proceps** [comment]
with @jlpereira we already implemented a check box on the Browse TN page which always redirect search to the valid name. I agree that this is useful.
