### ISSUE TITLE
Save button in Manage Synonymies does not seem to work

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1640]
I created a new generic synonym by making Trigonura Sichel a subjective Junior synonym of Phasgonophora, and provided the citation and page number.

Numerous species are listed in Manage Synonymy screen, with current parent Trigonura and new parent Phasgonophora.  

If I select All, and hit green save button below the list, nothing happens.

I tried saving at bottom of screen, followed by saving at top of screen.  Still does not work.

Turned off autosave, still does not work.

Check of first name in list, chrysobathra, indicates that transfer to Phasgonophora has not been made.

I was working in Production version, browser is Safari 13.1.1.  Project is UCD 2019-09-30.

**Comment by proceps** [comment]
This bug was recently reported, and I believe it is fixed. The changes should be in effect once production is updated. Probably later today. See #1637.

**Comment by JimWoolley** [comment]
Many thanks, Dmitry.  I looked for the bug issue first but must have missed it.


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

979-845-9349
979-845-3699 (lab)

**Comment by proceps** [comment]
This is probably because the issue is already closed.

**Comment by JimWoolley** [comment]
Sorry. but this issue (#1640/1637) does not appear to have been resolved.

Manage synonymy screen was there and it did work for a synonym I created earlier (Trigonura under Phasgonophora).

However, when I made a new synonym this morning (Bactrochalcis under Phasgonophora), and saved it, the Manage Synonymy screen does not appear in the Production version.

It does appear in the Sandbox.


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

979-845-9349
979-845-3699 (lab)

**Comment by mjy** [comment]
@JimWoolley The synonymy section isn't showing becasue there are no children under _Bactrochalcis_ to manage.

**Comment by JimWoolley** [comment]
Ah, oops, should have picked up on that.  Thanks!

I’ll keep working with this, and see if I can come up with more dumb questions.


Jim Woolley
Professor Emeritus
Department of Entomology
Heep Center MS 2475
Texas A&M University
College Station, TX 77843-2475

979-845-9349
979-845-3699 (lab)
