### ISSUE TITLE
Objects details "locked" selections disappear randomly

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1641]
**Describe the bug**

Occasionally, when using the "lock" feature in comprehensive, the selected options in Comprehensive will just disappear and will need to be reselected.

**To Reproduce**
1. When I am using comprehensive to create lots of records in a row.
2. Then I select an option in "Object Details" such as "Adult" or another biocuration class.
3. And I select the lock button to enable.
4. Eventually, the locked input will disappear. Not predictable.

**Expected behavior**
Locked Object details should not randomly disappear. 

**Environment (please identify where you experience this bug:**
- Chrome
- Production

**Comment by tmcelrath** [comment]
Suspicion: may occur when someone else creates a Collection Object that does not share these Object Details, resetting the lock feature, but not sure.

**Comment by jlpereira** [comment]
I can't replicate it, if get this error again please add a screenshot.  The lock button should be always present on the first row.

**Comment by tmcelrath** [comment]
Will do.

**Comment by mjy** [comment]
Closing as out of date
