### ISSUE TITLE
Model - FieldOccurrence

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1643]
The sample recording the presence or absence of a taxon that was taken during a spatio-temporal slice.

Overlaps strongly with AssertedDistribution, however those are derived from published accounts (publication based) whereas these require a collecting event (event based).  This is blurry, but follows our use of GeographicArea.

# Attributes
* is_absent
* collecting_event_id
* otu_id

# Potential issues
* Dealing with chronological changes of the OTU.  I.e. issues like TaxonDetermination.  Could possibly use IsOrigin relationship to link one record to the next, thus letting us infer the OTU changes if this is necessary.

**Comment by proceps** [comment]
Two check-boxes on collection object (field_occurrence, absent)?

**Comment by proceps** [comment]
Alternatively, extend Asserted distribution to include a collecting_event as an alternative to GeographicArea.

**Comment by mjy** [comment]
FieldOccurrence:

* [  Order the left panels from top to botttom: FO, TD, Biocuration, Citation, CatalogNumber
* [ ] Maybe we can introduce a style component to indicate "required" here? I.e. FO, TD. CE get glowing borders or header background color that goes away when populated?
* [ ] TaxonDetermination- After I click "Add" then a row appears, however the OTU is not cleared.
* [ ] I wonder if flashing the full-screen spinner, even if it's only a second, would be helpful after Save -based clicks?
Need "Recent" Button
* [ ] Georeference count on Button is incrementing on Save and new with CE locked, it shouldn't

**Comment by mjy** [comment]
* [ ] Change New CE -> 'Map verification' to -> `Verbatim coordinates preview`.  Add orange help stub for it.
* [ ] CE -> `Parse` -> `Parsed`
* [ ] Geographic Area -> Show other options -> at least 1/2 width (less wrapping)
* [ ] Radial navigator  (and default) -> Edit -> route to task
* [ ] New -> route to task
* [ ] `/field_occurrences/list` -> does not exist
* [ ] `/field_occurrences/autocomplete` -> add, and enable

**Comment by mjy** [comment]
<img width="365" alt="Screenshot 2024-02-27 at 1 14 19 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/ca070cdf-081d-4ef3-b969-4b959cd28829">

* [ ] Update CE uses to better reflect 2 things: total uses, and current sequential use.  Something like "Total use: 123 | Current sequential use: 0".  Sequential ticks everytime a locked CE gets used again (as does Total).
