### ISSUE TITLE
Task - DwC-A Workbench - Add message and error handling to dropzone

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1644]
When I drop a zipped archive onto the dropzone, then I the request (may) raise:

* [x] `DarwinCore::EncodingError - No support for encodings other than utf-8 or utf-16 at the moment`, but the interface does not catch and report failed drop.
* [x] TypeError - no implicit conversion of nil into String:

Add handling for these and:

* [ ] Add message in Dropzone to indicated what is expected (a zip?)

**Comment by LocoDelAssembly** [comment]
> DarwinCore::EncodingError - No support for encodings other than utf-8 or utf-16 at the moment, but the interface does not catch and report failed drop.

This is now catch on backend-side but I need to submit code to dwc-archive gem to provide a message along with the exception to not make the validation message too programmers-oriented.
