### ISSUE TITLE
Comprehensive - Start/End time & units of elevation does not save

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1645]
**Describe the bug**

When I save a record with start and end time - the values do not save/appear anymore. Same with units of elevation. Meters and feet do not save/appear upon reloaded form. 

**To Reproduce**
1. When I go to comprehensive.
2. Then I choose/create a collecting event and save units of elevation or start and end time. 
3. And I save.
4. Then the values do not appear when record is saved. 

Pre-save:
![image](https://user-images.githubusercontent.com/11411328/89943640-26e83500-dbe4-11ea-9386-fd6a6bf6b92b.png)

After save:
![image](https://user-images.githubusercontent.com/11411328/89943695-3b2c3200-dbe4-11ea-9369-24ba2e6b0317.png)

**Expected behavior**
Should save.

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Perhaps a form display issue?  When you use the basic "Show" view do they appear?

**Comment by tmcelrath** [comment]
They are saved if entered in the basic show/edit form. But if I edit them at all in comprehensive they disappear and are erased, even if first entered in show/edit form.

**Comment by tmcelrath** [comment]
Also show/edit form for elevation says "all values in meters" but comprehensive form gives both options and does not auto-select meters after entering values in feet.
