### ISSUE TITLE
Pinboard - auto navigation

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1647]
When I pin an X on the inpboard, and it is set as the default (by whatever mechanism), then I want to navigate to the Browse of that record when avaiable.

Hard code hotkeys, it's a two step macro. First key sets mode to pinboard nav, second fires the specific.

* ctrl -> N (?) to trigger pinboard nav mode, then
  * O -> Browse OTU
  * T -> Browse taxa
  * C -> Collecting event
  * S -> Collection object

* [ ] Quick modal flash notice if nothing is pinned for the second set option.
* [ ] Quick modal flash notice to state "navigating to X" ?

**Comment by jlpereira** [comment]
Some of those hotkeys are already used in other interfaces, we gonna need to think a different combination or another way to navigate between pinned  default items. 

Maybe we could activate the navigation and display a modal with all default pinned items. 

So the steps could be:
1- Hotkey to open pinboard navigator (Modal)
2- Display all pinned default objects(Click or press key number to select one)
3- Show all task available for that kind of object. (Click/press key select it.)

I think we could use radial navigator metadata to this.

**Comment by mjy** [comment]
None should be in use, because they follow the first key press which is the
only unique one we need?  Or maybe you're saying we can't combo?  Hmm.

We just want two keys to fire the opening, nothing more.  Ideally- first
key -> in a mode, second key -> launch.

**Comment by jlpereira** [comment]
If you only want to navegate on browse tasks for each type, we could do this:

1- hotkey to open modal (On modal display which object is set as default and shortcut to browse)
2- press (o, t, c or s) not need a combination, because will be binded on the modal

**Comment by mjy** [comment]
THis! Exactly.  Here is the idea:

![Screen Shot 2020-08-13 at 9 57 43 AM](https://user-images.githubusercontent.com/22600/90150634-7e54e500-dd4b-11ea-97b0-3355edd37f6c.png)

**Comment by mjy** [comment]
Meh- alphabetic not ordered, but do what notes say, not what it looks like :)
