### ISSUE TITLE
Map obscures

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1653]
When I attempt to enter a new asserted distribution directly from the radial annotator in Browse OTUs page, a map (which I believe is a new feature) is overlaying the Geographic Area fields.

See attached Screenshot.

My browser is Safari 13.1.1 in Mac OS 10.14.6.

Working in Production mode.
![Screen Shot 2020-08-17 at 12 15 14 PM](https://user-images.githubusercontent.com/30122486/90440058-3b24aa00-e09c-11ea-970d-a6b5117d9e11.png)

**Comment by proceps** [comment]
in looks normal in Chrome.

**Comment by mjy** [comment]
Raises the point- technically Safari is not supported.  If we can't replicate in FF or Chrome we'll have to close this.  Could be something basic though.

**Comment by jlpereira** [comment]
Tested on FF and Chrome and seems to works fine.
