### ISSUE TITLE
Species Files migration - missing(?) metadata like identifiers 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#166]
It seems we are perhaps missing some metadata.  These observations need further confirmation.

* TaxonNameID from SF not present as attribute in TW?
* Potentially add higher_taxon_name from SF as an attribute to name in TW.
* Potentially add original taxon name string as data attribute for cross reference

**Comment by mbeckman** [comment]
Will happily add SF.TaxonNameID as data_attribute. But, Mike and I are looking at the other two items; we're not sure what the value of higher_taxon_name (do you mean AboveID?) and taxon_name_string would be in the TW environment. TW.parent_id is often different than SF.AboveID.

**Comment by mbeckman** [comment]
Added attribute for SF.TaxonNameID. Per conversation with @mjy, no need for attributes for SF parent_id or SF taxon name string.
