### ISSUE TITLE
People API results incorrect for combined role and name request

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#1662]
http://localhost:3000/api/v1/people?roles=SourceEditor&last_name=murphy&token=hp7-CAdxGHZLtyiq4n8hmw
should return no names, but instead returns all last names of Murphy (same as if no roles specified).  All Murphys in this database are < SourceAuthor >s.

**Comment by jrflood** [comment]
I'm sorry, this should have been people, not sources -- edited title !

**Comment by mjy** [comment]
Closing, currently returns nothing.
