### ISSUE TITLE
Correct form of attributing credit to TaxonWorks

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1666]
I would like to know how I should preferably cite the role of TW both in papers and on web-pages.
I am talking about works that were directly developed using the TW platform rather than passing citations.

**Comment by LocoDelAssembly** [comment]
Also think the former might be nice, but unsure how to dealt with authorship properly... All contributors (continuously changing https://github.com/SpeciesFileGroup/taxonworks/graphs/contributors list), probably cannot be excluded. Not including any author might not be valid either. Perhaps "Yoder, M. J. et al." would be fine?

Other option would be citing in references normally, like: TaxonWorks [Biodiversity software]. (2020). Retrieved from http://taxonworks.org/

(Retrieved from part a bit doubtful if should really go, as the cited URL as well)

**Comment by adrik29** [comment]
We,ve decided to display a TW icon on the catalogue page, which links to the main TW page.
Of course we haven't put it live yet; this is just an experiment -- maybe in two weeks it will be live:
![image](https://user-images.githubusercontent.com/46284943/91074854-8a765780-e613-11ea-9bda-0fc25c4ae22d.png)

And in the companion eBook we wrote something like:
![image](https://user-images.githubusercontent.com/46284943/91074974-b8f43280-e613-11ea-97d7-33798dd7f363.png)

**Comment by mjy** [comment]
Get my name out of there!  

Substitute "Matthew J. Yoder" with "The Species File Group and many other [Contributors](https://github.com/SpeciesFileGroup/taxonworks/blob/development/CONTRIBUTORS.md)".

BTW @gdower is experimenting with a tree browser as well.  At some level you might join forces ultimately.

**Comment by debpaul** [comment]
How BLENDER does this http://citebay.com/how-to-cite/blender/

**Comment by debpaul** [comment]
Example from the Digital Curation Centre (DCC https://www.software.ac.uk/how-cite-software) for Software checked-out from a public repository:

OGSA-DAI REST. OGSA-DAI Project. http://sourceforge.net/projects/ogsa-dai. 27/04/2012. Check-out: ogsa-dai/branck/ogsadai4.1/, revision 1657.

**Comment by mjy** [comment]
I *very* much like the Blender format, thanks for digging it up.

**Comment by debpaul** [comment]
We will also be asked how to cite the software in body of the paper. Example from DCC again

>The results in this paper were obtained using R 2.7.0 with the packages MASS 7.2-42, pscl 0.95, sandwich 2.1-0, car 1.2-8, lmtest 0.9-21. R itself and all packages used are available from CRAN at http://CRAN.R-project.org/.

So we could use this to create a variation:

> The [website] uses data shared via TaxonWorks open source, community developed software, version ##, specific version for this website archived on Zenodo available at [DOI].

**Comment by mjy** [comment]
I'm not sure we need to archive the code in Zenodo, there are built in github level archiving mechanisms.  I.e. the only reason to do so is a DOI?

**Comment by debpaul** [comment]
@mjy wrote:
> I'm not sure we need to archive the code in Zenodo, there are built in github level archiving mechanisms. I.e. the only reason to do so is a DOI?

Practically speaking, yes.
But discovery might also be enhanced? Does including access to a version of TW address any reproducibility needs (for a given instance of the Opiliones site, for example)?

**Comment by debpaul** [comment]
"Inconsistency is also reflected in recommendations that may include referencing articles that discuss the software, direct 
citation of the software itself, or simply providing a link to where it can be downloaded 
(Figure 1). " from http://www.ijdc.net/article/view/11.2.48/451

Which do we want to do? provide?

**Comment by debpaul** [comment]
The bits we need are (from the same article as above).
  - identification
  - access and discovery ( providing stable points of access through archives, registries, or (less desirably) 
software article)
  - credit and appraisal
  - provenance and connection

**Comment by mjy** [comment]
A clarification- this issue is just for the TaxonWorks code base, not specific projects, which we have another issue for and is much more of a multi-faceted problem.

I think this is also for the collective, rather than individual contributions let's open a new issue to explore those aspects. 

> direct citation of the software itself

^ This.

> One feature of software citation that is increasingly recommended is the use of unique and persistent identifiers, such as DOI. 

I would prefer a PURL pointing to the git repository.  These meet the requrirements I think.

Something like:

```
Community, T., 2021. TaxonWorks - Software to document the Earrth's biodiversity, Species File Group and the TaxonWorks Community , Champaign/Urbana and Worldwide. Available at: http://taxonworks.org  <or some PURL>.
```

**Comment by mjy** [comment]
Somewhat unrelated but ongoing discussion at CoL as well points to considerations here: https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=Wikipedia&id=1019154774&wpFormIdentifier=titleform#CBE/CSE_style

**Comment by debpaul** [comment]
@mjy to clarify

1. #1666 for citing the **TW codebase**. Something like
>
```
Community, T., 2021. TaxonWorks - Software to document the Earrth's biodiversity, Species File Group and the TaxonWorks Community , Champaign/Urbana and Worldwide. Available at: http://taxonworks.org  <or some PURL>.
```
2. For **citing various projects using TW** see https://github.com/SpeciesFileGroup/taxonworks_doc/issues/40
3. I'm confused by your [comment](https://github.com/SpeciesFileGroup/taxonworks/issues/1666#issuecomment-825292168): "**let's open a new issue** to explore those aspects"
 - what aspects exactly. I can't follow yet. Perhaps we need a Venn diagram or similar.

**Comment by mjy** [comment]
Perhaps we can rephrase the needs (@debpaul see also our external doc, I'll try to sync the two lists):

_As an author I would like to acknowledge, via citation, the people who contributed to:_

# TaxonWorks
* [ ] The collective code in the TaxonWorks repository (all, version free)
* [ ] The collective code in TaxonWorks at a specific version
* [ ] The non-code, but digital, contributions to  the TaxonWorks community (e.g. opening issues, adding help documentation, etc.)
* [ ] The non-code, and not digital, contributions, e.g. people we talked with that gave us ideas
* [ ] Any of the above (a true community citation)

# Data in TaxonWorks
* [ ] All data in any instance of TaxonWorks, ever, destoyed or not
* [ ] All data in a single instance of TaxonWorks
* [ ] All data in a single project of TaxonWorks, not accessible by the API
* [ ] All data in a single project, accessible by the API
* [ ] All data in a single project, archived somewhere (e.g. SQL dump to Zenodo)

**Comment by debpaul** [comment]
# Citing TaxonWorks

- [ ] The collective code in TaxonWorks at a specific version.

Hadoop example, Apache Software Foundation.

author name, software name, version number, year, available at url pointing to the software

@software{hadoop,
  author = {{Apache Software Foundation}},
  title = {Hadoop},
  url = {https://hadoop.apache.org},
  version = {0.20.2},
  date = {2010-02-19},
}

Apache Software Foundation. Hadoop. Version 0.20.2. Feb. 19, 2010. URL: https://hadoop.apache.org

Trying the following in TW, doesn't load, says "wrong data."

@software{taxonworks,
  author = {{Species File Group}},
  title = {TaxonWorks},
  url = {https://taxonworks.org},
  version = {0.80.2},
  date = {2021-02-19},
}

I edited the above to

@misc{taxonworks,
author = {{Species File Group}},
title = {TaxonWorks},
url = {https://taxonworks.org},
version = {0.80.2},
date = {2021-02-19},
}

and had some success but not total: See
https://sandwich.taxonworks.org/tasks/sources/new_source?source_id=11005

**Trying this next format**

@book{CUDA, 
   author = {{NVIDIA Corporation}}, 
   title = {NVIDIA CUDA Compute Unified Device Architecture Programming Guide}, 
   publisher = {NVIDIA Corporation}, 
   year = {2007}
}

@book{taxonworks, 
   author = {{SFG Group}}, 
   title = {TaxonWorks Documentation Guide}, 
   publisher = {SFG Group}, 
   year = {2021}
}

Also limited success with the above. See https://sandwich.taxonworks.org/tasks/sources/new_source?source_id=11006

**Comment by debpaul** [comment]
For me I'm at the point of

a) citation formats we need are not hard (or at least much easier) once we figure out how to deal with the "who" when it equals the Species File Group. I see that citing an author when the author is an organization, foundation, or group, that a hack (like the double curly braces) is all that works to stop the "Group, S. F."

b) Once we figure out a above we have the issues of

1. importing citations into TW
2. displaying them as desired / needed
3. being able to search relevant source fields to filter
4. being able to export in format we desire and publisher/s desire
5. being able to import (bibtex) or other citations into TW with expected behavior.

With point 5 above, I exported bibtex file, then tried to use it to re-import. No joy. But I need someone else to review what I tried to do ... The line endings were unix, and encoding was UTF-8 (but there are no "label" fields in TW exported BibTeX files).

**Comment by debpaul** [comment]
[DRAFT Example text file](https://github.com/SpeciesFileGroup/taxonworks/files/7181028/citing_taxonworks_examples.txt) for different types of citations needed for TaxonWorks aligned with the types outlined in [Matt's comment above](https://github.com/SpeciesFileGroup/taxonworks/issues/1666#issuecomment-917728906).
![bibtex_notepad_screenshot](https://user-images.githubusercontent.com/2990155/133686821-8e62a5c8-4a61-44a8-9b46-0d0a2aa21162.PNG)

**Comment by debpaul** [comment]
[Sample bibtex file](https://github.com/SpeciesFileGroup/taxonworks/files/7181034/tidyBibTeX_Copy.txt) of various article types

**Comment by mjy** [comment]
>  is it okay to solve the Accessible at by putting it inside the how published?

Yes, sounds very reasonable to me.

**Comment by mjy** [comment]
Completed here: https://docs.taxonworks.org/about/citing-taxonworks.html.

**Comment by tmcelrath** [comment]
Recent comment about the citation format here: https://docs.taxonworks.org/about/citing-taxonworks.html#other 
"One of the comments about the Sphindidae chapter that was made by the lead editors of BOCUS is that our Sphindid catalog citation was not O.K. as is.  Here is Andrew Smith's comment:  " this link goes to a sign-in page and I have no account (neither will most readers).  Can this reference be reworked to cite something accessible publicly?"   Any thoughts about that?  Should we just plan to get the paper version out and then swap out the citation?"

**Comment by tmcelrath** [comment]
Thoughts?

**Comment by mjy** [comment]
Can you post what was actually used?  I'm not seeing a link in the documentation to a password protected endpoint, just API ones.

**Comment by mjy** [comment]
That's not the link in the documentation ;)

**Comment by tmcelrath** [comment]
Good point.

**Comment by mjy** [comment]
We should, however, be able to provide more specific endpoints for things that come from the API.  In theory though the results are replicable via some work.
