### ISSUE TITLE
TW erratic

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1668]
Since yesterday TW is behaving strangely.
I suppose it is suffering some big maintenance overhaul.
Otherwise it is alarming...
![image](https://user-images.githubusercontent.com/46284943/91034096-cccf7280-e5da-11ea-9167-26e0d7194b5f.png)

**Comment by mjy** [comment]
Hi @adrik29.  Thanks.  We are indeed looking into network issues for the SFG instances of TW.

**Comment by LocoDelAssembly** [comment]
@adrik29 please let us know if you are still seeing those "Backed fetch failed" screens. Thanks!

**Comment by adrik29** [comment]
It seems normal again to me.
But don't worry, I'll report here if I experience turbulence...

**Comment by LocoDelAssembly** [comment]
Perfect, thanks!
