### ISSUE TITLE
Irritating and distracting unneeded confirmation

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1669]
In the **_Edit Taxon Name_** module,
in the submodule **_Original combination and classification_**
![image](https://user-images.githubusercontent.com/46284943/91037448-6567f180-e5df-11ea-96b1-991ba5e75f0d.png)

Every time I want to change the combination I have to press the red trashcan icon, which I find weird to begin with, but the real issue here is this useless confirmatory message which forces me to deviate from what I'm doing to go up and press "yes" -- multiply this for hundreds of times.... how much time spoiled.
![image](https://user-images.githubusercontent.com/46284943/91037630-b7107c00-e5df-11ea-8daa-2bf3f07b7d85.png)

What seems to be the alternative here?
-- No, I'm just a crazy person randomly pressing keys?

Therefore I humbly suggest, if I may, that you **remove** this confirmatory message. All 5 people in my project think the same way... We think it is a **counter-productivity** tool.

**Comment by mjy** [comment]
@adrik29 thanks for the insight.  Are you thinking about all confirmation dialogs, or just this original combination dialog specifically?

**Comment by proceps** [comment]
If implemented, only as a user preference. I would say, if the database is well maintained, the delete is relatively rare action. We started with the interface without confirmation. Everything was deletable in a single mouse click. I run into the problem, that occasionally I delete something, not intentionally. just clicking in a wrong area (you know the buttons close to each other and the mouse cursor slides), and after deletion, I realize that I do not know what is deleted. Unless there is an implementation, to revert every single deletion, I would prefer to keep the confirmation. With the revert mechanism, I would agree, that delete without confirmation is much more convenient. Besides, we have slightly different behavior in different parts of the system, which adds additional confusion. In some places delete means deleting the object in the database. In some other places, it is related to editing, for example in the pin board removing _default_ property from the selection. Removing the default does not remove the object. And you can also click the same button again, and restore the default condition. The same for untag and tag back the object. You can repeat it several times. Deleting the original combination, on the other hand is not reversible. I would strongly oppose removing the confirmation.

**Comment by mjy** [comment]
Second bit- There should be no confusion about delete functionality.  Red means touch a database and remove a record (default on current record), Green means touch a database and add data, everything else does not touch the database.

First bit- is tricky.  There is a strong argument for optimizing the application to getting new data towards stable, rather than mantaining stable.  Stable data will also have fewer edit operations in general.  Your data are exceptional @proceps, new sets like @adrik29 are going to be more likely?

**Comment by mjy** [comment]
Folowup to @adrik29 do you know you can drag/drop the names up and down in that tool rather than destroying and re-creating?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/91060730-ea0f3b80-e5f0-11ea-9fb4-6ab2fda8b5d1.png)
Look Three buttons. All of them red (meaning deletable from the database). But in case of first 2, I can delete and restore, but in case of the third one, it is permanently out of the database. This is a huge difference. The interface originally had no confirmation for any delete action. It was extremely difficult for me. Yes in most of the cases it does not matter, I remember what I deleted, and could just search and restore, but few time, I had to go and find a catalog to restore the relationship, and in few instances, it was not trivial. The win win solution would be to implement some kind of delete cashing, and if you delete something by mistake, you can restore it. But I understand it is not trivial. Not in all cases. In some cases the delete is cascading. For example citations do not prevent objects from being deleted. Few times I deleted the distribution record with several citations attached to it, and this is already something which is not that trivial to restore. One can delete an object with citations, identifiers, notes, tags, etc. And you do not even notice that you delete those.

**Comment by proceps** [comment]
Yes, @mjy made a good point, in most cases editing of the original combination for me is moving taxon from genus to the subgenus. it is the same taxon name. So you can just drag the name one line down. The same for the taxon authors, if you want to change the order, you can just drag and drop.

**Comment by mjy** [comment]
I see the distinction @proceps, thanks.  I'm hoping @adrik29 just didn't know a bout the drag drop :)

**Comment by adrik29** [comment]
Thanks for all the hints. In the case of our project "Opiliones of the World" there is a particularity:
We started up by importing a spreadsheet containing names and authorship, but the author and dates act as placeholders, and we have to as I say "**kill** the placeholders", replacing them for real connections, real **sources**, with real **people**.

What often happens: we have a species originally described in genus Aus, but which is currently in genus Bus.
For example:
![image](https://user-images.githubusercontent.com/46284943/91066226-d7ecc780-e607-11ea-993b-c609db3e8b0d.png)

In my database we had Ventrivomer ancyrophorus (Butler, 1873), but we know we should insert Gonyleptes as the original genus.
Then I just go to Edit taxon name > Original combination and classification, here:

![image](https://user-images.githubusercontent.com/46284943/91066461-21d5ad80-e608-11ea-9a04-bd1f39014a26.png)


As far as I know I cannot write or paste the name Gonyleptes in the form, rather I have to hit the "set as current" button so I am able to somehow interact with the form.

Then I have this:
![image](https://user-images.githubusercontent.com/46284943/91066743-7547fb80-e608-11ea-92d9-cc79499ad6bc.png)

And now I can edit. Maybe I'm missing something here.
But this is the part where I mentioned I'm using the red trash can because the system requires confirmation...
And after I insert the original genus, and kill the placeholder, inserting the real source the result should be this:

![image](https://user-images.githubusercontent.com/46284943/91067711-a70d9200-e609-11ea-9f8d-7778007649e0.png)

**Comment by adrik29** [comment]
I wish to clarify that I'm not talking about the pinboard. I understand that the red trash can in the pinboard simply removes the shortcut and that I should should look for the green bar to see which of the items on the pinboard is the current one.

And I'm not talking about every single confirmation -- I am just talking about this specific part which seems very weird to me. Because I cannot interact with the form until I choose the "set as current" option.

**Comment by mjy** [comment]
You can trigger the start of the editing by dragging the name down, rather than clicking set as parent!  Then all the boxes are searchable.

**Comment by adrik29** [comment]
Oops.... I knew there was something weird.

**Comment by adrik29** [comment]
Now a new world unveils before my eyes.
Please note that I'm **not** stupid -- I just didn't have the idea of dragging...

**Comment by mjy** [comment]
You are definitely not stupid.  We are stupid for not being able to communicate in the interface that you can do this.  Basically our intent was the up/down arrow became a drag drop cue anywhere in TW.  We'll try to emphasize this.  @jlpereira perhaps we can add blue circles around the arrows to indicate actionability?

**Comment by adrik29** [comment]
Well, Matt -- the best way to learn is doing. A little bit every day, so that you get familiar with the system. 
In the very beginning TW is intimidating, especially for people who don't master nomenclature concepts, as I can gather by my 4 collaborators (they are intelligent people, but who stumbled a lot with the interface).
But in time I've become very comfortable using TW, and now I can appreciate the careful attention you gave to the details. 
It is a truly wonderful platform!

**Comment by jlpereira** [comment]
@mjy agree, blue button and title on mouse hover to explain this is a drag and drop input
