### ISSUE TITLE
Species Files migration - missing taxon name authors for ref in ref

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#167]
For example /taxon_names/1126409 in the sandbox is missing the taxon name roles that should have been created.  

This might be an issue with nested attributes not saving.

**Comment by mbeckman** [comment]
Ref in ref has been revamped into two categories: 
* Chapter author: Galvagni in Baccetti 1987, a true ref in ref; all work therein attributed to Galvagni.
* Taxon name author: Chamorro-Rengifo in Braun, Chamorro-Rengifo & Morris. Chamorro is cited as taxon author in a paper authored by three people.

Chapter authors are only considered for bibtex books. There may be some reference data from SF that are inconsistent with this.  Possible reasons would include incorrect original data entry. If anyone finds such a case that cannot be resolved under these guidelines, please bring up in GitLab.
