### ISSUE TITLE
Editing Content: Can't save changes and improvements to search/edit content

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1670]
I have one potential bug, and a couple of suggestions for dealing with "Contents"
**Bug/Issue:**
When using "Editing content" to edit previously created content, I try to save changes, but I get an error that "Topic has already been taken". I am not creating a new topic, I just wanted to edit the text of the existing content. Oddly this isn't an issue with all "content" I create. Just ran into it in this one instance.

![EditContent](https://user-images.githubusercontent.com/70152690/91076025-e7224400-e60c-11ea-815a-bd4f5474d47f.jpg)

**Suggested Improvements**
In "Browse OTUs", under the radial with associated data (like asserted distributions biological associations and such), there is wedge for "Contents". However, you can only create new content, and while it lists previously created content, It doesn't seem like you can directly edit existing content from this window.
![EditContentRadial](https://user-images.githubusercontent.com/70152690/91077141-8d227e00-e60e-11ea-821c-997df47d0231.jpg)

So therefore, I need to navigate to the content I want to edit from Contents tab. However, the search bar here only searches for strings within the content, but does not allow for searches by OTU, so I need to go to the list of content and find the content associated with an OTU I want to edit.

Could you either allow editing of content from the associated data radial in the "Browse OTU" view or could you modify the search bar under "Contents" to search for the string in OTUs as well (i.e., if I search Aus bus, it lists all content created FOR Aus Bus, not just content containing the string Aus Bus).

**Comment by jlpereira** [comment]
Thanks for report this, @kandakoj 
There is a task called "Content editor" that could be better for you to create and edit contents.

**Comment by mjy** [comment]
Hi @kandakoj.  Awesome!  SO great to see people using the Content editor.  If you can replicate the "content is already created" bug (I suspect it's a latent message that displayed after the fact) let us know.

**Comment by kandakoj** [comment]
Hi @jlpereira and @mjy. Thanks for the quick response. I could not replicate the error in "Content editor". Strangely the error in my first screenshot still persists if I access the editing window from "Contents", but I will switch over to using "Content editor". Thanks!

Could this function be added to one of the radials in "Browse OTU?" It would be very convenient to navigate directly from OTU to "Content editor".

**Comment by mjy** [comment]
It's there all ready.  OTU radial -> All tasks -> Bottom link?

**Comment by kandakoj** [comment]
Oh Thanks! I was looking at the wrong radial; the one that had the Contents wedge.

**Comment by mjy** [comment]
Aha!  @jlpereira can we add a direct nav link from the contents wedge row?  (and truncate that text too, no point in trying to read it there).  Maybe down to 2 lines?

**Comment by jlpereira** [comment]
Yah, no problem

**Comment by jlpereira** [comment]
@kandakoj we added a edit button on the radial object. This will redirect you to the Content editor task to edit the selected one. You will see this on the next update.

Closing now, reopen if is needed.
