### ISSUE TITLE
Formatted content text not displaying under Browse OTU

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1671]
This is tangential to the previous issue and concerns the display of content un the Browse OTU. Again, one potential bug, one suggestion for improvement.

**Potential bug**

Using the Content Editor, I added formatting (italics and hyperlinks) to the text block. It appears correctly in the Content Editor preview. (imbelis and sierrae italicized and as a link)
![ContentEditorPreview](https://user-images.githubusercontent.com/70152690/91087223-1beac700-e61e-11ea-9aa6-3992729dd027.png)

But under the Contents in Browse OTU, the text only displays with the formatting code.
![BrowseOTU_Content](https://user-images.githubusercontent.com/70152690/91087493-8865c600-e61e-11ea-89c5-d8561644c113.png)

In case this is a browser issue, I am using Chrome.

**Suggested Improvement**

In the same way you can drag and changes the display order of the various attributes in Browse OTU like common names, biological association, and distribution, can this be done for topics under "Contents"?

**Comment by mjy** [comment]
Good catch. @jlpereira we'll just have to filter it through MD render.  I can do it SS if we need, however we're also goning to be extending that markdown slightly to let OTU IDs be much simpler to add than what @kandakoj is doing.  Maybe it's time to tackle that.

**Comment by jlpereira** [comment]
> Good catch. @jlpereira we'll just have to filter it through MD render. I can do it SS if we need, however we're also goning to be extending that markdown slightly to let OTU IDs be much simpler to add than what @kandakoj is doing. Maybe it's time to tackle that.

What you mean exactly with extending markdown? a special tag or something like that?

@kandakoj we make some changes on Browse OTU, now you will see the markdown render correctly on the next update.

**Comment by mjy** [comment]
Yes- things I mentioned before.  Will open new issue.
