### ISSUE TITLE
List of in-Project authors

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1678]
It would be very useful to be able to see and manipulate a list of authors ONLY IN A GIVEN PROJECT.
I get lost amidst zillions of abstract names which don't mean anything for us.

**Comment by mjy** [comment]
@adrik29 understood, thanks for the issue.  It would help to define the new(?) task if you could help list the ways you would like to "manipulate" the People in your project.  We of course know some, but getting an idea as to the different possible actions we want to take in a more concrete way can help flesh out this interface.

**Comment by proceps** [comment]
I tent to agree on this. As well as to limit the list of sources to a particular project. As an option of cause. May be a check box.

**Comment by mjy** [comment]
Sources can already be limited in the primary interface where we interact with them- the source filter- but this is about people ;)

I'm pretty strongly opposed to by default setting sources to only those in your project in interfaces like autocompletes, that defeats the long term mission of unification.  We want to expose, just enough you to other data, but I agree there are times, for example when cleaning up data, where you want to focus on what is in your project.  When you are assinging data- you should see everyone/thing.

**Comment by adrik29** [comment]
We are using those filters now to debug our base. There have been some errors in the initial migration (which also left zillions of placeholders to be uniquified).
And of course some errors of copy/paste -- we need to see a list of the authors we already have, but currently it is impossible.

**Comment by adrik29** [comment]
As about general things, for example, Linnaeus 1758 book -- it would really be desirable to have it unified to avoid duplicating efforts.
But speaking for myself, I have found some authors/earlier books cited in a very cursory manner -- I strive to assign birthdates, etc to their files. And I would love to assign LSIDs to them as well.

**Comment by proceps** [comment]
I believe, it is fixed (not in production yet). All search fields for people and sources prioritize those used in the project. Other sources and people not in the project will be listed at the bottom of the list.
