### ISSUE TITLE
Species Files migration - seemingly "empty" citations of taxon name use

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#168]
See "Gryllus" in the Orthoptera sandbox. 

There are protonym derived (click the eye, then "origin") citations of the form `Gryllus (Gryllus)` that exist, but don't otherwise have associated metadata.

Identify which metadata is expected to be there by comparing to SFS.

It could be that these were topic/annotation related and that those annotations are now with (or supposed to be with an OTU).

**Comment by mbeckman** [comment]
It's not clear to me exactly what the issue is here. If there is an issue with how the taxononomic data is being imported, please be specific and raise the issue in GitLab.
