### ISSUE TITLE
pdf viewer

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1680]
The pdf viewer in TW accumulates pdfs (and fragments them) unless you leave the page and then return for a new source search. The downloads work fine (only downloading the article that was selected.

Is there a way to clear what is in the viewer (while working on the same page [i.e. sources]? It wants to retain all new source items when the pdf is opened and the only way to clear it is to exit the source page. It should only display the pdf for the source that is selected.

**Comment by mjy** [comment]
@JohnHeraty welcome to the issue tracker!  Thanks so much for posting here.

@jlpereira suspect we aren't reseting the viewer?

**Comment by jlpereira** [comment]
Yes i think that could be the reason, we have to clean the DOM Element before append the new one

**Comment by mjy** [comment]
@JohnHeraty we need better steps to replicate, can't do so right now.  Make sure to include browser etc.

**Comment by JohnHeraty** [comment]
Go to filter sources

Under tags pick “chapter morphlogy2” [returns 10 references]

open more than one pdf at a time and look in the viewer - the pdfs accumulate, they do not replace. And not only do they not replace, they also “interdigitate”. In the example, you have page 1 from Chiappini and page 68 of Amsorak et al.

Also, I can only load papers to the viewer using filter sources. If I use just sources, it always downloads with no option to open in the viewer.

John

**Comment by jlpereira** [comment]
I pushed a fix for this that probably fix the problem, you will see this reflected on the next update. If the problem persist, please reopen the issue.
