### ISSUE TITLE
sources search limitation

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1683]
**filtered sources capped at 1000**

**To Reproduce**
1. choose filter sources > mymarid [search text] + Mymaridae [title]

The maximum number of records that can be listed and bibtex exported is 1000. There should really be no limit.

**Screenshots**
<img width="945" alt="Screen Shot 2020-08-28 at 4 23 02 PM" src="https://user-images.githubusercontent.com/30123556/91623463-7357a280-e950-11ea-93ba-d89c19300875.png">

**Environment (please identify where you experience this bug:**
*** One of ***

- Production

**Comment by mjy** [comment]
![Screen Shot 2020-08-28 at 11 07 18 PM](https://user-images.githubusercontent.com/22600/91628272-aff0c180-e983-11ea-91c1-79142f158f1a.png)

Re-open if you don't think this will resolve.

**Comment by mjy** [comment]
Meh, wrong issue, sorry.

**Comment by mjy** [comment]
@jlpereira Here is a strategy.  Can we cap the in-browser show at 2k (current limit I think), but the download button ask for the whole thing?
