### ISSUE TITLE
I see dead people

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1685]
We in the WCO Project think that adding **LSID** to people and papers is desirable and important.
We are adding all Opiliones authors and papers to ZooBank.
Can I suggest that you add a field for **LSID identifiers** for people and sources?

**Comment by mjy** [comment]
It alread exists, Annotator Radial -> Identifiers -> Global -> LSID.

**Comment by adrik29** [comment]
I meant in the "export" facilities...

**Comment by mjy** [comment]
Is that the same as this? https://github.com/SpeciesFileGroup/taxonworks/issues/1679

**Comment by adrik29** [comment]
I guess I'm getting old -- I forgot I had already posted that one -- a thousand apologies...
