### ISSUE TITLE
Non-original combination authorship lacking parentheses

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1686]
The genus Jimeneziella was described by Avram (1970) with two species without type fixation. As such, it is a nomen nudum.
Kury & Alonso (2011) noticed this and made the name available by describing it as new genus. They decided to use the same original name of Avram for familiarity.
Both originally included species should came in parentheses, because **it is not the same genus**.
Jimeneziella decui (Avram, 1970) and Jimeneziella negreai (Avram, 1970)
But TW fails to recognize this case:
![image](https://user-images.githubusercontent.com/46284943/91767227-30950500-ebb2-11ea-932a-4c90fbfc94e6.png)
![image](https://user-images.githubusercontent.com/46284943/91767282-49051f80-ebb2-11ea-85b3-e83dd4d4c9b2.png)
![image](https://user-images.githubusercontent.com/46284943/91767362-689c4800-ebb2-11ea-956f-418fdf956140.png)

**Comment by mjy** [comment]
@proceps will comment, but you must create a second protonym IIRC for nomen nudem.  This is no changing, just adding facts.

**Comment by proceps** [comment]
Not sure this is possible to implement. I cannot use just taxon ID, because the cases when we have genus and subgenus with the same name and either of those could be assigned as an original genus. I know the cases like this, but I cannot recall any publication where parentheses were used. ICZN does not give any recommendation for such cases. Please remember, you can always force the parentheses in TW, but putting a verbatim author of the species with parentheses around the author name: "(Avram)"

**Comment by adrik29** [comment]
Thanks a lot for the suggestion, Dmitry. I hadn't thought of using verbatim -- **it seems a good way around this problem**.
ICZN is defective in many explanations, but this case is pretty straightforward. Parentheses should be used when the species is used in another combination, and this is another combination.
Jimeneziella Avram, 1970 is unavailable, while Jimeneziella K&A, 2011 is a brand new name. Author's names for the original species should definitely come between parentheses.

**Comment by proceps** [comment]
It is not always true. When a species is described in the genus with misspelled name, the parentheses are not used. Even when the original genus name is an unjustified emendation (available name). The parentheses are not used. The combination changes, but the author string does not. There is a special article of the Code for this. Before you asked, I thought that your case fall into the same category. Anyway, I send a question to the commission, to see what vision other people have. Unjustified emendations are actually a new discovery for me. I have to adjust the code to properly display the author strings for those.

**Comment by adrik29** [comment]
I clearly remember from ICZN that a misspelled generic name has no nomenclatural effect and it is considered as if it were a correct spelling. So, there is no reason to use parentheses in this case.
But the Jimeneziella case is different -- it is NOT the same name. If it was available it would have been a homonym. In 2011 we could have used any other name for the genus. We just put the same name as a tribute to the original author.

**Comment by proceps** [comment]
I believe, I was able to properly display the parentheses in cases like yours and also some others (when the original genus is a misspelling or unjustified emendation). Once the production is updated, you should be able just save the name to update the author string. No need for verbatim-author.

**Comment by adrik29** [comment]
This is excellent news, Dmitry -- I will warn the members of my team...
