### ISSUE TITLE
bibtex output

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1689]
**Bibtex output issue**

Journal names often not output in a format to be imported to endnotes

In the first two references, the journal is not imported; in the third it is. Problem of "booktitle =" versus "journal =" 

@article{55446,
author = {Bradley, J.C.},
booktitle = {Mémoires de la Sociéte Royale Entomologie de Belgique},
pages = {127-137},
title = {The wing-venation of Chalcidoidea and of some allied Hymenoptera.},
volume = {27},
year = {1955}
}
@article{56016,
author = {Bucher, G.E.},
booktitle = {Canadian Journal of Research (D)},
pages = {230-281},
title = {The anatomy of Monodontomerus dentipes Boh. an entomophagous chalcid.},
volume = {26},
year = {1948}
}
@article{56257,
author = {Burks, B.D.},
booktitle = {Annals of the Entomological Society of America},
journal = {Annals of the Entomological Society of America},
month = jun,
pages = {157-160, 1 plate},
title = {A study of chalcidoid wings (Hymenoptera).},
volume = {31(2)},
year = {1938},
stated_year = {1938},
issn = {0013-8746},
month_numeric = {6}
}

**Comment by mjy** [comment]
* The third record is incorrectly classified as an Article in TaxonWorks, it should be classified as a Book.

Checking the other two things.

**Comment by JohnHeraty** [comment]
The third record is the only one that works….

**Comment by mjy** [comment]
The data were imported incorrectly, populating the booktitle field when it should have been journal, in most cases.  I will convert them all back to journal.

If the third is working its for the wrong reasons.

The books will have to be spotted as such and changed to books, with the corresponding journal moved there manually.  There was no way for us to distinguish between them, but we still put the value in the wrong field.

Moving this to a UCD issue: https://github.com/chalcid/jncdb/issues/34
