### ISSUE TITLE
tagging in Filter Source

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1692]
**tagging does not work in Filter souce**

I want to add the "chalcid morphology chapter" tag to all of these references (and then delete the “chalcid morphology2” tag. The tag I want is on my pinboard, but I can’t change anything on these references in this view. I am not sure what the green tag button is supposed to do, but here it doesn’t do anything. I also cannot add a tag to any of these with the pinwheel.

<img width="1344" alt="Screen Shot 2020-09-01 at 9 00 34 AM" src="https://user-images.githubusercontent.com/30123556/91881171-efdecf80-ec35-11ea-9b4e-058c10aeb562.png">

**Comment by mjy** [comment]
Can you confirm the Tag on your pinboard is set to green/default?

**Comment by JohnHeraty** [comment]
seems to be.

**Comment by mjy** [comment]
@JohnHeraty the tags are being created, it appears that the success message is being shown.

@jlpereira After `success: true`  should we disable the Tag button until a new search is set?  Not sure of the state space.

**Comment by JohnHeraty** [comment]
The tag “chalcid morphology chapter” [pinned] is not being added… so no success????

Each citation in the search has only one tag, which was the original [chapter morhology2]

**Comment by mjy** [comment]
Mmm- wil have to check response in backend too.
