### ISSUE TITLE
pdf viewer

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1693]
**viewing pdfs in sources versus filter sources**

If I click on a pdf for a citation using "sources", the pdf is automatically downloaded (no option to put in viewer).

If I click on a pdf for a citation using "filter sources", the pdf goes to the viewer (with the option for a download).

Sources should be doing the same thing as filter sources (pdf to viewer then option for download)

**Comment by mjy** [comment]
@JohnHeraty can you screenshot and highlight the two link locations?  Are they the same icon?

**Comment by JohnHeraty** [comment]
No - not the same

**Comment by jlpereira** [comment]
The icon there is the "download pdf", we can change it or just add the other one to open it.
Just to clarify, this is on Data -> Source

**Comment by mjy** [comment]
Add another.
