### ISSUE TITLE
[TW-Error] collecting_events clone (ActionView::Template::Error) "undefined method `id' for false:FalseClass"

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1705]
See raise emails.  Potentially a UI issue with locked/not buttons, but needs exploration.

**Comment by LocoDelAssembly** [comment]
Exception not allowed to propagate through:
https://github.com/SpeciesFileGroup/taxonworks/blob/d7d5649080adcdf94f0f794b54e62b7ad249938e/app/models/collecting_event.rb#L1097
