### ISSUE TITLE
[TW-Error] georeferences update (NoMethodError) "undefined method `y' for #<String:0x00007f8764afbb38>"

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1706]
There were quite a few of these coming in.

Keep in mind with recent new adapter fixes, this vaguely sounds related to something that might have been fixed.   Errors raised on the 11th, correlate with gem update.

**Comment by LocoDelAssembly** [comment]
Most recent I have is July 30th which is earlier than v0.12.14 release containing the updated gem (August 17th). It is very related I believe so this can be closed.
