### ISSUE TITLE
NomenclatureCatalog.data_for method not defined

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1716]
We get some exceptions for this. These are the places that `NomenclatureCatalog.data_for` is being called from: https://github.com/SpeciesFileGroup/taxonworks/search?q=NomenclatureCatalog.data_for

**Comment by LocoDelAssembly** [comment]
This is the commit that deleted the code for that method (the entire file actually): https://github.com/SpeciesFileGroup/taxonworks/commit/bbeec06ed25e673ebb1c747b707e8d8816806096#diff-ffe0b2ce3bd449320630cb27c152c16b2fb1fc0dbe476e542c8c5e0ea81b6f67

**Comment by mjy** [comment]
This was an early experiment to produce a "paper" version.  I'll either remove the task or fix it.

**Comment by mjy** [comment]
Task was removed
