### ISSUE TITLE
Protonym - some cached_original_combination values are nil when original_combination_relationships are present

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1717]
Ping @proceps.  Just a heads up that I'm observing this.  Checking scope of problem now.

**Comment by LocoDelAssembly** [comment]
All taxa:
```
Loading production environment (Rails 6.0.3.2)
2.7.1 :001 > counts = {}
2.7.1 :002 > TaxonName.find_each { |n| counts[n.cached_original_combination.class.name] ||= 0; counts[n.cached_original_combination.class.name] += 1 }
 => nil 
2.7.1 :003 > ap counts
{
    "NilClass" => 514200,
      "String" => 131873
}
 => nil
```
Protonyms only:
```
Loading production environment (Rails 6.0.3.2)
2.7.1 :001 > counts = {}
2.7.1 :002 > Protonym.find_each { |n| counts[n.cached_original_combination.class.name] ||= 0; counts[n.cached_original_combination.class.name] += 1 }
 => nil 
2.7.1 :003 > ap counts
{
    "NilClass" => 465224,
      "String" => 131876
}
 => nil 
```

**Comment by mjy** [comment]
Aha.

They are restricted to 2 projects, Lep index, Opilinoes.  The latter probably pre-dates proper caching.  We will have to crawl and rebuild their index.

That drops it to 115 names in Opiliones.  This is the major concern as it happened in the interface some how.

**Comment by mjy** [comment]
Problem is recent:  `Protonym.joins(:original_combination_relationships).where(cached_original_combination: nil, project_id: 10).order('taxon_name_relationships.created_at').last.updated_at` -> Sun, 12 Aug 2018 13:30:52 UTC +00:00

**Comment by mjy** [comment]
The issue *may* have been triggered (unexplored, but based on recent conversation) by:
1 - Use set as parent
2 - Delete the genus level record
3 - Use autocomplete to set the genus level record
4 - Save

**Comment by proceps** [comment]
I did not check Lepindex, I checked 3i to make sure it is  not coming from the interface. With lepindex, yes. I suspect we suppressed cached values when migrating lepindex. Protonym.each soft_validate + fix should resolve this, and probably other issues. it should be run on each TN and each TN_relationship

**Comment by mjy** [comment]
Nah, just need `taxon_name.save` to rebuild cached values.

**Comment by proceps** [comment]
it is faster, but it does not resolve everything.

**Comment by LocoDelAssembly** [comment]
This issue is now tracking on a separate repo. Closing.
