### ISSUE TITLE
Add User field in Filter Nomenclature task

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1720]
This was discussed in the most recent webinar for UCD@TW.

It would be helpful for administrators for the UCD project (and doubtless others) to have a "User" field in the Filter Nomenclature task.  This would allow us to audit the work of particular users for quality control purposes.

**Comment by mjy** [comment]
@jlpereira We need to unify the creator/update/user/date facet across the filters.
