### ISSUE TITLE
Browse Nomenclature/OTU: strange display of synonyms combined with genus of parent species

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1722]
This is apparently a known issue, but I cannot find it here (therefore I post it here to close a corresponding issue over there, related to import of OSF data, https://gitlab.com/SpeciesFileGroup/onedb2tw/-/issues/49).

Example:

![grafik](https://user-images.githubusercontent.com/33210201/92544099-6cb80d80-f223-11ea-83b6-7e2064e72ac5.png)

![grafik](https://user-images.githubusercontent.com/33210201/92544140-8a857280-f223-11ea-8464-f13fb515ff9f.png)

_Mesaphyllum peruvianum_ was cited once more as valid species of that genus, and then has been syonymized below _Hyperphrona punctulata_. The TW combination "_Hyperphrona peruvianum_" was never published and the gender-specific suffix is wrong.

This is still very confusing to me and I think it requires a better solution. Synonyms of species names are usually mentioned as original protonym or subsequently published combinations, but never with an artificial database combination.

**Comment by proceps** [comment]
This is a TW convention. If the species enter into synonymy and the genus of the valid species is different, according to ICZN, this species is transferred to the same genus as valid species. Even if this combination never published. If you look at the list of citation. The citation is not listed there. The title of the page is just a placeholder. This name is not completely useless. Although the synonym is invalid now, it is an available name which is now classified in a different genus, together with the valid name of this taxon. It still competes for secondary homonymy, with all other names included in the same genus.

**Comment by typophyllum** [comment]
If the name is just placeholder, I still think that there must be a better solution to display this. Concerning OSF, for me we cannot display an unpublished name in a taxonomic database. People will certainly get confused. And may then even publish it. And if the display in TW will be changed, it will become uncertain where the name originated.

As for the competion for secondary homonymy: I cannot find a corresponding article of the Code. Article 53.3 (Homonyms in the species group) says for secondary homonyms that they need to be subsequently **published** in combination with the same generic name. For example, a paper that synonymizes _Urubamba urux_ under _Jivarus americanus_ does not mention the fictitious combination "_Jivarus urux_", i.e. this combination isn't published.

**Comment by proceps** [comment]
ICZN does not have any requirement to publish new combination. This is not nomenclature, this is classification. Imagine situation, I am sure those exist in OSF too. Somebody make two genera synonys, each genus is has 5 species, but publication does not mentioned any new combination. In the botanical code, it is required that all new combination be explicit. In zoology, we can just move all species from one genus to another in the database. And this is is a legitimate procedure in the ICZN. Public should not see any of those names. I believe in TW we should only display the names where the name of a valid taxon is in the title. All synonymy will be listed under the valid name in the proper format.

**Comment by proceps** [comment]
Jivarus urux Giglio-Tos 1898 does not need a substitute name not because the combination was not published, but because it is an older homonym. If it is published after Urubamba urux Liebermann 1951, yes, it would need a substitute name (which one the other hand could be resolved by reverse synonymy).

**Comment by typophyllum** [comment]
Thank you. _Jivarus urux_ Giglio-Tos 1898 was a bad example. Assuming there was a _Jivarus urux_ Cigliano 2005, as I understand the Code, that name would remain valid, as long as nobody **published** the combination "_Jivarus urux_ Liebermann 1951". (David incorporated the Code exceedingly thoroughly into SFS, and it alerts you when you add a homonym species name under a genus, but it doesn't alert when you synonymize a species name under a different genus that already includes the same species name,)

Apart from that, I think in a taxonomic database like OSF all nominal species should be displayed separately, to view their own taxonomic history (protonym, subsequent combinations, status changes, synonymizations, etc.) without mixup with other names. And it should by no means display unpublished combinations (currently with incorrect gender suffixes). No taxonomic work does that.

**Comment by proceps** [comment]
In the last example, a replacement name is required if the name with the same epithet are classified in the same genus. If a species is placed into synonymy with another species in different genus, it is transferred into that last genus. No combination is required. The name became invalid but it is still an available names. It still competes for the homonymy. Even if the combination is not published. ICZN does not have any requirements that combinations have to be published. The code does not have any requirements that synonymy have to be published. Those two acts are not nomenclatural changes. Those are related to the classification of the taxa.  TaxonWorks has preserved all validations which were originally present in the SpeciesFile and have several classes of validation, which were not checked in SF.

**Comment by LocoDelAssembly** [comment]
Sorry to come back to this, but confusion happened once more regarding this convention. The example is [Xiphidium (Xiphidium) geniculare Redtenbacher, 1891](http://orthoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1133400) which Sandcastle lists it as [Conocephalus (Anisoptera) semivittatus geniculare (Redtenbacher, 1891)](https://sandcastle.taxonworks.org/tasks/otus/browse?otu_id=36180). Furthermore, [type information in OSF](http://orthoptera.speciesfile.org/Common/specimen/SpecimensByTaxon.aspx?TaxonNameID=1133400) shows the name originally published, whereas Sandcastle shows the unpublished combination. I'm guessing here it is because how it is displayed and not a data issue, and if so, is this OK? How do I know the original combination of the typification?

Was not able to check CoLDP output because it has some issues at the moment. But also wondering how all this data should be exported in DwC and CoLDP?

Since Sandcastle IDs are not super stable screenshots below for posterity:
![image](https://user-images.githubusercontent.com/4991925/96129823-7e996a00-0ecd-11eb-9a73-e93087e56ca3.png)

Also browse specimen:
![image](https://user-images.githubusercontent.com/4991925/96130061-c7e9b980-0ecd-11eb-8526-81e95644740d.png)
(TaxonDetermination not sure if import error or still display convention, but essentially cannot know label actually has *Xiphidium (Xiphidium) geniculare* written down)

Show type material:
![image](https://user-images.githubusercontent.com/4991925/96130377-3af33000-0ece-11eb-89f7-79b8b72a8527.png)

NOTE
=====
Ignore URL identifiers, are placed there for debugging purposes and they won't be there in the future.

On behalf of @MMCigliano, CC @typophyllum

**Comment by proceps** [comment]
Type material should always show the original name of taxon (not current name of taxon). I believe this display should be corrected.

**Comment by proceps** [comment]
in OSF 'geniculare' is currently classified as a synonym of Conocephalus (Anisoptera) semivittatus vittatus. So its current rank is the same as the rank of valid taxon - subspecies. Its parent is the same as the parent of valid taxon - Conocephalus (Anisoptera) semivittatus. The current name of the taxon is correct.

**Comment by typophyllum** [comment]
This seems to be a result of the weird display of synonyms. _Gomphocerus simillimus_ (never cited in the rank of subspecies) is a synonym of _Aeropedellus variegatus variegatus_ (protonym _Gomphocerus variegatus_, the two most recent citations which confirm this are missing, since the import algorithm fails to resolve trinomial subspecies names). It doesn't make any sense to call this synonym _Aeropedellus_ [SPECIES NOT SPECIFIED] _simillimus_ instead of simply displaying to protonym _Gomphocerus simillimus_.

![grafik](https://user-images.githubusercontent.com/33210201/98053374-322fb300-1e17-11eb-966a-d24a7fba8cc5.png)

**Comment by typophyllum** [comment]
Looking at OSF data in TW, MMCigliano and I keep getting confused by the synonym names appearing in unknown combinations. I think there needs to be at least an option to customize Browse OTUs so that the original combination/protonym is shown, as is standard in practically all taxonomic publications.

The Code, in the context of homonymy, speaks explicitly of published combinations:

53.3. Homonyms in the species group
Two or more available species-group names having the same spelling are homonyms [...] when they are subsequently **published in combination** with the same generic name (secondary homonymy)

57.3. Secondary homonyms
57.3.1. Identical species-group names established for different nominal taxa and subsequently **brought together in combination** with the same generic name are secondary homonyms [Art. 53.3] and the junior is invalid

**Comment by mjy** [comment]
I'm not sure if this is a data migration issue, likely not, but, in the short term:

* Think of this page as debugging only.
* For now, just like in browse nomenclature when you see a yellow background you should immediately jump to the valid protonym/Otu to get a proper view of this name's history (if that is you intent). @jlpereira we need a link 'Valid' up in the yellow to do this (let me know if you don't have this metadata).
* We might also consider a 'redirect to valid' mode, as we do for the taxon name autocomplete, this would "prevent" you from reaching these pages during typical viewing, but not eliminate them (they have their use).

**Comment by typophyllum** [comment]
It's not a migration issue but a strange peculiarity of TW. And I want to be able to view each synonym with its corresponding citations separately.

**Comment by mjy** [comment]
@proceps Should we just display original combination for yellow names?

**Comment by proceps** [comment]
It is just title, we can display original combination in the titles. But the taxa will still be listed under the valid genus name in the classification and few other places. And that cannot be changed. Than we will have an issues with OTUs attached to the synonyms. Which name you want to see in association whith the OTU? Current or original? I think, the best would be to modify the tytle to something like this: "Taxon1 (original combinaition) synonym (combination, etc) of Taxon2 (current combination)". That should definitely eliminate confusion.

**Comment by mjy** [comment]
Very good point @proceps, i.e. we need to emphasize this is a *taxon* (biological) page, that happens to contain nomenclature.

**Comment by mjy** [comment]
What about: `OTU Aus bus Smith, 1920 currently OTU Bus bus"` ?

**Comment by proceps** [comment]
OTU "Aus bus Smith, 1920 currently OTU Bus bus (Smith, 1920)" Add the author string, and do not include OTU in the name. This should be full name for any OTU.

**Comment by mjy** [comment]
Do you mean this?

`"Aus bus Smith, 1920 currently Bus bus (Smith, 1920)`

**Comment by proceps** [comment]
Yes

**Comment by proceps** [comment]
This should also work even for valid names, which has original combination different from current.

**Comment by mjy** [comment]
Was thinking that valid names would just be presented as is?  Do we need the original?   If we argue for original in that case we need 2x the original (invalid and valid could be different)

**Comment by proceps** [comment]
We will have two different OTUs if besides a protonym thereis a subsequent combination in the DB. Than you will have two forms. We already discussed it. The OTU should always be linked to the original combination of the protonym. This will resolve all the confusions.

**Comment by proceps** [comment]
Distribution, for example, could be attached to the subsequent combination, you will get a citation of the exact name use. And all distribution records for synonyms and combinations could be summarized to the valid name on the OTU page

**Comment by mjy** [comment]
I'm not sure I understand.  OTUs can be linked to any name, that will not change.   If you mean that:

1) In the label for the OTU
2) The original combination should be present when the name is not valid or current

Then I agree.

**Comment by proceps** [comment]
github.com/SpeciesFileGroup/taxonworks_doc/blob/master/manuals/OTU_BEST_PRACTICES.md

**Comment by proceps** [comment]
First portion of the OTU name will not change (original combination). The second half always changes to match the current taxonomic position.

**Comment by mjy** [comment]
Let's please add all possible combinations of data and their corresponding label renderings  *in taxon (biological)* pages here (if they happen to work for general OTU labels we can expand the use, let's keep focused for one use case).

https://docs.google.com/spreadsheets/d/19RIWCvq9zo1hu47nR99nF8X6_8NwO08eUPWrfMaLkjg/edit?usp=sharing

Please do not alter labels but rather provide alternates.

**Comment by mjy** [comment]
I know we have the theory worked out, this is a coding issue- providing exact strings and their corresponding labels (for all possibilities, regardless of best practices) will faciliate @jlpereira actually executing this. I've updated spreadsheet column headers to better reflect the possible considerations.

**Comment by MMCigliano** [comment]
> Should we just display original combination for yellow names?

Yes, please. We prefer to see the original combination for synonyms, without any other automatically created combination.

**Comment by proceps** [comment]
@MMCigliano, Unfortunately this would not satisfy my need and needs of some other people. It will be confusing, if I know that I expect to see the synonym species in a particular genus, but instead I will see it with very old historical combination, which does not even have any sense now.

**Comment by typophyllum** [comment]
Perhaps the name could be removed from the hierarchy at the top of the page. Then is would be obvious that 1) the name is a synonym and 2) it is under a valid species. MM and I find the artificial combinations totally confusing.

**Comment by mjy** [comment]
Let's please keep this specific.  I'm closing this issue and opening two others.  1) Browse OTU label; 2) Browse nomenclature label.  The two are not the same.  I will re-summarize on the open issues.
