### ISSUE TITLE
Task - Descriptor filter

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1726]
As a curator I want to filter descriptors based on various properties.

* [ ] Create filter lib

* [ ] Descriptor type
* [ ] Image presence/absence
* [ ] In/not matrix
* [ ] Observation count use range (sliding scale, 1 2-10, etc.)
* [ ] User facet
* [ ] Tag facet
* [ ] Citation facet

**Comment by debpaul** [comment]
See more discussion #2802, so closing this one.
