### ISSUE TITLE
Export fields for dump Opiliones Catalogue

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1730]
Consider this logonymic structure:
![image](https://user-images.githubusercontent.com/46284943/93005447-54980500-f527-11ea-96c7-bb3ae54b0c2c.png)

The current CoL export CSV files do NOT contain all needed info to retrieve this logonymy (only part).

For my World Catalogue of Opiliones I needed the following:

(1) ID of protonym Lacinius horridus + some info stating this is the accepted name for the taxon + info saying that Phalangium is the original genus;
(2) ID of Panzer 1794 as orig. source of (1) + page/figs number;
(3) ID of _combination_ Lacinius horridus + ID of Thorell 1876 with page (which is where this particular combination was proposed) -- and this is not a chresonym, at least in the usual Dubois (2000) sense, but an aponym;
(4) The same information as in (1) for Opilio hispidus;
(5) ID of source (where the synonymy was proposed) + page.

How should I proceed?

**Comment by mjy** [comment]
Essentially what you're asking for is what the API (https://api.taxonworks.org/) serves, in little pieces. 

To sideswipe slightly- are you trying to replicate everything you see in this history?

**Comment by adrik29** [comment]
Uh, yes, I thought I could replicate what I have in TW so I can get a catalogue...
Is this incorrect?

**Comment by mjy** [comment]
To be pedantic the CoLDP export may not have what you need for the catalog (bet see below).   Remember- it is a standard that is a subset of the functionaly of the semantics in TW, i.e. a lossey format.

However, @gdower and I will look into your question- at first glance I think the data are there, or, if not, they should be and perhaps we have an error.

Now a seperate question- what if we rendered, as Markdown (could be converted to HTML by your developer) the catalog as you see it, and made it available, would you use that?

We also plan to dump non-linked paper catalog versions as well (#1473).

**Comment by adrik29** [comment]
Thanks, Matt.
I took a look at the CoL exports and couldn't find some features for the logonymy.

The current version of WCO-Lite (https://wcolite.com/) is only a first layer, stripped almost to bare bones (see the parts called "coming soon"), that's why we could use the format of CoL so easily. You file **Synonym** provided parents so Ian Kury could build his tree.

1) WCO-Lite was developed to read into your CSV files, I suppose any other format would entail considerable reworking, especially because it is not a copy of a list, and there is also the hierarchical taxonomic tree.

2) If you really add a button "print catalogue" or something like that, I would seriously rethink the way I work, and would start using TW as my primary source. Currently I have a huge manuscript which I'm gradually moving into TW.

**Comment by mjy** [comment]
Of course the only reason to work hard to get data in is to do it *before* you need to publish, so that publishing becomes easier. ;)  Retroactive work is not nearly as rewarding.

We have a lot of work todo to find a balance where one can take the data, and produce their own product- your wcolite is truly pushing this forward, but in time it will become much easier, and more unified approaches will emerge. It will indeed need to co-evolve with the core.

A side note- in fact the core model for nomenclature in TW is not a tree, but rather a graph/network.  Looking at the data from the parent perspective is just one way it could be done, albeit the most famliar.  Even so work that assumes that the hierarchy is the core will miss some of the underlying power of what is possible.  This is obtuse/abstract, but perhaps worth mentioning.

**Comment by adrik29** [comment]
Thanks for the insight. I'll make sure to discuss that with my coder/kid when he's back from whatever...
Integrating all that stuff is the ultimate goal -- users will look at the species name, they'll have the PDFs of the publication at on-click distance, and they'll be able to see geographic distribution, museum holdings, whatever.
For now, I only wish an online catalogue, with all synonyms, homonyms and combinations, biblio references and their pages... Later, who knows?

Retroactive work = I have a highly advanced manuscript, but things are changing very fast. With the publication of the interface online + an eBook with some necessary nomenclatural corrections... All of that is happening like lightning. I have barely time to think it over...

**Comment by mjy** [comment]
And we barely have time to adapt to users needs.  BUT, taxonomy is a long, slow process, so we need not get too worked up about timeframes.

**Comment by mjy** [comment]
@adrik29 can we close this issue now?

**Comment by adrik29** [comment]
Sure. We'll reopen if necessary.
