### ISSUE TITLE
pdf page mixing

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#1733]
**pdf page mixing**

**To Reproduce**

In filter sources, when pdfs are opened sequentially, it is still not clearing the old pdf and it mixes up the pages as well (as before).

<provide a screenshot>

<img width="602" alt="Screen Shot 2020-09-15 at 11 29 00 AM" src="https://user-images.githubusercontent.com/30123556/93250181-488a8e00-f747-11ea-8ebb-2b157b64e605.png">
- Production

**Comment by mjy** [comment]
@JohnHeraty this is fixed in a pending release I think, correct @jlpereira?

https://github.com/SpeciesFileGroup/taxonworks/blob/development/CHANGELOG.md#fixed

**Comment by jlpereira** [comment]
Yes, fixed but not in production yet.

But leave this one open, we will ping you @JohnHeraty when you can test it

**Comment by jlpereira** [comment]
@JohnHeraty should be fixed in production now. Let me know if the problem persist

**Comment by jlpereira** [comment]
Already tested and it seems to works fine for me. If you see this problem again, reopen the issue @JohnHeraty
