### ISSUE TITLE
Add pdf icon after each citation

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1734]
Add function:

Would it be possible to add icon to open specific pdf directly from the screen where specific citation appear?
![Screenshot from 2020-09-16 06-59-43](https://user-images.githubusercontent.com/58753011/93347702-39a8e780-f7ea-11ea-94bc-8708874b019e.png)

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production

**Comment by PJansta** [comment]
Sorry, it is issue for the production.

**Comment by proceps** [comment]
implemented as a radial annotation button in the list of references.
