### ISSUE TITLE
Alt "H" -> in Linux the takes you to "Help" menu, not hub?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1738]

**Comment by LocoDelAssembly** [comment]
Seems to be Firefox only? When pressing `Alt-H` I'm redirected to the hub but also the help menu of Firefox is displayed (can't provide a screen capture because it goes away when taking it)

**Comment by mjy** [comment]
@PJansta can you comment as to the browser?

**Comment by PJansta** [comment]
Yes, it is problem in Firefox only. The Chrome seems to work well with ALT + H
