### ISSUE TITLE
Check that all #cached_* setters use a reasonable and identical pattern

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#174]
* individual setters should use `update_column()` (always?)
* cached setters should (always?) fire `after_save`
* objects with multiple cached values should have all setters wrapped in a single method (`set_cached` ?)
* the cached setter method should be identically named in all models (`set_cached` ?)
* cached setters should only fire if data being cached have actually changed (is_changed or related?)

Models with cached values:
* TaxonName
* Source
* Person
* Identifier
* Descriptor
* Observation
* CollectingEvent

**Comment by TuckerJD** [comment]
TaxonName:
* cached
* cached_html
* cached_secondary_homonym
* cached_secondary_homonym_alternate_spelling
* cached_original_combination
* cached_primary_homonym
* cached_primary_homonym_alternative_spelling
* cached_classified_as

**Comment by mjy** [comment]
Outstanding are CollectingEvent and Observation.
