### ISSUE TITLE
As a curator I want fast access to the PDF popup in some locations of the browse nomenclature

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1742]
What todo specifically is the question.  Simplest might be to add PDF link to references cited list.

**Comment by jlpereira** [comment]
If you're looking the possibility to open the pdf viewer just clicking a link, this is already possibly. Perhaps would be nice create a helper to use on rails views. The import thing is provide a data attribute:

```
<a data-pdfviewer="<url>">Open this pdf</a>
```

Example:

```
<a data-pdfviewer="/system/documents/document_files/000/000/321/original/dummy.pdf?1598974483">View</a>
```

Link or cicle button beside the citation should be fine

**Comment by mjy** [comment]
Thanks!

**Comment by jlpereira** [comment]
Already implemented for other issue:

document_viewer_button (document)

**Comment by proceps** [comment]
implemented as radial annotator next to each source.
