### ISSUE TITLE
List of Identifiers

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1745]
Isn't the list of identifiers for a given project working?
Has it ever worked or is it just a planned feature?

**Comment by adrik29** [comment]
![image](https://user-images.githubusercontent.com/46284943/93488516-d77cdf00-f8dc-11ea-8312-f7270dfc5633.png)

**Comment by mjy** [comment]
Real bug, thanks for reporting.  Fix in next round.  This is because some Wikidata identifier is causing a problem.

**Comment by mjy** [comment]
This is fixed, coming soon to live.
