### ISSUE TITLE
Forced classification of incertae sedis

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1751]
I'm not sure, but I guess **it is a bug**.
Genus _Biconibunus_ was originally in family Phalangodidae.
Later it was classified as suborder Laniatores incertae sedis.
Still later it was re-classified as infraorder Grassatores incertae sedis.
But TW doesn't let me put this new classification, as if classifying _Biconibunus_ in Laniatores was written on stone:

![image](https://user-images.githubusercontent.com/46284943/93663987-f21c9880-fa41-11ea-93b2-bca2823dff42.png)

**Comment by proceps** [comment]
Yes, it is intended. Incertae sedis always match with the present parent. If the parent changes, this means that the taxon is not incertae sedis any more. For historical placements there is different relationship: source_classified_as. This allows to save as many historical placements as you want. If you would like to change the parent, but preserve older incertae sedis relationship with its citations, you can edit the relationship and change the type to "classified as". There is also no restriction combining incertae sedis with multiple "classified as" relationships.

**Comment by mjy** [comment]
@proceps Please add notes to taxonworks_doc if scenario isn't outlined
there.

**Comment by adrik29** [comment]
Thanks, Dmitry, just to see if I got it:
_Biconibunus_ older (historical) classification in Laniatores should NO LONGER contain "incertae sedis"?
So, the tag incertae sedis should only be used in the current assignment to Grassatores?

**Comment by adrik29** [comment]
Like this?

![image](https://user-images.githubusercontent.com/46284943/93671273-ff547a00-fa77-11ea-98fd-45c625f9828b.png)

**Comment by proceps** [comment]
Yes, this is correct. I usually also put the citation on incertae sedis, just to remember who established this relationship

**Comment by adrik29** [comment]
Thanks a lot, Dmitry, I will complete the citation and try to follow this pattern.
