### ISSUE TITLE
Asserted distribution - spatial click to select [Was: Aliases for geographic areas?]

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1754]
I understand the need for controlled terms for geographic areas.
Those have to be chosen from among the children of larger areas.
But there could have been options, because it is not always easy to locate the exact name of the area as used in TW.
For example Bosnia and Herzegovina are listed as Bosnia-Herzegovina only. So I copy-pasted the name of the country and got nothing. We should be able to enter either and yet to get the same result.
![image](https://user-images.githubusercontent.com/46284943/93695125-aae9e280-fae9-11ea-93a0-b9a8d58eacbb.png)

Another example: 
Mount Athos Autonomous Region in Greece = https://en.wikipedia.org/wiki/Mount_Athos
It is also know as Agion Oros (Άγιον Όρος, 'Holy Mountain'), but in TW it is misspelled as "Ayion Oros" (perhaps because the Greek letter gamma is similar to Latin letter Y). It would be useful to have it also listed as Mount Athos for example. So whenever someone typed athos it would appear. I don't know if this is a propagation of an old misspelling from whatever source used.
![image](https://user-images.githubusercontent.com/46284943/93695067-11223580-fae9-11ea-95c7-184190a0fed3.png)

**Comment by mjy** [comment]
@adrik29 within TaxonWorks our philosophy and approach is to focus on the spatial representation forthe distribution.,  The spatial assertion will let us ultimately calculate the string (label) for our assertion in any language, spelling, controlled vocabularly, provided our spatial assertion matches an external spatial assertion. 

The gazetteers loaded are all external, and all the spelling comes from external sources.   We certainly do not want to be in the buisiness of managing gazeteers, they come an go, and they overlapp, and if you think nomenclature is crazy, try managing ungoverned systems of geopolitical names.

This is a long way of saying we need a new function that let's you select a gazeteer entry by spatial click.  This functionality exists in the "New asserted distribution by map".  If we "modernize" (in code) that functionality into our other tools we will be able to "adhere-to" the spatially centric philosophy in TW.  The function works by finding all areas that enclose the point clicked on, and lets the user resolve to one of them.

**Comment by mjy** [comment]
* [ ] ensure JSON api exists
* [ ] Integrate ... where? Probably a compact component/tab on the Geographic Area smart selector

**Comment by adrik29** [comment]
Thanks Matt!
There are functions I'm not sure sure we already have in TW:

(1) Can I for example display on a map all areas for all species of the family Assamiidae from Indonesia?

(2) Or even without the map, can I have a checklist for Indonesian Assamiidae based on what I already have in the database?

(3) And are we sure that the children areas propagate onto parent areas?
For example, if I mark "Occitanie", does it spread up to France and up to Europe? How/where can I see it?

**Comment by mjy** [comment]
3 - yes, if spatial asseritions then they can propagate up.

You will most definitely be able to report this data. Some of this is coming in the Browse OTUs improvements (in fact most will show there first).

However, right now there is no unified filter for this, I added a new task:https://github.com/SpeciesFileGroup/taxonworks/issues/1756

**Comment by adrik29** [comment]
That sound great -- I'm anxious to see all geo-things.
I'm still struggling with this -- they are a bit concealed in TW.

**Comment by proceps** [comment]
Adding alternative valued to gazetteers an adding alternative valued to autocomplete will significantly improve the search: #1434

**Comment by mjy** [comment]
And it will significantly increase the curation overhead.

**Comment by proceps** [comment]
At the moment, I know few examples which are extremely difficult to find. Like this one Bosnia and Herzegovina. or "Democratic Rep. of Congo". I already know that it is abbreviated. But I would just add an alternative value to know. Or cases like Formosa/Taiwan. Actually, only few names are required updates. One of the most problematic one is actually France, which includes all the island territories if you select it, and you get complete distortion of the species distribution.

**Comment by proceps** [comment]
The best, actually, if we could add a mechanism to combine synonyms, at least mark them in the database and hide them. I know that we calculate distribution spatial, and it does not matter which one I select, and from which gazetteer. But the think is, when I am using search box, and I have to select from the list, every time I have to think twice, which one I should select. I would rather spend some time to mark the synonyms. In fact, any given project operates only with few hundred geographic areas, it should be relatively easy to clear the lists.

**Comment by mjy** [comment]
I see the argument, I'm not sure I completely buy it.

If like you say most areas soon make it into your project, and they are limited, then you will see that information in the autocomplete, and it's easy to decide which ones to pick for the majority of your use cases.  Therefor we are talking the (small minority) of edge cases.  We already have one mechanism for this small list- add the geographic area to your pinboard if you've taken the time to figure out it's important for your project.  I'm suggesting two others- 1, the click to pick on map mechanism in the smart selector, and 2, we could add a find by Tag option in the smart select (you tag your set, we lay them out alphabetically or some such).

What happens when we add a completely new gazetteer?  Are you willing to map everyones abbreviations, deciding all over again what matches up label wise?  I personally am not, because it's not worth the time.... when you have the spatial assertion at the heart.

**Comment by adrik29** [comment]
I hate that they didn't keep Zaire -- it was a most memorable name, much better this DRC which creates a mix-up with Congo. Many horrible dictatorships bear names starting with "Democratic Republic" or something similar. I understand that they wanted to get rid of the memory of the cruel tyrant, but Zaire was good and DRC is an unlucky name.

In my experience, looking up names in TW is not simple, I often have to go to the parent area and look at the children to learn which alternative spelling we are using. 

If I type "demo cong" it won't find the right one, because it is "Dem. Rep. Congo". Even the smart auto-complete cannot find what is not there.

And one good practice is to always choose whatever is already in your project as we do with author names for example...

**Comment by adrik29** [comment]
When people create name they are not always sensible.
The stupid people of my country took the state called Mato Grosso and divided in into: Mato Grosso + Mato Grosso do Sul in 1975. Therefore creating a homonymy. We have always to check to see of which Mato Grosso the author is referring to. Couldn't they have called them Northern and Southern?

**Comment by mjy** [comment]
Back to "Combine synonyms".  We did combine synonyms. We determined identity by exact string match and identical parenthood, there was now other objective way of doing it across multiple gazetters.  I want to maintain this objectivity as we add more, so that we know the rules will always work the same.  As soon as we allow individual curation, we lose this pattern, and then we'll be dealing with "why is it this way" and trying to remember why humans did it one way or another.

**Comment by mjy** [comment]
>In my experience, looking up names in TW is not simple, I often have to go to the parent area and look at the children to learn which alternative spelling we are using.  

But if you went to a map, clicked where you meant, saw shapes, then you could pick a record that represents what you want to assert, right?

**Comment by adrik29** [comment]
@mjy  -- yes, Matt. This is a clever tool.
And by my own experience I know that if you start to relax controlled terms it gets real murky real fast, with each one contributing his whimsical 2 cents.

**Comment by proceps** [comment]
> If like you say most areas soon make it into your project, and they are limited, then you will see that information in the autocomplete, and it's easy to decide which ones to pick for the majority of your use

This is only if you remember how exactly to spell the name of the area, quite a few names (not many) are not spelled correctly in either of gazetteers (Dem. Rep. Congo) is one of the examples. Possibility the map to select a geographic area, is also not a strait forward way, and definitely not very efficient. For a new collecting event, if you collected yourself, yes it is a great way to do it, but for asserted distribution. I am not sure I can click every single state in US, definitely not all 50 of them, I am not even saying for all countries in Europe or Asia. And even if the map zooms and displays the name, typing the name in the search box is much faster option than exploring the map.

**Comment by mjy** [comment]
You use the click when you then name doesn't work (i.e. never for any state, etc.)- which should be for a tiny fraction of the areas of interest.  For everytime you spent a minute figuring somethign out, pin it.  Very shortly you'll be wasting very little time relative to the time you spend deciphering what the paper meant.

**Comment by proceps** [comment]
Pinning is great, but it is just for myself. I mentioned France before, I know what is the difference of France in different gazetteers, but I also have students working with me (and of cause I have few option of France recorded in the database, about half of them incorrect), It is hard to envision all problematic areas and pin them for every single person in the project. Yes, I know the ways around, and it does not bother me much. Except for probably just one Sardinia, which is recorded in gazetteer only as Sardegna. Very obvious. And I do not know Italian. The problem starts when I need to teach a student how to find a proper geographic area. And you know for a student there is no difference between France with all territories and without. It is the same. Even if you visualize it on the map. The question is only what could be done to simplify the work for everyone.

**Comment by mjy** [comment]
Tagging seems to be a potential solution, especially if we can limit include somethign in the autocomplete `t!my_places Sardinia`, emulating the powerful "bang" feature of Duck Duck Go that routes/parameterizes things based on single letter + '!' + varaible <then search term>.

**Comment by debpaul** [comment]
@adrik29 wrote:
> Mount Athos Autonomous Region in Greece = https://en.wikipedia.org/wiki/Mount_Athos
> It is also know as Agion Oros (Άγιον Όρος, 'Holy Mountain'), but in TW it is misspelled as "Ayion Oros" (perhaps because the Greek letter gamma is similar to Latin letter Y). It would be useful to have it also listed as Mount Athos for example. So whenever someone typed athos it would appear. I don't know if this is a propagation of an old misspelling from whatever source used.

Hm. It looks like (at some points in this ticket) we are also talking about transliteration. 
- [ ] Perhaps we can use Wikidata to help with this? 
- [ ] Future, look into using BELS (geo gazetteer being built right now).
- [ ] How does this issue relate to capturing "verbatimLabel" of the place?

**Comment by proceps** [comment]
As a first stap, I would like to have annotatons on geographic areas. So that I can provide alternative spellings to few places which I have problem finding.

**Comment by mjy** [comment]
Closing this as resolved in part (smart selector for areas).  Remainder is pertinent to future `Gazeteer` model in part.  Specifics can be added as individual issues.
