### ISSUE TITLE
Pdfs mixed up

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1760]
Pdf of some of Sellenschlo papers in TW are mixed up and one pdf includes pages of another pdf 

For example the pdf of Sellenschlo, U. 1979. Untersuchungen zur Taxonomie und Biologie europäischer Torymidae (Chalc., Hymenoptera).Dissertation Zur Erlangung Des Doktorgrades Des Fachbereicher Biologie Der Universität Hamburg. 302pp, 33 pls.

include some pages of pdf of Sellenschlo, U. & Tröger, E.J. (1993) Nachweise von Erzwespen der Unterfamilie Hybothoracinae (Hymenoptera: Chalcididae) in Deutschland Parastioide bei Netzflüglern (Neuroptera). Entomologische Zeitschrift, Frankfurt 103(11), 207–210. [1993]

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
![Screenshot from 2020-09-22 05-11-13](https://user-images.githubusercontent.com/58753011/93880265-0eaf0f80-fc92-11ea-9b7f-fd290a5b9366.png)
**- Production**
Browser: Firefow

**Comment by jlpereira** [comment]
@PJansta this is a know issue and its already fixed, but not yet on production.
Duplicate: https://github.com/SpeciesFileGroup/taxonworks/issues/1733
