### ISSUE TITLE
Selection of citation

### ISSUE THREAD

**Issue by PJansta** [SpeciesFileGroup/taxonworks#1761]
If you select some citation in Filter Source (here for example some of Sellenschlo citation) and display as BibTeX, then it gives you the same result if you unselect all (either manually or using the button "Unselect all), select different one and display as BibTeX. You will get the list of citation from previous selection...

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***

- Production
- Browser  - firefox
![Screenshot from 2020-09-22 05-23-15](https://user-images.githubusercontent.com/58753011/93881434-bf69de80-fc93-11ea-855b-ea30dcb15305.png)

![Screenshot from 2020-09-22 05-19-29](https://user-images.githubusercontent.com/58753011/93881059-41a5d300-fc93-11ea-9f67-8128ee7ed099.png)

**Comment by mjy** [comment]
Blocked by need for for param `id[]=`.
