### ISSUE TITLE
DWC Import - getting imports to match current namespaces unclear/not possible

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1765]
Problem
I do not understand how to get namespace and catalog number to match with what is currently in database. E.g. if I have the INHS Insect Collection namespace, where does that go in a DWC import?

Right now it seems to create it from the collectionCode, then adds a "-". We need the text there to match with a current namespace in the system rather than creating it's own. 

Basically, I will almost always want to import into an already created namespace, not create a new one. The semantics for that need to be SUPER clear. 

Example of what is currently created in sandworm when importing a new record: 
![image](https://user-images.githubusercontent.com/11411328/93932884-742ceb80-fce6-11ea-8799-92c672bdd2a1.png)

Current namespace already in there: 
![image](https://user-images.githubusercontent.com/11411328/93932930-860e8e80-fce6-11ea-933d-b8d601b95f65.png)

Import row:
![image](https://user-images.githubusercontent.com/11411328/93933616-85c2c300-fce7-11ea-9baa-9eb42153487e.png)
![image](https://user-images.githubusercontent.com/11411328/93933681-9bd08380-fce7-11ea-8c3a-56227cc24c79.png)
![image](https://user-images.githubusercontent.com/11411328/93933751-bdca0600-fce7-11ea-9116-0b3ae08ca464.png)
![image](https://user-images.githubusercontent.com/11411328/93933815-d5a18a00-fce7-11ea-9cb1-923733a6b11e.png)

**Comment by mjy** [comment]
@tmcelrath Can you lease post the import row in these cases as well?

**Comment by tmcelrath** [comment]
@mjy added

**Comment by mjy** [comment]
This is also getting add what mode we initially want to use.  I think it's likely "Strict", where we have to match certain things, rather than create-anew.  This might be more cumbersome intiially, but ultimately might be our quickest way to getting the feature live.  But I'm not sure.

**Comment by LocoDelAssembly** [comment]
Current matching for namespace is checking whether one with short name formed by institutionCode-collectionCode exists, if it doesn't then it is created and the full name is appended with "[CREATED FROM DWC-A IMPORT IN `<TW project name>` PROJECT]".

Given that unique institutionCode:collectionCode pairs shouldn't be a large number I'm leaning towards disabling this behavior and requesting users to explicitly map namespaces before allowing import of the record.

**Comment by mjy** [comment]
@LocoDelAssembly I second the requirement of explicit namespace map prior to import.

**Comment by tmcelrath** [comment]
@LocoDelAssembly @mjy thirded(?) the requirement of explicit namespace map prior to import.

**Comment by LocoDelAssembly** [comment]
This feature is available through Settings button. When namespace is selected, affected rows transition from NotReady to Ready.

**Comment by tmcelrath** [comment]
Looks good to me and it works for me on import. I think we can mark closed?

**Comment by mjy** [comment]
@jlpereira I think there is a minor bug where the current pages of records is not re-checked, page needs reload?
