### ISSUE TITLE
Help - DWC Import

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1766]
I proposed that we need new help guides on the DWC import that show us where different fields will get imported:
1) Click on the help tab
2) Each of the fields in your dataset to be imported are highlighted.
3) Hovering over/clicking those fields would tell you the data table and field that this will be imported to/created in.

**Comment by tmcelrath** [comment]
https://docs.google.com/document/d/1u9yXhThghCR6_seq-sLUHQ0-KGuCZFPwAimlceQy4ss/edit?usp=sharing - SOP for Using this task in the INHS Insect Collection.

**Comment by debpaul** [comment]
@tmcelrath is this done yet to your satisfaction?

**Comment by tmcelrath** [comment]
Yeah looks great!
