### ISSUE TITLE
New feature request - Add Importer for non-DWC fields on collection objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1773]
I would like, after adding a DWCA for Occurrence Records, to be able to drag an additional CSV or another table with matching catalog numbers or occurrence IDs, but with additional fields that are only present in TaxonWorks. Notably, I would like to be able to add "Buffered Determinations", "Buffered Collecting Event", and "Buffered Other Labels".

This would function as a two-step process, First (required) step would be to add the DWC and check for import issues, Second (optional) step would be to add the above file for just those fields.

**Comment by LocoDelAssembly** [comment]
This could be solved as a DwC-A Extension problably? https://tools.gbif.org/dwca-validator/extensions.do (not particularly suggesting it must be registered there, but I mean using this mechanism)

The importer currently supports staging extensions, but development is concentrated on importing core table only (and so the UI, that is why it is not visible, but the database actually has the extension records stored for those DwC-A records having them).

**Comment by LocoDelAssembly** [comment]
Forgot to mention: Extension data does not require a separate table, for cases that a core record may have at most one extension record, then the mapping can be made into the core file, that is totally valid and much more Excel friendly (having one sheet per extension and linking by ID would probably be a nightmare for users).

**Comment by tmcelrath** [comment]
@LocoDelAssembly That mechanism works for me. IF we can make it simpler and put it in one table that is fine with me. I don't see it being too hard for users to have it as a separate table, but one table would certainly be easier.

**Comment by mjy** [comment]
@LocoDelAssembly discussed this a little further.  If we move to handle extensions then this would be the priority:

`taxonworks:model:field`

* [ ] taxonworks:CollectionObject:buffered_collecting_event
* [ ] taxonworks:CollectionObject:buffered_labels
* [ ] taxonworks:CollectionObject:buffered_determinations

**Comment by LordFlashmeow** [comment]
Is this not implemented now with the `TW:CollectingEvent:<field>` syntax?

eg `TW:CollectingEvent:ElevationPrecision`

**Comment by tmcelrath** [comment]
Yeah I think so. @mjy @LocoDelAssembly got any code commits to add to this for reference when closing?

**Comment by mjy** [comment]
Documented here: https://docs.taxonworks.org/guide/import-and-export.html#darwin-core-archive-dwc-a-import.
