### ISSUE TITLE
Deprecate Task Import Penn-State DWC-A 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1774]
Functionality superceded by new importer.

**Comment by debpaul** [comment]
@mjy  Does Penn-State Andy Deans know how to use this (or need to know how to use this for his current Frost Museum data pipeline into TW workflow)?

**Comment by mjy** [comment]
This is replaced with DwC import.  This issue is so that I remember to remove the old task.
