### ISSUE TITLE
DWC Importer - RecordedBy does not add collectors in created CE table

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1776]
**Describe the bug**

When I have "recordedBy" in my DWCA for import - no collector is added

**To Reproduce**
1. When I have a DWC with collector indicated using the "recordedBy" DWC term
2. Then I import a record.
3. And I look at that record in comprehensive.
4. No collectors in either verbatim Collectors or in parsed "Collectors" people table. 

Result of DWC Import:
![image](https://user-images.githubusercontent.com/11411328/94315511-421ac400-ff48-11ea-8768-6e267b5ffa46.png)

Screenshot of DWC Import Screen (note "recordedBy" field is filled in:
![image](https://user-images.githubusercontent.com/11411328/94315537-5068e000-ff48-11ea-8951-5ff6f447e303.png)

**Expected behavior**
recordedBy should fill either "verbatim Collectors" or the parsed "collectors" field in the collecting event table that is created as a result of an import. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandworm (McElrath DWC Test Project)
- Chrome

**Comment by mjy** [comment]
@tmcelrath What's the exact wording on recordedBy? 

Thinking down the road does it best match up with CE, what about the person who creates a verbatim CollectionObject, but no CE?

**Comment by tmcelrath** [comment]
"A list (concatenated and separated) of names of people, groups, or organizations responsible for recording the original Occurrence. The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first."

**Comment by tmcelrath** [comment]
I think recordedBy is about recording the original occurrence, not creating the digital record. Two different things.

**Comment by tmcelrath** [comment]
There is nowhere to put "digitalRecordCreatedBy" in DWC. But that would be covered by proposed attribution expansion to DWC through certain agent strings if I remember from this weeks meeting.

**Comment by LocoDelAssembly** [comment]
> "A list (concatenated and separated) of names of people, groups, or organizations responsible for recording the original Occurrence. The primary collector or observer, especially one who applies a personal identifier (recordNumber), should be listed first."
```ruby
    # recordedBy: [Not mapped. NOTE: Collector is included here, but not explicitly mentioned. Review]
```

Because of its definition it is uncertain when parsed what I'm actually getting, and I'm (perhaps wrongly) under the impression that some people may use this for recording authorship of the effort of putting the data in the spreadsheet rather than showing the collector. But even if it doesn't relate to the digital record, it is unclear by the definition that I'm guaranteed the collector will be there and what is the role of other people.

The safer approach at the moment would be to import as data attribute verbatim? (Which ultimately will do for all fields that are left unmapped before merging staged-imports into development)

**Comment by tmcelrath** [comment]
@LocoDelAssembly I disagree. In my experience this is almost explicitly used by the collection community to refer to collector of a specimen. The only reason it is called "recordedby" instead of "collectedBy" is because this also is used by non-specimen based observations such as photographs or iNaturalist. 

I think other users will be surprised/frustrated if this field does not get parsed to, at minimum, the verbatim collector field in collecting event. Honestly it would be better if it also created people in the people table that can get uniquified. 

We can change mapping eventually when new DWC attribution metrics are released, but I think the idea that someone would use this for the person who created a digital record is an edge case.

**Comment by debpaul** [comment]
Yes @tmcelrath [dwc:recordedBy](https://dwc.tdwg.org/terms/#dwc:recordedBy) (had a different name in the past), is as you say, for the person/s collecting or observing the objects. It is not equivalent to the concept of a database field that tracks who created a given database "record." (isn't English fun)?

> @LocoDelAssembly I disagree. In my experience this is almost explicitly used by the collection community to refer to collector of a specimen. The only reason it is called "recordedby" instead of "collectedBy" is because this also is used by non-specimen based observations such as photographs or iNaturalist.

[dwc:modified](http://purl.org/dc/terms/modified) carries the information about when the digital record was last changed. There's no field (that I know of) in Darwin Core, to carry the name or ID for the person creating the digital record in a CMS.

of course, in the iNat sense, isn't the person who makes the observation, by default creating the digital record in iNat? For that case, they are same person, but the concepts are different.

**Comment by mjy** [comment]
Welcome @debpaul :).  We are super excited to have you here.

**Comment by LocoDelAssembly** [comment]
Also in https://scan-all-bugs.org/?page_id=1327 collectors is mentioned to be recordedBy. For demo purposes I added the mapping to be imported as people. However, sometimes it will be wrong and perhaps this has to be yet another thing requiring manual mapping (although way more tedious than mapping namespaces). Or perhaps just import as verbatim and have a separate task to curate verbatim fields converting them into proper models? For parsing fields that contain people I'm using https://github.com/bionomia/dwc_agent , but things like 'Hardy, Andrews & Giuliani' will be parsed as `[{ last_name: 'Hardy', first_name: 'Andrews' }, { last_name: 'Giulliani' }]`, which with my human (?) brain (??) I can tell in reality there are three people there. There is an even worst situation where instead of a person, there is an organization there.

Same issue with determiners (which already uses same parsing mechanism).

**Comment by tmcelrath** [comment]
@mjy @debpaul I like the idea of importing as verbatim and then having a collection-wide task that parses verbatim collector strings to parsed people. But I also like having all the easy ones, if formatted correctly, do both so I don't have too. What about a hybrid approach, import verbatim people, and then also attempt to parse?

**Comment by mjy** [comment]
@tmcelrath I think we need to discuss in digitization meetings.  Certainly you are correct that we likely need "modes", and that SOPs are going to be needed in this flow.  Each option doubles complexity when combined with other options, both for user and developer, so we must be careful.  I'd like to have approaches better outlined before we get something more than the baseline live. 

Therefor, I suspect that mapping to `verbatim_<>` represents the path of least resistance that we might take to get the code live?  In theory it's the least lossey?

**Comment by debpaul** [comment]
> @mjy @debpaul I like the idea of importing as verbatim and then having a collection-wide task that parses verbatim collector strings to parsed people. But I also like having all the easy ones, if formatted correctly, do both so I don't have too. What about a hybrid approach, import verbatim people, and then also attempt to parse?

@tmcelrath I still have much to learn, so I hesitate to weigh in. That said, as Bionomia is ever more complete, and more collectors and those doing IDs have QID or ORCID, along with known aliases stored, the parsing should improve. And, a "collection-wide task" as you suggest, might be great for a CitSci or community-specific (or taxonomic group specific) effort to work on. Many of us find this task "fun" (haha). Note that "volunteers" have already linked over 2% of all names for recordedBy or identifiedBy in GBIF. Quite an accomplishment!

**Comment by tmcelrath** [comment]
This is "Fixed" in that they are imported to people. Good enough for me for a DWC import.

**Comment by LocoDelAssembly** [comment]
Given there exists unify people task, can this be considered solved? Also, dwc-agent received an update recently that solves my example https://github.com/bionomia/dwc_agent/issues/7 (disregard my comment there, I already have code on importer-side to move first_name to last_name when no last_name is found).

**Comment by tmcelrath** [comment]
Solved in my book.

**Comment by LocoDelAssembly** [comment]
On conversation at dwc-agent repo I just learned about `DwcAgent.clean`. Its use needs to be considered.

**Comment by LocoDelAssembly** [comment]
`Person.find_by(attributes) || Person::Unvetted.create!(attributes)` (i.e. find person by attributes collected from parsing the text, if none found then create as an UNVETTED person).

**Comment by mjy** [comment]
Can you strict for the former to those created in this dataset?  I think this default behaviour is going to be dangerous.  For example "Smith" will add things to some Smith, which is going to turn into a missmatch of data that will require some serious puzzling to tease out.

**Comment by LocoDelAssembly** [comment]
Do I have something I can glue to people for this or I'll going to maintain a list in the ImportDataset model?

**Comment by mjy** [comment]
There is nothing right now, but we should think about how todo this, a new attribute (1-time sha?), a seperate Model?  We need todo this in many places, and doing it well would be very good.  

We do have the IsOrigin table (people origin from some Dataset).  The semantics are resonable although somehwat muddy.  It might work but we'd have to flesh out the concern.  Not sure, thoughts?

**Comment by LocoDelAssembly** [comment]
> We do have the IsOrigin table (people origin from some Dataset). The semantics are resonable although somehwat muddy. It might work but we'd have to flesh out the concern. Not sure, thoughts?

Which table is it?

Was now thinking of data attribute using GUID of import dataset. Not sure name of predicate to use and what URI if any.

**Comment by mjy** [comment]
Meh, it's not IsOrigin.  OriginRelationship.  I think we should try using it.    See the concern https://github.com/SpeciesFileGroup/taxonworks/blob/development/app/models/concerns/shared/origin_relationship.rb#L1 for implementation in People.
