### ISSUE TITLE
DWC Import - Georeference Uncertainity not added on import

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1779]
**Describe the bug**
When I have "coordinateUncertainityinMeters" in my DWCA for import - it is not added to the Georeference table

**To Reproduce**
1. When I have a DWC with coordinate uncertainity indicated using the "coordinateUncertainityinMeters" DWC term
2. Then I import a record.
3. And I look at that record in comprehensive.
4. No uncertainty in either verbatim uncertainty or in parsed Georeference uncertainty table. 

Result of DWC Import:
![image](https://user-images.githubusercontent.com/11411328/94317856-cb33fa00-ff4c-11ea-99f4-d057f9d9817f.png)

Screenshot of DWC Import Screen (note "coordinateUncertaintyinMeters" field is filled in:
![image](https://user-images.githubusercontent.com/11411328/94317916-ef8fd680-ff4c-11ea-9f56-b1ac5fa9bf81.png)

**Expected behavior**
coordinateUncertainityinMeters should fill the parsed "uncertainty" field in the georeferences table that is created as a result of an import. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandworm (McElrath DWC Test Project)
- Chrome

**Comment by mjy** [comment]
@LocoDelAssembly this is simply added to `error_radius`  in the georeference, assuming it's in M

You can easily convert units with RubyUnits.

**Comment by mjy** [comment]
Commenting here for lack of a better space.

We should be careful about our interpretation of "verbatim_" mapping.  In TaxonWorks we assert that verbatim_ values are literally 1:1 with text seen on labels etc, NOT interpretted values.  All interpretted values (e.g. 2nd column of CE editor) are added as "typed" values (actual numbers, relationships to other records, etc.).

**Comment by LocoDelAssembly** [comment]
I've added the unit in `verbatim_geolocation_uncertainty`. Comprehensive digitization form says "Geolocation uncertainty in **meters**", but does actually `verbatim_geolocation_uncertainty` imply that? If so I'll remove 'm'.

**Comment by mjy** [comment]
TW `verbatim_` most certainly does NOT imply meters (we need to update the UI if it says such, only m is implied in Georeference).  We have converters coming on my dwc fields branch that take that value and move it to the `error_radius`.

**Comment by LocoDelAssembly** [comment]
Uncertainty is added now but it complains when `error_radius` is greater than 10km (TW core models, not the importer). Why is that limit and what should I do with this? (Current behavior is setting the record as Errored and importing nothing at all of it).

**Comment by mjy** [comment]
Erroring is fine.  The thought was that > 10km error is almost certainly a superficial georeference made up by someone, i.e. the exact provide number is arbitrarily made up.  Statistics will likely just exclude this type of data if looked at carefully in analysis, so a) it's subjective at that point, and b) not particularly useful.  Happy to hear counters.

**Comment by tmcelrath** [comment]
Counterpoint - there are localities that are listed on labels that are not included in the gazetteer or do not fit within the gazetteer definitions that are over 10km. e.g. National Parks, national forests that overlap state lines, etc ... is the 10km limit on specimens where you create a bounding box, or just on points with >10km error added?

**Comment by mjy** [comment]
This error radius only applies to point records.

Our model allows for shape errors, but it's not implemented in interfaces.

**Comment by proceps** [comment]
DWC has fields for coordinates and error radius. We should always return centroid and radius. In case of error shape, we have to return a centroid and error shape. Not sure if GBiF works with error shapes, Not even sure if they use Radius, but having a dot with radius was always considered a good georeference practice. Even when GPS is used, we alway put radius. Practically nobody collect on a single spot (unless it is a trap). 10k was a standard error in INHS insect collection for the points coming from gazetteers. We also have 100k for a county and 1000k for a state. In cases where there is not coordinates, but there is geographic area associated with the record, we still have to provide a centroid point and error radius for the area. That is what GBiF expects from us.

**Comment by mjy** [comment]
Please remember this is an import issue, and the goal is to define the behaviour of the importer in this manual.  It is not about output. We are further talking about a standard, not what somebody wants or needs (although GBIF is the big fish in the pool). 

I'm sorry for the strong language, but 100k and 1000k radius error is crazy, please point to where this is used in real-life geospatial calculations.  Are you OK with your specimen possibly being in an ocean?

Output is done on another branch, and we can discuss what is done there when merged.

**Comment by proceps** [comment]
This is just how original collection database was set up. INHS did not have geographic area field. And if we have label Illinois. It is better to work with centroid of illinois, and error radius, than nothing. Just to know which part of the word the specimen comes from. Definitely geographic_area completely replaces the large error radius in cases like this. There is no question is the data useful or not, the question was to get maximum of the existing data. And yes, sorry, I thought this is export related.

**Comment by LocoDelAssembly** [comment]
Real life example would be ANSP-ORTH at https://scan-bugs.org/portal/collections/datasets/datapublisher.php which has 4,000+ records with uncertainty above 10km and about 2,000+ above 20km. Max value 237997 meters (5 records with "georef batch tool 2017-05-30; GeoLocate" `georeferenceSources`). At sandworm this dataset is in project OrthopNet.

**Comment by tmcelrath** [comment]
Another dataset with clear requirements for (slightly) larger uncertainty than 10k: all of Charles Robertson's specimens (15000k in the INHS Insect Collection), can only be assigned the locality of Carlinville Courthouse, with a "Future collectors may closely approximate this area by staying within 17.7 km (11 miles) of the Macoupin County courthouse" = error radius of 17.7 km from a single point.

**Comment by LocoDelAssembly** [comment]
The initial text opening this issue is solved, but then conversation turned into core models issues (hard validation of maximum distance). It seems it is not possible to split the issue into two so I guess I leave this open?

**Comment by LocoDelAssembly** [comment]
Closing. Please create a new issue if you think TW's core models should change to allow larger uncertainty or if something else needs to be changed.

*(Repopen here in case import-side can do something about this)*
