### ISSUE TITLE
New Taxon Name Task - Relationship Soft Validation 

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#1781]
When exercising with homonyms we created a New Taxon Name: _Jivarus viridis_ by Braun, 2008. This name already existed for another species, _Jivarus viridis_ Ronderos, 1979. So,from the _J. viridis_ Braun, 2008, we create the relationship with _J. viridis_ Ronderos, 1979, **primary homonym**.

Then we create a new name for the Braun species, _Jivarus elegans_ Pocco, 2015. 
From Braun`s _viridis_ species we create the relationship with this new name, **replaced by** _Jivarus elegans_ Pocco, 2015.

![image](https://user-images.githubusercontent.com/63611746/94437716-85f21100-0174-11eb-8a0f-53e77f207e35.png)

And we Edit the relationship of Pocco`s name with Braun`s one. **Nomen novum** for _Jivarus viridis_ Braun, 2008.

In the Soft Validation for this name, for Relationship appears the message: **_Jivarus elegans_ Pocco, 2015 and _Jivarus viridis_ Braun, 2008 are not similar enough to be homonyms. **

![image](https://user-images.githubusercontent.com/63611746/94437876-bd60bd80-0174-11eb-8803-00be0b4b2e82.png)

But as they are not homonyms we wonder what is the Taxon Works program interpretation.

**Comment by mjy** [comment]
If required please provide answer in taxonworks_doc.

**Comment by proceps** [comment]
I will check it, looks like a bug. 
Although, nomen novum relaitionship is not required, Replaced by relationship should resolve the names correctly.
