### ISSUE TITLE
Feature request - multiple DWCA import modes

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1784]
From Brian Fisher:
For import, I suggest three options: Import new records, Update existing records, and Merge imported records.  The Update option matches Cat. Number in the input file to Cat. number in the  Data File, and updates any other fields specified. The Merge option should ignores duplicated Cat. Numbers, and imports only records with unique Cat. numbers.

**Comment by LocoDelAssembly** [comment]
Sigh... Wrote long text, then realized my mistake...

So behavior would be (considering only Cat. No. in selected namespace, should identify other potential sources of identification):

 Mode | Duplicate Cat. No. | New Cat. No.
-------- | ------------------------ | ------------------
New | Error | Import
Update | Update* | Skip
Merge | Skip | Import

\* Means it will change existing data fields in existing model instances with whatever the DwC record has (also creating new model instances where necessary)

Is the table above accurate?

**Comment by tmcelrath** [comment]
That is correct I think. I'll try to pull in the original author to make any comments he has.

**Comment by bpescador** [comment]
looks accurate.  For New Mode, the duplicate catalogNumber(s) should be listed in the report.

**Comment by mjy** [comment]
Closing as out-dated.  We will not be updating or merging records with this UI, the emerging batch-options are the route forward.
