### ISSUE TITLE
CoLDP export - exclude OTUs/names that are species/genus groups but include "super" categories

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1792]
CoLDP likely can't, or won't handle crazyness like Superspecies or SuperSuperspecies (who would want to).  Proposal is to exclude this nomenclature and OTUs from the export.

Crossreference: https://github.com/CatalogueOfLife/data/issues/179#issuecomment-702358293

**Comment by proceps** [comment]
@gdower is it still an issue?
