### ISSUE TITLE
Edit taxon name/Browse nomenclature: synonymize species under species in different genus (parent issue)

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1793]
I added a synonym relationship to _Urubamba urux_ Liebermann 1951, as subjective synonym of _Jivarus americanus_ Giglio-Tos 1898. The soft validation says that it should have the same parent as the latter:

![grafik](https://user-images.githubusercontent.com/33210201/94949347-24ed7480-04b7-11eb-8919-c9acc8911880.png)

How do I do this? Simply edit _Urubamba urux_ again and change the parent to _Jivarus_? This is a little bit confusing, since the parent is the species _J. americanus_ and the combination "_Jivarus urux_" does not exist (perhaps same as #1722).

And "original publication is not selected" is also a little bit confusing, since the name has author and date. When I try to edit the citation to check "is original" this message appears:

![grafik](https://user-images.githubusercontent.com/33210201/94950752-81519380-04b9-11eb-92af-db587d8414a5.png)

**Comment by proceps** [comment]
for Urubamba urux.
1. The parent should be Jivarus
2. Original genus should be Urubamba
3. Original publication soft validation message points not to the taxon_name, but to the synonym relationship. TW asks to provide a  citation of the source where synonymy was established.
For references, please use:
https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/manuals/NOMENCLATURE_BASICS.md
and
https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/faq/nomenclature.md
