### ISSUE TITLE
Edit Descriptors

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#1797]
**Describe the bug**

When I navigate to the observation matrix hub I see recently created descriptors. When I click one the browser moves to the "create new" page rather than the previously generated descriptor. 

**To Reproduce**
1. log in and click "Observation matrix hub"
2. Then I see "Recently created descriptors" on the right
3. And I click one of them ("monothalamous" in the attached screen shot)
4. I then go to the form to create a new one, rather than seeing (and being able to edit) the old one

<img width="1176" alt="Screen Shot 2020-10-06 at 10 57 45 AM" src="https://user-images.githubusercontent.com/8043009/95219182-15c23b80-07c3-11eb-8b31-12589a89983c.png">

<img width="1182" alt="Screen Shot 2020-10-06 at 10 58 54 AM" src="https://user-images.githubusercontent.com/8043009/95219200-1a86ef80-07c3-11eb-84ac-4be4ee0336f3.png">

**Expected behavior**
Int he example above I would like to click "monothalamous" and go to that descriptor, for example to edit it or destroy it

**Screenshots**

**Environment (please identify where you experience this bug:**

- Production
- Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by jlpereira** [comment]
Fixed
