### ISSUE TITLE
Editing descriptors from list

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#1798]
**Describe the bug**

When I go to the list of descriptors and select one to edit, either to fix a typo or to destroy one that is inappropriate, I am redirected to create a new descriptor.

**To Reproduce**
1. When I  navigate to .../descriptors
2. And I click "list"
3. The browser takes me to that descriptor. 
4.  If I click "edit" I am redirected to create a new descriptor.
5. If I click "destroy" I sometimes get an error (75% of the time) and sometimes successfully destroy the descriptor (25%)

<img width="1127" alt="Screen Shot 2020-10-06 at 11 09 23 AM" src="https://user-images.githubusercontent.com/8043009/95220547-93d31200-07c4-11eb-9ecd-803fac5bc782.png">

<img width="1151" alt="Screen Shot 2020-10-06 at 11 09 33 AM" src="https://user-images.githubusercontent.com/8043009/95220561-97ff2f80-07c4-11eb-94b4-7addefe5f3db.png">

<img width="578" alt="Screen Shot 2020-10-06 at 11 08 46 AM" src="https://user-images.githubusercontent.com/8043009/95220574-9cc3e380-07c4-11eb-910c-dcbca65c669e.png">

**Expected behavior**
Clicking edit should take me to the descriptor so that I can edit what was written. Clicking destroy should destroy it (after being asked "are you sure?", which it does)

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***

- Production
- Chrome Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by mjy** [comment]
PG::ForeignKeyViolation: ERROR:  update or delete on table "descriptors" violates foreign key constraint "fk_rails_12347ac772" on table "character_states"
DETAIL:  Key (id)=(1205) is still referenced from table "character_states".

  app/controllers/descriptors_controller.rb:76:in `destroy'

**Comment by mjy** [comment]
@jlpereira I think this is a `/descriptors/123` vs `/descriptors?descriptor_id=123` issue, at least in part?
