### ISSUE TITLE
Needed: Collection Object Quick form: Origin relationship

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1799]
As a curator, I need to be able to link two objects in a Collection Object relationship with Origins defined. 

Use case: I remove a wing from a wasp that is pinned and mount it on a slide. I give both preparations a catalog number. I then want to link the wing to the pinned specimen via catalog number and specify the origin relationship that one is extracted from another.

**Comment by jlpereira** [comment]
Its already done

**Comment by tmcelrath** [comment]
I'd love to get a demo of this done at next digitization meeting

**Comment by tmcelrath** [comment]
I don't know how to do this in TW. I need to do it soon. Can I get a demo?
