### ISSUE TITLE
Needed: Collection Object Quick form: Quick extract

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1800]
As a curator, I need to be able to link two objects in a Collection Object relationship with Origins defined, but one of those objects is a data class "Extract".

Use case: I remove a leg from a wasp that is pinned and send it for DNA extraction. I give the pinned wasp a catalog number and the extract an identifier of some sort. I then want to link the leg extract to the pinned specimen via catalog number and extract identifiers and specify the origin relationship that one is extracted from another.

**Comment by jlpereira** [comment]
This can be done with Origin relationship quick form

**Comment by tmcelrath** [comment]
@mjy would also like to see this @ digitization next week

**Comment by mjy** [comment]
Use the collection object quick forms, and pull it up on the Origin relationship slice, easy peasy:

<img width="2094" alt="Screen Shot 2021-05-07 at 9 37 43 AM" src="https://user-images.githubusercontent.com/22600/117485066-90a42e00-af2d-11eb-8741-55bb26b60f9e.png">
