### ISSUE TITLE
Needed: Collection Object Quick form: Quick sequence

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1801]
As a curator, I need to be able to link collection objects, extracts, and sequences in a Collection Object relationship with Origins defined, but one of those objects is a data class "Sequence", and the other is data class "Extract. 

Use case: I remove a leg from a wasp that is pinned and send it for DNA extraction. I give the pinned wasp a catalog number and the extract an identifier of some sort. I then want to link the leg extract to the pinned specimen via catalog number and extract identifiers and specify the origin relationship that one is extracted from another. I then get sequences back, and want to link those sequences to both the extract (leg), and the original collection object (pinned specimen).

**Comment by debpaul** [comment]
I imagine @kandakoj would be interested in this too?

**Comment by mjy** [comment]
There is an interface for existing sequences/extracts:

<img width="2349" alt="Screen Shot 2022-02-06 at 8 50 54 PM" src="https://user-images.githubusercontent.com/22600/152717110-d7c37ac2-94ba-4acb-8e28-434cb02c1366.png">

From a "quick" perspective I think this is good enough.  I think the parallel example is that we need Quick new sequence for Extract.  In both cases I'm not completely convinced that "Quick" is the way to manage sets of sequences and extracts.  I"m going to close for now in lieu of a `Task - New sequence` issue.
