### ISSUE TITLE
As a User I'd like display the version being used, with a link to that Tag in the code repo

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1804]
Display slightly more subtle than in development, not sure where.

**Comment by mjy** [comment]
Looks good, maybe slightly smaller (.75), aligned bottom of Logo text?

**Comment by LocoDelAssembly** [comment]
@jlpereira Can you check if it is possible to perform @mjy's alignment request? Technically it is aligned, if the version had "g" or "j", the bottom of those letters would be at the same line the "S" of Taxonworks sits on. Perhaps there is some HTML trick for this, tried a couple of alignment attributes but nothing affected it. Haven't tried absolute/relative positioning, but those not sure if are totally safe.
