### ISSUE TITLE
DwC Importer - Add support for spreadsheet files (ods, xls, xlsx)

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1806]
Sometimes conversion from spreadsheet to tab-separated TXT might garble the data a bit (specially true with Excel). It is best to allow users to submit spreadsheets directly rather than attempting to revert transformations made by spreadsheet software so the TXT data can be safely used.

**Comment by mjy** [comment]
@LocoDelAssembly how hard is this going to be?  Some questions:

* What type of transformations are you thinking of?  Why do we assume we can handle all the edge cases that might arrise in code with some library that likely doesn't support all excel's nuances?

Here I am in great favour of having people learn themselves the routes forward out of dependency of excel as an exchange format.  Supporting a proprietary format is going to open up all sorts of long term considerations that I'm not sure is worth our time investment.
