### ISSUE TITLE
Collection object filter - Geographic area search does not return certain records

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1807]
**Describe the bug**

When I search for something in a certain geographic area, and I **know** that there are records that should match it, those records don't come up. 

**To Reproduce**
1. When I search for records of a particular species in the collection object filter
2. Then I get those records returned.
3. And I then search for those records with a geographic filter **that is already assigned to the specimens**
4. Then those records no longer come up. 

Searching for "Ammophila gracilis"
![image](https://user-images.githubusercontent.com/11411328/95601762-89f61c80-0a19-11eb-8f1b-ce7371c7da6b.png)
Four records come up, all with geographic area of Minas Gerais Brazil. 

Adding a Geographic Area filter of Brazil:
![image](https://user-images.githubusercontent.com/11411328/95601857-b742ca80-0a19-11eb-9721-ed36ca1aac60.png)

Note no records are returned. Similar results if not treated spatially, or if I search for Minas Gerais. No records returned. 

**Expected behavior**
Geographic area filter should work. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
If you use "treat as spatial" then only the shape is considered- are they georeferenced?

**Comment by tmcelrath** [comment]
No, but they have an assigned geographic area. Do assigned geographic areas not get checked fro this search? I thought they had default centroid georeferences.
