### ISSUE TITLE
Enhancement - DWC Importer - Error for "name" should be "scientificName"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1818]
When I import a scientific name that is improperly formatted for DWC importer, and I get an error that says "name" has error, then it should say "scientificName" because there is no "name" field. 

![image](https://user-images.githubusercontent.com/11411328/95907860-d5823080-0d61-11eb-9519-6155ee3071e2.png)

**Comment by LocoDelAssembly** [comment]
Also consider kingdom, phylum, class, etc. Error may come from those as well when name tree is created.

**Comment by tmcelrath** [comment]
So, can the error then reflect which column this is coming from? "Name" is still not good enough to isolate error.
