### ISSUE TITLE
Bug - can't use navigate radial on collecting events at all in production

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1824]
**Describe the bug**
Can't use navigate radial on collecting events at all in production

**To Reproduce**
1. When I open any collection event. 
2. Then I click the navigate radial.
3. Get an internal 500 error. 

Error:
![image](https://user-images.githubusercontent.com/11411328/96184656-655ce180-0efe-11eb-92e3-1c8f39cc51f1.png)

**Expected behavior**
Should be able to use the navigate radial.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome
- INHS Insect Collection project

**Comment by tmcelrath** [comment]
@LocoDelAssembly I was told to tag you by @mjy

**Comment by LocoDelAssembly** [comment]
I might have fixed this already with https://github.com/SpeciesFileGroup/taxonworks/commit/fb5ea91cd8498e8b543d26ca8a1b485d26731a53. Can you reproduce on sandboxes too? I just tried sandworm and doesn't seem to have this problem.

**Comment by tmcelrath** [comment]
Matt tried and couldn't reproduce on anything but production.

**Comment by mjy** [comment]
Working on production snapshot locally.
