### ISSUE TITLE
OTU: citations prior to formal descriptions of species or subspecies

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1825]
Often new taxa are mentioned in the literature before they are formally described. Either with some informal name, or e.g. as _Eremobia gibbera_ var. 1 (in Saussure 1884), _Typophyllum_ sp., and _Deinacrida_ n. sp.

Corresponding OSF citations are imported to the OTU with the current name (most often the subsequently published protonym, which is confusing).

At the moment it is apparently impossible to add such citations in TW (the three last examples above could be created as non-Latin and linked to a formal name, but would receive author and year, and "sp." etc. will probably enter homonymy competition). Would it be possible to develop an appropriate model/task to record an original verbatim identification and link it to a protonym?

**Comment by proceps** [comment]
If you absolutely have to enter those names into nomenclature, you can mark them as nomen nudum (or one of the subclasses) or excluded (or one of the subclasses). Unavailable names do not enter into homonymy. In general we discourage the use of non nomenclature related entities in the TaxonName table. Using OTU table is more appropriate for them. OTU could be linked to the taxon and got a name. OTU may have a citation, and it will be visible in the list of historical names in the browse OTU page.

**Comment by mjy** [comment]
To echo what @proceps says.  These names are not intended to be governed by a code of nomenclature, and therefor don't belong in TaxonNames in TaxonWorks.  Informal names belong as OTU names, since no rules apply to them.

I would *not* recommend including the names 'n. sp.' as Nomen Nuda, that assertion will not be interpreted as you might think it will in view/display in the long run.

**Comment by typophyllum** [comment]
This is not about names, but published pre-protonym identifications. Often they are of taxonomic interest or come with other important information on the corresponding species.

**Comment by proceps** [comment]
OTU will cover it. Add TaxonName of a valid taxon, and use the Name as it was published. Citation will be visible in Browse OTU. As I said, if you absolutely have to do it as a TaxonName, you can do something like this:
![image](https://user-images.githubusercontent.com/5597748/96207895-ef726d80-0f31-11eb-8213-39c3c03ad38e.png)

**Comment by typophyllum** [comment]
Thank you. I actually do no want to create a TaxonName. The original ID can be mentioned in Notes. It is only strange that the protonym appears prior to its publication.

![grafik](https://user-images.githubusercontent.com/33210201/96734445-eef23080-1390-11eb-93bf-394403c8d969.png)

**Comment by proceps** [comment]
This is not a protonym. This is an OTU, the dark background is intended to emphesize the difference. If you go to Browse nomenclature and look there, OTUs are not listed there.
