### ISSUE TITLE
Task - Edit TaxonName - Non Latin

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1826]
When I have a protonym, which already saved, for example A. mueleri. 
If I alter the name to "müleri", and try to save it, I have a pop up message suggesting to Add "Non Latin" status. 
If I do it, instead of updating an existing name, a new protonym is created.

After the protonym is created, the "Non Latin" status is not visible, before the page is reloaded.

**Comment by jlpereira** [comment]
Fixed
