### ISSUE TITLE
Task - OTU radial - asserted distribution

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1828]
Asserted distribution is not visible in some of the taxa.
See for example https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=375734 (3i)
![image](https://user-images.githubusercontent.com/5597748/96392748-9f3e1a00-1182-11eb-9dd7-f9c624e60213.png)

**Comment by proceps** [comment]
Just noticed, when you create an area in Radial, it is visible, but once radial is closed and opened again, it is not visible.

**Comment by jlpereira** [comment]
shape is missing on response, something has been changed there?

**Comment by jlpereira** [comment]
yah, I see it, now we have to pass geo_json param.

**Comment by mjy** [comment]
Sorry, this might need further refinement and tweaks elsewhere as well, see https://github.com/SpeciesFileGroup/taxonworks/issues/1581.  Indeed, geo_json is required.  BUT, I think there is also a problem with the geo being exported 2x in the response, or there was at least when I was tweaking the API version.
