### ISSUE TITLE
Enhancement - Collection Object Filter: Cannot search by "Determiner"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1835]
As a user, I want to find all the specimens determined by a determiner, e.g. Leonora Gloyd. I want to be able to search "Determiner" field and "Buffered Determinations" for an exact or partial string.

**Comment by mjy** [comment]
* [ ] `:determiners[]=`
* [ ] `:buffered_determinations`
* [ ] `:exact_buffered_determinations`
