### ISSUE TITLE
Geographic area no longer shows up in comprehensive Georeference display

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1840]
**Describe the bug**
Geographic areas no longer show up and aren't "scoped to" in georeferencing pane of comprehensive.

**To Reproduce**
1. When I  go to comprehensive and open/create any collection object with an assigned collecting event. 
2. Then I assign or see that collecting event has an assigned geographic area with a shape.
3. And I open the georeference pane. 
4. Then I see no geographic area. 

Assigned geographic area of Champaign Couty, Ohio:
![image](https://user-images.githubusercontent.com/11411328/96880388-bd39a200-1442-11eb-9c56-b0ad253ff0a3.png)

Resulting Georeference Pane:
![image](https://user-images.githubusercontent.com/11411328/96880363-b448d080-1442-11eb-8bea-01596e179a37.png)

**Expected behavior**
Should scope to geographic area if no georeference present.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chome

**Comment by mjy** [comment]
Duplicate, fixed already I think (ping @jlpereira).  Reminder to check (and for us to fill) CHANGELOG.md.
