### ISSUE TITLE
Comprehensive - Can't immediately assign/save cloned collecting event

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1843]
**Describe the bug**

When I clone a collecting event in comprehensive, I can't immediately save it, it won't let me. I have to reload the page, select the cloned event, then save. 

**To Reproduce**
1. When I am in comprehensive and clone a collecting event.
2. Then the collecting event is automatically created and assigned to a collection object
3. But I cannot save. No error, just fails/won't let me. 
4. I can reload the page, re-select the cloned collecting event, then I can save. 

**Expected behavior**
Should immediately be able to save cloned collecting events

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by jlpereira** [comment]
I followed the steps and i can't replicate it, works fine for me. @tmcelrath could you try to replicate it? and try it with the network tab open to see what could be failing

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/96910302-e66b2a00-1464-11eb-8905-bca867c64b06.png)

**Comment by tmcelrath** [comment]
Does that help?
![image](https://user-images.githubusercontent.com/11411328/96910406-11ee1480-1465-11eb-8413-53833d3eab5b.png)

**Comment by jlpereira** [comment]
Yah @tmcelrath thanks, i will look more close on this

**Comment by jlpereira** [comment]
@tmcelrath could you retry one more time with the network tab open. After fails, click on clone request, select preview tab and post the screenshot

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/96915141-85932000-146b-11eb-9791-a920fce31dbf.png)
![image](https://user-images.githubusercontent.com/11411328/96915178-8f1c8800-146b-11eb-94c0-ccb601803370.png)

**Comment by jlpereira** [comment]
<img width="1680" alt="Captura de Pantalla 2020-10-22 a la(s) 15 39 15" src="https://user-images.githubusercontent.com/16530364/96915627-da8b6200-147c-11eb-9c06-4e31b6663e78.png">

@tmcelrath check if you got one called "clone" like in the image. You will see it after cloning the collecing event

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/96915843-5df08780-146c-11eb-8bfc-5395ec259663.png)
![image](https://user-images.githubusercontent.com/11411328/96915861-63e66880-146c-11eb-84ad-d57cb725d17e.png)

**Comment by tmcelrath** [comment]
That better?

**Comment by jlpereira** [comment]
@mjy seems the clone response is giving the same id of the previous failed patch request?

**Comment by mjy** [comment]
@jlpereira @tmcelrath can this be closed?

**Comment by tmcelrath** [comment]
Yeah I think so - not having this issue anymore

**Comment by jlpereira** [comment]
I never could replicate this. Maybe was a problem with a index. Closing
