### ISSUE TITLE
Comprehensive specimen digitization: wrong repository name from grbio.org

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#1848]
This is the correct name:  **Staatliches Museum für Naturkunde Stuttgart (SMNS)**

TW has this:  **Staatliches Museum fuer Naturkund Stuttgart (SMNS)** 

![grafik](https://user-images.githubusercontent.com/33210201/97319449-a7b1e700-184b-11eb-9efb-9db03c9d1f0b.png)

This link is obsolete: http://www.grbio.org/institution/staatliches-museum-fuer-naturkund-stuttgart

GBIF has the correct name there: https://www.gbif.org/publisher/99ea0c90-61e5-11dc-a64c-b8a03c50a862

**Comment by proceps** [comment]
Fixed in production
