### ISSUE TITLE
Enhancement - DWCA Import - If InstitutionCode not found, does not check collectionCode

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1860]
When I import a DWCA with different InsitutionCodes and collectionCode, e.g. WIS for IC, and WIRC for CC (see: [GBIF WIRC](https://www.gbif.org/grscicoll/collection/47324008-87f6-4172-a6ed-1cf4a72b96e6), but institution code is not found, the DWCA does not check the collectionCode for a repository to add to the specimen. 

Many collections choose to place themselves as a collection within an institution but only provide their collection code. So I think if no institutional code matches, TW should check the collection code before it fails to import. 

Especially since for repositories, TW does not distinguish currently between Institutions vs. Collections as GBIF does [see](https://www.gbif.org/grscicoll) - and an importer wants to specifically list a subcollection as the repository vs. an institution, this is a good step to add to reduce import frustrations.

**Comment by LocoDelAssembly** [comment]
Do you have an example in sandworm? When mapping namespaces you should be able to map to instititionCode=*(blank)* collectionCode=<YOUR_COLLECTION_CODE>.

**Comment by tmcelrath** [comment]
I do. Check: https://sandworm.taxonworks.org/tasks/dwca_import/index?import_dataset_id=43 and collection code WIRC. Institution is WIS, which is not in system, but WIRC is. Does collection code override Institution Code if found?

**Comment by LocoDelAssembly** [comment]
Ah, OK understand now. Even if namespace is mapped, although CO is imported the repository is not set: https://sandworm.taxonworks.org/tasks/collection_objects/browse?collection_object_id=992183

@mjy guess we don't have a way to retrieve a repository from a namespace? Would extending the mapping to also ask for the repository solve the problem? (Potentially pre-filling those that can be guessed)

**Comment by tmcelrath** [comment]
Actually, I didn't even see that bug, but yes, it looks like if you don't have an institutionCode then the repository is not set, but the specimen is imported, even though it matched a collectionCode.

**Comment by tmcelrath** [comment]
Larger issue I was reffering to was when you don't want to set the repository as the institutionCode (e.g. WIS in this case), but rather as the collectionCode (e.g. WIRC). If both are the same, that's easy. But if they differ, maybe we need to discuss how to deal with that. @mjy

**Comment by tmcelrath** [comment]
Also, how does TW deal with institutions vs. collections? Does it just have entries for both in repository and you can assign to either one? Can you map to two repositories?

**Comment by mjy** [comment]
We track organizations, but integration is weak.  Repositories are intended to be some physical collection. In theory one org could have many repositories.  As we move to BGIFs grbio list this metadata should be linked I think.

**Comment by LocoDelAssembly** [comment]
The importer assigns a repository based on which Repository it could match on TW by acronym. The collectionCode is not imported as such, just used as part of the key for the namespaces mapping.

**Comment by tmcelrath** [comment]
For example: :)
https://www.gbif.org/grscicoll/institution/55efe71a-faba-4333-951c-d665509f3d67

One institution, many collections. Each collection has its own code, alongside the institutional code.

**Comment by LocoDelAssembly** [comment]
To clarify a bit more:
* institutionCode: importer uses this value to locate a repository with an acronym matching this value. If this value is empty no repository is assigned to collection object. If some text is in here but doesn't match any registered repository in TW then status is switched from Ready to Errored and an error message is provided explaining the situation and how to fix.
* collectionCode: Used by the namespace mapper (alongside institutionCode) to select the namespace for the catalogNumber field.

> We track organizations, but integration is weak. Repositories are intended to be some physical collection. In theory one org could have many repositories. As we move to BGIFs grbio list this metadata should be linked I think.

Assumed repositories were actually organizations having collections. Not really the case? What is the organization tracking we have?

**Comment by mjy** [comment]
Closing as resolved with explict mappings that were recently worked out.
