### ISSUE TITLE
Enhancement - Collection Summary - Show #'s of specimens within taxa

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1864]
Set a Taxon Level (e.g. Order, Class, etc...) and display # of digitized specimens in each larger grouping. E.g. for Insect Collection, I want to see # of specimens by various taxonomic groupings. Keep it to higher levels (Family and above for now). 

Can report as numbers right now, but ready-made bar graph visualization would be cool.

**Comment by tmcelrath** [comment]
Idea - integrate with container profiling, and add visualization of # of specimens in a taxon that are digitized vs. number that are not digitized.

**Comment by mjy** [comment]
> Idea - integrate with container profiling

Ideas are continued here, in part: https://github.com/SpeciesFileGroup/taxonworks/issues/2875
