### ISSUE TITLE
Task - Export project data

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1868]
As a curator I want all data in my project exported in a unified Zip, or SQL dump (priorty is latter).

* As a SQL dump that can be loaded with `rake tw:db:load file=dumped_file.sql` (this is the primary use case we need to have ready for the Hack week)

* As verbatim CSV from tables (this can be secondary priority)

* Should include dump of Users, but with passwords reset to some string, fixed and simple.
* Should create a Download, with is_public defaulted to false

Strategies - perhaps hard coding the SQL with a generator that inspects Project::Manifest then executing it with a shell out to dump the terminal.

**Comment by LocoDelAssembly** [comment]
>As a SQL dump that can be loaded with rake tw:db:load file=dumped_file.sql (this is the primary use case we need to have ready for the Hack week)

@mjy  Is this intended to restore on top of an empty database?

**Comment by mjy** [comment]
@LocoDelAssembly Yes, completely empty.

This reminds me that there will be issues with geo/shapes bit of the export, not sure about this.
