### ISSUE TITLE
Questionable Synonyms

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#1869]
Is there a way to indicate that an OTU is a questionable synonym?

**Comment by mjy** [comment]
For the OTU, presently, not formally, but somewhat informally possible. Right now some groups are doing the following:

otu.name   otu.parent
"Aus nr. sp. bus",  "Aus" (id of a genus).

This will make the OTU name, as listed, appear under the Genus in places where it is displayable, i.e. typically where we want to see it.

The other assertion to consider is to add a Confidence to the OTU itself.  You can  create whatever confidence levels you want.  Note that if you're using the OTU in relation to the Specimen, then the Confidence could be placed on the TaxonDetermination itself, rather than on the OTU (which in that case can be something like plain old "Aus bus", without the uncertainty encoded in the name).

Let me know if this helps.

**Comment by jcabbott13** [comment]
I think that would work, but why is the synonym being attributed to the current genus instead of the genus it was originally described under (as I have it in the data you uploaded)?

**Comment by proceps** [comment]
If the species name enters into synonymy to a species classified in different genus, the synonym name is now also classified under the new genus. In the list of citations, the species is still listed under original name.

**Comment by typophyllum** [comment]
While I do understand that synonyms are technically classified under the genus of the valid name, I cannot understand the reasoning behind TW making these Frankensteinian names. I've never seen any taxonomic work making up artificial combinations for synonyms. This creates much more confusion than it provides useful information. Apart from that a lot of these artifact names don't comply with ICZN Article 31.2. on agreement of gender.

**Comment by mjy** [comment]
@jcabbott13 can you clarify where you are seeing this in a screenshot before we engage further?

**Comment by MMCigliano** [comment]
Below a screenshot to the issue that @jcabbott13 maybe is referring to.. a display that we also find it not very clear
![Uploading image.png…]()

**Comment by MMCigliano** [comment]
Below an example of an issue described by @jcabbott13 ; a display of synonyms that I also find it confusing
 
![image](https://user-images.githubusercontent.com/33158036/98273193-bfd2e600-1f70-11eb-82dd-af730bf02031.png)

**Comment by mjy** [comment]
In general we've told people, if they don't understand the view from the perspective of the synonym, to immediately click on the valid name in the summary box when they see the yellow header, that takes you to the view that you are likely used to seeing.  Further using the eye to restrict to only Protonym collapses the view to an even simpler rendering. In part the "redirect to valid name" in the search helped to hide these pages.

@proceps as @typophyllum suggests swapping out the header to show the original combination in these cases is of course possible.  I have nagging worries that this would get in the way, so to speak, of curators coming to understand the nature of TW's "Protonym",  but these worries likely unsubstantiated.

**Comment by proceps** [comment]
@mjy I do not mind changing the title for the synonyms. But this would not prevent the questions. People will see the synonyms classified under the proper genus name in the treeview, and may be some other places. If we want to be precise, we should probably show the relationship in the title in cases of synonyms. Something like "species1" (in the original form) as a synonym of "species2" (in current form); or "Combination" as a combinations of "species1" (in current form)

**Comment by proceps** [comment]
The label for synonyms was updated
