### ISSUE TITLE
Exporting Note field via API

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#1870]
Can the note field (see Libellula imbuta) be made available via the API?

**Comment by mjy** [comment]
Definitely.

**Comment by jcabbott13** [comment]
Great...when will we know that it is available?

**Comment by mjy** [comment]
In general liveness can be determined by the [CHANGELOG.md](https://github.com/SpeciesFileGroup/taxonworks/blob/development/CHANGELOG.md).  When the CHANGELOG includes a relased version number, then all instances are updated to that number.  We are now quite good at keeping the CHANGELOG up to date.

Sandboxes may be updated prior to a version number being assigned.   Technically (for your programmers) you can trace the commit to history of commits.  The sandbox UI then lists the commit sha for that build, e.g.:

<img width="919" alt="Screen Shot 2020-11-04 at 10 11 24 AM" src="https://user-images.githubusercontent.com/22600/98136071-24654680-1e86-11eb-9227-70e9c32ca441.png">

In a related way you can track this issue to see when commits that address the issue are added.  When you see that commit added, then check the CHANGELOG.md. 

Finally, if we remember, we may @ ping you on the issue when it is available, or if convseration is on-going on Gitter mention it there.  We also tend to mention major changes in the Zoom meetings.

**Comment by jcabbott13** [comment]
Hi Matt....wanted to check in on the status of including the note field in the API. I don't see anything in ChangeLog. Thanks!.

**Comment by mjy** [comment]
@jcabbott13 candidate branch is pushed, hope this is in sandboxes this week.
