### ISSUE TITLE
Loan data

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#1872]
**Describe the bug**

When a loan form is edited, if the "date requested" is not filled out, it automatically reports the "date requested" as today.

**To Reproduce**
1. When I  look up a loan
2. Then I 'edit' (Not Edit(task))
3. And I modify anything
4. Then the loan will show the "date requested" as today

1.
![image](https://user-images.githubusercontent.com/25491000/98292850-0295bd80-1f73-11eb-8e4d-bfb9403bffae.png)

2. +3.
![image](https://user-images.githubusercontent.com/25491000/98292938-25c06d00-1f73-11eb-8d79-a94749de68cb.png)

Then click Update Loan

4.
![image](https://user-images.githubusercontent.com/25491000/98293034-47b9ef80-1f73-11eb-88fd-8241f4c443be.png)

**Expected behavior**
Expected: nothing. I don't want any dates filled in automatically..

.

**Comment by jlpereira** [comment]
Fixed

**Comment by mmkohler** [comment]
Not fixed

**Comment by mjy** [comment]
@mmkohler We close the issue when it's been done in code, not when it's live.  You can track the CHANGELOG.md to see when this issue is made live.

**Comment by mmkohler** [comment]
Thanks Matt!
