### ISSUE TITLE
As a curator I need the DwC-A to add objects with the same catalog number to a virtual container.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1875]
When an identical Catalog Number is present on multiple rows, then we need *the option (off by default)*  to use the approach we use in the Comprehensive digitization form.

* [ ] Add option to use virtual containers ("Lot mode")
* [ ] On create check for Lot mode, and validation errors based on duplicate Catalog identifier.

IIRC there are methods to containerize and move specimens simultaneously.

**Comment by LocoDelAssembly** [comment]
Superseded by https://github.com/SpeciesFileGroup/taxonworks/issues/2055
