### ISSUE TITLE
Task - New source - New button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1877]
Please reload the entire page when the New button is used (not just clear the form). I tend to keep the task in a separate tab. When it is not used for a while, it probably loses the connection with the server. When I use the New button, the task behave normally, the form is cleared, I can add all new information, included the related data (people, serial). But when I click the save button, it fails. I have to reload the page and start editing all over.

**Comment by mjy** [comment]
Weird.  There is no persistent connection, so this should only break when versions update and you'd have to reload anyways.

**Comment by proceps** [comment]
Could be, but the problem is that the form do not show any warning that the version is updated. Reloading form on "New" would be the easiest solution.

**Comment by mjy** [comment]
Whatever is done we have to be consistent throughout.    I think we first fix/determine why new is not triggering.  If there is a reason that is not "there is a new version" then we need to fix that.

**Comment by mjy** [comment]
I'm going to close this.  If you've been away from the application for some time, then you should reload your page.
