### ISSUE TITLE
How to register a subgenus elevated to genus

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1879]
Kratochvíl 1958 created Carinostoma [subgenus of Mitostoma].
Staręga 1976 elevated Carinostoma to genus.
How do I convey this in TW?

**Comment by mjy** [comment]
Use the 'New combination task'.  Create the combination as you see it.  Add the citation Staręga 1976 to the Combination.

In TaxonWorks we don't think of "changed", "updated", etc. but rather "added a new fact at some time".  So we don't assert that Staręga elevated, we just say they used it in such and such a way.

**Comment by adrik29** [comment]
Thanks a lot, Matt -- I see the logic behind...

**Comment by proceps** [comment]
This may not work, the task still do not recognize the genus or a genus and subgenus. We still have an open issue #748.

**Comment by adrik29** [comment]
Uh.... It is NOT working....
I really don't wanna enter Carinostoma as a new genus, just because IT IS NOT new.
I'll leave the matter for now -- but I think it is part of the logonymy to note who made this nomenclatural act.
After all it is currently a genus, not a subgenus and I can't have the information on WHERE this change happened in my TW project.
