### ISSUE TITLE
Collection Object Match does not return containerized objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1885]
**Describe the bug**
Collection Object Match does not return containerized objects

**To Reproduce**
1. When I use the Collection object match task to search
2. Then I get no matches returned for containerized objects where the identifier is on the container, not the object.

CO Match result:
![image](https://user-images.githubusercontent.com/11411328/99111393-a6095280-25b1-11eb-9010-d2e0dac201eb.png)

Containerized CO:
![image](https://user-images.githubusercontent.com/11411328/99111358-9558dc80-25b1-11eb-8c31-c965ee648443.png)

**Expected behavior**
Should return some result. 

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Need to modify Filter response for exact identifier to return objects in container

**Comment by tmcelrath** [comment]
Pinging this. Easy fix to add in next small update?

**Comment by mjy** [comment]
Requires redefinition of   `def match_identifiers_facet` in CO filter.

**Comment by tmcelrath** [comment]
Actually I think this is fixed. I can check later?

**Comment by tmcelrath** [comment]
Fixed.

**Comment by mjy** [comment]
Are you sure?  I'm not seeing the code behind this.

**Comment by tmcelrath** [comment]
Yes:
![image](https://github.com/user-attachments/assets/ef214f35-0ce7-4105-8d4a-7b9a08ac792c)

**Comment by tmcelrath** [comment]
Has been working for some time now.

**Comment by mjy** [comment]
Aha, that match is different code I suspect.  It won't work in Filter CO I think?

**Comment by tmcelrath** [comment]
![image](https://github.com/user-attachments/assets/0889f772-53ed-4b19-aadb-20fe33d0b666)
Works just fine.
