### ISSUE TITLE
Eventdate not DwC compliant

### ISSUE THREAD

**Issue by bpescador** [SpeciesFileGroup/taxonworks#1887]
DarwinCore standard for eventdate includes the option of including "/" for date ranges as in: 
2000-12-05/2000-12-13 

This format is not accepted using the DwC-A import in Sandworm: see https://sandworm.taxonworks.org/tasks/dwca_import/index?import_dataset_id=51

*

**Comment by mjy** [comment]
@LocoDelAssembly Seems that range is OK, at least according to the wiki version of the ISO standard.


https://en.wikipedia.org/wiki/ISO_8601
https://dwc.tdwg.org/terms/#dwc:eventDate

We need a ISO gem for processing dates, perhaps this? https://github.com/arnau/ISO8601/blob/main/docs/time-interval.md

**Comment by LocoDelAssembly** [comment]
@mjy will check that gem, but definitively adding support for intervals.
