### ISSUE TITLE
Overview of issues with first Ant data import

### ISSUE THREAD

**Issue by bpescador** [SpeciesFileGroup/taxonworks#1888]
In reference to the import: https://sandworm.taxonworks.org/tasks/dwca_import/index?import_dataset_id=51

Though separate issues are mentioned below; I wanted to record in one place my thoughts on the import. 

**A number of dwc fields did not seem to import as expected:**

typeStatus
eventDate [error if format with end date after "/ "]
recordedBy
elevation
higherGeography
previousIdentifications 
identificationQualifier

**With those records that did import, I have a number of questions to ask regarding interpretation.** 

For example, 
Fieldnumber is imported but it appears to only act as a text field, not a unique field for the collecting event: https://sandworm.taxonworks.org/collecting_events/234097.  Thus unclear how to use fieldnumber to link collection objects like this: https://www.antweb.org/collection.do?name=BLF00882 or to add collection objects to data for a collection event using fieldnumber. 

Also, unclear how to view all the collection objection information: this view: https://sandworm.taxonworks.org/collection_objects/994819
doesn't show many of the fields I would expect like field numbers.  Also, when viewing the collection object, I wish I could click on the species identification and view other collection objects for that species.

**Comment by mjy** [comment]
@LocoDelAssembly:
* [ ] when `fieldNumber` is supplied then it should *also* be added as a `Identifier::Local::Tripcode'
* [ ] typeStatus - are we creating TypeSpecimen records for the corresponding TaxonName?
* [ ] elevation - mapping?  remember all this needs to be converted to meters to persist in TW
* [ ] higherGeography - this raises questions with what to do when we have lat long, we'll have to describe the behaviour at first then go from there.  I.e. in theory lat long means we don't need higher for computation (@bpescador see the DwC row at the bottom of the Browse collection object pages)
* [ ] previousIdentifications - these probable get added as new/matched OTUs with no taxon names I think
* [ ] identificationQualifier - one option is to match these to CVT for ConfidenceLevel and add to TaxonDetermination, this would be the most precise handling in TW.  I'd have to look closer at the actual values.

@bpescador 
> eventDate [error if format with end date after " | "] 
See also other ISO related issue already added, but I think " | " should be slash according to your first example? https://github.com/SpeciesFileGroup/taxonworks/issues/1887

 
> Also, unclear how to view all the collection objection information

 https://sandworm.taxonworks.org/collection_objects/994819 is a Data card.  You want the corresponding Browse task ('Browse collection objects'):  https://sandworm.taxonworks.org/tasks/collection_objects/browse?collection_object_id=994819.  The browse pages are very preliminary, suggestions for improvements welcome.

**Comment by mjy** [comment]
> I would add option to move through classification by clicking genus or species

Do you mean viewing an individual record, then stepping to the previous/next in the scope of some taxon, or viewing a summary of all records in some scope.  The latter is possible in Filter collection objects, but not in the click-through manner you describe.  I think the click through is perhaps a different/new task concept, show collection objects summaries by classification with some options to zoom out to individual records, etc.?

> show all object fields with data: fielnumber missing for example

The Filter objects task is the place to add parameters to filter sets of objects by.   Add individual issues for each facet (parameter) you'd like to see there.  For example: 'Task - Filter collection object, objects missing field number parameter.'

**Comment by LocoDelAssembly** [comment]
> when fieldNumber is supplied then it should also be added as a `Identifier::Local::Tripcode'

How would the namespace mapping be done here? Ask the user to supply one? Would a single namespace be enough even on large datasets like AntWeb?

> typeStatus - are we creating TypeSpecimen records for the corresponding TaxonName?

It is not imported as TypeMaterial. Is any intermediate approach to this? Biggest problem is that most of the time it is not just "Holotype", but rather "Holotype of Jivarus americanus Giglio-Tos, 1898" and many variations. Not sure if simple NLP will be enough, and then also know whether the cited name refers to original combination or current name, etc.

>elevation - mapping? remember all this needs to be converted to meters to persist in TW

There is `minimumElevationInMeters` and `maximumElevationInMeters`, also `verbatimElevation`. Will map those to corresponding CO fields.

>higherGeography - this raises questions with what to do when we have lat long, we'll have to describe the behaviour at first then go from there. I.e. in theory lat long means we don't need higher for computation (@bpescador see the DwC row at the bottom of the Browse collection object pages)

It is currently ignored, also atomic fields, all is handled with coordinates. Not sure how to deal with multiple matches? Also what to do when no gazetteer matches? Possible intemediate approach is adding this in a verbatim field.

> previousIdentifications - these probable get added as new/matched OTUs with no taxon names I think

It does not import this field. Example data:
>Chalepidae, Pinus abies, Anthus sp., field ID by G. Iglesias | Anthus correndera, expert ID by C. Cicero 2009-02-12 based on morphology

I see in AntWeb data that this field very often has a single name and that it matches `scientificName`. This field perhaps should be left empty when that happens?

Re identificationQualifier, please check examples at https://dwc.tdwg.org/terms/#dwc:identificationQualifier . I see in AntWeb things like `ankarana_MG02`. Not sure what to do with those?

**Comment by proceps** [comment]
1. I found it is inconvenient to have a namespace for a TripCode identifier, especially when the data are comming from the literature, I tend to enter those as Unknown identifier, because that one does not require a namespace.
2. for the type material, if there is no direct link to the TN, it is better to export the data as a DataAttribute, and not try to parse it.
3. Elevation, enter original as verbatim, and convert it to meters. Higher elevation only needed if the range is provided.
4. For higher geography, I usually tend to build the mapping manually. In any given dataset, I expect to see 100-200 geographic areas constantly used. I resolve those manually and add a cross reference table.
5. For previous identification, you can of cause create OTUs, but if you do not link the OTU to the TN, it is just lost in the system. Check what we do in OSF. It is a multy step approach. Try to resolve the TN first, and only as a last step create a new OTU. link the OTU to the valid TN.
6. There is also a stand alone methods which extract coordinates, elevations and dates from the verbatim label, all three are provided as verbatim and converted into a standard form. Could be useful even when it is not a verbatim label, but the same field provides data in different formats.

**Comment by mjy** [comment]
@LocoDelAssembly thanks much for the clarifications, they should help users modify their data to meet the import in several cases.

Please don't modify any of the import strategy until further discussion.  In part we'll need to break this down into specific issues before moving forward.

**Comment by bpescador** [comment]
@proceps 
Re identificationQualifier, I followed the standard to place morphospecies codes following this discussion: 

see: https://github.com/tdwg/dwc-qa/issues/162
also:https://doi.org/10.1371/journal.pone.0218904

https://obis.org/manual/darwincore/#occurrence

<img width="1008" alt="Screen Shot 2020-11-16 at 2 25 01 PM" src="https://user-images.githubusercontent.com/6276764/99315436-85dacd00-2817-11eb-850b-098d7c9ef722.png">

**Comment by mjy** [comment]
In the `Gadus` example I would prefer to create a OTU name with that `Gadus cf. morhua`, i.e. scientificName + qualifier.

**Comment by proceps** [comment]
I agree with @mjy. But sometimes it could be linked to the species TaxonName, if somebody later stated that "cf. morhua" is corresponding to a particular species. Basically the question is alway where in the classification the name fits better.

**Comment by bpescador** [comment]
might be easier to show in this format, where TW OTU = taxonconceptID


**Example   5 | Adetomyrma MG01 morphospecies   code**
**higherClassification** | Animalia \| Arthropoda \| Insecta \| Hymenoptera \| Formicidae \|   Amblyoponinae \| Adetomyrma
**scientificName** | Adetomyrma
**scientificNameAuthorship** | Ward, 1994
**scientificNameID** | Antcat URL
**taxonRank** | genus
**family** | Formcidae
**genus** | Adetomyrma
**specificEpithet** | [empty]
**identificationQualifier** | MG01
**previousIdentifications** | Adetomyrma MG01
**taxonConceptID** | scientificName + the identificationQualifier

Also note I see I should also include additional higher classification Kingdom, Phylum and Class as well.

**Comment by debpaul** [comment]
@bpescador are all these issues now resolved?

**Comment by mjy** [comment]
Closing as stale. Open data-specific issues now on `antweb-staging` repo.
