### ISSUE TITLE
How to convey rank change in the family group?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1890]
Manaosbiinae Roewer 1943 was originally described as a subfamily.
It was later elevated to family rank (Kury 1997) and included in the superfamily Gonyleptoidea.
How can I convey this idea in TW?
I know that the second part is easy by using the "classification" tab.

**Comment by proceps** [comment]
You have to create sevelal protonyms.
One - current name (with proper ending and rank).
Second one: original spelling with the Family group name original form relationship
Third one: with Family group name form relationship.
Classification is not necessary, but could be use if you want to specify that the subfamily was classified under particular family.

**Comment by adrik29** [comment]
Thanks a lot, Dmitry:
It is important for me to keep track of these "secondary" things as well...

**Comment by adrik29** [comment]
Hm... It looks alright to me, but it seems that I added a superfluous author role -- I dunno where, because the error msg mentions an error -- but there is no error, it is just a matter of usage. The subfamily has its rank elevated to family, that's all.
Is this error msg right? Should I change anything now?

![image](https://user-images.githubusercontent.com/46284943/99377169-a69d3400-28a4-11eb-9104-b2d14d7cbba8.png)
![image](https://user-images.githubusercontent.com/46284943/99377212-b288f600-28a4-11eb-961a-593a65ef5637.png)

**Comment by proceps** [comment]
Yes, author role is not require for any protonym which has a relationship from the group Usage. Because the author of the TaxonName always comes from the original author, and the citation comes from the linked source.
