### ISSUE TITLE
Task - New Namespace [was: Namespace delimiter clarification and improvements]

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1891]
Need to clarify delimiters on namespaces in data tab:
Add buttons for:
- NONE: no delimiter between namespace, e.g. renders as [NAMESPACEIDENTIFIER] i.e. TCM2020_01
- SINGLE SPACE: single space between namespace and identifier, e.g. renders as [NAMESPACE IDENTIFIER] i.e. TCM 2020_01
- CUSTOM: enter any delimiter combination, e.g. renders as [NAMESPACE"CUSTOMDELIMITER"IDENTIFIER] i.e. TCM-----2020_01

Make sure this is very clear in the data entry sheet.

**Comment by mjy** [comment]
@jlpereira Need some old school Javascript here, this is the modification:

<img width="675" alt="Screen Shot 2020-11-18 at 10 03 46 AM" src="https://user-images.githubusercontent.com/22600/99554990-6cf02a00-2985-11eb-9139-c13b9954221a.png">

**Comment by LordFlashmeow** [comment]
Can this be documented on the create new namespace page?
