### ISSUE TITLE
Error message correct???

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1892]
My dearest: I strongly suspect that this error msg is incorrect.
Could you please check for me?
Stygnopsidae is simply a subfamily described in a "wrong" family, which was later discovered to be a member of Zalmoxidae.
But Zalmoxidae is not and has never been divided into subfamilies.
The error msg basically says that A SUBFAMILY CANNOT BE A SYNONYM OF A FAMILY. But of course it can.
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=329230

![image](https://user-images.githubusercontent.com/46284943/99445524-68cbfa00-28fc-11eb-9a10-125c5f0638e4.png)
![image](https://user-images.githubusercontent.com/46284943/99445646-9add5c00-28fc-11eb-831b-b7232ae77f55.png)

**Comment by proceps** [comment]
I will check the validation.
The message which you display ("should have the same parent") This could be disregarded. The TW should automatically fix some of the problem throug the softvalidation fixes. At the moment, this could only be done programmatically. But eventually we may need a specialized interface to run validations and fix what could be fixed.

**Comment by proceps** [comment]
@mjy Sould we run softvalidation fix after taxon_name is saved (when Save button is clicked)?

**Comment by adrik29** [comment]
Thanks, Dmitry!
Those validation messages are immensely useful to guide our actions, and they increase productivity a lot.
We should be able to search specifically for taxa which have validation error msgs so we can quickly be aware of possible problems.

**Comment by proceps** [comment]
I did some changes in validation. There could be some warnings that the parent should be the same and or the rank should be the same. Those should be fixed either automatically, through the soft validation fix. It could be either ignored for now, or fixes could be applied manually. Both synonyms (senior and junior) should have the same rank and parent. When two are synonymized, according to ICZN, they are first brought to the same rank (synonymy is only recognized within the same rank). And also if two names are synonymized, they are brought under the same taxon concept, they should have the same classification. So the parent of two should be the same. So the fix will allow to treat the family group name as a synonym of subfamily without the ending change.

**Comment by adrik29** [comment]
Cool! This principle of coordination gives me headaches.
Families, subfamilies and superfamilies are deemed by the Code to be established simultaneously, although this is **purely fictitious**. 
I find this extremely difficult to convey, even using pure text for my manuscript. By using a word processor we are not constrained by anything and could write anything in any form (and colors, which make it it much easier for me to see). This gives you a lot of freedom, but weakens the structured idea of a database for a catalogue.
I usually resort to clearly note the parent taxon for each entry, so I know where I'm threading.
![image](https://user-images.githubusercontent.com/46284943/99477395-312b7500-2931-11eb-9e2b-113651febddf.png)

**Comment by proceps** [comment]
In theory, you can provide this data only once for one of the coordinated taxa in TW. Soft validation Fix should add a proper citation, people, type, etc. for all coordinated taxa. Although, as I said, at the moment the fix could only be run programmatically.
