### ISSUE TITLE
Row order in observation matrices - ability to lock

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1895]
This is tangentially related to the bug I posted a while ago (#1881), which has been closed. 

Row order can be very important to the user, so please include an option to lock the user-defined row order from "edit observation matrices". 

Or simply disable in observation_matrices/view, the ability to resort rows by clicking on OTUs.

**Comment by mjy** [comment]
@jlpereira I would suggest we keep the sort locked by default (like comprehensive form), and click to unlock.

**Comment by proceps** [comment]
@jlpereira in both cases, here in #1881. The observation_matrix_rows.position should be used as a primary sorting mechanism when the rows are displayed.

**Comment by jlpereira** [comment]
Already changed the order in edit/new matrix task, reopen if the problem persist
