### ISSUE TITLE
Matrix row coder, can't code free text or media characters

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1896]
In Matrix row coder, Free text and Media character types do not show and cannot be created. In screenshot below, USNM Holdings (character 1) is free text and holotype images (charcter 2) was created as a Media character. All other character types, I can code in this module.
![Matrix_rowcoder_bug](https://user-images.githubusercontent.com/70152690/99551958-79c34c80-298a-11eb-8f19-2b23fc8c799a.png)

**Comment by proceps** [comment]
The media characters implemented specifically for image matrices. Use the matrix dashboard interface and open OTU in the image matrix, you should be able to drag and drop images directly to the cells of the table.

**Comment by jlpereira** [comment]
As @proceps said, this should be done on image matrix. But i will add the possibility to MRC handle media observations

**Comment by mjy** [comment]
The Descriptor is a type that needs to be fillable in the row coder, there is no difference there vs. the other form, the semantics are the same.
