### ISSUE TITLE
Otu quick forms - can't update an existing Biological Association to `is_original` ?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1900]
Because we are stacking multiple citations on the record we can't get back to edit/destroy a specific citation. 

May also be an issue with asserted distribution?

**Comment by proceps** [comment]
In both placces the radial annotator is available and you can edit each individual citation. I do not have an issue.

**Comment by mjy** [comment]
Got it, thanks!
