### ISSUE TITLE
undefined method `api_v1_download_file_url

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1908]
An ActionView::Template::Error occurred in sources#generate:

  undefined method `api_v1_download_file_url' for #<#<Class:0x00007f1695eed678>:0x00007f134c241fd8>
Did you mean?  api_v1_downloads_url
               api_v1_api_download_file_url
  app/helpers/downloads_helper.rb:15:in `download_file_api_url'

  https://github.com/SpeciesFileGroup/taxonworks/blob/0daaabbcb/app/helpers/downloads_helper.rb#L15

Not sure why the API is involved on this? Referrer is https://sfg.taxonworks.org/tasks/sources/filter?keyword_ids%5B%5D=662&per=500&page=1

**Comment by mjy** [comment]
This is a share link to let you  copy/paste the API link to a zipped bibliographies.
