### ISSUE TITLE
Observation matrix: Row, column order is now locked

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1915]
Probably related to closed issue #1881. Under both edit and view tasks for observation matrices, the row order and column order seems to be fixed and user cannot click and drag to reorder.

**Comment by proceps** [comment]
There is a checkbox for reordering at the top of the Edit Task
![image](https://user-images.githubusercontent.com/5597748/100765964-b8f79180-33bd-11eb-9176-373f19b9af11.png)
