### ISSUE TITLE
Filter Image Task returning wrong images

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1916]
**Describe the bug**
When I search by any classification scope, I get lots of images returned, but none are the right images. 

**To Reproduce**
1. When I use image filter task.
2. Then I scope by classification.
4. I get the exact number of images specified (e.g. 50, 100), but they are all the wrong images (do not match classification)

Search for Ixodida - no images returned are of Ixodida. 
![image](https://user-images.githubusercontent.com/11411328/100890978-6a5dfc00-347e-11eb-9e54-6e5e403d64fa.png)

**Expected behavior**
Should be able to scope by taxon.

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
@tmcelrath this is production, not your local machine?

**Comment by tmcelrath** [comment]
Correct.

**Comment by tmcelrath** [comment]
Replicated by Jim Wooley during TW Demo
