### ISSUE TITLE
Elevation not parsed with DWC Importer

### ISSUE THREAD

**Issue by brennaldecker** [SpeciesFileGroup/taxonworks#1917]
**Describe the bug**

In the DWC field, minimumElevationInMeters, this is not parsed into TaxonWorks Elevation field.

**To Reproduce**
1. When I enter a number into the minimumElevationInMeters column, and enter the verbatim information in the verbatimElevation column, (everything else in the datasheet is completed)
<img width="1216" alt="Screen Shot 2020-12-02 at 9 55 42 AM" src="https://user-images.githubusercontent.com/75384782/100905184-fffc8a00-3484-11eb-8024-a1cbf76e118e.png">

2. Then I upload using DWC-A Importer on Sandworm (INHS DWC Testing)

3. And I make sure it uploaded properly, and go to one of the records, click the stacked icon in the top right corner to get to the Comprehensive specimen digitization page, and check the elevation...

<img width="878" alt="Screen Shot 2020-12-02 at 9 56 02 AM" src="https://user-images.githubusercontent.com/75384782/100905209-0a1e8880-3485-11eb-8ae9-c4b16066b6a5.png">

**Expected behavior**
If the elevation on the label is 1063m, the minimumElevationInMeters column go into the Minimum elevation field and should have 1063, and 1063m should appear in the Elevation field in the Comprehensive specimen digitization

**Environment (please identify where you experience this bug:**
- Sandworm -  https://sandworm.taxonworks.org - INHS
- FireFox on Mac

**Comment by LocoDelAssembly** [comment]
Added support in https://github.com/SpeciesFileGroup/taxonworks/commit/f7558a7ac023b28466c39951e23543d3981f43ce
