### ISSUE TITLE
Radial annotator - new image, option to use pinned source as citation

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1919]
When I drop an image, then I want a checkbox to let me auto-cite the pinned source as the origin of that image.

**Comment by proceps** [comment]
this is alredy implemented in the imae matrix

**Comment by mjy** [comment]
@jlpereira something like putting the blue pin here: <img width="883" alt="Screen Shot 2021-08-09 at 8 47 07 AM" src="https://user-images.githubusercontent.com/22600/128716627-7e3e2be5-be57-4fd1-9b94-ed6a745e97c6.png">

**Comment by jlpereira** [comment]
By default, in the smart selector component the pinned icon is always at the right of the switchs
