### ISSUE TITLE
Task - New Taxon Name - flip radio/text boxes in Gender and form (maybe?)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#192]
* Put the radio buttons on top, and the text boxes on the bottom (@proceps - but note decoupling of values ... hmm, maybe not good, should we really do this?)  

Current:
![screen shot 2017-09-08 at 5 07 57 pm](https://user-images.githubusercontent.com/22600/30232998-76792f3c-94b8-11e7-839f-2c9dd8f7b827.png)

Requested:

![screen shot 2017-09-08 at 5 07 57 pm](https://user-images.githubusercontent.com/22600/30233023-95eb302c-94b8-11e7-92c2-03593facabc3.png)

**Comment by proceps** [comment]
just put the status above the Feminine box.
