### ISSUE TITLE
Simple Batch Load Nomenclature - loading issue and enhancements

### ISSUE THREAD

**Issue by brennaldecker** [SpeciesFileGroup/taxonworks#1927]
I am testing the simple batch loader in the sandbox account using a Mac on FireFox. I want to make a nomenclature spreadsheet that can be used to jump-start a production account in the future.

The simple batch loader only has the headers for the taxon names (kingdom through subspecies works) and the author_year. It would be great if, when importing the nomenclature, to -

1. have a column that specifies if the scientificName (i.e. Minagenia osoria Banks, 1941) is a synonymy of another name in the list, and a second column to specify that accepted taxon name (i.e. Minagenia externa banks, 1910)

- In the Edit Taxon Name, this would appear in the Relationships field.

2. have a column that also imports the source

- in the Edit Taxon name, there doesn't seem to be a Publication field, yet the soft validation says that the record is missing an original publication ("Original publication is not selected").
<img width="1266" alt="Screen Shot 2020-12-03 at 2 26 35 PM" src="https://user-images.githubusercontent.com/75384782/101090264-9d35ec00-3573-11eb-8fd8-07719500cfb3.png">

3. import the name in the Verbatim author field if it does not have parentheses

- It seems like if the author_year is "(Kaplin, 1983)", the Author and Year are parsed out, but when it's "Kaplin, 1983", only the year is used and no person is specified in the Verbatim section of Author (but still creates a unique person identifier).
<img width="393" alt="Screen Shot 2020-12-03 at 2 25 47 PM" src="https://user-images.githubusercontent.com/75384782/101090171-7677b580-3573-11eb-85b1-7efe0aff021f.png">

I'm not sure if there is work being done to update the batch loader for taxonomic names, or if my Sandbox account just doen't have the recent updates to the code. This is on a Mac in FireFox.

**Comment by mjy** [comment]
Hi @brennaldecker thanks very much for this issue.

Re your points:
1 - Asserting synonyms are possible now in the CASTOR load, I fixed the documentation there, it should be live shortly.
2 - How would you want to reference the source, by ID?  With the full citation to link to a verbatim citation?
3 - Using the verbatim field has been proposed recently by others too- we may move to that option, however the multi-merge option of people in uniquify people now facilitates the use of people a little more cleanly, so maybe that would help?

**Comment by brennaldecker** [comment]
Thanks, @mjy! 
1. Great, I'll try that when it goes live.
2. I was thinking a full citation to link. I haven't played with importing citations yet, but if there's the verbatim, then a column for (Kaplin, 1953) that matched the Author and Year in the relationships filed, would that work too?
3. I think that will help, I haven't played with muliti-merge yet either.

**Comment by debpaul** [comment]
@mjy wrote to @brennaldecker :

> Hi @brennaldecker thanks very much for this issue.
> 
> Re your points:
> 1 - Asserting synonyms are possible now in the CASTOR load, I fixed the documentation there, it should be live shortly.
> 2 - How would you want to reference the source, by ID? With the full citation to link to a verbatim citation?
> 3 - Using the verbatim field has been proposed recently by others too- we may move to that option, however the multi-merge option of people in uniquify people now facilitates the use of people a little more cleanly, so maybe that would help?

Please what is the status of this Matt? And can I help to test?

**Comment by mjy** [comment]
@debpaul you can test the "CASTOR' batch load `/taxon_names/batch_load`.  That importer will not be updated with additional functionality, only documentation clarification. Importing synonymy will likely be a 2 step process (valid, then invalid) in TW.  Adding citation links to parsed sources is likely the purvue of generalized functionality in the DwC Checklist importer ultimately.

Closing as stale for specific issues.
