### ISSUE TITLE
Cannot edit or view Notes in annotator 

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#1928]
**Describe the bug**

When I click Notes in annotator, I cannot access them to view or edit.

**To Reproduce**
1. When I add a Note in annotator.
2. Then I click back to Collecting event/Collection object interface.
3. Then I go back to Notes to view or edit.
4. Then I see there is a Note in Notes field.
5. Then I click on Notes.
6. The Note disappears and I cannot edit or view the note.

**Expected behavior**
I should be able to edit and view my own notes.

**Screenshots**
See below.

**Environment (please identify where you experience this bug:**
*** One of ***

- Production
- Chrome

**Comment by tmcelrath** [comment]
Screenshot as I create a note:
![image](https://user-images.githubusercontent.com/11411328/101188369-3cfa8500-361b-11eb-89b9-d5539ea04e28.png)

**Comment by tmcelrath** [comment]
After refresh of page: 
![image](https://user-images.githubusercontent.com/11411328/101188460-5f8c9e00-361b-11eb-8be1-6dd6e9e8288c.png)

**Comment by tmcelrath** [comment]
Upon clicking, notes disappear and can't be edited:
![image](https://user-images.githubusercontent.com/11411328/101188501-6b786000-361b-11eb-9290-7da225abea7b.png)

**Comment by mjy** [comment]
Perhaps a blocker.

**Comment by mjy** [comment]
Replicated, weird.  @jlpereira is it related to the pulse bit?

**Comment by jlpereira** [comment]
@mjy Nope. The response its sends an empty list
