### ISSUE TITLE
Allow for adding custom data attributes to more models

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#1932]
As a user who wants to store additional data, for which there are currently no data attributes, I would like the ability to add custom data attributes to models that are currently not customizable. Specifically “Extracts” and “Depictions”.

**Comment by mjy** [comment]
Extracts have custom attributes (just an eg in screenshot).  Closing as is, rethink for Depictions and re-open if necessary.

<img width="951" alt="Screen Shot 2022-02-06 at 8 47 54 PM" src="https://user-images.githubusercontent.com/22600/152716825-ec8322e1-7923-4e05-9e1e-b24ec86b5914.png">
.
