### ISSUE TITLE
Upgrade "Geolocate" georeference importer to import shapefiles as polygons in Georeference pane

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1937]
If I am using Geolocate to georeference a specimen
Then I want to be able to use their error polygons.

So from a Geolocate formatted shapefile e.g.:
"Indiana Dunes State Park":

41.663093	-87.036977	3613	41.663349022,-87.009749925,41.662094022,-87.013033925,41.661843022,-87.013710925,41.661295022,-87.015079925,41.660243022,-87.017843925,41.659222022,-87.020613925,41.659049022,-87.021118925,41.658698022,-87.022083925,41.658208022,-87.023470925,41.657698022,-87.024877925,41.657160022,-87.026285925,41.656893022,-87.027055925,41.656194022,-87.029076925,41.656000022,-87.029536925,41.655824022,-87.030021925,41.655656022,-87.030549925,41.655142022,-87.031936925,41.654680022,-87.033323925,41.654414022,-87.034009925,41.654348022,-87.034254925,41.654331022,-87.034417925,41.654331022,-87.034635925,41.654312022,-87.034738925,41.654305022,-87.034779925,41.653732022,-87.036367925,41.652635022,-87.039532925,41.652073022,-87.041123925,41.651497022,-87.042686925,41.651097022,-87.043814925,41.650383022,-87.045799925,41.649611022,-87.047962925,41.648681022,-87.050643925,41.648355022,-87.051512925,41.648070022,-87.052285925,41.647620022,-87.053545925,41.647206022,-87.054715925,41.646600022,-87.056423925,41.645663022,-87.058904925,41.644922022,-87.060894925,41.644705022,-87.061504925,41.644386022,-87.062381925,41.644306022,-87.062588925,41.645005022,-87.062578925,41.646177022,-87.062586925,41.648645022,-87.062598925,41.651344022,-87.062608925,41.653262022,-87.062626925,41.654051022,-87.062626925,41.656389022,-87.062650925,41.656930022,-87.062661925,41.660296022,-87.062700925,41.6629670221,-87.0633459217,41.6630420221,-87.0630599201,41.6631490221,-87.0627819201,41.6632570221,-87.0626039201,41.6634720221,-87.0623439201,41.6635690221,-87.0621879201,41.6636550221,-87.0619039201,41.6638590221,-87.0609549201,41.6639390221,-87.0606849201,41.6640480221,-87.0603999201,41.6642490221,-87.0599629201,41.6643630221,-87.0597519201,41.6644390221,-87.0595619201,41.6644740221,-87.0593779201,41.6645200221,-87.0589019201,41.6645690221,-87.0587149201,41.6646900221,-87.0583549201,41.6648710221,-87.0577439201,41.6650030221,-87.0574109201,41.6652900221,-87.0568259201,41.6653560221,-87.0566179201,41.6655170221,-87.0561699201,41.6655690221,-87.0559099201,41.6656520221,-87.0555879201,41.6657280221,-87.0551549201,41.6658090221,-87.0546019201,41.6658710221,-87.0543569201,41.6661380221,-87.0537469201,41.6662430221,-87.0533959201,41.6663060221,-87.0531189201,41.6663580221,-87.0527729201,41.6663990221,-87.0525819201,41.6664820221,-87.0523949201,41.6667400221,-87.0519429201,41.6669340221,-87.0517429201,41.6671280221,-87.0515759201,41.6672450221,-87.0514129201,41.6673110221,-87.0511919201,41.6673660221,-87.0509149201,41.6675070221,-87.0504869201,41.6675380221,-87.0503249201,41.6675690221,-87.0498599201,41.6676070221,-87.0495419201,41.6676990221,-87.0490969201,41.6677230221,-87.0489219201,41.6677440221,-87.0487709201,41.6677850221,-87.0486329201,41.6678820221,-87.0484419201,41.6680930221,-87.0481929201,41.6683920221,-87.0473979201,41.6686070221,-87.0467579201,41.6689270221,-87.0458829201,41.6691860221,-87.0453919201,41.6692750221,-87.0450919201,41.6693920221,-87.0444719201,41.6695100221,-87.0439529201,41.6695880221,-87.0437129201,41.6696610221,-87.0436089201,41.6700690221,-87.0428679201,41.6704930221,-87.0420589201,41.6705830221,-87.0418199201,41.6706660221,-87.0414389201,41.6707690221,-87.0408329201,41.6709100221,-87.0401939201,41.6710410221,-87.0397369201,41.6713470221,-87.0388939201,41.6714820221,-87.03849192,41.6715930221,-87.03797592,41.6717260221,-87.03743092,41.6718540221,-87.03706692,41.6720030221,-87.03654092,41.6721230221,-87.03607192,41.6723090221,-87.03558292,41.6726540221,-87.03480592,41.6727850221,-87.03429792,41.6729340221,-87.03360492,41.6732190221,-87.03264392,41.6733580221,-87.03213092,41.6737920221,-87.03075092,41.6739670221,-87.03008492,41.6740150221,-87.02998392,41.6740910221,-87.02977992,41.6741950221,-87.02930192,41.6742390221,-87.02916192,41.6743460221,-87.02902692,41.6745190221,-87.02861092,41.6752300221,-87.02665292,41.6752710221,-87.02655892,41.6752950221,-87.02639292,41.6753420221,-87.02622892,41.6754460221,-87.02610392,41.6755810221,-87.02584792,41.6756470221,-87.02557392,41.6756990221,-87.02524892,41.6757770221,-87.02452292,41.6759980221,-87.02401092,41.6761680221,-87.02347792,41.6765740221,-87.02236392,41.6767580221,-87.02188292,41.6770190221,-87.02124792,41.6776330221,-87.01976692,41.6778480221,-87.01936592,41.6779410221,-87.01915392,41.6779530221,-87.01907292,41.6779530221,-87.01887192,41.6780120221,-87.01858092,41.6781570221,-87.01823092,41.6783610221,-87.01778092,41.6785020221,-87.01757492,41.6786160221,-87.01734992,41.6786710221,-87.01714192,41.6787400221,-87.01674092,41.6788030221,-87.01657392,41.6788790221,-87.01640492,41.6789250221,-87.01636192,41.6790600221,-87.01617792,41.6791050221,-87.01605292,41.6791640221,-87.01576892,41.6792130221,-87.01542992,41.6792610221,-87.01516992,41.6793200221,-87.01497292,41.6793980221,-87.01480492,41.6795190221,-87.01465592,41.6795740221,-87.01450392,41.6796120221,-87.01418492,41.6796540221,-87.01397392,41.6797130221,-87.01376592,41.6799320221,-87.01333792,41.6800050221,-87.01316492,41.6801090221,-87.01288092,41.6802890221,-87.01220292,41.6803600221,-87.01196492,41.6804810221,-87.01165692,41.6808930221,-87.01077392,41.6810850221,-87.01041592,41.6811190221,-87.01033392,41.6811710221,-87.01021192,41.6812310221,-87.00987592,41.680845022,-87.009822925,41.680522022,-87.009815925,41.680452022,-87.009878925,41.680387022,-87.009902925,41.678075022,-87.009906925,41.676144022,-87.009851925,41.675904022,-87.009852925,41.674428022,-87.009859925,41.671150022,-87.009826925,41.669454022,-87.009828925,41.667526022,-87.009786925,41.666552022,-87.009753925,41.664608022,-87.009732925,41.663738022,-87.009746925,41.663349022,-87.009749925

I would want to import that as a type "Geolocate", and as a polygon, not a centroid georeference. 

The resulting polygon should look like this:
![image](https://user-images.githubusercontent.com/11411328/101671906-c72b5a80-3a1a-11eb-9fc3-1695cad25895.png)

**Comment by tmcelrath** [comment]
Having trouble with this in today's meeting. Not working properly in Production

**Comment by tmcelrath** [comment]
Can do with not with WKT importer. Close @proceps @mjy?

**Comment by mjy** [comment]
I don't think we can assign as *error*, only as "asserted" (we haven't exposed any error shape management to the UI yet).
