### ISSUE TITLE
Add warning/confirmation for saving collecting event if it updates >50 records

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1938]
As a user, I want a warning when I am editing a collecting event in Comprehensive if saving that collecting event will modify more than 50 records.

E.g. as a user I accidentally modify the "Unknown" collecting event which is currently assigned to >20000 records. This is bad and should not be done but is generally easy to do. 

A warning should pop-up to confirm save where you have to type "Modify" to modify more than 50 records.

**Comment by jlpereira** [comment]
@mjy i think we gonna need to make a call to check how many collection object are linked to that CE on each update. I hope this not make a big impact on performance

**Comment by mjy** [comment]
In that project we need to get rid of the unknown CE, or rename it "unknowable' is one thing, it's pointless, right?

**Comment by tmcelrath** [comment]
Yes and no? Was kind of a catch-all collecting event in old database for lots of poorly documented specimens, some of which can be taken further, and some not.

**Comment by jlpereira** [comment]
Duplicate #3727
