### ISSUE TITLE
dwc_event_date not ISO 8601 compliant 

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1939]
https://github.com/SpeciesFileGroup/taxonworks/blob/86886f4939cbc3e94a2de2a8a083ac914b22b2e3/app/models/collection_object/dwc_extensions.rb#L115

That returns dates in the form `YYYY/MM/DD-YYYY/MM/DD`, should be `YYYY-MM-DD/YYYY-MM-DD`.

Do we have anything relying on current format that would block changing to ISO format?

Also, there is a potential semantic problem here (also affecting #1887) involving the meaning of the time interval.

https://dwc.tdwg.org/terms/#dwc:eventDate

>Definition: The  date-time or interval during which an Event occurred. For occurrences,  this is the date-time when the event was recorded. Not suitable for a  time in a geological context.

>Comments: Recommended best practice is to use a date that conforms to ISO 8601-1:2019.

Up to that point it seems to be used to indicate when the event started and when it finished, but then on examples:

>Examples: 1963-03-08T14:07-0600 (8 Mar 1963 at 2:07pm in the time zone six hours earlier than UTC). 2009-02-20T08:40Z (20 February 2009 8:40am UTC). 2018-08-29T15:19 (3:19pm local time on 29 August 2018). 1809-02-12 (**some time during** 12 February 1809). 1906-06 (some time in June 1906). 1971 (some time in the year 1971). 2007-03-01T13:00:00Z/2008-05-11T15:30:00Z (**some time during** the interval between 1 March 2007 1pm UTC and 11 May 2008 3:30pm UTC). 1900/1909 (some time during the interval between the beginning of the year 1900 and the end of the year 1909). 2007-11-13/15 (some time in the interval between 13 November 2007 and 15 November 2007).

(Last example potentially not compliant actually, not parseable by iso8601 gem nor Ruby built-in parser)

So question here is what is the purpose of eventDate interval, is it to express uncertainty or to express a time span? And is it a 1:1 mapping to TW semantics for `start_date_*/end_date_*`?

PS: Not belonging to this issue tracker but after making a change all data will have to be re-indexed.

**Comment by mjy** [comment]
We not so long ago pushed hard to get everything unified to reference the dash version in TW:
https://github.com/SpeciesFileGroup/taxonworks/blob/development/lib/utilities/dates.rb#L6

Re certainty vs. time span.  I think they are the same thing.  I think of it as asserting knowns (certain of X).  If that happes to be certain it's uncertain that's fine.  From those examples I *thnk* the mapping is 1:1 semantically. 

I'm anticipating significant health/re-indexing options for the DWC index, we'll be blowing it away with the merged of the export branch.

**Comment by debpaul** [comment]
Not sure I follow all the nuances here. But historically note that DwC used to have [dwc:earliestDateCollected](https://dwc.tdwg.org/list/#dwc_EarliestDateCollected) and [dwc:latestDateCollected](https://dwc.tdwg.org/list/#dwc_LatestDateCollected), but these were deprecated. 

So in this single term / concept you can provide a single date, or a date range.

I don't believe it's meant to represent uncertainty. If there was uncertainty (say a label that reads"June? 1896"), I might put dwc:verbatimEventDate = June? 1896, but in dwc:eventDate you could just put 1896. Does that help?

**Comment by LocoDelAssembly** [comment]
Is anything related to **import** here? Is it OK if I go ahead and change `eventDate` output format on `development` branch to produce valid ISO date?

**Comment by mjy** [comment]
Where is the output format?

**Comment by LocoDelAssembly** [comment]
```ruby
2.7.2 :001 > Utilities::Dates.today
 => "2021-02-23" 
2.7.2 :002 > Utilities::Dates.from_parts(2021,02,23)
 => "2021/02/23" 
2.7.2 :003 > Utilities::Dates.today.inspect
 => "\"2021-02-23\"" 
2.7.2 :004 > Utilities::Dates.from_parts(2021,02,23).inspect
 => "\"2021/02/23\"" 
 ```
 
 Perhaps as a first step add functions to this library that mention `iso8601` explicitly in their names and refactor all code later when it is safe that it won't brake anything switching format? (The iso-variants would be used only for dwc_occurrence at this time.)

**Comment by mjy** [comment]
That's fine.  Reality is we should use an gem that is not ours to deal with these kind of issues. 

We need to unify on '-' rather than / as well, at least internally.
