### ISSUE TITLE
Requested feature: ability to sort long lists of biological associations

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#1946]
It would be very helpful if one could sort long lists of biological associations on the Browse OTU page.  For example, see the OTU Burkseus vittatus (Walker ) in UCD project.  There are probably hundreds of records of hosts and plant associates, and they do not seem to be output in any particular order (or at least it is not apparent to me).  

As a result, it is virtually impossible to determine whether a new published record "is original" or not.  This also makes it very difficult to determine whether or not an OTU has been reared from a particular host.

If one could sort each of the individual columns it would go a long way towards solving this problem.

As an example, see attached screen shot of a host list that I am attempting to enter for this species, from Perry and Heraty (2019).

<provide a screenshot>

![Screen Shot 2020-12-11 at 1 02 51 PM](https://user-images.githubusercontent.com/30122486/101945573-06d97a00-3bb4-11eb-9388-9afba320b9d2.png)

**Comment by debpaul** [comment]
@JimWoolley mentioned this today at TaxonWorksTogether2021. Any movement forward yet for this?

**Comment by mjy** [comment]
@jlpereira has the filter stubbed, waiting on filter back-end.  Might have to rope @LocoDelAssembly into some of this work on the unified filter branch.

**Comment by debpaul** [comment]
Today at the Technical meeting, we reviewed some tickets, including this one. The UCD@TW ( e.g. @JimWoolley @JohnHeraty @rkres001) group would like SFG to to prioritize some movement for this task (biological associations functions). 

Specifically, some functions like
- column sort (see screen shot)
- ability to download Biological Associations list as CSV

Example Record: https://sfg.taxonworks.org/tasks/otus/browse?otu_id=140066
![image](https://user-images.githubusercontent.com/2990155/165579836-aa29955b-341f-4a05-8856-080f7dba9bdf.png)



Down the road, @proceps notes, he would prefer a GloBI style presentation, all the relationships by OTU in both directions.

**Comment by mjy** [comment]
<img width="2238" alt="Screenshot 2023-11-16 at 3 34 54 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/e16fa0fa-63ad-4860-9082-5e214e890a88">

**Comment by JohnHeraty** [comment]
This looks like what we are after, especially if it can be copied to an excel file. I wonder if author year is necessary. It seems more like clutter, although it could be removed by parsing the column. Can the sources be spit out at the end (reference list) as how Roger is doing it on the UCD web version?

**Comment by mjy** [comment]
>  if it can be copied to an excel file

See "Copy to clipboard"

> Can the sources be spit out at the end (reference list) as how Roger is doing it on the UCD web version?

Yes.
