### ISSUE TITLE
Senior synonym replaced by next oldest synonym because of homonymy

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1959]
My dearest:
I was trying to replicate in TW what I wrote in the manuscript of my catalog using a word processor (FIg 1):
![image](https://user-images.githubusercontent.com/46284943/103238938-f4d53680-492a-11eb-9e90-57a217d9ecb3.png)

I was forced to write the synonymy twice (one for each genus on lines 5 and 6), otherwise I got an error message (Fig 2):
I am sure there is a way to do it properly in TW. How?

![image](https://user-images.githubusercontent.com/46284943/103239062-3f56b300-492b-11eb-9d6f-55286370cccb.png)

**Comment by proceps** [comment]
@adrik29, you did it correct way. Of cause you can reduce it to just one synonymy relationship: Acantholophus is a synonym of Lacinius, in this case, you would not need the second relationship, and you also would not need the Valid status. You should remember, that all relationships in TW are bidirectional by their nature. Basically saying that T1 is a synonym of T2 is almost identical as saying that T2 is a synonym of T1. It is still means the synonymy of two taxa. There is of cause the priority involved, but we overvrite the priority issue by invalidating one of the name with a homonym relationship. 
I will think if we really need a "Substitute" relationship. My primary concern is that both names are subjective synomyms, and relationship may disapper if somebody decide that two taxa are not synonyms.

**Comment by adrik29** [comment]
@proceps = thanks Dmitry!
I still miss the qualifiers JUNIOR and SENIOR in the synonymies and homonymies.
Lacinius is junior, but steps up only because Acantholophus is a homonym (this one is of course stg permanent).
The synonymy however, could be lifted at any moment as you said.
But....
There could be an EXTRA relationship, stg like "junior synonym made valid because of homonymy of the senior"...
Take care, our lives are precious...

**Comment by proceps** [comment]
For some reason, I do not like it. It is too precise, there could be some other reasons why the senior synonym may become invalid (homonimic type genus, rejected by the Commission, etc.). I really like descrete statuses (both nomenclatural statuses and statuses through the relationship), and option to apply multiple statuses to the same name. In this particular example, we have homonym status, and synonym status, I do not like the idea to combine two together, because if you start doing this, you will quicly realized that you are getting overvelmed with possible combinations. I know, because I worked with original ucd database, which had double and triple statuses, it was extremly difficult to extruct all necessery information to record all the assertions.

**Comment by adrik29** [comment]
@ proceps -- thanks for the insight!
There is a big difference between what I write in my text (because I can basically put anything I like and a special explanation for each situation) and what I mark in TW.
All those relationships are extremely complex and we have to be careful not to end up with an overwhelming number of classes of relationships.
Lacinius would be invalid if not because of the homonymy of Acantholophus with a genus of Coleoptera. And I wanted to have this clearly explained in the TW project.

**Comment by proceps** [comment]
In complicated cases, I use OUT Contents to provide additional comments, those are specifically designed for free text expressions. Besides of nomenclatural issues, I also put information on introduced species there, basically anything which could not be expresed precisely using the TW model. Basically using it as a footnote.

**Comment by adrik29** [comment]
Ah, OK, I will try to use more the comments facilities.
We can always adapt format in the future, but at least the relevant information is there.
Cheers,
Adrik
