### ISSUE TITLE
SqedDepiction created for OTU

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1961]
This happened on sandbox.taxonworks.org. Tried couple of methods to replicate through New Image task but failed. There is only one instance returned by `SqedDepiction.joins(:depiction).merge(Depiction.where.not(depiction_object_type: 'CollectionObject'))`, none in production. The depiction is from Dec 10th, last updated on Dec 18th, so happened with very recent code and is not old bad data.

This problem is related with `undefined method 'buffered_collecting_event' for #<Otu:0x000055a72b806bc8>
  app/helpers/sqed_depictions_helper.rb:139:in 'sqed_waxy_metadata'`

**Comment by mjy** [comment]
Added validation to ensure SqedDepiction is linked to a depiction of a CollectionObject, however i can not find the bad data in the database after some basic queries, so leaving open for now.

**Comment by mjy** [comment]
Closing as out of date.
