### ISSUE TITLE
Edit taxon name firing multiple updates when updating gender

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#1970]
When I update the gender of a genus multiple duplicate updates are fired, some even concurrently causing random 500 HTTP errors (deadlock situation at database when processing taxon_name_classifications endpoint).

**To Reproduce**
Steps to reproduce the behavior: (in sandcastle with OSF)
1. When I  go to edit taxon name for genus Gryllus (id=23093)
2. Then I go to gender and form
3. And I set it to 'Masculine'
4. Duplicate requests appear

![image](https://user-images.githubusercontent.com/4991925/104225228-e3a92100-5424-11eb-89f0-0db5f6ef866d.png)

Please see video as well: 

https://user-images.githubusercontent.com/4991925/104226281-4f3fbe00-5426-11eb-8867-f7c290ad69ab.mp4

**Expected behavior**
Do not perform multiple updates (please notice one of the calls is fired with the green line reaches the right side), perhaps the call to taxon_names_classification is the only PATCH required, the others seems to be submitting the same params each time and are unrelated to the actual change made.

**Comment by proceps** [comment]
When a gender is assigned, it require numerous changes: first the taxon_name_classification is created; after that. all species under the genus have to be updated and all combinations (original and subsequent) have to be updated to match the grammatical gender of the genus. I do not think it generate any errors.

**Comment by LocoDelAssembly** [comment]
This morning I caused several "[TW-Error] taxon_name_classifications create (ActiveRecord::StatementInvalid) "PG::InFailedSqlTransaction: ERROR: curre..." with the steps above.

By multiple updates I mean the PATCH requests the browsers sends, the terminal with the rails log output in the video is to hint when the whole process stops.

**Comment by mjy** [comment]
@proceps it's not back end issue (ah, I see @LocoDelAssembly mentions this now), front-end.
