### ISSUE TITLE
Task - New asserted distribution - error warning

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1971]
All records created in the task are marked with orange triangle, when clicking I have the waring:
![image](https://user-images.githubusercontent.com/5597748/104519072-74673480-55be-11eb-835d-fe0244fc3c48.png)
In fact, the records are created correctly, but the error is a mistake.

**Comment by mjy** [comment]
Are you sure you don't have an absent record for equador (or some greater area) for the taxon?  Issue is raised in`sv_confilicting_geographic_area`

**Comment by mjy** [comment]
Error is in the method, it needs to be scoped to Taxon.

**Comment by proceps** [comment]
It is every single records, some of the taxa did not have any other distribution recordred.
