### ISSUE TITLE
Soft Validations - refactor metadata and fix pattern

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1972]
As a developer and user I need to be able to run individual or sets of soft validations.  To do this properly we need to refactor how soft validations are instantiated.

After the refactor soft validations will *not* be re-run prior to fix calls, fixes are run only on the set of soft validations that are called.  All fixable soft validations are fixed when requested, i.e. if you want to exclude or only run some then only validation those you intend to fix.  See options in `lib/soft_validations#soft_validate`.

Steps:

* [x] rewrite set method and meta expectations (@mjy)
* [x]  all `has_fix: true` must be updated to `fix: :sv_fix_name`, moving the validation name from the sv_ method to the `soft_validate` call (@proceps)
* [x] remove `fix: :abc` from sv_checks methods (fix is defined prior)
* [x] all `fix_trigger: :abc` must be change to `flagged: true`  - soft validations with flagged: true are not run by default, i.e. a restricted set (@proceps) 
* [x] move `resolution: :named_route` from sv_method to soft_validate(resolution: :method_name)
* [x] all spec calls for actual specs (not meta-model testing) must be updated to reflect this pattern (@proceps).  For example `@ad.soft_validate(:some_method)` can become `@ad.soft_validate(only_methods: :some_method)`, `@ad.soft_validate(only_methods: [:some_method])` is also allowed.
* [x] All `@model.fix_soft_validations` have no params passed to them, you must call `@model.soft_validate(params)` *before* running fixes.  Params in soft_validate determine what set of fixes will be run.

**Comment by mjy** [comment]
Models to update method calls:

* [ ] AssertedDistribution
* [ ] Citation
* [ ] CollectingEvent
* [ ] CollectionObject
* [ ] Descriptor
* [ ] Image
* [ ] Otu
* [ ] RangedLotCategory
* [ ] Serial
* [ ] TaxonName
* [ ] TaxonNameClassification
* [ ] TaxonNameRelationship
* [ ] TypeMaterial

**Comment by proceps** [comment]
show we close this?
