### ISSUE TITLE
Sandbox TODOmap task card broken

### ISSUE THREAD

**Issue by juliah3** [SpeciesFileGroup/taxonworks#1973]
Working in a sandbox.
When I try to access the 'Collection object image breakdown TODO list', I instead get a message "We are sorry, but something went wrong.  If you are the application owner check the logs for more information."

Is there a way to fix this?  It was working for a few weeks before this happened.
Or is there another way to access the image TODO map?

Thank you,
Julia

**Comment by mjy** [comment]
Hi @juliah3 thanks for the bug report.  We'll look into it and see if we can get a better report back.  The sandbox had a number of development changes added yesterday, we perhaps broke a route.

**Comment by LocoDelAssembly** [comment]
https://github.com/SpeciesFileGroup/taxonworks/issues/1961 related?

**Comment by juliah3** [comment]
Thanks!

It actually happened right before the holidays, though!  I didn't check for
a couple weeks, but it is still happening now.

Julia

**Comment by debpaul** [comment]
This seems to be working now @juliah3. Please retest and let us know? 

in sandbox.taxonworks.org I see
![image](https://user-images.githubusercontent.com/2990155/162042694-b0cf7e16-373c-4e94-9af7-9b982a50d78a.png)

and when I click on it I see

![image](https://user-images.githubusercontent.com/2990155/162042807-052fea7a-4da1-43b1-a09d-2a7bdce6947d.png)
