### ISSUE TITLE
Task - Comprehansive & New Collecting Event - Suggested geographic area

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#1976]
When coordinates are available, the geographic area is suggested. Of several gazeteers, please provide the area with larger number of records used already in the project.

**Comment by mjy** [comment]
We don't have synonymy for geographic shapes, not sure this can be done in a fool-proof manner?

**Comment by mjy** [comment]
We suggest geographic area when Georeference present.
