### ISSUE TITLE
Task - Comprehensive CO CE status clarification

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#1986]
As a curator it is difficult to note when I'm editing an existing vs. creating a new CE.  

* Unify status, icons, etc. together on the bottom
* Add warning triangle / status verb "New record" | Modifying existing (X uses)"
* Consider changing the blue undo button to a 'New' button, which it essentially does (setting the form to unset) (where all do we use this pattern?)
* Update object tag to include "X uses" as in other autocompletes

![Screen Shot 2021-01-20 at 2 20 16 PM](https://user-images.githubusercontent.com/22600/105371396-34114300-5bca-11eb-9e43-7b41ebe936f0.png)

**Comment by tmcelrath** [comment]
Saw the new look. Much better!
