### ISSUE TITLE
TW system doesn't let me note past classification as incertae sedis

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1987]
Happy New Year for all:
I want to report what I suspect to be an **incorrect error message**:
Genus _Glysterus_ Roewer, 1931 has been assigned to the following parent taxa:

(1) _Glysterus_ was originally in Hernandariinae.
(2) Transferred to Gonyleptinae by Goodnight & Goodnight (1947a: 13).
(3) Put in Gonyleptidae incertae sedis by Kury (2003a: 104). 
(4) Transferred to the Ampycinae by Kury & Alonso-Zarazaga (2011: 52). 

So, we see that in 3 it was not included in any subfamily, but in 4 it is already in Ampycinae.
That means, **during a window of seven years** _Glysterus_ was a Gonyleptidae incertae sedis.
But TW doesn't let me note this in the CLASSIFICATION module, because it doesn't understand that G inc. sedis is a **PAST CLASSIFICATION**.
It keeps saying the the tag incertae sedis is incompatible with the allocation to Ampycinae.

![image](https://user-images.githubusercontent.com/46284943/105427806-ba5e7100-5c2c-11eb-9551-81dcc21a2951.png)

All I can do is this:

![image](https://user-images.githubusercontent.com/46284943/105427938-0f01ec00-5c2d-11eb-9415-df0d1213b6ad.png)

**Comment by proceps** [comment]
Yes, you should you Classified as relationship.
Incertae sedis is reserved for current classification only. It is a temporaty status, befor better position for the taxon is recognized. In fact, you cannot even change the parent of the taxon before you remove the Incertae sedis relationship. Using Incertae sedis, will let the sistem negate some of the soft validation messages, and could also be used as a filter. For historical placements we reserved "Classified as" relationship. Which is designed for historical placements of the taxon. If you want to be more specific, you have to use comments, for example OTU Contents.

**Comment by adrik29** [comment]
Thanks, Dmitry. So I basically did what was correct in this case...
