### ISSUE TITLE
Discriminating details of sources in auto-complete

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#1988]
### In **Edit taxon name**:

Whenever I start typing, the **autocomplete** enters and does a fantastic job.
And one of the things that is more important is that it discriminates the sources by means of colored boxes. And this is immensely useful. In the example below I can easily detect that there are duplicates and that the second line (already used 7 times in the project) is the correct one to pick:

![image](https://user-images.githubusercontent.com/46284943/105578614-458c5380-5d60-11eb-901e-3d0685a82b59.png)

### However, in "Asserted distribution" this does not happen:

![image](https://user-images.githubusercontent.com/46284943/105578677-a9af1780-5d60-11eb-953f-edf19e2a1b4f.png)

**So, I ask: can we have the same positive feature mentioned above also in the "Asserted distribution" form?**

**Comment by jlpereira** [comment]
Yes, its possible we are using a different label to display the results. I will take a look at it

**Comment by adrik29** [comment]
@jlpereira = Thanks, José Luis! It will be appreciated.

**Comment by adrik29** [comment]
**Fan-tas-tic!**
Many thanks from Rio!
