### ISSUE TITLE
Task - New Taxon Name - hyperlinks to external data

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#199]
Add hyperlinks for external data.
1. All taxa should be linked to browse taxonomy pages.
2. Source - to Source page (or Edit source page)
3. Citation - make html safe (hide tags, e.g. <i>Name</i>)

**Comment by mjy** [comment]
@proceps  Best to tease these out as individual issues at this point.

**Comment by mjy** [comment]
Is 3) still an issue?  @proceps can you screenshot if so?

**Comment by proceps** [comment]
Yes, it is still an issue. If I have <i>Genus</i> in the citation, I still see the tags.

**Comment by mjy** [comment]
Ah.  This is probably a bigger problem as we haven't decided on the standard way to express that I don't think.  It should be the same mechanism used in BibTex.
