### ISSUE TITLE
Determinations on new CEs from collecting event take time to show up

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1991]
**Describe the bug**

Determinations on new CEs from collecting event take time to show up

**To Reproduce**
1. When I use the "Add/Current" button to create new specimens from a collecting event
2. Then I add determinations
3. And I wait for the COs to be created
4. The COs are created and visible but the determinations do not show up immediately. 

All of these COs should have determinations
![image](https://user-images.githubusercontent.com/11411328/105726174-6636e380-5eef-11eb-8b95-0d975d62ca2a.png)

"Coleoptera 4" with determination visible in annotator, but not CO table:
![image](https://user-images.githubusercontent.com/11411328/105726364-9da59000-5eef-11eb-844d-478ffa43b5a8.png)

**Expected behavior**
Should see create determinations immediately for real-time validation. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox - Sandworm
- Chrome

**Comment by mjy** [comment]
We confirmed this is an issue with the dwc indexing (we're using dwc index as fields for the descriptor).

**Comment by mjy** [comment]
@jlpereira do we need to catch this with spinners maybe?  Feel like this is the live-page update stuff we were thinking about doing down the road.
