### ISSUE TITLE
Georeference preview map overlaps with header bar in "Edit Collecting Event"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1992]
**Describe the bug**

When i scroll down in a CE that has a georeference and an associated georef. preview, the pane covers over the header bar

**To Reproduce**
1. When I am on/in a CE with a verbatim georef. 
2. Then I scroll down
3. See map preview pane cover over header bar. 

Pre-scroll:
![image](https://user-images.githubusercontent.com/11411328/105727349-9d59c480-5ef0-11eb-8673-c1d645881bd4.png)

Scroll down:
![image](https://user-images.githubusercontent.com/11411328/105727418-ac407700-5ef0-11eb-960b-36bec29ef8cb.png)

**Expected behavior**
Georef. preview pane/map should be behind header bar

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - Sandworm
- Chrome

**Comment by jlpereira** [comment]
This problem is present only on sandworm, works fine on sandcastle and development branch.
