### ISSUE TITLE
No columns in label preview/printer

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#1993]
**Describe the bug**

When I print a long set of labels that require "columning" - these columns do not show up/get formatted at all

**To Reproduce**
1. When I  generate a lot of labels that should get "columned" (e.g. 100 QR codes)
2. Then I click preview/print
3. See one long column instead of a specified number of columns

Specs:
![image](https://user-images.githubusercontent.com/11411328/105729533-f4f92f80-5ef2-11eb-80df-23100f3a960b.png)

Result (no columns):
![image](https://user-images.githubusercontent.com/11411328/105729581-03474b80-5ef3-11eb-942e-d675b1304e91.png)

**Expected behavior**
Should get columns

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox - Sandworm
- Firefox

**Comment by mjy** [comment]
@tmcelrath I think resolved ... maybe?

**Comment by tmcelrath** [comment]
Not in production? Works in Sandworm I think.
