### ISSUE TITLE
New error message when creating a new image 

### ISSUE THREAD

**Issue by szaslow** [SpeciesFileGroup/taxonworks#1995]
Last night I was trying to create a new image and followed the same protocol as I have usually done. I add my name into the author section, click on the proper license (CC0.10), click on collection object, cross pattern with a red outline and properly add in the labels for each of the four quadrants. I add the repository (UNHC), preparation (pin) and the OTU. When all of the images had properly downloaded I clicked on the "apply" buttons for the attribution and depiction summary lines. The attribution summary worked just fine, but when I clicked on the depiction summary button I got a new error message that I have not seen before. Typically when I press apply, new hexagons are created within the "TODO Breakdown" tile, but this time nothing appeared. When I go into the "Browse Collection Objects" tile the "images" appear. They have the correct OTU but nothing else appears. I am unsure of how to remedy this or what I need to be adding to the "New Image" page to correct this issue. Thank you!
![Screen Shot 2021-01-26 at 11 32 52 AM](https://user-images.githubusercontent.com/78037634/105873970-0d884900-5fca-11eb-95df-c893ad275931.png)

![Screen Shot 2021-01-25 at 10 02 07 PM](https://user-images.githubusercontent.com/78037634/105873535-96eb4b80-5fc9-11eb-996f-d52cea4e00a6.png)

**Comment by mjy** [comment]
Thanks @szaslow, looking into this now.

**Comment by mjy** [comment]
@jlpereira this might be yours, some combination of parameters not being added?  I don't *think* we changed depiction handling in 0.16.0?

**Comment by jlpereira** [comment]
Looking

**Comment by LocoDelAssembly** [comment]
@mjy @jlpereira is this important enough to make a new release now? I deployed to sandboxes 354520f.

**Comment by jlpereira** [comment]
Yes @LocoDelAssembly pushed a couple of new fixes
