### ISSUE TITLE
TaxonName#year_of_publication is not validated (and has some bad values)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2000]

**Comment by proceps** [comment]
What should be validated?

**Comment by mjy** [comment]
0, 999, 19444 are terrible years.

**Comment by proceps** [comment]
Keep in mind, that free text may still be required in some cases. For example: 
THAUMALEIDAE Bezzi, 1913 (1847).
Some replaced family group names have their own publication date an also a precedence date of replaced names. It is very hard to formulate this and some flexibility is definitely needed.

**Comment by mjy** [comment]
So far it has never been required, and we use the field to calculate, I
don't think we should allow exceptions, its too fragile.

**Comment by mjy** [comment]
Validation already exists. Bad data must have been entered prior.

**Comment by mjy** [comment]
Closing for https://gitlab.com/SpeciesFileGroup/sfg-taxonworks-data/-/issues/4
