### ISSUE TITLE
DwC Importer - Problem with auto-creating preparation types

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2001]
Just seen comprehensive form in sandworm (screenshot below). I guess I should change mapping from find-or-create to just find and error the import if not found? Given preparations are community data (and cannot be made selectively available per project?) looks I should put the constraint that the preparation must exist in the database already. Not sure of alternatives?

![image](https://user-images.githubusercontent.com/4991925/106043011-91baf900-60bc-11eb-9d68-c6050114380d.png)

**Comment by mjy** [comment]
@LocoDelAssembly Just was reminded of this as well. I'm OK with requiring prep types in DB to start.  Will force convergence/improvement of data.
