### ISSUE TITLE
Soft validation - Determined before Collected should bring up soft validation

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2005]
On a collection object it is generally impossible to have a collection object that has a determined date before its collecting event. If this happens soft validation should trigger

**Comment by mjy** [comment]
Great catch/suggestion.

**Comment by tmcelrath** [comment]
You can thank Heidi for this one, she caught it. Would tag her but she's not on GitHub yet I don't think.

**Comment by tmcelrath** [comment]
@hah1009

**Comment by mjy** [comment]
I think this should be a hard validation actually?
