### ISSUE TITLE
CoL - CoLDP exporter adding accepted names as synonyms of themselves

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#2006]
**Describe the bug**

The CoLDP exporter is adding accepted names as synonyms of themselves. This is not necessarily a major issue because the CoL importer won't allow it anyway, but it does get flagged with `ACCEPTED_ID_INVALID` and `ACCEPTED_NAME_MISSING` issues and it will probably affect WCO Lite if they start rendering synonyms at some point.

https://data.catalogueoflife.org/dataset/2257/verbatim?issue=accepted%20id%20invalid

**To Reproduce**
1. When I  CoLDP export Gryllotalpidae from Orthoptera Species File
2. Then I import it into ChecklistBank
3. Synonym names are flagged with [`ACCEPTED_ID_INVALID` and `ACCEPTED_NAME_MISSING` issues](https://data.catalogueoflife.org/dataset/2257/verbatim?issue=accepted%20id%20invalid) and it's because the accepted names are referencing themselves as synonyms.

Here's the [example dataset](https://github.com/SpeciesFileGroup/taxonworks/files/5888867/coldp_otu_id_30999_2021-01-28T17.00.29%2B00.00.zip), but the summary below shows the issue:

### Name.tsv
ID | basionymID | scientificName | authorship | rank | uninomial | genus | infragenericEpithet | specificEpithet | infraspecificEpithet | publishedInID | publishedInPage | publishedInYear | original | code | status | link | remarks
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
**31021** | 31021 | Gryllotalpella lawrencei | Cadena-Castañeda, 2015 | species |   | Gryllotalpella |   | lawrencei |   | 38073 | 451–490 |   | TRUE | ICZN | http://purl.obolibrary.org/obo/NOMEN_0000224 |   |  

### Taxon.tsv
taxonID | nameID | status | remarks | referenceID
-- | -- | -- | -- | --
**31003** | **31021** |   |   |  

### Synonym.tsv
ID | parentID | nameID
-- | -- | --
**31003** | 31000 | **31021**

**Expected behavior**
Accepted names shouldn't be set as synonyms of themselves.

**Environment (please identify where you experience this bug:**
- sandcastle.taxonworks.org
- Firefox 84.0.2 (64-bit)

**Comment by LocoDelAssembly** [comment]
https://github.com/SpeciesFileGroup/taxonworks/blob/01d953976d56ea84c7aae18a63f226a0fc17188f/lib/export/coldp/files/synonym.rb#L40

Is a matter of just replacing that with code below or are there deeper problems? Checked sandcastle data for the provided example and seems to be fine.

```ruby
        next if o.taxon_name&.is_valid?
```

What is the correct treatment for OTUs without taxon name? For synonym file I guess that all should be ignored, but there is a comment above saying `# otus are valid and invalid`, but unsure what would that mean for OTUs with no taxon name.

**Comment by mjy** [comment]
@gdower still an issue?

**Comment by gdower** [comment]
Fixed in latest export
