### ISSUE TITLE
TaxonName#name is allowing spaces and `[sic]`, at least the latter is a big problem

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2009]
Something must have softened the validation too much, arg.  

* [ ] Add specs to ensure that `[sic]` is never allowed
* [ ] Review reasons spaces are allowed

**Comment by proceps** [comment]
[sic] is not alowed as a part of the name. It is notly added as a cached value. Excluding it from chached would be huge problem for the taxon_name search. There will be no any means to distinguish misspellings and misapplications from available protonyms.

**Comment by mjy** [comment]
This is in `name`, not cached, see title.

**Comment by mjy** [comment]
@proceps for what reasons would space ever be allowed in `name`?  Given current bad data there is a single record, see below.  I would prefer to require that to be `2maculatus` and enforce a stricter ruleset.  At present the lack of the rule is doing much more harm than good as you can see from the data.

```
 500949 | 2 maculatus
 263126 | sp. a
 513447 | var. b
 500510 | tredecim articulatum
 508543 | gallae quercus
 491021 | bimaculati pennis
 493394 | |near| andalusicus
 495537 | n. 27
 495522 | rosae aurata
 495524 | salicis strobili
 500950 | aeneus ramicornis
 500964 | fuscus ramicornis
 645765 | incertae sedis
 659625 | incertae sedis
 648579 | incertae sedis
 660157 | Z_Non-Teneb or Bupe genera
 649103 | incertae sedis
```

**Comment by mjy** [comment]
I've added this restriction.  If it becomes a problem we can revisit.

**Comment by proceps** [comment]
Some original spellings of the mane may have space. Something like "santae rosae" or "st. rosae".
I believe the most of the problem come from the button "Non Latin" which basically allowed to push anything into the system. I would prefer unrestricted use of the field for the original, misspelling, non Latin name, not binomial names. If you put restrictions, you loose resolution of the project.

**Comment by mjy** [comment]
Besides- if you truly need the exception, you can check the data in verbatim_name (which 3i seems to be using incorrectly btw).  That keeps all the garbage in the garbage pile.
