### ISSUE TITLE
No type fixation after 1930 is grayed out

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2010]
I need help with an issue:
The genus Marua was originally cretaed by Roewer in 1935 with 2 species and no type. Therefore it is a nomen nudum
Starega (1992) listed Marua and chose one of them as type, so genus authorship is Starega 1992. In my catalogue it reads like this:
![image](https://user-images.githubusercontent.com/46284943/106358177-2a35c100-62e9-11eb-814c-81e6345f78d2.png)

I deduced that to represent this I should create a "new taxon name" Marua Roewer 1935 and indicate in the "status" module that it is a nomen nudum because there was no type fixation after 1930:
![image](https://user-images.githubusercontent.com/46284943/106358205-59e4c900-62e9-11eb-9f5e-402f83f1591f.png)

But for some reason, this option is grayed out and I cannot choose it.
How should I proceed?
I already linked Marua 1935 with Marua 1992:
![image](https://user-images.githubusercontent.com/46284943/106358222-8567b380-62e9-11eb-8fbc-0aa5aa357add.png)

**Comment by adrik29** [comment]
To make it easier I'm adding a link:
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=325146

**Comment by adrik29** [comment]
Well, I don't uynderstand why, but after I linked the species with the original genus the buttons turned green.
I don't know what happened but now it is working:
![image](https://user-images.githubusercontent.com/46284943/106358347-77666280-62ea-11eb-8162-bfe66596bf31.png)

![image](https://user-images.githubusercontent.com/46284943/106358361-864d1500-62ea-11eb-8e58-bbb96f76d594.png)

**Comment by proceps** [comment]
Sometime the page need to be just refreshed. The status selection is dependant on the taxon rank. When a new taxon is created an saved, the list of ranks is not refreshed automatically. Although there is a work around, the issue could be addressed.

**Comment by adrik29** [comment]
@proceps = Thanks, Dmitry, it took me a while to discover the **refresh** aspect.
Now it is working fine and it makes all sense in TW to create a new genus name as a nomen nudum which is the one that actually takes part in the original combination with a species, because that is exactly what happened in real life. And I understand the use of the word "linked", because if it is a nomen nudum, technically it cannot be a homonym or synonym, although in practice we treat it like a homonym.

**Comment by proceps** [comment]
@adrik29 Yes we are trying to be more precise in TW. The name cannot be treated as a synonym, unless it is available. It is not a homonym either, for the same reason.

**Comment by jlpereira** [comment]
@ adrik29 I pushed a fix for this, it should be reflected on the next update. If not please reopen
