### ISSUE TITLE
ColDP: (NoMethodError) "undefined method `id' for false:FalseClass"

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2011]
This is causing exception notifications pretty frequently. More info: https://github.com/SpeciesFileGroup/taxonworks/commit/6a21cc71c85c27066829dc36fcd1018b3a3fa97c#r43626667

**Comment by mjy** [comment]
This is due to missing indexing on taxon names, around 160k combinations need to be re-saved.  We'll need a (rake) task, preferably in parallel, to be run to ensure the cached value is there.  This happend as Lep Index pre-dates this cache.

**Comment by mjy** [comment]
Note this is a skip fix of sorts.  New downstream issues can be added to better address the issue of having multiple OTUs per taxon name.  Next steps are to examine CoLDP exports for datasets like Orthoptera.
