### ISSUE TITLE
Task - New Taxon Name - relationships

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#202]
```
   when I see the Relationship section
     then I should see
         the relationship select widgets(s)
         the name search box 
     and the select widget should be on top
     and the user can start by selecting either option
        and depending on the current piece of data added the filter narrowing the other option can be applied
```

**Comment by mjy** [comment]
I want to argue for leaving this until we hit production and get more feedback.

**Comment by proceps** [comment]
I discovered another problem with the existing model. I found, that if I already selected the related taxon name and a relationship. I cannot modify it. The only way to do it, is to delete the relationship and to create a new one. What happens if you have associated data? It would be nice to keep it updatable.

**Comment by mjy** [comment]
It will be made updateable when we get the Radial annotator.

**Comment by mjy** [comment]
@proceps I think we can close this now, right?
