### ISSUE TITLE
Scrolling after clicking "Retry" errored records in DWC importer causes visual glitch where it looks like wrong records are being retried/imported

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2022]
**Describe the bug**

When I have a DWCA dataset, and I click "Retry" or "Import" and then quickly scroll, the gray temporary box moves to a new spot, but the correct record retries/imports. 

**To Reproduce**
1. When I  am in DWCA importer.
2. Then I have records that are errored and need retried, or have new records to import.
3. And I quickly click import/retry and scroll down quickly
4. See a visual glitch where the wrong records look like they are importing. 

**Expected behavior**
Temp. gray box should stay with records clicked on. 

**Screenshots**
Can't get screenshots, happens too fast

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandworm
- Chrome

**Comment by mjy** [comment]
@tmcelrath @jlpereira still an issue?

**Comment by tmcelrath** [comment]
Woof. I don’t think so?

**Comment by jlpereira** [comment]
I think this was fixed. Close?

**Comment by tmcelrath** [comment]
Close.
