### ISSUE TITLE
Task: New task for calculating Statistics of data content 

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#2024]
We need a task  for nomenclature statistics, that provide a count with valid/invalid species, authors, etc. Like it is present on the image below
![image](https://user-images.githubusercontent.com/33158036/107402379-a5198b80-6ae2-11eb-8292-f6fb0eacad13.png)

**Comment by proceps** [comment]
This is already covered by Nomenclature Stats task and additional project related stats.

**Comment by MMCigliano** [comment]
Thank you!
