### ISSUE TITLE
OTU radial - Observation matrix sector

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2033]
![image](https://user-images.githubusercontent.com/5597748/107667141-e8940700-6c54-11eb-827c-c1eddbf2f768.png)
When I select a taxon in Browse nomenclature, I can open OTU radial and should be able to quickly add OTU to a matrix. When OTU is already in the matrix, I can quickly navigate to the row coder or to the image matrix.
However, if the OTU is not in the matrix, I click on the matrix name and nothing happens. Expected behaviour is similar to the Matrix Dashboard interface. When I click on the matrix name, The OTU, if it is not in the matrix, should be added to the matrix (a warning modal is presented). After OTU is added to the matrix, the Row coder or image matrix interface is open in the next tab window. The behavior should replicate the Matrix dashboard interface.
Small addition, if the matrix is pinned to the pinboard, a pin should be present in the matrix selection sector. 
![image](https://user-images.githubusercontent.com/5597748/107668156-f9914800-6c55-11eb-8ae0-a3f19cc9d143.png)

**Comment by proceps** [comment]
It works, but with the Matrix row Coder redirect, If I have an Image matrix, then nothing happens.

**Comment by proceps** [comment]
In the Matrix Hub, I have both option depending on the matrix type.

![image](https://user-images.githubusercontent.com/5597748/109225908-93dbaa80-7783-11eb-8e4c-6a038b339480.png)

**Comment by mjy** [comment]
You are using development?  This is not live yet.

**Comment by proceps** [comment]
Yes, development

**Comment by proceps** [comment]
Thanks
