### ISSUE TITLE
DWC Importer: Non-parsable names should be imported verbatim, not "errored"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2049]
When I am importing a dataset with collectors (in the "recordedBy" field) that can't be parsed (e.g. initials), or some other non-standard format, currently, the names return as "errored". However, these names are verbatim names and can't be "improved" any, so they should just be imported into the verbatim Collectors field. 

Two options
1) Not returned as "errored", just import only to verbatim collectors field.
2) Return as "errored" allowing for improvement or modification, with an option to just "only import to verbatim" once you have reviewed the errored records. 

![image](https://user-images.githubusercontent.com/11411328/108261820-bf2e1c00-7129-11eb-828d-0cb1d02cab07.png)

**Comment by tmcelrath** [comment]
Once this issue is fixed, I have no other issues with DWC importer being pushed to production.

**Comment by LocoDelAssembly** [comment]
Option 1 used. Option 2 would still not solve cases when actual parsable name cannot be determined.
