### ISSUE TITLE
Task - Merge people

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2050]
When merging two people, please do add missing fields to the correct person. for some reason (probably from some export). Many people has their inicials mistakenly placed into the preffix field. When merging this record, which could be just one use, with a record, which has hundreds of uses, it adds unneded preffix to an existing records, and emmend all related records (probably sources), with wrong author string (takes a lot of time). Lets assume, that the first selected author and correct, and add all attributes as alternative values.

**Comment by proceps** [comment]
The main problem is, you do not even notice that your correctly spelled name is update, unless you emidiately check the source with this author to see how it looks like.

**Comment by mjy** [comment]
We already add attributes, and do assume this.  Can you point me to the data in question?

**Comment by mjy** [comment]
There are also significant tests, can you add a failing test that illustrates this problem?

**Comment by proceps** [comment]
I already resolved several names. I do not have those any more. It should be possible to filter people which has a preffix field and do not have anything in the first name field. The attributes are created correctly. Problem with the wrong preffix, which is being added to the correctly spelled name, which should not have any preffix.

**Comment by mjy** [comment]
But when there is a "right" prefix, it is lost.  I don't see a way around this.

**Comment by proceps** [comment]
I assume that the first name, which it is merged to, already have proper prefix in place.

**Comment by proceps** [comment]
You may still lose the data if you merge, for example complete first name to inicials. My practice is to take a properly resolved name, and add something, which is incomplete. But extra data in fields may completely destort the name. It is better to put those as alternative attributes. Not update existing fileds of the record.

**Comment by mjy** [comment]
I think this requires a spec to illustrate the failure.

The code should work by assuming the first Person and its values are correct.  If any value (of the 4) is empty, then it is populated by field in the merged person.  The fact that bad data (e.g. should have been in First name, but was in Prefix) was sloppily entered means that data should be fixed before merge?

Keep person: Prefix: Jr, Last name: Jones
Destroy person: First name: Jim, Last name: Jones

Merge result:  Jim Jr. Jones

**Comment by mjy** [comment]
"You may still lose the data if you merge, for example complete first name to inicials.".  This should never happen, if it is we need a spec.

**Comment by proceps** [comment]
"sloppily entered means that data should be fixed before merge?" 
why would I need to fix the data before merging? There could be an option checkbox to ignore missing data. Still could be useful. I just merged few names which were just misspellings. I would not want to fix those before merging. Adding alternative values as attributes in this case does not also make much sense, since those are just typing errors.

**Comment by mjy** [comment]
I would prefer to not give people the option to inadvertently delete data by checking options that will raise confusion for people.   It seems reasonable to make a final pass on the merged person after the merge is executed.  Merge 200 -> 1.  Edit one person.  This doesn't seem bad.

**Comment by mjy** [comment]
Regardless.  There is at least one real issue- if values from the merge target (Person that is destroyed) are over-writing existing data from the select target this is a big fail that needs to be promptly addressed.

**Comment by mjy** [comment]
Added another spec, they are in spec/models/person/merge_spec.rb.

I can't replicate the over-written values.

**Comment by proceps** [comment]
The values are not over-written. I am just saying if you have one person with initials and another person with fully spelled first name. For example "C. Linnaeus" and "Carolus Linnaeus" the fields are not overwritten. This is correct. But if you merge the second person to the first, you will end up with "C. Linnaeus" and a single person. "Carolus" will end up in alternative values and never displayed. That is what I call the reduction of the information. That is why, I assume, when I merge, I select one completely curated name and merge to it identical or partially curating name. What I propose, that the second name is only add alternative values to the fields of the record, but never changed the field itself. Even if you say it is a correct prefix. There are many cases when the prefix could be either treated as part of the last name or true prefix, and I saw many cases when both formats are present to the database. Obviously, on of them is incorrect, and correction of other names before merging them does not make any sense. Especially taking into account, thousands of the names which were created during the migrations which are duplicating each other with the idea that SOMEBODY later have to resolve those names. I already described my problem. I have well curated list of thousands of names. Somobody creates hundreds and hundreds of uncurated names which destruct my ability to find a correct person in the list. Now I have to finish somebody’s job to resolve/merge unneeded names, either because curators in other projects did not care to resolve those for themselves or because the system allowed them to do so. So, I want to be able to effectively merge the names, assuming that I already have a curated name, which I do not want to be altered. The interface does not show the final result of merge, so you do not even know what happens with the persons name after the merge. Fixing the name after merging is not a big issue. The biggest problem is. If I have a name, something like “DeLong” which has about 2000 uses in the database. And somebody enters “Long, De” (where “De” is a prefix), just a single record. When I merge two, I ended up with “DeLong, De”). Yes it can be fixed manually, but having 2000 uses, the merge fires 2000 updates on all records which has DeLong as an author, it takes about 2 min, during which you do not even know if the system just frozen and something is going on on the background. After that you realized that you curated name got change. You fix it and save, than you wait another 2 min during which 2000 entities got updated with the new name. I believe it is very inefficient way of working. So far I did not run into an example when the second name really provided any additional information to what is already present in a curated name.

**Comment by proceps** [comment]
Alternative solution. Is to hide all the noise (hundreds of unresolved people) from other project and show me only the people from my project, than I will be able just to ignore the problem.

**Comment by debpaul** [comment]
> There could be an option checkbox to ignore missing data. Still could be useful. I just merged few names which were just misspellings. I would not want to fix those before merging. Adding alternative values as attributes in this case does not also make much sense, since those are just typing errors.

I'm still learning about this issue. Jumping in at this point @proceps. Note that this seems similar in some respects to merging data in Symbiota, _where if the software detects a duplicate herbarium sheet record_, it shows you all relevant dups (or possible dups). Then you
- choose to "import all data from a given record" (overwriting what you have)
- choose to "import only data from fields not yet populated in the current record"

(To non-herbarium folks, these are "true dups" (as in herbarium sheets from the  same plant and collecting event but stored in different herbaria. I don't mean duplicate records in the same herbarium database, but "across" the databases).

I would wonder where to store variations on a person's name (aliases?). These go into "alternative values", is that correct? These are very useful!

**Comment by proceps** [comment]
@debpaul alternative spellings are already automatically created a "alternatives values" when you merge two people for example if you merge two names, one with diacritical marks, another without. Alternative values could be seen on the Person page, or using the radial annotator.

**Comment by mjy** [comment]
@proceps part of your exasperation is maybe a reflection of this- https://github.com/SpeciesFileGroup/taxonworks/issues/2054.  Having some screenshots of the autocomplete *failing* your queries might help to visualize your frustration.

That said- we won't permit projects to ignore the outer world when it comes to people, we can improve how/when we find people, and other peole will ultimately help you.  This is a balance that we need to work out in the user interface and curatorial experience.

**Comment by proceps** [comment]
@mjy you know, I am not against shared data, as long as it does not disrakts the workflow. Prioritizing people in the search box, may help, I balieve we have another issue opened for this. But merging people is another issue. I really appleciate the option that now I can merge multiple people at once. It is really useful. But merging attributes from multiple people to a single one is still a serious issue. I already merged several hundred of people, I never experienced any single case when I would get some additional information from the second record. Alternative spelling - yes, but missing data - no. But of those few hundred, I alredy experience more than dosen of cases where the prefix (or some other field) is incorrectly placed in the wrong position. And mergind two name just distorts the good record. All intended benifits are negated with unexpected behaviour.
