### ISSUE TITLE
Task - DwC Importer - as a curator I want to add multiple specimens to a container (virtual/not)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2055]
This will be a priority to facilitate getting Brian's data loaded, perhaps already handled.

@LocoDelAssembly @jlpereira we will need to either default behaviour or allow a the curator to enter a mode in which the import can create virtual containers when the identifier is the same for multiple rows.  Perhaps this is already done, etc.

E.g. in `container mode`  this results in 5 Collection objects grouped into 2 Container::Virtual and the identifier is added to the ContainerVirtual (maybe automagic in code already), not the collection object.

individualCount | lifestage | Sex | occurrenceID 
-- | -- | -- | --
1 | adult | male | 1 
1 | adult | male | 1 
1 | adult | male | 1 
1 | adult | female | 2 
1 | adult | fmale | 2

**Comment by LocoDelAssembly** [comment]
How would this go? The first successful import creates a CollectionObject with identifier as usual, but if later a duplicate is detected "mutate" the CO to no longer have the ID and put it inside the container along with the record that is being imported?

**Comment by jlpereira** [comment]
Yes, move the identifier to the container

**Comment by mjy** [comment]
Right.  I'm almost positive that whe do the mutation already in the background, you can test:
* Create specimen with catalog number
* Put specimen in Virtual container
* Check identifier_object_type

If we *dont* do this in the model, we should.

**Comment by mjy** [comment]
@jlpereira is going to say we don't do it, and get mad that we should have done it so he doesn't have to do it in the UI! XD

**Comment by LocoDelAssembly** [comment]
This should be origin-scoped?

**Comment by mjy** [comment]
I don't think it's related to origin.

**Comment by LocoDelAssembly** [comment]
OK, if any catalogNumber collision is detected then mutation will occur regardless of existing record origin. I think we can start with default behavior but need explicit opt-in for safety later.

**Comment by mjy** [comment]
Exactly.  We should only trigger this mode with opt-in. *MOST* incoming DwC data will not want this, but rather identifiers should error as not-unique.

**Comment by mjy** [comment]
Please open a new issue if auto-move of identifier to container is not done.

Also- if preparation type is provided, then if it matches Container type, you can use that container type rather than Container::Virtual.  @jlpereira can explain.

**Comment by LocoDelAssembly** [comment]
The feature is live. Can be enabled with `Settings > Containerize specimen with existing ones when catalog number already exists` checkbox.
![image](https://user-images.githubusercontent.com/4991925/108890461-5f81b600-75ec-11eb-8bc8-dc4e587083e5.png)
