### ISSUE TITLE
404 not found message when destroying an OTU

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2062]
**When Destroying an OTU a blank page with the following message apears "404 Not Found"**

When I want to destroy an OTU I created myself, I choose the one I want to delete, from the list and open it. 
Then I click on the Destroy boton above and a white page with a message "404 Not Found" shows up with the followinf url: 
https://sandworm.taxonworks.org/otus/256612

![image](https://user-images.githubusercontent.com/63611746/109250176-f6569a00-77c7-11eb-91f8-8ad22896f37e.png)

Then I click on the back botton of the navegator twice and it takes me again to a previous page. When I go to the Hub again the message "Otu was succesfully destroyed" cames up. 

![image](https://user-images.githubusercontent.com/63611746/109250392-5ea57b80-77c8-11eb-81ff-3f2698175396.png)

See why it does not flow correctly and this 404 not found shows up.

It happens to me working on sandworm.taxonworks.org

**Comment by mjy** [comment]
Thanks @mabecabrera.  To confirm, this is from the OTU list right?  We'll fix the routing.

**Comment by proceps** [comment]
I experienced it too. The OTU is destroyed, but the page is not redirected, after reload, the address is not found (because OTU is deleted). It only happens when OTU successfully deleted

**Comment by LocoDelAssembly** [comment]
This is a systematic problem, also happens in Data > Taxon Names, deletion takes you back to show instead of index. I guess this problem is more widespread. When using tasks it is all fine.

`redirect_back(fallback_location: (request.referer || root_path)` will have to be smarter.

**Comment by mabecabrera** [comment]
> Thanks @mabecabrera. To confirm, this is from the OTU list right? We'll fix the routing.

I select the Otus List from the Data Board, and then, in the TAXON NAME page I use the Destroy Button.

**Comment by LocoDelAssembly** [comment]
Solved with #2223
