### ISSUE TITLE
Task - New Taxon Name - autofix for soft validation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#207]
Some of the soft validation issues could be fixed automatically. Should we provide a fix button?

**Comment by proceps** [comment]
Please prioritize.

**Comment by mjy** [comment]
Also move this to top of Ready list in project.

**Comment by mjy** [comment]
This is not technically a blocker, it's just high priority.

**Comment by proceps** [comment]
Soft validation fix in Edit TaxonName could be implemented by simply clicking Save button, or as a separate button in the soft validation Section.
