### ISSUE TITLE
Observation Hub Matrix link broken

### ISSUE THREAD

**Issue by rkres001** [SpeciesFileGroup/taxonworks#2071]
Bug:
"Observation Hub Matrix”  link on “New/Edit Descriptor Page” is broken. When I click on it, I am taken to the 404 error page
![bandicam 2021-03-02 09-34-22-304](https://user-images.githubusercontent.com/32372768/109690153-e24dc800-7b3a-11eb-94a4-2c431c6af86b.jpg)
![bandicam 2021-03-02 09-36-13-124](https://user-images.githubusercontent.com/32372768/109690158-e5e14f00-7b3a-11eb-9236-6a08c4f75c72.jpg)

Expected behavior
I expect the link to return me to the observational matrix hub

Environment (please identify where you experience this bug:
UCD 2019-09-30 18:56:32 +0000

**Comment by mjy** [comment]
@rkres001 thanks for your very first issue here.  Hope to see many more... sort of.
