### ISSUE TITLE
 Controlled Vocabulary for Sampling Protocol Methods

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2074]
It would be very useful to have a Controlled Vocabulary for Sampling Protocol Methods when using Comprehensive specimen digitization or New collecting event tasks. Such as Preparation have a list to choose from.

**Comment by mjy** [comment]
See "Protocol Relationship" in radial annotator.  This could in theory be applied to CollectionObject or CollectingEvent, depending on what one is describing.
