### ISSUE TITLE
Cached subgeneric names rendering is not capturing italics correctly?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2075]

**Comment by mjy** [comment]
@proceps I think this is likely fixed, we just need to re-index the data?

**Comment by mjy** [comment]
![Screen Shot 2021-03-03 at 10 46 22 AM](https://user-images.githubusercontent.com/22600/109849321-ddf6dd00-7c16-11eb-85af-af64b9f00063.png)

**Comment by proceps** [comment]
I checked, it is a real one. Probably related only to generic combination, and since we could not create those before, it was never noticed.
