### ISSUE TITLE
Task - Comprehansive - Geological periods

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2079]
As a curator, I would like to be able to record the basic geological timeline as Eon, Era, Period or Epoch. Preferrably the same way geographical area is recorded. Single search field for all diffirent ranks.

**Comment by mjy** [comment]
For OTU?

**Comment by proceps** [comment]
This one was specifically for Collection object. 
although OTU would be also interesting option, like an Asserted Distribution.

**Comment by debpaul** [comment]
See https://dwc.tdwg.org/terms/#geologicalcontext for future of exporting TW geo data to DwC.

**Comment by proceps** [comment]
same as #65
