### ISSUE TITLE
Task - New Taxon Name - limit parents to valid

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#208]
Limit the parent list to VALID protonyms only. (It has all invalid names and combinations now).

**Comment by mjy** [comment]
I think we have this option in autocomplete filter already, just need to apply it in the request.  I'll look at it.

**Comment by mjy** [comment]
@proceps Can you test?  I think this works now.

**Comment by proceps** [comment]
@mjy It works, my main problem now that the genus and subgenus name now in two opposite sides of the list. Another issue, the list returns me the values from both ICZN and ICN.

**Comment by mjy** [comment]
@proceps - thanks!  we can solve the latter half by dynamically adding
code, that's easy.  We should lay out an algorithm for autocomplete though,
to solve first bit.  If you want describe behavior given test cases, i.e. a
priority for results, something like

```
    exact cache match (limit 1)
    wildcard at end match (limit 10, order by cached, smallest first)
    wildcard both ends (limit 10, order by cached, smallest first)
    ...etc.
```

**Comment by proceps** [comment]
@mjy I cannot predict the proper order now. I do not think we should limit anything to one. Yes you probably right, about the order. And I will have to use it more extensively with real data to find this out. For now, I just see obvious: subgenus should be next to the genus in the list. And it probably should have a priority. Try to search for '%(Genus)' and give it priority over 'Genus'. It should work for both, nominative and not nominative taxa.

**Comment by mjy** [comment]
@proceps the :iczn vs. others issue is actually #20.  We don't know the code at this point, because, in fact, we want to be able to add any code.

**Comment by proceps** [comment]
@mjy Accepted :)
