### ISSUE TITLE
Task: Collection Objects Filter

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2080]
Curating data. We need additional filters in the Collection object Filter URGENT!!!

I need to be able to enter a Null field.
For example: I need to find all the records without a repository, Or without a determination, or without type status.

URGENT!!

**Comment by mjy** [comment]
Please add specifics beyond these:

* [ ] With/out determinations
* [ ] With/out repositories
* [ ] With/out type status
* [ ] With/out collecting event
* [ ] With/out identifier

**Comment by mmkohler** [comment]
With/without Depiction
That is the only other one I can think of at the moment.

-Michelle

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mjy** [comment]
That should be already done?

**Comment by mmkohler** [comment]
I dont see it in the Collection objects filter. It would be helpful to be able to combine the image/no image option with the other features.  As in 'X collecting event' with image. Etc.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by proceps** [comment]
I would add 
[ ] with/without geographic area
[ ] woth/without georeference
