### ISSUE TITLE
TaxonName autocomplete - valid/invalid

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2086]
As a user I need to be able to distinguish valid and invalid TaxonName in the authocomplete search box. Combinations are already marked, but not the synonyms.

**Comment by mjy** [comment]
I just noted this too, IIRC we have it for OTUs, but not TN.  Will do.

**Comment by proceps** [comment]
or even better if we can distinguish available and unavailable name, we already do this, when we build TN relationships. In that case only available names are displayed.

**Comment by mjy** [comment]
I don't think we can do that as a general case, the autocompletes are
everywhere.  It's something for specific uses.

**Comment by proceps** [comment]
I have problem with family group names, If I have several family group forms attached to valid, name, it is hard to distinguish what is a real one, what is subsequent use. It will be easy to distinguish when the name is valid, but if the family is a synonym, I will still have the problem. The same is also apply to nomina nuda. If I have a nomen nudum linked to a synonym, it is hard to distinguish between real protonym and nomen nudum.
I think it will be useful to make this generic everywhere. Today I had to reassign a number of OTUs to different protonym, because those were linked to a wrong one.

**Comment by mjy** [comment]
Can you screenshot some examples of the problematic result?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/110002222-c4b76480-7cda-11eb-98ec-98cc7998706e.png)
One name is a synonym, another one is nomen nudum. I always have to reference Browse nomenclature to pick the right one.

**Comment by mjy** [comment]
Thanks
