### ISSUE TITLE
Task - New Taxon Name - part of speech

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#209]
'Part of speech' should not be on the list of available options.

**Comment by proceps** [comment]
Thera are 5 options available
* Part of speach
*Adjective
*Noun in opposition
*noun in genetive case
*participle

There should be only 4 options. The first one is a parent class. It should not be on the list

**Comment by proceps** [comment]
part_of_speech.assignable = False
The others are true

**Comment by mjy** [comment]
Pull, and rebuild.  Works for me.
