### ISSUE TITLE
Task - Browse OTU - options to toggle scope of map  [was nesting of species geography under genus]

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#2093]
**localities are not amalgamated under a higher level taxon**

If I go to the genus Chalcis, the otu page shows a map distribution of only India ( the one locality entered at the genus level).

It would be much better to draw in the geography from all of the children to show the true distribution of the genus (worldwide). Similarly, the same can be said of each higher level taxon.

... and why not other otu relationships as well such as hosts and associates?

**Comment by mjy** [comment]
@JohnHeraty thanks very much for logging this, was just pondering how many issues we've discussed that have been burried in our meeting minutes.

Couple of gentle hints about filing an issue:
* Identify which Task, or page/section is being referenced.  @mjy  can infer, but TW is big, and there are numerous other developers who may need to understand specifics, so pointing us to what you're seeing helps everyone.
* Add a (annotated) screenshot if possible.  A picture is worth many words.  You can use shift-command-4 to draw a window on your screen.  The result is a screenshot added to your desktop.

**Comment by proceps** [comment]
It would probably make sense to convert dots (if the data comming from specimens) to the country or state shape to display the distribution of a genus or a higher taxon.

**Comment by JohnHeraty** [comment]
a screenshot does not work, so here is the url to the problem. 
https://sfg.taxonworks.org/tasks/otus/browse/93578

Chalcis has a huge number of descendant species. Assuming that each of the species has a distribution, none of this is being aggregated to the genus level, which shows up now as just India for the single genus level record that has been input. At a higher group level, the geographic information should be amalgamated from the descendants - however that information is being inputted (shape or dot) for the otus. 

As an example, Chalcis canadensis has a North American distribution that is well documented but it is not being pulled to the genus level:
https://sfg.taxonworks.org/tasks/otus/browse?taxon_name_id=468127

**Comment by mjy** [comment]
@JohnHeraty https://support.apple.com/en-us/HT201361

**Comment by proceps** [comment]
same as #1755
