### ISSUE TITLE
Citations - add PDF sign with a hyperlink

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2098]
Add PDF sing if a documentation is available in the following tasks:
Browse nomenclature,
Browse OTU
New Asserted distribuion,
Citations by source,
and others where the ful citation is available. Maybe the citation lablel should be modified.
On click, PDF should open in another window.

**Comment by mjy** [comment]
Please break these down to specific issues, one per possible task.

**Comment by proceps** [comment]
Is it possible to update the citation label, so that PDF authomatically added to all pages where it is used?
