### ISSUE TITLE
Resolvable soft-validations

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#21]
Raised by various users and developers.  

```
   When I see a soft validation
      and it has a resolvable attribute set
        then I should see a link beside it to resolve (fix) it
```

Potential steps to implement:
- Straightforward, but not very integrated - add an attribute to soft_validation instances that points to route, this end point of this route is a form that lets the problem be resolved
- Integrated, but trickier - provide a mechanism to popup a form inline, the convention for defining these popups (partial name, RESTful request etc) would have to be worked out before hand.  Would perhaps require multiple new attributes within the soft validation, though we should try to minimize this.  Could likely take advantage of a set endpoint and a global_id.

**Comment by mjy** [comment]
This is increasingly being requested, and is becoming fairly high priority.

**Comment by LocoDelAssembly** [comment]
This is actually the kind of interface we originally thought of here to
implement the "new taxon name" task, just create the name and then click on
the soft validation errors to be redirected to forms to fill-in missing
data.

**Comment by mjy** [comment]
Are you now thinking about that approach as a replacement for the wirefame that was proposed?

**Comment by LocoDelAssembly** [comment]
Yes. I just talked with MM about this idea again and she (in a bit of a
hurry) agreed on it. I think this is a better first step before going into
creating the new taxon name task (if we discover that resolvable
soft-validations alone are not handy enough). In fact it could probably be
built on top of it, first complete basic information and in a next step you
are guided to complete the rest of the data in any order you want rather
than a single big form.

**Comment by mjy** [comment]
Thinking quickly- I think we still need the form as we designed, but it's certainly not a bad step to do this first. We need to do the following:

* Extend the invocation pattern `soft_validate(:other_soft_validation_method, set: :some_set, resolutions: ['route_name_only_no_path_or_url_postifx', ... 'other_path'])`  (prioritize the first path, but here recognize that tasks may ultimately overlap, so we might give users different views that both solve the problem- likely don't use this pattern too much, but at least make it possible)
* Extend SoftValidation (singular) with an accessor that stores an array of (see below) the resolution paths, set on initialization
* Add a helper method(s) that generated the fully qualified path to resolution, and optional other paths if there are more based on some click through event

Soft validation code is quite (very?) well tested, so we should be able to extend it quickly.  Do you want me to tackle it, or do you want to take a look (and maybe make general improvements)?

**Comment by mjy** [comment]
With f7ec60a817e you can make a soft validation resolvable by including ```resolution_with: __method__``` in soft_validations.add() (note that __method__ is literally what you use).  It feels a little crude, and not as automagic as it could be, but might be workable, and gives us the flexibility to user/not resolution with a particular soft validation instance.  Need to further document what's going on.

**Comment by mjy** [comment]
Going to close this, the existing solution provides resolvable soft validations, albeit with some extra weight.  We can open an new issue when we need specific changes.
