### ISSUE TITLE
New image task: 'Reset' button issues

### ISSUE THREAD

**Issue by juliah3** [SpeciesFileGroup/taxonworks#2101]
When uploading and annotating images with the 'New image' task, the 'Reset' button is helpful, but it would be even more helpful if a couple idiosyncrasies were ironed out.

For my use, the most helpful aspect (as is) is that pressing 'Reset' rather than refreshing/Ctrl-R leaves the staged image drop-down menus as you last had them, which saves a good amount of time.  This is excellent.

The less useful part is that it leaves the repository and taxon determination fields only half-way filled, or incorrectly filled, as follows.

For repository, the field appears to have been left populated, as you can see below:
![image](https://user-images.githubusercontent.com/76214527/110530903-ef455b00-80e8-11eb-8528-cd3ddd83ca74.png)
But when you press the apply buttons to create the records, this field is actually left blank, so your collection object is not associated with a repository.  As it stands, the user needs to remove the repository and then re-choose it in order for it to be correctly applied to your record.  
Best case outcome, clicking 'Reset' would leave repository populated correctly, so it could be assigned to your record.

For taxon determination, nearly the same thing happens.  The taxon determination OTU field is left populated, but 'apply' does not successfully apply this to your record.  Normally, after choosing the OTU, the 'Add' button changes from grey (inactive) to green(active), and you need to click it, at which point the Determination will appear below the button next to a red delete option.  However with the Reset button, the 'Add' button does not turn green despite the OTU field being populated, so you can't add the determination.  
![image](https://user-images.githubusercontent.com/76214527/110532041-56174400-80ea-11eb-8079-bbb83c5d9ae1.png)
As it is, the user has to delete the OTU and re-choose it, then click the green add button.
Best case, the 'Reset' button would leave the OTU choice in place, and the 'Add' button would turn green so that the user could add the determination.

Working in Chrome, in Windows, and not in a sandbox.

**Comment by jlpereira** [comment]
@juliah3 thanks for report this, I already made a couple of changes but you wont see it until the next update.
Now when you reset the interface none of those field will display the previous selection, because that is what really happen and the interface didn't reflect it.

Let me know if im correct, what you need here are lock button to prevent remove those selections after each reset. Thats correct?

Just another question. Which reset button are you pressing? the top one or the bottom(the blue one)?

**Comment by jlpereira** [comment]
@juliah3 with the new changes this should be solved. You will see it on the next update. Reopen if you think not

**Comment by juliah3** [comment]
Great!  Looking forward to the new update.  Yes, lock buttons would be helpful. And I was pressing the top reset button, I haven't used the bottom one.
Thanks.
