### ISSUE TITLE
PDF viewer - not persistant

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2106]
If I view a PDF in one tab, it is not accessible in the different tab.
If I add PDF in one place, I would like it to be accessible in other places. For example, I created a new source and added PDF. Than I what to switch to New TN or New Asserted distribution, I want to see the same pdf file when I open PDF viewer panel.

**Comment by proceps** [comment]
A small addition. When I upload PDF, it should authomatically be added to PDF viewer.

**Comment by mjy** [comment]
The viewer is terrible (library, not us), and really not recommended for
production use btw.  But we can experiment.

**Comment by proceps** [comment]
See #368
