### ISSUE TITLE
Task-Collection Event-Can not type in negative (-) in Lat/Long

### ISSUE THREAD

**Issue by ChrisGrinter** [SpeciesFileGroup/taxonworks#2108]
**Describe the bug**

You can not type in the negative sing - in any of the verbatim fields, but you can copy and paste it in.

<provide a screenshot>

**Expected behavior**
Must be able to type in the - while adding verbatim coordinates.

<img width="155" alt="Screen Shot 2021-03-10 at 1 05 44 PM" src="https://user-images.githubusercontent.com/68249867/110697599-6ccca200-81a1-11eb-9782-23b1f8bc00a8.png">

**Comment by jlpereira** [comment]
@ChrisGrinter I tried to type a negative coordinate on verbatim lat/lng fields and seems to work fine.

**Comment by ChrisGrinter** [comment]
For reference, my Adblock Pro was the issue on Firefox. Disabling fixed the issue.
