### ISSUE TITLE
 Task-Collection Event-feet to meter conversion does not work as expected

### ISSUE THREAD

**Issue by ChrisGrinter** [SpeciesFileGroup/taxonworks#2110]
**Describe the bug**

Toggling between Feet to Meters does not change values or label in expected ways. When entering 1500 feet and saving the record, the 1500' is converted to 457.177689728741m, which is unnecessary/impractical precision. Entering anything into the verbatim elevation does not effect the second elevation field, nor does it get populated on the label.

**To Reproduce**
1. Add 1500 feet with 10feet uncertainty
2. Add 1500 feet, or 1500' to "elevation" under verbatim.
2. Generate label - feet does not appear on label
3. Save record
4. Conversion to meters from non-verbatim field results in ridiculous precision.

**Expected behavior**
If a label should say feet for some reason, then feet should be generated on label. I like (prefer) the option to convert to meters, but there should be a "convert from verbatim" option. Right now adding something to verbatim elevation does nothing to the record if it's added directly. If it's populating from verbatim that works as expected.

**Screenshots**
<img width="746" alt="Screen Shot 2021-03-10 at 1 11 34 PM" src="https://user-images.githubusercontent.com/68249867/110698574-aeaa1800-81a2-11eb-9542-d48ea07f4d2e.png">
<img width="724" alt="Screen Shot 2021-03-10 at 1 13 02 PM" src="https://user-images.githubusercontent.com/68249867/110698576-af42ae80-81a2-11eb-8dcc-1d457c8b4365.png">

**Comment by mjy** [comment]
@ChrisGrinter The Unit is only for convience in the parsed data section, as you noted all values convert to meters.  We'll need to make that clearer.  The intent there is it is standardized.  @jlpereira We can generate the label with both values and let the user decide which to catch.

The label generation in general could be vastly improved, it likely needs a macro-language like CSL styles, but we likely wont' get there quickly.

**Comment by mjy** [comment]
@jlpereira I think this is client side.
* Round the coversion to 2 decimal places (12.12)
* If pre-save then when label is generated use the value as ft, without conversion.
