### ISSUE TITLE
Model - Protonym - Kingdom level restrictions too restrictive?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2111]
As a curator interested in a cursory higher classification only I want to replicate the CoL, but I can't?

![Screen Shot 2021-03-10 at 4 14 46 PM](https://user-images.githubusercontent.com/22600/110705384-f25d4b80-81bb-11eb-8128-48c28d800086.png)

**Comment by proceps** [comment]
pushed some changes. Keep in mind, Protozoa is covered by ICZN
