### ISSUE TITLE
People autocomplete mismatch/not showing in CO Filter

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2115]
**Describe the bug**
I see a person in search autocomplete in "People" data page search but not in CO Filter. 

**To Reproduce**
1. When I search a person in CO Filter 
2. Then I do not see them
3. And I search that person in People
4. And then I see them. 

Screenshot of "Gloyd" search in People auto-complete in People Data Page:
![image](https://user-images.githubusercontent.com/11411328/110824391-a0b6ce80-8258-11eb-8fb8-77e36763863c.png)

Screenshot of "Gloyd" search in Determiner auto-complete in CO Filter:
![image](https://user-images.githubusercontent.com/11411328/110824281-8846b400-8258-11eb-91bb-c077090b3208.png)

**Expected behavior**
All potential people should return? Is current behavior only showing those with "Determiner" roles?

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
As you can see Gloyd has never been a determiner, so they are not displayed in the filter, this is by design.
