### ISSUE TITLE
Mockup - Manage & Filter Loans Task

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2116]
See mockup below and at Google Drawing [here](https://docs.google.com/drawings/d/1Mb79o6Pt0yrOBZlZftUYSiMFgGPpe4TLxWx7ahXytzw/edit?usp=sharing):
![image](https://user-images.githubusercontent.com/11411328/110832232-ae705200-8260-11eb-8bd2-4afde8fc17c4.png)

**Comment by tmcelrath** [comment]
Merge with "Overdue Loans" task

**Comment by tmcelrath** [comment]
@ChrisGrinter

**Comment by mjy** [comment]
Considering done with Unified. Not all the concepts are there, but we have a foundation for finer refinements/more precise issues.
