### ISSUE TITLE
export observation matrix for LUCID

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2117]
As a curator I want to export interactive key matrix in LIF or LIF3 format for LUCID
LIF is a text-based format
LIF3 is XML based schema.
https://www.lucidcentral.org/help/lucid/3.6/builder/help/importing_and_exporting.htm

**Comment by proceps** [comment]
Two examples of LIF3 files. One is generated after processing NeXML from TW.

[Archive.zip](https://github.com/SpeciesFileGroup/taxonworks/files/6126785/Archive.zip)

**Comment by mjy** [comment]
Is this redundant with the NeXML format?
