### ISSUE TITLE
Could you turn on the "Recent" button in the Determinations box

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#2119]
The "Recent" button in the Determinations box does not work

1. When I am working in the Comprehensive Specimen Digitization Task
2. Then I scroll down to the Determinations box
3. And I click on the Recent button in the Determiner section
4. Nothing appears

(tried to attach a screenshot and got the below, disregard screen on the right:)
![image](https://user-images.githubusercontent.com/61740366/110965998-cf997700-8322-11eb-87c3-704e0269f5e1.png)

**Expected behavior**
It would be helpful for this feature to work and provide a list of the most recently used determiners.

**Environment (please identify where you experience this bug:**
- I experience this bug when using the INHS database
- Using Chrome

**Comment by mjy** [comment]
@hhopkins77 Recent applies to people recently used as Determiners, not all recently used people.  Does this help describe what you're seeing?

**Comment by hhopkins77** [comment]
When I click on the recent button, the people I have recently used as
determiners do not appear. That is why I hoped you could activate the
button so that it would work. Hope that answers your question.


Heidi Hopkins, PhD

"She is not what you would call refined.  She is not what you would call
unrefined.  She is the type of woman who would keep a parrot."  ~Mark Twain
