### ISSUE TITLE
Task - Collection Object filter - descendants param is duplicated when sent from OTU

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#212]
I see `"GET /tasks/collection_objects/filter/set_otu?utf8=%E2%9C%93&descendants=off&descendants=on&otu_id=&%5Botu_id%5D=39715 HTTP/1.1" 200 13`

**Comment by mjy** [comment]
@TuckerJD please confirm this is not/fixed.

**Comment by TuckerJD** [comment]
It turns out that this redundancy is actually a part of how Rails #check_box() works.
[Rails #check_box() doc.](https://apidock.com/rails/ActionView/Helpers/FormHelper/check_box)
