### ISSUE TITLE
Cannot "Clone" in the New Edit Collecting Event

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2122]
When I click "Clone" A pink box comes up and says: 
Status: 500 Erroe" Internal Server Error"
I have tried it in two different browsers.

**Comment by mjy** [comment]
@mmkohler can you give us some more details, we are unable to replicate as is.  Thanks!

**Comment by mmkohler** [comment]
Not really as the problem is now only occasional. The next time it happens, I will document it here

**Comment by mjy** [comment]
Going to close, please re-open when found.
