### ISSUE TITLE
New task - Loan filter

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2124]
Similar to "Filter Collection Objects"
 - Filter all attributes of a loan, matching text string or exact text
 - Search by Person (Recipient/Supervisor)
 - Search by Identifier (and ID ranges)
 - Text in "Notes" field, matching text string or exact text
 - Tags
 
Special Searches:
-  "Is Overdue" - Filters Loans to those Loans with a "past" Date Return Expected
- "Has Documentation" - with or without documentation toggle
- "Has Identifier" - with or without an identifier

Loan item(s) Filters:
- OTU included in loan (e.g. show me all loans with "Coleoptera" or "Arachnida")
- By Collection Object identifiers (all loans with the following identifier range or specific identifier)
- Filter loans by Item Status (e.g. show me all the loans with loan items marked as "Lost":
-  ![image](https://user-images.githubusercontent.com/11411328/110998892-2617ad00-8345-11eb-884e-de7ae2e28172.png)

**Comment by mjy** [comment]
== Base attributes

* Filter all attributes of a loan, matching text string or exact text
  * [ ] `loan_wildcards` - we need identical facet as used in CE attribute search
 
* Search by Person (Recipient/Supervisor)
  * `role[]`, with `person_id[]`

* [ ] `overdue` - both - nil, is overdue - true, is not overdue, false
* [ ] `documentation` - with/out filter
* [ ] `identifiers` - withou/out

* [ ] Existing facet for `taxon_name_id` and `descendants` filter
* [ ] Existing facet for `otu_id[]` selector

* [ ] Loan item status - `loan_item_disposition` - see select list we use in LoanItem UI for things like "Lost"

 == Annotations
* [ ] Identifier, and Match identifier
* [ ] Notes
* [ ] Tags

== Notes

> By Collection Object identifiers (all loans with the following identifier range or specific identifier)
* Will do this, to start, with `collection_object_query` passing in
