### ISSUE TITLE
Comprehensive Specimen Digitization 

### ISSUE THREAD

**Issue by szaslow** [SpeciesFileGroup/taxonworks#2134]
Hello!
I have been working on Taxonworks for a while now and typically when I am parsing labels through the comprehensive specimen digitization function when I press "next" at the top right it brings me to the next breakdown hexagon in the TODO list. Recently, when I press "next" the site brings me to the specimen that has the next identifier tag (ie. working on specimen 2000 and when I press next it will bring me to specimen identified as 2001 (see screenshots below)). This has been problematic as it jumps me all over the place and will bring me back to specimens I have already parsed labels for rather than the next specimen within the species I am working on. This makes it more difficult to be efficient with my work flow as I am constantly having to exit and go back through the TODO breakdown to get to the next chronologically uploaded specimen.

Thank you,
Sophia 
![Screen Shot 2021-03-16 at 10 41 43 AM](https://user-images.githubusercontent.com/78037634/111327276-9ffcae80-8643-11eb-8b98-ce64c4783165.png)
![Screen Shot 2021-03-16 at 10 41 52 AM](https://user-images.githubusercontent.com/78037634/111327286-a3903580-8643-11eb-8d40-4dcadb8c9b3a.png)

**Comment by jlpereira** [comment]
We change this adding 2 links for previous and next, one by id and another by identifier. This will be reflected on the next update

**Comment by szaslow** [comment]
Okay thank you so much!

**Comment by mjy** [comment]
@jlpereira I think we could do the same as we do for the Next in the New collecting event?  I.e. give a more expanded modal for next by various options?  Did get your note re needing a new endpoint.

**Comment by jlpereira** [comment]
Aha, yah. Probably that will be better
