### ISSUE TITLE
Insufficient Resolution Feature for Interactive Key  (Enhancement)

### ISSUE THREAD

**Issue by rkres001** [SpeciesFileGroup/taxonworks#2136]
As a curator I would like to be able to explore the resolution of my interactive identification key to determine if taxa are sufficiently delimited with the given characters.

For example, in Lucid if I create a key and do not distinguish two taxa sufficiently, the program will prompt me to add additional characters to distinguish those taxa.

Currently this is the only reason that I would use Lucid instead of exclusively using Taxonworks. If this feature was created, I would exclusively use Taxonworks for key development.

I know this should be an enhancement and not a bug, but I can't seem to edit my label.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/127198567-69f64123-1f33-4ce4-9973-6d758e31cf6f.png)
Use validation box to run validation.

**Comment by rkres001** [comment]
Thank Dmitry!
