### ISSUE TITLE
pdf uploaded in one project not available in other projects

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#2139]
pdf uploaded in one project does not appear when that same source is accessed in another project.

**To Reproduce**
1. I accidentally uploaded a pdf of a termite paper while in the project "INHS Insect Collection".
2. Then I went to Isoptera Catalog and looked up the same paper on Source Hub (see first screenshot below on right hand screen, notice no pdf button on the right hand column).
3. Then I clicked on the radial annotater to re-upload the pdf and discovered that under documentation it indicates "1" (see second screenshot, right hand screen)
4. Then I clicked on the documentation pie slice and saw that there was in fact nothing in the documentation, despite the fact that there had been a "1" indicating that there was something there (see third screenshot, right hand screen).
5. FYI, I re-uploaded the pdf this time while in Isoptera Catalog, so it is there now.

![image](https://user-images.githubusercontent.com/61740366/111645645-4f1dbf00-87d7-11eb-8660-ce877d5c787f.png)
![image](https://user-images.githubusercontent.com/61740366/111645931-95731e00-87d7-11eb-9584-f1306e543bc5.png)
![image](https://user-images.githubusercontent.com/61740366/111646216-d53a0580-87d7-11eb-8941-d9b09e2b4df0.png)

I expected the pdf to be found across all projects.

**Environment (please identify where you experience this bug:**
I found this bug in Production using Chrome.

**Comment by mjy** [comment]
While source records are shared across projects documents on those sources are not, so this is cross-project rendering sneaking through.

**Comment by hhopkins77** [comment]
Ok. Good to know.

Heidi Hopkins, PhD

"She is not what you would call refined.  She is not what you would call
unrefined.  She is the type of woman who would keep a parrot."  ~Mark Twain
