### ISSUE TITLE
Feature Request: Manual Entry of Loan Number

### ISSUE THREAD

**Issue by mraymond362** [SpeciesFileGroup/taxonworks#2140]
Would it be possible to manually enter a loan identification number during the new loan or edit loan tasks? Loan/accession management often comes with a longstanding naming/numbering practice for each institution that needs to be represented in a database record. For example, a loan I'm currently working with is numbered "2021.06" as the sixth loan of the year 2021. Thanks in advance!

**Comment by mjy** [comment]
You can create one after creation with the radial annotator -> Identifiers.  You would want to create a namespace, and then choose "loan code" as the local identifier type.

**Comment by tmcelrath** [comment]
@mraymond362 We do this all the time in the INHS Insect Collection.  We created a namespace "INHS Loan Invoice" and then add them as local identifier type: loan code, just like Matt said:
![image](https://user-images.githubusercontent.com/11411328/111684696-07a62b80-87f5-11eb-9b83-96069b5ad655.png)
![image](https://user-images.githubusercontent.com/11411328/111684739-15f44780-87f5-11eb-9fd7-163662700242.png)

**Comment by mraymond362** [comment]
Fantastic, thanks so much! Another question: how can I create a new namespace identifier? It seems selection is possible, but I cant figure out unique identifier creation...

**Comment by tmcelrath** [comment]
You can create new namespaces from the "Namespace" data card, accessed from the "Data" tab on the homepage.
