### ISSUE TITLE
NeXML export - depictions in the export file

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2142]
Our existing NeXML file could be used directly to build a Lucid key. Can we package CharStates depictions into NeXML file?  The Lucid developers said they can extract those directly into the key if available. May be in a separate folder with depications in a zipped file?

**Comment by proceps** [comment]
It does not look there is described way to add images to NeXML. But the xml schema describe <meta> tag used for annotation. We can probably use it. We are the first customers of Lucid, so they are ready to accomodate the data extraction in the format we can provide.

**Comment by mjy** [comment]
We should raise this with the NeXML devs (likely this issue tracker https://github.com/nexml/nexml) rather than hacking in a solution.  Maybe some of the examples have hints: https://github.com/nexml/nexml/tree/master/examples.

Ping @rvosa, @balhoff

**Comment by rvosa** [comment]
Hi! It is certainly possible to reference an image in NeXML. Are there existing vocabularies that could be used for the semantics?

**Comment by mjy** [comment]
We use the general concept of "depicts some", which I *think* is somewhat along these lines: http://xmlns.com/foaf/spec/#term_depicts.  I think @balhoff knows what we should use though?

**Comment by rvosa** [comment]
I would try to find something more domain-relevant than FOAF. I don't quite know what to recommend but maybe you can cobble something together out of DwC, CDAO, or PATO or something? Hopefully, @balhoff has better suggestions.

**Comment by balhoff** [comment]
I'm not aware of anything very domain-specific. Is the value an image URL? If so you can use `http://xmlns.com/foaf/0.1/depiction` or `http://schema.org/image`.

**Comment by mjy** [comment]
Value will be a URL to an image, or maybe a filename, though we'd be OK with the former.

@balhoff what was used for the image linking to HAO classes?

I don't want domain specific I think, `depicts_some` is super useful to us in a generic way.  Image depicts_some Thing.  

In the case of TW we can depict the observation, descriptor (character and/or state, but also other types), OTU, etc.  There is likely use for including the semantics in NeXML for all of these.

**Comment by balhoff** [comment]
@mjy in HAO we did it the other direction: with the image as the subject you would use `foaf:depicts`. That way we could create an OWL class expression for the "depicts some whatever".

**Comment by balhoff** [comment]
@mjy I think NeXML already supports what you want to do, I guess as you say you need an example. Here is an OTU from a Phenoscape file:

```xml
<otu id="efbb6210-4abc-4ef8-aa38-c61c0ca8a153" label="Diplophos taenia" about="#efbb6210-4abc-4ef8-aa38-c61c0ca8a153">
      <meta xsi:type="ResourceMeta" rel="dwc:taxonID" href="http://purl.obolibrary.org/obo/VTO_0057862" />
      <meta xsi:type="LiteralMeta" property="ps:hasMatrixName">Diplophos</meta>
      <meta xsi:type="ResourceMeta" rel="dwc:individualID">
        <meta xsi:type="LiteralMeta" property="dwc:catalogNumber">55469</meta>
        <meta xsi:type="ResourceMeta" rel="dwc:collectionID" href="http://purl.obolibrary.org/obo/COLLECTION_0000194" />
      </meta>
      <meta xsi:type="ResourceMeta" rel="dwc:individualID">
        <meta xsi:type="LiteralMeta" property="dwc:catalogNumber">206614</meta>
        <meta xsi:type="ResourceMeta" rel="dwc:collectionID" href="http://purl.obolibrary.org/obo/COLLECTION_0000417" />
      </meta>
      <meta xsi:type="ResourceMeta" rel="dwc:individualID">
        <meta xsi:type="LiteralMeta" property="dwc:catalogNumber">274404</meta>
        <meta xsi:type="ResourceMeta" rel="dwc:collectionID" href="http://purl.obolibrary.org/obo/COLLECTION_0000417" />
      </meta>
</otu>
```

You need to define your namespaces up at the top:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<nexml xmlns="http://www.nexml.org/2009" xmlns:dc="http://purl.org/dc/terms/" xmlns:dwc="http://rs.tdwg.org/dwc/terms/" xmlns:obo="http://purl.obolibrary.org/obo/" xmlns:phen="http://www.bioontologies.org/obd/schema/pheno" xmlns:ps="http://vocab.phenoscape.org/" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" generator="Phenex null" version="0.9" xsi:schemaLocation="http://www.nexml.org/2009 http://www.nexml.org/2009/nexml.xsd http://www.bioontologies.org/obd/schema/pheno http://purl.org/phenoscape/phenoxml.xsd">
```

So, you could have something like this:

```xml
<meta xsi:type="ResourceMeta" rel="foaf:depiction" href="http://example.org/my/image.jpg" />
```

**Comment by mjy** [comment]
@balhoff If I want to include all the depictions in their own block, not as inline meta, should I just create a block for them, then use `about`?  

I.e. can you fire me a quick example of relating the depiction to it's target if they are all aggregated together?

**Comment by mjy** [comment]
@proceps I have merged this to development. At present only depictions for character states are included.

* [ ] Add OTU depictions
* [ ] Add Character depictions
* [ ] Add Observation depictions
* [ ] Add CollectionObject depictions

**Comment by proceps** [comment]
I got a request to update NeXML file to put depictions of OTUs inline with each OTU. The proposed format is:
I have a library for image matrix, which returns depictions for an OTU or list of OTUs with all attributes, see NeXML export file for an example.
 

    <otu id="row_172576" about="#row_172576" label="Scaphytopius chiquitanus Linnavuori &amp; DeLong, 1978">

      <meta xsi:type="ResourceMeta" rel="dwc:individualID">

        <meta xsi:type="LiteralMeta" property="dwc:collectionID">UNDEFINED</meta>

        <meta xsi:type="LiteralMeta" property="dwc:catalogNumber">145864</meta>

      </meta>

<meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/107/original/chiquitanushtd.jpg?1619460006" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Habitus, dorsal view" label="" citation=""/>

    <meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/108/original/chiquitanushtl.jpg?1619460011" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Habitus, lateral view" label="" citation=""/>

    <meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/104/original/chiquitanusml.jpg?1619459877" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Pygofer, lateral view" label="" citation=""/>

    <meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/103/original/chiquitanusmv.jpg?1619459870" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Subgenital plate" label="" citation=""/>

    <meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/105/original/chiquitanusal.jpg?1619459882" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Aedeagus, lateral view" label="" citation=""/>

    <meta xsi:type="ResourceMeta" rel="foaf:depiction" about="row_172576" href="https://sfg.taxonworks.org//system/images/image_files/000/715/106/original/chiquitanusav.jpg?1619459890" object="&lt;i&gt;Scaphytopius chiquitanus&lt;/i&gt; Linnavuori &amp; DeLong, 1978" description="Aedeagus, ventral view" label="" citation=""/>

    </otu>
