### ISSUE TITLE
Filter images - improvements to handling filter results

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2147]
The current display of results from filter images is pretty basic, and you can only "pin" the results and view a larger (but not full sized) image.

As a user, I would like to access more data associated with the image. Could radial and hamburgers buttons be added to image results (which links to annotations, collection object record, browse otu, etc.)?

Also, can there be an option to view the full sized image from the search results?

**Comment by mjy** [comment]
@jlpereira on click of the thumb we need to include a link to the object(s) that the image depicts.  May need new endpoints.

**Comment by kandakoj** [comment]
In response to what we talked about during nomenclature meeting, pagination needs to be added to filter images as well.

**Comment by mjy** [comment]
@kandakoj is this resolved now?

**Comment by mjy** [comment]
Considering this done given new linkages via Unified filters.  We can open specifics in new issues as they arrise.
