### ISSUE TITLE
Image uploads - increase maximum file size

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2148]
Currently, when I upload photos using the drag and drop feature in comprehensive specimen digitization, the file size seems to be limited to <150MB. For larger files, I get error 413 Requests Entity Too Large

As a user, I would like to avoid the time spent resizing photos before storing them in TaxonWorks and be able to store original sized images. 

Could the size limit be increased?

**Comment by mjy** [comment]
@LocoDelAssembly @dimus.  @kandakoj tells me his images are 151MB.  I think we should up, if possible, to at least 500mb and see where this goes?

**Comment by mjy** [comment]
@kandakoj you mentioned doing image stacks and getting the result to this size.  Does the result include the individual images?  If so others here might be interested in what you did, as there results are much larger.

**Comment by LocoDelAssembly** [comment]
Increased size, but leaving issue open until this is tested (increasing limit at reverse proxy might not be enough)

**Comment by mjy** [comment]
@kandakoj can you test and close if fixed?

**Comment by LocoDelAssembly** [comment]
With latest @jlpereira's change in front-end I think this issue should be solved by now. Please re-open if problem persists.
