### ISSUE TITLE
Task - Filter nomenclature - redirect to edit TaxonName

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2156]
Please add a checkbox to redirect to Edit TaxonName insted of Browse if selected. I will make it much easier to do numerous corrections of selected names.

**Comment by mjy** [comment]
![Screen Shot 2021-03-26 at 9 11 02 AM](https://user-images.githubusercontent.com/22600/112644325-49e1f500-8e13-11eb-8b91-8852a08571e0.png)

**Comment by mjy** [comment]
I feel that we need to keep the concept of navigation unified, and not spread out?

**Comment by proceps** [comment]
that should work

**Comment by proceps** [comment]
This (radial selector) does not work. When I use it, the focus is automatically redirected to a new tab, after that I do not even remember which line I started at.  The idea is to make editing faster. Opetting taxon page take takes about 5 seconds. So my strategy is to open 5-10 tabs using right click and open in the text tab window. I can do it very fast. By the time I open 10 tabs, the first one is already loaded, and I can emediately can jum to editing. Using radial is ideal for a single record editing, but for mass editing is impossible to use. I still ended up openning 10 tabs in browse mode (just to keep trach which were already opened). And than switching each one to edit mode, waisting 5-10 sec. on each. If the radial can open task in the text tab, but not redirect me automatically to that tab, that would be perfect, otherwise, I would preffer to have a green edit button with a pencil, which will I can right click and just open it in the edit mode directly.

**Comment by mjy** [comment]
We can not control how users bind their mouse buttons, that is up to them.  What your settings are are not ours.

In your browser you have serveral options:
* An option to open new links in new tabs
* An option to open links in new windows
* An option to move the focus to the clicked link.

By customizing these links you can control your expeirence.  Note also that ctrl-<some click type> is usable on this wheel to get a different effect.

**Comment by mjy** [comment]
The problem with adding random links in different places is it seeps everywhere, and we lose the power of starting to undertand *where* to look.  Yes, we need to get to the point where we can be as effective as possible in recognizing where to go, this will take time.  If we stay unified people will gain overal mastery rather than specific mastery, a balance that is hard to achieve, but worth working towards I feel.

**Comment by proceps** [comment]
Normal Right mouse click gives you option, the way Radial is codded, this functionality is not available. I have only 2 options: 1 Left mouse click open in the same window (lets say I use it may be in 5% of the cases, because I do not want to lose the contexts, especially in complicated filters like this)
2nd option: right mouse click which open the content in a separate tab. No Ctrl or any other combination does not work. I would not complain if the radial sector has normal right click functionality where I could select how to proceed.

**Comment by mjy** [comment]
Confirmed.  @jlpereira can you remove the ctrl-click focus so that it is up to the user whether to set focus to the new tab or not?

**Comment by jlpereira** [comment]
@proceps the new radial library should let you now open the browse menu on each slice. For those that are links should let you choose how you want to open it, like a normal link.

**Comment by proceps** [comment]
Thanks
