### ISSUE TITLE
Task - Filter nomenclature - statuses and relationships

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2157]
When I select a nomenclatural code (ICZN for example), please restrict the list of relationships and statuses to this code. When I open complete list, all statuses are listed and it is not easy to select the right one, since one status could be listed multiple times for different codes of nomenclature.

**Comment by mjy** [comment]
@jlpereira do we have this in the API response that gets us the types of both?  I don't think we do?!
