### ISSUE TITLE
OTU radial - Observation matrix sector - Count is missing

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2158]
I have an OTU link to two matrices, but the sector is not indicated as being used. It should have a blue arch with number of matrices where this OTU is added.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/112685670-e7085200-8e42-11eb-91bb-bfce51eb8bf6.png)

**Comment by jlpereira** [comment]
The count should be visible now. However, it will be visible only if you open the slice first. This slice is hardcode so the count information its not provided in the metadata

**Comment by mjy** [comment]
@proceps can we close this?  If so @jlpereira let's make sure it's in the changelog.
