### ISSUE TITLE
task - Edit Observation matrix - add new descriptior

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2167]
After last update, I cannot add a new new descriptor to the matrix. 
It does not work for newly created descriptors (descriptor is created, but not linked to the matrix). The same if I search for the descriptor using the search box. In both cases I get 500 error (and e-mail notification as well)

**Comment by LocoDelAssembly** [comment]
@proceps looks https://github.com/SpeciesFileGroup/taxonworks/commit/94fb3cd319624b037bed112fc4e462092618ca34 would fix?

Although I don't understand why is failing for new records. Searched the incorrect type across all files and couldn't find anything.

**Comment by proceps** [comment]
works in development. We need this fix in production

**Comment by LocoDelAssembly** [comment]
@proceps I just applied the migration manually in production as it won't cause any trouble when deploying next release. Please try again to confirm this fixes the problem.

```ruby
2.7.2 :002 > ap ObservationMatrixColumnItem.group(:type).count
{
      "ObservationMatrixColumnItem::SingleDescriptor" => 2118,
          "ObservationMatrixColumnItem::Dynamic::Tag" => 1,
    "ObservationMatrixColumnItem::Single::Descriptor" => 193
}
```
```ruby
2.7.2 :003 >     ActiveRecord::Base.connection.execute(
2.7.2 :004">       <<~SQL
2.7.2 :005">       UPDATE observation_matrix_column_items
2.7.2 :006">       SET type = 'ObservationMatrixColumnItem::Single::Descriptor'
2.7.2 :007">       WHERE type = 'ObservationMatrixColumnItem::SingleDescriptor';
2.7.2 :008 >       SQL
2.7.2 :009 >           )
 => #<PG::Result:0x0000561477a2fd50 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=2118> 
```
```ruby
2.7.2 :010 > ap ObservationMatrixColumnItem.group(:type).count
{
          "ObservationMatrixColumnItem::Dynamic::Tag" => 1,
    "ObservationMatrixColumnItem::Single::Descriptor" => 2311
}
 => nil 
```

**Comment by proceps** [comment]
@LocoDelAssembly, thanks. Looks like the functionality is restored.
