### ISSUE TITLE
As a curator I want to download a copy of a dataset to import via a link in the DwC importer

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2170]
@jlpereira @LocoDelAssembly do we store the original zip archive as a Document by any chance?

![Screen Shot 2021-04-06 at 10 52 10 AM](https://user-images.githubusercontent.com/22600/113740333-39106980-96c6-11eb-8e1e-a9051ea39ef5.png)

**Comment by LocoDelAssembly** [comment]
Functionality is already available at https://sandworm.taxonworks.org/import_datasets/:id (download link) but not reachable from task.

@jlpereira I guess I should just add URL to backend response and that would be enough to implement link in card?

**Comment by jlpereira** [comment]
> Functionality is already available at https://sandworm.taxonworks.org/import_datasets/:id (download link) but not reachable from task.
> 
> @jlpereira I guess I should just add URL to backend response and that would be enough to implement link in card?

Yes, that will be fine

**Comment by debpaul** [comment]
@jlpereira @LocoDelAssembly @mjy is this done?
