### ISSUE TITLE
pdf not showing up in source list when present

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#2172]
pdf not showing up in source list when present

<img width="889" alt="Screen Shot 2021-04-07 at 8 43 39 AM" src="https://user-images.githubusercontent.com/30123556/113895120-81d72980-977d-11eb-82c2-af9f7411b409.png">

All of these references have pdfs added but the icon does not show up. The references that do not show a pdf are not part of the project (not in original Noyes database). Can they be added to the project to clarify the pdf issue? Also, will the uploaded pdf only be visible in the Universsal Chacididoidea Database project? All of these were checked as "Is Public" [which they are] so they should be able to be shared across projects.

Environment (please identify where you experience this bug:**
*** One of ***
Taxonworks live in universal chalcidoidea database

**Comment by mjy** [comment]
Documents are not shared across projects.  What project did you load the document to?  Was this Luke + UCD?

**Comment by JohnHeraty** [comment]
I uploaded the pdfs in UCD (Live TW).

It seems to be a pity not to be able to be share across projects.

John

**Comment by mjy** [comment]
> It seems to be a pity not to be able to be share across projects.

Yes, it is, particularly for documents that can be shared, we can work towards making that possible.

Regarless, I've confirmed the bug.  Adding a document to a source does not automatically add the source to the current project.  We'll fix that.  For now you can go to each source that has a PDF an click 'add to project'.  Show the source, then click to add. See below.

![Screen Shot 2021-04-07 at 3 05 09 PM](https://user-images.githubusercontent.com/22600/113927318-f082aa00-97b2-11eb-9105-9f7c71ac1314.png)

**Comment by JohnHeraty** [comment]
Perfect!
