### ISSUE TITLE
Catalog number cached value not updated after updating namespace

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2175]
**Describe the bug**

When a namespaces is updated, catalog numbers cached values retain original value.

**To Reproduce**
1. When I  go to Data > Namespaces
2. Then I edit a namespaces
3. And I see an specimen with a catalog number assigned to the edited namespace
4. Display shows old value and I need to re-save to get new value

![image](https://user-images.githubusercontent.com/4991925/114206403-b12e9780-9931-11eb-936b-d258e4e896ba.png)
*(Console screenshot, but saving from comprehensive has the same "healing effect")*

**Comment by mjy** [comment]
@LocoDelAssembly Question is what to do with massively used namespaces, whether to run as a background job.   I.e. check for total use then update one way or the other.

**Comment by LocoDelAssembly** [comment]
```ruby
  def delimiter
    a = namespace&.read_attribute(:delimiter)
    return '' if a == 'NONE' 
    [a, ' '].compact.first
  end

  def build_cached
    [namespace.verbatim_short_name, namespace.short_name].compact.first + delimiter + identifier.to_s
  end

  def set_cached
    update_column(:cached, build_cached)
  end
```
I think this can be done with an update_all SQL code in reasonable time to not require a background job. Let me take a look into this.

**Comment by mjy** [comment]
You're right, the concat is trivial so we can do it in a single query.

**Comment by mjy** [comment]
@LocoDelAssembly I xspecified a spec in `namespace_spec` to confirm the bug.  Remember that subclases might require their own raw sql update at some point, but that's fine, we can do it when required.
