### ISSUE TITLE
Manage controlled vocabulary- Error deleting a Biocuration Term

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2181]
When Editing the Biocuration Terms in my project, I tried to delete one term from the Data list of Controlled vocabulary terms.
![image](https://user-images.githubusercontent.com/63611746/114735383-7e164a80-9d1b-11eb-8fc0-e98ad334caeb.png)

Or form the Manage controlled vocabulary task, in the Biocuration Calsses.
![image](https://user-images.githubusercontent.com/63611746/114735562-ad2cbc00-9d1b-11eb-9d75-b0cf0318935e.png)

Both ways results in Error. Internal server error or 
![image](https://user-images.githubusercontent.com/63611746/114734563-b701ef80-9d1a-11eb-998c-6b9974265c85.png)

The reason it cannot be removed is because it is in use. It would be preferable to have a Warning Message explaining the reason why it is not possible to delete that term, so that the data can be cured.

**Comment by mjy** [comment]
@jlpereira back end is fixed.  Need to stop spinner update on Mange CVT now when record fails to destroy.

<img width="1893" alt="Screen Shot 2022-01-23 at 5 10 47 PM" src="https://user-images.githubusercontent.com/22600/150701870-b56a69e1-30e1-428d-8abc-33f0c90e9e50.png">
