### ISSUE TITLE
As a developer I want access to the postgres `tablefunc` library.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2189]
Adding is simple, we can do it with a migration: `CREATE EXTENSION tablefunc;`

Considerations:
* dumps/restore
* ??

**Comment by LocoDelAssembly** [comment]
```ruby
2.7.2 :005 > ap ActiveRecord::Base.connection.exec_query("SELECT * FROM normal_rand(4, 5, 3);").to_a
  SQL (0.7ms)  SELECT * FROM normal_rand(4, 5, 3);
[
    [0] {
        "normal_rand" => 6.786546376632428
    },
    [1] {
        "normal_rand" => 3.1476271683303443
    },
    [2] {
        "normal_rand" => 7.031389966536828
    },
    [3] {
        "normal_rand" => 4.065829998299258
    }
]
 => nil 
```

I think dump/restore should work fine. Already does with GIS-related stuff which I beleave it is not auto-configured by rails on non-empty databases, only when creating them.

**Comment by mjy** [comment]
Thanks. Reasigning to me since it's just a migration.  Likely coming in the dwc *export* branch.

**Comment by mjy** [comment]
@LocoDelAssembly please revert.  Policy is to never ever change an old migration.  Add a new migration file with the change.  Sorry for the confusion.

**Comment by mjy** [comment]
@LocoDelAssembly I'm sorry, I'm an idiot. 

I glanced and saw the schema being updated and assumed it was the migration.  I see the migration file db/migrate/20210419173135_enable_tablefunc.rb  in the original commit, which is exactly right.

So- please excuse my hasty carelessness and revert the wrongness that you added in c0cf16d, then we can close this and I won't waste more itme.

**Comment by LocoDelAssembly** [comment]
OK, will revert. Probably against policy but will have to be this way this time.
