### ISSUE TITLE
Task - Edit TaxonName - softvalidations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2191]
softvalidation section is missing the soft_validation branch.
It is present in BrowseNomenclature interface.
![image](https://user-images.githubusercontent.com/5597748/115314142-40aa2680-a13a-11eb-9a17-60954c641570.png)

**Comment by proceps** [comment]
It is actually present, but only if soft validations has fixes.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/115318680-d8604280-a143-11eb-81f0-d802e781b755.png)

![Uploading image.png…]()

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/115318793-18bfc080-a144-11eb-8f80-63ee471ae595.png)

**Comment by mjy** [comment]
@proceps this should be fixed, it was a bad resolution: [] path.  Please confirm and close if so. 

For reference (was my code, but)- nte that resolution: [] routes should not contain the `_path` suffix.  The route names come exactly from one of the names on `rake routes`.
