### ISSUE TITLE
Add Clarity on DWCA import

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2193]
When I go to DWCA Import and add a description, instead of "Drop Import File Here", I want to see exactly what file I need. 

For example, instead of "Drop Import File Here", can it say "Drop DWCA Formatted ZIP file" here?

**Comment by LocoDelAssembly** [comment]
What would be the correct phrase here? Supported format are:
- True DwC-A (ZIP with data in text files + meta.xml)
- Tab-separated values text file
- XLS, XLSX and ODS spreadsheets

(Last 2 mapping is derived from headers in first row)

Is it possible to have multi-line text in Dropzone @jlpereira?

**Comment by tmcelrath** [comment]
I would say all of those should be listed somewhere on the page. Might not have to be on the "Drop file here" box itself, but listed directly above in a text box would be extremely useful.

**Comment by jlpereira** [comment]
> What would be the correct phrase here? Supported format are:
> 
> * True DwC-A (ZIP with data in text files + meta.xml)
> * Tab-separated values text file
> * XLS, XLSX and ODS spreadsheets
> 
> (Last 2 mapping is derived from headers in first row)
> 
> Is it possible to have multi-line text in Dropzone @jlpereira?

Yes, its possible. Let me know what formats it will handle and i will add it

**Comment by tmcelrath** [comment]
My vote is to include all three of the above.

**Comment by LocoDelAssembly** [comment]
Actual message should be like this I think:

- Darwin Core Archive (DwC-A) ZIP file with meta.xml and data files inside <i>(preferred)</i>
- Tab-separated values text file (TXT)
- Spreadsheet (XLS, XLSX and ODS supported)

**Comment by mjy** [comment]
This should be added to the orange help icon I think.  Remember we want to drive towards clean interfaces and people knowning where to look for help.

**Comment by jlpereira** [comment]
<img width="575" alt="Captura de Pantalla 2021-04-22 a la(s) 10 45 19" src="https://user-images.githubusercontent.com/16530364/115725050-e1c1f880-a357-11eb-93b9-7480e167a761.png">

**Comment by tmcelrath** [comment]
Looks great! In the future we should add links to Help doc with examples too, but I think that is great.

**Comment by mjy** [comment]
@jlpereira do we support markdown in the help strings?

**Comment by jlpereira** [comment]
> @jlpereira do we support markdown in the help strings?

Nope, for that will gonna need to add another lib to convert md to json. But we can make a separate tool to write help files in md format and then convert it to json.
I wondering how difficult would be create a tool for chrome or FF to write help tips directly on the page and then export a file.

**Comment by mjy** [comment]
We started a new issue template on taxonworks doc to kickstart the help writing process.   This conversation belongs there I think.  I think we can close this one.

https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/.github/ISSUE_TEMPLATE/inlinehelp.md
