### ISSUE TITLE
Minimal image size limitation. 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2201]
Some gif image files used to illustrate character states are much smaller than 1kb. The smallest I have is 271 bypes.
Currently the minimal file size is set to 1kb.

**Comment by LocoDelAssembly** [comment]
Can you upload the sample to simplify testing?

**Comment by mjy** [comment]
We  do all image creation dynamically, without static files, it's not needed.

**Comment by proceps** [comment]
http://dmitriev.speciesfile.org/images/section_round.gif
