### ISSUE TITLE
Task - Interactive key - Character state images - frame overlaps

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2202]
![image](https://user-images.githubusercontent.com/5597748/115908203-7b100e00-a42f-11eb-9304-9104bcfc1700.png)

**Comment by jlpereira** [comment]
@proceps link?

**Comment by proceps** [comment]
I do not have images in production. I am working on migration. tasks/observation_matrices/interactive_key?observation_matrix_id=21 that what I was using. And uploaded few images there. Each character in the key has a hyperlink to the images, which are displayed if present.

**Comment by proceps** [comment]
Could you also try to align the text to the upper part of frame, so that all checkboxes are on the level of the first line of the character state and all boxes are on the same level.
![image](https://user-images.githubusercontent.com/5597748/115914628-d0e8b400-a437-11eb-9a86-51996d0c4900.png)

**Comment by jlpereira** [comment]
@proceps take a look the new changes, let me know if are okay now
