### ISSUE TITLE
Model - Uniquify TaxonName

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2206]

**Comment by proceps** [comment]
same as #970?

**Comment by mjy** [comment]
No, this this the back-end model code, 970 is the Task

**Comment by mjy** [comment]
This blocks an efficient way to destroy TaxonNames.

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/970
