### ISSUE TITLE
Task - New observation matrix - row/column interface selection broken

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2208]
When I see my matrix, then both row and column selectors are shown, only one should be.

I can not use the column selector. 

![Screen Shot 2021-04-26 at 10 08 23 AM](https://user-images.githubusercontent.com/22600/116105960-6cb43300-a677-11eb-8f6e-c511626b1ea3.png)

**Comment by proceps** [comment]
It could actually be nice to see them both, adding fixed/dynamic switch to each section. They do not take much spece. But at the moment, When I do search to add the column, the search is performed on OTU. I cannot add any descriptors using the selector.
