### ISSUE TITLE
Task - Edit TaxonName - generic synonymy.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2213]
When I synonymize two generic names, I have a section which allows to transfer all species from one genus to another. The problem is, the section displays all descendants of the synonym genus without distinguishing their rank. When you have a genus devided to subgenera, or species divided to subspecies, there is no distinction between those. So when you do the transfer, the classification get flattenen. All subspecies and their synonyms get now listed under the valid genus name. In fact, this transfer should be allowed to the chlindren one level down (regardless of their rank). So if the genus is devided to subgenera, only subgenera should be transfered to the new place in classification. If the genus has subgenera and some species unassigned to subgenus, all those species should be moved as well. If the genus has species and some of the species are divided to subpecies, anly species should be moved to new location.

**Comment by mjy** [comment]
Not a bug I think, this was intended. You can selectively check which things to move, and you are warned with a "type to confirm" dialiog.

**Comment by proceps** [comment]
There is no way to distinguish species from subspecies in the list. And there is no any reasons to include all children taxa to the list. The list should be limited to those taxa, which have the synonym as a parent taxon. All other taxa should be excluded. I just synonymized two genera, and spend one hour resolving the mess it created.

**Comment by proceps** [comment]
Actually, if we apply sv_fixes to all descendants, it would resolve the relationships inteligently.

**Comment by mjy** [comment]
There is a reason.  If you synonymize, say families, then you may want to move genera to different places.  

I spent 2 hrs batch fixing someone who didn't read the instructions names as well...

Concur, we need to list/sort on rank, I think it's an issue already.

**Comment by proceps** [comment]
Yes, I agree that this is very useful that you can decide what moves and what needs to be resolved manually. But in your example, when two families are synonymized, I cannot imagine a scenario when a subspecies (including all synonyms associated with those subspecies) changing parrent from species to family. This does not make sense. Synonymizing taxa on higher level should not affect classification on lower level. Synonymy of families should affect only direct descendants of that family (subfamilies, or tribes, but not species and subspecies). Now all descendants are proposed to change the parent to family. This is very dangerous procedure. I propose to limit the list of selection only to those which has family as a parent_id. In this case, people would not be able to completely destort the classification. If spot changes are needed, it is much better to do those manually.
