### ISSUE TITLE
Uniquify people doesn't propagate?????

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2215]
I have uploaded in the past a great number of data form a spreadsheet therefore creating many "ghost" authors.
These are gradually being replaced with the real ones.
By successfully using UNIQUIFY PEOPLE I expected to get rid of all ghost names in the **auto-complete** for example in the "New Source" module.
But the ghosts persist there -- how do I get rid of them?

**Comment by mjy** [comment]
@adrik29 can you list a couple of examples that should be gone?

**Comment by adrik29** [comment]
Yes, for example, all ghost Seisho Suzuki **in my project** have been merged.
![image](https://user-images.githubusercontent.com/46284943/116801027-8a045980-aadc-11eb-92c1-ece854cd7489.png)

However, when I try to edit a source all ghost reappear:
![image](https://user-images.githubusercontent.com/46284943/116801049-ae603600-aadc-11eb-8383-49fb995ff13f.png)

**Comment by mjy** [comment]
I see these are Suzuki's that you created.  So either the merge failed, or there were more than you merged?

**Comment by mjy** [comment]
What is the ID of the "real" Suzuki?

**Comment by adrik29** [comment]
> What is the ID of the "real" Suzuki?


It is 457:
![image](https://user-images.githubusercontent.com/46284943/116802252-d1dcae00-aae7-11eb-81fd-ae9e9f5b308d.png)

**Comment by mjy** [comment]
Are all the Suzuki's that you created initially the same?  If so I will experiment with the remainders?

**Comment by adrik29** [comment]
They are the same PERSON. There is only one Suzuki who worked on Opiliones, although it is a fairly common surname.
And yes, they were all created simultaneously when I made my huge initial upload en 2018.

**Comment by mjy** [comment]
@adrik29 I suspect you only merged the first 100 and that there were more to merge (based on dates). I.e. you may have to repeat the search, only 100 results at a time are returned.  

I merged the remainder.

**Comment by adrik29** [comment]
mjy -- ah -- I never knew there was this 100 items limit!
So I should refresh because it said ALL the ghost Suzuki had been merged into the real one = that means it found ZERO Suzuki after the initial merging.

**Comment by adrik29** [comment]
But it doesn't work anyway:
![image](https://user-images.githubusercontent.com/46284943/116821577-d7221300-ab50-11eb-834c-8503a615976b.png)

**Comment by proceps** [comment]
I never had an issue merging large number of authors, but sometimes you have to do it multiple times. In cases like this, it works easies if you first merge those, which are unused or have a single use, and than merge them to a currated one.
If this task is updated, please take #2050 into account

**Comment by mjy** [comment]
I just missed the hundreds more, has to be repeated again with reminders.
Notice the years get more recent as the old records are merged.

**Comment by mjy** [comment]
I believe there is an error when you try to merge 100s of people.  Perhaps some records fail.  When I try 5 or so batches, it works.  When I try 100, at least some fail.

**Comment by mjy** [comment]
Related: https://github.com/SpeciesFileGroup/taxonworks/issues/2218

**Comment by adrik29** [comment]
Wow -- this takes much more work than I first thought. Anyway, I like a lot the direction that you guys are guiding TW to.
The tools are improving a lot and at least we in the Opiliones Project are always perfecting the database...

**Comment by mjy** [comment]
There is a fix coming to let you run batches of 100 properly, it was a real bug you caught.
