### ISSUE TITLE
Make the built-in PDF viewer still better?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2216]
The built-in PDF-viewer is a tremendous improvement for TW.
I would suggest that the blue PDF icon appear also in the References in the "Browse Nomenclature" module, as here:
![image](https://user-images.githubusercontent.com/46284943/116819857-6e369d00-ab48-11eb-93b9-a8f9c92576b5.png)

AND EVEN MORE IMPORTANT:
IT WOULD BE A SUPER ENHANCEMENT IF THIS APPEARS ALSO IN THE "AUTHOR" MODULE IN THE "EDIT TAXON NAME" TAB.
![image](https://user-images.githubusercontent.com/46284943/116819952-ef8e2f80-ab48-11eb-9cc4-a758b163882b.png)

**Comment by adrik29** [comment]
I am aware that we can invoke the viewer from the pinboard, but even so... It would considerably improve the error checking.

**Comment by proceps** [comment]
same as #2103
