### ISSUE TITLE
Task - Uniquify people - Number of uses not displayed.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2219]
It is dispayed when you search for the person.
![image](https://user-images.githubusercontent.com/5597748/116822856-d4222500-ab46-11eb-9890-b4fcc493e412.png)
But once selected, only question marks are displayed.
![image](https://user-images.githubusercontent.com/5597748/116822881-f6b43e00-ab46-11eb-8225-6752b46e88d6.png)

**Comment by mjy** [comment]
Use is only showed for when the person is in your project. I suspect you were in a different project here?  We can add a different total to show all use?

**Comment by proceps** [comment]
I definitely was in my project. I even used my name in search ;)

**Comment by proceps** [comment]
When I use left filter to find person, yes, I see the numbers, but I never used it before. When I use the top filter, I see only a question mark, most common raute for me when I search a person as an author (for example a source author), and source returns me 2 results, I select a person, right click the person to open it in the next tab, than I use navigate radial to get to Uniquify people task. In this case, I can see "0" uses instead of "?" for selected person.
![image](https://user-images.githubusercontent.com/5597748/117740916-0d9e0480-b1c7-11eb-8490-ffb33771a4c5.png)

**Comment by mjy** [comment]
@jlpereira can you extract the count from the autocomplete?  I can add a data attribute indicating which element contains it?
