### ISSUE TITLE
Task - OTU radial - determinations.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2227]
Each determination should be open in Browse Collection Object.

**Comment by mjy** [comment]
@proceps Do you mean Colleciton Object radial?  Screenshot/

**Comment by proceps** [comment]
Each determination should be replaced with actual collection object and point directly to the CO View or Edit (radial with proper view or edit link would be enough)

**Comment by mjy** [comment]
Closing this as done.
