### ISSUE TITLE
Nuke result- Grid digitizer task

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2229]
When I assign catalog numbers to images that match pre-existing collection objects in the database, when creating theis "new objects" TW merges the objects with the same catalog number. No prior notice of coincidence. Also when I want to delete the objects that I am creating with the image, either there was a confusion or a mistake was made doing the work, by using the Nuke function, the collection objects are completely removed. Not just the assigned photo. Perhaps this should be clarified to avoid complications.

**Comment by mjy** [comment]
@jlpereira When we click 'Nuke', then we should add text to the warning that is prefixed to asking the user to type the confirmation.

'This will ALSO DESTROY specimens that matched assigned identifiers, not just those created de-novo in this tool.'
