### ISSUE TITLE
TaxonName.cached is referencing the html version?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2236]
There should be zero html references in the building of `cached` for TaxonName, but I see this:

`"</i>[<i></i>GENUS NOT SPECIFIED<i></i>]<i> vulnerata"`

**Comment by mjy** [comment]
The value is set correctly, i.e. after `.reload` the cached value is correct.

The question remains why <i> values appear at all, they should not be involed in the composition.

**Comment by proceps** [comment]
We originally used .cached for html version. Then we created new field .cached_html. I tried with new record, html tags are not created in .cached field any more. Some of the old data need reindexing. Best way to reindex is to sv and fix, this will only update the records which need to be fixed.

**Comment by mjy** [comment]
This issue isn't about old dat, it's about new data.  The spec Referenced above demonstrates how to see, temporarily, the cached fields.  The methods should never be touching the htmlized verison, thus I'm very confused.

**Comment by proceps** [comment]
It looks confusing, but I cannot find any html reference to cached value in the code. Should be some glitch in spec handling. For complicated operations you cannot really validate anything in spec before you reload the object. Should be related to caching the object in spec not real data handling by the model.
