### ISSUE TITLE
Task - New Taxon Name - New button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#224]
When New button is clicked, the warning should show up only if there are unsaved changes. 
Each section should have a notification of unsaved changes.

**Comment by mjy** [comment]
@proceps please further atomizing issues, this is two different ones.

**Comment by proceps** [comment]
When I pick a type species for a genus but did not select a relationship type, when I click a New button, I do not get any warning that relationship is not saved.

**Comment by mjy** [comment]
@proceps can we close this?

**Comment by proceps** [comment]
When the type selection or relationship is incomplete (related taxon is selected, but the type of the relationship is not). The record is not recorded as unsaved. Clicking new button ignores incomplete relationships.

**Comment by mjy** [comment]
@proceps close?
