### ISSUE TITLE
Model - TaxonName, valid/invalid methods are not sufficient, they do not include TaxonNameClassifications

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2242]
The CoL export has "illuminated" a fairly large oversight with some of the scoping methods, e.g. `that_is_(in)valid`, they only check via proxy of the cached_valid_taxon_name_id.  This major issue is this doens't work when only invalidating TaxonNameClassification are persent.  

A proposal might be to: 
* Update cached_valid_taxon_name_id to allow nil when name is invalid due to TaxonNameClassification only
* Add a boolean to assert valid/invalid, rather than depending on the comparison of id to cached_valid_taxon_name_id
* Both.
* Ensure valid/invalid scopes pick up all considerations (i.e. also TaxonNameClassification)

This is a fairly major refactor, definitely a new branch required.

**Comment by proceps** [comment]
we have specific method for this .unavailable_or_invalid?
Yes, we can add additional cached value boolean to assert if the name is valid.
Overloading cached_valid_taxon_name_id is not good idea, the name may still have additional taxon_name_relationships. For example a nomen_nudum, may have a misspelling associated with it, we still end up with a claster of names which we distinquish by cached_valid_taxon_name_id
Partially related to #1541

**Comment by mjy** [comment]
> Overloading cached_valid_taxon_name_id is not good idea, the name may still have additional taxon_name_relationships.

Right.  I don't think it's overloading.  If there is _no_ relationship, and the name is invalid/unavailable, then it shouldn't have a cached_valid_taxon_name_id is the statement.  If it is both, then it can point to what is valid.  In some ways it's overloaded now?

**Comment by mjy** [comment]
>Partially related to #1541 
Good catch, this is a dupe with more detail.

**Comment by proceps** [comment]
Added cached_is_valid column to TN it takes into account both TNR and TNC. The data in the table should be reindexed to populate the field. The clean way to do it is to use soft_validation fixes.

**Comment by mjy** [comment]
What branch did you do this on?  It should be on 2242.

**Comment by proceps** [comment]
it is in development
