### ISSUE TITLE
As a curator I want access to the "status" attributes of my taxon name through the API  [was: API Query]

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#2243]
Can we pull the status of a taxon (nomen nudum/nomen dubium) using the api? We are not seeing where it is.

**Comment by mjy** [comment]
Good catch, TaxonNameRelationship and TaxonNameStatus are not exposed

@proceps @jlpereira I wonder if we create a unified status endpoint that includes both for a taxon name?  Would that be perhaps usable in the new taxon name interface as well?

**Comment by proceps** [comment]
we have method .combined_statuses which brings together list of statuses which come from both relationships and classifications. It could be exposed with an endpoint.

**Comment by mjy** [comment]
@jcabbott13 I suspect you want a human readable summary string?  Or will you compose the "status" from the raw data?

**Comment by jcabbott13** [comment]
Yes…human readable string is preferred, but we can probably work with either.
