### ISSUE TITLE
family names (or taxonomic heirarchy) of associates needs to be displayed.

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#2244]
**family names (or taxonomic heirarchy) of associates needs to be displayed**

**To Reproduce**
For Torymus bedeguaris (L.) otu
https://sfg.taxonworks.org/tasks/otus/browse/111066

<img width="959" alt="Screen Shot 2021-05-12 at 8 34 25 AM" src="https://user-images.githubusercontent.com/30123556/118003970-e26a0100-b2fd-11eb-9c1c-8efa3fcc785c.png">

there is a list of associates, but there is nothing to identify what they are (i.e. family), which is essential if you do not know what they are. You have to do a google search on each name. The associates should have the family name displayed, or even as a wand over. Also would be nice if the columns could be sorted by relationship or object.

**Environment (please identify where you experience this bug:**

- Production

**Comment by proceps** [comment]
same or similar to #2228
