### ISSUE TITLE
New Combination also misspelling

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2250]
Working with Taxon Names.... In the case we have a New Combination for a species taxon name.
 
Ex: The protonym for _Conocephalus (Anisoptera) melaenus_ is _Locusta (Xiphidium) melaena._ 

![image](https://user-images.githubusercontent.com/63611746/118100232-99bd5100-b3ac-11eb-81e9-3bb56d508cad.png)

We create the New Taxon Name first, _Locusta (Xiphidium) melaena_. The next mention is a new combination with no complication... _Xiphidium melaenum_. But the one that follows, as many of the following mentions, is a New combination with a misspelling: _Xiphidium (Xiphidium) melanum_. Which is the best way to record this case?

When we have a misspelling TW recommends to create a New taxon name, but in that case it creates a new Protonym also... and this record ends up being for a protonym and not for a combination.  Maybe the New combination task could have a new feature that allows us to register, when we use the verbatim choice, in the case it refers to a misspelling and add [sic] by it. 

![image](https://user-images.githubusercontent.com/63611746/118100275-a6da4000-b3ac-11eb-8bc2-8642ec8ca432.png)

**Comment by mabecabrera** [comment]
Or maybe add the option of New combination type of relationship to the **New Taxon Name** task

**Comment by proceps** [comment]
Creating a new protonym for misspelled combination is advisable. If the same misspelled name is used later for another combination, you can create New combination. Both, new misspelling and new combination, look the same in the list. Both derive their author string and year of publication from the correctly spelled protonym.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/118148451-321bfb80-b3d6-11eb-92cf-e1eb1e336583.png)
