### ISSUE TITLE
number of records displayed

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#2251]
**number of records displayed**

Not having a higher number of records to be displayed (i.e. 5000 or 10,000) is hampering searches for finding the number of species in a group. In the example, the number of species of Mymaridae exceeds 1000, but I cannot display them past 1000.

<img width="977" alt="Screen Shot 2021-05-13 at 8 49 46 AM" src="https://user-images.githubusercontent.com/30123556/118151388-6be60580-b3c8-11eb-9706-cfc9dfdacfca.png">

**Comment by mjy** [comment]
Click on the pagination to the left (1 2 Last >>).  The "1000 records" is also being replaced with the total.

**Comment by proceps** [comment]
please use Nomenclature Stats for this
![image](https://user-images.githubusercontent.com/5597748/118152631-8aed9300-b3da-11eb-8db7-cdd2136ca075.png)

**Comment by JohnHeraty** [comment]
Why am I getting only names, not numbers?

**Comment by mjy** [comment]
@proceps was showing a different task - Nomenclature stats.

**Comment by proceps** [comment]
Select thecolumns and rows which you want to display. I selected subfamilies for rows and genus and species for columns

**Comment by JohnHeraty** [comment]
This works, but the numbers are different for genera and species using stats or browse. The overestimates in stats is likely due to ghosts which can be filtered out in browse but checking only names with authors. So browse is more accurate.

**Comment by mjy** [comment]
Closing this, pagination totals are now displayed- 

`will be live this week sometime`

<img width="423" alt="Screen Shot 2021-05-13 at 11 54 25 AM" src="https://user-images.githubusercontent.com/22600/118158910-030b8700-b3e2-11eb-9121-8aeeed5e1aff.png">
.
