### ISSUE TITLE
Hyperlinks in biological associations do not work.

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#2252]
Hyperlinks in biological associations do not work.

https://sfg.taxonworks.org/tasks/otus/browse?otu_id=601068

<img width="1360" alt="Screen Shot 2021-05-13 at 3 17 40 PM" src="https://user-images.githubusercontent.com/9273125/118175886-ad91a300-b3fe-11eb-8780-506f67ab988b.png">

**Comment by proceps** [comment]
same as #2228
