### ISSUE TITLE
https://github.com/SpeciesFileGroup/taxonworks/issues/2254

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2255]
**Describe the bug**

**Recent** list of Authors is not recent. Even after adding more people names, only the ones from quite a few records back are showing in the Authors **recent**box.

Likely related to https://github.com/SpeciesFileGroup/taxonworks/issues/2254

**To Reproduce**
1. When I am adding new sources
2. Then I add authors where needed
3. And I note that upon adding another source, 
4. The authors I added in the prior record do not appear in the **recent** list.
![2bSource_TWsandbox_SoftVal_AuthorRolesNotSelected_HowInWhatOrderToDoThisTask_NoteRecentIsntRecent](https://user-images.githubusercontent.com/2990155/118372508-8e6a5100-b577-11eb-84cf-2597eb41f129.PNG)

**Expected behavior**
After entering authors for a Source and moving to add the next Source, I'd expect the "recent" list to reflect the names I just added in the prior record.

**Screenshots**
See above

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandbox https://sandbox.taxonworks.org/tasks/sources/new_source
- Browser Firefox, Win10 PC

**Comment by jlpereira** [comment]
@debpaul I pushed a fix for this. The change should be reflected on the next update. If not reopen the issue.
