### ISSUE TITLE
Task - filters [nomenclature] - add citations to mass annotator [edited]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2257]
Curculionidae database has all nomenclature and bibliogrophy, but taxon_names are not linked to sources. An interface is needed to add source to number of records filtered with Filter nomenclature interface.

**Comment by mjy** [comment]
@proceps is this the same as "match author/year to source?"  If so I believe it might be a dupe.

**Comment by proceps** [comment]
could not find, do you know the issue #?
