### ISSUE TITLE
image in Comprehensive specimen digitization form is wonky

### ISSUE THREAD

**Issue by LauraPorturas** [SpeciesFileGroup/taxonworks#2262]
**Describe the bug**

Collection objects uploaded by the Grid Digitizer are now displaying photos of the entire grid instead of individual slides. The image of the entire grid can’t be zoomed in enough to view individual slides for transcription.

**To Reproduce**
When I visit the Comprehensive specimen digitization form, and I try to click on the image depiction to view for transcription, then I see the entire imaged grid instead of the individual slide specimen specific to the collection object.

**Expected behavior**
I expect to see only the individual slide, not the whole grid.

**Screenshots**
![image](https://user-images.githubusercontent.com/62353864/118701994-5ca8f280-b7e2-11eb-88d5-491cb80f5e58.png)
![image](https://user-images.githubusercontent.com/62353864/118702011-616da680-b7e2-11eb-9054-827212f87fbb.png)

**Environment (please identify where you experience this bug)**
*** One of ***
chrome on mac

**Comment by LauraPorturas** [comment]
Hi José, thanks for helping with this issue. I am still experiencing the bug. Should I just wait to check back on it after the next release?

**Comment by mjy** [comment]
Hi @LauraPorturas exactly.  Issue is fixed in development.

In general if you check the CHANGELOG.md file at the root here you will find what is live and what is not.

**Comment by LauraPorturas** [comment]
Thank you!
