### ISSUE TITLE
insertae sedis

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#2264]
I wasn't able to make the weekly meeting today, but have a question. What is the best way to handle insertae sedis genera in TaxonWorks? For purposes of our WOL (https://oc.staging.birdsinthehand.com/app/#/wol/) we were thinking it might be easiest to classify them in a "family" called insertae sedis, but the validations in TaxonWorks won't allow that. I would appreciate any thoughts on this.

**Comment by proceps** [comment]
In the Edit Taxon Name, please use Classification section:
![image](https://user-images.githubusercontent.com/5597748/118853173-1498d700-b899-11eb-9207-f1e9982a7ca7.png)

**Comment by jcabbott13** [comment]
Thanks Dmitry, but those options are available to me. I’m looking specifically at Sciotropis in the odonate project (https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=708156 <https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=708156>)

John
-- 

John C. Abbott 

AbbottNature.com
AbbottNaturePhotography.com
flickr.com/abbottnaturephotography
facebook.com/AbbottNaturePhotography
youtube.com/AbbottNature
www.odonatacentral.org 

Author of Common Insects of Texas (NEW)
Dragonflies of Texas, 
Damselflies of Texas, & 
Dragonflies and Damselflies of the South-central U.S.

**Comment by proceps** [comment]
Yes, because you have superfamily as a parent taxon. Incertase sedis is alway identical with parent. If you would like to use historical placement, please use "Classified as" instead. 
![image](https://user-images.githubusercontent.com/5597748/118855061-0055d980-b89b-11eb-86f4-2ddf2f5bb7ff.png)
If you cannot find the section, it is below the original combination.

**Comment by jcabbott13** [comment]
Got it. I needed to “set to parent” for the options to show up. Thanks!
-- 

John C. Abbott 

AbbottNature.com
AbbottNaturePhotography.com
flickr.com/abbottnaturephotography
facebook.com/AbbottNaturePhotography
youtube.com/AbbottNature
www.odonatacentral.org 

Author of Common Insects of Texas (NEW)
Dragonflies of Texas, 
Damselflies of Texas, & 
Dragonflies and Damselflies of the South-central U.S.
