### ISSUE TITLE
As a devop I need spring not to raise 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2268]

**Comment by jrflood** [comment]
In RubyMine, there are multiple paths to disable spring: from the Project tree, from the top menu "Run" tab, and probably from the Preferences dropdown. 

- In the Project tree, If no previous "Create Run Configuration" has been  executed, right-click the Spec and Select "Create Run Configuration", then select the scope, e.g., All specs in <this spec>. A modal dialog for the new run/debug configuration will appear, and will have a selector for "Use pre-load server:" which is probably set to "Spring".  Change this to "None".
- From the "Run" top menu tab dropdown, select "Edit Configurations", which pops a modal listing all Run/Debug Configurations.  Select the desired configuration(s) and change "Spring" to "None" as above.
- At the moment, I have not found the hidden path to manage this through RM Preferences dropdown, but RM usually has a way to access such things through Preferences.

**Comment by proceps** [comment]
I believe we have it fixed.
