### ISSUE TITLE
Staged image sections display issues

### ISSUE THREAD

**Issue by juliah3** [SpeciesFileGroup/taxonworks#2273]
See this previous post: #2057

When staged images are taller than they are wide, the display for transcribing depictions is buggy.  It seems to me that the problems come from inconsistently compensating for taller-than-wide images.

When I first 'recalculate' the sections, the first image shown is displayed with the image width sized to the width of the space, and the height proportional.  With a taller-than-wide image, this means the bottom of the image is cut off.  The zoom box works as expected.
![Screenshot (124)](https://user-images.githubusercontent.com/76214527/119516516-d2621080-bd44-11eb-8c6b-9053860a5987.png)

When I click the quadrant section image on the left hand menu, the upper image is now displayed correctly, with the longer of the dimensions sized to the space, and the shorter dimension proportional.  So none of the image is cut off.
However, the zoom box here does not match this correct display, but instead seems to be referencing the incorrect, width-locked display.  
![Screenshot (122)](https://user-images.githubusercontent.com/76214527/119516582-e148c300-bd44-11eb-85c1-da58aa02b45c.png)
![Screenshot (126)](https://user-images.githubusercontent.com/76214527/119516592-e574e080-bd44-11eb-9671-4268e0794edb.png)

Correct functionality would be for the display to always size based on the longer dimension, so that none of the image is cut off.  And the zoomed-in, lower display would match the location and size of the zoom box in the upper image. 

Thanks,
Julia

**Comment by mjy** [comment]
@jlpereira @proceps did you just tweak some fix for the image rendering endpoints that might have addressed this?  I vaguely recall a tweak?

**Comment by proceps** [comment]
https://github.com/SpeciesFileGroup/taxonworks/commit/ba6b1c2b517f38f8011c8c11a6c9538db16aeb86
The only change I made.  We run into problem with the  method scale_to_box:
http://localhost:3000/images/651918/scale_to_box/0/0/696/945/696/945 Which suppose to create the image of exactly the size of original, produced a result image of the same width but twice as tall. 696x1890. Because the value was multiplied, and not divided.
![image](https://user-images.githubusercontent.com/5597748/119521844-1f43e800-bd41-11eb-90e6-ed9e55647dfd.png)
became 
![image](https://user-images.githubusercontent.com/5597748/119521947-35ea3f00-bd41-11eb-812a-30816b850c20.png)

**Comment by mjy** [comment]
I think this is the issue.  @juliah3 can you attach the full cool test image you used above here?  I will test it with this change.

**Comment by proceps** [comment]
I think, the issue could be some other place in the code, where it is compensating for initial stretched result. We also had an issue in one place, where images were resized based only on the image width, not taking into account other dimensions, @jlpereira made some change to made image to fit a frame taking into account both length and width of the original image. But he should provide more details.

**Comment by juliah3** [comment]
Here's the full test image used.  Thanks, Julia
![5_25_21_test2](https://user-images.githubusercontent.com/76214527/119524623-d04f8000-bd4b-11eb-853b-750bbd61a7cf.jpg)

**Comment by mjy** [comment]
@jlpereira you're saying the scale code that was fixed was in JS?

**Comment by jlpereira** [comment]
Nope. We didn't touch anything related with this task. Im using "scale" not "scale_to_box" in image viewer to create jpg image from tiff.
What i mean is if the backend code(scale_to_box) now is correctly, then maybe we need to update the frontend code of the old task.

**Comment by mjy** [comment]
Keep in mind this could be bad edge detection.
