### ISSUE TITLE
New Extract; show origins in table of recent extractions

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2283]
As a user, I would like to see more data associated with recently entered extractions in the "New Extract" window.  It would be useful to be able to see the "origin" of the recent extractions (specimen voucher code and associated OTU name).

It would also be useful to see Specimen code, OTU, and taxon determination in the listview of Extract data.

**Comment by debpaul** [comment]
this ticket is "duplicate" of #2271 which is closed. So @mjy can we close this one?

**Comment by mjy** [comment]
Closing.  The information is there, but not in individual columns.  We will adapt/change in the new Extract filter results table as needed.
