### ISSUE TITLE
New Georeferences fields Required for New Collecting Event Task

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2285]
For the cases in which the georeferences of a collecting event are created afterwards, we need three more Darwin Core fields so that the appropriate information is captured. These are: georeferencedBy, georeferencedDate, georeferenceProtocol

![image](https://user-images.githubusercontent.com/63611746/119856224-efcfdf80-bee8-11eb-8b4b-1c275bd29ae0.png)

These fields are essential to be able to record all the necessary data. In the Specify software that we have been using for the MLP Enotmology Collection, we have them. We need to have them in TW also to migrate the information and to continue digitizing.

![image](https://user-images.githubusercontent.com/63611746/119859668-f9a71200-beeb-11eb-8cd0-50f0980d3d92.png)

Besides adding those DwC fields as CollectingEvent custom attributes, would perhaps be possible to support them natively?

**Comment by mabecabrera** [comment]
Besides adding those DwC fields as CollectingEvent custom attributes, would perhaps be possible to support them natively?

**Comment by mjy** [comment]
All doable.

Some are being exported in the dwc_fields branch by inferrrence already.
The remainder are largely done by adding Attribution to Georeference.

**Comment by mabecabrera** [comment]
![image](https://user-images.githubusercontent.com/63611746/143303077-c4ea98da-50e3-40dd-9d55-29b630a8531b.png)

**Comment by debpaul** [comment]
@jlpereira which of these requested fields have been added please?

**Comment by jlpereira** [comment]
@debpaul Date fields are already present for Georeferences. Protocol and Verifier(people) are in radial annotator

**Comment by mjy** [comment]
I think this is closable?

**Comment by debpaul** [comment]
@mabecabrera do you have what you need (fields?) now?

**Comment by mjy** [comment]
Closing as done.
