### ISSUE TITLE
Model - Namespace -> boolean option to export to DwC with no namespace [Was: Browse collection object - DwC Catalogue Number]

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2286]
The DwC table of the **Browse collection objects** task has a column for "catalogNumber". This column is currently showing the concatenation of the Namespace (used in TW)  and the actual "catalog number". 

![image](https://user-images.githubusercontent.com/63611746/119895583-528aa080-bf14-11eb-8d66-62d091532ee5.png)

Being this a DwC column it should be showing only the number, without the namespace. 

![image](https://user-images.githubusercontent.com/63611746/119903489-27597e80-bf1f-11eb-9b0e-21d410f8f4ee.png)

Also, it would be useful if in this table could show the institutionCode column near by the catalogueNumber one, and add a new column for the collectionCode by them.

**Comment by mjy** [comment]
This only make sense if the namespace can be defined in another column, and I'm not sure there is a place for it in DwC sensu we use it. @debpaul can chime in perhaps.  I see no problem with all the value in the Catalog Number.

**Comment by debpaul** [comment]
The dwc:catalogNumber should be what the collection uses for their catalogNumber. In the example shown,  it does look more like a "Darwin Core Triplet" of sorts (a concatenation of institutionCode, collectionCode, catalogNumber). 

@mabecabrera wrote:
>Also, it would be useful if in this table could show the **institutionCode** column near by the **catalogueNumber** one, and add a new column for the **collectionCode** by them.

I do see the need for these columns as well.

The main point for dwc:catalogNumber is that it is usually a "finding aid" for collections to locate a specific item in their collection. (Said another way, if this number was a UUID it would not be great for finding a jar that is in cabinet X on row Y without looking up the UUID in the database). 

The value presented is fine. That said, you should put in the catalogNumber field, what you think of as your catalogNumber.

The concatentation (I'm guessing here), was likely created years ago following old recommendations from TDWG when trying to create (more) globally unique identifiers for specimens. So, it may have become standard practice in your collection to use this concatenated string as your catalogNumber.

**Warning:** Where it can get confusing...
- Upon export, collections need a "globally unique identifier" (usually a UUID, or similar). 
- However, some folks still use a Darwin Core Triplet. 
- This Triplet is usually created on "export" by concatenating 3 fields mentioned above (institutionCode + collectionCode + catalogNumber).
- So, if, in the above example, we took this course, you'd end up with (made up example)

MLP:DEN:MLP:DEN:he:100

I hope the water's not too muddy after this ... let me know.

**Comment by LocoDelAssembly** [comment]
The triplet thing was not supposed to be used for occurrenceID (usually prefixed with urn:catalog:)?

The importer-side is expecting this field to have only the actual catalog number, and not it being prefixed strings computed from namespaces. In Belén's example, the desired (but not necessarily achievable) output for the DwC index would be this:
institucionCode|collectionCode|catalogNumber|...
---|---|---|---
MLP|DEN:he|100|...

The more realizable with TW data would be:
institucionCode|collectionCode|catalogNumber|...
---|---|---|---
MLP|MLP:DEN:he|100|...
(repository)|(namespace short name)|(catalog number)|...

Still wouldn't match import data, if the institution of the namespace could also have CODEN-like short name then I guess would be possible.

**Comment by mjy** [comment]
As a note institution code is not the same as identifier namespace.  DwC and others have confused this in part, in TaxonWorks the distinction is clear.

**Comment by debpaul** [comment]
@mjy Darwin Core does now have institution ID and collection ID (separate and distinct from the "code" fields). These are meant to have more robust identifiers.

**Comment by mjy** [comment]
@debpaul yes, my comment was clarifying that in part, see reference to Hernán's example.

**Comment by debpaul** [comment]
Additionally, please note that it is still very common for collectionCode to be a string like:
- herbarium
- entomology
- fish

etcetera

**Comment by mabecabrera** [comment]
Debbie! Here I am. At the Museo de La Plata we are working on an old registers georeferencing project. One curator asked me, maybe the same thing you were talking about this Wednesday before I could connect. 
At this time we are creating the georeferences for old records. And it is very simple from an excel file to create them only once and copy them to all the collection objects that have the same locality... Will we be able to do this from TW in the future? And not having to access each specimen one by one to complete their georeferences? I heard Matt saying something about filters and having the option to edit records from there? 

Hugs!
Belén

    El jueves, 5 de agosto de 2021 14:12:00 ART, Debbie Paul ***@***.***> escribió:  
 
 


Additionally, please note that it is still very common for collectionCode to be a string like:
   
   - herbarium
   - entomology
   - fish

etcetera

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mabecabrera** [comment]
I have noticed that the otherCatalogNumbers column in the dataset I am working with has no values. 
![image](https://user-images.githubusercontent.com/63611746/139872902-f6f4ead8-6aa1-4214-87d8-b2a18472e74d.png)

But the DwC table in the Browse Collection Object task has a value for it. The same as catalogueNumber. 
![image](https://user-images.githubusercontent.com/63611746/139873235-712f2d02-9e45-4584-ac2e-474a465ff219.png)

Why is that?
