### ISSUE TITLE
DWC-Import broken?

### ISSUE THREAD

**Issue by bpescador** [SpeciesFileGroup/taxonworks#2291]
I can't upload a csv file with the DwC-A Workbench.  It states file time not accepted. I am on Sandwich: 
SANDBOX - build b786d3479 on 2021-05-27T23:04:52Z

I used to be able to upload CSV files.  What file format will it accept.  Can it provide guidance rather then just stating it won't accept csv file.

**Comment by bpescador** [comment]
[antweb1ktest.csv](https://github.com/SpeciesFileGroup/taxonworks/files/6581258/antweb1ktest.csv)

**Comment by bpescador** [comment]
I also can't upload .tsv file which I thought was a tab-separated format.

**Comment by bpescador** [comment]
I changed the .tsv to .txt and I can import now

**Comment by mjy** [comment]
Explanation here can move to taxonworks_doc when we triage Question labels.
