### ISSUE TITLE
DwC-A Workbench import cards need delete and back button

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2295]
There's no way to remove uploads that haven't been imported (parsing error, wrong file, etc).

![image](https://user-images.githubusercontent.com/33206210/120545479-901f7b80-c3a3-11eb-9fba-d0de2197dc9e.png)

It would also be nice to have a button to return to the workbench index page (to delete the file) without using the browser's back button.

![image](https://user-images.githubusercontent.com/33206210/120545967-26ec3800-c3a4-11eb-90f2-e662ea8023e7.png)

**Comment by mjy** [comment]
@LocoDelAssembly we disussed with @LocoDelAssembly a couple of options for destroy
* If no data has been imported, just destroy
* If some data has been imported, modal option with confirmation worked, remove dataset and origin relationships

We don't have a way to really nuke everything that was imported efficiently, so this will have to be made clear.

**Comment by jlpereira** [comment]
Done
