### ISSUE TITLE
Task - New Taxon Name - author string.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#230]
If I pick an author, after save it appear next to the taxon name preview on the right. But it does not update the original combination. Besides, original combination and taxon name get Author string from two different sources. One from citation, another from roles.

**Comment by mjy** [comment]
> Besides, original combination and taxon name get Author string from two different sources. One from citation, another from roles.

@proceps  will have to discuss this, not sure I understand.

**Comment by mjy** [comment]
@jlpereira 

1) The top right author year should always come from taxon_names JSON, `cached_author_year`, regardless of the origin of the author strings.  

2) Any time you update top right, also update original combination (which is correct form as currently implemented)

* This may mean you have to turn off the auto-update feature when typing in the `verbatim` field, that's fine.


![screen shot 2017-09-15 at 11 21 32 am](https://user-images.githubusercontent.com/22600/30494382-77e527f4-9a0d-11e7-9154-dc53b7eb93b8.png)

**Comment by mjy** [comment]
Blocked by https://github.com/SpeciesFileGroup/taxonworks/issues/174.   Cached is set by before_save, roles don't exist then, so record is not updated.  Resolution: use `:after_save` for all cached generation.

**Comment by proceps** [comment]
It does not resolve the issue, I can go and change a person, It should fire all roles and update all related cached values.

**Comment by mjy** [comment]
Don't touch, I branched and am resolving.
