### ISSUE TITLE
Task - Filter source - number of citations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2305]
For each source, I would like to see the number of citation by model (number of citation for TaxonNames, Biological associations, Asserted Distributions, etc.)

**Comment by mjy** [comment]
This is in the citations by source task, if it's not, it's where it belongs.

**Comment by proceps** [comment]
Yes, citations by source give details for one source, I would like to filter sources and get summary on number of citations on each model (like nomenclature stats).

**Comment by mjy** [comment]
We anticipate needing the option to send a basic filter result to a different task to display specifics/other stats that take time to calculate there, so to me this is a new task request.  We can't do everything in a timely manner in one place.
