### ISSUE TITLE
Classification or relationship?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2311]
TW "Citations by source" mode contains two different modules for:
1) Taxon name relationships
2) Taxon name classifications

OK. This is super useful and I love it! But... as I understand, a classification is a special form of relationship. 
If a species is combined with a genus, TW calls it COMBINATION (it is a relationship).
If a genus is classified in a subfamily, TW calls it CLASSIFICATION (it is a relationship of the same kind, only as there is no binomen, the name itself doesn't change).

Here in this example I couldn't understand WHY the 3 genera in question (which changed family) appeared in "relationships" instead of "classifications".
If this classification appears under "relationships", WHAT should appear under "classifications"????

![image](https://user-images.githubusercontent.com/46284943/121953169-9c0c2580-cd33-11eb-8712-2f281366c34c.png)

**Comment by proceps** [comment]
Classification in TW is a nomenclatural status. Confusion comes from the terminology used in the base model. For example Nomen Nudum is classification. The status which apply to the name itself. Classified As is a relationship, it requires two names (genus name and family name). Type species is a relationship (it requires two names).
Combination itself a TaxonName model, but it has several relationships: genus in combination, species in combination, etc.

**Comment by adrik29** [comment]
@proceps = thanks for the clarification! The "classification" which appears in that module should be "status" instead of "classification". Terminology is a delicate subject...

**Comment by proceps** [comment]
@jlpereira, could you please change the header from "Classification" to "Status" to match TaxonName Edit terminology.
