### ISSUE TITLE
PDF Document viewer - current document disappears every time

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2312]
There is a vexing **flaw** in the PDF Document viewer: whenever you move away the viewer (close the tab) and opens it again the current document **disappears** and you have to invoke it again by choosing from the pinboard - EVEN IF THERE IS ONLY ONE DOC IN THE INBOARD.
Which is irritating and time consuming.

**Comment by adrik29** [comment]
The problem happens ,whenever you jump to another taxon, which hard-forces the viewer to close.
And the document restarts to slowly load every single time...

**Comment by debpaul** [comment]
@mjy is this issue pointed out by @adrik29 something we can address or is it just that the PDF Viewer software we use inside TW has issues we can do nothing about?

**Comment by jlpereira** [comment]
I think its possible saving the current state of the pdf viewer using local Storage, but i'm not so sure if we can't avoid to download the pdf again.

**Comment by proceps** [comment]
same as #368

**Comment by jlpereira** [comment]
@adrik29 I pushed some changes for this in the development branch. You will see the changes in the next production update.
