### ISSUE TITLE
Adding new Taxon names

### ISSUE THREAD

**Issue by MicrolepiLee** [SpeciesFileGroup/taxonworks#2314]
This is not a bug, more like a basic learning step question about building taxon names in a new project. I am in the exercising/learning step, so please bear with me. After creating a new project, I was able to add new references in Sources. However, I couldn't add any taxon name at all and kept getting an error message "1 error prohibited this protonym from being saved: Parent is not selected." While I was typing Parent name, somehow there was no matching name/item popped up/found for me to select. I guess I am not doing correctly as I supposed to do. Hope I would get navigated to continue exercising in learning. Any assistance would be appreciated!

**Comment by LocoDelAssembly** [comment]
Hi @MicrolepiLee. If this is an empty project it would be normal not finding matching names, you need to create higher taxon names first. There is one name that should be available called "Root" that you can use to start building your taxonomic tree.

Hope this helps.

**Comment by proceps** [comment]
Sangmi, I wold not recommend to use issue tracker as a place to put questions about the interface, gitter would be a better place. To answer your question, you should have the parent taxon in the database before you can select it as a parent. So if you want to have species, you have to enter the genus name. Basically you start with the top level taxon you want to have in your system and go down. For the first name you enter to the DB, you use Root as a parent.

Having this said, I checked the project. The project is created, but it is not populated with Root. And I do not see any way create it.

**Comment by proceps** [comment]
The Root should be populated automatically when a new project created. I think we have a real bug here.

**Comment by proceps** [comment]
I think not, I just tried to create a new test project, it is automatically populated with Root. Probably @MicrolepiLee deleted the root from the project. You can start over, it is a test database. You can create a new one on sandcastle. Basically use Root as a parent for the first taxon you enter to the DB.

**Comment by LocoDelAssembly** [comment]
I'd recommend using sandboxes other than sandcastle, that one will have the database rebuilt very soon. Not sure which sandbox is @MicrolepiLee using.

**Comment by proceps** [comment]
Yes, it is sandstorm, not sandcastle.
