### ISSUE TITLE
Taxon refuses to be destroyed

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2318]
I need serious help here.
There is a taxon marked with a "[c]".
It refuses to be destroyed and it is like a ghost persisting eternally giving me a second Nelima silvatica.
What does this [c] mean and how do I get rid of it?
![image](https://user-images.githubusercontent.com/46284943/123475945-7c49ec80-d5d2-11eb-9464-cc7d1e4b8bb0.png)

**Comment by jlpereira** [comment]
Hello @adrik29,
When you see a taxon name with [c] it means it's a combination. You should be able to destroy it using the radial navigation following these steps:

1 - If you're in browse nomenclature, uncheck "Redirect to valid name"
2 - Use the autocomplete to search Nelima silvatica, choose the one with [c]
3 - Once you're in browse nomenclature with Nelima silvatica selected (The header background should be soft orange), open the radial navigation.
4 - Click on destroy Slice, and type DESTROY to delete it.

That should works. Let me know if not.

**Comment by proceps** [comment]
And in most cases you would not want to destroy it. A subsequent combination is spelled identically as current name of the taxon, but it indicates where and when this combination is created. Remember, the protonym is a reference to the original combination of the taxon.

**Comment by adrik29** [comment]
@jlpereira -- Hello, José Luis -- I had overlooked this "Redirect to valid name".
I think this was cutting my access to the combination.
It seems it worked, but........
There must be some residue because in my GUI there are still 2 Nelima silvatica.
and...
@proceps -- there are TWO Nelima silvatica appearing in my GUI (outside TW). That's why I wanted to destroy one of them.

**Comment by adrik29** [comment]
I decide to MARK the true Nelim silvatica adding the word true to the name:
![image](https://user-images.githubusercontent.com/46284943/123481756-8e2f8d80-d5da-11eb-8b2d-f62130bac836.png)
But now I have THREE Nelima silvatica:
![image](https://user-images.githubusercontent.com/46284943/123481844-aef7e300-d5da-11eb-914e-22f8af183010.png)
Obviously I have some problem in my GUI, but it must have arisen from some residue in TW.

**Comment by proceps** [comment]
You can also use the Filter Nomenclature Task to get access to the right record:
![image](https://user-images.githubusercontent.com/5597748/123483564-87018300-d5cc-11eb-80a3-ed6a7e9cef44.png)

**Comment by adrik29** [comment]
@proceps -- Thanks, Dmitry. It seems that in TW the situation is now resolved. I'll have to investigate next why I'm getting 3 parallel Nelima silvatica in my non-TW GUI.

**Comment by proceps** [comment]
Protonym, original combination, subsequent combination?

**Comment by adrik29** [comment]
> Protonym, original combination, subsequent combination?

Hmm -- it seems a suitable avenue of investigation.
We are experimenting with the API to create a logonymy the way we want, but it seems that we forgot something.

**Comment by adrik29** [comment]
I only find it strange because this doesn't happen in any other taxon.
And we are using the parent/children structure from TW.
