### ISSUE TITLE
LoanItem is not destroyed when the attached object is deleted

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonworks#2319]

**Comment by LocoDelAssembly** [comment]
@mjy What would be the correct procedure here, fail because CO is still being referenced or destroy the loan item?

**Comment by tmcelrath** [comment]
Should this be "loan item" not "loaditem"?

**Comment by tmcelrath** [comment]
Also causes loans to be unable to load if a container is a loan item, then that item is "uncontainerized"
E.g. I make a loan with a loanitem that is a container with the identifier on the container (loanitem type container)
Then I make that containerized item not a containerized item.
Then I get an error when trying to access the loan.
