### ISSUE TITLE
Nomenclatural comments: how to show them?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2320]
Good Sunday to everyone:
Where should I write this kind of nomenclatural note (the part following the double dagger):
• Libitioides ornata Roewer 1912d: 15. **_‡ Nomen made available by deliberate employment of Wood’s misidentification (Code Arts 11.10 and 50.1), but originally incorrectly attributed to Wood, 1868._**

And more importantly:
How can I make it visible in the browse nomenclature or at least in my own GUI logonymy (meaning, can I get this from the API???).

**Comment by adrik29** [comment]
I thought about using the "notes".
But what good is this note field if this information remains hidden? How can I display it in my logonymy?
![image](https://user-images.githubusercontent.com/46284943/123555904-ea231f00-d75e-11eb-9319-a6a74d72eb4b.png)

**Comment by adrik29** [comment]
I noticed that my "notes" appear in the "Taxon names" module. So I ask: can I get the content of my notes using the TW API?
![image](https://user-images.githubusercontent.com/46284943/123555979-4d14b600-d75f-11eb-97aa-f8b0263b5f5b.png)

**Comment by jlpereira** [comment]
Hi @adrik29 

It's possible get notes using the API. You have to set the following object parameters:
`note_object_id`
`note_object_type`

or

`object_global_id`

For example, lets say you want to get the notes of the following taxon name:

```JSON
{
  "id": "123",
  "name": "foo",
  "global_id": "gid://taxon-works/Protonym/123",
  "base_class": "TaxonName"
}
```

And let's assume the following configuration:

```
host: 127.0.0.1:3000 // Your server host
token: abcd // Your user API token
project_id: 1 // The project where you have the note
```

Two possible ways:

By global id:
`http://127.0.0.1:3000/api/v1/notes.json?token=abcd&project_id=1&object_global_id=gid://taxon-works/Protonym/123`

By ID and type:
`http://127.0.0.1:3000/api/v1/notes.json?token=abcd&project_id=16&note_object_id=623397&note_object_type=TaxonName`


For more information:
https://api.taxonworks.org/#/notes-get

**Comment by adrik29** [comment]
@jlpereira -- Thanks a lot José Luis. TW is already fantastic, but still more fantastic is the level of care and response that you give to the TW community!
Much appreciated!
