### ISSUE TITLE
Task - New Image - add option to Depict some Person

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2321]
<img width="558" alt="Screen Shot 2021-06-28 at 9 30 22 AM" src="https://user-images.githubusercontent.com/22600/123654305-91519600-d7f3-11eb-91c0-fa4a5230f050.png">

**Comment by debpaul** [comment]
Images need metadata about permissions to use, and formats available? See GitHub [TDWG AC](https://github.com/tdwg/ac) repo and [website](https://www.tdwg.org/standards/ac/). So if we can add images of people, where does this metadata go?

**Comment by LocoDelAssembly** [comment]
In case not covered by what @debpaul mentions, could be potential privacy concerns? This would not be a user uploading a profile picture but user adding pictures on behalf of other people.

**Comment by debpaul** [comment]
> 
> 
> In case not covered by what @debpaul mentions, could be potential privacy concerns? This would not be a user uploading a profile picture but user adding pictures on behalf of other people.

Yes exactly @LocoDelAssembly. That's what I'm getting at. If these images are "used with permission" great. But if they are openly available through the TW API, they need metadata clarifying use. Else, there could be privacy and use concerns.

**Comment by mjy** [comment]
@debpaul - TaxonWorks has a full attribution model, you simply add it in the new image task or at any time afterwards through the radial annotaqtor.

People are public shared data in TaxonWorks.  They are not Users.  You must assume that any data attached to them will be made public, period, there will be no option to make People data private, i.e. we will not update the *software* to allow for data on People to be private.  The data in individual instances of TaxonWorks are another matter, the SFG support instances will assume that all data are public, in other instances it's up to those managing the installatin.

**Comment by debpaul** [comment]
@mjy to be sure I understand, a short story.

Say I share an image I "found on the internet." It gets into TW, and then discovered via the TW API. I use it in my presentation, but w/o proper metadata, or rights to use it. Bots come along and sniff this out. Now I'm asked to pay a fine b/c I did not have permission, or b/c I did not properly cite the image. 

I'm all for making these data public. But at the same time, we need to help our TW users not trip over these unpleasant possibilities? We may also need a disclaimer for TW too.

**Comment by mjy** [comment]
>  I use it in my presentation, but w/o proper metadata, or rights to use it. Bots come along and sniff this out. Now I'm asked to pay a fine b/c I did not have permission, or b/c I did not properly cite the image.

This problem is not special to TaxonWorks.  We can't, and don't want to control what users put in their presentations.  We can, and should, provide Attribution to data in TaxonWorks so when they find an image they can use that data.
