### ISSUE TITLE
Nomen nudum appears as valid and invalid at the same time (in Summary box)

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#2327]
When I enter a nomen nudum, the summary box lists that species as valid and invalid at the same time. (Right screen, below)
<img width="1919" alt="Screen Shot 2021-10-07 at 4 23 05 PM" src="https://user-images.githubusercontent.com/22600/136464212-dcf7a93b-c173-4a0d-9470-7a3c0a5914b2.png">

I would not expect to see this contradictory statement displayed.

**Comment by debpaul** [comment]
Thanks @hhopkins77 for adding this ticket.
