### ISSUE TITLE
Task - ColDP - Download button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2335]
![image](https://user-images.githubusercontent.com/5597748/125380718-42aa0d00-e358-11eb-9526-cae2758686d6.png)

Update button is more prominent than Download hyperlink. Make both buttons. It is reported, that Update button is used by mistake when download is actually intended. Probably make them different color: update - blue, download - green.

**Comment by mjy** [comment]
@LocoDelAssembly @jlpereira we need a general widget/approach that injects the JS into non Vue pages to handle async checkups of the process I think?  This, and other pages would benefit from a slicker (working/done) type approach.
