### ISSUE TITLE
New problem with "Citations by source" task

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2336]
The "Citations by source" task have always worked very well for us, but today I noticed that is fails to show some "Taxon names" while others appear perfectly.
I suppose this is related to some other change in the code which affected this module.
I give here an example of Hadzi 1973 in which we have 12 entries,
HERE = https://sfg.taxonworks.org/sources/111292/related

of which only 5 appear in "Citations by source".
HERE = https://sfg.taxonworks.org/tasks/nomenclature/by_source?source_id=111292

**Comment by proceps** [comment]
Project Opiliones
