### ISSUE TITLE
As a curator I want a "batch" annotator on all filters

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2340]
When I filter a set of records, then I can tag them in some (all?) cases.  I would like to further annotate them.

Proposal:

* [x] Add a new "meta" annotator icon, it should rif on the old one, but also include a "group" concept visual element
* [x] Add it to the top of filter forms
* [ ] It should have similar status updates bar to the current DwC form, showing progress in annotating the filtered set of records
* [x] It should allow users to create a Tag on all filtered result
* [x]  It should allow users to create a Citation
* [x] It should allow users to create a Confidence Level
* [ ] It should allow users to create a DataAttribute::Internal
* [x] It should allow users to create a Note
* [ ] It should allow users to replace all of the existing annotations of some type with this type
* [ ] It should allow users to remove all of the existing annotations of some time

**Comment by proceps** [comment]
Citations?
Editing the filtered records? (like - change a parent for all filtered taxon_names).

**Comment by mjy** [comment]
Citations yes, editing the records is the pervue of a different task.

**Comment by mjy** [comment]
It should allow curators to destroy:
* [ ] <some> tags on all selected
