### ISSUE TITLE
DwC importer create Type Material from typeStatus column

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2343]
During DwC-A imports, would it be possible to automatically create Type Material records from the type status column?

For example:
```
| catalogNumber | typeStatus                     | scientificName     |
|---------------|--------------------------------|--------------------|
| CASENT0005538 | Holotype of Strumigenys fronto | Strumigenys fronto |
```

should create a type material for Strumigenys fronto linking to this collections object.

**Comment by mjy** [comment]
@LocoDelAssembly I think a strict match maybe be possible here, allowing at least some assertions?  

If:
* `scientificName` string is found in `typeStatus`
* a TW type (constant) is found in `typeStatus`
* `scientificName` is unique in TaxonNames
Then:
* TypeMaterial record can be created?

**Comment by LordFlashmeow** [comment]
I would suggest requiring a stricter format for the field.

The DwC spec allows multiple types for a single Identification, and gives this as an example: `holotype of Pinus abies | holotype of Picea abies`. 

The field may also have a publication attached, which is a whole other can of worms to parse. From DwC: `holotype of Ctenomys sociabilis. Pearson O. P., and M. I. Christie. 1985. Historia Natural, 5(37):388`. 

What about having a field for the TW type, and using the existing `scientificName`?

**Comment by mjy** [comment]
Also good, thanks for reminder. The field for TW type is `TypeMaterial::TypeType`.

The following then would also work, and is more precise:

If 
* `TypeMaterial::TypeType` and it matches our vocab
* `scientificName` matches a name uniquely (but see `cached_original_combination` for more precision)

Then
* We create a TypeMaterial record

**Comment by LordFlashmeow** [comment]
Makes sense to me. What do you suggest is the best way to store the original TypeStatus string? In my data, I'm going to parse the field to extract the type, but I'd like to save the original string somewhere as well.

**Comment by proceps** [comment]
CollectionObject.verbatim_determination_laber or CollectionObject.verbatim_other_label is good place for it. A data attribute on CollectionObject is another option.

**Comment by LocoDelAssembly** [comment]
> CollectionObject.verbatim_determination_laber or CollectionObject.verbatim_other_label is good place for it. A data attribute on CollectionObject is another option.

If you add custom attribute for collection object with predicate URI `http://rs.tdwg.org/dwc/terms/typeStatus` the importer will automatically add the attribute for you with the value as-is. Works for collection object and collecting event and you can freely pick either or both as the target for the data attribute.

Just added rudimentary support for `typeStatus` import into `TypeMaterial`. Will only work if matches `scientificName` and has the `<type_type> of <scientific_name>` pattern.

**Comment by mjy** [comment]
Related: https://github.com/SpeciesFileGroup/taxonworks/issues/2363

@LordFlashmeow let us know if the support added by @LocoDelAssembly helps.

> Just added rudimentary support for typeStatus import into TypeMaterial. Will only work if matches scientificName and has the <type_type> of <scientific_name> pattern.

**Comment by LordFlashmeow** [comment]
Yep, about half (10k of 25k) of the types  are for valid names, so the `scientificName` matches the name in the `typeStatus` field. For the other half, we'll need to use the batch importer.
