### ISSUE TITLE
Task - Edit TaxonName - Original combination

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2346]
for new TN, the fields are not visible.
![image](https://user-images.githubusercontent.com/5597748/125728636-fd124569-3c4a-4cbf-a207-c0ee037e9a46.png)

**Comment by jlpereira** [comment]
I can't replicate it. Steps?

**Comment by proceps** [comment]
Browser Chrome. I do not see the section only when I enter a new genus or species name to the database. I can still use Set as current classification button and edit the section after. With the names which has the original already set, the section is available. Checked also development. Result is the same.

**Comment by mjy** [comment]
Can you check the developer tools to look for errors?  Also, the specific id of the name you are looking for?

**Comment by jlpereira** [comment]
Replicated, fixing
