### ISSUE TITLE
neoparatype

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2349]
On behalf of @bpescador:

is there a reason "neoparatype" is not an accepted type status? In ants, when a Neotype is created, there are often neoparatypes created.

**Comment by proceps** [comment]
ICZN does not support allotypes, neoparatypes, etc.

**Comment by LocoDelAssembly** [comment]
How should the type material be recorded if that is all the data you have? (Not on behalf @bpescador this time :)

**Comment by bpescador** [comment]
what about "paraneotype"?

**Comment by bpescador** [comment]
or are you saying that TW ignores all Secondary types?

**Comment by bpescador** [comment]
the question I guess if TW does not accept how specimens are designated as types, then where do we put that information.  our data includes many kinds of types (pretty much these: http://gbif.github.io/parsers/apidocs/org/gbif/api/vocabulary/TypeStatus.html)

is there a typeRemarks field or a verbatim type field we should use instead

**Comment by tmcelrath** [comment]
Hey Brian - I think what Dmitry is saying is that since neoparatype has no nomenclatural status, it is not available to select. It can be selected as a paratype in TW easily enough. I do like the idea of having a verbatimtypestatus field available though.

**Comment by proceps** [comment]
TW only recognize only official ICZN types, not logotypes, not topotypes, etc. We have 3 verbatim labels associated with each specimen. Determination label or Other label would be an appropriate place to store this information. This is valid part of the specimen metadata, but the specimen should not be labeled as a type specimen, it is not.
Once neotype is designated, it nullify the status of all other types associated with the taxon name.

**Comment by mjy** [comment]
@tmcelrath and @proceps are correct, we only manage recognized types. Because types are a matter of preference at many different levels, they are best handled not as a new field, but as a DataAttribute by those want to record additional information.
