### ISSUE TITLE
Task New Taxon Name - Add ClassifiedAs Relationship to All List

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#235]
Probably just have to update the All constant.

**Comment by mjy** [comment]
@proceps Is this done now with the constant fixes?

**Comment by proceps** [comment]
No, It requires finding a family group taxon for a genus or species and it is not possible for the current set up. This one and Incerte sedis probably require alternative implementation. But may be we should just try to remove the rank restriction for the taxon search and add classified as additional relationship which could be assigned to the taxon. That is an important relationship, which is not possible to record with a present setup.

**Comment by mjy** [comment]
* Potential new section that lets you look for object outside of scope assigned in relationship

**Comment by proceps** [comment]
Could you check this issue as well? It is similar to Incertae sedis, but require an alternative "parent" taxon selection.

**Comment by mjy** [comment]
@proceps there were some questions that I think we need to clarify.  Is the intent that this is family group names only?  Higher only?  We need to define this quite precisely.  Check the domain/range in the model for the current settings.

**Comment by proceps** [comment]
Yes, this is family group and higher. The model should already be set for this. The genus placement could be set up with combination. Unless we want to use it to assemble the alternative classification, than any rank of parent (alternative parent) is acceptable entry.

**Comment by mjy** [comment]
Thanks.
