### ISSUE TITLE
Data Attributes

### ISSUE THREAD

**Issue by jcabbott13** [SpeciesFileGroup/taxonworks#2350]
In the Odonata project, there is a data attribute named 'distribution' that contains distribution information for each species. Is there a way to 1) filter the otu's that lack this information and 2) export otu's along with this information?

**Comment by mjy** [comment]
Closing for:

https://github.com/SpeciesFileGroup/taxonworks/issues/1633
https://github.com/SpeciesFileGroup/taxonworks/issues/2366
