### ISSUE TITLE
Setting DwC-A import catalog number namespace mapping does not mark items as ready

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2355]
**To Reproduce**
1. Load DwC txt file with collectionCode field
2. Assign namespace mappings in settings
3. The rows do not update to ready, even though they have namespaces mapped

Changing the collectionCode value to something new marks the cell as ready.

![image](https://user-images.githubusercontent.com/33206210/126395762-aa993000-0e95-417b-8e86-acec7b78215c.png)

**Expected behavior**

After selecting a namespace for the catalogCodes, the related rows should become ready to import

**Environment (please identify where you experience this bug:**
- Development (native)

**Comment by LocoDelAssembly** [comment]
Can you upload a sample file to test? (Just a subset of the table enough to reproduce)

Last commit I pushed had to go through setting up namespaces to test and didn't encounter any issues. Status doesn't change until Settings dialog is closed IIRC.

**Comment by LordFlashmeow** [comment]
I stripped all the prefixes out of this, but you may need to create the namespace

[ant_small.txt](https://github.com/SpeciesFileGroup/taxonworks/files/6851336/ant_small.txt)

**Comment by LocoDelAssembly** [comment]
Thanks! Found problem, header says `InstitutionCode` instead of `institutionCode`. Missing case insensitivity somewhere. Looking code now.
