### ISSUE TITLE
Mapping DwC EventID to TripCode

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2359]
As discussed over zoom, the DwC `eventID` field should probably be mapped to `TripCode`. 

We could use the same parsing method as `collectionCode`, and require the namespace to be provided as a separate column.

**Comment by LocoDelAssembly** [comment]
`eventID` acts more like `taxonID` and `occurrenceID` and should be unique within the dataset (not just some row-dependant namespace). Is `eventID` unique within the dataset or at least when duplicate them all refer to the same event in AntWeb data?

If we were to export from TW, eventID would be either CollectingEvent.id or some other database-wide unique value.

**Comment by mjy** [comment]
`eventId` is not unique per dataset, but per CollectingEvent.  An error should be raised (or we could just assume identity) when CollectingEvent params differ for an identical `eventID`.

**Comment by LocoDelAssembly** [comment]
eventID|-
 --- |---
Identifier | http://rs.tdwg.org/dwc/terms/eventID
Definition | An identifier for  the set of information associated with an Event (something that occurs  at a place and time). May be a global unique identifier or an **identifier specific to the data set.**
Comments |  
Examples | INBO:VIS:Ev:00009375

> It should map to Identifier::Local::TripCode, just to be on the same page.

But with a single namespace like `occurrenceID` and not like `catalogNumber` that namespaces are row-dependent, right?

**Comment by LordFlashmeow** [comment]
No, I think they the namespaces may be row-dependent. 

The events come from different collectors, and each should have their own namespace (AFAIK). 

For example, several specimens are collected during the event recorded as `BLF25204`. This trip should be added under the `BLF` namespace, so they can be grouped with other collecting events by Brian.

We also have specimens collected by P.S. Ward, who uses the `PSW` prefix for their events. They should be assigned to the `PSW` namespace. (Conveniently, his specimens also go in that namespace).

**Comment by LocoDelAssembly** [comment]
```ruby
    # fieldNumber: verbatim_trip_identifier
    set_hash_val(collecting_event, :verbatim_trip_identifier, get_field_value(:fieldNumber))
```
The importer currently has the mapping above. Would `fieldNumber` be suitable for this? (Or both `fieldNumber` and `eventID`, but do some trick to ensure `eventID` uniqueness.)

**Comment by LordFlashmeow** [comment]
I don't think so, since we would like to use the namespacing provided by `TripCode` identifiers.

**Comment by LordFlashmeow** [comment]
Any update on this?

**Comment by mjy** [comment]
There is an underlying issue, if we could detect the format of `eventId` (and other `fooId`), then we could better map it to a TW identifier type (e.g. some might be UUIDs or URIs).

* `fieldNumber` semantics are identical to `Identifier::Local::TripCode`

... more on spreadsheet to be reflected here.
