### ISSUE TITLE
Allow batch importing invalid taxonomic names

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2364]
The current batch importer doesn't allow linking invalid names to valid names, which prevents us from importing ~15k invalid taxon names (synonyms, homonyms, unavailable, misspellings, etc.) 

Can the functionality of the Taxon Name importer be expanded to load this information?

**Comment by mjy** [comment]
@LordFlashmeow can you confirm the importer you are describing?  `/taxon_names` or the DwC importer? Both don't handle synonyms, we just need to know which you refer to for this issue.

**Comment by LordFlashmeow** [comment]
`/taxon_names`

**Comment by LordFlashmeow** [comment]
Importing invalid names has been implemented in the DwC Checklist importer
