### ISSUE TITLE
Edit biological associations - fields are not correctly mapped

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2370]
![image](https://user-images.githubusercontent.com/5597748/127221645-242b7b11-fd12-4a8c-a56f-01505f337d43.png)

**Comment by proceps** [comment]
Fields are not properly mapped. Both OTUs and CollectionObjects are mapped to each field on either side of the relationship

![image](https://user-images.githubusercontent.com/5597748/127414602-2de26221-95ba-4a86-a748-02daff106a82.png)

**Comment by jlpereira** [comment]
I gonna change the title of this, because it's a different issue
