### ISSUE TITLE
What happened to typing numbers?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2386]
Good day to all:
I have noticed that typing numbers in many of TW's forms is compromised.
Maybe you are already aware of this and are working on the problem, maybe not.
I have even bought myself a new keyboard thinking it was a problem on my side.

**Comment by debpaul** [comment]
@adrik29 can you give us an example or screenshot please?

**Comment by adrik29** [comment]
Here:
Number 2 never enters -- I tried to type page 20 and instead I got page zero.
![image](https://user-images.githubusercontent.com/46284943/128241307-4122c7ed-55a3-434b-9794-f0dc80a7c085.png)

**Comment by adrik29** [comment]
Also in "New source" module, numbers 12345 never enter.

**Comment by adrik29** [comment]
And I have tried different browsers.

**Comment by proceps** [comment]
I cannot replicat (production and development)

**Comment by adrik29** [comment]
Does it mean your numbers are entering normally?

**Comment by proceps** [comment]
Tried in Chrome only

**Comment by adrik29** [comment]
I have now tried with:
Chrome = fail
Microsoft Edge = fail
Mozilla Firefox = OK

**Comment by proceps** [comment]
computer restart?

**Comment by adrik29** [comment]
No, Dmitry -- this is going on since many many days, through many restarts.
Big mystery to me -- I suspected it could be some change you introduced in the system.

**Comment by adrik29** [comment]
I will inquire in my team to see if someone has the same problem.

**Comment by proceps** [comment]
could you try different computer?

**Comment by proceps** [comment]
Well, I recently had a problem with my mouse when it did double click instead of sing (only occasionally), I thought I am getting crazy.

**Comment by adrik29** [comment]
Hm, I tried in another computer and the numbers take a while but they end up appearing.
This is all very strange to me.
For now, I will migrate my work in TW to Mozilla, but there must be some weird stuff going on.
I hope it is not a virus.

**Comment by proceps** [comment]
https://www.techbout.com/keyboard-not-typing-numbers-windows-10-48426/

**Comment by debpaul** [comment]
> 
@proceps @adrik29 I have had this happen to me before (in general not just in TW). Thanks @proceps. Let us know if any of these steps help @adrik29 !

> https://www.techbout.com/keyboard-not-typing-numbers-windows-10-48426/

**Comment by adrik29** [comment]
@debpaul -- thanks for the hints, I will make sure I'll try those.
I JUST HATE WINDOWS 10 WITH ALL MY HEART.

**Comment by debpaul** [comment]
@adrik29 closing this ticket now. If you need help to sort this out, please contact me by email or gitter and we can meet online to solve it together. Windows does have some wonderful "features."
