### ISSUE TITLE
data view - Collecting Event - Edit button should resolve to new Edit interface in tasks

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2387]

**Comment by mjy** [comment]
Screenshot?
<img width="597" alt="Screen Shot 2021-08-05 at 9 28 34 AM" src="https://user-images.githubusercontent.com/22600/128367417-eadddc59-d0d3-4aa6-a37c-044525bf8861.png">

**Comment by proceps** [comment]
I think I was redirected to data editing page. In the Data page for collecting event, when I click Edit button, I should be redirected to a new Edit Collecting Event page.
