### ISSUE TITLE
Task - New Taxon Name - conflicting statuses

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#239]
selecting a Status does not update the Soft Validation list. 
When I select two conflicting relationships (e.g. 'Nomen nudum' and 'Valid') I do not get a warning. only after a page refresh.

**Comment by jlpereira** [comment]
![image](https://user-images.githubusercontent.com/16530364/30672755-b305851e-9e44-11e7-8f19-3d068626a9ca.jpeg)

This was done without refresh the page, the status is updated every time you add or delete an status.

Can you check this again? and see in the browser console if you're getting a message

**Comment by mjy** [comment]
Also works for me. @proceps list your browser please.
