### ISSUE TITLE
Task - Browse collection object - fails to initiate

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2392]
in development
![image](https://user-images.githubusercontent.com/5597748/128379449-5628885a-976e-4638-80c3-eff948a1c237.png)

**Comment by mjy** [comment]
Restart your server.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/128399434-d213590f-bf36-47f9-b4b4-11e830ec3aa7.png)
