### ISSUE TITLE
DwC importer: Predicate NoMethodError

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2398]
**Describe the bug**

DwC import with custom predicates causes rows to report failed.

Relevant code: https://github.com/SpeciesFileGroup/taxonworks/blob/e89a42a22357ae2a4ed38121fd20db22a2b0dbd5/app/models/dataset_record/darwin_core/occurrence.rb#L910-L914

```
NoMethodError - undefined method `sanitize_sql_like' for #<DatasetRecord::DarwinCore::Occurrence:0x00007fdc2375cd10>:
  app/models/dataset_record/darwin_core/occurrence.rb:913:in `append_data_attribute'
  app/models/dataset_record/darwin_core/occurrence.rb:886:in `block in parse_tw_collection_object_data_attributes'
  app/models/dataset_record/darwin_core/occurrence.rb:885:in `parse_tw_collection_object_data_attributes'
  app/models/dataset_record/darwin_core/occurrence.rb:82:in `block in import'
```

**Comment by LocoDelAssembly** [comment]
Thanks @LordFlashmeow, worked fine somewhere else but here failed because this is in the context of an instance method.
