### ISSUE TITLE
Project list sort by date incorrect 

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2399]
Projects in the list are sorted alphabetically by date instead of numerically.

![image](https://user-images.githubusercontent.com/33206210/128772848-80a33207-0541-4799-9722-62fdd2d7f668.png)

**Expected behavior**

I expect the list of projects to be listed in chronological order.

**Environment (please identify where you experience this bug:**
- Sandbox - Sandwich

**Comment by LocoDelAssembly** [comment]
Just to clarify, it is actually sorted by `Project.id` (and implicitly by `created_at` but not shown in table).

What I mentioned is at backed-side, almost push `[Comment]` when I realized you're using sorting by column. I'm afraid there are even more problems than lexicographical on all columns regardless of underlying data type, I bet sorting is happening on current page only and this likely is a widespread issue on most of `/list` data views.

**Comment by mjy** [comment]
All stock `/list` do not sort across the whole dataset, they are page only.  This was an early issue (might still be).  We will likely not change this, functionality should be done in filter results, for example.
