### ISSUE TITLE
Namespace short name uniqueness clarification

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2402]
Should namespace short names be case-sensitively unique or case-insensitive? 

If insensitive, there should be a hard validation on it. If not, `Namespace.find_by` code should be double-checked to make sure we're using case-sensitive searches.

**Comment by LocoDelAssembly** [comment]
`find_by` is case-sensitive:
```ruby
2.7.4 :004 > Namespace.find_by(short_name: 'Taxon Code')
  Namespace Load (0.8ms)  SELECT "namespaces".* FROM "namespaces" WHERE "namespaces"."short_name" = $1 LIMIT $2  [["short_name", "Taxon Code"], ["LIMIT", 1]]
 => #<Namespace id: 1, institution: "INHS Insect Collection", name: "INHS Taxon Code", short_name: "Taxon Code", created_at: "2019-08-28 14:44:24", updated_at: "2019-08-28 14:44:24", created_by_id: 3, updated_by_id: 3, verbatim_short_name: nil, delimiter: nil> 
2.7.4 :005 > Namespace.find_by(short_name: 'Taxon code')
  Namespace Load (0.8ms)  SELECT "namespaces".* FROM "namespaces" WHERE "namespaces"."short_name" = $1 LIMIT $2  [["short_name", "Taxon code"], ["LIMIT", 1]]
 => nil 
```

Validators and table indices are case sensitive so it is possible to re-use existing `name` and `short_name` by single-letter case toggling. `name` being case sensitive is likely a bug, not sure about `short_name` @mjy?

**Comment by LordFlashmeow** [comment]
So should this be case-sensitive?

https://github.com/SpeciesFileGroup/taxonworks/blob/ad4af3146b8d42188f887964b64bab9ca0df75b4/app/models/dataset_record/darwin_core/occurrence.rb#L150

**Comment by LocoDelAssembly** [comment]
I remembered why I did that, it was for convenience because the dataset might have different case than stored in TW database (and maybe some sample data actually had problems?). If `short_name` is supposed to be case-sensitive unique and not case-INsensitive then have to change this and users will need to use find-and-replace functionality to fix the data when a match is not found because of case mismatch.

**Comment by LordFlashmeow** [comment]
Is it too much work for users to fix if we raise an error when `TW:Namespace:eventID` case doesn't match `short_name`?

**Comment by LocoDelAssembly** [comment]
Not super laborious to do a few, but I'd rather avoid demanding strictly equal short name if it is actually a bug to have 'ants', 'Ants' and 'AnTs' in the same TaxonWorks instance.

**Comment by LordFlashmeow** [comment]
I agree, but what if they are distinct? The search won't prioritize an exact case match, so only one identifier will be used for all rows

**Comment by mjy** [comment]
@debpaul can you think of cases "in the wild", real, actual cases, where namespace short name differs only in case?

I am leaning to requiring short name be case-insentive hard-validated at the moment.  We are not building a full dataset editor, this is an importer, there are lots of tools (Refine) that can help users unify their values, we don't need to replicate (all) those in TW.

**Comment by mjy** [comment]
This was resolved with new specs.
