### ISSUE TITLE
DWCA Importer - eventDate import help and recommendations conflicting

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2406]
When I am formatting a date range, the help (show below from DWCA) recommends that event date ranges are formatted like so:
XXXX-XX-XX/XX e.g. 2015-10-05/07
![image](https://user-images.githubusercontent.com/11411328/128915351-c5c5ec22-1df8-475f-892f-b542e8bed373.png)
![image](https://user-images.githubusercontent.com/11411328/128915328-c2d04fbc-51cd-4a77-97cc-755f556f25d6.png)
As shown in TW help: 
![image](https://user-images.githubusercontent.com/11411328/128915468-628c7c2d-cd88-4b6d-bd26-12ecbec6f4b8.png)

But, when I format an eventDate range like that, the date is errored and recommends a different format, XXXX-XX-XX/XXXX-XX-XX, e.g. 2015-10-15/2015-10-17:
![image](https://user-images.githubusercontent.com/11411328/128915627-d9581d47-703f-471d-977d-ae3ff9b57dc4.png)

We need to pick one or the other and stick to it.

**Comment by LordFlashmeow** [comment]
It's not too hard to make a regex to capture this scenario. Do you want to support this or diverge from the DwC standard?

**Comment by LocoDelAssembly** [comment]
Despite read the Wikipedia article multiple times and systematically concluded truncated end datetime is not mentioned now I clearly see it... (Did I switch to a different universe during my sleep?)
>For <start>/<end> expressions, if any elements are missing from the end value, **they are assumed to be the same as for the start value** including the time zone. This feature of the standard allows for concise representations of time intervals. For example, the date of a two-hour meeting including the start and finish times could be simply shown as **"2007-12-14T13:30/15:30", where "/15:30" implies "/2007-12-14T15:30" (the same date as the start), or the beginning and end dates of a monthly billing period as "2008-02-15/03-14", where "/03-14" implies "/2008-03-14" (the same year as the start).**

This needs to be supported.

PS: Maybe truncated representation was not supported in previous ISO8601:2004 standard?

**Comment by LocoDelAssembly** [comment]
Not used hash to keep compatible output with original `parse_iso_date` method that used Ruby's own `DateTime` class. `OpenStruct` is closer to hash because you can add attributes dynamically and still refer them with `.` instead of `[x]`. `Struc` IIRC you need to "create a type", then use it.

You may of course change all of this if simplifies coding and readability. Let me know if you need help implementing this or if you prefer that I do it.

**Comment by LordFlashmeow** [comment]
Upon further inspection, `OpenStruct` does seem like the cleanest solution, since there's not a neat way to create a `Struct` from a hash. 

Anyways, I'll write some unit tests to make sure it works as intended.

**Comment by LordFlashmeow** [comment]
Hmm, this can't handle inputs like `2015-10/11`. Might need to do some more rewriting.

**Comment by LocoDelAssembly** [comment]
Also make sure this one works, originally `parse_iso_date(:eventDate)` returned empty array (or `nil`?).
```ruby
2.7.4 :057 > parse_iso_date_str(nil)
Traceback (most recent call last):
        3: from (irb):56
        2: from (irb):57:in `rescue in irb_binding'
        1: from (irb):3:in `parse_iso_date_str'
NoMethodError (undefined method `with_index' for nil:NilClass)
```

**Comment by LordFlashmeow** [comment]
Abbreviated end dates should be working now, if you'd like to test them out. If you encounter any bugs feel free to open a new issue.
