### ISSUE TITLE
Geographic areas not scoped in Georeferences pane until georeference added

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2408]
**Describe the bug**
Geographic areas not scoped in Georeferences pane until georeference added.

**To Reproduce**
1. When I add a Geographic area to a collecting event.
2. Then I go to georeferences pane
3. Then I do not see a geographic area
4. Then I add a georeference in that geo area
5. Then the geo area shows up.

Geo. area added:
![image](https://user-images.githubusercontent.com/11411328/129069642-2d74978e-a1ae-468c-9838-b2c88a0a7bd5.png)
Geo pane opened:
![image](https://user-images.githubusercontent.com/11411328/129069679-9fba27c6-4e21-4de0-bf4d-894d696f70d3.png)
Added a georeference:
![image](https://user-images.githubusercontent.com/11411328/129069836-e027e419-50b8-4693-94c0-178f7cdee5c2.png)

**Expected behavior**
Should auto-scope to geo. area before adding georeference

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by jlpereira** [comment]
Fixed
