### ISSUE TITLE
Custom attributes are missing from comprehensive specimen digitization

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2426]
Inside comprehensive specimen, there's a section for custom attributes in the CollectionObject and CollectingEvent. It's always empty, and data attributes must be added via the radial annotator. When a collectionobject has data attributes, they don't show up in this section.

![image](https://user-images.githubusercontent.com/33206210/129625083-515df6d8-381e-40bb-8bb8-0e249bb2a454.png)

**Environment**
- Sandbox - sandwich

**Comment by jlpereira** [comment]
@LordFlashmeow Click Project in the header bar, then click on Preferences, if you dont find it, just replace the host in this link `http://localhost:3000/tasks/projects/preferences/index`. There you can select the model and the data attributes you want to see there

**Comment by LordFlashmeow** [comment]
Can I change the link so it points to the preferences page instead of `Create a term (Predicate)`?

**Comment by mjy** [comment]
Yes
