### ISSUE TITLE
Collecting Event generated label shows latitude and longitude twice

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2427]
**Describe the bug**

The generated label has the coordinates written twice, once on separate lines and once on a single line together.

**To Reproduce**
1. Input verbatim latitude and longitude
2. Click the button to parse to georeference
3. Click Generate Print Label

```
US UT Millard Co.: Swasey Peak, 64 km W Delta
39.38815
-113.31633
2021/09/09
39.38815, -113.31633
9.ix.2021
2945.0m
Fisher, B.L.
BLF49600
```

![image](https://user-images.githubusercontent.com/33206210/129622394-8305a217-232e-4bfc-8977-51175e098cee.png)

**Expected behavior**
I expect the label to only include the coordinates once.

**Environment (please identify where you experience this bug:**
- Sandbox - sandwich

**Comment by mjy** [comment]
I think this was intended, to proof the label.  1x is from verbatim, 1x is a value from Georeference.
