### ISSUE TITLE
Enhancement: shortcut to select annotator slices

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2431]
(Continuing from #2351)

It would be very helpful to have shortcuts to switch to specific slices once the annotator is open. For example:

* `n` -> Notes
* `t` -> Tags
* `d` -> Data Attributes
* `i` -> Identifiers
* `c` -> Citations
* `p` -> Protocol Relationships
* and others for confidences and depictions

Ideally, they don't need a modifier key (like control) to activate, only that a text box not be active.

If they need a modifier key to activate, would it be possible to disable page shortcuts (like `ctrl-n` for new) while the annotator is open? This way we can reuse the same keybindings (so `ctrl-n` opens the notes slice) without conflicts.

**Comment by jlpereira** [comment]
@LordFlashmeow each shortcut is the first letter of the section. Sometimes it will be more of one option with the same letter. In that case the selected slice will change between those each time you press key.
