### ISSUE TITLE
Potential bug: increment identifier in CO editor keeps number of leading zeros, changing length of number

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2435]
**Describe the bug**

The number of leading zeros stays the same when the identifier increments from 999 to 1000 in the CO editor.

For example: `0099` becomes `00100` instead of `0100`

See [a visualization here](http://pythontutor.com/visualize.html#code=function%20increment%28textString%29%20%7B%0A%20%20if%28textString%20%3D%3D%20undefined%20%7C%7C%20!%28/%28%5Cd%2B%29/g%29.test%28textString%29%29%20return%20textString%0A%0A%20%20let%20numbers%20%3D%20textString.match%28/%28%5Cd%2B%29/g%29.map%28Number%29%0A%20%20let%20index%20%3D%20numbers.length-1%0A%20%20let%20newValue%20%3D%20numbers%5Bindex%5D%20%2B%201%0A%20%20let%20start%20%3D%20textString.lastIndexOf%28numbers%5Bindex%5D%29%0A%20%20let%20numberLength%20%3D%20numbers%5Bindex%5D.toString%28%29.length%0A%0A%20%20return%20textString.substring%280,%20start%29%20%2B%20newValue%20%2B%20textString.substring%28%28start%20%2B%20numberLength%29,%20textString.length%29%0A%7D%0A%0Aincrement%28%2200999%22%29&cumulative=false&curInstr=1&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D&textReferences=false)

The js function is here: https://github.com/SpeciesFileGroup/taxonworks/blob/908cdf82e5c120a8c6aa6c8a73033b0045f93fa9/app/javascript/vue/tasks/digitize/helpers/incrementIdentifier.js

**Expected behavior**

I would expect the length of the identifier to stay the same when incrementing, rather than keeping the same number of leading zeros.

If this is intended behavior, however, please close the issue.

**Comment by jlpereira** [comment]
@mjy do you remember if this was intended or not?

**Comment by mjy** [comment]
It is a real bug, number of leading zeros should not increase
