### ISSUE TITLE
CO Save and New does not copy determination

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2443]
**Describe the bug**

Locking the determination field in the comprehensive editor does not add the determinations to new records

**To Reproduce**
1. Edit a CO with a determination
2. Lock the determinations field
3. Click save and new
4. The determination is not copied to the new record

**Expected behavior**
I expect the determination(s) to be copied if the field is locked.

**Environment (please identify where you experience this bug:**
- Sandbox - sandwich

**Comment by jlpereira** [comment]
@LordFlashmeow you mean the determination list?

**Comment by LordFlashmeow** [comment]
Yes?

**Comment by jlpereira** [comment]
Currently there are only locks are for OTU and Determiner, I will add another for the list
