### ISSUE TITLE
empty `recordedById` in dwc_fields DWC Occurrence Report task

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2458]
**Describe the bug**

When there are more than one determiner and/or collector for an occurrence with no orcid, the row still shows a delimiter

**To Reproduce**
1. Have an collectionobject with a different determiner and collector, neither of whom have orcids
2. Navigate to the DWC Occurrence Report task
3. The recordedID field shows a delimiter and nothing else

![image](https://user-images.githubusercontent.com/33206210/130528590-b6f524d8-7abe-4af1-81ec-2cbf73c97b31.png)

**Expected behavior**
I expect the field to be empty if neither person has an identifier (orcid)

**Environment (please identify where you experience this bug:**
*** One of ***
- Development: dwc_fields branch, a92a0c95a32fa133f9f79e116dad9b0c3898ad0e

**Comment by mjy** [comment]
@LordFlashmeow IIRC, I'll check, but you must have ORCID ids for users who added the record.  I don't believe this is an error.  See user params.  

Steps:
* Create a Person representing you/others as a user.
* Create an ORCID identifier for that person

The value should map.

**Comment by LordFlashmeow** [comment]
What if they don't have an ORCID?

**Comment by mjy** [comment]
Then there is no ID to share, and it fails the semantics of the field.

Note that IIRC the field is not supported by DwC, it probably shouldn't be there... yet.
