### ISSUE TITLE
Task - Browse Collection Objects - new facet, search by User metadata/date range

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#246]
Same approach as #216.

* New scopes belong with user housekeeping
* Limit select box to a single user for now (`sessions_current_project.users`)
* Radio buttons toggle the field to search against
* Date fields are standard HTML selectors, nothing special! https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

<img width="507" alt="screen shot 2017-09-28 at 10 38 44 am" src="https://user-images.githubusercontent.com/22600/30976013-5656cbb6-a439-11e7-9a3b-d223ab108444.png">

**Comment by TuckerJD** [comment]
Select User by name (is there an example of user_by_name?), or by email address (as in Add Project member)?

**Comment by mjy** [comment]
Don't think there is a user by name select existing already, probably useful to make a helper in users.  Pass it an array of users, get a select.  Should be easy to do with Rails select helper as well.

` User.where("name ILIKE 'Matt%'")`.

**Comment by TuckerJD** [comment]
New class methods of User: 
* get_user_id(user) to get one specific user, requires exact match if string is used (name or email)
* get_user_ids(user, user, user, ...) to get array of Ids, uses partial string match (name or email)
