### ISSUE TITLE
As a curator, I would like to replace TaxonName verbatim author + year with saved Source

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2460]
When taxon names are created from a DwC checklist or occurrence, the source is always a verbatim author name and year. (Changing that is another issue.) 

If I have the source saved in TW, I would like a task (or section in an editor) to display a list of sources that match the verbatim author/year and a button to set it as the taxon name source.

**Comment by proceps** [comment]
duplicate of #2257
