### ISSUE TITLE
Taxon Name editor does not show active author tab on load

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2461]
**Describe the bug**

The taxon name editor always shows to the source tab on load, even if the saved data is in the verbatim tab.

**To Reproduce**
1. Have a Taxon Name in the editor
2. Add a verbatim author name and year for the source section
3. Reload the page.
4. The Source tab is open, instead of the verbatim tab (_which has a checkmark next to it!_)

**Comment by proceps** [comment]
I would prefer to keep source as a default open tab.

**Comment by proceps** [comment]
Although it could be useful to make data in all three tabs always visible (remove tab functionality)

**Comment by LordFlashmeow** [comment]
If you did, it opens up the opportunity for a "did you mean" suggestion button like I was describing in #2460

**Comment by proceps** [comment]
Please remember, in most cases, verbatim fields are comming from the export, in properly curated project, verbatim fields are not in use. I have about 95% of the names which are rendered based on source and/or people fileds.

**Comment by LordFlashmeow** [comment]
Yes, but as I understand it, every project that uses the importer (rather than inputting by hand) will be in the same position of having many verbatim sources. Moving away from verbatim fields is a process, and having a button to select the new source is much easier than typing in the verbatim value into the search bar.

A bulk tool would be ideal, but I don't think it would be hard to copy that functionality into the taxon editor.

Side note: are new projects instructed to import their sources first, so they can be added to the taxon names when the names are created?

**Comment by mjy** [comment]
Side reminder there were hotkeys on the smart selectors.

**Comment by mjy** [comment]
I agree with this issue, it should be fixed.  It should be a rule for the smart selector.  There was some past discussion of where to land on the smart-selectors. If there are data then we should open to that data, in preference of preferred data/priorities.  If there are no data then we should, feel, open to the best practice (Source).  In your case we should open to what is there, not what should be done.  Once there is Source and verbatim, then we should land on Verbatim in TaxonName (as it over-rides Source when present), etc.
