### ISSUE TITLE
As a curator, I would like to create a DwC Occurrence Report that includes custom predicates

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2464]
The DwC Occurrence Report does a great job of combining CO and CE data into a single row, suitable for import and processing by other software. However, there is no way to include custom data attributes associated with the CO and CE. 

A set of checkboxes to select which predicates are included for the CO and CE (using the `dwc_occurrences/predicates.json` endpoint to filter out unused/empty ones) would be sufficient.

**Comment by mjy** [comment]
Re-iterate that endpoint is done.

**Comment by mjy** [comment]
@LordFlashmeow this is implemented, but not strongly tested.  Close if it meets your needs at a basic leve.

**Comment by mjy** [comment]
Closing, reopen with issues.
