### ISSUE TITLE
Nomenclature statistics

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2472]
As a user, I would like to see nomenclature statistics for a specific clade: number of species described by year (valid and synonyms) and species accumulation curve by year:
![image](https://user-images.githubusercontent.com/5597748/131157481-9737b102-7f6a-4ee8-b444-d5e74d5fb4aa.png)
![image](https://user-images.githubusercontent.com/5597748/131157545-bd11cb32-873c-40ec-aefc-68320b053a2d.png)

**Comment by proceps** [comment]
Adriano recently asked me if we can do this statistics, and made it downloadable.

**Comment by JohnHeraty** [comment]
very cool.... how do I do it or is that in the works?

**Comment by proceps** [comment]
It is an open case, I did this in the past in excel, extracting the numbers outside of TW.

**Comment by proceps** [comment]
The numbers do not look right:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/f606bf22-9e01-4e9a-99f0-f01da915e3e1)
I search for all species in Auchenorrhyncha (restricted Protonyms, species rank and descendants of the suborder). And same if I do the valid name only. So I have 47,000 valid names, and 66,000 total name. But the cumulative curve show that the number of synonyms and valid name is the same. It looks like the same result is displayed for valid and invalid names. The number of taxa by year seems to be correct

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/cb3e4a24-520c-437c-9c66-36ca203520d4)

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/d640869c-621b-4e8e-8c53-656415ccd737)

**Comment by proceps** [comment]
And the total in the cumulative curve seems to be below 40,000, which is less the number of valid species

**Comment by proceps** [comment]
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/bb506f03-4f9d-429a-8f19-a8858380107e)
This may correspond to actual deficiency of the date no verbatim year, and no associated source, or a source without a year...

**Comment by proceps** [comment]
I checked my database offline, in all cases those are misspellings which do not have original publication.

**Comment by mjy** [comment]
> I checked my database offline, in all cases those are misspellings which do not have original publication.

Yes, this is exactly one of the reasons, as intended.

> But the cumulative curve show that the number of synonyms and valid name is the same.

I doubt it, mouse over the bars to get the exact values.

**Comment by mjy** [comment]
Did find one small bug, pushed.
