### ISSUE TITLE
As a developer, I would like to have my account added to new projects I create

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2476]
I often make new projects to test things out, and it would be a huge convenience to add the active account to the project at creation time. 

A checkbox on the new project screen "Add me to the project" would be perfect. Is there a limitation/design concern preventing this or can I make a PR to add it?

**Comment by mjy** [comment]
Duplicate of a recent issue IIRC, therefore yes, PR!
