### ISSUE TITLE
Date facets have mm/dd/yyyy format

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2479]
Filter facets (does not apply to data-entry inputs, see re-opened issue) should be yyyy/mm/dd

<img width="375" alt="Screen Shot 2021-08-29 at 12 26 01 PM" src="https://user-images.githubusercontent.com/22600/131259677-89e8cc54-88a2-4349-b727-ffd56f5f534c.png">

**Comment by jlpereira** [comment]
The displayed date is formatted based on the locale of the user's browser, but the result will be yyyy/mm/dd. I don't think we can change this in the native input. So we going to need to replace the input and use a date picker

**Comment by mjy** [comment]
What does it look like for your browser? @jlpereira

**Comment by jlpereira** [comment]
<img width="255" alt="Captura2" src="https://user-images.githubusercontent.com/16530364/131265360-66cc554c-a7c8-45c4-a506-84649d838d48.PNG">

dd/mm/yyyy

**Comment by mjy** [comment]
Let's leave it native.
