### ISSUE TITLE
YouTube tutorials

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2482]
I find the videos available in YouTube showing how to use TW extremely useful to help train my coworkers.
Too bad there are only two so far.
Any plans to add more???

**Comment by debpaul** [comment]
Greetings @adrik29 yes there are plans to add more. [Four were added today](https://www.youtube.com/channel/UCKNr7QYwvVFcRfQAcMEAhLw) and 5 more are done awaiting post-production editing.

**Comment by debpaul** [comment]
Closing now, please re-open if you have a related question about the YouTube tutorials.

**Comment by adrik29** [comment]
Fantastic -- started to wacth them. I'm spreading the word to see if my people watch them as well...
