### ISSUE TITLE
Task - Navigate radial - Filter task

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2488]
When I use Navigate radial and select an option for Firter task for this model (for example Filter TaxonName or Filter Source). I do not want prepopulate the Filter task with the existing data from the page I am leaving. I want to open blank filter page. Filtering of the data takes time. So every time I use the option, I have to wait for filtering results, and crear the task page after if is finished filtering. In case of Filter task, I propose to always open the blank task.

**Comment by mjy** [comment]
Strongly disagree I think.  The real solution is to cap the number of results when we launch out from here.

**Comment by mjy** [comment]
Depends on the filter you are hitting, right?

**Comment by proceps** [comment]
I believe it is always use the object_id.

**Comment by mjy** [comment]
With the new unified filters the use of sending one object to the filter, so that you can continue on to the next result is very powerful.  Leaving as is.
