### ISSUE TITLE
Task - Comprehensive digitization - Soft validation needs to nest in Collection Object section

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2491]
Not sure how to refactor, maybe top right, to converge on similar edit of Taxon names, but at minimum it's confusing ot have it in the collecting event section.

<img width="1686" alt="Screen Shot 2021-09-03 at 11 49 25 AM" src="https://user-images.githubusercontent.com/22600/132041025-14fcc67e-22d6-4867-8ba7-87bcbd3bbc80.png">

**Comment by mjy** [comment]
We may also want to split it out into at least 2 sections, one for specimen, one for collecting event.

**Comment by jlpereira** [comment]
Yep, putted there by request. I think we can put it beside Depiction, citations and attribution part. We have a lot of space for it
Btw, we're duplicating soft validations. Clicking hexagon icon should open a modal with all validations

**Comment by proceps** [comment]
I need the sv to be always visible. I do not want to click something to see it.
