### ISSUE TITLE
Loan item "select/deselect all" buttons needed

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2493]
When I am in "New/Edit Loan" task
Then I want to select a combination of loan items and edit them
Then I want to be able to unselect/select all loan items to bulk edit those items with two buttons respectively.

**Comment by mjy** [comment]
<img width="1102" alt="Screen Shot 2021-09-03 at 4 24 57 PM" src="https://user-images.githubusercontent.com/22600/132066856-ccdc0a57-b4ee-408c-a6ea-bf6cfbf40116.png">

**Comment by jlpereira** [comment]
This is already implemented, it is missing after the breakout changes in vue 3 migration
