### ISSUE TITLE
Filter - Taxon Name - without original combinations

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2496]
As a curator I want a list of all species or genus names that do not have original combination, or have missing original combination information.

**Comment by proceps** [comment]
This is just a subset of soft_validations. We should be able to show all soft_validations or sorted by method. It is much more efficient than focusing on individual issues.

**Comment by proceps** [comment]
See #72

**Comment by mabecabrera** [comment]
As a curator I need a complete list with all the results with their Taxon Names with GENUS NOT SPECIFIED or SPECIES NOT SPECIFIED. Not only the truncated one Browse Nomenclature's search gives me. Is it the same as @mjy is asking for?

**Comment by proceps** [comment]
Use the task "Filter nomenclature" and in the name field type "SPECIFIED". Filter, and get the list of all names.

**Comment by LocoDelAssembly** [comment]
That doesn't work, should list several hundred names. Problem is that the filter is not taking into account incomplete or missing original combinations.
![image](https://user-images.githubusercontent.com/4991925/154687700-8fa0adca-f167-4382-9b2e-373c51e72212.png)

**Comment by proceps** [comment]
Yes, this will not work here. The question was about "GENUS NOT SPECIFIED". But for missing oriignal combinaiton, we need an index on soft validations.

**Comment by proceps** [comment]
related to #2546
