### ISSUE TITLE
LepIndex - Original genus not pulled through for valid names

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#25]
For valid names the original genus is not being picked up i.e. where original genus != current genus e.g. for “Anthela adriana” validation states “original genus is not selected”.  For the Bombycoidea it only affects 71 records but for the wider recordset it actually affects 50,000 records. For invalid names it has picked up the original genus successfully.

**Comment by proceps** [comment]
There was a bug in the code which restricted finding original genera only if it is valid name.
