### ISSUE TITLE
docker-compose build/up fails with migration error

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#250]
```
  when I follow the instructions on using docker-compose
      and I have never run the process before
          then when I try to visit the web endpoint
             I get a server-side error re migrations 
            "127.0.0.1/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)"
```

(Thanks Lisa)

**Comment by lisasroughdrafts** [comment]
![screen shot 2017-10-05 at 11 12 44 am](https://user-images.githubusercontent.com/5199181/31235699-2632c156-a9c0-11e7-8b1a-4102740b79bf.png)

This was the message displayed in my browser window, in case it helps.

**Comment by devarsh1997** [comment]
@lisasroughdrafts, even I have faced this error. @jlpereira and @mjy helped me tackle this problem on native installation. To solve this:

-  Access Shell of your Docker app (as outlined in [here](https://github.com/SpeciesFileGroup/install_taxonworks/blob/master/development/docker/README.md))
-  Kill server (using CTRL + C)
-  Try following instructions in that shell (I'm assuming it is normal unix bash) :
     ```
      rake db:drop
      rake db:create && rake db:schema:load && rake db:test:prepare
      rake db:migrate
     ```
-  If you're not seeing any errors. Exit from the shell.
-  Now going through the [docker quick-start](https://github.com/SpeciesFileGroup/install_taxonworks/tree/master/development/docker#development-quick-start) process will probably work.

**Comment by devarsh1997** [comment]
@lisasroughdrafts, please don't try my solution. It does not work. I have patched docker files for installation and updated instructions for [Docker installation](https://github.com/SpeciesFileGroup/install_taxonworks/blob/master/development/docker/README.md) to guide through the process.

Feel free to re-open this issue if Docker installation still does not work for you.

**Comment by mjy** [comment]
@devarsh1997 I'm going to add some pseudo-code as comments `docker_compose_start.sh` to outline the expected behaviour.

**Comment by mjy** [comment]
Problem for me was a bad database.yml file.  Closing for #279.
