### ISSUE TITLE
Increase contrast in headers [was: color schema is not good]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2505]
Please make title and labels darker. They look like grayed out.

![image](https://user-images.githubusercontent.com/5597748/132542541-bc32efd7-62e7-4cc2-9e13-c7d82f81da69.png)

**Comment by jlpereira** [comment]
@proceps Something is wrong there, I think it is inheriting CSS properties.

Where did you see this?

**Comment by proceps** [comment]
This is in OTU radial, but I think it is also in other radial. It looks like the CSS (or inheritence) changed recently.
this is the same from sandstorm:
![image](https://user-images.githubusercontent.com/5597748/132568982-0e81d643-4e0d-435e-bbb4-d3778dcd0c67.png)

**Comment by jlpereira** [comment]
Fixed
