### ISSUE TITLE
Model - Geographic area - alternative values

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2506]
As a user, I need alternative values on geographic area. In some critical areas I would like to create alternative spelling, because it is difficult to find some areas based on the gazeteer name.

**Comment by proceps** [comment]
I need this for work, a student working on Asserted distribution could not find a proper geographic names because of alternative spellings. It would be easier for me to add alternative spellings on several areas, which I know are always problematic.

**Comment by debpaul** [comment]
Hm. 
- If money were no object, I wonder if ISO standards for transliterations would be useful here. 
- OR instead we could ping wikidata, as there are wikidata records that amass name variants for a place. Example for "[Moscow](https://www.wikidata.org/wiki/Q649)."

@proceps what was the name of the place in question? (to check wikidata)?

**Comment by proceps** [comment]
I have many places in question, and I would preffer manually add alternative values.

**Comment by proceps** [comment]
Ability to add alternative values on geographic areas would be a fast and efficient soultion in majority of the cases. More complicated solutions like wikidata could be left for future. I need a simple solution to allow students to populate historical distribution records. Otherwise it is getting back to me every time, because they cannot find a record on the list. I do not have a list of problematic names, but names like  Formosa = Taiwan, Ceyloy = Sri Lanka are obvious candidates for alternative spellings.

**Comment by mjy** [comment]
Perhaps there is a simpler, more educative approach that requires nothing from anyone as the "quickest" solution

Teach your lab to use WIkidata to resolve the names? See:

<img width="772" alt="Screen Shot 2022-08-08 at 12 58 52 PM" src="https://user-images.githubusercontent.com/22600/183483204-f3373036-60c6-48b5-8a4e-84944f4807b8.png">

**Comment by debpaul** [comment]
> Perhaps there is a simpler, more educative approach that requires nothing from anyone as the "quickest" solution
> 
> Teach your lab to use WIkidata to resolve the names? +100 @mjy 

@proceps they'll learn to hunt wikidata easily and quickly and they then can a) appreciate that someone's already done this work (no need to do it again) and b) maybe some of them even contribute.

**Comment by proceps** [comment]
Lets start with the fact that I never used wikidata myself. I know it could be useful, but wikipedia answers 99.9% of my questions.
Second: I do not have a single person who I can teach and this person keep working. The hourly people change constantly all the time and I have to do the same teaching ower and over again. 
Third: my goal is to make work done fast and efficiently. Yes, I know that each job have to be educational, but at the same time, working with student, I realized that they are already overwelmed with information on lectures, and in many cases, they just prefer to get the work done with bare minimum information, and minimal use of external sources of information. 
How for example, I can teach each student, that by convertion of TW "Dominican Republic" is recorded in TW as "Dominican Rep." and if 'Dominican Republic' is copied from the source and pasted into the search field, TW can find an area, but without shape file? How Wikidata could help me with this?
Why I can provide an alternative spelling for the person, and not for geographic area?
Yes I know about the learning curve, but why should not we try to make some things easier?
Why I should wait a sophisticated solution with wikidata, if some simple solution could be done today?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/183497597-6b563935-a970-4b27-a2db-048991ba1a79.png)
Exactly, I would like to see the same interface in TW. Yes wiki, could be educational, but eventually, I still do not know what spelling variant is used in TW, and I manually have to try those one by one.
One example from wikidata, which people like to reference. Please try to find a correct geographic are in TW for "Italy: Sardinia". You would need to try every spelling to find a correct one.
![image](https://user-images.githubusercontent.com/5597748/183498110-24ff08e5-f81e-4e26-9571-89e91e5dad88.png)

**Comment by proceps** [comment]
could we please prioritize this issue?
