### ISSUE TITLE
Change text line in the interface

### ISSUE THREAD

**Issue by yroskov** [SpeciesFileGroup/taxonworks#2510]
Doing CoLDP export, I came to the step of narrowing OTU selection. Phrase, next to a tick-box, says: On taxon name with multiple OTUs conflict narrow selection to unlabelled ones.

![image](https://user-images.githubusercontent.com/28574252/132750228-f2aae03a-d40b-4648-96cb-8e90e42c880d.png)

Simple phrase, something like "**Do single OTU export**", will make my user's life easier.

**Comment by LocoDelAssembly** [comment]
Well, text might not be clear, but actual behavior is to favor unlabelled OTUs when a taxon name has more than one. 

Not sure if you mean you want ANOTHER option to export ONLY that OTU without taking children taxa into account?

**Comment by yroskov** [comment]
I meant, that phrase is not simple and may confuse users

**Comment by LocoDelAssembly** [comment]
We need to think of something else then, "Do single OTU export" not quite explain what the checkbox does and also could lead to think you will download ONLY selected OTU.

The checkbox should explain (hopefully easier than current text) what the following code does:
```ruby
 # @return [Otu#id, nil, false]
  #  nil - there is no OTU parent with a valid taxon name possible
  #  false - there is > 1 OTU parent with a valid taxon name possible
  #  id - the (unambiguous) id of the nearest parent OTU attached to a valid taoxn name
  #
  #  Note this is used CoLDP export. Do not change without considerations there.
  def parent_otu_id(skip_ranks: [], prefer_unlabelled_otus: false)
    return nil if taxon_name_id.nil?

    # TODO: Unify to a single query

    candidates = TaxonName.joins(:otus, :descendant_hierarchies)
      .that_is_valid
      .where.not(id: taxon_name_id)
      .where(taxon_name_hierarchies: {descendant_id: taxon_name_id})
      .where.not(rank_class: skip_ranks)
      .order('taxon_name_hierarchies.generations')
      .limit(1)
      .pluck(:id)

    if candidates.size == 1
      otus = Otu.where(taxon_name_id: candidates.first).to_a
      otus.select! { |o| o.name.nil? } if prefer_unlabelled_otus && otus.size > 1 # <<<<< [CHECKBOX]

      if otus.size == 1
        return otus.first.id
      elsif otus.size > 1
        return false
      else
        return nil
      end
    else
      return nil
    end
  end
```

**Comment by yroskov** [comment]
OK. Any clear phrase will be OK.
