### ISSUE TITLE
download formatted references from filter sources not working

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#2512]
Even for one reference the wheel keeps on spinning....

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**
Do a simple search for one reference: 113767 | Heraty, J.M., Mbanyana, N. & Van Noort, S. (2020) A new species of Eucharissa  Westwood (Eucharitidae) from South Africa, with an evaluation of the  importance of pupae for assessing relationships in these ant  parasitoids. Journal of Hymenoptera Research 79, 43–55. https://doi.org/10.3897/jhr.79.56042
-- | --

Tried to download a formatted reference using either zookeys or zootaxa format (using Firefox) > no result

**Screenshots**

<img width="1021" alt="Screen Shot 2021-09-09 at 9 19 25 PM" src="https://user-images.githubusercontent.com/30123556/132799167-71ebf8d6-04c0-47cb-bc12-9f997a3d2b9f.png">

**Comment by JohnHeraty** [comment]
it does work for Acta Amazonica...

**Comment by JohnHeraty** [comment]
works now - it may be because one of the references was verbatim - when fixed it worked.

**Comment by mjy** [comment]
@jlpereira seems like there might be an edge case to handle both in the back end and the UI here.  Let's test with response that only returns verbatim.
