### ISSUE TITLE
Task - new collecting event - Soft validation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2519]
The soft validation is not upated once the georeference and/or geographic area is added, even after I press Save button.
For some reason, the georeferences show "2", although I have only one georeference. Before I created the georeference, it showed "1" (whene there were non). Is it because the label has verbatim fields? I do not expect as those be treated as a georeference.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/133148215-5c30837b-2ad7-44d0-bce9-d173e4baa338.png)

**Comment by jlpereira** [comment]
I can't replicate it the soft validation issue. Georefrence warning dissapear after save. 
After test it, i think you're getting 2 records, because it's counting the geographic area shape like a georeference record. I have to fix this

**Comment by proceps** [comment]
I tested this in sandbox before. In production the sv disappears after save. Still have 2 records for georeference.
Minor unrelated, would be nice to have an `Edit` button from Browse collecting event to this task.

**Comment by jlpereira** [comment]
![browse](https://user-images.githubusercontent.com/16530364/133163605-722e1661-cc95-4872-aede-ac229c55bc16.png)

I think it's already there

**Comment by proceps** [comment]
Aha, I did not even look there, I was looking for green button in the same place where we have radial. It would be nice to unify.
