### ISSUE TITLE
Source::Bibtex - resolve difference between `cached` and bibtex CSL rendering

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2521]
At present `cached` is csl rendered (according to Zootaxa, but that will change) but hacked to include other values.  While other values are nice, this confuses people because what they see as the citation is not what they get when a bibliography is rendered.

* [ ] Explicitly provide a CSL preview in task new source as the default view that is unmodified.
* [ ] Determine why the hacked version of cached is necessary, it breaks expectations.  Proposal: remove all hacked elements and improve Source autocomplete to include the hacked elements (e.g. language, notes).  This solves the common case of finding the value, while preserving expectations of what gets exported.

**Comment by proceps** [comment]
There is no single citation style which would include all important fields from BibTex. We definitely need an extended version. See also comment to #2517.

**Comment by mjy** [comment]
This issue is to resolve exactly what you point out in other issue, separating bibliography view from cached view.

**Comment by proceps** [comment]
Please, try to preserve, all "hacks"

**Comment by mjy** [comment]
> Please, try to preserve, all "hacks"
That is the purvue of `taxonworks.csl`, if we can't do it there then we can come back to updating `source_tag`, which can be a wrapper around that CSL that includes other data.

**Comment by proceps** [comment]
this is resolved with taxonworks.csl
