### ISSUE TITLE
DwcOccurrence indexing referencing CEs with only large GeoAreas as georeference slow

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2526]
Probably related to calculating a centroid.  Repeatable by creating a CE with geographic area "United States".  Potential solution is to skip centroids unless polygon is a certain area, or by proxy something like calculate for counties only.

**Comment by LocoDelAssembly** [comment]
Is the centroid calculation done on Postgres-side? Would a computed index be possible?

**Comment by LocoDelAssembly** [comment]
Requires querying with pretty much the same SQL code used for the index to get Postgres to notice. I have a complicated index in https://github.com/SpeciesFileGroup/taxonworks/blob/2b1b5e47921b9e2b18691c8d2a40e62a102d2a79/db/migrate/20210406125820_create_dataset_record_fields.rb#L27 that requires to use exact same params for substr to make the index usable (besides also including import_dataset_id, encoded_dataset_record_type, position in `where`).

The index you have I'm not quite sure why you need GIST? Are you querying with the centroid as a conditional or you actually want the centroid *value* back and you are querying by another criteria?

**Comment by mjy** [comment]
This: I want the centroid value back given other criteria, e.g. id.

**Comment by mjy** [comment]
Closing as resolved unless further details come up.  WKT read/write is much improved in the indexing cycle.
