### ISSUE TITLE
Source and metdata JSON updates [Was: Smart selector - Sources - slow response]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2531]
<strike>Using smart selector for the source is chelenging. It takes about 10-20 seconds to render Quick and Recent list. I believe it is either json or front end issue. The method is very fast. By that time, I can find the source using the search box. Very often, by the time I selected the source and ready to submit the citation, the list is formed and the form is reoranged. The submit button moves down. And, insted of clicking on submit button, I click on an item on a newly generated list, and I have to start searching again. There are several issues to addres:
* [ ] the search response should be optimized to get results within 1-2 sec.
 * [ ] the items in the list are hardly distinguished from a selected item. Proposed change: trim the size of each line to 50-70 characters (to fit one line). On mouse over, display entire string.</strike> 
 
Core speed issues resolved here, along with many other basic response changes. See #2539 for styling.

**Comment by mjy** [comment]
General changes  to metadata (e.g. `/otu/123.json`)
* [ ] object response no longer include `origin_citation` by default, use `&extend[]=origin_citation`
* [ ] object responses no longer include `pinboard_Item` by default, use `&extend[]=pinboard_item`
* [ ] object responses where `&extend[]=origin_citation` only include sources/_base_attributes for the source not extended metadata

Changes to `/sources`
* [ ] reponse no longer includes author/editor_roles, use `&extend[]=roles` to include both
* [ ] author/editor roles no longer include extended metadtata for people, only base_attributes
* [ ] response no onger includes `documents` by default, use `&extend[]=documents`
* [ ] `/sources/select_options` now only includes base attributes, not metadata (may break smart selectors)

**Comment by mjy** [comment]
* [ ] Roles labels not showing people: 
<img width="696" alt="Screen Shot 2021-09-21 at 4 14 36 PM" src="https://user-images.githubusercontent.com/22600/134248843-47d6cb10-4e92-4a19-8db1-31ae70bd382b.png">

**Comment by mjy** [comment]
* [ ] Geographic area extends with `level_names, geo_json, geographic_area_type, parent`

**Comment by mjy** [comment]
* [ ] Biological associations extends with `triple_metadata`, `family_names`, `citations`

**Comment by mjy** [comment]
* [ ] Citations extends with `citation_object`, `citation_topics`, `source`, `target_document`

**Comment by mjy** [comment]
* [] AssertedDistribution extends with `otu`, `geographic_area`, uses metadata for each rather than attributes
