### ISSUE TITLE
Some geographic areas do not add appropriate stateProvince to DWC index

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2542]
**Describe the bug**
I select a geographic area of a state Province, e.g. "Colorado", but when I go to index (even after it updates), the stateProvince is not listed.

**To Reproduce**
1. When I  select a geographic area (e.g. TDWG Level 3 Colorado)
2. Then I go to Browse CO
3. And I look at DWC Index
4. Then the state is not there

Selected Geographic area:
![image](https://user-images.githubusercontent.com/11411328/135128444-1c7c319c-0b49-42b9-ba40-3800c7f34913.png)

Missing stateProvince:
![image](https://user-images.githubusercontent.com/11411328/135128532-99ead7bd-049f-416d-916d-ed49311ef373.png)

**Expected behavior**
Should see stateProvince in DWC export

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by tmcelrath** [comment]
Not sure what geographic areas this affects.

**Comment by tmcelrath** [comment]
At least affects TDWG Level 3 Colorado and Missouri Geographic areas.

**Comment by proceps** [comment]
See #1433 (this is applicable to asserted distributions and collecting events)
