### ISSUE TITLE
Model - Protonym #original_combination_elements returns inconsistent values

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2547]
E.g. `{:genus=>[nil, "Euchiradia"]} ` vs.  `{:subgenus=>[nil, "(Heringijana)"], :genus=>"[GENUS NOT SPECIFIED]"} `

**Comment by proceps** [comment]
this is a correct result if original genus not set.

**Comment by mjy** [comment]
I changed nothing but unified the format.  Needs specs if so.
