### ISSUE TITLE
/tasks/gis/report has execution error.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#255]
Last week, the sandbox issues emails for an execution error when entering /tasks/gis/report.  This error has been corrected on the current development branch. There were two separate issues, one on first paint, and the second as a result of the show.

Even though the show now selects objects properly, the paging links on the /tasks/gis/location_report_list page do not operate properly.

**Comment by TuckerJD** [comment]
It turns out that the process of presenting the page selected from the pagination links works, but the spinner (middle box-spinner mx-spinner)? is never hidden, and thus never uncovers the resulting text.  This behavior is consistent with what happens with the pagination available on the results page for /tasks/collection_objects/filter/find.

**Comment by jlpereira** [comment]
Jim, what is the branch where you're doing this?

**Comment by TuckerJD** [comment]
This was fixed on development.
