### ISSUE TITLE
Task - Comprehensive - identifier error message

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2550]
When I open an existing collecting event with an identifier, I have this error message
![image](https://user-images.githubusercontent.com/5597748/135496653-d615a5fd-59f1-4d82-8a34-74b0d5e26723.png)

**Comment by mjy** [comment]
Easiest fix, perhaps, is to state 'Identifier already exists, and won't be (re)saved.'  We need just identifier.cached, not object tag in the highlight as well I think.

**Comment by mjy** [comment]
Blocked by extend/embed branch.

**Comment by mjy** [comment]
@jlpereira we might be able to tackle this, unsure?

**Comment by jlpereira** [comment]
Yes, I think. We need to check if the existing identifier is the same loaded to avoid display the message
