### ISSUE TITLE
Feedback after testing DwC Download (file naming, data workflow notes, some data observations)

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2561]
**Describe the bug**

Testing the DwC Download via sandbox.taxonworks.org using INHS Insect Collection Data.

![image](https://user-images.githubusercontent.com/2990155/136065964-f28e1238-2375-459a-a3d5-b36cd79c5d90.png)

**Steps to test**
1. In sandbox.taxonworks.org > INHS Insect Collection > Collection Objects Filter > Illinois (no shape) > Search = 8575 records
2. Clicked "Download DwC"  and then "All" in the DwC Dashboard (see screenshot next)

![image](https://user-images.githubusercontent.com/2990155/136066090-779e576d-a18f-4f2b-8d7a-c0080c30c458.png)

3. Filenames need to change (I believe) to expected values (data.csv to occurrence.txt, for example, **see sample screenshot) to work with current aggregator workflows.**

![image](https://user-images.githubusercontent.com/2990155/136066451-76e6d6d1-ae51-420b-a2d2-23096684b9a5.png)

4. Tab-separated data is fine, but will take explaining.  On a PC, double-click to open file in Excel using a PC results in data that has no separator.

5. IF I open in Excel using "Import from Text" and I specify the encoding as UTF-8 (called **file origin** in Excel) then all is well. IF I let Excel use the "file origin" from my download it defaults to **1252: Western European** and of course, messes up the characters.

**Some Data Observations**

1. why no dwc:coordinateUncertaintyInMeters?
2. No metadata for georeferences? (Who did them, for example)?
3. **dwc:eventTime field, many records have a dash "-" in this field,** with no other information. 
I can't tell if this is intentional, or maybe an artifact in TW of tabbing through the fields?

4. Could map dwc:verbatimLocality to dwc:locality too -- IF verbatim is supplied and dwc:locality is not (in TaxonWorks).

**Environment for testing**
- sandbox.taxonworks.org / INHS Insect Collection
- Firefox

**Comment by mjy** [comment]
All great points, some I feel we can do something about in TW, others are completely valid, but don't require changes.

>Filenames need to change (I believe) to expected values (data.csv to occurrence.txt, for example, see sample screenshot) to work with current aggregator workflows.

Filename is defined in meta.xml, as per the spec it can be anything.
```
    <files>
      <location>data.csv</location>
    </files>
```

> Tab-separated data is fine, but will take explaining. On a PC, double-click to open file in Excel using a PC results in data that has no separator.

Not a TW issue, but rather basic data literacy.  Trying to use commas in this type of data is maddness.

> IF I open in Excel using "Import from Text" and I specify the encoding as UTF-8 (called file origin in Excel) then all is well. IF I let Excel use the "file origin" from my download it defaults to 1252: Western European and of course, messes up the characters.

Also not TW, but rather basic data literacy.

> why no dwc:coordinateUncertaintyInMeters?

Only provided when assertable.  For example, centroids based on the US have no uncertainty, verbatim data may also not have it.  The check here is to see that a) the method is supplied (may have a bug), and b) the corresponding (lack) of data makes sense.

> No metadata for georeferences? (Who did them, for example)?

Will check, pointing to specific IDs will help.  In some cases we can't know.

> dwc:eventTime field, many records have a dash "-" in this field, with no other information.

Bug! Almost certainly.

> Could map dwc:verbatimLocality to dwc:locality too -- IF verbatim is supplied and dwc:locality is not (in TaxonWorks).

On it.
