### ISSUE TITLE
Copy pasting into verbatim year with alphanumeric gives error even though numeric are all that are visible

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2577]
**Describe the bug**
When I paste alphanumeric text into "verbatim Year" in New Taxon Name (e.g. Mannerheim, 1843), even though all that shows up is the numeric, I still get an error saying it must be a numeric value. 

**To Reproduce**
1. When I  copy alphanumeric text (e.g. Mannerheim, 1843)
2. Then I paste it into "verbatim year"
3. And I try to save
4. See error saying it must be numeral
![image](https://user-images.githubusercontent.com/11411328/137174559-136a2280-6c76-4789-83da-4ca29a8b30cc.png)

5. If I erase all text and just type the numbers it is fine. 

**Expected behavior**
Should not error. 
- Production
- Chrome

**Comment by mjy** [comment]
The error is a back-end validation.  I suspect the input is showing one thing, and sending all.  Could be confirmed by looking at the POST in network tab.
