### ISSUE TITLE
Task - New combination - Button Change parent

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2578]
When the rank of combination is different from the current rank of protony, changing the parent, should also set the rank of protonym

**Comment by mjy** [comment]
@proceps please provide example to clarify.  There is no parent for the Combination, it's auto-calculated, so is the button broken?

**Comment by proceps** [comment]
That could be tricky, it definitely need testing after implementation. But in general, we have several scenarious:
Genus
Genus (Subgenus)
Genus species
Genus (Subgenus) species
Genus species subspecies

Basically have have to find the lowerest rank of the new combination and assign this rank to the lowerest rank protonym in combination. We should also take into account the code of nomenclature.

**Comment by mjy** [comment]
I feel this should be a boolean/option in the UI and be triggered in the model, not the UI.

**Comment by mjy** [comment]
@proceps we need unit tests on Combination, and a virtual attribute to trigger the effect on update of Combination.

**Comment by proceps** [comment]
We trigger all the changes on the interface (controller??) level, not in the model.

**Comment by mjy** [comment]
I also am starting to wonder why we want to change ranks, it feels like this is edging into the world of "change", not "add", and is meeting the needs of @proceps approach to keep things unified under one name, rather than unify our understanding in the view.

**Comment by mjy** [comment]
> We trigger all the changes on the interface (controller??) level, not in the model.

Complex rules for updating ranks should happen in the model, not logic in the controller.

**Comment by mjy** [comment]
To clarify:
* User triggers update by clicking button
* We pass param `update_ranks=true` on button
* Combination model adds `attr_accesor :update_ranks`
* Combination model adds something like `  after_save :update_ranks, if: -> { update_ranks }
* `def update_ranks` does the work of updating, according to the logic

**Comment by proceps** [comment]
Update rank should work only when update parrent is triggered. And probably always when parent is updated (well, only if the rank need to be changed).
If most of the user find new combination interface in Edit TaxonName task as more useful, we may not need this extra logic in the new combination task.

**Comment by mjy** [comment]
> Update rank should work only when update parrent is triggered.

Understood. This  `We pass param update_ranks=true to the controller` would only happen when that happens.

**Comment by mjy** [comment]
Is this really a bug then?  Or a feature?
