### ISSUE TITLE
Observation matrix - coding characters - moving "Description (generated)" and similar outputs to bottom of page

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2582]
As a user, I am currently using the observation matrix tools to manage projects, so each column represents progress on a certain type of data. 

For this use, in the model for coding characters, Description (generated), Diagnosis (generated), and Similar objects aren't informative; in the case of Similar objects, since the goal is for all the rows to be coded the same when the project is complete,  having a large block of text to scroll past to get to the character coding is a bit of a nuisance.

Would it be possible to put these in boxes that can be dragged to the bottom or rearranged, similar to how various fields can be moved in Browse OTU?

**Comment by mjy** [comment]
I completely agree- this is not the place for previewing data, those should be hidden and modal as required.  This task is the basic coding interface.

**Comment by mjy** [comment]
Why can't we just fix a bar to the top of matrix row coder, that floats on top of the scroll.  And add a "preview" button that shows the data.  You could link it to a hotkey, and toggle it super fast, or just make it clickable?

**Comment by kandakoj** [comment]
Hopefully I wasn't implying that the summary data in the row coder is completely useless; I did like it for coding morph characters, just not for project management. @proceps hide button (with saved user preference) is exactly what I would want. 

I know there are other ways to track progress like tags and such, and maybe using the matrix model isn't the best (or appropriate) approach, but it seemed the best way to get quick overview of progress on a single project right now.

**Comment by mjy** [comment]
Closing, the top bar solve many issues.  Open new with single specifics.
