### ISSUE TITLE
Task - comprehensive - type material

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2584]
One specimen could serve as a type of two differenent species, but the task does not allow selection of a second taxon name.

**Comment by mjy** [comment]
I see I think.  You mean we need to reload the page, but select a specimen that is already created, correct?  Can that edge case be handled in Comprehensive?

**Comment by proceps** [comment]
For objective synonyms and coordinate names you do not want to create a separate type specimen. Yes, it should be visible in Comprehensive. At the moment, the type specimen is created, if the species is marked as an objective synonym (using SV fix). But there is no verification, you cannot see two type records.
