### ISSUE TITLE
Task - New Descriptor - Clicking update takes me back to the matrix hub automatically

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2594]
When I go from the hub to new descriptor.  And I click update after the Descriptor is created, then I go to the Hub automatically, some problem with redirects.

**Comment by proceps** [comment]
we have 2 buttons "Update" and "Update and return to matrix"
We need additional button "Update and New" which saves the existing descriptor, and clear the form for a new entry (both previous and a new descriptor should be automatically linked to the matrix).
