### ISSUE TITLE
DwC dashboard - if possible remove params from URL

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2599]
When I click on the DwC download button (e.g. from the CO filter), then the URL bar has it's params set, and when I reload the page by accident, then I fire another download creation.

Perhaps we will need to isolate the index call (likely) from the build/create call, that would make things cleaner?

**Comment by jlpereira** [comment]
@LordFlashmeow I can't replicate this, maybe you reach this in an old branch?

**Comment by mjy** [comment]
Closing as stale, @LordFlashmeow please reopen if necessary.
