### ISSUE TITLE
LepIndex - Infrasubspecific names with wrong authorship

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#26]
The valid name as shown under relationships is displaying the authorship of the *name of record* and not the *senior name*. Examples:

(1)	“scheidenbaueri Gschwandner 1924” is an invalid name with the senior name as “Deilephila elpenor Linnaeus 1758”. In TW it shows the senior name as “Deilephila elpenor elpenor Gschwandner, 1924”.

(2)	“costimaculata Bang-Haas 1938” is an invalid name with the senior name as “Marumba quercus [Denis & Schiffermüller] 1775”. In TW it shows the senior name as “Marumba quercus Bang-Haas, 1938”.

There are over 6,000 infrasubspecies names in the full dataset.

**Comment by proceps** [comment]
This is view interface issue, data in the database are correct
