### ISSUE TITLE
Task - Source - soft_validation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2611]
Hide the block when no errors found
![image](https://user-images.githubusercontent.com/5597748/139519728-6138c7c3-2daf-42b2-a6d2-c1cf39f7d66f.png)

**Comment by jlpereira** [comment]
That's strange, it shouldn't be there if is empty. Link?

**Comment by proceps** [comment]
It is true for all sources. For example.
https://sfg.taxonworks.org/tasks/sources/new_source?source_id=12509
