### ISSUE TITLE
"Wrong" country/stateProvince calculated for darwincore for specific Collecting Event

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2614]
**Describe the bug**
For this CE: https://sfg.taxonworks.org/tasks/collecting_events/browse?collecting_event_id=226311 - the country/stateProvince are incorrectly calculated as "Mexico/Tamaulipas" when they should be United States/Texas. The Georeference is right on the border so perhaps there is some issue there?

![image](https://user-images.githubusercontent.com/11411328/139695574-9767bee8-171b-491a-9e62-84b6c360131d.png)

- Production
- Chrome

**Comment by mjy** [comment]
I feel we need to define a fixed priority to resolve this class of questions.  Once that is place we can code what is preferred and exported. I do not want to export conflicting data.  So, the question is, what is the priority for dwc fields.

We should list each field, then list possible ways it is filled, then order their priority.

**Comment by lvhart2** [comment]
I am having the same issue with the wrong stateProvince displaying for a number of CE's. 
<img width="1440" alt="Screen Shot 2022-01-19 at 11 12 43 AM" src="https://user-images.githubusercontent.com/75492546/150181040-c2da7b75-b5ef-4adc-97eb-ff406354feff.png">
stateProvince should be Illinois, but TW is changing it to Indiana, as you can see on the right hand side when I search for it. Same wrong info is included when exported. I even deleted the georeference to see if that may be the issue but it won't change to the correct state. 

Any updates on this? Thanks.
-Lily Hart

**Comment by lvhart2** [comment]
I forgot to add that I also checked that the correct **Wabash Co.** in IL is selected for Geographic area.

**Comment by redewalt** [comment]
This is a public forum, so my thoughts are coming by email!

**Comment by lvhart2** [comment]
IL, Crawford Co., Wabash River, Hutsonville
<img width="1440" alt="Screen Shot 2022-09-27 at 4 35 03 PM" src="https://user-images.githubusercontent.com/75492546/192640604-009bc00f-6cb2-47e2-9228-85c8dbe98f26.png">

As you can see in the upper right hand corner, "Indiana" shows up for this locality when searching, even though it is in fact Illinois. 

A similar result for the following locations:

Tower Rock, IL- shows as KY
Ohio Co., Markland, IN- shows as KY
Mt. Carmel on Wabash River- shows as IN
Cave in Rock, IL- shows as IN
Golconda, IL-shows as KY
Ft. Madison, IA- shows as IL

**Comment by mjy** [comment]
@lvhart2 I've been working on this today.  It would be helpful if you posted the IDs of the offending colleting events..  I think I have it working for the first couple of cases, but could use more tests.

**Comment by lvhart2** [comment]
@mjy Here's my list of Ed's (and his former student's) tripcodes for these collecting events:

Hutsonville on Wabash River
RED-2019-044
RED-2020-018
RED-2020-036
RED-2020-057
RED-2020-113

Tower Rock, IL
EAN-2019-057
EAN-2019-069

Ohio River, Markland Dam
EAN-2020-116

Mt. Carmel on Wabash River
RED-2019-049
RED-2019-050
RED-2020-019

Cave In Rock, IL
RED-2019-051
RED-2019-052

Golconda, IL
EAN-2021-010

Ft. Madison, IA seems to be fixed. One ID for that location is EAN-2021-004.

Thanks! Hope that helps.

**Comment by mjy** [comment]
@lvhart2 thanks!  Sorry, I should have describe more accurately what I meant by the id (so many different identifiers!).  These will all help just fine though! See the id I was referencing:

<img width="1192" alt="Screen Shot 2022-09-28 at 11 06 47 AM" src="https://user-images.githubusercontent.com/22600/192830703-b87ffbee-4c86-4c9b-a8c8-e97acb43cdd1.png">

> Ft. Madison, IA seems to be fixed. One ID for that location is EAN-2021-004
Weird, nothing has changed, yet.  Could be a reflection of the bad code that is currently in place being non-deterministic.

**Comment by lvhart2** [comment]
@mjy Oh! I haven't clicked Development View before.. I learn something new every day!
