### ISSUE TITLE
Software versioning

### ISSUE THREAD

**Issue by yroskov** [SpeciesFileGroup/taxonworks#262]
As a user/tester/developer I need to see a version of the software and date of its release (not a deployment date) in my interface (for example, in sandbox interface), for example, "ver. 2342 of 15Oct2017". I need to be sure which version I am testing and which version have a bug to be reported.

**Comment by mjy** [comment]
Hi @yroskov.  Thanks!  And thanks for your first issue, and thanks for closing an issue! :)

I think you saw what we have on the sandbox?

<img width="619" alt="screen shot 2017-10-17 at 1 55 41 pm" src="https://user-images.githubusercontent.com/22600/31683576-f8f259d6-b342-11e7-99aa-4ee00ca1bc23.png">
