### ISSUE TITLE
COs with verbatim Coordinates do not export decimalLatitude and decimalLongitude to DWCA export table

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2624]
**Describe the bug**
If there is a specimen with a verbatim coordinates, then the coords are only exported to verbatimLatitude and verbatimLongitude, not decimalLatitude and decimalLongitude

**To Reproduce**
1. When I have a specimen with verbatim decimal Lat/Long
2. Then I save it after adding a verbatimGeoreference and error
3. And I go look at DWC export
4. Do not see in decimalLatitude and decimalLongitude

https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=1310597
![image](https://user-images.githubusercontent.com/11411328/140553409-3d765c8c-7da5-4bb6-a40f-3275257dcfbb.png)
![image](https://user-images.githubusercontent.com/11411328/140553430-dfabe731-98ad-4d0b-890f-819374161787.png)

**Expected behavior**
Should also be in decimalLat/decimalLong

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by proceps** [comment]
We do not have decimalLat/Long in the model. We have verbatim fields, and a georeference (which is the equivalent of decimal values). So we should be eble to export decimal if georeference exists.

**Comment by tmcelrath** [comment]
You have decimalLatitude and decimalLongitude exported though. That's what I'm referencing.

**Comment by tmcelrath** [comment]
E.g. in DWC report at bottom of Browse Collection Object: 
![image](https://user-images.githubusercontent.com/11411328/140562832-758138a6-a51b-46ba-b582-4a0a26cae628.png)

**Comment by proceps** [comment]
Collection object did not have a georeference. I created one. See it now:
![image](https://user-images.githubusercontent.com/5597748/140563734-6861f177-e7dc-4384-a0dc-f9f9f6f7c651.png)
