### ISSUE TITLE
Task - OTU radial - asserted distribution - citations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2629]
There are 2 issues with the OTU radial
1. If I open Asserted distribution, I have a citation button, but when I click it, a blank modal is opened (the citations are missing).
2. If I close OTU radial and try to open it again, it does not, unless I reload the page.
3. Please also add a tooltip to the citation button.
![image](https://user-images.githubusercontent.com/5597748/140770654-13ebb748-9482-43b9-a2b2-a64560714566.png)

**Comment by mjy** [comment]
@jlpereira probably `extend` issue.
