### ISSUE TITLE
Task - OTU radial - Biological associations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2630]
Biological association sector does not work at all. I cannot select a relationship
The error message. This blocks our abilities to edit data.
![image](https://user-images.githubusercontent.com/5597748/140773547-71047b8d-64a9-45c2-8b19-3030e8939c9f.png)

**Comment by proceps** [comment]
Also, once I have the modal open on Biological association, it would not close with Esc or `X` button

**Comment by jlpereira** [comment]
Probably a `extend` issue. Looking
