### ISSUE TITLE
Task - Edit TaxonName - Clone from source button (for authors based on people) is disabled.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2631]
![image](https://user-images.githubusercontent.com/5597748/140774658-ab813003-6c6c-49fa-845f-22f85f49dd82.png)

**Comment by mjy** [comment]
Could also be &extend issue.

**Comment by jlpereira** [comment]
I can't replicate this, are you sure authors are people and not verbatim?

**Comment by proceps** [comment]
seams to works in development, but not in production...
sometimes it woks, but sometimes I have this error
![image](https://user-images.githubusercontent.com/5597748/140815699-43715275-212c-49ef-a9ae-63c1e9d157f8.png)

**Comment by mjy** [comment]
@proceps 404 happens when you have changed projects but didn't refresh the page.  Is that maybe what happened?

**Comment by proceps** [comment]
I was experimenting with the page. When you create a new name, the Authors options were not available, before reloading the page. I also tried to delete and create people record, and at some point I saw those errors. Not sure exactly what triggered it. When I tried to delete people, there was a great delay, I may reload the page before it completed or something.
But definitely not changing the project.

**Comment by mjy** [comment]
Possibly stale now with new version.

**Comment by proceps** [comment]
Still an issue. When I create the new taxon, the button is not visible. Only after the page reload
![image](https://user-images.githubusercontent.com/5597748/141341582-bacf4254-6e17-4d21-92d9-fba6e8b829aa.png)

**Comment by mjy** [comment]
Is the record saved?

**Comment by proceps** [comment]
yes, after creating new records, and adding original source

**Comment by jlpereira** [comment]
I can't replicate it. I need more info.
This is on local or production? Which is the source selected? Can you take a look at the browse console to see if you're getting errors?

**Comment by proceps** [comment]
I added 5-6 taxa in production, and it failed for me each time.
My steps: 
* created new source from DOI. Add authors as people and save.
* Pin the source
* I have Browse or Edit nomenclature task open in different tab. So I either switch to Edit mode or select a New taxon.
* Enter the name and parent and save (TN is created)
* Go to Author and use the Pin button to add the source.
* Add page number
* Go to People section and it is blank.

I just replicated this in one of the sandboxes and got the following Errors:
```/tasks/nomenclature/…on_name_id=330331:1 Uncaught (in promise) Object
new_taxon_name:1 Autofocus processing was blocked because a document already has a focused element.
runtime-core.esm-bundler.js:8358 TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.isAlreadyClone (AuthorPeople.vue:62)
    at e.value (reactivity.esm-bundler.js:250)
    at e.get (reactivity.esm-bundler.js:1531)
    at Object.get [as isAlreadyClone] (runtime-core.esm-bundler.js:2729)
    at Proxy.render (AuthorPeople.vue:15)
    at Pt (runtime-core.esm-bundler.js:630)
    at e.fn (runtime-core.esm-bundler.js:5310)
    at e.value (reactivity.esm-bundler.js:250)
    at Ji (runtime-core.esm-bundler.js:8265)
    at wr (runtime-core.esm-bundler.js:8563)
er @ runtime-core.esm-bundler.js:8358
Xi @ runtime-core.esm-bundler.js:8331
Pt @ runtime-core.esm-bundler.js:659
(anonymous) @ runtime-core.esm-bundler.js:5310
value @ reactivity.esm-bundler.js:250
Ji @ runtime-core.esm-bundler.js:8265
wr @ runtime-core.esm-bundler.js:8563
Promise.then (async)
br @ runtime-core.esm-bundler.js:8421
gr @ runtime-core.esm-bundler.js:8445
vr @ runtime-core.esm-bundler.js:8449
(anonymous) @ runtime-core.esm-bundler.js:8799
U @ reactivity.esm-bundler.js:526
R @ reactivity.esm-bundler.js:478
(anonymous) @ reactivity.esm-bundler.js:676
(anonymous) @ updateSource.js:17
Promise.then (async)
(anonymous) @ updateSource.js:15
(anonymous) @ updateSource.js:5
(anonymous) @ vuex.esm-browser.js:315
B.dispatch @ vuex.esm-browser.js:1052
dispatch @ vuex.esm-browser.js:932
triggerSave @ AuthorSource.vue:146
Ji @ runtime-core.esm-bundler.js:8265
Ki @ runtime-core.esm-bundler.js:8275
Nt @ runtime-core.esm-bundler.js:394
updatePages @ citationPages.vue:34
Object.onBlur.t.<computed>.t.<computed> @ citationPages.vue:7
Ji @ runtime-core.esm-bundler.js:8265
Ki @ runtime-core.esm-bundler.js:8275
e @ runtime-dom.esm-bundler.js:447
```

**Comment by mjy** [comment]
> created new source from DOI. Add authors as people and save.

Are you sure people were created and saved?  I suspect this might be the problem in part?

**Comment by proceps** [comment]
Yes, I am, I create people for each source record. Besides, when in Edit TN mode, if I reload the page, the functionality is restored.
Apparently there is something in exact staps. Because if instead of using pinned source, I select a filter to find the source, the tasks works as expected.

**Comment by proceps** [comment]
Besides, the people section is completely blank, not even the search textbox is present to select the authors manually.

**Comment by jlpereira** [comment]
What DOI are you using?

**Comment by jlpereira** [comment]
Nevermind, found it. It's a extend issue with the pages autosave.
