### ISSUE TITLE
Filter Collection Objects - Filter by Individual Loan and generate DWCA/CSV

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2632]
As a curator, I want to go to Filter COs
Then I want to search for the collection objects currently loaned on a SPECIFIC LOAN
Then I want to be able to generate a CSV or DWCA of the objects on that loan to be sent to loanee

**Comment by mjy** [comment]
@jlpereira new facet.  Param is `loan_id[]=`

**Comment by tmcelrath** [comment]
Request reopen, not working in 0.21.2

**Comment by tmcelrath** [comment]
Currently returns list of all records in project (Production, INHS Insect Collection)
