### ISSUE TITLE
Task - Edit Taxon Name - Original source - Navigation radial

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2633]
When I am in the Edit TN mode, and I have a source, selecting Navigation radial for source generates e-mail error. When I use the same radial in Browse nomenclature or Edit Source interface, it seams to work properly
<img width="853" alt="Screen Shot 2021-11-08 at 2 58 38 PM" src="https://user-images.githubusercontent.com/5597748/140817609-6a3b183a-b57c-4ee2-aa7d-9e32fda813a7.png">

**Comment by jlpereira** [comment]
@mjy source object doesn't have global_id in origin_citation
