### ISSUE TITLE
Use of OTUs in loan

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2648]
**Describe the bug**

I need to be able to enter the same OTU more than once. I also need to be able to differentiate between alcohol and pinned specimens
For example I have 49 Buprestidae in Alcohol and 20 Buprestidae pinned. I need to be able to indicate this on the loan form. Currently I can only put 69 Buprestidae

**Comment by mjy** [comment]
@mmkohler thanks!

There are several ways of doing what you want I think:

First solution, create 2 OTUs representing what you want to loan, "Buprestidae (Pinned)", and "Buprestidae (Alchohol)".  You can put a total on each.

Second solution. Create Lots, with the requisite totals and preparation type, and loan those.

Would either of these work for you?

**Comment by tmcelrath** [comment]
Hey Matt -  both of those solutions seem clunky to me. I think a better solution would be to allow loan items to specify prep types. E.g. 49 Buprestidae Pinned and 345 Buprestidae vials. 

As a short term solution we will merge them into one number and specify in the notes field how many of each there are, but we will need to do this better in the future.

**Comment by mjy** [comment]
Why won't Lots work?

Spreading properties that already exist to multiple places means managing the concept multiple places.  I think the Lot is the way to go.

**Comment by tmcelrath** [comment]
I'm honestly not even sure where that goes in TW? Is it a CO? A separate data class? I don't see a data class for lots.

**Comment by mjy** [comment]
Sorry for confusion. A Lot is what we call a CollectionObject with total > 1.

Comprehensive colleciton object 
* Prep type alchohol
* Total 49
* Determination - OTU "Buprestidae"

Repeat.

There is much bonus, and no(?) downside here.  You've added totals to the collecitions (partial digitization).  You've linked two things to the same OTU, etc.

**Comment by tmcelrath** [comment]
Main problem I see is duplication and confusion regarding what that thing "is" in TW. I'm assigning multiple COs to one CO? They are even containerized differently. That makes no sense semantically IMO. Does the Lot then get a GUID? Does that GUID then get sent out and used? DO I delete it when the specimens come back? 

It's a weird shortcut that borrows from the ideas of CO and "typical" lots. 

We used to do this in the INHS Filemaker database and I really disliked it b/c it conflated two ideas into one "solution" into the database, which were then very confusing to external users. E.g. they would see one of our "loan lots" and think we had a single collection object with 100s-1000s of specimens and be very confused.

**Comment by mjy** [comment]
I did not mean to containerize them virtually.  I meant to create 2
records. The thing is very well defined.  In TaxonWorks we auto-classify
things enumerated > 1 as 'Lot'.  It means the curator has counted a certain
number of specimens, and wants to "do work" with those specimens (e.g. Loan
them).  All specimens in the Lot get the same properties (determination,
preparation type).

Yes, you have identified a problem with GUIDs, but at least you have one to
reference if the specimens never come back.  The particular problem "what
to do with the GUID" isn't special to this case.

There are thousands of "Lot" records in INHS, I have heard no concerns with
their use so far, so to be honest I'm confused as to the issues here.

**Comment by tmcelrath** [comment]
Table for next discussion time. I think we might be talking past each other here.
