### ISSUE TITLE
Task - edit TaxonName - subsequent combination - subgenus

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2654]
When I have a genus and a subsequent combination is recorded as a subgenus, the combination is displayed twice.
![image](https://user-images.githubusercontent.com/5597748/141670026-e99c6458-f900-43e9-ba4c-52fa6e870198.png)

**Comment by jlpereira** [comment]
@mjy I can handle this from my side, but maybe we should fix the response for this. It's sending two times the same object
Project: i3 project
ID of duplicate object: 422866
link: http://localhost:3000/taxon_names.json?combination_taxon_name_id[]=359319

![Captura de pantalla de 2021-11-14 12-02-30](https://user-images.githubusercontent.com/16530364/141686620-2c54d0dd-761c-48f8-9c09-17ebf5a42ce5.png)
