### ISSUE TITLE
As a developer I want a images endpoint that returns *all* images referenced via OTU

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2656]
Param `:otu_scope`
* `:all` (default, includes all below)
* [x] Depicting OTU `:otu`
* [x] Observations via OTU `:otu_observations`
* [x] Observations via CollectionObjects currently determined as `:collection_object_observations`
* [x] Collection Objects currently determined as OTU `:collection_objects`
* [x] Coordinate OTUs `:coordinate_otus`
* [x] Specimens currently determined as Coordinate OTUs `:coordinate_collection_objects`
* [x] Observations on Specimens currently determined as Coordiate OTUs `:coordinage_collection_object_observations`

Potentially interesting
* [ ] Content on OTUs
* [ ] Depictions of related CollectingEvents

**Comment by proceps** [comment]
Please add depictions through the observations.

**Comment by mjy** [comment]
@proceps already done.  The only thing possibly missing AFAIKT is depictions through Content.

**Comment by proceps** [comment]
Ok, Thanks!
