### ISSUE TITLE
Task - Edit Source - source authocomplete textbox

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2659]
there is strange behavior ocasinally happening in the Source autocomplete box.
I start typing the string, it starts firing searches for a portion of the string, but ocasionally, when I start typing, it does not search for a string any more, but searching for a single (first) letter instead. It is upredicted. It does not happens every signle time.
![image](https://user-images.githubusercontent.com/5597748/141863314-e360aaa3-310d-4ad5-bb15-e2a5834f18e4.png)

**Comment by proceps** [comment]
I can delete or add a letter to fire a normal search.

**Comment by mjy** [comment]
@proceps maybe keep your console open and look for javascript or response errors?

**Comment by proceps** [comment]
I do not see any errors. Not sure if this is a browser behavior or the code. When I start typing, the search seams to work fine for existing fragment of the word, and I can see the results of the search. But sometimes (not always), when I stop tiping, although I have more than one word in the search box, I have the search defaulted to the first letter of the phrase. I will post more, if I could make it reliably replicated.

**Comment by jlpereira** [comment]
I have a vague idea of ​​what it could be, maybe the previous call is not canceled and returns the results of the previous search

**Comment by proceps** [comment]
I saw this in other interfaces as well (TaxonName for example). But for some reason, it was more pronounced when searching sources.

**Comment by mjy** [comment]
> I have a vague idea of ​​what it could be, maybe the previous call is not canceled and returns the results of the previous search 

Are we using a standard autocomplete library for this?  Waaaay back in jquery land we resolved this and everything also felt way snappier.

**Comment by debpaul** [comment]
@proceps is this still happening? I can't find any hits using <paramesus> at all.

**Comment by proceps** [comment]
this is not specific issue, and not easy to replicate. Not sure if this still exists. I will watch for a while. The exact string search is not important. The exampl shows that even when a string entered to the search box, the search is performed based on a single first letter only.
 Duplicates may exist, but we do not have a mechanism to unify sources yet (there is a separate open issue).

**Comment by mjy** [comment]
Closing as outdated
