### ISSUE TITLE
Heterotypic synonyms are getting flagged with the :sv_missing_otu soft validation

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#2664]
**Describe the bug**

For botantical data, heterotypic synonyms are getting flagged with the `:sv_missing_otu` issue, which seems incorrect although I could also be doing something wrong with the importer rake task. It's not a blocker because I'm temporarily excluding `:sv_missing_otu` when running the soft validation fixes and the importer task already sets up OTUs correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/8573609/142023632-fa59d895-5ce2-445d-b12d-3df964df3d1b.png)

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native : 83939fea72655c6e9ee7c443d861b612713006e8)
- Browser Firefox 93.0

**Comment by mjy** [comment]
I'm not sure I agree with this soft validation.   What if people only want to manage nomenclature sensu TW, without any reference to OTUs?

**Comment by gdower** [comment]
Hmm, that's a good point. Let me see how it affects the CoL data package exporter. I think it will probably add the synonyms as accepted names if they are given OTUs. In the CoL data model, the synonym distribution data would be moved to the accepted name, although I could certainly understand wanting to keep the distribution data for synonyms separate for research purposes especially with different species concepts.

**Comment by gdower** [comment]
Synonyms with OTUs don't get exported as accepted taxa by the CoL data package exporter which was my main concern, and I can still set synonyms to not have OTUs with the soft_validate `except_methods: [:sv_missing_otu]` parameter.
