### ISSUE TITLE
[Bug]: Darwin Core Export does not include catalog numbers for containerized specimens

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2666]
### Steps to reproduce the bug

```bash
1. Create a DWCA with DWCA Export that has containerized specimens
2. Look at the DWCA.
3. No Catalog numbers are exported
...
```

### Screenshot

Specimens when exported:
![image](https://user-images.githubusercontent.com/11411328/142439745-08060767-cfd7-4a33-9342-b616c2e8226e.png)

Specimen in TW
![image](https://user-images.githubusercontent.com/11411328/142439827-c2ed9783-831a-41b3-b389-7ed8d8dedd2e.png)

### Expected behavior

Should export catalog numbers

### Environment

- [ ] Development_native
- [ ] Development_docker
- [ ] Sandbox
- [X] Production
- [ ] Browser (e.g. chrome, firefox, safari)

### Browser Used

Chrome

**Comment by mjy** [comment]
@tmcelrath can you test in sandboxes, I believe this is already resolved.
