### ISSUE TITLE
Task - Otu radial - contents - Edit content

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2676]
When I select an existing content for editing, it is available only in a reduced form:
![image](https://user-images.githubusercontent.com/5597748/142973209-bc90b1e4-fc7d-4a08-bf43-5744263c3463.png)

**Comment by mjy** [comment]
@proceps what do you mean, reduced form?

**Comment by proceps** [comment]
do you see `...` in the picture, there shold be a full paragraph of text after it, which is not available for editing.

**Comment by jlpereira** [comment]
@proceps can you upload a full screenshot of the page to look this more in context

**Comment by proceps** [comment]
save long paragraph of a text
![image](https://user-images.githubusercontent.com/5597748/143080534-1930e0d9-52f0-4762-bc8a-15da44c6ddbe.png)
Once it is saved, use edit button
![image](https://user-images.githubusercontent.com/5597748/143080655-e290b077-f909-4142-b2bf-c9c9795d4d24.png)
the paraph but in truncated form is available for editing
![image](https://user-images.githubusercontent.com/5597748/143080740-44344af2-5938-419c-95bf-48b4760c656f.png)
