### ISSUE TITLE
[Feature]: Print catalog numbers (& associated QR codes) free from New Collecting Event interface

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2679]
### Your role

Collection manager

### Your needs

Printable QR codes not associated w/ collecting event

### Audience question

How can I print lots of QR code catalog numbers all at once?

### Audience

Taxonomist, collection manager

### Napkin sketch

In the print label task
As a collection manager I want an area to create and print catalog numbers
I want these catalog numbers to not be printable again, but no CO created.
I want the options for customization already in the New CE task

I want to be able to create 1000s-10000s at once and then print them .

### Data

Namespace and Catalog Number/Identifier

**Comment by tmcelrath** [comment]
This is complete, right @mjy ?

**Comment by mjy** [comment]
If it works, then it is :)

**Comment by tmcelrath** [comment]
Pretty sure it works.
