### ISSUE TITLE
Task - Update Dockerfile to remove migration errors

### ISSUE THREAD

**Issue by devarsh1997** [SpeciesFileGroup/taxonworks#268]
- In Docker and native installations, migration related issues arise during installation and testing TaxonWorks.
- Update the Dockerfile so that migration error does not occur when testing Docker version of TaxonWorks for the first time after installing.

**Comment by devarsh1997** [comment]
Migration error is resolved in patched version of docker_compose_start.sh.

**Comment by mjy** [comment]
Duplicate of #250
