### ISSUE TITLE
Task [Admin] - As an administrator I want a quick and dirty batch load of users.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2680]

**Comment by debpaul** [comment]
Hi @mjy First try with the Batch Load New Users on workshop.taxonworks.org. I get
![image](https://user-images.githubusercontent.com/2990155/143929358-3098607b-8990-47c3-bdfa-048a128d550c.png)

I'm guessing the helper text that says 
`<name, email>`

doesn't need the space?

I'm trying without the space now.

**Comment by debpaul** [comment]
Nope, no joy with space removed. 

List I am trying to add is here

Jamie Smith,jamie.smith@naturalsciences.org
Austin Hendy,ahendy@nhm.org
Luc Willemse,luc.willemse@naturalis.nl
Claude Nozères,claudenozeres@gmail.com
David G. Robinson,david.g.robinaon@usda.gov
Paloma Shimabukuro,palomahfs@gmail.com
Mary Ann Feist,mfeist@wisc.edu
Emily L Sandall,sandall.emily@gmail.com
Torsten Dikow,DikowT@si.edu
Lauren Raz,lraz@unal.edu.co
Daniela Maeda Takiya,takiya@gmail.com
Doris Lagos-Kutz,doris.lagos-kutz@usda.gov
Eugenio Valderrama,e.valderrama.e@gmail.com
Judicaël Fomekong Lontchi,judicaelfomekong@gmail.com
Mostafa,msc.ghafouri@gmail.com
Jon Fong,jfong@calacademy.org
James C. Sagebiel,sagebiel@austin.utexas.edu
Thembile Khoza,T.Khoza@sanbi.org.za
Danielle Uchitelle,danielle.uchitelle@gallerysystems.com
Blair Ramon,Blairnramon@gmail.com
Rouba Al Aseer,Widelight2016@gmail.com
Marina Ascunce,ascunce@ufl.edu
Nilver Zenteno ,nilverjzenteno@gmail.com
Boaz Shacham,boazshacham@mail.huji.ac.il
Carla Novoa Sepúlveda,novoa.spulveda@gmail.com
Adelaide Ephraim Sallema,adelaide5mon@yahoo.co.uk
Siobhan Leachman,siobhan.leachman@gmail.com
Ben Norton,ben.norton@naturalsciences.org
Greg Whitbread,whitbread.greg@gmail.com
Beckett Sterner,bsterne1@asu.edu
Maximiliano Fero Meñe,maxisogosote@gmail.com
Rodrigo de Vilhena Perez Dios,rodrigodios@gmail.com
Mark Fishbein,mark.fishbein@okstate.edu
Adela Roa-Varon,Roa-VaronA@si.edu
Tricia Goulding,tc.goulding@gmail.com
Eric H. Metzler,metzlereh@si.edu
Rachel King,Rachel.king2@my.jcu.edu.au
Manuel Lujan,m.lujan@kew.org
Burcin,cingayburcin@gmail.com
Carlos Martínez,archilegt@gmail.com
Eve Lucas,e.lucas@kew.org
Ed Baker,edwbaker@gmail.com
Jason Bengtson,j.bengtsonunm@gmail.com
