### ISSUE TITLE
Radial Annotator - Add 'Verification' section.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2683]
Includes the standard role picker we use elsewhere.  Creates the Verifier Role between the annotated object and the Person.

@jlpereira on 2285_georeference_metadata_updates.

**Comment by jlpereira** [comment]
This is a new slice? and for what kind of objects? Georeferences?

**Comment by proceps** [comment]
I would suggest to make it part of Confidence section.

**Comment by mjy** [comment]
New slice.  All objects.  I'm working out the refactor to permit it on the georeference branch.

**Comment by mjy** [comment]
> I would suggest to make it part of Confidence section.

I thought about that.  It's conceptually different enough in meaning and code that I don't want to mix the two.  Remember we auto-create a lot of the annotation UI etc.  Merging would be a headache.
