### ISSUE TITLE
Task - New Descriptor - Clarify matrix inclusion autocomplete in a proper section

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2685]
It is not immediately clear what the 'Matrix: [autocomplete]' is intended for. Move the autocomplete to its own green-bar section at the bottom of the form.  Add flavour text (italics) indicating this is optional.

<img width="1669" alt="Screen Shot 2021-11-28 at 11 00 22 AM" src="https://user-images.githubusercontent.com/22600/143778247-736a7d18-5f88-47f2-ab29-fe1e41d34ef9.png">

**Comment by proceps** [comment]
selecting a matrix to associate descriptor with?

**Comment by mjy** [comment]
Confused. Are the suggestions I'm making making it less clear?

**Comment by proceps** [comment]
I never generate descriptors outside the matrix scope. When I come from the matrix, I have matrix selected for me:
![image](https://user-images.githubusercontent.com/5597748/143783466-3bf9e246-b1f2-4304-bd5c-ac6fe1ea8514.png)
And it seems to be properly in place.

**Comment by mjy** [comment]
I frequently create descriptors outside of a matrix context where I a) don't care about placing it in the matrix currently, or b) want to choose the matrix in a more intuitive spot.  That is, when I enter New descriptor as a task card, then I am confused about "matrix: []".  I just want to place it in a clearer place.
