### ISSUE TITLE
Task - Obseration Matrix Dashboard - Cannot select matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2696]
in production

![image](https://user-images.githubusercontent.com/5597748/144460347-791ccc87-c0d2-461c-8b77-37fbf29e74a3.png)

**Comment by proceps** [comment]
Same problem if I use OTU radial to select an observation matrix
![image](https://user-images.githubusercontent.com/5597748/144461498-1143aeba-1d7a-4259-8137-e8992d207c88.png)

**Comment by LocoDelAssembly** [comment]
Probably related: https://github.com/SpeciesFileGroup/taxonworks/commit/fb546dc73103b537749a54336380dbc28096fa6d#r61251352
