### ISSUE TITLE
[Bug]: Status 500 error using Task Author by first letter

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2697]
### Steps to reproduce the bug

```bash
1.Select Task: Author by first letter
2.I chose letter "V"
3.I see the "Loading" gif but no results
4.I do see (greyed out at the bottom) "Status 500" "Internal Service Error"
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/144460263-a4956fde-7690-495e-bd9c-850e30ab4882.png)

### Expected behavior

I expect a list of author names

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandbox

### Version

 SANDBOX - build 89f7b1cb8 on 2021-12-01T14:08:52Z

### Browser Used

firefox

**Comment by LocoDelAssembly** [comment]
Guess the following error comes from here then:
```
An ActionView::Template::Error occurred in people#index:

  undefined method `source_author_path' for #<ActionView::Base:0x00000000117a60>
Did you mean?  source_tags_path
               source_notes_path
  app/views/shared/data/all/_metadata.json.jbuilder:6


-------------------------------
Github link:
-------------------------------

  https://github.com/SpeciesFileGroup/taxonworks/blob/89f7b1cb8/app/views/shared/data/all/_metadata.json.jbuilder#L6
```
