### ISSUE TITLE
[Bug]: Status 500 Uniquify people

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2698]
### Steps to reproduce the bug

```bash
1.Search "Orrell" in Uniquify People task, returned 4 hits
2.Selected person to keep and checked boxes for the other 3 be merged
3.Clicked merge
4.Seems to have worked but also saw the Status 500 error msg box
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/144469322-724bd573-629f-4f8a-ac49-91e78e81dfb3.png)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandbox

### Version

SANDBOX - build 89f7b1cb8 on 2021-12-01T14:08:52Z

### Browser Used

firefox

**Comment by debpaul** [comment]
Re-testing. I no longer get the Status 500 message. So I think we can close this ticket.
NOTE: _I'm not sure I'm getting the expected objects count after merge._ (Will need to test further). 
See logs (I merged several instances of Dmitry Dmitriev). I think this would be a new ticket, yes? @mjy @jlpereira

**Comment by mjy** [comment]
Yes, new ticket.  Remember that new names can (and do) come in at any time, requiring merges.
