### ISSUE TITLE
Erroneous genera sitting under ‘Lepidoptera’ in the taxonomic hierarchy

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#27]
Under ‘Lepidoptera’ there 39 genera which should not be there. Looking at the original data I can’t see any obvious data issues that explains this. If it’s just a few we can correct manually but potentially for the full dataset it could produce many more. Is it possible to track down where there were generated from? 

![taxonworks_hierachy](https://cloud.githubusercontent.com/assets/22223106/18688461/6fed38a4-7f7c-11e6-83ad-f873f04cf756.jpg)
[TaxonWorks_Hierachy.xlsx](https://github.com/SpeciesFileGroup/taxonworks/files/483577/TaxonWorks_Hierachy.xlsx)

**Comment by proceps** [comment]
Bug in the coded resulted in duplicate names in the proper position and under Lepidoptera for some of the taxa
