### ISSUE TITLE
Task - Edit taxon name - lock or check box `for also create OTU`

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#270]
```
when I visit the edit taxon name page
    then I should see an 'also create OTU' checkbox
      and when I save the name
         then an OTU is created
  then for already saved names
     I see some indication as to whether an OTU exists for that name
```

**Comment by proceps** [comment]
I would propose different action. When you want to pick an OTU which does not exist, create it on demand, In any form which touches OTU.

**Comment by proceps** [comment]
I think this is already implemented

**Comment by mjy** [comment]
Where is it implemented?  Do you mean via the OTU navigator icon?


M

**Comment by proceps** [comment]
OTU radial changes the color when you click it, if OTU did not exist before.

**Comment by mjy** [comment]
Exactly- if that is good enough for you that's great.
