### ISSUE TITLE
[Bug]: Identifier field missing in Task: Transcribe depiction

### ISSUE THREAD

**Issue by juliah3** [SpeciesFileGroup/taxonworks#2700]
### Steps to reproduce the bug

```bash
Previously, in the Task: Transcribe depiction window, there were fields to populate an identifier id.  We would type in our unique collection IDs from the images.

Now, there is no field in that space to type in.
```

### Screenshot

Previously it looked like this (image from last year)
![image](https://user-images.githubusercontent.com/76214527/144662028-f28e10a9-47af-4e8f-a2f0-023567478603.png)

Now, it looks like this
![image](https://user-images.githubusercontent.com/76214527/144662117-ad42a60a-d2a2-4a45-9c09-c2bbe1cfa774.png)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Sandbox Used

(not entirely sure which environment.  Project UNH Insects.)

### Version

v0.22.2

### Browser Used

Chrome

**Comment by mjy** [comment]
Thanks @juliah3, I think I know the problem.  This will be fixed today or tomorrow.  In the time being you can use the radial annotator to add the identifier (local: CatalogNumber).
