### ISSUE TITLE
[Bug]: New Asserted Distribution by Map not working

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#2702]
### Steps to reproduce the bug

```bash
1. Go to ../tasks/asserted_distributions/new_from_map/new
2. Add OTU
3. Add source
4. Click on map

The behaviour that I am seeing is that a ghost of the TaxonWorks logo flashes up briefly, below the source field, but quickly disappears. No other information appears.
```

### Expected behavior

I would expect that a pin of the clicked locality would appear on the map, and a choice provided to select the coordinates generated, or a broader (possibly named) locality. 

### Environment

- [X] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

### Browser Used

firefox

**Comment by sdjbrown** [comment]
Following up: this task performs as expected when using the sandbox. I believe that the problem is that in my local instance I haven't created any geographic areas yet.

So now the question is, how does one create geographic areas in TaxonWorks? I'm looking around, but the way to do it hasn't yet revealed itself to me.

**Comment by mjy** [comment]
Welcome @sdjbrown.  Contact me in Gitter?  We have have GeographicAreas as a initialization that I can tell you about.  You can not create them in the interface.

**Comment by mjy** [comment]
Closing as related to absence of initialization dat.
