### ISSUE TITLE
[Bug]: Can't select parent in taxon name relationship picker to set incertae sedis

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2704]
### Steps to reproduce the bug

```bash
1. Create taxon with rank Family
2. Create taxon with rank Genus
3. Type in parent name in Relationship textbox
4. Autocomplete does not show parent taxon
```

### Expected behavior

Autocomplete in the relationship picker is limited to names in the same rank group. As a result, you can't select the parent as the object for the TaxonNameRelationship.

See code:
https://github.com/SpeciesFileGroup/taxonworks/blob/255ad27fa673c7f5b19a3c4ef81d676dcfd68e25/app/javascript/vue/tasks/nomenclature/new_taxon_name/components/relationshipPicker.vue#L21-L31

### Environment

- [X] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

### Version

9202a9

**Comment by LordFlashmeow** [comment]
Ok, further poking revealed that you set _incertae sedis_ from the Classification section, not Relationship.

Maybe add a message to the help overlay that says this?

**Comment by proceps** [comment]
There are many special TN relationships which are not set up using Relationship section. In general, the relationship section is designed for the taxa at the same hierarchical level (genus-group, species-group, family-group). All other relationships are set using different sections: Type, Original combination, Subsequent combination, Classification.
