### ISSUE TITLE
Task - Interactive key - Character order selector

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2707]
When I select the first (blank) option, The key is not loading. By default, when I enter the interactive key, nothing is selected, I would expect the same behavior, when I select the blank option.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/144931572-ffe546c1-02da-4057-92de-f3e56ba1b727.png)

**Comment by mjy** [comment]
Blanks should never have behaviour, they are the option to not choose anything or trigger any effect.  If you want a reset then we should include a "Reset" option

**Comment by proceps** [comment]
When I enter to the interactive key, this parameter is not used by default. When I click to blank, some value is sent to the controller
