### ISSUE TITLE
Task - Observation Matrix Dashboard - OTU is already in matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2708]
When I select an OTU in the Dashboard and click the button to add this OTU to a matrix. When This OTU is already in one or several matrices, those matrices were previously highlighted on the top of the list with Blue. This behaviour is lost now.
![image](https://user-images.githubusercontent.com/5597748/144932513-9d8d7871-b477-4c57-8b0c-0e12b7554bdd.png)

**Comment by proceps** [comment]
It is even worse, the matrices, where OTU is used are not in the list any more.

**Comment by proceps** [comment]
Please check also OTU radial interface, it has the same matrix selector.

**Comment by jlpereira** [comment]
I can't replicate this. Did you test it on development branch?

**Comment by proceps** [comment]
in the production. 3i database. In the dashboard search for: 'Scaphytopius abbreviatus'
The species should be in two matrices: Scaphytopius matrix, and Illustrations matrix. Both matrices are visible in the matrix hub, but not visible when the species is selected in the dashboard.

**Comment by jlpereira** [comment]
I see the issue, `https://sfg.taxonworks.org/observation_matrices.json` response is limited to 25 records, I will add `per` param to the request. 100 records max would be fine for you @proceps ?

**Comment by proceps** [comment]
Yes (for now) :) Well, if the OTU in a matrix, it should always be visible. The other matrices, prefferably I want to see all of them, or paginated. But definitely the search box should return a result, now even the search box is useless.
