### ISSUE TITLE
Task - Comprehensive - entry point

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2709]
When I enter a new species and (Edit TN task) and use a hyperlink to enter the type specimen (Comprehensive), the Comprehensive tasks opens for me at the very bottom of the page. I would like to see the top of the page on entry

**Comment by mjy** [comment]
I believe we explicitly set it this way to indicate to the user that the Type section was filled.  I personally would like to keep it that way?

**Comment by proceps** [comment]
This is very contrintuitive. In my experience, more often, I forget to put a repository, not the type (because it is going right after identification (in my view, I moved type next to identification section). Besides, the workflow, after finishing the form and saving includes going back to taxon name to check if all validation messages are cleared. Present implementation only requiresm scrolling form back and force.

**Comment by mjy** [comment]
OK.  Not sure I agree, but....  To me, I want to see that the where I came from is the starting point of where I ended up.  After that I do the work.

**Comment by proceps** [comment]
Do you know ANY website that suggest starting the form filling from the bottom? Unless it is only one relevant part of the form.

**Comment by proceps** [comment]
If this is important, than the type selection should be at the top of the page.

**Comment by mjy** [comment]
That doesn't follow at all.  It is important *when you come to set the type specimen". not for a majority of specimens.

**Comment by mjy** [comment]
Im not saying your idea isn't valid.  I'm saying it's presently he said/she said.  We add this on request.

**Comment by proceps** [comment]
Yes, exactly, when I come to entry the type specimen, I would like to follow the same workflow, as majority of the specimens.

**Comment by jlpereira** [comment]
From the user perspective. If I came from a place clicking a link that I know what it's going to do, I don't need to see if the system already set it when I get there. I prefer to focus filling the other information.

**Comment by mjy** [comment]
Here is a compromise:  Write a functional test to ensure that the record is set when we transition from task to task.  When that is in place we can be more assured that the assumptions of the user (my field is set even though I didn't see it, because I learned that's the way it works) are less likely to be wrong because we break those assumptions in code.  

When it is in place we can display the task as requested here.

**Comment by proceps** [comment]
The taxon_name is always set for the type but the type_type have to be selected manually.

**Comment by jlpereira** [comment]
Then it should be fine to put the view on that section

**Comment by proceps** [comment]
I would prefer to start from the top of the page, and have an error message that the type is not completely set up. Otherwise, it is a lot of scrolling on the page. Even if I set up the type (the bottom of the page), I still have to scroll to the top, to start specimen entry, and I have to finish to the bottom (finish determination and collecting event).
