### ISSUE TITLE
descriptors update (ActiveRecord::RecordNotDestroyed) "Failed to destroy the record"

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2713]
An ActiveRecord::RecordNotDestroyed occurred in descriptors#update:

  Failed to destroy the record
  app/controllers/descriptors_controller.rb:62:in `block in update'

-------------------------------
Github link:
-------------------------------

  https://github.com/SpeciesFileGroup/taxonworks/blob/6da13f6e5/app/controllers/descriptors_controller.rb#L62

I'm unsure what happens here. Does the frontend supply the complete desired database state (scoped to one descriptor) and not just what needs to be updated, created or deleted?

**Comment by proceps** [comment]
Not sure either, it looks like somebody tried to delete a descriptor on a sandbox. But that descriptor has several char_states and numerous obseravtion. It should not be deletable. May be just the error have to be handled more nicely?

**Comment by LocoDelAssembly** [comment]
This was an `update` call to the model, but apparently the params carry an array of nested attributes and I guess ActiveRecord tries to delete those related records that are no longer present in the supplied array. I'm a bit worried that the frontend might have a bigger responsibility than in should and shouldn't manipulate relationships so directly?

Since this is a sandbox I'll assume it is safe to publish the params:
```ruby
{
    "descriptor" => {
                               "name" => "Body form",
                         "short_name" => "Body form",
                        "description" => "{proportion between length and width}",
                       "default_unit" => nil,
                               "type" => "Descriptor::Qualitative",
                           "position" => 9874,
                   "description_name" => "Body form",
                           "key_name" => "Body form",
                             "weight" => nil,
               "gene_attribute_logic" => nil,
        "character_states_attributes" => [
            [0] {
                              "id" => 878,
                            "name" => "slender, length more than 5 times maximum width",
                "description_name" => "slender",
                        "key_name" => "slender",
                           "label" => "0",
                   "descriptor_id" => 923,
                        "position" => 1
            },
            [1] {
                              "id" => 1979,
                            "name" => "moderate, length between 2 to 4 times maximum width",
                "description_name" => "moderate or robust",
                        "key_name" => "moderate or robust",
                           "label" => "1",
                   "descriptor_id" => 923,
                        "position" => 2
            },
            [2] {
                              "id" => 3253,
                            "name" => "robust, lenght less than or equal to two times maximum width",
                "description_name" => nil,
                        "key_name" => nil,
                           "label" => "2",
                   "descriptor_id" => 923,
                        "position" => 3,
                        "_destroy" => true
            }
        ]
    },
    "controller" => "descriptors",
        "action" => "update",
            "id" => "923",
        "format" => "json"
}
```

Looking at this prettier representation of the params I see last one is marked to be destroyed (while at the same time all the fields values are also provided).

**Comment by LocoDelAssembly** [comment]
Fix was for something else. Reopening.

**Comment by mjy** [comment]
Solved by catching raise, might be missing something in related models, particularly before/after, but nothing obvious hit.  Apparently this is expected behaviour if you have dependent => destroy => despendent => destroy (restrict with error) chains.
