### ISSUE TITLE
[Bug]: Menu options broken when right-click on matrices in Observation matrix hub

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#2716]
### Steps to reproduce the bug

```bash
1. Go to Observation matrix hub (tasks/observation_matrices/observation_matrix_hub)
2. Right-click on any of the available observation matrices
3. Select any of the options available

"Show" results in an error---"The page you were looking for doesn't exist" in sandbox; 
"Edit" results in the same error
"Pin/Unpin" is silent, but the matrix is not added to the Pinboard
"Delete" is silent, but the matrix is not deleted
```

### Expected behavior

I would expect the following behaviour when selecting the options from the right-click menu:
- "Show": Be directed to "tasks/observation_matrices/view/XX"
- "Edit": Be directed to "tasks/observation_matrices/new_matrix/XX"
- "Pin/Unpin": The matrix should get added to the pinboard (or removed if already on it)
- "Delete": An "Are you sure?" dialogue should appear, if "Yes" is selected, the matrix should be destroyed.

The expected behaviour of "Show" "Edit" and "Pin/Unpin" can be achieved by clicking on the links or icon in the table showing the available matrices. However, I cannot see any other way of deleting Observation matrices, either on the Observation matrix hub, or in the edit view for the unwanted matrix.

### Environment

- [X] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandfly

### Version

build 2b7f7f502 (sandbox)/ v 0.22.3 (development)

### Browser Used

edge (sandbox)/ firefox (development)

**Comment by proceps** [comment]
Interesting, I guess I never used it this way
![image](https://user-images.githubusercontent.com/5597748/145151856-5ae2b528-8722-496f-9658-4410e1e47829.png)
