### ISSUE TITLE
Task - Edit Observation Matrix - Add Rows from another matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2717]
When I try to add OTUs from another matrix, I can select the external matrix, and from the list, I can add few OTUs, but the button does not work.
<img width="557" alt="Screen Shot 2021-12-08 at 4 00 54 PM" src="https://user-images.githubusercontent.com/5597748/145291811-e4a9a456-9625-4561-be77-2c427d9cbe9d.png">

**Comment by jlpereira** [comment]
It was already fixed during the presentation 
https://github.com/SpeciesFileGroup/taxonworks/commit/eb4d66afc24f4853479c1a52cfe2dfd422bb2368
