### ISSUE TITLE
Zeitwerk mode

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2718]
We might need to consider prioritizing changing our loader to Zeitwerk. Besides occasionally having to patch loading (like in https://github.com/SpeciesFileGroup/taxonworks/commit/7768b7e3f11e38ef8e2dbd167f99416026f605d2), it [will be mandatory Rails 7](https://weblog.rubyonrails.org/2021/9/3/autoloading-in-rails-7-get-ready/)

**Comment by mjy** [comment]
We definitely need to do this, it will also help cleanup our autoload.

Can we start/work on it in a Rails 7 branch?

**Comment by LocoDelAssembly** [comment]
You think we should go all the way now and not just have zeitwerk working with current rails?

**Comment by mjy** [comment]
I guess I'm predicting that the refactor required will be large enough that it makes sense to undertake it when we also move to 7, but I could be wrong.  I'm fine with a seperate branch tackling the problem pre 7.

**Comment by mjy** [comment]
Related: https://github.com/SpeciesFileGroup/taxonworks/issues/2981

@LocoDelAssembly let's make 2 PRs for now.  This alone, and 7 alone, and see where it goes from there?
