### ISSUE TITLE
[Bug]: Can't create new source from BibTeX

### ISSUE THREAD

**Issue by markmetz** [SpeciesFileGroup/taxonworks#2719]
### Steps to reproduce the bug

```bash
When creating "New source" from "BibTeX"
Paste in BibTeX source (see example below) and click "Create" button
```

### Expected behavior

New source is created and move to soft validation

Observed behavior:
Failure beep and "fly up" window with text "Wrong data X"

BibTeX source example:
@Article{Park2021a,
  author   = {Kyu-Tek Park AND J. B. Heppner},
  title    = {Notes on Vietnam moths, 21. Athymoris in Vietnam, with two new species (Lepidoptera: Lecithoceridae: Torodorinae)},
  journal  = {Lepidoptera Novae},
  year     = {2021},
  volume   = {13},
  number   = {1-2},
  pages    = {23--26},
  issn     = {1941-1014},
  abstract = {– Two new species of the genus Athymoris Meyrick, 1935, are described from Vietnam: Athymoris gilvimaculata Park & Heppner, sp. nov.,
and A. clinozonalis Park & Heppner, sp. nov.},
  file     = {:VN-Athymoris.pdf:PDF},
}

Note:
Earlier this morning I created a source from BibTeX successfully with this BibTeX source (Although the drag and drop pdf document failed for which I'll add a second bug:
@Article{Park2021,
  author   = {Kyu-Tek Park and J. B. Heppner},
  title    = {Review of genus Adelomorpha of Southeast Asia (Malesia) and transfer from Gelechiidae (Lepidoptera: Lecithoceridae: Torodorinae)},
  journal  = {Lepidoptera Novae},
  year     = {2021},
  volume   = {13},
  number   = {1-2},
  pages    = {13--22},
  issn     = {1941-1014},
  abstract = {– Notes and new records are given for the genus Adelomorpha Snellen, 1885, and the species A. ritsemae Snellen, 1885, from Sulawesi, and
are transfered from Gelechiidae to Lecithoceridae, with description of three related new species of Malesia, A. dumoga n. sp. and A. minahasa n. sp. from
Sulawesi (Indonesia), and A. perakensis n. sp. from Perak (Malaysia).},
  file     = {:Adelomorpha.pdf:PDF},
}

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Browser Used

Google Chrome Version 94.0.4606.54 (Official Build) (64-bit)

**Comment by proceps** [comment]
I just tried in sandbox, and everything works.
Suggested three potential issues:
1. The source is created, but not saved, you still have to save source after it is created: 
![image](https://user-images.githubusercontent.com/5597748/145416866-2651b28b-1ff4-46ba-afd0-373713dcbac8.png)
2. You get logged out of the DB. I happens to me ocasionally, when I have window open on the source interface, and I try to create new source, the system fails to notify me, that the user is not logged into the system. Reloading the page and logging back helps to resolve the problem.
3. Source is already in the DB.

**Comment by markmetz** [comment]
Good suggestions, but doesn't seem to be the case for me.
The source is not in Production based on a search.
I am definitely logged in.
There's no option to save the new source until after the BibTeX is processed.
![BibTeX_Source_Error](https://user-images.githubusercontent.com/7288657/145420920-8ef32687-b43b-4362-9f57-b9763ca44996.png)

**Comment by proceps** [comment]
We may have an open issue, if the field names in Bibtex have some space before, the Bibtex is not processed. When I copied the record from your example above, it just worked. I actually preffer to work with doi, that works very smooth. Besides, it can brings some additional metadata.

**Comment by mjy** [comment]
Replicated, but one of the records has to be present first.  Checking for details on "Wrong data".

**Comment by mjy** [comment]
First problem: @jlpereira Please replace "Wrong data" with the content of the JSON response, e.g. we're actually returning "{\"identifiers.identifier\":[\"has already been taken\"]}" that.

Second problem- I suspect the identifier parsing of the leading identifier is stripping something.  Looking into that.

**Comment by mjy** [comment]
The problem is with `issn`, it should not be added as an identifier for type 'Article'.

**Comment by markmetz** [comment]
Removing issn worked!
Not sure why that would be a bug since issn is the unique identifier for the journal.
The identifier journal is accepted for type 'Article'

**Comment by debpaul** [comment]
> The problem is with `issn`, it should not be added as an identifier for type 'Article'.

@mjy bibtex site says there are required, optional, and non-standard fields and that **issn** is "non-standard" for type @article. But that doesn't mean we have to refuse it does it? see https://www.bibtex.com/e/article-entry/

**Comment by mjy** [comment]
We are not refusing it, we are saying that if we take it, we must apply it to the thing that it identifies, in TaxonWorks' case this is a Serial that is linked to the Source, not the Source itself.

**Comment by proceps** [comment]
I believe it will be just ignorred if present.

**Comment by debpaul** [comment]
> I believe it will be just ignorred if present.

Yah, @mjy explained. But the user might be confused / and is then losing information if they don't realize it was ignored. So a good idea perhaps to be very clear we are taking the required level of bibtex elements for each type and not the non-standard elements for any given type.

**Comment by proceps** [comment]
probably, we should just hide this field in the interface.

**Comment by mjy** [comment]
I kept this issue open because we can set it up to NOT lose information.  That's the whole point.
