### ISSUE TITLE
[Bug]: Numbers 1--5 on my keyboard don't work TaxonWorks fields

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#2724]
### Steps to reproduce the bug

```bash
Weirdly, numbers 1 to 5 on my keyboard don't work in TaxonWorks. They work well in other circumstances (including typing in this field now---123456789), but they don't add anything to the various fields in TaxonWorks.

1. Navigate to any field in TaxonWorks (e.g. tasks/nomenclature/new_taxon_name)
2. Put cursor in a field (e.g. "Name")
3. Type "123456789" using the main number keys
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/1320161/145666404-b16f298e-3b53-4f5b-afc1-f8dc518ac6cb.png)

### Expected behavior

I would expect the number "123456789" to appear in the text box

### Environment

- [X] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandfly

### Version

build f594ad1d2 / v 0.22.3

### Browser Used

firefox

**Comment by proceps** [comment]
could not replicate. But in the past some people also reported issues with numeric values. Not sure if this a browser issue. Did you try another browser?
![image](https://user-images.githubusercontent.com/5597748/145679593-ad8512d2-5acb-41b9-9c2f-3167ebe60235.png)

**Comment by jlpereira** [comment]
Me neither, did you try using other browser @sdjbrown ?

**Comment by LocoDelAssembly** [comment]
I think I also had this problem with the DwC importer when I was in a Zoom breakroom with @debpaul. Had to refresh the page to be able to type digits in cells.

**Comment by jlpereira** [comment]
Replicated

**Comment by sdjbrown** [comment]
Confirming that this bug has been fixed. Great job, thanks.
