### ISSUE TITLE
DwC Export missing collectionCode field, joins namespace and identifier in catalogNumber

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2726]
Eg namespace is `ABC`, identifier is `123`: 

Current output
|catalogNumber | ... |
|---|---|
|ABC-123| |

---
Desired result
| collectionCode | catalogNumber | ... |
|-------------|------------------|-----|
| ABC         | 123              |     |

**Comment by mjy** [comment]
If you do not want to join namespace to the identifier on export then make virtual, i.e. set it to `is_virtual`.

**Comment by mjy** [comment]
We do not export `collectionCode`, as it doesn't always map to our concept of Namespace.  I suspect we should use a DataPredicate to clarify that you want to export a `collectionCode` and link it that way, but I'm not 100% certain.
