### ISSUE TITLE
[Feature] DwC Occurrence Importer, better way to handle collectionCode with multiple institutionCodes

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2733]
### Feature or enhancement

In the DwC Occurrence Catalog number namespace mapping, we set the namespace for each institutionCode with the same collectionCode. ie [[institutionCode, collectionCode], namespace] mappings.
If I wanted to set the namespace for a collectionCode, regardless of the institutionCode, would it make more sense to have:
* an option to set the namespace for each collectionCode once, ignoring institutionCode, or
* a button to apply the namespace to all rows with the same collectionCode (mockup below)

### Location

DwC-A importer

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/33206210/146838710-3fbe953e-0ce0-4398-82e2-aa3d353c2724.png)

**Comment by LordFlashmeow** [comment]
I was thinking it might be easier to group the rows by collectionCode, and assign to all by default. If the user wants to use different namespaces, they can click the triangle to expand the grouped rows.

<img width="738" alt="Revised Catalog Number Namespaces" src="https://user-images.githubusercontent.com/33206210/173917851-27f3e21c-68ea-4ef0-a759-1110ab54d796.png">

**Comment by LocoDelAssembly** [comment]
Things to do:
- Sort by collectionCode, institutionCode
- Check if possible to have 3 tables, first one same as we have now, then two more matching by either collectionCode or institutionCode with less priority than first one.

**Comment by mjy** [comment]
Where is this at realtive to the last update?

**Comment by LocoDelAssembly** [comment]
I think we can close as original request was done, however `institutionCode` alone was not implemented as it would complicate things too much, but that was an idea that came later and was only for completeness sake rather than solving an actual requirement.
