### ISSUE TITLE
Improve Source autocomplete

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#274]
* Suggestions welcome as to how to prioritize source autocomplete

For example
* match exact author name first (what to do in multiple authors)
* match exact author/year first
... etc.

**Comment by proceps** [comment]
Last name exact match
Any person exact match
partial match any part of the author string
Year match
Start of the title match
Start of the journal match
partial match of any part of the source string (author, year, title, journal) separate multiple works with wild cards on both sides.

**Comment by mjy** [comment]
See also #281

**Comment by mjy** [comment]
* [ ]  use a style to indicate whether source is in project, or not
   * [ ] return a reasonable number or results
   * [ ] provide example searches in data-help, and perhaps as tooltip

**Comment by mjy** [comment]
* [ ] year letter match

**Comment by mjy** [comment]
Priority
* [ ] exact author and autocomplete year_letter (limit 1)
* [ ] exact author and year (limit 4)
* [ ] any person with year (limit 4)
* [ ] partial author with year (limit 4)
* [ ] whole query with spaces as wildcards (limit 5)
* [ ] any match to ORed fragments (limit 20)

**Comment by mjy** [comment]
Closing, further refinements by new issues.
