### ISSUE TITLE
As a developer I need to investigate why DwC download creation is taking so long

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2742]
Double check that indexing isn't being re-done when not required (which should be almost never now).

**Comment by LordFlashmeow** [comment]
I found that skipping the excluded columns was significantly faster than plucking all and deleting from the table

eg: 
```ruby
#lib/export/download.rb
def self.generate_csv(...)
   # ...
    column_names = scope.columns_hash.keys.map(&:to_sym) - exclude_columns

```

**Comment by LocoDelAssembly** [comment]
https://github.com/SpeciesFileGroup/taxonworks/compare/development...2742_debug_dwc_dumps

I remember trying deleting unneeded columns pretty much the way you did but can't remember what I saw going wrong. The branch still fetches all columns but is very minimally impacted when deleting them but better would be not fetching them in the first place.

**Comment by mjy** [comment]
I can tackle this, there are multiple routes to the last query that need to be considered both for DwC and the general CSV download framework.  I'm pretty sure I know at least some of points that need updates.
