### ISSUE TITLE
DwC export "verbatimLabel" from "Buffered" fields

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2749]
### Feature or enhancement

As a collection manager, I want to export "buffered" (e.g. Buffered Determination, Collecting Event, Other labels) fields in my DWCA to the GBIF and TDWG-proposed "verbatimLabel" field (see https://github.com/tdwg/dwc/issues/32) 

GBIF Documentation here: http://rs.gbif.org/extension/gbif/1.0/typesandspecimen.xml#verbatimLabel 

This could be a "checkable" option when the option to export Data Attributes comes up from CO Filter. 

### Location

https://sfg.taxonworks.org/tasks/collection_objects/filter

### Your role

Collection manager

**Comment by tmcelrath** [comment]
Working on finding a dataset that uses this field already in GBIF for reference, if it exists.

**Comment by mjy** [comment]
The recommendation is to add this as a data attribute, i.e. it would be indexable, but not processed or "understood".  It seems we are still waiting on the ratification of the field at this point.

**Comment by tmcelrath** [comment]
https://dwc.tdwg.org/terms/#dwc:verbatimLabel
has been ratified and approved. Time to include in exports!
