### ISSUE TITLE
Task - OTU (Taxon) filter

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#275]
Concept is nearly identical to filter collection objects, but it returns OTUs.  Facets are joined by && as for collection objects.

Three facets to start:

# Geographical
* Area/map (Otu -> TaxonDetermination -> CollectionObject -> CollectingEvent -> [GeographicArea/Georeference])

# Nomenclature
* A- All OTUs for TaxonName (Otu -> TaxonName)
* B - All OTUs and descendants of A
* C -Only OTUs of nomenclature rank X for B

# Author
* A - All OTUs tied to TaxonNames with Person name ( Otu -> TaxonName -> TaxonNameAuthor -> Person) (choose a person)
* B - All (Otu -> TaxonName#verbatim_author) (provide a string)
* C - All matches through A and B *by string*

Result is just a table of OTUs, sorted alphabetically order(TaxonName#cached, Otu#name).

**Comment by jrflood** [comment]
Ready for pull request

**Comment by mjy** [comment]
Not closed until pull request accepted.

**Comment by mjy** [comment]
@TuckerJD @jrflood I think we can close this issue now, and open new issues for tweaks/issues?  If so please close.

**Comment by jrflood** [comment]
Development work has terminated on this issue.
