### ISSUE TITLE
CO/CE Filter - search by Coordinate invalid

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2756]
### Feature or enhancement

When I am filtering records in CO/CE filter, I want to be able to find records that have coordinates in the "verbatim Coordinates" field but are not "valid" and/or mappable, and do not otherwise have an associated georeference. 

### Location

https://sfg.taxonworks.org/tasks/collection_objects/filter & https://sfg.taxonworks.org/tasks/collecting_events/filter

### Your role

Collection manager

**Comment by tmcelrath** [comment]
Cross-link to GBIF evaluation types:
https://github.com/gbif/gbif-data-validator/blob/master/doc/evaluation_types.md - where this idea comes from

**Comment by mjy** [comment]
@jlpereira we're going to do this by adding "Any" option to CE attribute facet.

* Collecting event filter parameter is `any_value_attribute[]=`
* You add the name of the parameter to this array
* Implement by adding a button (second option) that says "Any" beside exact.  If clicked value is erased (if present), and corresponding section in list that says "Exact" has "Any", not checkbox there

<img width="421" alt="Screenshot 2023-02-25 at 6 10 56 PM" src="https://user-images.githubusercontent.com/22600/221385475-f1575d47-0f84-4fda-b125-1a371eee38f5.png">

**Comment by jlpereira** [comment]
Done https://github.com/SpeciesFileGroup/taxonworks/commit/baba25d8affe7e5b0e5fdb510d6ce650f100e12b

**Comment by tmcelrath** [comment]
Looking forward to checking this!

**Comment by mjy** [comment]
It's not quite 100% aligned with your concept (we can't check validity of verbatim values with 100% certainty), but we can quickly see, for example, that there are 65605 records with verbatim latitude that don't have Georeferneces.

**Comment by tmcelrath** [comment]
Okay, but doesn't TW already have a check for this? E.g. I type in something in the verbatim field and it can't be mapped. Can't I search for those records somehow?

**Comment by tmcelrath** [comment]
This is a great search "Search by Coordinates in Verbatim but w/o Georeference" but is not "Search by Coordinate Invalid"

**Comment by mjy** [comment]
> "verbatim Coordinates" field but are not "valid" and/or mappable, and do not otherwise have an associated georeference.

So we are doing the latter.  If we step back and look at what's driving this issue (I'm guessing), bad values in DwC exports, then in practical terms what you are maybe asking for is an export mode that says "if we dont' have a Georeference, don't export the geo-coordinates".  That way we can use the presence of the Georeference as the confirmation that someone has validated the coordinates, so to speak (which is my practica/working assumption).
