### ISSUE TITLE
Citations by source: Taxon names should display the nature of taxon

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2760]
### Feature or enhancement

Formerly TW had the useful feature of showing if the taxon name displayed referred to a new species of new combination.
I don't know why this feature has been removed.
I would plea for its return!

### Location

Citations by source> Taxon names

### Your role

curator of project

**Comment by proceps** [comment]
It seams that all taxa are marked as valid now (with a checkmark), we should have "c" or "x" makrs for combinations and invalid names respectivly.

**Comment by adrik29** [comment]
> It seams that all taxa are marked as valid now (with a checkmark), we should have "c" or "x" makrs for combinations and invalid names respectivly.

Exactly, and it was working fine before, discriminating all those cases...
