### ISSUE TITLE
Task -  Matrix Row codder - Add illustrations for the descriptors which have those (same implementation as in interactive key)

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2763]
![image](https://user-images.githubusercontent.com/5597748/149398126-05297289-aeb6-4bad-a87f-2ce606bc097c.png)

**Comment by jlpereira** [comment]
Hi @proceps 

Since the task is different, I have some questions. Is this just a view or will have checkboxes and apply button? In that case, should it redirect to interactive key task?

**Comment by proceps** [comment]
In the row codder, I have a list of descriptors. I have a user, who requested the illustrations for each char_state, so that the codding could be done by clicking the depiction. I suggested that we should implement it the same way it is implemented in the interactive key. If depictions are available, provide a hyperlink to open a modal window with depicltions, and allow codding by clicking on the depiction. We can probably add checkboxes and sync the click on the depiction with the checkbox in the main list.

**Comment by debpaul** [comment]
Saad is asking for this.

**Comment by jlpereira** [comment]
Done
