### ISSUE TITLE
[Bug]: DwC status filter rows don't update after stopping import

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2768]
### Steps to reproduce the bug

```bash
1. Load a dataset that has errors in it
2. Manually import a known error row
3. Set the status filter to "Errored", 1 row appears
4. Import all rows through the Import button in the toolbar
5. Once more errors occur, click stop import
6. The newly errored rows don't appear in the filtered view until the filter is reset/reapplied.
```

### Expected behavior

I would expect the newly errored rows to appear once I've stopped the import.

This would be helpful for quickly finding errors when I see them crop up while monitoring an import.

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

**Comment by jlpereira** [comment]
Fixed

**Comment by LocoDelAssembly** [comment]
(In dwc_scoped_filters branch, not fixed in development yet)
