### ISSUE TITLE
[Bug]: Uniquify people task shows "0" in used column and no roles

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2769]
### Steps to reproduce the bug

```bash
1. Open uniquify people task
2. Click search to show people
3. Used column says 0, roles is a question mark
```

### Screenshot

<img width="840" alt="Screen Shot 2022-01-17 at 3 40 59 PM" src="https://user-images.githubusercontent.com/33206210/149848164-eee4cd39-ba62-4646-946c-fb68cea7bb4f.png">

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

**Comment by mjy** [comment]
@jlpereira grasping without looking, but this is an `&extend[]` issue maybe?

**Comment by jlpereira** [comment]
Probably, looking
