### ISSUE TITLE
Alternate Values for People

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2774]
The author search does not correctly find the alternate name I need to find.

When I add an alternative value for a Chinese name, for example, it can be written with or without "-". eg Zhang, Dao-Chuan or Zhang, Daochuan.

I go to Alternative Values ​​to add the name Daochuan instead of Dao-Chuan in the Alternative Spelling section.

![image](https://user-images.githubusercontent.com/63611746/150171601-2c19ed90-f555-4beb-b496-ed6db765c4b3.png)

And click SAVE

![image](https://user-images.githubusercontent.com/63611746/150171797-18144ff4-393b-4ec9-9d67-dc38ea3f1fb8.png)

But then, for example, in the New Source task, when I type Zhang Daochuan in the Author search, it doesn't find anything.

![image](https://user-images.githubusercontent.com/63611746/150172852-ecdacdaa-d22e-4342-87f8-f3439543418c.png)

If I search for just Daochuan, without typing the last name, it takes me to the person I'm looking for.

![image](https://user-images.githubusercontent.com/63611746/150173094-39a4e391-1d3d-4d2b-83f2-e1e4e713dfe1.png)

 It doesn't associate it to the last name as it should.
 
![image](https://user-images.githubusercontent.com/63611746/150173311-83ba08c2-1c0c-4e51-b50f-e3d26ce283ee.png)

I would need it to show me that this alternate spelling is for the same person. Here at OSF is an example of the information I get from searching for people in Species Files.

![image](https://user-images.githubusercontent.com/63611746/150174859-ba7daeed-1bfe-4452-a0e6-38cd74d3f840.png)

**Comment by proceps** [comment]
If you search for "Zhang, Da" in TW, you should get right result (same as in OSF example). If you search for "Daochuan, Za" - probably not. All search terms are treated as ordered. So the search assumes that Daochuan is the last name. Alternative searches are linked to Last name field only. I can check if the first name could be added to the search criteria, but the real chalenge is that more options you add, less precise results you get. Partial searches work for me best. The last name an first inicial or last name an both inicials works best for me.

**Comment by debpaul** [comment]
do we index all these values? could there be one box to search any part of the string instead? (Note I'm trying to follow what is possible, what we know won't work). @mabecabrera thank you for this entry. We need to work on documentation that explains what to expect and what we know will not work.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/162041894-2f28b00b-94f2-4002-8d52-101d7f0cb364.png)

**Comment by proceps** [comment]
Previous one was for the last name, This one is for the first name.
![image](https://user-images.githubusercontent.com/5597748/162042502-84bcac24-1bfc-441c-bf3a-c92594afda7f.png)

**Comment by proceps** [comment]
Radial annotator for Person is designed for adding alternative values (when you uniquify people, it is also done automatically).
![image](https://user-images.githubusercontent.com/5597748/165372808-376003e6-20c8-417e-9af7-228bc9f371b2.png)

**Comment by proceps** [comment]
@mabecabrera, did you try the alternative spellings? Did it work for you? Should the issue be closed?

**Comment by mabecabrera** [comment]
Yes! @dimus! It works fine! Thank you! I didn't want to close the issue myself. I'll do it now! 👍
