### ISSUE TITLE
Image duplicates

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2776]
When I upload a new image, the system already recognizes that the same image was uploaded to the DB, but still a new duplicate image is created. It would be nice to recognize the duplicate, and do not add a new image, instead of, only to create a depiction referring to an existing image in the DB.

**Comment by kdrager1** [comment]
This would be helpful for our instance of TaxonWorks as well. We are interested in setting up a matrix with anatomical terms as each column, it would be nice to have one image that can be linked between multiple columns rather than duplicating them.

**Comment by debpaul** [comment]
See also #2909

**Comment by proceps** [comment]
should be fixed
