### ISSUE TITLE
Task - Browse OTU - Image section is missing for a genus OTU

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2786]
I have an OTU associated with a genus. Genus has depictions in the image matrix, but those are not visible in the Browse OTU page. May be this is also an issue for other ranks (subgenus, family-group ranks, etc.). For species, the image section is displayed.
I expect to see the images associated with this OTU regardless of the rank.

**Comment by mjy** [comment]
>  I expect to see the images associated with this OTU regardless of the rank.

Not that easy.  There may be thousands.  We'll have to make this dynamic and be clever.

**Comment by proceps** [comment]
not all, just those dirrectly associated with this otu, or through the image matrix observation on this otu, not all species from the genus
