### ISSUE TITLE
Examined material section formatted to the journal style.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2787]
As a user, I would like to be able to download list of studied specimens in a format accepted by the journal. At least Zootaxa and ZooKeys should be supported.
As an example of the tool, we can look at http://phorid.net/automatex/index.php
The web site offers a scv template as a download.

**Comment by mjy** [comment]
Dulicate of https://github.com/SpeciesFileGroup/taxonworks/issues/2325.
