### ISSUE TITLE
Task - filter sources - date range

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2788]
The date range filter has "Now" Button. When chlicket, the button shoud set the End date, now it changes start date of the search.

**Comment by jlpereira** [comment]
That was the old behaviour, we changed it but I dont remember why. If you click one time, it will change the start date, if you do double click, it will change the start and end date.

**Comment by proceps** [comment]
Please change to a single click, if somebody need to set up the start date for today (not sure why whould you do it), that a second 'now' button should be added to the interface.

**Comment by mjy** [comment]
Why wouldn't you need start date now?  It's the exact same reason as using it for end date, why would I want that?  Setting the end date without start date by clicking a button makes no sense.

It should fill the first empty date.  There is no confusion then.
