### ISSUE TITLE
[Bug]: Type species mode of designation causes crash

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2789]
### Steps to reproduce the bug

```bash
Whenever people try to indicate the type species of a genus in /Edit taxon name/, the system stalls after showing a menu consisting entirely of grayed-out options.
In my example, the genus Yraguara has a junior subjective synonym which is Melloleitanius.
It is impossible to indicate the type species of Melloleitanius.
```

### Screenshot

Example: genus Melloleitanius:
![image](https://user-images.githubusercontent.com/46284943/151699202-565e3b7d-990a-46b1-875c-f26988f2bfbc.png)
I go to the module "Type", enter the species name:
![image](https://user-images.githubusercontent.com/46284943/151699308-d7d72eb4-593c-47d1-8c45-af9a61e914eb.png)
And voilà, I receive a list of grayed-out options which freezes any further action I'd wanted to take.
![image](https://user-images.githubusercontent.com/46284943/151699355-b4ab6e8d-7cd3-4ecb-bfcf-7c903942c56f.png)

### Expected behavior

I expect that SOME options would be normally colored, allowing me a choice so I could proceed with the register.

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

### Browser Used

chrome

**Comment by jlpereira** [comment]
Hello @adrik29 

This was already fixed last week, you will see the change on the next update

**Comment by adrik29** [comment]
@jlpereira - thanks a lot! Cheers.

**Comment by adrik29** [comment]
"on the next update" = when? is there a schedule for the updates?

**Comment by adrik29** [comment]
@jlpereira 
> Probably today or next week, @adrik29

I saw the update now. It looks like we have nice new features. I'm curious to explore them. Congrats!
