### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#279]
```
when I run `dockercompose-up`
   and database.yml exists
     but it is a configuration for a non docker-based environment
         then my taxonworks_app container crashes
```

In `exe/docker_compose_start.sh` check that:
* port matches configuration in database.yml.docker.compose.example
* IP matches configuration in database.yml.docker.compose.example
* other?

**Comment by devarsh1997** [comment]
- Ensure database.yml is validated according to @mjy's suggestions
- Ensure webpacker has compiled successfully before starting the Rails server in app container
- Maybe other features like pre-loading users using rake db:seed?
