### ISSUE TITLE
Task - Edit taxon name - original combination (variety and form)

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2795]
Original combination for ICZN names is now limitet to 4 rank levels (genus, subgenus, species, subspecies), there should be 2 additional levels  (variety and form).
In ICN, original combination has 8 levels.

Subsequent combination is correct now (4 levels for ICZN and 8 levels for ICN).

**Comment by jlpereira** [comment]
Fix https://github.com/SpeciesFileGroup/taxonworks/commit/29848521a5137f948de8605041992b298983db8f
