### ISSUE TITLE
[Bug]: cannot add type species for new genus name

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#2796]
### Steps to reproduce the bug

```bash
1.See genus Kressleinius
2. when I attempt to add the type species, Kressleinius celans, I get the dialog box in screen shot below
3. None of choices are active (correct one is type by original designation and monotypy), in fact, the x at top right to exit doesn't work either
4. Locks up the system, need to quit TW and restart

...
```

### Screenshot

![Screen Shot 2022-02-04 at 10 17 20 AM](https://user-images.githubusercontent.com/30122486/152565120-284311d1-b8a2-46db-9629-5774a74fffb2.png)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Version

Version 0.22.7 release

### Browser Used

Chrome

**Comment by mjy** [comment]
Duplicate, this is fixed and will be made live ASAP.
