### ISSUE TITLE
Alphabetical list of source authors task does not access letters

### ISSUE THREAD

**Issue by mikemaehr** [SpeciesFileGroup/taxonworks#280]
Opening the alphabetical list of source authors task produces a list of authors available within the project. Clicking on any of the letter links available horizontally (e.g., 'D') is always greater than 10 seconds for the bar to appear to finish loading, but does not take you to the letter.

**Comment by mjy** [comment]
This needs massive refactoring, if not complete rethought, it was an early experiment.  One solution is to dynamically load the section on letter click.

**Comment by mjy** [comment]
* [ ] Turn the Alphabetic list of authors into a super simple Vue app, click a letter, update a list.
* Endpoint for query result is /people?last_name_starts_with=A (one letter only, maybe case insensitive)

**Comment by mjy** [comment]
@jrflood We should close this, correct?

**Comment by mjy** [comment]
Blocked by #542
