### ISSUE TITLE
Observation matrix - Download CSV file

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2801]
There is a request from a user to be able to download the matrix in CSV format, so that it could be directly used in Principal Component analisis.

**Comment by mjy** [comment]
This already exists?

**Comment by proceps** [comment]
we have tnt, nexus and NeXML, I have a request to download the matrix in a format, which could be dirrectly opened in Excel or in a statistics software (PAST, for example).

**Comment by mjy** [comment]
I'm certain I have the code for this and it was an option, but indeed I
don't see it there now.  Easily done.
