### ISSUE TITLE
Task - Filter descriptors [was: Filter descriptors  interface]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2802]
There is a request from a user to be able to download the list of descriptors and the states.
This probably could be implemented as a Filter.
The filter options:

New
* [x] All descriptors - no param, just click search, as in all filters
* [x] Matching `term`, curator selects `term_target` (one of `name`, `short_name`, `description`, `description_name`, `key_name`) with nil for all (radio)
* [x] `term_exact` 
* [x] `observation_matrix_id` and `observation_matrix_id[]` Descriptors from a particular matrix
* [x] type  `descriptor_type` and `descriptor_type[]`

"Boolean"
* [x] Descriptors with/without/both observation_matrices - `observation_matrices` 
* [x] Descriptors with/without/both observations - `observations` 
* [x] Descriptors that do/not have depictions on *observations* - `observation_depictions`

Existing
* [x] Tags facet - Desriptors with a Tag
* [x] Users facet
* [x] Identifiers facet
* [x] Notes facet

Make the list downloadable in a text format with options: each state on a separate line, or all states inline with the descriptor.

**Comment by mjy** [comment]
> Make the list downloadable in a text format with options: each state on a separate line, or all states inline with the descriptor.

@proceps can you describe further what the goal of this format is?  Are they looking for a paper worksheet?

**Comment by proceps** [comment]
Yes, a collaborator told me he wants to download a list of descriptors in publication ready format. One of the requirements, is that not all the states of the descriptors are used in one particular matrix, only those which are in this matrix should be included to the list.
