### ISSUE TITLE
DwC archive export - Determinations

### ISSUE THREAD

**Issue by LauraPorturas** [SpeciesFileGroup/taxonworks#2805]
### Feature or enhancement

When downloading data to a .csv or DwC archive it would be nice to have all determinations downloaded to the scientificName field, even if the nomenclature is not in the system. For example: PSUC_FEM 10006358 has a determination saved, but when data are exported, this determination is not included. Other examples of collection objects with determinations that do not export: PSUC_FEM 10005896 & PSUC_FEM_10006284

### Location

DwC Dashboard

### Screenshot, napkin sketch of interface, or conceptual description

<img width="349" alt="Screen Shot 2022-02-07 at 1 59 47 PM" src="https://user-images.githubusercontent.com/62353864/152854118-6f653f7e-6100-4cd6-b1b2-5a086401aa16.png">

### Your role

Collections Manager

**Comment by mjy** [comment]
Thanks @LauraPorturas.  This is a bug if that determination is not showing up.  Checking now.

**Comment by mjy** [comment]
Update on this.  The reason you are not seeing the determination is because the OTU is not linked to a corresponding taxonomic hierarchy.  There are several issues here:
* Certain fields are required to share the data with other providers (e.g. a nomenclatural hierarchy including Kingdom if it goes to GBIF)
* We could dump the data if there are OTU name only OTUs, however then we'd have the possibliity of very mixed quality results
* We could make the otu NAME mappable to scientificName as an option, though this would again have limited use (but nevertheless some use).  

I'm not sure how to best proceed.  @LauraPorturas can you let us know what your needs are with respect to where the export of data is going?  Is it ongoing research, or "archiving"?

**Comment by mjy** [comment]
This is also illustrating that we need to prioritize this: https://github.com/SpeciesFileGroup/taxonworks/issues/130

**Comment by mjy** [comment]
@LauraPorturas you are right on track.  We need to get a preview of the OTU filter live for you to do this.  In the interm I might be able to build you a quick report that does what you want.

**Comment by LauraPorturas** [comment]
I didn't know an OTU filter was in the works. That will be awesome.

**Comment by mjy** [comment]
Yes, there will be an epic OTU filter, and in general filters are going to get unified in some very cool ways. We're discussing a very brief preview that would do what you need in the background now.

**Comment by debpaul** [comment]
@mjy wrote:
> @debpaul please chime in here? If there is _only_ `scientificName` (no other fields) will GBIF take the data?

@mjy I think the answer is "yes" BUT, w/o other fields (taxonRank, kingdom)  they will match the string against the backbone. So with homonomy, synonomy, and orthographic variants, etc. some issues arise resulting in species ending up in some very strange places.

See [complete list of GBIF Dataset Required fields](https://www.gbif.org/data-quality-requirements-occurrences).

**Comment by mjy** [comment]
Well, then I think I will adapt the exporter to use `Otu#name` as `scientificName` if TaxonName is not present.   This will mean things like `n.sp` and `undescribed spp #2` etc. can make it in to the exports, so it's not without consequences.

**Comment by mjy** [comment]
@debpaul that is calculated through TaxonName linkages.  I'd rather not add a work-around, as it promotes worst, not best practices.

**Comment by debpaul** [comment]
@mjy re temporary names. they are "not allowed" see this https://www.gbif.org/data-quality-requirements-occurrences#dcSciName
`Ideally, the name supplied is at species level or below. If the determination only allows for information on a higher level, this is acceptable as well. Valid scientific names are Latin names following the syntax rules of the respective taxon group (e.g. botanical nomenclature). Not permitted are, i.e., working names ("Mallomonas sp.4"), common names ("fruit fly"), or names containing identification qualifiers ("Anemone cf. nemorosa").`

**Comment by mjy** [comment]
Then we should exclude `@otu.name` as an export.  We must provide curatorial tools, as noted above, to make things easy to migrate from name to nomenclature.
