### ISSUE TITLE
Broken short_url for images in NeXML

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2811]
Some short_url do not resolve to a real image file. For example:
https://sfg.taxonworks.org/s/xmpa4i
resolves as
/system/images/image_files/000/790/437/original/data?1632259405
searching for %data?% returns me in the shortened_urls table returns me about 100 results.
Is it some kind of indexing issue? or a problems with real images?

**Comment by mjy** [comment]
Can you link to the object with that URL?

**Comment by proceps** [comment]
https://sfg.taxonworks.org/images/790437

**Comment by proceps** [comment]
in 3i db

**Comment by proceps** [comment]
I have suspicion that the user file name may have some characters which were not correctly interpreted and the it was replaced with 'data'
```
User file name: data

Height: 190

Width: 235
```

**Comment by proceps** [comment]
I will add this to pending migration for 3i DB.
