### ISSUE TITLE
[Bug]: Collection Object custom data attribute values don't appear in Comprehensive (after DwC Importer run)

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2813]
### Steps to reproduce the bug

```bash
1. Add custom data attributes
2. Use DwC Import with field headers modified to upload data to the custom attributes
3. Review records after import, we see the custom data attributes and the values associated in some places but not others.
- can see in Collection Object attributes UI under Annotations
- can see via the Specimen Annotator > Data Attributes
- **can not** see in Comprehensive specimen digitization
...
Example: Can see here https://workshop.taxonworks.org/collection_objects/138468
Example Cannot see these values here https://workshop.taxonworks.org/tasks/accessions/comprehensive?collection_object_id=138468 

@MJTPaleo and I discovered this while testing the DwC Importer
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/153480072-c5406580-1215-4431-bfe7-986d681a2a6d.png)

### Expected behavior

After attributes are added and the DwC importer runs, we expect to see the values for any of these attributes appear in the matching fields displayed in Comprehensive.

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

workshop

### Version

 SANDBOX - build cc13fc026 on 2022-02-10T16:03:33Z

### Browser Used

firefox

**Comment by jlpereira** [comment]
Custom attributes needs to be setup in: https://workshop.taxonworks.org/tasks/projects/preferences/index

Once you able the fields for the data attributes on the collection object, the fields and the information should be present on comprehensive

**Comment by debpaul** [comment]
> Do you need to extend[] data attributes? Can we see the attributes present in the annotators?

@mjy here's what we see in the specimen annotator

![image](https://user-images.githubusercontent.com/2990155/153488232-6e6430ba-68be-44d2-a80d-fbb4f69b64bb.png)

**Comment by jlpereira** [comment]
Like @LocoDelAssembly said, you have to enabled for collection object. In the screenshot are enabled for collecting events

**Comment by debpaul** [comment]
Thanks @jlpereira @LocoDelAssembly. Let's see if @MJTPaleo and I can grok this. 

@mjy we have specimen occurrence records to upload in the DwC Importer. But @jlpereira and @LocoDelAssembly make it clear(er) that the data attributes we added are part of the Collecting Event because they are associated with where?

I'm not understanding the model yet. ... but I can understand you want us to go in and check some boxes. I don't get why they automatically show up for the Collection Object and annotator ... but not in Comprehensive. I'm missing something.

**Comment by debpaul** [comment]
> 3\. Jared mapped the predicate to the wrong class (CO, not CE)

@mjy I think you and I did this particular mapping? Not sure now. (Post workshop, some changes may have been applied to what we uploaded).

**Comment by mjy** [comment]
@debpaul I believe we can close this?

**Comment by debpaul** [comment]
@MJTPaleo have you tested this, is all good now? Do the custom data attributes appear in Comprehensive for you after you use the DwC Importer?

**Comment by MJTPaleo** [comment]
pretty sure it works fine now. I haven't tested it in a while, but last time Hernan helped me with an upload everything seemed to be correct. I just haven't tested it since then, but I can if you like. Let me know.

Jared


M. Jared Thomas
Paleontology Collections Manager


PRI Center for Paleontology
Prairie Research Institute
University of Illinois at Urbana-Champaign


1816 South Oak Street
Champaign, IL 61820, USA
Office: +1 (217) 300-2790<tel:+12173002790>
Cell: +1 (760) 815-2296<tel:+17608152296>
http://paleo.prairie.illinois.edu<http://paleo.prairie.illinois.edu/>
________________________________

**Comment by mjy** [comment]
Thanks @MJTPaleo. Closing for now.  Can be re-opened if issues.
