### ISSUE TITLE
filter collection objects by creator/updater

### ISSUE THREAD

**Issue by juliah3** [SpeciesFileGroup/taxonworks#2815]
### Feature or enhancement

We have different sets of people working on different projects within the same TaxonWorks Project.  It would be very helpful if it was easier to filter collection objects by creator/updater. This would allow us to more easily work only on images/collection objects within our respective projects.

The two places this would work best with our workflows are:
1. The TODO/breakdown list page.  It would be great to be able to filter the 'hexagons' by creator/updater.  If that's too complicated, it would help to be able to type in a page number to jump to.
2. in the Filter Collection Objects Task. Likewise, it would be helpful to be able to sort by creator/updater.

Thank you!
Julia + Sophia

### Location

https://sfg.taxonworks.org/tasks/collection_objects/filter and https://sfg.taxonworks.org/tasks/accessions/breakdown/sqed_depiction/todo_map

### Screenshot, napkin sketch of interface, or conceptual description

For the collection object filter, it would be easy to add filters for record creator and record updater.

For the TODO/breakdown list, it would be great if we could filter by record attributes.  But if not, at the very least it would speed things up to have an option in the navigate bar to jump to a page number.  Eg.  ( Jump to: [type page number here] [Go button] )

### Your role

Collection digitization technicians

**Comment by mjy** [comment]
> in the Filter Collection Objects Task. Likewise, it would be helpful to be able to sort by creator/updater

This one is done.  

The other (TODO) is now a separate issue: #3043.  Closing this.
