### ISSUE TITLE
[Bug]: We Need to Talk About Junior

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2825]
### Steps to reproduce the bug

```bash
There is a mismatch between the author name in the authority for the species versus as the author of a source.
How do I correct this?
Did I enter anything incorrectly?

In "Edit taxon name", I used the "clone from the source" green button. And the suffix "Junior" already is missing.
https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=755457

But in the author name it is there.
https://sfg.taxonworks.org/people/59221
```

### Screenshot

![image](https://user-images.githubusercontent.com/46284943/154792163-471949e1-0942-484f-be6b-2b670c452777.png)
![image](https://user-images.githubusercontent.com/46284943/154792225-f67d546b-c127-4536-a30c-ea56aa7cbeb3.png)
![image](https://user-images.githubusercontent.com/46284943/154792243-552ef41c-665e-4fee-9ddb-cefab78d9e0e.png)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [ ] Production

**Comment by adrik29** [comment]
And I wanted to add that in our GUI this glitch does NOT occur, which is at least curious:
![image](https://user-images.githubusercontent.com/46284943/154792612-a55c2a8d-0b79-48dc-a3f9-61114dc4bb00.png)

**Comment by debpaul** [comment]
About Jr. :-) @adrik29 may I please be added to your project so that I can see the issue directly? Thanks.

**Comment by adrik29** [comment]
@debpaul -- Done!

**Comment by mjy** [comment]
@proceps Last name cached rendering  for taxon name author_year should include prefix and suffix of the last name, almost certainly it should include suffix?

**Comment by proceps** [comment]
Will take a look, I think it was fix long time ago.
