### ISSUE TITLE
[Bug]: In Matrix Row Coder, when I change an existing coding, saving stalls out

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2833]
When I try to change an existing coding in the Matrix Row Coder, the save bar stalls out (yellow with Saving Changes). It doesn't seem like it is lagging, I've had a window open for like five minutes with just the message up. 

This only happens when I edit the coding of an already-coded character, not when I code a character that has not been previously coded.

### Screenshot

![stalled](https://user-images.githubusercontent.com/70152690/155916581-0dd48432-6101-467b-a777-3832c796d6e5.jpg)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Browser Used

chrome

**Comment by jlpereira** [comment]
Hello @kandakoj 

I'm going to need some screenshots from the Browser inspector.
You can open it pressing Command+Option+J (Mac) or Control+Shift+J

1 - One of console tab
2 - Another two from network tab.

In "Network" tab, write "observation" in the filter input, you will see the failed request there(the red one), please click on it and take an screenshot of "response" tab and another one from "headers" tab

**Comment by kandakoj** [comment]
Here is a screenshot of the error in the console. 
![console_error](https://user-images.githubusercontent.com/70152690/156182473-9364afbd-ce3c-46de-97f5-b7b61dd15840.jpg)

The network tab doesn't show an error, even when I perform the action that showed an error in the console.
![networktab](https://user-images.githubusercontent.com/70152690/156182645-20426716-b27b-47be-ad28-351487ba3752.jpg)

**Comment by jlpereira** [comment]
Thanks @kandakoj

Looking at that line of code I can confirm this was already fixed last week. You will see the change on the next update
