### ISSUE TITLE
[Bug]: Under Soft Validations: The green "fix" button in front of "Indicate whether the synonym is objective or subjective" does not work

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#2838]
### Steps to reproduce the bug

```bash
1. Currently there is a green fix button in front of the statement "Indicate whether the synonym is objective or subjective" which would seem to indicate that there is a fix.
2. When you click that fix button nothing happens.
3. I think either there is no fix for this, currently, or if there is the fix is broken.
```

### Expected behavior

I expect that when I click on the fix button, the correct type of synonym would be indicated. Alternatively, if the fix is not available, I would expect there to be no green fix button.

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Version

0.23.1

### Browser Used

Chrome

**Comment by proceps** [comment]
Not all fixes will fix the issue. All of them will try. For Example, you have two genera marked as synonym, and they have two different type species. The fix will assigne a subgective synonym type (two genera based on different types). But if you have two genera and the type species is not assigne to either of those two, nothing could be fixed. The fix algorithm do not know if the issue could be fixed on not. Basically we have all soft validations divided into two categories, some of those could potentially fix (fixable messages). Some are not fixable. The invision is that in future, we can run soft validations on entire project and get some (not all) issues be fixed automatically.

On the fix click, the method can return success of failure messages, we currently do not display those. This could be updated in the future.

**Comment by debpaul** [comment]
Could there be a 3rd option? If i click "fix" i could get an option to go where i need to be to provide the information? I do realize this is "not" soft validation.

**Comment by proceps** [comment]
@debpaul this is already an option: click on the red triangle and get directed to the interface where you can fix it.

**Comment by mjy** [comment]
I thought it was a blue wrench?

**Comment by proceps** [comment]
Yes, may be, but I do not see the wrench now...

**Comment by mjy** [comment]
@jlpereira did we lose the blue wrench, or decide to use something else, in soft validation sections?

**Comment by jlpereira** [comment]
![Captura de pantalla de 2022-03-03 11-55-49](https://user-images.githubusercontent.com/16530364/156590155-de5b2356-af6a-4795-8e52-91cfeab2ef71.png)

Blue wrench is there, maybe is missing on that particular response

**Comment by proceps** [comment]
@jlpereira  Could you check if we can intercept success/return messages?

**Comment by jlpereira** [comment]
Looking, it seems we're getting error 500 in some of those. I'm passing you more details via gitter

**Comment by mjy** [comment]
@jlpereira @proceps @hhopkins77 can this be closed?

**Comment by hhopkins77** [comment]
Nothing for over 18 months. I think it can close.
