### ISSUE TITLE
DwC mappings for fieldNumber vs eventID are inconsistent on import/export

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2852]
On import, `fieldNumber` maps to `verbatim_trip_identifier`, and `eventID` produces a `Identifier::Local::TripCode` object. However, on export, `Identifier::Local::TripCode` is used for `fieldNumber` and `verbatim_trip_identifier` isn't used.

Can we change this so that import/export behavior is consistent?

Edit: I see that `verbatim_trip_identifier` is basically never used or exposed.

What about exposing `collecting_event_id` for `eventID` and leaving `Identifier::Local::TripCode` for `fieldNumber`? To me, this lines up better with the DwC definitions (eventID being computer/numerically-generated, while fieldNumber relates to the personal identifier given by the collector)

**Comment by mjy** [comment]
Thanks @LordFlashmeow.

Perhaps we need a new local identifier to improve semantics?  @LocoDelAssembly thoughts?

```
DwC File        TW Serialization                         Export
fieldNumber  -> Identifier::Local::TripCode          ->  fieldNumber = Identifier::Local::TripCode ? Identifier::Local::TripCode : verbatim_trip_identifier 
eventID      -> Identifier::Local::CollectingEvent   ->  eventID = Identifier::Local::CollectingEvent ? Identifier::Local::CollectingEvent : nil
```

Note that I'm *very* hesitant to expose TW internal ids as verbatim values in the export, i.e. CollectingEvent#id should not go direclty into eventID if a local identifier doesn't exist.   I'd rather write routes/services that can infer based on the DwC OccurrenceID.  Examples coming.

Let me know if this looks acceptable and I'll prioritize the back-end code on a new branch.

**Comment by debpaul** [comment]
I'm not necessarily following yet (still fuzzy). I can say that in botany, they often have no "trip code" at all. They don't use dwc:fieldNumber, rather they use dwc:recordNumber which is the unique number (unique to the collector) assigned by the collector for that specific object collected. Botanists might have a collecting event id. Not sure they'd map it to fieldNumber. FieldNumber tends to be used by non-botanists (in my experience).

**Comment by LocoDelAssembly** [comment]
Currently `eventID` is not necessarily a `Identifier::Local::TripCode` if you provide a specific `Identifier::Global` type in `TW:Namespace:eventID` (e.g. `Identifier::Global::Uri`, not really a namespace per se but if the importer sees that it knows you want different kind of identifier).

I'm not so sure about `fieldNumber` identifiers, we need to pair with something else, otherwise I believe collisions will occur pretty often. These are IDs that are assigned perhaps in a notebook (paper one, not computer) and pencil, and uniqueness is a somewhat soft requirement (despite it is required property to make it usable as an ID).

`fieldNumber`:  An identifier given to the event in the field. Often serves as a link between field notes and the Event.

Wonder if it is supposed to be considered verbatim identifier given its definition somewhat implies it might not be the definitive one?

**Comment by debpaul** [comment]
Yes @LocoDelAssembly you wrote:

> I'm not so sure about `fieldNumber` identifiers, we need to pair with something else, otherwise I believe collisions will occur pretty often. These are IDs that are assigned perhaps in a notebook (paper one, not computer) and pencil, and uniqueness is a somewhat soft requirement (despite it is required property to make it usable as an ID).

fieldNumbers will often only be unique to the person in-the-field, not global unique. And they may be different from some eventID (which has a greater expectation uniqueness).  
 
> `fieldNumber`: An identifier given to the event in the field. Often serves as a link between field notes and the Event.
> 
> Wonder if it is supposed to be considered verbatim identifier given its definition somewhat implies it might not be the definitive one?

The fieldNumber is more-or-less equal to dwc:recordNumber. It would be "definitive" for the collector (as in: should be unique in that person's notebook -- but not globally unique).

**Comment by mjy** [comment]
PIcking up some of this again.

> fieldNumber is more-or-less equal to dwc:recordNumber.

While part of a similar process they are clearly semantically different one identifies an Event (CE in TW), the other an Occurrence (CO/FO in TW).

**Comment by mjy** [comment]
Closing to work on in #3800.
