### ISSUE TITLE
[Bug]: Verbatim original citation for images not displayed correctly

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#2857]
When the original citation for an image is a verbatim source, the display looks like this:
![image](https://user-images.githubusercontent.com/4991925/159470243-bf137f7e-5cfb-4e44-ae7e-81068ff0af61.png)
Actual verbatim source is "© Muséum National d'Histoire Naturelle (MNHN), photo: Martina Pocco"

**Comment by mjy** [comment]
TODO: 
* [ ] add `extend[]=citations` on `/images.json`, we don't need this for single image display as we can get it with `extend[]=origin_citation` instead.  Update the Vue imageViewer code to reflect this request change
* [ ] add `extend[]=citations` on `/api/v1/images.json`
* [ ] ensure the change in /citations/_attributes extended `source`  from source_author_year to full citation display doesn't impact display in other places
* [ ] Update Source to sanitize title (and cached) with sanitize(source.cached, tags: ['i']) on write, so we don't have to do this on display

**Comment by mjy** [comment]
Branch was not merged.
