### ISSUE TITLE
Task - Uniquify People - minor QoL improvments

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2858]
A number of small changes based on discussion from @debpaul's walkthrough:

  * [x] Provide a breakdown counts by roles for display in select person (likley requires an update to metadata)
  * [x] On entry from another page, e.g. with `person_id=4320` then Used/Roles in Selected person are not set properly
  * After clicking merge
       * [x] Refresh metadata on Selected (middle column)
       * [x] Refresh metadata on Selected (left column)
  * In "Selected Roles"
    * [x] Make each role clickable to show the data behind it via modal
    * [x] or ... Group Identical Role types, and show all values when one type is selected
  * [x] Ensure that Match roles are updated when match person is selected (they might not be appearing correctly)
  * [x] Ensure that Selected Annotations are unique (something felt wrong with the list, there were too many of them)
  * [ ] Consider Adding tab buttons so that you can toggle columns, in the same space, between Roles, and Attributes

**Comment by proceps** [comment]
Change the Search buttons to:
1. Search (Selected person)
2. Serach (Match people)

**Comment by jlpereira** [comment]
Done
