### ISSUE TITLE
Darwin Core Importer - numerous people created on import

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2859]
Do not create New Person, if a person with the same name already exists in the DB (or at least in the scope of the same DwCArchive dataset).

**Comment by debpaul** [comment]
To a dwc Archive, can Tommy add dwc:identifiedById? (set equal to his ORCID)? Same for dwc:recordedById (for the person collecting the specimen)? (Multiple people can be associated with the collecting of a given specimen. So not sure how that would work for upload. Might slow down import)?

**Comment by proceps** [comment]
ORCID does not present on the specimen labels. It could be assigned to each person, if recorded directly in TW, than you will get the maximum level of accuracy

**Comment by LocoDelAssembly** [comment]
It is supposed to not create the same people twice for a given dataset. Do you have examples of this not happening and the importing being creating the same person over and over for the same dataset? Even an origin relationship is created.

**Comment by proceps** [comment]
I thought about it, may be this is just old data, we was playing with one of the sandboxes today morning.

**Comment by proceps** [comment]
We was using McElrath as an example, but when I checked production, there are only 3-4 people, this is more legitimate, compared to several hundred of records in the sandbox. Please close the issue, if this is not the case.

**Comment by debpaul** [comment]
@LocoDelAssembly we need to rope in @tmcelrath. I'm looking at data in sandworm for the INHS Insect Collection (not INHS Insect Collection on Production). So I'm not certain about the origins of the many duplications of Tc McElrath.

**Comment by LocoDelAssembly** [comment]
identifiedById and recordedById are not currently supported, only their verbatim counterparts.

**Comment by debpaul** [comment]
> identifiedById and recordedById are not currently supported, only their verbatim counterparts.

@LocoDelAssembly I'll make an enhancement pull request :-) we need to enable this ...

**Comment by LocoDelAssembly** [comment]
Let me know when you do, have something in clipboard to paste, but would be better a separate issue for this, or re-open an older one: https://github.com/SpeciesFileGroup/taxonworks/issues/2025

**Comment by mjy** [comment]
Remember that the sandboxes contain many old experiments.  Confirming before we hunt ghosts will help focus our development efforts.

**Comment by proceps** [comment]
close for now
