### ISSUE TITLE
Error generated trying to access list of projects

### ISSUE THREAD

**Issue by mikemaehr** [SpeciesFileGroup/taxonworks#286]
Trying to access the list of projects available gives an error message. In the sandbox, from the projects page (http://sandbox.speciesfile.org/projects), clicking on the 'list' link gives an error message.

**Comment by mjy** [comment]
Automated tests caught it too, yay!

**Comment by mjy** [comment]
@jlpereira Problem is re-use of table that auto adds right-click -> pin option.  We need to be able to disable that in specific cases like projects->list with a data-attribute or configuration option.  Suggestions?

**Comment by jlpereira** [comment]
Yes, checking if the object has the method pinned?, that should works.

**Comment by mjy** [comment]
Closed for #286.
