### ISSUE TITLE
Up and down t for staged images

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#2863]
### Feature or enhancement

Could you create up/down and perhaps left t staged image pattern?

### Location

https://sfg.taxonworks.org/tasks/images/new_image/index

### Screenshot, napkin sketch of interface, or conceptual description

<img width="433" alt="Screen Shot 2022-03-25 at 2 05 17 PM" src="https://user-images.githubusercontent.com/9273125/160177029-38ae7c46-5cf6-45b6-90dc-1ae650c374a6.png">
<img width="434" alt="Screen Shot 2022-03-25 at 2 05 09 PM" src="https://user-images.githubusercontent.com/9273125/160177030-b8a9a75c-b27e-4029-835c-931dd73bc2b5.png">

### Your role

Collections manager / digitization projects

**Comment by mjy** [comment]
Thanks @teleaslamellatus.  Definitely possible. Keep poking us.

**Comment by teleaslamellatus** [comment]
Thanks! And what should I do in terms of getting this done? I mean the proposed stage versions to be added?

Thanks!

**Comment by mjy** [comment]
@teleaslamellatus thanks for the prompt. You need not supply anything more. More details coming to you in person.

**Comment by teleaslamellatus** [comment]
Nice~! But somehow, Taxonworks, seemingly, started to rotate images that are not right but top T accurately...so perhaps that is not an issue anymore? I mean to preselect template? Nice profile photo, very professional

**Comment by mjy** [comment]
> rotate images

I be these are iPhone, correct?  If so there is something new with the image metadata that stores rotation different in thumb and upload.  I think we discussed this in another issue.

**Comment by mjy** [comment]
@jlpereira we need two new select options for the staged images in new image task:
  * `T`, looks like first image above and
  * `Inverted T`, the second image above

On 2863 branch.

**Comment by mjy** [comment]
`0.7.0` sqed on this branch has the processing added.

**Comment by mjy** [comment]
@teleaslamellatus this is live now on sfg.
