### ISSUE TITLE
Task - observation matrix dashboard - add OTU to a matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2873]
Does not work.
OTU apparently added to the matrix, but matrix does not open.
If I add OTU second time, I get an error message that the OTU is already in the matrix, but matrix does not ope.

**Comment by proceps** [comment]
If the OTU already in the marix and has images, it apparently works fine, but for new OTU it fails.

**Comment by mjy** [comment]
@proceps Please outline the exact steps, what/how does it mean to "open the matrix"?  In what view/task.  I'm not seeing raises in the emails other than for image matrix, is this what you mean?

**Comment by mjy** [comment]
@proceps Sandbox, production?

**Comment by mjy** [comment]
In basic samples I can not replicate.
