### ISSUE TITLE
Task - uniquify people

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#288]
```
when I have a big list of people
   then I want to make assertions that some people are the same
```

```
when I see a Persons attributes
  then I see attributes by proxy 
     including taxon_name#verbatim_author linked through taxon_name#taxon_name_authors
       this will help me use a verbatim value as an AlternateValue
```

**Comment by mjy** [comment]
Create methods to predict that a person is: 

* [ ] `#similar`
* [ ] `#identical`

Consider defining the response to `similar` as containing `:reasons`.

**Comment by TuckerJD** [comment]
What are the criteria for the rubric of  'similar' (in no particular order)?

- Last names are more important than first names?

- what is the precedence of Suffix/Prefix issues?

- How important are roles (At the moment, only the TaxonNameAuthor role is accounted for in 'identical'. Are other roles to be included, and if so, how?)?

- Vetted/Unvetted is ignored.
