### ISSUE TITLE
[Bug]: Uniquify check mark select all missing and merge count issue

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2892]
### Steps to reproduce the bug

```bash
1. Logged in to sandwich > INHS Insect Collection
2. Task Uniquify > Select McElrath, Thomas (who has 19 objects for "Used")
3. Match People > try to select all the McElrath, Tc but there's no check box anymore to "select all" or "select some"
4. Selected one, and then repeated to select another and clicked to "merge people."
5. I expected the count after merge to be 21, but it was 20.
...
```
### Screenshot
See below
### Expected behavior

When I do "Match People" I need to be able to select "n" of the hits. The Select All option is also gone.

When I Merge People, I expect the "Used" count to go up by "n" (equal to the number of instances of Tommy selected).

### Additional Screenshots

![Uniquify1](https://user-images.githubusercontent.com/2990155/162228604-075e38bd-8158-4817-b918-28e93671159a.PNG)
![Uniquify2](https://user-images.githubusercontent.com/2990155/162228608-f6f8b774-e94f-4b45-94d7-a4a9f3d2f5f0.PNG)
![Uniquify3](https://user-images.githubusercontent.com/2990155/162228610-5625d3d5-a971-4752-859a-74b044c324f0.PNG)
![Uniquify4](https://user-images.githubusercontent.com/2990155/162228600-e7ec362c-fe2e-4591-ba21-8070ffbedee2.PNG)
![Uniquify5](https://user-images.githubusercontent.com/2990155/162228602-97a3bdbf-0680-4dfd-804a-ddb7015283c4.PNG)

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [x] Sandbox
- [ ] Production

### Sandbox Used

sandwich

### Version

199bbc709 on 2022-04-07T02:05:31Z

### Browser Used

firefox

**Comment by jlpereira** [comment]
@debpaul select option is there. It's the first checkbox in the header of the match people table. The autocomplete doesn't have a functionality to select all the items in list, for that use I think the user should use the filter. Are you sure you're not selecting the same person in the match list? maybe that's the reason why the counter is 20 and not 21. I have to check this and if this is the case, prevent add the same person to the match people list

**Comment by debpaul** [comment]
@jlpereira perhaps still user error? I can only select one person at a time ... even though many show up i the list.

**Comment by debpaul** [comment]
> . Are you sure you're not selecting the same person in the match list? maybe that's the reason why the counter is 20 and not 21.

These were definitely two different "people" see the People record identifiers are different for them?
