### ISSUE TITLE
GenBank field to complete

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2895]
### Feature or enhancement

 When specimens published have a GenBank number, 
 then I want to have a field so I can save that information easily. 
 In the Comprehensive specimen digitization task, Collection Object section, under the Catalog number identifier, there could be multiple identifiers to select from and complete the code given in the publication.

### Location

Task- Comprehensive specimen digitization

### Your role

Curator

**Comment by mabecabrera** [comment]
I know we have *Custom attributes* with its predicates, but as those are predicates, this codes can not be entered that way... It would be nice to have a verbatim field for Costum attributes for information like this GenBank codes.

**Comment by mjy** [comment]
@mabecabrera this exists as a Global identifier in Annotator->Identifiers.   Please re-open if missunderstood.

Do be careful with the semantics.  An identifier is not the same as a link.  Ensure that the identifier coming from Genbank is for a Specimen object, not a Sequence object.

<img width="1421" alt="Screen Shot 2022-04-08 at 12 32 48 PM" src="https://user-images.githubusercontent.com/22600/162492771-201cb1ac-d9e8-4b00-b477-bae9686be23d.png">

**Comment by jlpereira** [comment]
@mjy I think that @mabecabrera has changed the subject of this issue. She's asking if we can add multiple identifiers in comprehensive task to allow the user add more identifiers like gen bank accession code and not only catalog number

**Comment by mabecabrera** [comment]
From the issue #2904, and adding to this one, I think we have to think the best way to see the multiple identifiers from each collection object on the Comprehensive task. 

When a collection object has more than one identifiers:
![image](https://user-images.githubusercontent.com/63611746/164069997-357046f0-4447-43cd-83df-a931a7d43f40.png)


Then the DwC representation looks like this:
![image](https://user-images.githubusercontent.com/63611746/164069676-97c39619-952b-4c74-91ad-ec8bc5d99100.png)
PERFECT

The last identifier entered is the current one and the one in the identification. That is correct. But I think it is confusing to understand the Collection Object section in the Comprehensive Task with another identifier in the Catalog Number field and 
![image](https://user-images.githubusercontent.com/63611746/164069481-bd75a0b8-2f53-45cc-80d8-954b2af9ab69.png)

I think that if we could see the multiple identifiers together in the Collection Object Section. Maybe an Identifiers space including Catalog Number and other identifiers as the GenBank Code.
Similar to this view that includes all of them. 
![image](https://user-images.githubusercontent.com/63611746/164071435-c7204c69-6cca-40f4-83a0-f1c61345cdb1.png)
And the one in the top should be the current one.
