### ISSUE TITLE
[Bug]: no determination appears for new Collection Object until after refresh

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2899]
### Steps to reproduce the bug

```bash
Working with @tmcelrath in INHS Ent Collection testing

1.After adding a taxon name, Add Collection Object
2.The Determination is selected, but doesn't appear in the display header as expected until after refresh.
...
```

### Screenshot

![DeterminationNotAppearingUntilPageRefresh_Comprehensive_Pcoloradensis_INHSENT_prod](https://user-images.githubusercontent.com/2990155/163057853-30e62740-481e-4c70-803c-3f655f81a504.PNG)

### Expected behavior

Expecting the determination to show up in the display without using "refresh" method. @tmcelrath can add more information about expected behavior if you need more information @jlpereira 

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Version

INHS ENT Collection

### Browser Used

firefox

**Comment by mjy** [comment]
@debpaul you must save the record first.

**Comment by debpaul** [comment]
@mjy I think we did? Will re-test.

**Comment by tmcelrath** [comment]
We did save. Does not show up until either a second save or a refresh.

**Comment by jlpereira** [comment]
I can't replicate it. Please provide more detailed steps

**Comment by tmcelrath** [comment]
Specifically _at the top of the page_. Steps:
1) I go to comprehensive
2) I add a determination (with OTU, collector, year, or any combo)
3) I save.
4) The determination does not show up at top of page until I save twice or I refresh page.

**Comment by jlpereira** [comment]
I can't replicate it. Does it always happen with all collection objects you're creating? It could be a unique case. Maybe something didn't save properly and the form didn't fill out correctly. Can you provide a link with an example case?

**Comment by tmcelrath** [comment]
Happens everytime I do this: Replicated just now:
![image](https://user-images.githubusercontent.com/11411328/163823226-42edd123-2ff8-4421-b4aa-65d939b5371c.png)

**Comment by tmcelrath** [comment]
I refresh and it turns to this:
![image](https://user-images.githubusercontent.com/11411328/163823323-237ccbbb-6a41-44ff-956a-8e581a346808.png)

**Comment by tmcelrath** [comment]
Same with using save once, then twice.

**Comment by jlpereira** [comment]
Thanks, I see now.
This happens because we save first the collection object and then the determations. I will see if I can compose the label from the client side
