### ISSUE TITLE
[Bug]: verbatim lat/long and uncertainty aren't verbatim in Comprehensive Specimen

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2900]
### Steps to reproduce the bug

```bash
1.Using Parse of verbatim to fill verbatim fields for a Collecting Event inside Comprehensive Specimen 
2."N" and "W" appear (not present in verbatim)
3. "10" meters uncertainty appears (not present in verbatim)
...
```

### Screenshot

![WhereDidUncertaintyComeFrom](https://user-images.githubusercontent.com/2990155/163058530-16176d34-7e61-45d5-81a0-99a79a43c690.png)

### Expected behavior

Test to ensure verbatim is ... verbatim.
Or explain to those entering data why these are appearing?

@tmcelrath can provide more information as well

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [ ] Sandbox
- [X] Production

### Version

INHS ENT Collection

### Browser Used

firefox

**Comment by tmcelrath** [comment]
Actual issue is that we can’t enter coordinates verbatim. Eg the coordinates in this case were written aith an extra ° symbol at the end but were not parseable. So we had to delete it to get it to “work” even though on the verbatim label there is an extra degree symbol.

**Comment by proceps** [comment]
The pattern recognition could not be 100% error proof. There are hundreds different way the coordinates could be entered to the label fields. Some of the coordinates are not recognized, some recognized with error. The good rule is to validate the verbatim rules, the same applies to the date recognition. I am not sure about the uncertanty value, this is definitely not comming throug the recognition.

**Comment by proceps** [comment]
I will check on N and W characters.

**Comment by proceps** [comment]
I just created new collecting event, everything is parsed correctly. Not N, W signes, not precision. The data presented at the top are probably comming from initial INHS insect collection migration. This is the way the data were originally stored in the FM database. The same with the error radius. Please reopen if you still find an issue.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/163185492-c37fedfc-c2ed-4f38-ab5f-f1822e3af82c.png)
