### ISSUE TITLE
DwC Export - ensure complete export of `otherCatalogNumbers`  [Was: Where do I enter otherCatalogNumber DwC field in TW?]

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#2904]
### Feature or enhancement

I want to enter a previous local catalogNumber. I do not want to create a new Namespace for it because I only have two letters and I do not know the origin of that collection this specimen came from. I just do not want to lose this identifier. 
![image](https://user-images.githubusercontent.com/63611746/163281795-704bd399-b154-4e96-b263-547e8fa9f5c3.png)
In DwC I could save it in the otherCatalogueNumber column.  In TW I would need a verbatim field to enter this kind of identifiers. 

Also when I go to Identifiers in the annotator and create a new Local identifier as a Catalog Number, the Darwin Core representation shows that the Other Catalog Number is the same value as the catalogNumber field. 

![image](https://user-images.githubusercontent.com/63611746/163282514-3b2b16bd-fcbc-4d05-a683-bd5956ff98c3.png)

![image](https://user-images.githubusercontent.com/63611746/163282449-ae372914-8c38-4b3b-8353-1020af54e7b6.png)

![image](https://user-images.githubusercontent.com/63611746/163282554-dfdc292a-a939-4b1a-947b-99bce1022452.png)

So, how can we address the otherCatalogNumber info in TW?

### Location

Comprehensive specimen digitization

### Your role

Curator

**Comment by mjy** [comment]
> I do not want to create a new Namespace for it because I only have two letters and I do not know the origin of that collection this specimen came from

This is the beauty of the Identifiers, you don't have to know the origin of the collection since they reference *Namespaces*, not Collections. The solution is to create a new namespace, and document where you're you found in the system.

I.e. I don't believe this is an issue.  Create a new Namespace, and the `otherCatalogNumbers` should be populated (I think, please test).

**Comment by mabecabrera** [comment]
Ok! Yes, I was told to make a ticket and I was not sure if an Issue was the same. 
I understand that we can create as many namespaces as needed and can work with that. 

otherCatalogNumbers is not being populated with anything but the first catalogNumber entered in the Collection Object section.  If I only enter one catalog number the otherCatalogNumbers is not present in the Darwin Core representation.
But when I create a second catalog number it is present in the DwC representation but as shown in the third screenshot, repeats the first catalog number value.

**Comment by proceps** [comment]
For random identifiers, I just create identifier as "Unknown" origin, and do not create the namespace.

**Comment by debpaul** [comment]
> For random identifiers, I just create identifier as "Unknown" origin, and do not create the namespace.

@proceps if you do this "Unknown" does it map to dwc:otherCatalogNumbers on export? or is it lost to those outside your TW Project?

**Comment by LocoDelAssembly** [comment]
Problem seems to be that either, identifier position is `nil` or there are several with the same position. In comprehensive, when creating the second identifier via radial, it still assigns position 1. Perhaps would be best to just subtract `catalogNumber` from the array before building the pipe-separated string?

**Comment by mjy** [comment]
Position is handled in the model (acts_as_list), it should never be submitted as a param unless re-ordering.  We may have to re-run the indexing.

**Comment by LocoDelAssembly** [comment]
```ruby
  # @return [Identifier::Local::CatalogNumber, nil]
  #   the first (position) catalog number for this collection object, either on specimen, or container
  def preferred_catalog_number
    if i = Identifier::Local::CatalogNumber.where(identifier_object: self).first
      i
    else
      if container
        container.identifiers.where(identifiers: {type: 'Identifier::Local::CatalogNumber'}).first
      else
        nil
      end
    end
  end
```
Neither branch is taking position into account so in practice you get the first catalog number ever created for the CO but on exporting `otherCatalogueNumbers` position is taken into account. When a new identifier is created it takes position 1 and the existing ones are shifted.

Would be correct to change this method to return first by position? Probably need statistics to see how many COs would change their preferred catalog number by this change.

PS: Just in case, `.first` is not extended by `acts_as_list`:
```ruby
3.0.2 :033 > Identifier.last.identifier_object.identifiers.first.first?
  Identifier Load (0.3ms)  SELECT "identifiers".* FROM "identifiers" ORDER BY "identifiers"."id" DESC LIMIT $1  [["LIMIT", 1]]
  CollectionObject Load (0.1ms)  SELECT "collection_objects".* FROM "collection_objects" WHERE "collection_objects"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Identifier Load (0.3ms)  SELECT "identifiers".* FROM "identifiers" WHERE "identifiers"."identifier_object_id" = $1 AND "identifiers"."identifier_object_type" = $2 ORDER BY "identifiers"."id" ASC LIMIT $3  [["identifier_object_id", 1], ["identifier_object_type", "CollectionObject"], ["LIMIT", 1]]
  Identifier Exists? (0.2ms)  SELECT 1 AS one FROM "identifiers" WHERE "identifiers"."project_id" = $1 AND "identifiers"."identifier_object_type" = $2 AND "identifiers"."identifier_object_id" = $3 AND ("identifiers"."position" <= 3) AND ("identifiers".id != 1641) LIMIT $4  [["project_id", 2], ["identifier_object_type", "CollectionObject"], ["identifier_object_id", 1], ["LIMIT", 1]]
 => false 
3.0.2 :034 > Identifier.last.identifier_object.identifiers.last.first?
  Identifier Load (0.3ms)  SELECT "identifiers".* FROM "identifiers" ORDER BY "identifiers"."id" DESC LIMIT $1  [["LIMIT", 1]]
  CollectionObject Load (0.2ms)  SELECT "collection_objects".* FROM "collection_objects" WHERE "collection_objects"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Identifier Load (0.2ms)  SELECT "identifiers".* FROM "identifiers" WHERE "identifiers"."identifier_object_id" = $1 AND "identifiers"."identifier_object_type" = $2 ORDER BY "identifiers"."id" DESC LIMIT $3  [["identifier_object_id", 1], ["identifier_object_type", "CollectionObject"], ["LIMIT", 1]]
  Identifier Exists? (0.2ms)  SELECT 1 AS one FROM "identifiers" WHERE "identifiers"."project_id" = $1 AND "identifiers"."identifier_object_type" = $2 AND "identifiers"."identifier_object_id" = $3 AND ("identifiers"."position" <= 1) AND ("identifiers".id != 4942) LIMIT $4  [["project_id", 2], ["identifier_object_type", "CollectionObject"], ["identifier_object_id", 1], ["LIMIT", 1]]
 => true 
```

**Comment by LocoDelAssembly** [comment]
39 INHS Insect Collection COs would be affected in production if `preferred_catalog_number` is updated with proposed change.

**Comment by mjy** [comment]
> Would be correct to change this method to return first by position? 

Yes!  This is an oversight.  We need to add `order(:position)`.

**Comment by mabecabrera** [comment]
I just created a new collection object with a namespace and identifier that I entered in the main Comprehensive task [ZMH64610 (TI)]. Then went to the identifiers to add a second one [(TI)].

![image](https://user-images.githubusercontent.com/63611746/164012532-900cfbf8-5a22-4448-86d5-16c36e577c10.png)

Now in the DwC representation of Browse Collection Object the second identifier I added figures as the **_catalogNumber_** and the one I entered in the Comprehensive task main screen figures as the **_otherCatalogNumber_**...

Is there anyway to choose which one is the current one? If not I would prefer that the ones added from the Identifiers in the Annotator were the OTHERS...
