### ISSUE TITLE
Comprehensive specimen digitization search types (nomenclature)

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#2907]
### Feature or enhancement

Currently with the search bar in Comprehensive specimen digitization, you can search by catalogue number or taxonomic determination (OTU).  It would be useful to also be able to search in this task based on the taxonomic name of the type designation.

Or another option might be: since the act of designating a type is like making an identification on the specimen, create a button to automatically create an identification to the nominate OTU for the taxon name from the type designation. 

### Location

Task - comprehensive specimen digitization

### Your role

researcher in small taxonomy-focused lab group

**Comment by proceps** [comment]
I like the second option, a button to create identification from the type. When ussing the Quick type task, the type is not created. I think, I will implement this as a soft validation fix.

**Comment by mjy** [comment]
We used to have automation to automatically add the Determination when incoming from type I believe. @jlpereira perhaps you can look into this.

**Comment by jlpereira** [comment]
> We used to have automation to automatically add the Determination when incoming from type I believe. @jlpereira perhaps you can look into this.

What kind of automation you mean? create a determination or just load it? When you open a type material in comprehensive from New type material task, It should load the determinations.

**Comment by mjy** [comment]
when I open comprehensive from a type,
then if a determination does not exist for the type taxon name
then an unsaved determination is stubbed

**Comment by jlpereira** [comment]
We have something there to automatically set the OTU name for the determination. I realized we only pass that param from New taxon name task and not from New type specimen. I will add it there too.
