### ISSUE TITLE
New task - stepwise determination bulk parser

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2911]
### Feature or enhancement

As a curator, I want a task that gives me a chosable list of all the strings in “buffered determinations” on collection objects that DONT have an added OTU in my project. 

E.g. 
1) Monotoma picipes det TC McElrath 2020 (1050 collection objects) 
2) Monotoma picipes det TC McElrath 2021 (300 collection objects)
3) Apis mellifera (147 collection objects) 
Etc ….

Then, I want to select a string, and be able to bulk assign a determination to all those collection objects instead of doing it one by one. 

Future improvements could suggest the determinations for me (eg parse the scientific name/OTU, determiner, and date) and suggest it. 

### Location

New task

### Your role

Collection manager

**Comment by mjy** [comment]
Endpoints:

* Get groups of unique labels: `http://127.0.0.1:3000/tasks/collection_objects/stepwise/determinations?count_cutoff=100&page=1&per=10`
* Pass the label selected to get the list of CollectionObjects (experimental (use below for actuall code until we need different or more precise response) `http://127.0.0.1:3000/tasks/collection_objects/stepwise/determinations/expand?buffered_determinations=Dermacentor%20albipictus `
*`/collection_objects?buffered_determinations=Dermacentor%20albipictus`
* Add determinations to CollectionObjects (use the comprehensive CO form): PATCH `/collection_objects`

**Comment by mjy** [comment]
* [ ] Add button on each CO row that you can click to show thumbnails of the determination 
* [ ] Move the Count  column to be the leftmost, i.e. left of the 'Set' button, so it's closer to the action.
* [ ] Add a second icon, beside the image thum icone,  a magnifying class icon modal that let's you inspect the attributes (`/collection_objects/123/extend[]=dwc_fields`) of any one CO, in that list. I want to say we created this already.
* [ ] (not checked!)- when you add determinations, if you are addding > 5, then have a word type confirmation to add.
* [ ] After adding success, decrement the Count in the row label (if possible, maybe just reload that page/component)
* [ ] "Last" - "Add" button on dtermination form should be blue, not green.
