### ISSUE TITLE
Task - View Observation matrix - CSV file download.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2912]
Saad reported, that he wants to see full OTU names in the downloaded file, not abbreviated names. CSV file should not have the same restrictions as Nexus file.

**Comment by mjy** [comment]
@proceps what character should I substitute for comma (,) in the OTU name?  There are many with (author,year).  Right now I have pipe, '|'.

**Comment by mjy** [comment]
@proceps never mind question above-  using quotes and substituting double quotes out.
