### ISSUE TITLE
[Bug]: Cannot set Determiner of CO to department/organization

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2915]
### Steps to reproduce the bug

```bash
1. Create an organization
2. Open the comprehensive editor task
3. Type in the name of an organization in the Determiner text box, it doesn't show up as a suggestion
```

### Expected behavior

I expect to be able to select an organization from the list of matching names once I type something in.

### Environment

- [ ] Development (native)
- [ ] Development (docker)
- [X] Sandbox
- [ ] Production

### Sandbox Used

sandwich

### Version

830d73e0d

### Browser Used

brave (chromium)

**Comment by debpaul** [comment]
Solution is toggle role selector between people and organizations  (per discussion at Open session on 20 April 2022).
