### ISSUE TITLE
[Enhancement] Copy identifiers from Filter CO task for Match Collection Objects task

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2917]
### Feature or enhancement

When I use the filter CO task to get a list of collection objects and want to make a batch change, I would like a faster way to get the identifiers into the Match CO task than:

1. Downloading the CSV
2. Opening the CSV in Excel and copying the column
3. Pasting it into the Match CO text box

A `Copy Identifiers` button next to `Download CSV` & `Reindex DwC` would be perfect.

### Location

Filter CO

**Comment by mjy** [comment]
We should also accept CollectionObject filter params as a way to initialize the match, we could insert the identifiers into the text box, and execute the search.  This would let us follow the planned pattern that we want to develop "Send this filter result to ..." for all filters.  That will come either in the arrow (nav) icon or a new "filter sending" radial.
