### ISSUE TITLE
[Feature] Search by DataAttribute/Predicate in Filter CE task

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2922]
### Feature or enhancement

Related to #2350 and #1633, the antweb project needs to search for collecting events with our custom predicates, like "BiogeographicRegion". 

### Location

Filter Collecting Events task

### Screenshot, napkin sketch of interface, or conceptual description

The custom predicate fields should be included in the existing "attributes" drop down list, next to items like `verbatim_collectors`, `verbatim_habitat`, etc. (Maybe with a divider between regular and custom predicates?)

**Comment by mjy** [comment]
Completed in 0.28.0.
