### ISSUE TITLE
Need to be able to search by "Preparation = None"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2937]
### Feature or enhancement

When I am in Filter Collection Objects, there is no way to search for objects that have a preparation of "None"
See:
![image](https://user-images.githubusercontent.com/11411328/164557256-30482633-c647-4d26-b878-9d05e205b12b.png)

This should be added, either in the above box or in the area below where you can choose "With" or "Without" things. 

### Location

Filter Collection Objects

### Your role

Collection manager

**Comment by jlpereira** [comment]
@tmcelrath New [both/with/without] facet for this. You will see it on the next update

**Comment by tmcelrath** [comment]
Needs re-opened - currently can only search by "with" - "without" returns all COs.
