### ISSUE TITLE
Cannot create new project

### ISSUE THREAD

**Issue by mbeckman** [SpeciesFileGroup/taxonworks#294]
When saving new project, error occurs because root taxon name violates constraint:

ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "cached_html" violates not-null constraint
DETAIL:  Failing row contains (4, Root, null, null, null, null, 2017-12-12 17:41:40.427564, 2017-12-12 17:41:40.427564, null, null, NomenclaturalRank, Protonym, 1, 1, 4, null, null, null, null, null, null, null, null, null, null, null, null, null).
: INSERT INTO "taxon_names" ("name", "created_at", "updated_at", "rank_class", "type", "created_by_id", "updated_by_id", "project_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"

Project itself is validated without errors.

**Comment by mjy** [comment]
Use `without_root_taxon_name: true` as param in Project.new as a work
around.

**Comment by proceps** [comment]
I tried, and it did not work. It gives less precise error message. Like name is nil. And I do not know which name it is. the project name is not nil.

**Comment by mjy** [comment]
@proceps can you add a unit test that fails/describes the behaviour?  Do it
in /models/project_spec.rb.
