### ISSUE TITLE
[Bug]: Determination lock not working for "Add to container"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2943]
### Steps to reproduce the bug

```bash
1. When I am on a collection object with an added determination
2. Then lock all fields
3. Then I click "Add to Container"
4. Then I do not see the determination to be added to the containerized collection object.
```

### Screenshot

Before clicking "Add to container"
![image](https://user-images.githubusercontent.com/11411328/165145063-37054e36-affa-45a7-8241-07f3b1237bca.png)

After clicking "Add to container"
![image](https://user-images.githubusercontent.com/11411328/165145177-eec79525-855d-4a2f-9fcf-f06a35f4936a.png)

### Expected behavior

The determination lock should work and transfer to next specimen.

### Environment

Production

### Version

0.24.2

### Browser Used

Chrome

**Comment by tmcelrath** [comment]
Reopen - determiner and potentially date not carried over. Currently at least determiner does not carry over even if included in determination.

**Comment by jlpereira** [comment]
@tmcelrath I can't replicate this. I added a determination and locked the list, then I saved the collection object and pressed "Add to container" button. It created a new CO with the taxon determination already added on the list

**Comment by tmcelrath** [comment]
With a determiner or not? The issue is that the determiner doesn't carry over properly.

**Comment by jlpereira** [comment]
Yes, the determiner too. Everything in the list seems to be copied correctly. Can you provide the detailed steps to replicate?

**Comment by tmcelrath** [comment]
Pre-"Save and New"
![image](https://user-images.githubusercontent.com/11411328/168374528-9bfa2c15-d8fc-4a2b-9dd7-3ce052e9ea33.png)
![image](https://user-images.githubusercontent.com/11411328/168374621-13deda26-ff42-44f0-a571-2ec7d87a0687.png)

After "Save and New" (pre-save)
![image](https://user-images.githubusercontent.com/11411328/168374693-928ded69-887c-48a3-831c-4aeecde67c2a.png)

After "Save and New (after save)
![image](https://user-images.githubusercontent.com/11411328/168374776-25443cc1-4846-4762-b47b-1b6083ef911c.png)

As you can see, for some reason the determiner is dropped out.

**Comment by jlpereira** [comment]
Ok, I will try to replicate it again
