### ISSUE TITLE
[Bug]: Browse CO Det string appears twice

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2947]
### Steps to reproduce the bug

```bash
Scenario: @tmcelrath and I curating INHS ENT records on Production with biocuration issues (e.g. female,male in dwc:sex on export).

1.Browse to a given CO
2.See the "determined" row
3.In the "Object" column, for that Determination, the person who did the "det" shows up twice. (See screenshot)
4.See example https://sfg.taxonworks.org/tasks/collection_objects/browse?utf8=%E2%9C%93&collection_object_id=&%5Bcollection_object_id%5D=1129907
5.I have seen this in other records.
```

### Screenshot

![WhyDetPersonTwiceOnCOShow](https://user-images.githubusercontent.com/2990155/165369562-385de007-0fef-4d19-800a-102233c23141.PNG)

### Expected behavior

I'm not really sure what I should expect.

Is it there twice for a reason?
Could it be that it's both buffered and parsed showing up in the call to the UI?
If that's true, it could be kind of nifty as a data quality check making it easy to compare the literal string with the parsed value.

If it's not there for a reason, I think I'd expect the "linked" part to remain (e.g. https://sfg.taxonworks.org/otus/215676) and the string to go away.

### Environment

Production

### Version

 v0.24.2

### Browser Used

firefox

**Comment by proceps** [comment]
This is display issue, the data seems to be correct.
