### ISSUE TITLE
[Bug]: Mystery of Origin for "Pupa" value in Biocuration for a Collection Object

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#2948]
### Steps to reproduce the bug

```bash
Scenario: @tmcelrath and I curating INHS ENT records on Production with biocuration issues (e.g. female,male in dwc:sex on export).

1.Editing the Biocuration data for INHS Insect Collection 139107
2.Noted the record said "Pupa"
3.After we did the biocuration, we now see Pupa and Pupae
4.But @tmcelrath notes **we need to know where Pupa comes from** (and delete it?) We couldn't figure out its origin. He can provide more information if needed.

See "Pupa" in the history https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=334042 -- note the export is now correct for this object
See both "Pupa" and "Pupae" in history https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=1339146 -- note the export is now correct for this object.
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/165371746-44e79794-a60a-4868-8167-ca8367fb3d82.png)

### Expected behavior

I'm not sure this is a bug? Maybe it was a value from some data import? The question is where did it come from?

### Environment

Production

### Version

v0.24.2

### Browser Used

firefox

**Comment by mjy** [comment]
Pupa is almost certainly not added to the biocuration group that is used to display choices in Comprehensive.  Check to see that the group includes Pupa.

**Comment by proceps** [comment]
There are two biocuration classes in the DB:
*Pupa*: https://sfg.taxonworks.org/controlled_vocabulary_terms/518 (comming from the original migration, with thousands of associated records)
*Pupae*: https://sfg.taxonworks.org/controlled_vocabulary_terms/178 (created by Michele, with about a hundred of associated records).

**Comment by proceps** [comment]
please reload the page https://sfg.taxonworks.org/tasks/accessions/comprehensive?collection_object_id=1339146
You can see that both Pupa and Pupae are selected for the record. One of the biocuration classes was made invisible. Most likely, you would like to find all specimen records for Pupae, and manually reassigne those to Pupa. After that, you can delete one of the biocuration classes. And rename the other of if needed.

**Comment by debpaul** [comment]
@tmcelrath please note the above comments. 
- Based on our discussions today, you preferred Pupae not Pupa, yes? 
- Also note strategy suggested by @proceps. I leave it up to you Tommy to get these represented as you wish. 
- And, Tommy, does this make sense now for how Pupa came to be?

**Comment by debpaul** [comment]
> Pupa is almost certainly not added to the biocuration group that is used to display choices in Comprehensive. Check to see that the group includes Pupa.

@mjy I see this in Manage Biocuration 
![image](https://user-images.githubusercontent.com/2990155/165386489-5d68e188-e32e-4ef2-ab56-17e4fd8fdd5b.png)

**Comment by proceps** [comment]
I added it when experimented with related records.

**Comment by tmcelrath** [comment]
I have updated the terms to make it so that "Pupa(e)" is the "Correct" term. I will do like Dmitry suggested and remove all Pupa [Deprecated] Biocurations and transition to "Pupa(e)".

**Comment by tmcelrath** [comment]
Pupae [Deprecated] has been deleted. Issue can be closed, mystery solved.
