### ISSUE TITLE
Task - Filter Collecting event - House keeping returns too many records, the date filter is not set properly

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2957]
When I searched the collecting event within one month range. I got about 45,000 records, it should be only a few.

**Comment by mjy** [comment]
Screenshot?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/166165330-7f5a21d8-84f4-4cd1-841f-3582382e7c29.png)
