### ISSUE TITLE
task - Edit Taxon Name - new species button is lost

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2961]
The button to create a new species as a type of a genus is not visible any more
![image](https://user-images.githubusercontent.com/5597748/166391909-92421976-8cfa-4249-bf71-8b4daf488f0f.png)

**Comment by jlpereira** [comment]
Tried on development branch with a genus, seems to works fine. Could you provide more details? link?

**Comment by proceps** [comment]
I create a new genus, when I enter a species name, I expect to see a button create new

**Comment by proceps** [comment]
tried it again, could not replicate, will reopen, if the issue persist.
