### ISSUE TITLE
[Bug]: Problem in the API

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#2962]
### Steps to reproduce the bug

```bash
Until a few months ago, all type-species information of genera was correctly transferred into the API and consequently into my external catalogue wco-lite (https://wcolite.com/).
Suddenly this information became absent from the API. We have searched and it is not there, while for older genera it is working perfectly.
Something happened recently which spoiled this function. I suspect this started to occur in 2022.
Could you check it, please?

I'll give you an example (see figs below):

1) Genus Beloniscus last updated in June 15, 2021 [it works normally]


2) Genus Biungulus entered into the database in May 2, 2022 [it lacks any type-species indication in the API].
```

### Screenshot

![image](https://user-images.githubusercontent.com/46284943/166396051-a48ada02-45b0-42b8-87d3-0b324431d349.png)
![image](https://user-images.githubusercontent.com/46284943/166396084-b067a2e3-f197-45f3-8165-5f5e3767110f.png)

![image](https://user-images.githubusercontent.com/46284943/166395800-1761c54d-525f-4344-90f5-745091f9e451.png)
![image](https://user-images.githubusercontent.com/46284943/166395884-c41fe285-738e-4fe7-9749-54d05778b254.png)

### Expected behavior

I expect recently entered genera to behave like genera entered pre-2022.

### Environment

Production

### Browser Used

chrome

**Comment by mjy** [comment]
@adrik29 Can you list the specific endpoints that you are using?  I expect that the problem is there is a new parameter pattern that we are using that extends, rather than showing by default results.  This lets us better customize and improve the speed of the API.

I.e. Once I understand the list of requests that you are sending, then I can detail how to get the data back.

**Comment by adrik29** [comment]
@mjy -- Ah, I already discovered. It was our mistake in the coding...
