### ISSUE TITLE
[Bug] Previously loaned items can not be loaned once returned

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#2964]
Issue is likely "on_loan?" logic.

**Comment by tmcelrath** [comment]
request hotfix actually - I need to send out a loan and can't add objects to the loan until this is fixed. Need fixed ASAP.

**Comment by tmcelrath** [comment]
To replicate all you should have to do is create two loans with the same objects, but return all the ones from the first loan, then try to add them to the second loan

**Comment by mjy** [comment]
Can't be hotfixed, sorry.
