### ISSUE TITLE
[Bug]: Image Matrix will not save data on the depiction

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2965]
### Steps to reproduce the bug

```bash
Where it says "Label" and "caption" Whatever I type into that space is not saved when I click "Update"
```

### Screenshot

![image](https://user-images.githubusercontent.com/25491000/166515738-a8c0aa10-715f-4a8b-8dc2-54da67eb5694.png)

### Environment

Production

### Browser Used

Chrome

**Comment by mmkohler** [comment]
When will you apply the fix to production?

**Comment by jlpereira** [comment]
Maybe we will do a minor release today. In the meanwhile @mmkohler  I can tell you this issue was a problem with missing information(figure_label and caption) in the server response, but you can be sure that your changes are saved, just you won't see them until the next release.
