### ISSUE TITLE
CO Filter - search by "Notes" field facet

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#2966]
### Feature or enhancement

When I am in the CO Filter
Then I need to search in the "Notes" field.

### Location

CO Filter

### Screenshot, napkin sketch of interface, or conceptual description

![notes_facet](https://user-images.githubusercontent.com/11411328/166713603-60aa8fc2-b7cd-4fdf-b980-fcb1d535e9fb.jpg)

### Your role

Collection manager

**Comment by mjy** [comment]
Also needs With/out Notes facet.
