### ISSUE TITLE
Browse OTUs: Type species should be displayed with the original combination.

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#2968]
### Steps to reproduce the bug

```bash
1.
2.
3. 
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/33158036/166724133-b42bada2-4ef6-4e92-b39e-30ddbf592c09.png)

### Expected behavior

Type species should be displayed with the original genus combination

### Additional Screenshots

![image](https://user-images.githubusercontent.com/33158036/166724298-69370be7-5d84-4197-a1f1-d9f0da256516.png)

### Environment

Sandbox

### Sandbox Used

sandcastle

### Browser Used

chrome

**Comment by proceps** [comment]
Same problem in Edit TaxonName interface. The Browse TaxonName display the relationship correctly.
