### ISSUE TITLE
Task - Global Names Finder - exact match

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2969]
I would like to have an option to filter the names with have / have not exact match to taxon_name.cached and taxon_name.cached_original

**Comment by mjy** [comment]
Are you wanting to differentiate in the various sections as to how the name was found?

**Comment by proceps** [comment]
I would like to get a list of taxonnames in a publication. All names. Names matrich those already in the database. Names found in publication, but not in TW.

**Comment by mjy** [comment]
This already exists. Gnfinder playground.

**Comment by proceps** [comment]
Well. For found names, may be, but for not found names, not that easy. All the lists are mixed with matching and non matching names. See picture for example. 
![image](https://user-images.githubusercontent.com/5597748/169403336-5ffe2075-344f-4d61-9043-4917640059a4.png)
Another example. `Erythroneura vitifix` recognized as present and the reference to the taxon `Erythroneura`. In fact the name is a misspelling, but this misspelling is present in the database. It should be recognized as one. 
![image](https://user-images.githubusercontent.com/5597748/169403745-08ce1f43-a4c0-40dc-9b9c-4082ea6fe377.png)
The label for a recognized name should include the author/year.

Basically, I need tuning on the interface and better filterring options. For example, the search find a lot of names with abbreviate genus. It is useless for me, I need to recognize if the name is present in the database or not. Assuming that each species name is spelled as a binomial name in the publication. I should be able to recognize that there is a new combination or a new misspelling in the paper. I cannot do it with present interface. I basically have to do it one by one, the same way I would do it in browse nomenclature. Create a new citation feature is not much of a help. And actually dangerous. Clicking button, automatically creates combination (without page number). For the page number, I have to search the publication manually. Once the citation is created, I cannot delete it (I can only by going to Browse nomenclature).

For experiment, I used this source in 3i project.
https://sfg.taxonworks.org/tasks/sources/gnfinder?source_id=19123

Well, I am not sure, if it is possible to recognize clean names, but there is a match index. May be if I can set up the filter treshold it could be little bit more informative.

**Comment by proceps** [comment]
May be an OCR text with hiperlinks on the name cold be useful.

**Comment by proceps** [comment]
This is implemented in nomenclature match
