### ISSUE TITLE
[Bug]: Browse annotations for data attributes returns empty column

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#2976]
### Steps to reproduce the bug

```bash
1. Go to browse annotations and select a data attribute that has values
2. Click submit to show the table
3. The object attribute column is always empty, even when it should have data
```

### Screenshot

<img width="839" alt="image" src="https://user-images.githubusercontent.com/33206210/167010670-8497d4c7-839a-4824-b4e4-153bf46eb26c.png">

### Expected behavior

I expect the data attribute to show up in the empty column

### Environment

Sandbox, Development (native)

### Version

f40a4eb38

### Browser Used

brave (chromium)

**Comment by mjy** [comment]
Object attribute is not an attribute of DataAtttribute, it's only present when used in AlternateValues. Because we can append records to the report we include the column here.
