### ISSUE TITLE
Task - project activity - record/minute

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2979]
could we change records/minut to reocrds/hour. It will be more visually informative.
![image](https://user-images.githubusercontent.com/5597748/167204955-6732399d-2c2e-407e-abf2-c712e9340266.png)

**Comment by mjy** [comment]
I disagree.  I want to know the time it takes to do 1 record.  If by hour I have to divide by 60?

**Comment by proceps** [comment]
Well, 5 min/record is also good option. But .203 records/min is not.

**Comment by mjy** [comment]
>  5 min/record

This just crossed my mind too.  I was indeed doing the math on the .203 in my head, just subconsciously.
