### ISSUE TITLE
Task - browse nomenclature - unrelated citations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2984]
Browse nomenclature now have some citations related to OTU, not TN. I have a species, which should have a single citation, and it has 3 citations now.
![image](https://user-images.githubusercontent.com/5597748/168374229-4cb4c89f-daaf-44bc-956f-27556fcd0ab1.png)

**Comment by mjy** [comment]
@LocoDelAssembly was something modified for the public citations for OTU endpoint perhaps?  If this is recent then it's likely something I did. Did this just pop up @proceps?

**Comment by proceps** [comment]
I would say, I just noticed it on a taxa which suppose to have a single reference. For the taxa with the list of reference, it is harder to detect.
