### ISSUE TITLE
Loans and Filter Collection Objects

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2987]
### Feature or enhancement

When I use the Filter Collection Objects task, the results should quickly and easily tell me if the specimen is on loan.  There needs to be a column or color indicator in the first several columns that will show if a specimen is on loan

### Location

Filter Collection Objects

**Comment by mjy** [comment]
You can add the filter facet to refine your result:

<img width="491" alt="Screen Shot 2022-05-17 at 3 58 18 PM" src="https://user-images.githubusercontent.com/22600/168909051-c4e5e380-1179-48fd-a14e-1001e9470cb4.png">
