### ISSUE TITLE
Task - Edit Source - Clone button - unpredicted behaviour

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#2992]
When I create a new source with authors and editors (as roles), save the record, if I clone the record, the entire record became clone, including the roles, but when I use the fileter to find an existing source and clone it, the source is cloned without roles. I would be useful to clone roles in both cases (if changes are needed, the roles are easy to delete).

**Comment by jlpereira** [comment]
It seems that the backend is returning an unsaved clone object.

Example of source where it doesn't work:
https://sfg.taxonworks.org/tasks/sources/new_source?source_id=19115
