### ISSUE TITLE
[Bug]: Cannot add a determination after editing one

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#2996]
### Steps to reproduce the bug

```bash
In comprehensive specimen digitization, when I edit a determination (add determinet or year) I then hit "update". 
If I then need to add a more recent determination and the only option available is "update" when I newed it to say "add"
```

### Screenshot

![image](https://user-images.githubusercontent.com/25491000/170113175-8b0d6987-fa56-42a5-903f-4602518818e0.png)

### Expected behavior

After I update a determination and save, I expect it to allow me to add another determination seperate of the first one. 

### Environment

Production

### Browser Used

Chrome

**Comment by jlpereira** [comment]
I can't replicate this issue.
Did you remove the taxon determination after select it for editing? In your screenshot I can't see the taxon determination on the list.

**Comment by tmcelrath** [comment]
I can confirm this is an issue. it's weird to replicate. Navigate to any collection object that has a determination, then edit it to something else. Update the determination. Save. Then you will see no "add" button.

**Comment by tmcelrath** [comment]
So basically, this makes it so that you can't add two determinations unless you refresh the page.
