### ISSUE TITLE
Lepindex - citation pages have not been migrated

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#30]
The citation pages (BUTMOTH_SPECIESFILE_REFS_UNIQUE.PAGE) have not been migrated to the Sources records.

**Comment by mjy** [comment]
@proceps Maybe these went to a Citation, not the source?

**Comment by mjy** [comment]
@AdrianHine The pages are tied to specific citations.  We just fixed the Citation list, should be live shortly, so see Citation#list.  Let us know if this doesn't address your issue.

**Comment by mjy** [comment]
Pages are showing up on list now, and in citations.
