### ISSUE TITLE
task - New Source - CrossRef parsing - cursive tags

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3001]
When cursive tags are added to the title automatically (as a result of CrossRef parsing). Often the tags are added without word spacing.
`hoppers<i>Laodelphax striatellus</i>in China`
it should be
`hoppers <i>Laodelphax striatellus</i> in China`
you can use DOI: `10.1002/ps.3992` for testing

**Comment by mjy** [comment]
It should be `hoppers <i>..</i>` I think?

**Comment by proceps** [comment]
Yes, corrected...
