### ISSUE TITLE
[Bug]: Data Source List Error

### ISSUE THREAD

**Issue by ben-norton** [SpeciesFileGroup/taxonworks#3006]
### Steps to reproduce the bug

```bash
1. Sandbox
2. Paleo Data
3. Click DATA tab
4. Click Sources card
5. Click List in the Source bar
6. https://sandbox.taxonworks.org/sources/list
Something web wrong error page.
...
```

### Screenshot

![sandbox-taxonworks-error](https://user-images.githubusercontent.com/7331520/171224417-18003efe-3f52-4c18-a93f-7f5d3a09aee0.png)

### Environment

Sandbox

### Sandbox Used

Paleo Data

### Browser Used

Firefox Developer

**Comment by mjy** [comment]
Working now. Manually fixed bad data, one source was missing cached.
