### ISSUE TITLE
Collection Object - Smart selector.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3007]
In the list of recent Collection Object, I want to see the collection codes, not the automatically generated identifier. Those identifiers could be useful for the data export, but should be hidden as much as possible in the interfaces. They are not informative and confusing, since this information could not be found on the labels.
I want to see INHS 12345 instead.
![image](https://user-images.githubusercontent.com/5597748/171255567-32b5a5f2-5271-47ac-b61a-a34a35980bc4.png)

**Comment by mjy** [comment]
Are you sure they have codes?  We optimized to deal with this but might have missed this case.
