### ISSUE TITLE
Task - Real time validation/warnings for curatorial processes

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#301]
As students/curators add data they might be headed down the "wrong" path, what various kinds of "real time" detection can we imagine that would trigger alerts (emails/dashboards) to managing curators (e.g.:

 - [ ] "worker is adding many 0,0 georeferences;
 - [ ] worker has added (apparently) duplicate records X times)... etc.

**Comment by mjy** [comment]
Potentially useful: https://www.idigbio.org/wiki/index.php/Data_Ingestion_Guidance#Data_recommendations_for_optimal_searchability_and_applicability_in_the_aggregate

**Comment by tmcelrath** [comment]
Collection Object validation ideas (rough incomplete to complete order):
Object does not have catalog number
Object does not have Institution Code
Object does not have Verbatim Locality/Determination
Object does not have parsed locality
Object does not have parsed determination
[special case] object has accession or field code but no corresponding data from field or accession code
Object is not identified to species
[insert field here] is not parsed out (maybe make this customizable)
Object is not Georeferenced
Others??? Want input from others to see how detailed we want to go here

**Comment by JoannaMcCaffrey** [comment]
@mjy @tmcelrath  add condition that 'Object does not have occurrenceID identifier (UUID with prefix preferred)'

**Comment by mjy** [comment]
Let's close after we have as many possible soft validations done for this.  The rest is a duplicate of the code that is needed to report classes of soft validations.
