### ISSUE TITLE
[Bug]: year and stated year 

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#3021]
### Steps to reproduce the bug

```bash
When the year and stated year are both filled in but the same, there is no need for "(Original work published 2011)" to be included at the end of the reference.

e.g.
Mottern, J.L., Heraty, J.M. and Hartop, E. (2011) Cales (Hymenoptera: Chalcidoidea): morphology of an enigmatic taxon with a review of species. Systematic Entomology, 36(2), 267–284. (Original work published 2011)

[output formated from filter sources; tag Chapter Calesidae; download formatted > Chalcidoidea of the World]
```

### Expected behavior

Mottern, J.L., Heraty, J.M. and Hartop, E. (2011) Cales (Hymenoptera: Chalcidoidea): morphology of an enigmatic taxon with a review of species. Systematic Entomology, 36(2), 267–284.

### Environment

Production

### Browser Used

firefox

**Comment by proceps** [comment]
the issue is fixed, the reindexing may be needed to update the rendering. In general, I would not recommend to use both dates if those are the same.

**Comment by JohnHeraty** [comment]
It seems to be something that Noyes did… and for no real reason… but thanks … it is better not to have to regularly delete the second date…

:-) John
