### ISSUE TITLE
[Bug]: Filter nomenclature - results are showing "Original Combinations"  even when one is not set.

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3024]
### Steps to reproduce the bug

```bash
When I  search in "filter nomenclature" the results show a column "Original combination".  If original combination was set for a name, that value is shown (as expected), but for names where the original combination has not been set, the taxon name string is shown.
```

### Expected behavior

If a taxon name does not have an original combination, it should just be blank. 

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
The cached values are not set if there is no original combination
![image](https://user-images.githubusercontent.com/5597748/221697600-cc424c3b-007d-435d-8d0b-3ba2c74bf335.png)

**Comment by proceps** [comment]
But helper may return some value, otherwise we will end up with blank strings in Browse nomenclature for each protonym without original combination.

**Comment by proceps** [comment]
In filter, I believe you can specifically search for the names with/without original combination.

**Comment by proceps** [comment]
I think, the general assumption was that the original combination is the same as current name if not explicitly provided.

**Comment by mjy** [comment]
The new unified queries are finding cached set with no combination relationships.  Maybe these are old/bad data?  I was hoping it was just a helper issue, but it's not (it still could also be a helper problem, I haven't looked at that).

> I think, the general assumption was that the original combination is the same as current name if not explicitly provided.

I think we should not do this now, it is the reason for this issue, and confusion from others as well.
