### ISSUE TITLE
[Bug]: Content tied to OTUs cannot be viewed or edited

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3031]
### Steps to reproduce the bug

```bash
When I use browse OTU to navigate to an OTU page for an OTU with linked content, I get an internal server error and the content is not displayed.

In the quick forms, the wedge for Content still correctly indicates the number of content types that are filled for the OTU.

However, I can't edit, nor can I navigate from "Content Editor" (same generic internal server error).
```

### Environment

Production

### Version

v 0.27.0

### Browser Used

chrome

**Comment by kandakoj** [comment]
oh sorry, just saw an issue related to content was mentioned on the gitter. can delete if its already on your radar.

**Comment by jlpereira** [comment]
We pushed some fixes for content on the last version. The problem persists, @kandakoj ?

**Comment by kandakoj** [comment]
@jlpereira Problems seem to be resolved. Thanks.
