### ISSUE TITLE
selenium-webdriver 4.3 failing with some specs

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#3033]
Specs failing are those from spec/features/tasks/otus/filter_spec.rb that interact with Google Maps.

As temporary fix version was locked to `~> 4.2.0`

**Comment by mjy** [comment]
I think we can close this?

**Comment by LocoDelAssembly** [comment]
Unfortunately no, upgrading makes `spec/features/tasks/otus/filter_spec.rb` fail. I guess we need to rewrite the spec at this point, we recently did https://github.com/SpeciesFileGroup/taxonworks/commit/6abcf0da7547c6d931460ce6b6915a42f4e014b1 to prevent failures.
