### ISSUE TITLE
[Bug]: Loan object total count of containerized objects reports number of containers, not number of individuals in collection object

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3035]
### Steps to reproduce the bug

```bash
1. When I add a container to a loan
2. Then I create a recipient loan form
3. Then the number of specimens in that collection object "Total" is reported as the number of containers, not the number of specimens.
...
```

### Screenshot

Note containerized objects at bottom:
![image](https://user-images.githubusercontent.com/11411328/176271577-ce5ce3df-bf7e-4fbb-a965-8405cf0ea944.png)

Browse CO view of one of containerized objects:
![image](https://user-images.githubusercontent.com/11411328/176271699-87dd64ff-7e4e-40c0-ac31-ada02af924ae.png)

### Expected behavior

Instead of getting a count of total containers, report should report total numbers of specimens in the containerized object. E.g. if a vial has two containers, one with 10 objects and 14 objects, the total reported should be 24. 

### Environment

Production

### Version

0.27.2

### Browser Used

Chrome

**Comment by mjy** [comment]
@tmcelrath can this be closed?

**Comment by tmcelrath** [comment]
Nope - see: https://sfg.taxonworks.org/loans/3356 - the one container within that loan is still reporting a total of "2" when it should be reporting a total of 20.

**Comment by mjy** [comment]
<img width="1057" alt="Screenshot 2023-10-06 at 12 55 39 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/924bd229-b79a-4bd5-a70e-9e28a81ebe88">
