### ISSUE TITLE
issues with a staged image

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3036]
Could you please help us to figure out what the problem with this image is?

Thanks
![IMG_0863](https://user-images.githubusercontent.com/9273125/176280332-6c75b4b4-16d4-4af9-bc1a-0f7212a16396.JPG)
!

**Comment by mjy** [comment]
Hard to say.  The red looks very thick to me, it might be that the horizontal is near the thickness of the bottom right section- but I'm grasping.  I'll have to run it manually to check.  The `|-` is also at a slight angle, but it seems like not enough to make it invalid.

**Comment by teleaslamellatus** [comment]
Thanks for the comment! Meanwhile, we figured out that the problem was the specific jpg iPhones are using. They are not normal jpg-s. Nevertheless, we can easily batch convert them using photoshop, so everything is AOK,

i
