### ISSUE TITLE
Observation matrix - download as csv issues

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3040]
The issues reported by Saad:
There is some mistakes in Excel sheet, that downloaded from TaxonWork
![image](https://user-images.githubusercontent.com/5597748/176816250-f7828ec8-0dcf-4fc4-9892-5875bd89ccba.png)
1. the most important ones the first character shifted with date of species name, so all characters shifted
![image](https://user-images.githubusercontent.com/5597748/176816308-fee55935-ecc1-4a8d-977c-b431573db8e7.png)
2. these one character divided into 2 column it is also make the same problem in the first note 
![image](https://user-images.githubusercontent.com/5597748/176816360-73d5e763-9046-46b3-bc55-b78e8e1cd7fa.png)
3. all Sample Characters not appear in the matrix and could be it is the reason of Interactive key error
![image](https://user-images.githubusercontent.com/5597748/176816443-df64cf6c-4407-4776-a6d1-394e9a077b38.png)
4. several observations not appear in the excel sheet ?
![image](https://user-images.githubusercontent.com/5597748/176816488-2d69dc97-b898-4932-99ec-6dde035b973a.png)
5. the end of character, because of the some characters divided into 2 columns

![image](https://user-images.githubusercontent.com/5597748/176816480-21e8fdea-464e-4d46-a6d9-6c38ac03e68d.png)

6.

**Comment by mjy** [comment]
Likely missing some `.html_safe` on quotes containing data... perhaps.

**Comment by proceps** [comment]
that what I thought, but also missing numerical scores. Probably one or two small fixes should resolve it.
