### ISSUE TITLE
Filter for species without subsequent combination [was: Bug in the "Filter nomenclature" module]

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3051]
Good day to all:
TW offer some excellent tools to help diagnose databases and locate problems.
However, I think I detected a problem with the "**Filter nomenclature**" task.

1) I searched for all species of a given taxon to locate uncited combinations; and got 221 hits.
2) I fixed two of them, but checked again and I'm still getting the same 221 hits.
3) My conclusion is that somehow the tool failed to register the fixes. 
4) I would ask the devs to take a look at the issue [= possible bug], otherwise we may be missing this excellent tool.

Below are links and Images of the two fixed species, and the link to the defective task:
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=329141
![image](https://user-images.githubusercontent.com/46284943/180439185-53504901-573f-4150-bbd8-23db1e5ec638.png)
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=328914
![image](https://user-images.githubusercontent.com/46284943/180439077-438702cb-0f63-40b9-b8fe-37524743ded1.png)
![image](https://user-images.githubusercontent.com/46284943/180439370-7d3580fc-c66a-4e47-b0b9-5d36ac4148a6.png)
![image](https://user-images.githubusercontent.com/46284943/180439435-bbea5545-46d4-4aae-bd41-1b2ef7ab3285.png)
![image](https://user-images.githubusercontent.com/46284943/180439753-ed56243f-83cb-4374-83be-05c2b02f798f.png)

**Comment by mjy** [comment]
Excellent report.  Will check in to it, thanks.

**Comment by jlpereira** [comment]
@adrik29 maybe I missing something, but if you're looking for uncited taxons you should use the other facet for it
![Captura desde 2022-07-22 11-57-26](https://user-images.githubusercontent.com/16530364/180466819-1b576228-e9bc-4c30-9613-f9ea65026fc4.png)
.

**Comment by adrik29** [comment]
@jlpereira -- that's what I thought at first, but I tried a search for ALL species of Opiliones, and it returned NONE, when I know for a fact that we haven't yet entered combination citations for many species.

Maybe the original idea of this filter was different and I misunderstood.
I wanted to search for [in the following example]: what is the original citation for the combination Paracranaus spiniger? As you may see it is still **_lacking the orange combination tag_**, and I wanted to quickly locate all examples of that.

![image](https://user-images.githubusercontent.com/46284943/180469567-424bc427-2b1a-4ea5-b03d-a96ddac15a68.png)

**Comment by adrik29** [comment]
@jlpereira -- and it is not the uncited taxa, but only the combinations, because sometimes a species has original citations, but the current combination doesn't.

**Comment by proceps** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/5597748/182482157-58e03236-bba9-4038-a594-6da1600c4c07.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/5597748/182482220-63f95323-3544-4708-b698-50989a989731.png">
I just checked in my project. Worked as as expected, after adding the citation, the number of records in the filter get reduced

**Comment by adrik29** [comment]
@proceps -- Maybe I explained myself inadequately. We needed some tool which showed us **where** in the project original citations for combinations are lacking so we can proceed to fill this omission.

**Comment by proceps** [comment]
@adrik29 Yes, see my example above. Name type: 'Combination' + Citation: 'without'. It will find all combinations (not protonyms) which do not have citations.
Do I miss something?

**Comment by proceps** [comment]
I think, I understand what you are looking for. If the species is moved to another genus, but a subsequent combination is not recorded in the database, you want to be able to find those taxa? I think, I can implement this as a soft_validation on a TaxonName. Once we have a tool for indexing soft_validation, we should be able to get complete list.

**Comment by adrik29** [comment]
Hello, Dmitry, there is something definitely wrong here:
(1) I took one species of my project which has changed genus.
My example is = Sitalcina kaweahensis Briggs & Hom, 1966
which was subsequently combined as Calicina kaweahensis (Briggs & Hom, 1966)
![image](https://user-images.githubusercontent.com/46284943/182493569-bd73b91f-06ac-4000-b0d1-37103d6a67e2.png)

(2) we can see there is NO CITATION for the subsequent [current] combination, and I wanted to LOCATE all cases where it occurs so I can complete.

(3) Then I go to the family Phalangodidae and do as you said.
![image](https://user-images.githubusercontent.com/46284943/182493846-3a514532-9565-44a0-a789-278444571e20.png)
![image](https://user-images.githubusercontent.com/46284943/182493876-bef84217-2510-4acb-a1c8-b212ef32821f.png)
![image](https://user-images.githubusercontent.com/46284943/182493935-5d25a897-631d-4b3a-98bf-5e255afedd7b.png)

(4) And I got "no records found", which is barely legible, because the color scheme choice of light gray over light pink background...
![image](https://user-images.githubusercontent.com/46284943/182494057-1dac2d12-3391-42a0-8bd6-f84f5f4f781c.png)

**Comment by proceps** [comment]
I added a soft_validation to Protonym with a fix. The filter should be available when the indexing of soft_validations is implemented. #2546

**Comment by adrik29** [comment]
@proceps -- That's fantastic, can hardly wait to see it!

**Comment by mjy** [comment]
Unified filter release will let you expliciltly query this, like so:
<img width="421" alt="Screenshot 2023-03-02 at 11 57 05 AM" src="https://user-images.githubusercontent.com/22600/222514006-b79af5b6-717b-4e95-9fd1-a0643855b570.png">

<img width="433" alt="Screenshot 2023-03-02 at 12 02 51 PM" src="https://user-images.githubusercontent.com/22600/222514012-3cc8b7b5-391e-4dd7-9489-7d543e14c10a.png">
