### ISSUE TITLE
[Bug]: Clipboard does not work

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#3052]
### Steps to reproduce the bug

```bash
I can copy and paste things into the clipboard, but I cannot use any Alt or Command keys to get the text into any TW form.
When I am transcribing data into the comprehensive specimen digitization form, I often have many specimens with the same determination. I can copy and paste that info into the clipboard. When I go to the next specimen, I can copy and paste the info from the clipboard back into the form, but I cannot use any hotkeys or shortcuts to move the text.
```

### Screenshot

![image](https://user-images.githubusercontent.com/25491000/180571828-896caed8-8446-4789-b61b-a99092a53532.png)

### Expected behavior

I expect to be able to use short cuts or hotkeys like Alt-1 to make my transcribing easier and faster.

### Environment

Production

### Browser Used

Chrome

**Comment by mjy** [comment]
@mmkohler what OS, PC, mac, or linux?

**Comment by jlpereira** [comment]
I can't replicate it. Looking the screenshot I assume it's Windows 10/11.

Could you try again using incognito mode, @mmkohler ? Maybe your bug could be related to an browser extension

**Comment by mmkohler** [comment]
I tried it in incognito mode and the clipboard worked. Why is that?

**Comment by LocoDelAssembly** [comment]
I think Chrome disables extensions in incognito mode? Maybe you could try disabling extensions one by one until you see it starts working (in regular browsing mode)?

**Comment by jlpereira** [comment]
Like @LocoDelAssembly said, the incognito mode doesn't use any extension. So, you may have an extension that is interfiering with the hotkeys. Follow @LocoDelAssembly advice and see if that fix your issue

**Comment by mjy** [comment]
@mmkohler I'm going to close this as agnostic to your browser setup.  Please re-open if you think it is not, for example if you can replicate on another browser on a different machine.
