### ISSUE TITLE
2nd order administrative divisions also for Brazil?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3054]
### Feature or enhancement

Currently in TW only the USA have 2nd order AD. Given that Brazil is a megadiverse country, with continental dimensions, it would be important to also have its subdivisions, not only the states, which in many cases are huge.
I am aware that we can pinpoint precise localities with coordinates, but in most cases, the NAME of the "county/province/municipality/parish/whatever" is far easier to access.
This could be eventually extended to some countries with complex biogeography, which lie in the crossroads of realms such as China or Mexico.

### Location

probably "Browse OTUs" but also "Browse nomenclature and classification"

### Your role

curator of project

**Comment by proceps** [comment]
could be tricky. We need a gazetteer with shape files

**Comment by adrik29** [comment]
@proceps -- hm... aren't those suitable?
https://www.diva-gis.org/gdata

**Comment by mjy** [comment]
That data is GADM, which is what we already use as a base-map.  It looks like there is some new movment to curate GADM, which is good.  https://gadm.org/data.html.  I suspect our solution will be to write a generic updator against GADM files.

**Comment by adrik29** [comment]
Is there a way that TW recognizes alternative names for areas?
For example if I use **"Toscana"** and someone else uses **"Tuscany"**, both should point to the same area.

**Comment by debpaul** [comment]
> Is there a way that TW recognizes alternative names for areas? For example if I use **"Toscana"** and someone else uses **"Tuscany"**, both should point to the same area.

Hm. @mjy could we use wikidata? for all possible transliterations?

**Comment by proceps** [comment]
I also want alternative values on geographic areas: #2506

**Comment by adrik29** [comment]
@debpaul -- not only transliterations, but rather translations for well-known place names.
Examples: 
Bavaria versus Bayern.
North Sulawesi versus Sulawesi Utara.

**Comment by mjy** [comment]
@debpaul that would help certain use-cases, yes.  It may resolve #2506 too, since we would have a single source of truth (not us, wiki-data).

**Comment by mjy** [comment]
BTW all - let's keep one issue per issue :).

**Comment by proceps** [comment]
I would like just have an option to put few alternative values on the name. Like Formosa = Taiwan, Ceyloy = Sri Lanka

**Comment by mjy** [comment]
_this is not the issue for alternative values, please keep that conversation on #2506_

**Comment by proceps** [comment]
Added level_2 Geographic areas for Brazil, China, Portugal, Spain
