### ISSUE TITLE
Batch CO identifier search API endpoint

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3058]
### Feature or enhancement

I would like to generate a DwC export from a newline-delimited file/list of CO identifiers.

The current process for doing this:
1. Paste all the identifiers into the CO Match task
2. Click match, and wait while it the ui makes a request for each identifier (it does 2-3/s in my dev environment, less in sandboxes)
3. Apply a temporary tag to the objects
4. Use the Filter CO task to select all COs with the temporary tag
5. Select all and click DwC Export

This is manageable when you're matching a couple dozen identifiers, but matching 5k identifiers takes 20+ minutes in the CO Match step. Having a batch identifier search endpoint would significantly improve the experience for large searches.

### Location

CO Match

**Comment by mjy** [comment]
This is now possible via the match facet it CO filter.
