### ISSUE TITLE
Loading Collect Object Image Breakdown TODO list

### ISSUE THREAD

**Issue by Camehalek** [SpeciesFileGroup/taxonworks#3066]
Hi, my name is Cameron and I am working with Istvan Miko on digitizing the UNHC entomology collection. I have noticed the past few days that the Collect Object Image Breakdown TODO list is having issues loading. It takes each page several minutes to load. Any help with this would be greatly appreciated. Thanks!

**Comment by debpaul** [comment]
@Camehalek thanks for posting this ticket. Sorry you're having to wait such a long time for the page to load. Question @tmcelrath @mmkohler are you seeing similar behavior?

I just poked around at a few of these in the INHS Insect Collection Project and the records loaded quickly.

Several days ago, we did note issues for "recalculate" (but not sure this has any relationship to what you're experiencing @Camehalek).

@Camehalek please if you can, provide one or two links to the exact item you're clicking on that's taking a long time to load. See example (on a PC, right click to copy URL link to a given object)
![image](https://user-images.githubusercontent.com/2990155/182923254-d32033ef-36e3-4dcd-a9c1-398c144a13e0.png)


To the developers:
See also #2275 #3047 which may or may not be related but both involve sqed issues.

**Comment by tmcelrath** [comment]
I am not seeing similar behavior. Our images are loading just fine, as our our image "polygon" pages.

**Comment by LocoDelAssembly** [comment]
Trying navigation of pages in `Collection object image breakdown (sqed) TODO list` task at `UNH Insects` project doesn't seem to take more that a few seconds each. Are you @Camehalek referring to the same page @debpaul is showing above?

cc @teleaslamellatus

**Comment by mmkohler** [comment]
In the past few weeks, I have not had the problem where it takes forever for each specimen to load. I do sometimes get a 404 error when I am trying to load a specific page by specimen number in the address bar.

The problem can be difficult to replicate, but very frustrating when it happens

-Michelle
Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mjy** [comment]
404s may happen when you have switched projects and try to load an object
not in that project.

M

**Comment by mjy** [comment]
Closing as stale.
