### ISSUE TITLE
Credit when publishing CoLDP - missing some folks in the Creator field at Checklist Bank

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3073]
### Feature or enhancement

When publishing a CoLDP to share with Checklist Bank, what can we do in TaxonWorks to 
a) ensure they are aware of whose names will or will not be in the "Creator" field at ChecklistBank.
b) possibly, offer the person a form to vet that contains names of all who worked on this dataset
c) perhaps even show them the mocked-up citation as it will appear in Checklist Bank?

Maybe this is part of the CoLDP task?

### Location

https://sfg.taxonworks.org/tasks/exports/coldp

**Comment by mjy** [comment]
Duplicate of #3069 I think?  Close if so.

**Comment by debpaul** [comment]
Closing this as it's a duplicate.
