### ISSUE TITLE
CO Filter with Predicate does not search event's data attributes

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3075]
### Feature or enhancement

1. Open CO Filter task
2. Add CE model data attribute (eg Microhabitat) and add a filter value (eg leaf/soil)
3. Click search

The search returns no results, instead of all COs whose collecting events match the provided data attribute.

The CO filter can already search CE fields (via the "By attribute" facet), so I would expect the Predicate search to behave the same way.

### Location

Task - CO Filter

**Comment by mjy** [comment]
This requires unified filters: #2652.

The CollectingEvent filter allows for this.  One temporary route forward is to create a button in CE filter that sends ce_ids to CO filter.  @jlpereira maybe you can do this with a button quick?
