### ISSUE TITLE
Task- CO Match- containerized specimens show up as "Unmatched" in results

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#3079]
### Feature or enhancement

When I need to match collection objects to edit their data all at the same time, containerized specimens do not show up in the results list.
I list the identifiers (catalog numbers) and hit the Match button. Containerized specimens show up as "unmatched". 
I don't recall this being an issue in the past. Maybe it is a bug? 

### Location

Task- Collection Object Match

### Screenshot, napkin sketch of interface, or conceptual description

<img width="1440" alt="Screen Shot 2022-08-24 at 11 38 37 AM" src="https://user-images.githubusercontent.com/75492546/186475487-49c77952-54a9-491b-840d-6dea46154916.png">

### Your role

Insect Collection Assistant

**Comment by mjy** [comment]
@lvhart2 I believe this works now.  Please reopen if not.
