### ISSUE TITLE
Provide minified URLs to Images

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#308]
* [ ] As a user, I want to drag drop images
* [ ] I want to browse those images, and get a shortened/minified URL that links to an image of a certain size, so I can embed that in my HTML
* [ ] I can submit the minified URL to an API endpoint, and get the link to the image

**Comment by mjy** [comment]
@TuckerJD Please research this issue and propose a solution

**Comment by TuckerJD** [comment]
shortener gem: version 0.6.2 requires Rails 4.2.10, and version 0.7.1 requires Rails 5.2.

**Comment by mjy** [comment]
Did you find any other options?

**Comment by TuckerJD** [comment]
6 chars, icase.
