### ISSUE TITLE
Task - New source, autocomplete not catching all results

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3091]
When I search for "TaxonWorks", then I I expect to get some cannonical hits in the title, but I don't.  For example in production I am missing "122858".  Likely we need a dynamic `limit()` based on the number of prior results loaded.  5 Results are returning, which is likely the cutoff for single word matches.

**Comment by proceps** [comment]
What you are looking for?source_id?  Please provide more details.
![image](https://user-images.githubusercontent.com/5597748/188675323-f4f52786-0b05-4ac3-b0cc-44c4799738dd.png)

**Comment by proceps** [comment]
Single word match - 20 results:
![image](https://user-images.githubusercontent.com/5597748/188676142-0505b82b-9932-4394-bc5f-67299f3bcd29.png)

**Comment by mjy** [comment]
Try searching for "TaxonWorks'.  Notice that you will not find the reference with the id "122858".

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/188682527-dfa7eba6-30da-416a-824d-891af7e61690.png)
