### ISSUE TITLE
Task - Citations by source - Nomenclatural statuses

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3095]
Nomenclatural statuses section is not populated
![image](https://user-images.githubusercontent.com/5597748/189453427-7e7b4aa8-8fe2-472b-9b51-fe8dacf05ab1.png)

**Comment by jlpereira** [comment]
I can't replicate it @proceps could you provide an example?

**Comment by proceps** [comment]
Strage, seams to work now... I will keep an eye on it.
