### ISSUE TITLE
LepIndex - LepIndex title field is the journal/book title not the article title

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#31]
The LepIndex FULLTITLE field has been migrated to the TaxonWorks _article_ title. The field is actually the journal or book title (mostly journal title) and never the article title.

**Comment by mjy** [comment]
Should be more or less resolved in the next attempt at loading.  May be some issues with Book titles.

**Comment by mjy** [comment]
@AdrianHine  they have all been migrated to Journal.  Let us know if this is acceptable or, can you let us know how to differentiate b/w book and journal?
