### ISSUE TITLE
Task - Edit Matrix - Create new OTU

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3101]
When I create a new OTU from the Edit Matrix interface (using New OTU button), the OTU should be automatically linked to the Matrix, the same way a new descriptor does.

**Comment by jlpereira** [comment]
I can't replicate this, when I create the new OTU is added to the matrix

**Comment by mjy** [comment]
This is from the New OTU link on the top.  It won't work untill we make a New OTU task. (Descriptor is a task).

I honestly think we should remove New OTU, we have it inline.

**Comment by jlpereira** [comment]
> This is from the New OTU link on the top. It won't work untill we make a New OTU task. (Descriptor is a task).
> 
> I honestly think we should remove New OTU, we have it inline.

Yep, agree. I will remove it
