### ISSUE TITLE
Filter CO: Geographic area/county is missing in specimen records that migrated from FM, visible in Data attributes 

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#3116]
### Steps to reproduce the bug

```bash
When I want to download a set of data either as CSV or DwC:
1.for example, I use Filter Collection Objects task to search for a certain species.
2.Some older specimens that were databased using FileMaker, much of their data, including county, does not filter out in Filter Collection Objects task and shows up blank in the table of data. 
3. This geographic area/county information is only visible/available if you look at the Data Attributes, however, this doesn't help me when I need to download bulk data for a report. This Geographic area didn't carry over to TW and the only way for it to show up in the CSV or DwC is to manually edit each old record and assign it a geographic area.
...
```

### Screenshot

<img width="1114" alt="Screen Shot 2022-09-27 at 10 32 26 AM" src="https://user-images.githubusercontent.com/75492546/192570919-e7da73be-5c4a-4615-88f3-a924f2fcab5c.png">
^ This screenshot shows blanks in some fields for specimen records.

<img width="1438" alt="Screen Shot 2022-09-27 at 10 33 39 AM" src="https://user-images.githubusercontent.com/75492546/192570965-04fa8f42-b70a-4e28-9e61-3f486c74d972.png">
^When I open that record with COD task, the geographic area is not assigned.

<img width="1437" alt="Screen Shot 2022-09-27 at 10 34 21 AM" src="https://user-images.githubusercontent.com/75492546/192571004-d4a72b70-c63e-46a9-99a3-4c14ef75d96c.png">
^However, when you look at the data attributes, county information is assigned to the specimen. 

### Expected behavior

When I filter out collection objects, I should be able to see all of the data for that record that was in the FileMaker database (county, park, body of water, etc.)  It doesn't make sense to have to edit all of those records in order to see data they already have. 

### Environment

Production

### Version

v0.29.3

### Browser Used

chrome

**Comment by mjy** [comment]
@lvhart2 thanks for reporting.  I checked this particular record.  It is successfully re-indexed with the fix to #2614, so I'm going to close this.  In a week or so (maybe sooner), when production is updated (the fix is applied), please re-open if you find additional issues.
