### ISSUE TITLE
Task - Matrix row coder - cloning observations with depictions

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3120]
In the image matrix, when I clone observations, depictions are not added to new observations

**Comment by mjy** [comment]
@proceps I looked/thought more about this.  I think this should only be allowed if the ObservationObject is an OTU.  If it is a collection object then it can not be the same Depiction according to the semantics.

**Comment by proceps** [comment]
That will work for me. In many occasions we we clone a 'typical species' depiction to represent a genus.

**Comment by mjy** [comment]
Already works, at present all depictions are duplicated, use with caution for specimens.
