### ISSUE TITLE
Task - matrix row coder - checkbox to show only unscored descriptors

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3121]
Saad requested some filtering functionality to 
1. display only unscored descriptors,
2. displays descriptors with a particular tag (we are doing this in interactive key)

Same should be implemented in the Column coder
1. display only unscored rows

**Comment by mjy** [comment]
I don't think we want to implement tags filtering- this is already done with dynamic character/views.  Create a new matrix, add the dynamic column via the Keyword, and you have the view you need, updated as you need.
