### ISSUE TITLE
OTU on the pin board

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3137]
We completely miss pinboard functionality for OTU
1. Pinboard icon is missing in Browse OTU page.
I can still put OTU to the pinboard through the data interface, but it is useful
2. I cannot retreat the OTU from the pinboard in Filter CO, Comprehansive digitization, and probably some other interfaces
3. The pinboard items are not displayed in the smartselectors (Comprehansive for example.

**Comment by mjy** [comment]
> Pinboard icon is missing in Browse OTU page.

Pin is integrated everywhere in the radial navigator: 

<img width="458" alt="Screen Shot 2022-10-11 at 10 28 21 AM" src="https://user-images.githubusercontent.com/22600/195134476-165b856d-9bbe-4d66-af22-fa33e926bd04.png">

Please open 2 and three as individual new issues.
