### ISSUE TITLE
Task - Matrix column coder - select OTUs with one char_state

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3141]
Hi, Saad asks if we can change the 'no scores' checkbox in MCC to a select box, where you can select not only unscored OTUs, but also OTUs with a specific character states from the list. It could be a list with a first option as unscored.

**Comment by jlpereira** [comment]
@proceps the idea is a select input to select a specific character states? And when you select it you can toggle between unscored/scored?

**Comment by proceps** [comment]
The idea is to replicate the functionality of the unscored checkbox. When I select one or few states, only display those OTUs which have selected states.

**Comment by jlpereira** [comment]
@proceps pushed branch 3141_char_filter

Is filtering by OR, let me know if it should be AND.

**Comment by anase24** [comment]
Hi 
The idea is first case: if I have many unscored OTUs and these need to divide into groups so I can select what I need then score it, for example after display unscored OTUs, there are 10 , 5 of them need to score with 0 and others 1 so I can select the first five and score it and next five 
second case: when I have long list of already scored OTUs, but I would to change specific numbers of OUTs so I can select it and give them the correct observation. so the only action to selected OTUs, I can destroy selected and populate them again. 

Third case: If I have data already in excel sheet, I can autofiltered in excel for only first observation then the result, go to TW and select the same the populate it. and so on, so it can be used as data entry as well.
