### ISSUE TITLE
[Bug]: sources reported as "in" are not

### ISSUE THREAD

**Issue by mccullermi** [SpeciesFileGroup/taxonworks#3142]
### Steps to reproduce the bug

```bash
1. search sources results show sources that are not in the project as being in the project

...
```

### Screenshot

![image](https://user-images.githubusercontent.com/7378944/195409723-81b449a9-e8f7-4cf5-801e-06d54b827e16.png)

### Expected behavior

sources added to the project at top of source results list

### Environment

Production

### Version

v0.29.5

### Browser Used

Chrome

**Comment by proceps** [comment]
I did not experience this problem, all sources are search for are correctly marked. Please provide a source ID and Project name for testing.

**Comment by proceps** [comment]
https://sfg.taxonworks.org/tasks/sources/new_source?source_id=107423 in 3i project

**Comment by mjy** [comment]
@proceps see bug below, handing it back ot you.

* As noted, the "in" is not calculated correctly (there is only one true "in" in this screenshot below)
* The `in` is incorrect as the `in_project` parameter does not compare to sessions_current_project_id
* The code prioritizes references with (many) citations in any project, not in this project.  It should only do this *after* prioritizing references in this project I think.

```
   if project_id && scope
            a = a.left_outer_joins(:citations)
              .select('sources.*, COUNT(citations.id) AS use_count, NULLIF(citations.project_id, NULL) as in_project')
              .where('citations.project_id = ? OR citations.project_id IS DISTINCT FROM ?', project_id, project_id)
              .group('sources.id, citations.project_id')
              .order('use_count DESC')
          end
```

<img width="1574" alt="Screen Shot 2022-10-24 at 4 29 04 PM" src="https://user-images.githubusercontent.com/22600/197633247-79da3de6-a236-48a3-948d-5d4a2eaad652.png">

**Comment by proceps** [comment]
Thanks, I check and update it, once I am back.

**Comment by mjy** [comment]
Pinging you @proceps to try and fix this.
