### ISSUE TITLE
[Bug]: Source added to "author" causing multiple issues

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3146]
### Steps to reproduce the bug

```bash
I don't remember the exact point at which it happens (I was working on autopilot the two times I encountered this error), but in Edit taxon name, under "Author" I am adding sources from the pinboard. 

I get some errors popping up on the bottom of the screen (see first image) and although the source is listed, I can't clone author from source (citations: is invalid). 

When I look at the name under browse nomenclature (second image), the protonym has been duplicated and the source is added as an annotation.
```

### Screenshot

![errorimage1](https://user-images.githubusercontent.com/70152690/196948214-4bb26d19-6b8c-45f4-ba6d-560b82fbde5f.jpeg)
![errorimage](https://user-images.githubusercontent.com/70152690/196948339-a9a595a9-f565-4e86-90c3-736ace0c3166.jpg)

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
you just managed to create two citations on the same protonym (
![image](https://user-images.githubusercontent.com/5597748/196974342-07ecb40d-7ab4-428f-b350-fe879f7e5a67.png)
Go to radial, and delete one of those (not original) from thelist of citations.

**Comment by mjy** [comment]
This should be allowed if the citations are identical.

**Comment by proceps** [comment]
I cannot replicate it, and I am working on the DB constantly. Should be some network issue. What we have with ocasional author duplication.  Ocasionally you may have a problem with protonym, if it has a citaion, but not original, and somebody is trying to create anoter (or the same citation), through edit TN interface, you will get an error message, that the citation already exists, althoug, the citation sitring is blank in the interface (which displays only the original citation. But I have not experience the citation duplication. There is no duplication of protonyms, you can see it from the screen shot.

**Comment by kandakoj** [comment]
Thanks. it is easy to fix when the problem occurs, just wanted to make sure it wasn't caused by something weird in the code. 

I only encountered it in the last few weeks. The only difference to my usual routine is now I am using the option to add the citation from pinboard.

**Comment by kandakoj** [comment]
The last couple days, I've been adding quite a lot of records to my catalogue, and I am running into this issue almost constantly (once every four or so times I add source). I know the fix is easy, but the few additional clicks to open the citation radial and delete one of the entries is a bit annoying, especially when I have to do it so frequently. 

I can't recreate the issue even if I delete both citations in an offending taxon. Is this a network issue on my end?

**Comment by mjy** [comment]
@kandakoj:

* try wiping your site cookies etc and hard reloading
* open your browser console,screenshot any red errors, try to leave it open while you work, this is likely the clues we need.  we did fix one issue caught this way with the latest update

**Comment by kandakoj** [comment]
Finally caught it with the console open. I had done the hard reload/wiped cookies a few days ago.

![DuplicatingCitations](https://user-images.githubusercontent.com/70152690/202538134-426a256c-2128-4de7-a374-78aa8e910cd3.jpg)

**Comment by mjy** [comment]
Closing this as out of date.
