### ISSUE TITLE
As a curator I (may) want a subclass of "Not latin" that reflects plant style names in ICZN (e.g. Protozoa)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3156]
When I add Protozoan names, then they are governed by ICZN, yet they haven't got their act together, so they have Plant endings, so TaxonWorks requires the 'NotLatin' work around.  Technically they *are* Latin, so maybe we need a subclass of "NotLatin" (subclass so we can maintain the functionality, it works fine to override spelling), that is something like "NotLatin::UnconformingName"?

**Comment by proceps** [comment]
When protozoan names are used in zoological nomenclature, the names should be normalized according to ICZN rules. We can always use "FemilyGroupNameForm" to indicate the usage of the name.
There is no problem to create a Kingdom with the name "Protozoa"
![image](https://user-images.githubusercontent.com/5597748/198315795-924a5343-8e9e-4069-8f8f-2a4d88ba6fe3.png)

**Comment by mjy** [comment]
Sorry for confusion. `Protozoa` is fine.  Families inside Protozoa are not.
<img width="1294" alt="Screen Shot 2022-10-27 at 2 37 26 PM" src="https://user-images.githubusercontent.com/22600/198382904-c6d427a1-3225-47a3-8f93-42331a3395c8.png">
<img width="272" alt="Screen Shot 2022-10-27 at 2 37 43 PM" src="https://user-images.githubusercontent.com/22600/198382905-81cb5318-f1b2-404b-8019-2843bfeeedc3.png">
<img width="1302" alt="Screen Shot 2022-10-27 at 2 38 38 PM" src="https://user-images.githubusercontent.com/22600/198382909-25515e5e-fd53-4b91-bc3d-3f28742fbd21.png">

**Comment by proceps** [comment]
I believe the families should be used with zoological endings, and we can record the original form as a family form under it.

**Comment by mjy** [comment]
@proceps Thanks, will do. We'll need to move this to the FAQ(esqe) section of docs.taxonworks.org).
