### ISSUE TITLE
Print Unit Tray Labels

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#3160]
### Feature or enhancement

As a Collections Assistant, I want to be able to go to Nomenclature, choose a Taxon name and select it for printing a Unit tray label that resembles the currently used labels. After I have selected a full page's worth then I want to click print.!
EasyPeasy!

### Location

Enhancement under Nomenclature

### Screenshot, napkin sketch of interface, or conceptual description

![Example Unit Tray Label](https://user-images.githubusercontent.com/25491000/198384768-b202c977-40c3-4475-a045-e3f9b47b26a2.jpg)

**Comment by tmcelrath** [comment]
Related to #69
