### ISSUE TITLE
[Bug]: Bacterial code has incorrect genus/higher validation

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3161]
### Steps to reproduce the bug

```bash
When I enter a genus ranked name for bacterial names, and I chose a tribe ranked name (or family). as parent, then I get an error.
```

### Screenshot

<img width="1399" alt="Screen Shot 2022-10-27 at 4 50 26 PM" src="https://user-images.githubusercontent.com/22600/198405182-5c9b09ad-dad2-4571-8837-166ef15d10ef.png">

### Expected behavior

Genus rank is lower than family/tribe, it should save.

### Environment

Production

### Version

 v0.29.5

**Comment by proceps** [comment]
Genus and family are in different Codes. I added additional validation. You can actually change the nomenclatural code in the Data mode. To do this, you have to remove the species from the genus (set parent to Root). In the Data mode, edit the Rank (select proper Code). Do the same for species, after saving, species could be associated back with the genus, and the genus could be reassigned to the family.

Alternative solution. If you have only biological associations, remove TaxonName from Otu. Delete both genus and species, create new genus and species in the proper Code, and associate OTU back.
