### ISSUE TITLE
TaxonName autocomplete should be faster

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3162]
### Feature or enhancement

We spend a lot of time searching via TaxonName autocomplete.  While the results are very accurate, and prioritized nicely, with lots of sub tricks, it feels like this is slightly too costly versus time to query.  Removing all but one, wildcarded against cached returns a very fast result, but at too much cost of accuracy/wildcardness.

* Perhaps this is the first place to build a full text index in Postgres to use
* With a first step full text behaviour would be fairily similar to CoL, which sacrifices likelyhood of hits, and nice features like `C aus` returning more exact matches first, with speed.
* Couple this with a very fast initial result, followed by options to expand, or expand all results to return what is now the present search scope.

Regardless of the approach, let's speed up the queries by at least 100%, at the cost of maybe 20% of accuracy.

### Location

Task - New taxon name, and many others

**Comment by proceps** [comment]
we should check, may be it is just a delay on a request?

**Comment by proceps** [comment]
Yes, it feels slow, the same with OTU search

**Comment by mjy** [comment]
Closing as done (wasn't logged in Changelog).  Now it is too fast, and not intelligent enough, and we have to backtrack a little - https://github.com/SpeciesFileGroup/taxonworks/issues/3509.
