### ISSUE TITLE
Validation for ICN subclass/class (a fungal name) seems to be incorrect?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3165]
When I enter the name `Dihaplophasea` and try to assign it to a subclass then I get this:

<img width="1749" alt="Screen Shot 2022-10-31 at 10 54 18 AM" src="https://user-images.githubusercontent.com/22600/199058330-f24c2453-e8b6-48ae-8dfa-02d394247f08.png">

**Comment by proceps** [comment]
ICN  16.3.  Automatically typified names end as follows: the name of a division 
or phylum ends in -phyta, unless it is referable to the fungi in which case it 
ends in -mycota; the name of a subdivision or subphylum ends in -phytina, 
unless it is referable to the fungi in which case it ends in -mycotina; the 
name of a class in the algae ends in -phyceae, and of a subclass in -phyci- 
dae; the name of a class in the fungi ends in -mycetes, and of a subclass 
in -mycetidae; the name of a class in the plants ends in -opsida, and of a 
subclass in -idae (but not -viridae). Automatically typified names with a 
termination not in accordance with this rule or Art. 17.1 are to be corrected, 
without change of authorship or date of publication (see Art. 32.2). How- 
ever, if such names are published with a non-Latin termination they are not 
validly published.
