### ISSUE TITLE
Task - Annotation browser

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#317]
After I have applied some annotations, then I want to see what I've done.  Create a simple faceted search to list out the annotations.
<img width="1620" alt="screen shot 2018-03-14 at 11 05 45 am" src="https://user-images.githubusercontent.com/22600/37414684-b1aa7f1e-2777-11e8-86f7-8bf70b1aa421.png">
<img width="1612" alt="screen shot 2018-03-14 at 11 05 36 am" src="https://user-images.githubusercontent.com/22600/37414688-b3b563a0-2777-11e8-903a-0c7e454d2eea.png">

Thoughts on functionality:

* *Annotation type* is selected by user
* Triggers population of options in *For*
* Toggled options in *For* triggers population of "On" and "By", and ideally a range in "When"
* Subsequent limits in any of On, By, When cascade changes to each other, and the result list

**Comment by mjy** [comment]
@jrflood wireframe is at taxonworksdoc/wireframes/tasks/annotations/AnnotationBrowser.bmpr

**Comment by jrflood** [comment]
* [ ] GET /tasks/browse_annotations/get_type_list - JSON for the left side selector

**Comment by mjy** [comment]
# Return the types of annotations

GET /annotations/types

# Return the set of predicates/keywords/confidence levels 

GET /controlled_vocabulary_terms?used=true?klass=Keyword&on[]=Otu
GET /confidence_levels?used=true&on[]=Otu

# Metadata about a type of annotations

* Returns set of annoated klasses (which things have Tags)
* Returns count of things on Tags

GET /tags/metadata
GET /data_attributes/metadata
GET /confidence_levels/metadata
GET /alternate_values/metadata
GET /notes/metadata

# Returing a set of annotations

The following params are available:

* on[]=Otu
* by[]=1
* created_after=1900/02/20
* created_before=2000/02/20

* [ ] GET /tags
* [ ] GET /data_attributes
* [ ] GET /confidences
* [ ] GET /alternate_values
* [ ] GET /notes

**Comment by mjy** [comment]
Been done for a while, add specific issues as new.
