### ISSUE TITLE
Collection object image breakdown todo list personalization 

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3171]
### Feature or enhancement

Make navigation easier. Ability to filter based on uploader/completeness and easier page selection (ex. Go to page ___ ).
We have posted a similar request earlier, but were not able to find the issue (by Grace Gaucher).

### Location

https://sfg.taxonworks.org/tasks/accessions/breakdown/sqed_depiction/todo_map

**Comment by mjy** [comment]
Turning this into a standard filter.

# Facets

* [ ] Houskeeping (user/created)

Then, Identical (including param name) to CollectionObject filter:

presence absence facets for:
* [ ] identifiers
* [ ] collecting_event
* [ ] taxon_determinations
* [ ] with_buffered_determinations
 *[ ] with_buffered_collecting_event
 *[ ] with_buffered_other_labels
