### ISSUE TITLE
Cannot retreive the list of specimens wihtout identifiers

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3173]
### Steps to reproduce the bug

```bash
Cannot retreive the list of specimens wihtout identifiers

https://sfg.taxonworks.org/tasks/collection_objects/filter?per=500&page=1&identifiers=false
```

### Screenshot

<img width="2330" alt="Screen Shot 2022-11-01 at 11 21 31 AM" src="https://user-images.githubusercontent.com/9273125/199269764-9afdeff8-4534-42b6-96e9-4e73fe5b2756.png">

### Environment

Production

### Browser Used

chrome

**Comment by mjy** [comment]
Right, we hit this earlier.  This is because all CollectionObjects now have GUIDs (ugh).  

We'll refine the query to be "No CatalogNumber", or allow the user to choose the type of identifier.
