### ISSUE TITLE
Mass delete collection objects

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3174]
### Feature or enhancement

it is perhaps allowed but we cannot find how can we delete more than one collection objects or collecting events.
it would be perhaps great if there would be allowed to delete objects that are checked on the filter result page (see screenshot below).

### Location

https://sfg.taxonworks.org/tasks/accessions/breakdown/sqed_depiction/todo_map

### Screenshot, napkin sketch of interface, or conceptual description

<img width="2322" alt="Screen Shot 2022-11-01 at 11 26 53 AM" src="https://user-images.githubusercontent.com/9273125/199271540-ed0e482c-1266-40bb-9b59-1bead0a6b78b.png">

**Comment by jlpereira** [comment]
It's done

**Comment by dominicev** [comment]
Is it possible to add an option to modify the max number of objects to delete?
