### ISSUE TITLE
OTU / Collection event merger

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3175]
### Feature or enhancement

Is it possible to merge collecting events and OTUs? It would be great to have a similar merger that we have for merging taxon names.

### Location

https://sfg.taxonworks.org/tasks/taxon_names/merge

**Comment by tmcelrath** [comment]
@mabecabrera

**Comment by mjy** [comment]
Will be resolved in https://github.com/SpeciesFileGroup/taxonworks/issues/970.
