### ISSUE TITLE
[Bug]: Source soft validation "Cached should be updated" is not calculating correctly after fix

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3181]
### Steps to reproduce the bug

```bash
1. When I fix the cached issue, then the soft validation persists
```

### Screenshot

See New source task.

### Expected behavior

Soft validation is gone

### Environment

Development (native)

### Browser Used

FF

**Comment by proceps** [comment]
Need an example. This is not always the case.

**Comment by mjy** [comment]
Does the validation method compare the same two methods, i.e. it includes the method that produces the cached?

**Comment by proceps** [comment]
I am not sure what is going on. Need an example to experiment. I may find one in my project sources.
