### ISSUE TITLE
[Bug]: Unit tray labels need botton 1/4 inch clear

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#3191]
### Steps to reproduce the bug

```bash
The bottom 1/4 inch of the unit tray label is behind the foam and cannot be seen. Pleae look at the picture I Included so you can see why the old labels work and the new ones need to be adjusted.
2.
3. 
...
```

### Screenshot

![Original Unit tray label](https://user-images.githubusercontent.com/25491000/200891180-fc60e8a9-f383-48a1-aac8-7c6592e37e39.jpg)
![Both labels](https://user-images.githubusercontent.com/25491000/200891201-f3ec5e51-6c17-49ed-b2b6-7b03d664c142.jpg)

### Environment

Production

**Comment by mjy** [comment]
@jlpereira we fixed this, correct?

**Comment by debpaul** [comment]
@mmkohler please can you test label printing to see if this is fixed for you?

**Comment by mjy** [comment]
It is not live.
