### ISSUE TITLE
Deaccesioned specimens or loaned specimens need banner when they are searched for/filtered

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#3192]
### Feature or enhancement

This enhancement is referencing closed issue #1234. 

1) Building upon that enhancement, I need to be able to see the Deaccessioned Specimen banner pop up when I am searching for specimens (the search bar autofills the results). Same thing for specimens that are on loan.

2) Another enhancement would be to add a checked box or button to Filter Collection Objects that says something like "include deaccessioned specimens". We do a lot of data extraction from TW and it is impossible to tell which are deaccessioned if I am downloading the DwC/CSV of data.

Example of banner that I would like to see when searching for specimens.
<img width="1440" alt="Screen Shot 2022-11-09 at 1 49 20 PM" src="https://user-images.githubusercontent.com/75492546/200927503-b769bb80-a611-4bb6-9dac-5c9ae3f9c562.png">
 Example of what I would like to see in Filter Collection Objects but for Deaccessioned Specimens.
<img width="416" alt="Screen Shot 2022-11-09 at 1 58 45 PM" src="https://user-images.githubusercontent.com/75492546/200929278-ce973be3-3dcc-4a5d-8f51-e9e76cb8c0db.png">

### Location

Task-CSD and Filter CO

### Your role

Insect Collection Assistant

**Comment by mjy** [comment]
Added issue: https://github.com/SpeciesFileGroup/taxonworks/issues/3195.  Will come in unified filter branch.

* [ ] Added "Loan" banner for specimens.
