### ISSUE TITLE
LepIndex - references with multiple authors do not appear to have been migrated

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#32]
Sources with multiple authors appear to be absent e.g. ‘Ballmer & Pratt 1992’, ‘Basquin & Cadiou, 1986’, ‘Behounek & Hacker, 1990’, ‘Beck, Kobes & Ahola, 1993’.

**Comment by proceps** [comment]
Issue with cached value generated. The Source is in the database. 
The author string "Beck, Kobes & Ahola" is abbreviated as "Beck, K. & A." in cached value.

**Comment by mjy** [comment]
We're going to handle this on the import by converting to a more Bibtex friendly format.  Should be fixed next time around.

**Comment by mjy** [comment]
Fixed- use the development view to see the data as fully rendered.  The bibtex value has the multiple "and" in there, so this looks a little funny as a raw value, but it's handled fine in rendering.  New records will reference people directly.
