### ISSUE TITLE
Staged images - handle Left - T [Was :Staged image pattern]

### ISSUE THREAD

**Issue by Camehalek** [SpeciesFileGroup/taxonworks#3204]
There is an option for right-T but all of my images were staged as left-T. There is currently no option for this.

**Comment by kleintom** [comment]
Looks like Left-T is an option now, can this issue be closed?
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/fc0648f6-5bd4-42d2-88a0-6770c0a187ab)

**Comment by mjy** [comment]
@kleintom thanks for this careful look!  We can indeed close this.
