### ISSUE TITLE
Task - Filter Nomenclature - with gender and form classification

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3212]
As a user, I need to filter on gender and form classifications (masculine or adjective). At the moment, the list of classifications is restricted to nomenclatural statuses only

**Comment by jlpereira** [comment]
Do you want to include this in the same facet or a new one?

**Comment by proceps** [comment]
I think it will work with the same one

**Comment by mjy** [comment]
New one.

**Comment by jlpereira** [comment]
> New one. Needs different param.

It's the same

**Comment by mjy** [comment]
Sorry- though this mean had the gender forms filled out.
