### ISSUE TITLE
Model - Identifier::Global - Add Zoobank identifier

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#322]
Need a new subclass for Zoobank identifiers.  http://zoobank.org/

* @dimus or @deepreef can likely get you the format, or point you to the docs. I suspect it's a URI based.
* Limit to TaxonName (or maybe just Protonym) in validation.

**Comment by mjy** [comment]
This is just a LSID resolved to zoobank, eg: http://zoobank.org/Identifiers.json/6EA8BB2A-A57B-47C1-953E-042D8CD8E0E2, so no new model is needed.  Question is whether zoobank LSIDs correspond 1:1 NOMEN instances?

**Comment by deepreef** [comment]
Can you point me to a clear definition of "NOMEN"?  ZooBank issues LSIDs for three classes of objects: Agents (people and organizations); References (including publications), and Nomenclatural Acts (a subset of all Taxon Name Usage instances; TNUs).  Strictly speaking the LSIDs issued by ZooBank for nomenclatural acts identify the conceptual intersection of a Protonym and a Reference (i.e., a TNU).  Protonyms themselves are a subset of TNUs, representing the first assertion of a scientific taxon name.  Identifiers issued by ZooBank to Protonyms (the vast majority of nomenclatural acts) can effectively be thought of as an identifier issued to a scientific "name" -- but this word means different things to different people.  So, depending on the exact definition of NOMEN, it may well be the case that each NOMEN instance corresponds exactly to one ZooBank Nomenclatural Act LSID; but the reverse is probably not true (i.e., not all ZooBank Nomenclatural Acts will have a corresponding NOMEN instance).

In any case, if you can provide me with an explicit definition & scope for NOMEN, I can probably provide a more definitive answer to this.

By the way, all ZooBank LSIDs correspond precisely (sameAs) to the associated GNUB UUID (i.e., the UUID embedded within each ZooBank LSID).  The LSID prefix is just dereferencing metadata for exactly the same data object.

**Comment by mjy** [comment]
Thanks @deepreef.  I think you answered the question: `Strictly speaking the LSIDs issued by ZooBank for nomenclatural acts identify the conceptual intersection of a Protonym and a Reference (i.e., a TNU)`.  I'm going to close this issue as we don't really have to do anything more to support this.

What you described, in TW speak, is an instance of Identifier::Global::LSID on an instance of (Original) Citation on an instance of a Protonym.  Simplified- an identifier that uniquely identifies the (original) citation of a protonym.

NOMEN- https://github.com/SpeciesFileGroup/nomen
Some examples of its application: https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/concepts/TaxonWorksNomenclature.pdf
