### ISSUE TITLE
[Bug]: 1.	Task- Browse Collecting Events - Layout overlapp bug

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3221]
### Steps to reproduce the bug

```bash
Hotspot on 'next' button obscured by CE table overlap in Chrome Version 108.0.5359.96 Windows 10 Enterprise 21H2. (Works properly on MacOS using Chrome)
```

### Screenshot

![Browse CE hotspotv2](https://user-images.githubusercontent.com/74991451/206545110-27f6269d-5ae4-4622-be51-33746f18f5ef.jpg)

### Environment

Sandbox

### Version

build 9ee302250

### Browser Used

chrome version 108.0.5359.96

**Comment by michesposito** [comment]
@bpescador, @cgrinter, @rich-keller

**Comment by mjy** [comment]
@AntWeb-org we're going to tackle this when we re-do Browse collecting event as it makes more sense to do it in that context.

**Comment by mjy** [comment]
Closing as fixing elsewhere.
