### ISSUE TITLE
3.	Task - Browse Collecting Events – Feature requests

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3223]
### Feature or enhancement

1.	Send all COs associated with a given CE to the CO Match function, and allow COs to be exported/downloaded; better yet, allow COs to be exported directly without having to send to CO Match function
2.	Would like all 'edit' options to be consistent and easily accessible across the board - far left, navigate panel, under ‘Previous/Next’ buttons preferred
3.	'Previous/Next by ID' button needed on display page under Navigate
4.	Would like a TOTAL number displayed of COs for CE
5.	Include ability to sort COs displayed for a given CE by clicking on table column heading

### Location

Task - Browse Collecting Events

**Comment by michesposito** [comment]
@bpescador, @cgrinter, @rich-keller

**Comment by mjy** [comment]
> Send all COs associated with a given CE to the CO Match function, and allow COs to be exported/downloaded; better yet, allow COs to be exported directly without having to send to CO Match function

Coming in unified filters branch.

> Would like all 'edit' options to be consistent and easily accessible across the board - far left, navigate panel, under ‘Previous/Next’ buttons preferred

> 'Previous/Next by ID' button needed on display page under Navigate

Addressed in other issues, will fix/resolve there.

>  Would like a TOTAL number displayed of COs for CE

Coming in revamp of Browse CE.  Recorded in #3222.

Closing as addressed in other issues.  I copied some features to them.  Please add individual issues for those things I messed up and did not address elsewhere.
