### ISSUE TITLE
Task - Browse Collection Objects - Next/previous buttons unhidden behind Go (Feature request).

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3229]
### Feature or enhancement

Would like a 'Previous/Next by ID' button on CO display page that is not hidden within additional 'Go'/Navigate button. Similar to 'Previous/Next' found in Browse CE display but with 'by ID'.

### Location

Task - Browse Collection Objects

**Comment by Gerutha** [comment]
@bpescador, @cgrinter, @rich-keller

**Comment by mjy** [comment]
Can you clarify whether you want this by true ID, i.e. internal, with no semantic meaning, or by a proxy, i.e. Catalog Number?

**Comment by mjy** [comment]
And b) would a hotkey bound to next/previous be a suitable work-around?

**Comment by AntWeb-org** [comment]
Catalog number would be great.
I'd try the workaround for starters.

**Comment by AntWeb-org** [comment]
Thanks for the feedback. I'll send each feature request separately unless they are connected in some way. Do you prefer UI Issues separate as well or itemized?

**Comment by mjy** [comment]
Itemized please! Thanks.
