### ISSUE TITLE
[Bug]: Task - Browse Collection Objects - Bug 

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3232]
### Steps to reproduce the bug

```bash
Pencil icon (edit) does not work on BCO page. 
There is a hotspot hand, color shade change and mouse rollover saying "pencil icon" but it does nothing on the click.
```

### Environment

Sandbox

### Version

build 64eba3530 on 2022-12-12T15:46:38Z

### Browser Used

Chrome Version 108.0.5359.99

**Comment by AntWeb-org** [comment]
@bpescador, @cgrinter, @rich-keller

**Comment by jlpereira** [comment]
This was already fixed today
