### ISSUE TITLE
Radial annotator - Ctrl + C

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3233]
Ctrl + C (copy) standard windows behavior is overwritten with some navigation, which is very inconvenient. Could you please do not overwrite standard Windows shortcuts.

**Comment by mjy** [comment]
What is this linked to currently?

**Comment by proceps** [comment]
one of the sectors, I believe Confidences.

**Comment by proceps** [comment]
it actually jumps between citations and confidences.

**Comment by mjy** [comment]
@jlpereira leave the 'c' for Citations.  Change to confidences to "n" if it is free.

Then, if, any annotator form is open, disable the pie-switching keys.

**Comment by proceps** [comment]
I am using Ctrl-C inside annotor.

**Comment by mjy** [comment]
Not before you are opening a form, there is nothing to Ctrl-C, is there?

**Comment by proceps** [comment]
true

**Comment by jlpereira** [comment]
> Ctrl + C (copy) standard windows behavior is overwritten with some navigation, which is very inconvenient. Could you please do not overwrite standard Windows shortcuts.

It isn't overriding Ctrl+C
Radial annotator has a function to navegate between slices using the first letter of the slice. So if you press "C" it will open "Citations", if you press again, it will open "Confidence" or whatever slice is present for that object. Shortcuts are disabled when the focus is on an INPUT or TEXTAREA element. But clearly we need to change this and use a key combination to avoid problems like this.

**Comment by jlpereira** [comment]
Changed to key combination:

Mac: Ctrl + First letter of the annotator
Windows/Linux: Alt + First letter of the annotator
