### ISSUE TITLE
Task - Browse Collecting Event - Edit Collecting Event: Add/Current 'X' is not visible

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3245]
### Feature or enhancement

 In BCE click Edit/Pencil icon to edit CE then click the Add/Current button for popup panels

After clicking ‘Add/Current’ button, the 'X' on the popup overlay to dismiss the popup is not visible. The dark 'X' is hidden in the dark header background (see red circle in screenshot). **Fix:** make ‘X’ white, similar to the other popup overlays

@bpescador, @cgrinter, @rich-keller

### Location

Task - Browse Collecting Event - Edit Collecting Event

### Screenshot, napkin sketch of interface, or conceptual description

![add current](https://user-images.githubusercontent.com/74991451/207705217-72a0723c-00f1-44cb-b219-699a192980bf.jpg)

**Comment by AntWeb-org** [comment]
Revisiting this issue, in an Edit Collecting Event record that has no Add/Current information, the panel is long enough that the "X" to close the pop up window is not visible. It is past the scrollbar on the right of the screen.

![image](https://user-images.githubusercontent.com/74991451/216156478-49733534-24e4-49a4-af32-03365a59d034.png)

**Comment by jlpereira** [comment]
Sorry, it's a different issue. I will fix it

**Comment by AntWeb-org** [comment]
I tacked it on to the original issue. Pardon the confusion.
