### ISSUE TITLE
Task - Browse Collecting Event - Edit Collecting Event: Add/Current: no identifiers displayed

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3246]
### Feature or enhancement

In BCE, click Edit/pencil icon to edit CE, click Add/Current button. 

After clicking ‘Add/Current’ the panel displaying the COs associated with that CE does not show the identifier/catalog number or determination (see screenshot/ignore red circle here). **Fix:** display the catalog number and determination (OTU?). The ID number is not useful to us.

@bpescador, @cgrinter, @rich-keller

### Location

Task - Browse Collecting Event - Edit Collecting Event

### Screenshot, napkin sketch of interface, or conceptual description

![add current](https://user-images.githubusercontent.com/74991451/207706385-06febd9c-ecc9-4ad5-814e-14ec7e011305.jpg)

**Comment by tmcelrath** [comment]
Seconded, this is very annoying. Would love to see the catalog numbers/determinations I just created without a refresh.

**Comment by jlpereira** [comment]
Months ago, we made some changes on the server responses when we implemented extend parameter to optimize and reduce response time. Because of that, these attributes were missing there. Let us know if you see problems like this on other places to fix it.
