### ISSUE TITLE
[Bug]: Task - Geographic Area Lookup: excluding geographic areas

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3247]
### Steps to reproduce the bug

```bash
1. Go to Geographic Area Lookup task
2. type in "Baja"
3. results exclude Baja, Mexico

A search for “Baja” (Return only records that have GIS shapes? checked or unchecked) yields results in the county of Baja in Hungary only, excludes Baja, Mexico

@bpescador, @cgrinter, @rich-keller
```

### Screenshot

![geo area lookup](https://user-images.githubusercontent.com/74991451/207727373-08541876-7d05-40f8-9158-40fe2faab095.jpg)

### Expected behavior

I would like the Geographic Area Lookup to find all instances of "Baja" and would like the search to be case insensitive since "baja" yields no results.

### Environment

Sandbox

### Version

build 64eba3530 on 2022-12-12T15:46:38Z

### Browser Used

Chrome Version 108.0.5359.99

**Comment by mjy** [comment]
The tool is made to simplify creating batch imports by finding exact matches.  Unfortunately we only have the undeveloped "GeographicArea" Show (see comments re not being the ideal).

Is this the area otherwise? https://sfg.taxonworks.org/geographic_areas/14710

**Comment by tmcelrath** [comment]
Replicated: here are all the "Bajas" that result from a simple search in the GeoArea field in Edit Collecting Event:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/11411328/207870283-0b7d6a00-e363-440c-a563-83e1ab548f16.png">

**Comment by mjy** [comment]
It's the very first record, isn't it?

<img width="874" alt="Screen Shot 2022-12-15 at 8 30 17 AM" src="https://user-images.githubusercontent.com/22600/207886848-5cd88dd9-4bf8-465b-b3cd-5c419a92746f.png">

**Comment by AntWeb-org** [comment]
It's the first record in the Filter tasks but I am only getting the one result in the Geographic Area Lookup task.

**Comment by mjy** [comment]
Two things I thought of here.
1) While you can't edit GeographicAreas, you can add alternate values to them!  You can use the radial annotator to provide translations, or different forms of the name. 
2) These alternate values *do not* get picked up on the Geographic Area Lookup task though.  It might be that we want this, but again, that task is basically for building offline datasets, not really browsing and checking the data.  It depends on exact matches to return IDs.

I suppose I'm overlooking what specific part of the curatorial process are you envisioning needing the Geographic Area Lookup for?

**Comment by AntWeb-org** [comment]
An example would be imported data that bypassed quality control and/or includes typos. A, country, ADM1, state or province might be incorrectly spelled or may/may not include a needed diacritic. I could theoretically edit those typos in the GA Lookup and it will link to all associated CEs.

But if there is a typo then there would be no result in the GA Lookup? That begs the question; how would I find those mistakes? I could use the Filter but you cannot do partial name searches in Filters and I the dropdown menu only provides correct information.

**Comment by mjy** [comment]
> An example would be imported data that bypassed quality control and/or includes typos. A, country, ADM1, state or province might be incorrectly spelled or may/may not include a needed diacritic. I could theoretically edit those typos in the GA Lookup and it will link to all associated CEs.

You can use the GA autocomplete to find the record in question and provide an AlternateValue of various types.  GeographicAreas are controlled, and their name is not editable directly. You won't be adding new ones and incorrectly spelling them.  You determine you have the correct, preferably, but it's shape, which defines the  true nature of the perhaps multiple-named entity.  I think you will find very few misspellings (but likely some) in the GA list.  

> But if there is a typo then there would be no result in the GA Lookup? That begs the question; how would I find those mistakes? I could use the Filter but you cannot do partial name searches in Filters and I the dropdown menu only provides correct information.

 I think this kind of error in the scenario is not really possible.  COs are, or not, linked to GAs.  If they are linked to the wrong GA, then a spatial query might catch them, and you can update the CEs accordingly, or point to the correct entity.  This is the benefit of using a controlled vocabulary, you can't make the kind of mistake you are outlining.  You can make other mistakes, and you can have incomplete data, and alternate spellings might be required.
