### ISSUE TITLE
[Bug]: Task - Geographic Area Lookup: cannot edit geographic area

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3248]
### Steps to reproduce the bug

```bash
1. Go to Geographic Area Lookup task
2. type in "United Kingdom"
3. click on "United Kingdom" under 'Details', 'Name'

Edit button is greyed out on Geographic areas page for the country, as are all options above the 'Attributes' panel

@bpescador, @cgrinter, @rich-keller
```

### Screenshot

![geo area edit](https://user-images.githubusercontent.com/74991451/207729515-6423762e-5a7b-43f4-8592-c900f916330d.jpg)

### Expected behavior

I would like to be able to edit Geographic Areas if there are typos in our data or if we need to update or add to geographic area names historically.

### Environment

Sandbox

### Version

build 64eba3530 on 2022-12-12T15:46:38Z

### Browser Used

Chrome Version 108.0.5359.99

**Comment by mjy** [comment]
GeographicAreas are community data, the are editable by no-one.  The resources is updated by concensus, for example we added 2nd level subdivisions to China, Brazil and a couple other places recently.
