### ISSUE TITLE
[Bug]: Click "Manage Synonymy" in Edit Taxon Name task does not redirect

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3250]
### Steps to reproduce the bug

```bash
1. Open Edit Taxon Name for a given name
2. Test the menu bar that jumps to sections in this task (e. g. Author, Status, etc.)
3. All work as expected except for **Manage Synonymy** which does not result in any jump to another section in the task.
4. Is this because there's no synonymy entered yet for this name? Or is it supposed to jump to a different section of the form?
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/207948811-079f88e0-122d-4817-9296-0cc0dbcfa4bf.png)

### Expected behavior

Based on the behavior of the other options to jump to different sections of the form, I expect **Manage Synonomy** to do the same.

### Environment

Sandbox

### Sandbox Used

workshop, project "testing 12"

### Version

v0.29.6

### Browser Used

firefox

**Comment by mjy** [comment]
@debpaul @jlpereira That section is dynamically present.  @jlpereira let's remove if not present if we can?

**Comment by debpaul** [comment]
@mjy thanks. If it is dynamically present, perhaps we just "gray" it out unless it's relevant to the Taxon Name being edited?
