### ISSUE TITLE
[Bug]: Filter Staged Images display cropped weirdly

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3260]
### Steps to reproduce the bug

```bash
1. When I select >100 images via changing the URL in the API request in Filter Staged Images
2. Then the image hexagons display, but they are cut off after ~100, and cannot be selected
3. 
...
```

### Screenshot

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/11411328/208544661-d1ca20ab-3fe2-43ba-a4f2-9a43c9c02e75.png">

### Expected behavior

Should be able to at least scroll to see them. 

### Environment

Production

### Version

0.30.1

### Browser Used

Chrome

**Comment by jlpereira** [comment]
@mjy It seems this already have a predefined size from the backend. We can recalculate it from the frontend side using getBBox function. However, it seems the response is limited to 110 records.
