### ISSUE TITLE
[Bug]: CASTOR attaching new name to root and not to selected taxonname

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3261]
### Steps to reproduce the bug

```bash
1.upload file (see below)
2.select parent name
3.select also create OTU and hit preview

preview shows root as parent and not selected taxonname 
...
```

### Screenshot

<img width="1669" alt="Screen Shot 2022-12-21 at 12 38 36 PM" src="https://user-images.githubusercontent.com/9273125/208969572-f41af83c-4d71-466c-a8d7-f4d9d013af13.png">
<img width="1670" alt="Screen Shot 2022-12-21 at 12 38 12 PM" src="https://user-images.githubusercontent.com/9273125/208969575-d78b6924-2b65-4865-a7da-e3b3fb348350.png">

### Expected behavior

I expecte to have the selected taxonname as parent and not root

### Additional Screenshots

Here is the tsv i tried to upload:

[Untitled spreadsheet - Sheet1 (3).xls](https://github.com/SpeciesFileGroup/taxonworks/files/10279996/Untitled.spreadsheet.-.Sheet1.3.xls)

### Environment

Sandbox

### Sandbox Used

Bogolyok

### Browser Used

Chrome

**Comment by mjy** [comment]
Closing, I beleve this is resolved in rebranded NOMEN version.
