### ISSUE TITLE
[Bug]: Task - Browse Collection Objects: recently added 'Go' arrows do not work

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3262]
### Steps to reproduce the bug

```bash
Based on [#3229](https://github.com/SpeciesFileGroup/taxonworks/issues/3229) submission workaround.

From the BCO task, you can click the Go button to enable the Navigate popup in order to choose Previous/Next by ID, but the arrows allowing the scroll through IDs are grayed out/inoperable.

@bpescador, @chrisgrinter, @rich-keller
```

### Screenshot

![BCO_go](https://user-images.githubusercontent.com/74991451/208987730-7f297c2a-ae90-4119-9768-9cef74ca3f83.jpg)

### Expected behavior

I would like the arrows to scroll Previous/Next by ID. Perhaps similar to CSD ID by identifier. see additional screenshot

### Environment

Sandbox

### Version

build 40d115751 on 2022-12-20T13:17:02Z

### Browser Used

Chrome Version 108.0.5359.99

**Comment by AntWeb-org** [comment]
![CSD_ID](https://user-images.githubusercontent.com/74991451/208989645-cc464096-e217-4395-ab5b-d30fc10e4536.jpg)

**Comment by mjy** [comment]
Arrows turn on when there are options available. It appears in this case we couldn't calculate previous and next. We'll have to see why catalog-numbers (by default it starts with these) are not usable in this context.
