### ISSUE TITLE
Task - Simple New Specimen: destroying records is clunky

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3284]
### Feature or enhancement

After entering a SNS and saving, the new CO shows up in a table of recently created COs below.

In order to delete a record from the SNS table, you have to scroll all the way to the right and select the third radial button.

Clicking destroy then typing delete takes you to the Data, Collection Objects search page (see screenshot) and not back to the SNS form. You have to hit ‘back’ arrow to get back to SNS form and then hit refresh to delete the CO from the table.

Instead, a double-click feature on the CO in the table could take you to the CO record. You can delete the CO from there where you can see all data associated.

I understand the destroy/delete option but not the Data, Collection Objects route. Entering COs here is totally different.

@bpescador, @chrisgrinter, @rich-keller

### Location

Task - Simple New Specimen

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/74991451/212760469-521f0807-18a2-4c76-af3d-20c7d4c09aa7.png)

**Comment by mjy** [comment]
@jlpereira move actions to left on table.  Destroy async.
