### ISSUE TITLE
Add New Zealand bioregionalisation geographic areas

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#3294]
### Feature or enhancement

A bioregionalisation system has been developed for New Zealand which subdivides the country into 29 regions. These do not correspond to local governmental areas, but they have been found to be useful and have gained wide use among New Zealand-based entomologists in particular. Having these regions available within sfg.taxonworks.org as level 1 regions nested within New Zealand would be really great, thank you.

More information, including the shapefile, metadata and licensing details can be downloaded from https://lris.scinfo.org.nz/layer/48165-nz-area-codes-for-recording-specimen-localities/

Please document the use of the import task, to allow replication of the process in a local instance of Taxonworks.

### Location

Geographic areas

**Comment by mjy** [comment]
@sdjbrown these are live on sfg.taxonworks.org.

**Comment by mjy** [comment]
https://lris.scinfo.org.nz/license/landcare-data-use-licence-v1/

All parents are "New Zeleand". 

`data_origin`:  `crosby_1998`

**Comment by sdjbrown** [comment]
Sounds good. Though, make sure "Zealand" is spelled correctly ;)

**Comment by mjy** [comment]
Closing as resolvable in #3979
