### ISSUE TITLE
New Preparation type: "Herbarium sheet"

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#3305]
### Feature or enhancement

Please add a new type of Preparation (list from Pill box to Ethanol) for plants: the "Herbarium sheet"

### Location

Preparation types list in Comprehensive specimen digitization

### Your role

Researcher

**Comment by mjy** [comment]
Anyone can add a preparation type through Data -> Preparation types.  Preparation types are shared, so please include as an accurate as possible definition so that others can benefit from your category.

**Comment by camwebb** [comment]
oops - sorry, noob question :-)
