### ISSUE TITLE
Unified CO Filter: save custom filter

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3307]
### Feature or enhancement

We will be using the "custom" filter option almost exclusively. 
After selecting the "custom" option for the filter, there should be a "save" option to create custom queries that we use often instead of having to unselect all options then check each box over and over.

@bpescador, @chrisgrinter, @rich-keller

### Location

Filter, Collection objects

**Comment by mjy** [comment]
We anticipated this, we want more testing and feedback as to how the sorting works.  For example we are almost certain people will want ot arbitrarily order their columns.

**Comment by AntWeb-org** [comment]
If we can reorder and save the custom layout preferences as well as the columns in the results, that would be great. 
The popup options do not currently fit all of the layout preferences without scrolling right/down. We will not use many of these options but the option we will use is off to the side (not visible). I can see many not realizing that they need to scroll.

**Comment by jlpereira** [comment]
Implemented today [#3756]

No need to press a save button, It will be save your changes automatically when you change/sort properties
