### ISSUE TITLE
[Bug]: Unified Filter CO: download [click] does not download [and close modal] [Edited]

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3313]
### Steps to reproduce the bug

```bash
1.GA = Arizona
2.Taxon name = Pogonomyrmex
3.Results = 118
4.Select 250 records per page
5.Click Filter again
6.Download DWC

The download only filters by predicates but does not include catalog numbers or taxon names/OTUs.
Download button does not work either.

@bpescador, @chrisgrinter, @rich-kelle


...
```

### Screenshot

![image](https://user-images.githubusercontent.com/74991451/221279234-c7c32f92-1f06-4d3a-b275-59d238198773.png)

### Expected behavior

I would like to have more options for predicate downloads such as the catalog number, trip code, and taxon name/OTU. Can these options be customizable?

### Environment

Sandbox

### Version

build 5728b2068d2f on 2023-02-24T16:52:28Z

### Browser Used

Version 110.0.5481.178

**Comment by mjy** [comment]
Overlaps #3280

**Comment by mjy** [comment]
@jlpereira I think the solution here is now:

* User clicks download
* Get success respose.
* Close or replace content in modals with "Generating Download.  It will be available shortly on the [Dwc Dashboard](link to /tasks/dwc/dashboard) (opens in new tab icon/functionality.
* Provide a 'Close' button to close the dialog if the user does not want to click link to Dashboard
