### ISSUE TITLE
[Bug]: DwCA will not import in sandbox

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#3314]
### Steps to reproduce the bug

```bash
1.Download DwCA from GBIF. (<https://doi.org/10.15468/dl.tn3sr3> used.)
2. Try to upload in <https://sandbox.taxonworks.org/tasks/dwca_import/index>

gives a popup, status 500, internal server error.

The DwCA from GBIF will actually not validate. See [issue](https://github.com/gbif/portal-feedback/issues/4587). If it is fixed, renaming `metadata.xml` to `eml.xml`, this new ZIP will still not import.
```

### Environment

Sandbox

### Sandbox Used

sanbox

### Version

b0420eef216d 

### Browser Used

firefox

**Comment by mjy** [comment]
Confirmed, thanks.  Should be fixed on next release.

@LocoDelAssembly this is a missed `exists?`.  Though I had them all but will check again.

**Comment by LocoDelAssembly** [comment]
`dwc-archive` required changes to be Ruby 3.2-compatible. Thanks for reporting!
