### ISSUE TITLE
A way to handle ex and in parts of a taxon name

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#3315]
### Feature or enhancement

We are hoping to be able to semantically enter the _ex_ and _in_ parts of botanical names:

 * _Ex_: "if the publication of the name by the initial author was invalid, the ex author was the author who subsequently published the combination validly. 
 * _In_: if initial author or ex author were responsible for the combination but were not actually the authors of the publication in which that combination first appeared, the author(s) of the publication should be added after _in_, usually with some bibliographic citation details following.)

E.g., _Salix alaxensis_ subsp. _glauca_ (Andersson _ex_ DC.) R. Coville _ex_ Jones _in_ Smith 1923

Perhaps we should just enter this as a verbatim string?

### Location

Task - New taxon name

### Screenshot, napkin sketch of interface, or conceptual description

Not sure...! It may be very tricky to implement. Thanks.

### Your role

Taxonomist

**Comment by proceps** [comment]
If I understand correctly, according to ICN, the author before '_ex_' is optional and in many cases '_ex_' is used confusingly with '_in_' authors. At the moment, we do not cover this in TW model. If we take the formula "Author1 ex Author2 in Author3".

Author3 is the author(s) of the publication and covered as source Authors in TW. 

Author2 is the author(s) responsible for the TaxonName description and covered as TaxonName Authors in TW.

Author1 is a reference to an earlier invalid name. We have an invalidating TaxonName relationship which links that invalid name to a valid name, if we need to semantically construct an author string based on a previously described invalid name, we need a special relationship (like a basionym, but distinct from it, indicating that the older name is the basis for the 'ex' relationship). What would be a correct name of this relationship of an invalid name to valid name to indicate that this name usage in a historical publication is the basis for the author citation?

**Comment by camwebb** [comment]
> What would be a correct name of this relationship of an invalid name to valid name to indicate that this name usage in a historical publication is the basis for the author citation?

"_republished validly as_"?

(I'm checking with a colleague too.)

**Comment by camwebb** [comment]
@proceps A related observation: In TW, if I give a name both a Person author (e.g. Smith) and a Source (e.g. Jones 1975) , then look in Browse Nomenclature, the History section for that name use _ex_ for the source. E.g. "_Salix glauca_ Smith _ex_ Jones, 1975". This is different from the behavior you cite above ("Author2 in Author3"), which would appear as "_Salix glauca_ Smith _in_ Jones, 1975"

**Comment by mjy** [comment]
Ping @proceps ^

**Comment by proceps** [comment]
I will look into it.

**Comment by camwebb** [comment]
Been working on this more, in the _Ephedra_ case.

> We have an invalidating TaxonName relationship which links that invalid name to a valid name

Currently there is only an "ICZN set as invalid of". Could you please create a "ICN set as invalid of". This would help with encoding the name relationship, even before you have created a tool to semantically construct the correct "Author1 ex Author2 in Author3" string. Thanks.

**Comment by camwebb** [comment]
Thanks! I see that was a lot of work.

I tested it in the Sandbox and it does exactly what we need: Name A1 ex A2 in A3 (see [image](https://user-images.githubusercontent.com/1167435/233409202-30669bd0-f0fc-434c-94cb-7a0606cd12db.png)). 🎉
