### ISSUE TITLE
[Bug]: Download TnT and nexus file for certain matrix, BeValid Scaphoideini species

### ISSUE THREAD

**Issue by anase24** [SpeciesFileGroup/taxonworks#3316]
### Steps to reproduce the bug

```bash
Download TnT and nexus file from matrix BeValid Scaphoideini species and others it takes some time then the time out without responses
```

### Screenshot

![image](https://user-images.githubusercontent.com/60975227/221685694-dc05dcce-bfd8-4df4-bc63-7726e2298843.png)

### Environment

Production

**Comment by proceps** [comment]
All downloads are timed out in about 50sec.

**Comment by mjy** [comment]
Should be resolved, was a sfg cluster issue.
