### ISSUE TITLE
'von Brandt' style (prefixed) names render inverted in full citation using citeproc/csl/styles

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#332]
When I use `prefix: 'von', last_name: 'Brandt'` as a Person, and I reference that person in `authors:` of a BibTeX spec, then the `cached_author_string` renders "correctly", but the native BibTex rendering renders with a comma.  

* Confirm this is expected behaviour, everything going into the bibtex renderer seems to be ok.

**Comment by proceps** [comment]
duplicate
