### ISSUE TITLE
Task - Comprehensive Specimen Digitization: combine panels

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3320]
### Feature or enhancement

On the CSD page there is a lot of white space next to the 'Attributes/custom attributes' panel. 
Can the second custom attributes panel be brought up alongside the first attributes/custom attributes panel or perhaps combine both panels? 

I'm not sure if both custom attributes panels are strictly for AntWeb data but there is a lot of overlapping data between the collecting events panel - between verbatim and parsed - and the two panels of custom attributes. There is also some extra data that can only be entered in the custom attributes panels (the only place to enter the biogeographic region, microhabitat and DNA notes). Is there a way to cut down on all the overlapping data entry currently required? Perhaps incorporate some of the custom attributes into the CO and CE panels so entering the data will flow better?

The data entry process right now is a bit flowless and fractured between a variety of panels requiring a top, down, up, over and down pattern of entry.

@bpescador, @chrisgrinter, @rich-keller, @AntWeb-org

### Location

Task - Comprehensive Specimen Digitization

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/74991451/222273778-e8f100e8-33dd-420c-b6c5-5315b83a77ea.png)

![image](https://user-images.githubusercontent.com/74991451/222273897-92e81767-f2f5-4cd1-b4b5-53315dbefbd0.png)

**Comment by mjy** [comment]
No, I don't think so, this would confuse the semantics.  The top is attributes on CollectionObject, the bottom is in the Collecting event panel.
