### ISSUE TITLE
delete taxon_name_classification by ID

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3323]
I need an interface where I can delete a taxon_name_classification by an ID.
I have one or few classifications probably from the initial migration which need to be deleted
in the data, I can see the list of classification but they are not open in view or edit mode, clicking on a taxon_name_classification is resolved to a taxon_name page.
I can see a classification using related data on taxon_name, but again, there is no delete button, and clicking on classification is resolved to a taxon_name. 
The classification is not visible in any tasks. I assume that this is extremely rare case, the easiest solution would be to use standard tools in the view/edit interfaces in DATA mode.

**Comment by mjy** [comment]
@proceps can't you just go to the name in edit mode and destroy it there?!

**Comment by proceps** [comment]
No I have about 10 genus level classes assigned by mistake to families, those are not visible on the Edit page. This is just an legacy of an old migration. I can just add this to a migration, which I need to run on the production DB shortly.

**Comment by mjy** [comment]
@proceps - don't do a migration for 10, just give me the IDs in chat.
