### ISSUE TITLE
[Bug]: "Cached values should be updated" no longer works.

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3324]
### Steps to reproduce the bug

```bash
When I press the button nothing happens. Or the button remains.
```

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
just pushed the fix, did not noticed the bug report before.

**Comment by mjy** [comment]
@proceps make sure you update CHANGELOG.md

**Comment by adrik29** [comment]
Hi, all: it is working now for me here....
