### ISSUE TITLE
[Bug]: Original combination and rank

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3325]
### Steps to reproduce the bug

```bash
In the module "Original combination and rank", the option "Set as current" no longer works.
```

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
The original combination relationship is created only for self, but not for other ranks (genus, subgenus, etc.). The original combination is not displayed before the page is reloaded manually.
A subsequent combination section works as expected.

**Comment by adrik29** [comment]
Sorry, Dmitry, I don't understand. It used to work BEFORE today's great overhaul.
If you wrote "set as current" the system would return the genus in the current combination...

**Comment by proceps** [comment]
Adriano, this was a comment to José to fix the Bug. We had a massive update today, do not be surprised to see some other bugs. Please report what you can find and we will try to fix those as soon as possible.

**Comment by adrik29** [comment]
Ah, now I understand. Thanks, I will keep an eye out for anomalous behavior.
Cheers.
