### ISSUE TITLE
[Bug]: Loans showing too much documentation

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3326]
### Steps to reproduce the bug

```bash
1. When I am Browsing a Loan
2. And I click the Edit Loan Object Radial
3. Then I click on Documentation (I see one document)
4. Then it takes a long time to load.
5. And I see 500 documents (possibly ALL documentation)
...
```

### Screenshot

Pre clicking:
![image](https://user-images.githubusercontent.com/11411328/223490377-a33cd2f5-ff35-4475-9b70-9efcae450a45.png)

After clicking:
![image](https://user-images.githubusercontent.com/11411328/223490483-f1888ebf-aa1b-4472-beb3-93ef152c041a.png)

### Expected behavior

Should only see the already added documentation. 

### Environment

Production

### Version

0.31.0

### Browser Used

Chrome

**Comment by tmcelrath** [comment]
I just noticed this happening in Notes too? I think I see that you fixed it there too?

**Comment by mjy** [comment]
It was happening in a couple of places, I will check notes, but if you find others best to ping us here.

**Comment by mjy** [comment]
Confirmed that Notes is OK via radial annotator.
