### ISSUE TITLE
[Bug]: Taxon name doesn't appear in "Citations by source" module

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3338]
### Steps to reproduce the bug

```bash
1. I have registered species Ischyropsalis ruffoi Caporiacco, 1947, which is a junior synonym of Ischyropsalis strandi Kratochvíl, 1936.
2. However, species name doesn't appear in the corresponding Citations by source page.
3. I suspect it might be because of another persistent bug which manifests whenever author name has a preposition such as "de" or "di".
See here:
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=321915
https://sfg.taxonworks.org/tasks/nomenclature/by_source?source_id=110638
```

### Screenshot

![image](https://user-images.githubusercontent.com/46284943/223868154-5d24c451-405f-4b04-86d4-4db38011ed6e.png)
![image](https://user-images.githubusercontent.com/46284943/223868242-5ae60817-59a4-4aaa-9095-f686a03f9596.png)

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
Original combination for the taxon is missing, that is why the blank record is displayed. But it is still a bug.

**Comment by adrik29** [comment]
Thanks, Dmitry! It was missing because of some bug due to the new overhaul. We couldn't always register -- it kept disappearing... Now it seems all OK.

**Comment by mjy** [comment]
@adrik29 are you saying we can close this issue now?

**Comment by mjy** [comment]
Thanks, closing for now.

**Comment by adrik29** [comment]
Uh... the bug is back. I entered two new combinations and they appear only as placeholders in the "Citations by source" module. The original citation is OK, I have even created OTUs, thinking that might be the problem, but nothing works.

![image](https://user-images.githubusercontent.com/46284943/224565890-7c2ef597-d67d-4afe-8b26-c52c132c41af.png)
https://sfg.taxonworks.org/tasks/nomenclature/by_source?source_id=131692

![image](https://user-images.githubusercontent.com/46284943/224565959-615385c7-53e0-4240-b973-676b872ce2b3.png)
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=321630
