### ISSUE TITLE
Data-Geographic Area: option to add new GA

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3339]
### Feature or enhancement

After selecting Data then Geographic Areas, there is no option to enter a new GA. Can there be a "new" option in GAs similar to the "new" option in Georeferences? There should be another avenue for entering new GAs other than through the CE.

I know we had numerous GA Lookup back and forths but I'm not sure we touched on actually entering new GAs, only trying to find existing GAs. 

@bpescador, @chrisgrinter, @rich-keller

### Location

Data-Geographic Area

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/74991451/223869420-51c10968-ae63-4fa0-aae3-9f454c681da7.png)

![image](https://user-images.githubusercontent.com/74991451/223869470-fd9dd480-8507-4919-a011-7468e951ca5d.png)

**Comment by mjy** [comment]
Geographic Areas are controlled and will only be updated by request to developers at this point.  For example see https://github.com/SpeciesFileGroup/taxonworks/issues/3294.  We don't anticipate this changing as we need to keep the semantics well defined.

We also are planning, at some point, to add user-specific shapes via a secondary model, see https://github.com/SpeciesFileGroup/taxonworks/issues/1954.
