### ISSUE TITLE
[Bug]: "Clone last citation" not working

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#3342]
### Steps to reproduce the bug

```bash
1. Select a taxon in "Browse OTUs"
2. Click "Quick Forms" icon and select "Asserted distributions"
3. Select a citation and page number and geographic area to make a new Asserted Distribution
4. Click "Clone last citation"---no citation is entered
...
```

### Expected behavior

Until recently (c. 2 weeks ago was the last time I attempted this action), clicking "Clone last citation" worked as expected---the source and page number that had been most recently added was cloned into this space.

### Environment

Production

### Version

 v0.31.1 

### Browser Used

Microsoft Edge Version 110.0.1587.63 (Official build) (64-bit)

**Comment by jlpereira** [comment]
This was fixed today

**Comment by sdjbrown** [comment]
Man, you guys are amazing. Confirmed that it all works as expected at this end. Thank you very much!
