### ISSUE TITLE
[Bug]: Filter Sources Radial displays document that is not there apparently

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3348]
### Steps to reproduce the bug

```bash
1. Filter Sources, in Haliplidae Project on Production
  2. Housekeeping = Lesley Deem
  3. Documents = "With"
  4. Returns 4 hits, 2 in project, 2 not. 1 with a PDF as expected
5. See first 3 hits (in screen shot) where radial annotator shows that a **Document** exists for this Source. 
6. Click **Document** in the Radial and there's no Document there. (Same thing happens for other items in the Annotator that show something is supposedly there, say for Identifier).


NOTE: We found this issue when @lesleyrose asked: How do I see / note that a Source has a PDF associated?
```

### Screenshot

![LD1_sourcePDF_FilterNotAsExpected1](https://user-images.githubusercontent.com/2990155/225454476-cababc9d-87b7-446b-bc6a-89f44220974c.PNG)
![LD1_sourcePDF_FilterNotAsExpected2](https://user-images.githubusercontent.com/2990155/225454489-fc721b7a-f9a5-45f3-912c-b46a2242b107.PNG)
![LD1_sourcePDF_FilterNotAsExpected3](https://user-images.githubusercontent.com/2990155/225454496-63cd8fa3-7921-44c3-b2d7-66fa96888abc.PNG)

### Expected behavior

We're not sure if those objects that are referenced in the Radial are real or not.

We can say, that for the 4th record (Source = Watts 1988 paper) the result is as expected. The PDF she uploaded is there and does appear in the radial and Documentation window as we would expect.

### Environment

Production

### Browser Used

Chrome on a PC

**Comment by jlpereira** [comment]
@mjy the document may have been uploaded to a different project. I think we're not checking the total according to this
