### ISSUE TITLE
Task - Filter nomenclature - results with higher classification

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3350]
I would like to have an option to present higher classification for Filtered results (something like what we have in Nomenclature stats).
If the higher classification is presented, the taxa should be sorted hierarchically by default. 
Alternatively, the data from Filter nomenclature could be sent to an interface (Nomenclature stats?) which is doing sorting.
The data should be downloadable as an CSV file.

**Comment by mjy** [comment]
Closing with cross-reference to #2121
