### ISSUE TITLE
[Bug]: Filter CO's by "Identifier" with option Exact gives no results

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#3353]
### Steps to reproduce the bug

```bash
1.When I Filter COs by Identifier and select option Exact, there is no result, even though I know the collection object with that exact identifier exists. 
2.If you choose Partial as the selected option, it does give a result.
3.Is this a bug? What is the difference between exact and partial? 
...
```

### Screenshot

<img width="1440" alt="Screen Shot 2023-03-17 at 4 44 41 PM" src="https://user-images.githubusercontent.com/75492546/226059060-8aaf773b-f543-4e29-b2a9-c6a5acd07e34.png">

<img width="1244" alt="Screen Shot 2023-03-17 at 4 48 06 PM" src="https://user-images.githubusercontent.com/75492546/226059283-cc661df5-7609-4e71-914f-bad440cfdaa2.png">

### Environment

Production

### Version

v0.31.3

### Browser Used

chrome

**Comment by mjy** [comment]
You must include the namespace short name, ie the full identifier, unless the namespace is virtual.
