### ISSUE TITLE
Task - Filter nomenclature - missing combinations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3358]
Filter nomenclature task does not return combinations.

**Comment by proceps** [comment]
When I search for a genus names and descendants, combinations are out of the list.

**Comment by mjy** [comment]
Add failing specification please.

**Comment by proceps** [comment]
I am searching for a genus name Zygina in 3i project. and I use descendants options. I expect to see valid and invalid names, as well as combinations. May be it is little bit less critical for the Filter interface, but the same endpoint is used now to select descendants to synonymize two genera. When I add synonymy relationship, I get a list of taxa which need to be assigned to a new parent. The combinations are excluded from this list now. Tested Combination/Protonym option in Filter nomenclature, it does not work when descentands are selected.

**Comment by mjy** [comment]
I (think) I know what you want, I want a coded unit test please, this should be working already on first glance.

**Comment by mjy** [comment]
Closing as re-interpreted after discussion with @proceps.
