### ISSUE TITLE
Task - Radial annotator - Alternative values are not displayed on Geographic Areas and Sources.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3363]
I can crate a new alternative value, but cannot see it once the radial is reopened

**Comment by mjy** [comment]
@proceps there are differences b/w Source (community) an non- are they problematic in both?

**Comment by proceps** [comment]
Yes, on both. I tried non community data (e.g. TN), alternative values are visible there, but not on Sources and Geographic areas.

**Comment by mjy** [comment]
Test dev  please, potential fix posted there.
