### ISSUE TITLE
Adding Left T pattern in staged image section on New Image Task Page

### ISSUE THREAD

**Issue by ggpagurus** [SpeciesFileGroup/taxonworks#3367]
### Feature or enhancement

On the Task: New image page there is a Right T option but no Left T option. The insect stages used by our collection require a Left T pattern and the use of other patterns causes issues with upload and transcription.

### Location

https://sfg.taxonworks.org/tasks/images/new_image/index

### Screenshot, napkin sketch of interface, or conceptual description

<img width="1821" alt="Screen Shot 2023-03-25 at 7 50 32 PM" src="https://user-images.githubusercontent.com/108902839/227747782-6e10942f-5a2b-4b14-bb9b-533daf13d206.png">

### Your role

Imaging Technician

**Comment by mjy** [comment]
Ping @ggpagurus please provide an example image if you can?

**Comment by ggpagurus** [comment]
This is the configuration I am looking for, let me know if you have issues with the file size
![LeftTconfiguration](https://github.com/SpeciesFileGroup/taxonworks/assets/108902839/dd617be7-5dcd-44d2-80eb-919a00359f2c)

**Comment by mjy** [comment]
Thanks @ggpagurus, it's with the next release.
