### ISSUE TITLE
Task - "All in one" specimen digitization form

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#337]
# Overview

> As a curator I want to use a single form to enter "everything" I know about a single specimen.  My task is not super concerned with speed, but more-so with completeness.

The interface will allow the user to provide data on:

* All the basic collection object attributes (total, preparation type, catalog number, repository etc.)
* Collecting Events (including drafting a label)
* Determinations
* Biocuration Attributes (user customizable male/female etc)
* User defined collecting event attributes (e.g. bodies of water, etc.)
* In-line depictions (images) for collection objects
* In-line depictions (images) for collecting events

In addition it will provide:

* The ability to annotate everything (collection objects, collecting events) with the already created radial annotator (== images, notes, data attributes, protocols, documents, etc.)
* Persistent hiding/showing of *some* (not all) elements of the interface 
* Partially customizable form elements for collecting events (user sortable input groups within columns)
* Quick access to georeferencing
* Quick access to biological relationships
* Quick access to type assertions

And in the future a more advanced interface for:

* Containerization

# Anticipated required endpoints

## Layout 
* [x] GET `/project_members.json`
* [x] PATCH `/project_members?&layouts={}`
* [ ] user definable data attributes sets per Model

# Data
* [x] REST to /collection_objects
* [x] REST to /collecting_events
* [x] REST to /type_materials
* [x] REST to /taxon_determinations
* [x] REST to /depictions
* [x] REST to /biological_associations

* [x] /collection_events/:id (index to collecting events filter SQL)

#387  Inferrence

* [ ] GET /collecting_events/suggest.json?label=Text

* [ ] Search for object or accession code
* [x] Create, clone, and increment identifier
* [ ] Look back? in geography smart selector

**Comment by mjy** [comment]
Concept and "exploded" task (all elements shown, rather than collapsed in parts).

<img width="597" alt="screen shot 2018-05-08 at 10 06 22 am" src="https://user-images.githubusercontent.com/22600/39765612-dddd97e6-52a7-11e8-9a28-ae3e9d78c7e0.png">
<img width="1135" alt="screen shot 2018-05-08 at 10 06 33 am" src="https://user-images.githubusercontent.com/22600/39765613-ddfb0bdc-52a7-11e8-9dc5-1aacba9dc4c6.png">
<img width="506" alt="screen shot 2018-05-08 at 10 06 42 am" src="https://user-images.githubusercontent.com/22600/39765614-de0cf7a2-52a7-11e8-8ecf-3a406e44d56a.png">

**Comment by mjy** [comment]
Todo: 

* [ ] Only show side bar with object list in container when "Add" button (see below) is clicked, otherwise just keep info in the given form
* [ ] Make all text areas for buffered * and label * 60 columns and 5 lines long
* [ ] Expand bufferend and depiections rows to full width
* [ ] Add the text and the eye that will show hide buffered/depictions rows.  This should be saved in user preferences
* [ ] Visually connect OTU smart selector buttons to the OTU autocomplete to start
* [ ] Use a Role picker smart selector for all roles (taxon determiner, type designator, collector)
* [ ] Use the blue pin to allow user to pin the collecting event on the pinboard as the designated CE
* [ ] Add a "Now" link beside Year, Month, Day that populates those fileds with todays date
* [ ] Change blue "New" Button to read "Add".  
* [ ] Make new blue "New" button beside reset, clicking it uses all the default values in a new form.
* [ ] Make Namespace lockable
* [ ] Make Repository lockable, and referencable with Blue pinned button from pinboard

**Comment by mjy** [comment]
* [ ] Group and formation autocompletes need to wire up as the are in the default collecting event field
* [ ] Radial annotator beside image on creation.
* [ ] Test removing async (We have Current now in place)
* [ ] Add ctrl-s to hot key save
* [ ] Add ctrl-a to hot key add
* [ ] Add ctrl-r to hot key reset
* [ ] Add ctrl-n to hot key new
* [ ] At ctrl-l to lock all values into a new record (== clone)
* [ ] If buffered collecting event is filled, then there is a button above CollectingEvent#label that is "Clone from specimen"  Clicking that copies it down into label.

**Comment by jlpereira** [comment]
* [ ] whitespace/css should be same for all smart selectors - is repository smart selected yet?
* [ ] same for isolating CE smart selector style
* [ ] (note to me we need a taxon name smart selector ... mmm, I think we have on on Citations by source? (for type material)
* [ ] if user adds namespace, but no identifier, then that section gets a warning triangle or visiaul cue, both have to be present to create an identifier, and a save seems to show that it was successfull when it hasn't been when just namespace is selected
* [ ] the intial plan had a eye icon to make buffered determination and images rows seperately collapsable (collapse also recorded as a preferency), this could be important for managing screen size
* [ ] After select of repository, add a button to reset it to nil.
* [ ] ! namespace needs to be lockable
* [ ] possible to make determination list have pen/edit icon?
* [ ] split words into two lines to better balance in drag/drop image inputs
* [ ] whitespace b/w Start date and its' fields (same for end date)

**Comment by mjy** [comment]
* [ ] Remove create/clone/next 
* [ ] Remove create, clone, and increment identifier
* [ ] Isolate search to it's own, top row
* [ ] Rename 'Save all' to 'Save', move it to be adjacent the Reset
* [ ] Add, at same level of 'Save all', 'Save and new' behaviour is an (overall) new record with locked values in place
* [ ]There should only be one catalog number per 'Save all'.  Move it to it's own section below search, in line with save buttons that are justified to right
* [ ] Print label need to be 45 columns by 12 rows
*[ ] Document label needs to be 45 columns by 6 rows.

**Comment by mjy** [comment]
Behaviour note-

# Events
1 - global save of everything
2 - append row to container/collection object
3 - unlock all lock buttons
4 - assign values from all locked inputs to current records
5 - reset the whole page, as if it was hit for the very first time
6 - increment identifier
7 - create virtual container and move single object to container

# Buttons

## Save
1

## Save and new
1,5,4 (if increment checked then also 6)

## Reset
1,3,5

## Add to container (1 record/CO present)
1,7,2,4
Notes: never 6

## Add to container (> record/CO present)
2,4 
Notes: never 6

**Comment by mjy** [comment]
Branch has merged.  Subequent requests for changes should come as *individual* issues.  Thanks @jlpereira!
