### ISSUE TITLE
Task - New source - New from Bibtex

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3372]
When a new source created from Bibtex, it is automatically saved (no confirmation to the user).
Expected behavior, the new source is stubbed, but the user can preview and modify it before saving.
New from crossref already stubs the record before saving.

**Comment by mjy** [comment]
I think this is slightly different- you paste in BibTeX with known values, so you have a chance to edit before you even submit.  Editing afterwards is also trivial?  (ctrl-s is your friend)

**Comment by proceps** [comment]
My main concern is, that I just realized that the source is create. There is no confirmation. The address line does not show source id, etc. I created a number of duplicates, because I did not realize that the source is created every time the bibtex is parsed. I would prefer to have a unified behavior an all parsing interfaces. You are right, Editing afterwards is simple. 
Side note. Ctrl+S does not work on PC, it saves htlm file on the hard drive.

**Comment by mjy** [comment]
We definitely need to fire the notice for saved if it is not showing.

**Comment by proceps** [comment]
It would be better not to save record to be consistent with other functionality on the form.

**Comment by jlpereira** [comment]
> We definitely need to fire the notice for saved if it is not showing.

We already have a notice for it: `New source from BibTeX created.`

**Comment by jlpereira** [comment]
> My main concern is, that I just realized that the source is create. There is no confirmation. The address line does not show source id, etc. I created a number of duplicates, because I did not realize that the source is created every time the bibtex is parsed. I would prefer to have a unified behavior an all parsing interfaces. You are right, Editing afterwards is simple. Side note. Ctrl+S does not work on PC, it saves htlm file on the hard drive.

Ctrl + S (Mac)
Alt + S (Win/Linux)

**Comment by mjy** [comment]
Autosave in some places, but not others.  I'm going to close this as not critical.
