### ISSUE TITLE
Use CO Match to return items from loan

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3387]
### Feature or enhancement

I would like to use Collection Object Match not just to add objects to a loan, but also to return them.
Use the same format as in Edit Loans. 
Select all matched collection objects, mark as any of the loan statuses, and also add date. 

### Location

Collection object match

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://user-images.githubusercontent.com/11411328/234381316-9b2e802f-7b2f-4811-8cf2-e17b77fef68f.png)

### Your role

Collection manager

**Comment by tmcelrath** [comment]
@mjy any chance we can add this by next release? I have a spreadsheet with over 2000+ catalog numbers I do NOT want to return/click one by one.

**Comment by mjy** [comment]
@tmcelrath not by the next minor release, sorry, but we can try and get this integrated into the CO filter (a new loan radial) soonish.

**Comment by mjy** [comment]
CO filter has match (most filters do now)

Imagine in CO filter a new radial with slices to add/return etc. objects to <some loan>.  A far more poweful way to select and deal with specimen/loan relationships I think?

**Comment by tmcelrath** [comment]
Ah, cool. Yeah, that would work.

**Comment by mjy** [comment]
I'm envision batch updates to objects in other ways merging to filter, or at least originating in filter when more complex.

**Comment by tmcelrath** [comment]
Just as a comparison @mjy , it took me four _**hours**_ to return items from a large loan _from a spreadsheet where I had all the numbers available_, vs. **2 _minutes_** to add those numbers to a new loan. This is ABSOLUTELY a priority for me now.

**Comment by tmcelrath** [comment]
That was for ~300 numbers. I have ~2000 in an upcoming returned loan to do next. By that logic returning the loan will take ~27 hoursish :0

**Comment by mjy** [comment]
I can't believe you let it run for 4 hours :).  Something definitely wrong there.  Not suprising as Filter CO conects a *ton* of things, but that latency suggests big problem with the underlying query.

**Comment by tmcelrath** [comment]
No no. There is no way to do it automatically. That's me doing it manually. 

I'm just comparing the automatic adding things to loans vs. the manual removing things from loans.

**Comment by tmcelrath** [comment]
So, adding, automatic, with identifier matching = 2 minutes.
So removing, manual, clicking over 300 objects and comparing them to two different spreadsheets = 4 hours. 

Need an automatic way to remove from a loan given a set of catalog numbers.

**Comment by mjy** [comment]
Radial.

3 Slices.

* Add
* Return
* Return and add

Inputs: (params are all the same as used in loan_items)

### Add
* Loan (autocomplete to loan, or smart selector if available)

### Return
* Status (same as loan item row)
* Date returned (with button to set for "Now")

### Return and add
2 sections (basically we are returning from one loan AND adding the returned to a loan)
1) "Return"
* Status (same as loan item row)
* Date returned (with button to set for "Now")

2) "Add"
* Loan (autocomplete to loan, or smart selector if available)

_All forms include typed confirmation after green button clicked (Add, Return, Return and add)_
