### ISSUE TITLE
Grammar to improve autocomplete for geographic areas [edited]

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3389]
### Steps to reproduce the bug

```bash
1. When I am a selecting a geographic area
2. And the area has a name of "Washington"
3. Then the list is too long and I can't find the one I want.
4. And I can't add "state" or "county" or even match the full name (e.g. "United States: Ohio: Washington" for https://sfg.taxonworks.org/geographic_areas/29091) to find the right level of geographic area.
```

### Screenshot

<img width="427" alt="image" src="https://user-images.githubusercontent.com/11411328/235183327-710a6eef-e1d3-49ea-86df-adf041cc2eff.png">

### Expected behavior

I want to be able to add either of the following to narrow it down:

- Administrative level: e.g. Washington state would pull up all the state/provinces matching washington
- the exact level combo name: e.g. United States Ohio Washington would pull up Washington county Ohio.

### Environment

Production

### Version

0.32.2

### Browser Used

Chrome

**Comment by mjy** [comment]
DYK?  You can append the first letters of the parents name to delimit the result to children:

`IL Ch` -> Only Champaigns in Illinois.

**Comment by tmcelrath** [comment]
That is nowhere in any documentation AFAIK. Would be super useful to have on help. 

Also you have it backwards, it's "Ch IL" - which gives totally different results from "IL Ch"

**Comment by mjy** [comment]
We definitely need a new section on autocompletes and their magic/approach.

FYI same pattern is available for Taxon Names (thanks for catching the flip).

**Comment by mjy** [comment]
@tmcelrath given the search pattern you now know is this still an issue for you?

**Comment by tmcelrath** [comment]
Yes, I think both suggestions I gave will help with a more intuitive search.

**Comment by mjy** [comment]
Cross-linking and closing for https://github.com/SpeciesFileGroup/taxonworks/issues/3519.
