### ISSUE TITLE
[Bug]: Identifiers not showing up from Radial Annotator

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3393]
### Steps to reproduce the bug

```bash
1. For a given Person where I know they have **Identifiers** I expect to see them when I open the **Radial Annotator.**
2. When I go this person's **Show** interface, I see the identifiers as expected.
3. When I click on the **Radial Annotator**, I see the expected number of identifiers in the Radial wedge for Identifiers. 
4. When I click on the **Identifiers* wedge to open the pop-up, there are no identifiers there at all (of any type).
5. Examples: see record for Jennifier Giron (who has both an ORCID and a Q number), and see screenshots below using me as an example.
...
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/235725437-1f7c2cc2-c683-4449-a3b4-c1fb6f3f7820.png)
![image](https://user-images.githubusercontent.com/2990155/235725562-9583c49a-cef5-4343-a21b-faf7c36a4df4.png)
![image](https://user-images.githubusercontent.com/2990155/235725673-5273dce1-b51a-4941-8988-4f2f54067e57.png)

### Expected behavior

When I click on the **Identifer** wedge in the **Radial Annotator**, I expect to see the identifiers there.

### Environment

Production

### Version

v0.32.2

### Browser Used

firefox

**Comment by proceps** [comment]
The similar bug is on Sources. If it has DOI, it is not visible in the radial (did not checked for other sectors).

**Comment by mjy** [comment]
@proceps We clearly need unit tests here.  If you could help that would be grant.  Perhaps in a new spec.
