### ISSUE TITLE
New Image Task: add "no delimiter" option to Staged Image to upload images without a stage

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#3400]
### Feature or enhancement

When mass uploading minimal specimen images without a stage, New Image task does not recognize the images and there is no way to upload images without a delimiter. 

I can upload the images manually, however it would be useful to upload them all into TW at once and transcribe from there.

For example, we acquired a donation of specimens and we've been taking images of the specimens & labels without a stage. 
![IMG_INHS930192](https://user-images.githubusercontent.com/75492546/236263473-e8d4d4d9-80a5-4f3a-997f-3ae1a65803bd.JPG)

The TW Image processor does process the image edited like this, with "Horizontal Split" selected for Pattern:
![IMG_INHS930192 (1)](https://user-images.githubusercontent.com/75492546/236263550-e63bc4f4-301b-472e-a8af-e4ff469781a3.JPG)

This is an extra 2 step process to edit the images. And for hundreds of images it would take too much time. 
Just an idea for enhancement if a stage is not available for imaging. 

### Location

Task-New Image

### Your role

Insect Collection Assistant

**Comment by lvhart2** [comment]
Matt,

I actually have been dropping them into CSD and parsing them that way, however I would like to have the option to get all the photos into TW first and then filter them out and begin parsing that way too. Currently I am housing the images on Box but in order for more people to have access to the images it would be convenient to already have them in TW. I don't rely on the transcribing tool to be honest. The issue is that they won't even upload in New Image Task if the photo isn't staged.


Thanks,
Lily V. Hart (she/her)
Insect Collection Assistant
Aquatic Entomology Research Assistant
Illinois Natural History Survey
***@***.***
312-330-5643
________________________________

**Comment by mjy** [comment]
Got it.  To confirm:
* You want to simply drop 50 images at a time and have each one stub/create a related collection object. 
* After this you could click next through comprehensive to process them?
