### ISSUE TITLE
[Bug]: DwC Importer doesn't import dwc:collectionCode, what to do?

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3401]
### Steps to reproduce the bug

```bash
1. Using the DwC Importer, for Paleo Data upload
2. One field in their dataset is dwc:collectionCode
3. It does not go into TaxonWorks via the Importer

...
```

### Screenshot

![image](https://user-images.githubusercontent.com/2990155/236311685-6b1b56f0-1e0f-491e-87fe-08b2dc03bf16.png)

### Expected behavior

How to get multiple collectionCodes to go in? (in some ways, analogous to the namespace issue)?
@mjtpaleo to make a list of all known dwc:collectionCodes currently being used.
We would want this value to go out to GBIF on export in dwc:collectionCode field.
Do we need to add it as a Data Attribute in the Importer?
Tagging @MJTPaleo

### Environment

Sandbox

### Sandbox Used

sandworm

### Browser Used

firefox

**Comment by debpaul** [comment]
See Blockers https://github.com/SpeciesFileGroup/migrations/issues/7
 - dwc:collectionCode is present in dataset > not uploaded to TW
   - what would be in dwc:collectionCode on export to GBIF? Do we need to add an attribute somewhere? or add this declared field to the DwC-A importer?

**Comment by mjy** [comment]
Is the physical catalog number `INHS-P 10000`?

**Comment by MJTPaleo** [comment]
Yes the physical catalog number for the INHS fossil collection is INHS-P-#### so INHS-P-10000 as an example. This has changed since our initial testing of the system when we were going to have INHSP#### or INHSP-####.

We have other collections under ours that will have other formats – some are legacy formats that we don’t want to change due to too many specimens needing changing if we alter the format. The other formats are new and will be for all new acquisitions.

ISGS-PAL##(year)-###(specimen number)
ISGS-P#
UIUC-G-#
INHS-P-#

**Comment by mjy** [comment]
For reference.  Several of the questions driving this issue are:
# "How will people find out that my data belong to my institution"?
# "How do I get all the data from my institution?

To explore these questions its useful to not imagine what's in your data but rather actually try out a reasonable approach with one of the indexers you expect your data to be found in.  Chances are this is GBIF.

### Scenario 1
You land on GBIF and search for "Perlesta".  You click through to its homepage (https://www.gbif.org/species/2004942).  You click "Occurrences".  Now you see something like this:

<img width="2239" alt="Screenshot 2023-05-05 at 9 05 13 AM" src="https://user-images.githubusercontent.com/22600/236480713-fb55c4f4-427d-454a-8ff1-e7e7430eb361.png">

Note that:
* We can see, with no reference to collectionCode, that occurrences come from a Dataset.  It's the metadata on this dataset that answer the question "what *is* my collection", a 4 letter code in collectionCode might hint it, but chances are you want much more than a hint.
* We can quickly follow the link to that dataset to get all the occurrences for that dataset.

### Scenario 2
You want to find all the occurences for the INHS insect collection.

* You search for "INHS insect collection" (or "INHS") and you get a list of datasets.  You select the pertinent one.

Note that this does not require the field `collectionCode` to be filled.

... others to explore?

**Comment by debpaul** [comment]
@mjy are you saying, that when Tommy exports the INHS Ent data ... all "12" namespaced collections go into one dataset on the way out the door? @tmcelrath

**Comment by mjy** [comment]
There is only one dataset that goes to GBIF for the INHS, yes.

**Comment by tmcelrath** [comment]
I thought we already fixed this with the namespace mapper? 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/11411328/236499179-97db2564-d1c8-474f-b2ef-baeb98007068.png">

I was able to import using several dozen namespaces associated with different repositories into my monotomidae research project.

**Comment by mjy** [comment]
Note to self.  Namespace is delimits a set of identifiers.  When it's a CatalogNumber it therefor defines a set of labeled CollectionObjects.  Is "set of collection objects" the same thing as a DwC `collection`?  If so then perhaps there is an option at export time to "also treat catalog number namespaces as collectionCode".  _Spiderman-tingles with this approach._

**Comment by mjy** [comment]
Closing for #3994 and out of date best-practice wise vs. recent (to be documented) identifier conventions.
