### ISSUE TITLE
[Bug]: DwC Importer adds dwc:occurrenceStatus and value=present, is this expected behavior?

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3403]
### Steps to reproduce the bug

```bash
1. Using the DwC Importer to upload Paleo Data
2. This dwc:occurrenceStatus field and value = present get inserted into database > these data are not in the spreadsheet.
```

### Expected behavior

Is this expected behavior? 
I get we're saying in Darwin Core speak, that this is not "absence" data.
If this is what we want, then we're good. Just need to manage expectations and document this so it's not a surprise.

tagging @MJTPaleo

### Environment

Sandbox

### Sandbox Used

sandworm

### Browser Used

firefox

**Comment by mjy** [comment]
All collection objects are by TaxonWorks definition present. It is inferred from the data and not required to be asserted.  They are not required in DwC import, nor would including "absent" in an import a) be recognized or b) follow TW semantics.

**Comment by mjy** [comment]
It is supported in AssertedDistribution.  It will be supported in upcoming `FieldOccurrence` type as well.
