### ISSUE TITLE
My external catalogue doesn't work anymore after recent changes

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3407]
### Steps to reproduce the bug

```bash
The problem seems to be with the following request:

https://sfg.taxonworks.org/api/v1/sources?token=W8kIg_iBpBG72j2EZZLhVQ&project_id=10&per=9500&page=1&in_project=true
```

### Screenshot

![image](https://user-images.githubusercontent.com/46284943/236704484-f99a72f3-978b-4fd2-8c94-a7e949e54447.png)

### Expected behavior

We make a request expecting to receive a JSON back, but when trying to parse this JSON, it gives an error: SyntaxError: Unexpected token < in JSON at position 0

That is, you have to find out what changed in TW's answer

### Environment

Production

**Comment by mjy** [comment]
@adrik29 when live you will no longer need the token(s), so you can do this: `/api/v1/sources?project_id=10&per=9500&page=1&in_project=true`.
