### ISSUE TITLE
Some TDWG GeographicalAreas are missing shapes

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#3410]
Some GeographicalAreas for TDWG area types are missing shapes:

https://sandcastle.taxonworks.org/geographic_areas/34321
https://sfg.taxonworks.org/geographic_areas/34321

Here's one with a shape for comparison:

https://sandcastle.taxonworks.org/geographic_areas/34322

Here's the full list of TDWG GAs missing shapes, although I guess maybe level 1 isn't expected to have them:

https://sfg.taxonworks.org/geographic_areas/33539 Europe tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33540 Africa tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33541 Asia Temperate tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33542 Asia Tropical tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33544 Pacific tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33545 Northern America tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33547 Antarctic tdwg_l1
https://sfg.taxonworks.org/geographic_areas/33548 Northern Europe tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33563 Siberia tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33564 Russian Far East tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33573 Indo-China tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33578 Southwestern Pacific tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33579 South-Central Pacific tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33585 Eastern Canada tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33586 Northwestern U.S.A. tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33555 West Tropical Africa tdwg_l2
https://sfg.taxonworks.org/geographic_areas/33616 Andaman Is. tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33702 Nigeria tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33765 Krasnoyarsk tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33796 Magadan tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33888 Society Is. tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33835 Norway tdwg_l3
https://sfg.taxonworks.org/geographic_areas/33701 Newfoundland tdwg_l3
https://sfg.taxonworks.org/geographic_areas/34007 Andaman Is. tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34293 Krasnoyarsk tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34376 Newfoundland tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34467 Society Is. tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34407 Norway tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34382 Nigeria tdwg_l4
https://sfg.taxonworks.org/geographic_areas/34321 Magadan tdwg_l4

Found with:
```
%w[tdwg_l1 tdwg_l2 tdwg_l3 tdwg_l4].each do |origin|
    GeographicArea.where(data_origin: origin).each do |ga|
        gagai = GeographicAreasGeographicItem.find_by(geographic_area_id: ga[:id])
        if gagai.nil?
        puts "https://sfg.taxonworks.org/geographic_areas/#{ga.id} #{ga['name']} #{ga['data_origin']}"
        end
    end
end
```

**Comment by jrflood** [comment]
Just reviewing your list ... It's strange that the level 1 shapes for Australasia and southern America are not absent.  While Australasia is somewhat simpler, it's not obvious that southern America is drastically less complex than the others (that may have had exceptions).

**Comment by mjy** [comment]
We tracked down the 30 bad shapes, all had invalid geometries or failed right-hand rules.  These are the data, script coming to add shapes shortly.

[validated_tdwg_shapes.zip](https://github.com/SpeciesFileGroup/taxonworks/files/12740366/validated_tdwg_shapes.zip)

**Comment by mjy** [comment]
[validated_tdwg_shapes.zip](https://github.com/SpeciesFileGroup/taxonworks/files/12750124/validated_tdwg_shapes.zip)

**Comment by mjy** [comment]
Script is in SFG's curation repo, it requires no configuration internally:

`rake taxonworks:fix_tdwg_shapes_import path=path/to/validated_tdwg_shapes/data/fixed_wkt/`

**Comment by LocoDelAssembly** [comment]
Log
===
```
(in /app)
1: Europe (OK)
10: Northern Europe (OK)
10NOR-OO: Norway (OK)
10NOR: Norway (OK)
2: Africa (OK)
22: West Tropical Africa (OK)
22NGA-OO: Nigeria (OK)
22NGA: Nigeria (OK)
3: Asia Temperate (OK)
30: Siberia (OK)
30KRA-OO: Krasnoyarsk (OK)
30KRA: Krasnoyarsk (OK)
31: Russian Far East (OK)
31MAG-OO: Magadan (OK)
31MAG: Magadan (OK)
4: Asia Tropical (OK)
41: Indo-China (OK)
41AND-AN: Andaman Is. (OK)
41AND: Andaman Is. (OK)
6: Pacific (OK)
60: Southwestern Pacific (OK)
61: South-Central Pacific (OK)
61SCI-OO: Society Is. (OK)
61SCI: Society Is. (OK)
7: Northern America (OK)
72: Eastern Canada (OK)
72NFL-NE: Newfoundland (OK)
72NFL: Newfoundland (OK)
73: Northwestern U.S.A. (OK)
9: Antarctic (OK)
Done!

real	0m42.407s
user	0m38.421s
sys	0m1.858s
```
