### ISSUE TITLE
[Bug]: Taxon Name Castor batch upload: if author, year is in parentheses, it does not import correctly

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3411]
### Steps to reproduce the bug

```bash
I ran into this bug using both the sample import file and a file that I created.

If author, year is in parentheses only the author imports. In the sample file, only author with no parentheses is imported, but in a file that I created sometimes the author is at least put in parentheses.
```

### Screenshot

![error](https://github.com/SpeciesFileGroup/taxonworks/assets/70152690/96a72d06-ca03-4138-9ec2-b5d7879ba487)
In import file (Smith, 1920)

### Environment

Sandbox

### Browser Used

chrome

**Comment by mjy** [comment]
@kandakoj Can you send me sample data offline, in CSV hopefully.
