### ISSUE TITLE
[Bug]: Collection Object Classification Summary Broken

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3412]
### Steps to reproduce the bug

```bash
1. Go to above task. 
2. Click summarize by Order
3. Total enumerated by order same for all orders
```

### Screenshot

<img width="1596" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/f9f0e47c-cc60-4b39-afad-32326961b226">

### Expected behavior

Should count correctly by taxon. 

### Environment

Production

### Version

0.32.3

### Browser Used

Chrome

**Comment by mjy** [comment]
Yup, we saw this on Wednesday, thanks for filing.

**Comment by tmcelrath** [comment]
Any chance for a hotfix? Want to use some graphs for SPNHC talk.

**Comment by mjy** [comment]
I can generate some locally if I can fix it. Contact me offline.
