### ISSUE TITLE
[Bug]: "status: 500 error: Internal Server Error" when attempting to use an interactive key

### ISSUE THREAD

**Issue by ccwirth** [SpeciesFileGroup/taxonworks#3416]
### Steps to reproduce the bug

```bash
1. When trying to use the "Interactive key | Edrotes" (observation_matrix_id=65) I get a status: 500 error: Internal Server Error.
2. I do not get this error when using any other interactive key from our lab.
```

### Environment

Production

### Browser Used

Chrome, Version 112.0.5615.137 (arm64)

**Comment by mjy** [comment]
@proceps, see emails. [TW-Error] interactive_key#key (ArgumentError) "comparison of Array with Array failed"

Numerous results were changed from Int to Array, I suspect this wasn't caught.

**Comment by proceps** [comment]
changed pushed. The interactive key should work when the production is updated. 
There were two problems with a particular matrix.
1. One presence/absence descriptor. All OTUs in the matrix were scored as absent.
2. Two numeric descriptors. Where measurements for one of the OTUs were scored as '0' for both min and max value.

Exceptions were added to handle the data inconsistencies.
