### ISSUE TITLE
[Bug]: Filter collection objects - filter by CE Date doesn't work

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3418]
### Steps to reproduce the bug

```bash
1.Search by any date range in collecting event:
2. All objects in project are returned.
```

### Screenshot

<img width="312" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/d30e5912-1a43-45a0-bb27-248d28854147">

Result:
<img width="478" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/e4f90521-caa1-4986-8e43-d5cbb83ef518">

### Expected behavior

Should only return objects collected between those dates

### Environment

Production

### Version

0.32.3

### Browser Used

Chrome

**Comment by jlpereira** [comment]
@mjy It works on Filter collecting event, params are the same
