### ISSUE TITLE
Task - New descriptor

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#342]
As a user I want a very basic form for creating new descriptors, augmented with the radial annotator at multiple points.

JSON endpoints (some of these are available from `matrix_row_coder` likely):
* [x] Descriptor GET
* [x] Descriptor POST
* [x] CharacterState GET
* [x] CharacterState POST
* [x] GeneAttribute GET
* [x] GeneAttribute POST

<img width="1036" alt="screen shot 2018-03-06 at 11 31 09 am" src="https://user-images.githubusercontent.com/22600/37063403-e38b34e8-215e-11e8-9468-b6fe3757c503.png">

**Comment by jlpereira** [comment]
@mjy what about those two checkbox left?

**Comment by mjy** [comment]
@jlpereira Tricky.  You see the Gene attributes section?  We need client side composition of some logic that gets posted.  It's non trivial, but the idea is that we need to select sequence IDs, and then combine them in logical notitation (that's the and/or bit).  I can't remember the exact thing to post, but it's something like `(1|2&(3|4)` where '|' == or and '&' == and.  Still NOT a high priority.  We're also missing sequence smart selector.

**Comment by jlpereira** [comment]
Already done. Closing
