### ISSUE TITLE
Filter interfaces, open multiple items for edit or view in new tabs.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3420]
This is very common action for me, I need to filter taxon names, or sources, and want to open all or some of the filtered results as new tabs for viewing or editing. I can currently do this one by one using a navigation radial. This requires 4 mouse click per item, and it is also hard to keep track what was the last item opened. I would like to select multiple and open selected items in new tab each as a single action. Probably limiting the number of items which could be open once by 50?

**Comment by mjy** [comment]
Done.  Have fun opening 500 tabs :)
