### ISSUE TITLE
where is rufus? [Bug]: 

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#3428]
### Steps to reproduce the bug

```bash
1.searching for rufus in collection objects
2. gives me screenshot below
3. I cannot scroll nor do I see how many objects have been found.
In any case Gomphocerippus rufus is missing
...
```

### Screenshot

![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/514132b4-fe90-4e48-bc6a-2992d23b21ad)

### Expected behavior

I expect a message that X rufus objects have been found.
I expect that I can scroll on the sidebar
I expected Gomphocerippus rufus to appear

### Additional Screenshots

![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/78a915e1-2352-424d-ad77-873c5d9fe744)

sidebar scroll does not work

### Environment

Sandbox

### Browser Used

firefox

**Comment by mjy** [comment]
@klausriede I would recommend using the CollectionObject filter and searching from that perspective if you are looking for potentially many specimens.  The autocomplete is often intended for use when you know the exact target.  The exact target here would be identified by a catalog number, typically.

**Comment by LocoDelAssembly** [comment]
This must be sandcastle:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/4991925/586ebb08-fee7-4efb-879d-ec8883fe2159)

But still not useful for enumerating all specimens as the list could still be larger than shown above.

**Comment by klausriede** [comment]
![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/b196ebe4-e7e2-4023-94f3-c79bba33cd5b)

so this is the screenshot from the Collection object sandcastle function. Again we do not see how many objects have been found.
Scroll bars do not work. But I do get into a collection event, albeit without event data
https://sandcastle.taxonworks.org/tasks/collection_objects/browse?collection_object_id=45988

**Comment by mjy** [comment]
Please use Filter Collection Object.  Browse modes are for single records.
