### ISSUE TITLE
question how do I add a species to a literature source

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#3429]
https://sandcastle.taxonworks.org/tasks/sources/new_source?source_id=7935

requires adding of the reference species Gomphocerippus rufus. How do I do that?

**Comment by mjy** [comment]
It sounds like you are adding a new taxon name?  If so use the New taxon name task.

Documentation is rapidly growing https://docs.taxonworks.org/guide/. You might checkout how the UCD folks are working: https://docs.taxonworks.org/guide/community-resources.html.

**Comment by typophyllum** [comment]
All the combinations (Gomphocerus rufus, Gomphocerippus rufus) are already present. In Browse Nomenclature you can click on the radial annotator at one of the citations with the desired combination, and add a new citation with this combination.

**Comment by klausriede** [comment]
found it but did not manage to add a new citation via annotator. Will try to find this in the doc. Can I annotate a locality?
