### ISSUE TITLE
[Bug]: Repository Selection does not appear in Filter Collection Objects

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3430]
### Steps to reproduce the bug

```bash
1. When I search by Repository
2. Then the selection does not appear.
```

### Screenshot

Note the successful search:

But no visible repository in search area:
<img width="1261" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/43fced45-328f-48ab-b224-a13a139f7d23">

### Expected behavior

Should be able to see Repository Client side

### Environment

Production

### Version

0.33.1

### Browser Used

Chrome

**Comment by mjy** [comment]
You have not selected a repository- that is the quick selector.  Click the circle, you should see a blue trashcan to unselect?

**Comment by tmcelrath** [comment]
Confirmed, what Dmitry said.
