### ISSUE TITLE
Make "Collection Summary" reports clickable

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3434]
### Feature or enhancement

As a user, I want to go to Collection Summary and see my summary stats:

Then, I want to click on those results and send that query to the appropriate filter so I can see those objects. 

### Location

Collection Summary

### Your role

Collection manager

**Comment by mjy** [comment]
And vice-versa.

**Comment by mjy** [comment]
See 
<img width="1011" alt="Screenshot 2023-10-12 at 12 42 06 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/fee676fa-e0bc-4ac5-a8b9-34d5aba9e4ef">
