### ISSUE TITLE
full collection data

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#3435]
### Feature or enhancement

When looking into this collection object https://sandcastle.taxonworks.org/tasks/collection_objects/browse?collection_object_id=1923 I cannot find the collector and the collection date, i.e. fundamental data for a  collection event.
maybe these data are missing? If so repsective fields should be indicated wit value NULL 

### Location

Collection objects

### Screenshot, napkin sketch of interface, or conceptual description

![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/81c118c4-c2e4-46b5-ad6a-cdbcbc4911e8)

### Your role

User

**Comment by typophyllum** [comment]
Apparently items with no data are simply omitted. The specimen from Barro Colorado Island of the same species shows the collector, but is lacking the date (May 01, 2010 to June 30, 2010).

**Comment by mjy** [comment]
Yes, in order to conserve space we remove the many fields not populated in this view.

**Comment by klausriede** [comment]
I think the basic fields should be shown: collector date place. You might omit "intentionally left blank" In the Barro Colorado case the date was not successfully migrated because it is present in old OSF

**Comment by mjy** [comment]
Deciding which fields to leave as left blank is somewhat arbitrary, some peoples key fields are not others.  I feel that this question is answered with experience.
