### ISSUE TITLE
[Bug]: timeout on updating this name

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3437]
### Steps to reproduce the bug

```bash
1. I try to update this name: https://sfg.taxonworks.org/people/134827/edit
2. It spins 
3. Then gives me a 503 error
...
```

### Environment

Production

### Version

0.33.1

### Browser Used

Chrome

**Comment by proceps** [comment]
It takes a lot of time when the person has many roles. It takes a while to save changes if the same person is used as an author for many taxa or as a source author. Apparently it takes longer if it is used as a collector. The script may just time out.

**Comment by proceps** [comment]
Trying it on local. 5 min and still running.

**Comment by mjy** [comment]
Moving this to a background task when roles > some_threshold.
