### ISSUE TITLE
[Bug]: OTU Tetrix depressa

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#3449]
### Steps to reproduce the bug

```bash
1.Searching for OTU associated with name Tetrix depressa
2. Finding the name https://sandcastle.taxonworks.org/otus/3132 but not the associated specimens (representing the OTU)
3. this leads to nowhere
...
```

### Screenshot

![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/7fb2fa6f-92ab-4889-819f-db97231b5dd8)

### Expected behavior

I expected to find some specimens because I searched for an OTU

### Environment

Sandbox

### Sandbox Used

 SANDBOX - build e3d9f275b on 2023-06-08T15:37:52

### Version

see above

### Browser Used

Firefox

**Comment by LocoDelAssembly** [comment]
There are specimens in Browse OTU: https://sandcastle.taxonworks.org/tasks/otus/browse/3132

**Comment by klausriede** [comment]
I see ! Then I should also see them via https://sandcastle.taxonworks.org/otus/3132 evtl under associated? Otherwise I think there is nothing behind this OTU (which is impossible by definition...)

**Comment by mjy** [comment]
Yes, OTUs are defined by their relationships/context. Browse OTU is where you can expect to find "everything".  It needs significant evolution, we're not quite ready to excute that yet, but getting much closer. We placed Associated on "Show" as a place to debug some values way back, I think maybe there are some things there for things like TaxonNames.  We don't plan to be comprehensive in Show, nor do we plan to add further things there for OTUs.

If you want an algorithmically iterated based on model relationships list of things related to an Otu (or any instance of data) see "Related" from the Navigating radial (has the paper airplane).  You might also check out the "Object graph" (typically vial Navigator -> All tasks).  That graph is not comprehensive.  Finally a recent talk @debpaul and I did might be of interest: https://drive.google.com/file/d/1JhlbbvWhif0iKTm9x75_0UVBNr_nsyBO/view?usp=sharing.
