### ISSUE TITLE
Pictures and type status should appear at an early stage

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#3450]
### Feature or enhancement

https://sandcastle.taxonworks.org/collection_objects/55834 Finally I found the Truxalis obesa collection object. By clicking on associated Browse collection object I found that this is a well-illustrated type. Which means that this is not an "association" but a core feature of the object: it is a type and it has an image! These infos should appear at a much earlier stage!

### Location

The picture and type status should be found at the stage illustrated below

### Screenshot, napkin sketch of interface, or conceptual description

![grafik](https://github.com/SpeciesFileGroup/taxonworks/assets/12816652/f3bee689-41e4-4385-9865-d668ca47ce44)

### Your role

OSF contributor

**Comment by mjy** [comment]
@klausriede Please note that the Data cards are meant to be "stubs", and not the primary entry point for your work.  I.e. the second Task is the canonical view, not the first.   When using a radial navigator choose "Browse" to get to those views. Links *outside* the Data context should point to this "Browse task as well"

When we develop we automatically scaffold the card views, ultimately we are planning to hide these away for debugging purposes only.
