### ISSUE TITLE
[Bug]: Edit observation matrix task - The Dynamic function to select groups of species is not working

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3454]
### Steps to reproduce the bug

```bash
1. I have selected Row and Dynamic to select a superspecies to create row for all the species included in this group.
2. I search for the taxon name: Zoniopoda iheringi [superspecies]
3. And nothing happens.
```

### Environment

Sandbox

### Sandbox Used

sancastle

### Version

build 3f0132906 on 2023-06-13T18:28:09Z 

### Browser Used

Chrome

**Comment by mjy** [comment]
Still a bug? I can't replicate with a simple test it seems to work.

**Comment by mabecabrera** [comment]
I though if I chose a genus then all the species from that genus should be listed in the rows... 
It is not working for me. I am using Chrome.

**Comment by proceps** [comment]
It does not work for me. I created a new test matrix, Selected Rows, and Dinamic, after that I picked a genus using the TaxonName search box. Nothing happens after a taxon is selected.

**Comment by proceps** [comment]
Trying it in the development, there is a lot of queries running on the background. The genus had only 12 species (plus some synonyms). It should not take that much time. Something is definitely not working properly. I personally never used dynamic rows in my project before. It is 5 min now, and the queries are still running.

**Comment by mjy** [comment]
Thanks for tests. @dimus, @mabecabrera please provide IDs of target taxon names for debugging (now that I can do that locally).

**Comment by proceps** [comment]
On sandstorm or development, you can use 374410 in 3i project, 12 species, all of those already have scores in another matrix.

**Comment by proceps** [comment]
If you want a genus without scores, use 393031, 6 species, not use in other matrices

**Comment by mabecabrera** [comment]
The ID for the taxon name I was testing is 17400. I was using sand castle. It is a genus with 16 species. I don't have any other matrices in sandcastle.

**Comment by mjy** [comment]
I found the problem, will be fixed on next release.  Don't experiment in production ;)
