### ISSUE TITLE
[Bug]: Upon DWCA export, some catalog numbers not reported

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3455]
### Steps to reproduce the bug

```bash
1. I make a CO with a catalog number.
2. I save it.
3. I export that CO.
4. That object does not have a catalog number
```

### Screenshot

Saved CO (created newly yesterday):
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/0c3fa552-08ab-498e-9cc9-9608db6f84b3)

DWC Export (note lack of catalog number):
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/e5b305be-519e-42e4-b64f-fb156ffb4c60)

Exported DWC:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/78f3c437-1bb9-4be3-a75b-0573708ce8c7)

### Expected behavior

When I save a CO with a catalog number, it should always be exported in DWC.

Not sure what the problem with indexing is, but it's definitely a problem. I can manually go to record, save it, and it fixes it. 

### Environment

Production

### Version

0.33.1

### Browser Used

Chrome

**Comment by mjy** [comment]
Mental note- or this is using delayed jobs and not being triggered on time.

**Comment by mjy** [comment]
Update.  Not all objects trigger rebuilds.  For the interm large releases should nuke and rebuild (admin side) the index.  In the medium term we will include a library that will create a record update hook.

**Comment by tmcelrath** [comment]
Any update on this? Need this asap. Would love a manual trigger for reindexing a set of records up to 1000.

**Comment by mjy** [comment]
@tmcelrath I think this is resolved now?

**Comment by tmcelrath** [comment]
Yeah I think so. Also fixed with forced re-indexing
