### ISSUE TITLE
Task - Filter sources - Add batch update functionality

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3456]
I need to add a lot of serials, and I do it manually one record in a time. I would like to use the batch update, similar to Geographic Area add to Collecting Event.

**Comment by mjy** [comment]
Just a thought that this one is significantly more dangerous/consequential as it hits Community data.

**Comment by proceps** [comment]
Yes, but in most cases I do restrict searches to the project only. As a bare minimum, I would need an option to open all selected sources as individual tabs, instead of using radial for each of them individually.

**Comment by mjy** [comment]
Serial update exists.

@jlpereira can we add another slice 'Author'.  There we can select authors as per role picker in create.  It needs a big bold warning "Updating in this fashion will delete all other Author information for this record, ensure all Authors in the source are in this list.".  Require a confirmation.
