### ISSUE TITLE
Clone Loan Directs to Old Loan New/Edit Task instead of Current New/Loan Task

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3462]
### Feature or enhancement

When I click on "CLONE" in "Browse Loan"
I get directed to the old loan new form:
<img width="1413" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/74ee8bec-b980-429c-8a47-b0b1af295d2e">

Instead, can we CLONE and direct to the nice "New Loan Task"?

### Location

Browse Loan/New Loan

### Your role

Collection manager

**Comment by debpaul** [comment]
@mjy @jlpereira would this be a **good first issue?** ( Not sure about any underlying data model changes that might be related to the "New Loan Task, else I would go ahead and **label** this a **good first issue** because it's likely only (one?) or a very few lines of code to make this re-direct).

**Comment by debpaul** [comment]
See related ticket https://github.com/SpeciesFileGroup/taxonworks/issues/3463

**Comment by mjy** [comment]
@debpaul yes, this is a good first issue!
