### ISSUE TITLE
[Bug]: TaxonName Combination soft validation for duplicates including other projects

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3466]
### Steps to reproduce the bug

```bash
1. Create a combination in one project
2. Create the same combination in another project
3. Duplicate warning soft validation appears
```

### Screenshot

https://github.com/SpeciesFileGroup/taxonworks/blob/8318d29f7a193624de5efca142a21e2baf877851/app/models/combination.rb#L446-L449

<img width="1474" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/33206210/54064927-9c74-4ad8-af23-2a9a3d71b769">

### Environment

Development (native)

### Version

e16d4364

**Comment by proceps** [comment]
Thanks for the report, I will fix it once I am back to Illinois. Or somebody can add `' project_id: self.project_id' param to WHERE.

**Comment by LordFlashmeow** [comment]
I'll make a PR, I wasn't sure if it was intended behavior or not.
