### ISSUE TITLE
Security contact for TaxonWorks?

### ISSUE THREAD

**Issue by p-** [SpeciesFileGroup/taxonworks#3470]
Hello TaxonWorks team!

I'm from the [GitHub Security Lab](https://securitylab.github.com/) and would like to report a potential vulnerability in TaxonWorks.
Could you please provide us a security contact to send the report to?

Instead of providing a security contact you can also enable [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) on this project.

Thanks!
Peter

**Comment by LocoDelAssembly** [comment]
@p- just enabled private vulnerability reporting. Not sure if it works, just in case this is my mail address: ellocodelassembler@gmail.com

Thanks

**Comment by p-** [comment]
Hi @LocoDelAssembly 
Thanks for enabling it 👍 , I've just sent the report.
Please check if you've received it.

**Comment by LocoDelAssembly** [comment]
Security advisory published. Thanks @p- , have a nice weekend!
