### ISSUE TITLE
Add pagination for controllers

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#3472]
`index` json response of controllers is not paginated, only html response is. Consumers of json response likely need update. 

- [x] labels
- [ ] observation_matrix_column_items
- [ ] observation_matrix_row_items
- [x] type_materials

**Comment by mjy** [comment]
@LocoDelAssembly I'm not going to add pagination to the last 2, we need the full result (and it's not overly large) in most cases.  Same for TypeMaterials, but in the filtering case there are at most 5-10 on average, so default pagination works, so I added i there.
