### ISSUE TITLE
Specimens linked to Taxon names 

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3473]
### Feature or enhancement

I was wondering why the system is letting us link specimens to Taxon names.

### Location

Task: New Image

**Comment by mjy** [comment]
Need more information @teleaslamellatus.  Did you mean to say "link images to taxon names"?

**Comment by debpaul** [comment]
> Need more information @teleaslamellatus. Did you mean to say "link images to taxon names"?

@mjy I think István was surprised, he expected images of specimens to be connected to OTUs, if I understood him correctly...

**Comment by debpaul** [comment]
> Images of specimens are linked to specimens. Images of OTUs are linked to OTUs. Images of TaxonNames are linked to TaxonNames (e.g. image of a card catalog card with the literal taxon name on it). We depict objects (sensu TW), we can depict most anything.

So @mjy what might be happening then, is confusion on part of students? as to where to upload images. Again, IF I understood István correctly, the images were not connected to the specimen, as expected.

**Comment by mjy** [comment]
Closing as explained (during past meeting).
