### ISSUE TITLE
[Bug]: Missing synonym record for basionym in COLDP export

### ISSUE THREAD

**Issue by dhobern** [SpeciesFileGroup/taxonworks#3482]
### Steps to reproduce the bug

```bash
1. Select Global Lepidoptera Index project
2. Create and download COLDP export for OTU Lepidoptera Linnaeus, 1758
3. In Name.csv, "Barsine rhodophila Walker, 1864" is correctly shown as the basionym for "Stigmatophora (Stigmatophora) rhodophila (Walker, 1864)", but there is no record in Synonym.csv between these two names (whereas other basionyms are shown as synonyms).
```

### Screenshot

**Here is the relevant set of rows from Name.csv in https://sfg.taxonworks.org/downloads/658:**

ID	basionymID	scientificName	authorship	rank	uninomial	genus	infragenericEpithet	specificEpithet	infraspecificEpithet	referenceID	publishedInPage	publishedInYear	original	code	status	link	remarks

60591	60591-1a9c61ff06d4beb2d224632db16c82f9	Stigmatophora (Stigmatophora) rhodophila	(Walker, 1864)	species		Stigmatophora	Stigmatophora	rhodophila				1864	false	ICZN	http://purl.obolibrary.org/obo/NOMEN_0000224		40015.00|ORIGINAL GENUS UNDETERMINED|Valid name|Noctuoidea-Arctiidae-Lithosiinae-9A-010011|Q:\Noctuoidea\Arctiidae\Lithosiinae\Drawer 9A\|FC-Noctuoidea-Arctiidae-Lithosiinae-9A-010011.jpg|BC-Noctuoidea-Arctiidae-Lithosiinae-9A-010011.jpg

60591-1a9c61ff06d4beb2d224632db16c82f9	60591-1a9c61ff06d4beb2d224632db16c82f9	Barsine rhodophila	Walker, 1864	species		Barsine		rhodophila				1864	true	ICZN			40015.00|ORIGINAL GENUS UNDETERMINED|Valid name|Noctuoidea-Arctiidae-Lithosiinae-9A-010011|Q:\Noctuoidea\Arctiidae\Lithosiinae\Drawer 9A\|FC-Noctuoidea-Arctiidae-Lithosiinae-9A-010011.jpg|BC-Noctuoidea-Arctiidae-Lithosiinae-9A-010011.jpg

899507	899507	Stigmatophora rhodophila	(Walker, 1864)			Stigmatophora		rhodophila					false				

**The corresponding record in Taxon.csv is as follows:**

ID	parentID	nameID	namePhrase	provisional	accordingToID	scrutinizer	scrutinizerID	scrutinizerDate	referenceID	extinct	temporalRangeStart	temporalRangeEnd	environment	link	remarks

452785	792163	60591													

**The only record in Synonym.csv for taxon 452785 is:**

taxonID	nameID	status	remarks	referenceID

452785	899507			

_It's unclear to me why "Stigmatophora rhodophila (Walker, 1864)" is shown as its own basionym, since this is just another combination based on Barsine rhodophila._

### Expected behavior

I would have expected an extra record in Synonym.csv:

taxonID	nameID	status	remarks	referenceID

452785	60591-1a9c61ff06d4beb2d224632db16c82f9	

### Environment

Production

### Browser Used

Vivaldi 6.1.3035.111 (Stable channel) (64-bit)

**Comment by mjy** [comment]
@dhobern @gdower was this touched by the latest minor release?

**Comment by dhobern** [comment]
Just checked the latest download and it remains unfixed.
