### ISSUE TITLE
When synonymising genera, list epithets to move in alphabetical order

### ISSUE THREAD

**Issue by dhobern** [SpeciesFileGroup/taxonworks#3486]
### Feature or enhancement

I synonymise genera as the simplest way to move large numbers (but not all) of the species from one genus to another, relying on the list that this offers me of epithets for which to change parent. Then I delete the temporary synonymy. 

This works well, but it would be much easier if the epithets were sorted in some useful way. Could they be ordered alphabetically

### Location

Task - New taxon name (when synonymising two genera)

### Your role

Data curator / biodiversity informatician

**Comment by mjy** [comment]
I don't see this on the CHANGELOG, is it released?

**Comment by mjy** [comment]
This was done.  See also the new update parent off of Filter nomenclature coming in 0.34.6:

<img width="968" alt="Screenshot 2023-10-06 at 10 41 54 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/4abefc47-6730-48e2-bca4-dbd6e734e273">
<img width="1102" alt="Screenshot 2023-10-06 at 10 41 59 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/86b50d5f-f9ca-41bd-b0e9-e67595961996">
