### ISSUE TITLE
Could we add WWF terrestrial ecoregions to our geographic areas?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3487]
### Feature or enhancement

In TW our geographic areas originate from quite a few gazetteers. And these areas are immensely useful for our project, especially after I created a huge spreadsheet with links to some of them and the hierarchic structure to be used as a customized tree.
Not it occurred to me that it would be great if the could also use the WWF terrestrial ecoregions as geographc areas.

I just don't know how easily the devs can easily implement this. There are shape files with all of those on the internet. 

In the old version I use for ARCGIS they don't match exactly the files of GADM as far as I understand.

But here there is a new version which might be compatible.

https://www.gislounge.com/terrestrial-ecoregions-gis-data/.

### Location

https://sfg.taxonworks.org/geographic_areas

### Your role

curator of project

**Comment by mjy** [comment]
Duplicate of #137.
