### ISSUE TITLE
Task - browse sources - direct link to new source, or embedded new source

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#349]
```
It would be nice to have the option to create a new source in the Browse sources tab... so that if you don't find the one you need, you can create it right from there, instead of having to go back to the main menu.
```

**Comment by JCGiron** [comment]
Same thing for when you are finished creating/editing a taxon name: have a button to go to Browse nomenclature.

**Comment by jlpereira** [comment]
Hi @JCGiron 

Already exist and option to go to Browse nomenclature after you create/edit a taxon name using the new taxon name task. 
You need to click on the name for that, i attached an example image

![example](https://user-images.githubusercontent.com/16530364/37312615-7f4f7842-262a-11e8-90b0-19d391635ddc.png)

**Comment by JCGiron** [comment]
Thanks for pointing that one out!

**Comment by mjy** [comment]
@JCGiron perhaps more importantly you can hit `ctrl-t` to flip back and forth between browse and edit views.
