### ISSUE TITLE
LepIndex - Better field titles for data attributes

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#35]
For those fields that do not map directly to TaxonWorks fields they have generated 'data attribute' fields. Understandably you use the column headers we provided. However these are not very user friendly. If we provide a list of more user friendly titles can you please use these instead e.g. ‘TS_COUNTRY‘ = ‘Type Species Country’. We can send a full list through.

**Comment by mjy** [comment]
We can do two things: 

1) You can send us the map, and we can map those values, leaving the imported data as ImportAttributes (essentially write-only).
2) We can switch these data to DataAttributes.  This means that you could edit the attribute name (supplying a real definition) after the import is in place.

Let us know your preference.

**Comment by mjy** [comment]
Not a blocking issue now.
