### ISSUE TITLE
Protonym - rendering of stated year versus year of publication

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#350]
It has been suggested that the recommended way (ICZN) to display the stated year versus the actual year of publication is to included the stated year in square brackets "[]". 

See notes [https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/manuals/NOMENCLATURE_BASICS.md](here) for how we presently represent (and display) the data.  

Things to remember- 
* This is a rendering issue, not a data representation issue.  There may be many different ways to render a name and its metadata.  
* Not all codes will follow the recommendation.

Is there a general concensus that displaying multiple years behind a name is a _good idea_?  Where are example pages, catalogs that have  used this approach?  Does this introduce more confusion or clarification?  Are there alternate ways of indicating that name became available under a code under a specific year, even though it _appeared_ to be from an earlier publication?

**Comment by mjy** [comment]
For reference the recommendation is here in the ICZN 22A.2.3 - http://www.nhm.ac.uk/hosted-sites/iczn/code/index.jsp?nfv=&article=22

**Comment by proceps** [comment]
I think it is more confusing than explaining. I could not recall seeing publications with this kind of rendering. The stated year is rendered on the publication side. We specifically have two fields for year in each publication. One is the actual year, another one is stated year.

**Comment by proceps** [comment]
The stated year should be rendered in the Source Citation, not the name string.

**Comment by mjy** [comment]
What do we do currently?
