### ISSUE TITLE
[Bug]: Browse Annotations "On" filter doesn't work for Notes

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3505]
### Steps to reproduce the bug

```bash
Go to browse annotations, click the "Notes" radio button, select an object type in the "On" menu, then click submit.

The results will include notes for all object types, not only the one you selected.
```

### Screenshot

<img width="1680" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/33206210/51ae5fd3-ec7a-47f9-83b9-45ac2648e04c">

### Environment

Sandbox, Development (native)

### Version

bf06c3da6

**Comment by mjy** [comment]
@jlpereira `on[]` needs to be changed to `note_object_type[]`
