### ISSUE TITLE
[Bug]: Bad autofill results

### ISSUE THREAD

**Issue by dhobern** [SpeciesFileGroup/taxonworks#3509]
### Steps to reproduce the bug

```bash
1. Open Global Lepidoptera Index project
2. Open New Taxon Name task
3. Enter "diehli Werny" in the "Search a taxon name..." box to navigate to the editor for _Horithyatira decorata diehli_ Werny, 1966
4. Results include many names that do not match these terms. Only the third of the first nine results (i.e. "Tethea consimilis diehli Werny, 1966") includes both strings
5. Enter "Horithyatira diehli Wern" in the same box - now _Horithyatira decorata diehli_ Werny, 1966 is at the top.
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/2c4d4a12-435e-4fae-8996-5d861902ad31)

### Expected behavior

The order of search results has changed and the intended result is now often almost impossible to find. I am sure the new behaviour is an effort to satisfy some other requirements, but I would prefer results to be ordered:

1. Exact match name first
2. Higher rank first if matching complete input
3. Accepted names before synonyms, etc. if matching complete input
4. Older names before newer if matching complete input

The third and fourth ordering factors are less important than 1 and 2.

### Environment

Production

### Browser Used

Firefox

**Comment by mjy** [comment]
@dhobern the autocomplete is experimenting with a new internal index/edit-distance approach, so it will feel distinctly different than prior.

Advantages should include, however:
* Speed, we run 1 query instead of over 20, optimizing the results of those 20.
* Spelling differences do not negate probability of good results (this is the k
* Only probable matches are returned (i.e. there is a e-like score cutoff)

Disadvantages
* Smaller search fragements (the index is based on tokens of 3) may match nothing
* Less probable matches that might still be relevant are not returned

This is definitely an experiment, we may tune it further or revert/adjust it to a new approach.  Once one understands the difference I've found it quite effective.

**Comment by dhobern** [comment]
Thanks @mjy - I do understand. The performance gain is great. However, please take my notes above as something to consider as you tune it. It seems out of balance if it returns a couple of pages of search results, one one of them includes the search strings and somewhere else in the data there are other actual matches. In the last day or so, I've accidentally created extra names I subsequently have to delete because no matter how I tried I could not find them by searching.

**Comment by dhobern** [comment]
Here's another good example. I wanted to find _Holothyatira assamensis_, so I typed "Holoth assam" and got just three matches.

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/933b1bd6-e365-4f5a-94c1-61984e8063fa)

I found what I wanted by typing "Holothyatira assam". I'm used to using the search as a flexible way to find things quickly. In many cases, all I know is that LepIndex did not have the name in either the original or the accepted current genus, so I often search using the epithet and author name. The fuzzy matches completely destroy this strategy.

**Comment by dhobern** [comment]
Another example. Just one result in the relationship box for "Holothy dieh".

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/fcf8ddad-4b11-4a6c-92d5-354d029019b2)

Oddly, adding the "l" brought the correct result up in second place:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/1a94b7c5-1f9b-4e39-811e-aeff8cbd5b7b)

Right now, the number and relevance of results seems unpredictable.

**Comment by dhobern** [comment]
Maybe it would be possible to pre-process the results from the search so any exact match is moved to the start. Or perhaps you could do something visually to format/highlight genera and other monomials so they stand out more in the midst of the species.

**Comment by hhopkins77** [comment]
Having the same problem as lesleyrose. I am having to type, in some cases, the entire species name in order for what I am looking for to show. This is leading me to think the species is not in the database. Also, in some cases, the species I am looking for does not appear on the cropped list of returns, and I have to type in the genus and species in order to get to what I need to work on. Could we have a check box to choose our search to be the way it was before?

**Comment by dhobern** [comment]
It looks like you may have reverted the function now, but here is what I was going to say...

After playing with it hard for a few days, I was still hitting lots of issues. The most acute is not being able to find names that I know are there and that do not come back until I've exactly typed every letter. The second is the tendency for near matches to appear much higher in the search results than exact matches. For example, if I was looking for something like _Epipsestis contrasta_, it is likely to give me Epiplema contrasta_ at the top and my actual choice in position seven or something. In several cases, I have clicked on the top result (not spotting the difference) and proceeded to edit the wrong name.

My suggestions (given the massive performance boost and presumed reduction in computational costs):

* Use the current search mechanism to grab the set of matches you're currently returning, but pre-sort them before display so that exact matches come first. That should retain most of the performance gain.
* When the search results are returned, add a button or a standard item in the returned list that triggers a deep fuzz-free repeat of the search. This would only get used where there is too much noise for the fuzzy match to be useful.

**Comment by dhobern** [comment]
Here is another example that takes extra time to resolve

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/8cb3716f-bfd1-4cfa-b7a4-627339acedaa)

I want to select the genus for a new species name and the entire results list is filled with other species. How can I select the genus without cloning another species?
