### ISSUE TITLE
bibtex broken from filter sources 

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#3510]
### Steps to reproduce the bug

```bash
1.I do a filter sources search on tag: Werren Genetics Chapter
2. All of the correct reference there (81 citations). I select all and I can do a download formatted just fine.
3. Problem 1 (most important): when I try do download Bibtex I get a random set of references not related the search --- there seems to be no link.
4. Problem 2 (less important)...at the bottom of the 'formatted references' there is a BibTeX button but it only gives out the formatted references.
```

### Screenshot

**Correct filter:**
<img width="1103" alt="Screen Shot 2023-08-06 at 4 12 47 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/30123556/6b61b245-c3f2-4e81-9c0e-31bef05b520e">

**Nonsense bibtext output:**
<img width="1103" alt="Screen Shot 2023-08-06 at 4 13 21 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/30123556/0e2a399b-99c9-403a-b337-eb076d9108b4">

### Environment

Production

### Browser Used

firefox

**Comment by JohnHeraty** [comment]
Not sure what you mean by which server - I am just using the Chalcidoidea database. If you tell me what to look for I will see what I can do - I know this worked beforeJohnOn Aug 7, 2023, at 10:06 AM, José Luis Pereira ***@***.***> wrote:﻿
Hello @JohnHeraty
What server is it? This was fixed last month. I think it's an old version, because looking at the second screenshot, there should be space between the buttons.

**Comment by jlpereira** [comment]
Is it https://sfg.taxonworks.org/ ?

**Comment by jlpereira** [comment]
If this is the case, try the clear your browse cache

**Comment by JohnHeraty** [comment]
I cleared the cache and restarted Firefox…. same random BibTeX entries….

**Comment by JohnHeraty** [comment]
and this is where to clear the cache, correct?

**Comment by JohnHeraty** [comment]
yes

**Comment by jlpereira** [comment]
Sorry John, I was look Download formatted option, I will check BibTeX

**Comment by JohnHeraty** [comment]
Does this take a while to get uploaded… it still does not work at my end.

sorry to bug you…

John

**Comment by jlpereira** [comment]
No problem John, the fix for this issue is already done. It will be live when we update the production. We will be releasing a minor update soon

**Comment by JohnHeraty** [comment]
Thanks!On Aug 7, 2023, at 12:05 PM, José Luis Pereira ***@***.***> wrote:﻿
No problem John, the fix for this issue is already done. It will be live when we update the production. We will be releasing a minor update soon

**Comment by jlpereira** [comment]
We released the new version @JohnHeraty

**Comment by JohnHeraty** [comment]
it works… thanks!
