### ISSUE TITLE
[Bug]: Combinations in COLDP exports lack rank

### ISSUE THREAD

**Issue by dhobern** [SpeciesFileGroup/taxonworks#3516]
### Steps to reproduce the bug

```bash
1.Open Global Lepidoptera Index project
2.Select Catalogue of Life (COLDP) exports tool
3. Enter and select Parainesis Krüger, 2015 as the OTU and click Download
4. On completion, download ZIP
5. Review Name.tsv file in download
6. Note that _Eilema restricta_ and _Eilema heterogyna_ (the two subsequent but non-current combinations) lack anything in the rank column
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/26148454/25e012ef-8018-4f2f-8b03-addcbe7f79a8)

### Expected behavior

These two combinations should have "species" in the rank column

### Environment

Production

**Comment by mjy** [comment]
@gdower Combination's are rankeless in the model, we have to determine by the finest Protonym used in the Combination in this case.  I thought we had a method for this, but perhaps not.

**Comment by gdower** [comment]
@mjy, I tested it on 3i Auchenorrhyncha and the export took 26 minutes which is about how long it usually takes so I don't think this has a major impact on export performance.  Thanks to @proceps for helping find a method to get ranks for combinations.

**Comment by dhobern** [comment]
Thank you all - this will help me greatly.
