### ISSUE TITLE
display of hyphenated author names

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3538]
In New source the names are displayed like this:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/d5931a68-e478-4dd8-816d-04521354bb48)

Then, e.g. in Browse nomenclature, the second author is displayed like this (instead of Ma, L.-B.) :
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/c3f306fc-cf5a-4b5a-a0d8-7457eaeecad4)

**Comment by typophyllum** [comment]
Changing the corresponding letters so lower case solves the problem:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/bbd390a9-ab12-43e8-a06e-e701105dcf14)
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/2af82a56-758d-4e02-9c5a-bcf7ada3ccda)

**Comment by proceps** [comment]
![Screen Shot 2023-08-31 at 2 32 28 PM](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/5a01423c-1ab3-4796-99a0-46191b08a0d5)
The best and most predictable results you will get if you add authors as Author Roles. Interpretations of the strings are always less predictable

**Comment by typophyllum** [comment]
Thanks, Dmitry. The missing "author role" another problem. Can't find where to select this. The blue tool leads to Edit taxon, but "role" isn't mentioned on that page.

**Comment by proceps** [comment]
I put a big arrow on the picture. When you add a person in the Author or Editor section, it creates different roles for this person. It could be an Author, it could be Editor, It could be TaxonName Author, it could be collector, etc. Everywhere you see a box to select a person, this is a Roll picker. Each of those is called according to selected role. You can see exactly the same interface in the Edit TaxonName page.

**Comment by typophyllum** [comment]
Thanks, Dmitry.
