### ISSUE TITLE
numbers of a taxonomic group described by year over a range

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#3539]
### Feature or enhancement

For Chalcidoidea, I would like to get a **csv output of the numbers of valid species/genera described by year since 1758**. The intent is to develop a cumulative graph of taxonomic description over time. This could be applied to any taxonomic level or time period, and parsed by valid/invalid species, although only valid is likely an important metric. Is this currently possible? It seems like something best applied to filter nomenclature (the best option) or nomenclature stats. For Chalcidoidea, the "valid" filter also needs to be coupled with "with author" to avoid ghost taxa, and thus filter nomenclature.

### Location

filter nomenclature

### Your role

curator of the chalcidoidea database

**Comment by proceps** [comment]
duplicates #2472
