### ISSUE TITLE
[Bug]: The order in the geographic levels is not correct

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3544]
### Steps to reproduce the bug

```bash
1. We created a collecting event with coordinates. 
This is the link to the record in Comprehensive Task https://sfg.taxonworks.org/tasks/accessions/comprehensive?collection_object_id=1601046
2. We were careful not to select any shape for it.
3. The hierarchical order of the names seems wrong. The Ouesso *District* is showing up before the country.
```

### Screenshot

This is a screenshot for the collecting event section in comprehensive task.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/4d53ab9d-d3c8-42b6-ab90-687a22f73630)

This is how it looks like in Browse OTU.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/b623b57d-bc2f-41aa-8b89-3c5542f2065c)

### Expected behavior

Get the correct order... First Country, then state, then district, .... etc.

### Environment

Production

### Version

 v0.34.3 

### Browser Used

chrome

**Comment by mjy** [comment]
Looks like client side.
