### ISSUE TITLE
can't select Filter Biological Associations task as a favorite [Bug]: 

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#3545]
### Steps to reproduce the bug

```bash
The little star doesn't work for any of the Filter tasks, or any of the Browse tasks.

I am using a Chrome browser.
```

### Expected behavior

I click on the little star in the task box but it doesn't turn gold

### Environment

Production

### Version

UCD 0.43.3

### Browser Used

Chrome

**Comment by mjy** [comment]
@JimWoolley if you have problems with your favorites you can try to reset them, see new button available from `Account`.

<img width="684" alt="Screenshot 2023-10-04 at 3 44 51 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/da536645-4fd5-4955-a594-775d4a125803">
