### ISSUE TITLE
How to merge unique subspecies with species?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3546]
_Brachytrupes chopardi_ had two subspecies, _Brachytrupes chopardi chopardi_ and _Brachytrupes chopardi tropicus_. After I moved the latter as full species under the genus, the nominotypical subspecies remains alone under the species. The task Merge taxon names only moved one of the citations of the subspecies to the species (two others remain at the subspecies). How can I merge these two taxa?

**Comment by proceps** [comment]
There is no merge task available. There is another open issue. At the moment, you have to delete one of the duplicates. I would usually elevate subspecies to species rank (and change the parent), after that, I would delete the original species (resolving the related data first).

**Comment by typophyllum** [comment]
Thanks, I will try this tomorrow.

I would also need to merge _Brachytrupes_ (no-author duplicate caused by migration, id=1042113) with _Brachytrupes_ Serville, 1838 (id=937758). There seems to be a relationship I cannot find and which doesn't let me destroy the former (already deleted a relationship at the latter).

**Comment by proceps** [comment]
<img width="1100" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/42e01f95-2481-404c-b93a-287c4ce5e945">

**Comment by typophyllum** [comment]
Thank you.

To the original problem: earlier in the afternoon I actually tried to  
elevate the subspecies to species, but this wasn't possible. The error  
message says: "The nominotypical subspecies chopardi can not be moved  
out of the nominal species".

**Comment by proceps** [comment]
Temporary change name of one of two names. Since I usually delete original species, I change it to something like 'speciesaaaaaaaa' so that I can easily filter it out, and also I know that I am deleting a correct one, after that, you should be able to remove the nominotypical subspecies.

**Comment by typophyllum** [comment]
This is a mess. Now I have _Brachytrupes chopardi_ (id=937767) with protonym _Brachytrypes_ [sic] _chopardidelete_, _Brachytrupes chopardidelete_ (937766), and the latter has supposed relationships to _Brachytrupes chopardi_ (1077172) and _Brachytrupes chopardi chopardi_ (1089842) which I cannot find.

**Comment by proceps** [comment]
If you look from the edit side, the name has holotype record, you have to delete or reassign it first:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/554641be-9ed7-4cbc-9840-b4e7f5009121)
you have an original combination and two subsequent combination. You cannot delete a taxon if you have any of those.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/f68b4266-aa82-44d5-89f3-1df2e8245538)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/a81689d4-c5d5-4368-b9f7-597a548e5617)

**Comment by typophyllum** [comment]
Thank you very much. This worked. The next problem is to add a citation at _Brachytrupes chopardi_ that treats it as subspecies _Brachytrupes chopardi chopardi_ (Gorochov 1993, Grylloidea of Saudi Arabia). The combination exists, so with the New combination task it doesn't work:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/b52f059c-9c27-455c-bb93-2d793447b1da)

**Comment by typophyllum** [comment]
Thank you.

Now I have very similar problem with _Brachytrupes membranaceussssssss_ Drury (id=937769) which cannot be destroyed because of relationships with _Brachytrypus_ [sic] _membranaceus_ ssp. _colosseus_  (1094362) and _Brachytrupes membranaceus_ var. _colosseus_  (1094391). The valid name is _Brachytrupes colosseus_ (937776), which has no relationship with _Brachytrupes membranaceussssssss_.

**Comment by typophyllum** [comment]
Now Belén found a way to solve it. Very complicated.

**Comment by proceps** [comment]
I added how to delete a TaxonName section to manual. Yes in some cases it could be very complicated, depending how much of the related data are linked to the TaxonName:
https://github.com/SpeciesFileGroup/taxonworks_doc/blob/development/docs/guide/Manual/nomenclature.md
