### ISSUE TITLE
Soft validation of Taxon name / page range of original source

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3548]
The Soft validation of the Taxon name is unaware of multiple page ranges of the original source. 

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/b1520f07-7b25-43f9-8274-efd4d9d04254)
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/e200f751-5a4a-4b3d-9c7f-a21a9875ecda)

The validation apparently only takes into account the first range (pp. 28–65). Page 144 is within the second (pp. 134–167). Old references often come in several installments, which usually are treated as a single reference in case they were included in an issue published in the same year.

**Comment by proceps** [comment]
Yes, the pages in the Source is a free text, there are many different formats, including roman numbers. Citation could be comming from a plate, insteade of the page number. There are many different cases when this validation may fail. It is still very useful for exact ranges.

**Comment by mjy** [comment]
Closing as explained.
