### ISSUE TITLE
Cannot create new OTU using new image tab

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3549]
### Steps to reproduce the bug

```bash
1.type Polia xanthomista nigrocincta in OTU field
```

### Screenshot

<img width="519" alt="Screen Shot 2023-09-11 at 11 28 57 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/9273125/4a07024e-b008-401b-9478-55cc22439ea3">

### Expected behavior

Should not sho up any OTU's that share only portion of the name entered, it should be exact match and the system should offer the option to generate new OTU (UNH enotmology, project 20).

### Environment

Production

### Browser Used

chrome

**Comment by mjy** [comment]
@teleaslamellatus the new option is only triggered when there are no matches in the list.  So in this case I would:
* Reverse select the text (command-shift-backarrow) and copy it
* Hit 'Delete" to clear the search
* type `zzz` to trigger the none
.. enter the name, perhaps pasting in bits you copied
