### ISSUE TITLE
On the 'Task' page, can we 'remember where we are'?

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#355]
On the 'Task' page, when you select a group of tasks using the black/white boxes at the top, it would be nice to keep track of which was the last selected start task, so that when you go back, it shows the same set as when you last selected one.

**Comment by mjy** [comment]
@TuckerJD Isn't this handled by the ability to favourite tasks and data cards?

**Comment by mjy** [comment]
Answering self after talking with @TuckerJD,  it's not.   The use case is systematically moving through the tasks one at a time.  

Solution is likely to turn the whole Hub into a Vue.js app and track state that way.  This is relatively low priority at the time, and should be done with the next major hub re-envisioning.
