### ISSUE TITLE
[Bug]: Edit taxon name- Persons- Clone from Source: Author order for taxon name does not match author order of source

### ISSUE THREAD

**Issue by kandakoj** [SpeciesFileGroup/taxonworks#3551]
### Steps to reproduce the bug

```bash
When using "Clone from Source", the author order of the taxon being created does not match the author order of the source.
```

### Screenshot

![Nomen_source](https://github.com/SpeciesFileGroup/taxonworks/assets/70152690/4a5c88cb-dd1d-42d0-8646-11d70ebf9230)
Source is Makhan and Hawkeswood
![Nomen](https://github.com/SpeciesFileGroup/taxonworks/assets/70152690/c90bfe52-63f8-4104-bd1f-1e69ba50f1d4)
But taxon authors are switched to Hawkeswood and Makhan

### Environment

Production

### Browser Used

chrome

**Comment by proceps** [comment]
Confirm
