### ISSUE TITLE
[Bug]: I used the "New" button to enter new type genus of a new family. Creation was refused.

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#3554]
### Steps to reproduce the bug

```bash
1.Created a new family in Plecoptera SF.
2.Used "new" button to enter type genus for this family.
3.Received popup stating "Name must be lower case"
3a. The genus name should be initial caps (which it was)
3b. Only the remainder of the name should be lower case (which it was)
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/61740366/752b079e-7a50-45c1-8372-d065af8ba1c3)

### Expected behavior

Expected new name to be created.

### Environment

Production

### Version

 version 0.34.3

### Browser Used

Chrome

**Comment by Aaryanpal** [comment]
I would like to contribute @hhopkins77.
Please assign

**Comment by mjy** [comment]
@hhopkins77 it only wants the monomial species, in your screenshot you are adding a capitalized genus name.

**Comment by mjy** [comment]
@Aaryanpal thanks for your interest.  We have labels, e.g. https://github.com/SpeciesFileGroup/taxonworks/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22, for issues that might be starting points, though these are quite outdated and need a little more review now.

We can flag additional issues that might be good targets, or you might jump into our chat channels and ask some questions/get familiar that way.

Thanks again for your interest.

**Comment by Aaryanpal** [comment]
Thanks you @mjy for the explanation
