### ISSUE TITLE
[Bug]: filtered species include genus names 

### ISSUE THREAD

**Issue by JohnHeraty** [SpeciesFileGroup/taxonworks#3563]
### Steps to reproduce the bug

```bash
1.filter nomenclature; Mymaridae; descendants; iczn species; valid; with authors.
2. returns 1655 records.
3. downloaded a csv of these (not a straightforward output)
4. converted in excel to 1655 names. However these include the genus names and there are 1655 csv records... so genus names are being included in the count.
...

[I don't see a spot to upload the excel file that was generated]
```

### Screenshot

<img width="980" alt="Screen Shot 2023-09-21 at 2 20 08 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/30123556/06a58f91-ab45-469b-94d6-77e4be7c1402">

### Expected behavior

5. can a simple species list be exported?
6. I need counts of species that do not include genus names. ****** important...

### Environment

Production

### Browser Used

firefox

**Comment by JohnHeraty** [comment]
delete this.. I had genus names checked as well... although the csv output could be cleaner....

**Comment by mjy** [comment]
We do have to work on the CSV formats for sure, its noted in other issues.
