### ISSUE TITLE
How to dismiss more recent synonymy and follow previous?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3564]
This is the situation: _Bolotettix exiguus_ was first synonymized with _lineatus_ and then with _histricus_.

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/a1314031-f945-4a5a-aa85-505d6fc60859)

However, Blackith 1992 and Otte 1997 also treat _lineatus_ as synonym of _histricus_. _Pseudoparatettix lineatus_ is currently valid, and since the types of both _lineatus_ and _exiguus_ are from Borneo (_Paratettix histricus_ has otherwise no records from there), it is more likely that _exiguus_ is a synonym of _lineatus_. That's how it was in the old OSF. How could I reproduce this in TW?

**Comment by mjy** [comment]
Add the synonymy on exiguus with lineatus on exiguus, with the citation(s) on that relationship, see if that works "automatically"?

**Comment by typophyllum** [comment]
The relationships are there, and TW follows the more recent one. I found no recent source that treats _exiguus_ as synonym of _lineatus_.

**Comment by mjy** [comment]
I'm not 100% clear, but 2 things jump to mind:
* Maybe you need to make a new OSF curator Source with curent year and add a citation the relationship you prefer (see screenshot)
* You can use a classification/status to assert that a name is valid, even when otherwise noted as invalid (but I don't think this is the case here?)

**Comment by typophyllum** [comment]
You mean adding a new source with just "OSF curator 2023"? This seems to be possible only as verbatim, and then the year isn't recognized. And it will probably look strange to have an irregular source among the citations.

Perhaps it should be possible to select one of several subjective-synonym relationships as the effective one even if it's not the most recent.

**Comment by mjy** [comment]
> Perhaps it should be possible to select one of several subjective-synonym relationships as the effective one even if it's not the most recent.

Unfortunately this would break a lot of the logic.  The curators really are acting as a source, and it needs to be cited at the same level, then people can assess the data without thinking of exceptions.

We can make Sources that are aggregates of People in TaxonWorks, though I just checked and UI might be broken.

But before we get that fix/resolved you could explore with something like this:

https://sandcastle.taxonworks.org/tasks/sources/new_source?source_id=62607

**Comment by typophyllum** [comment]
Thank you. This indeed moves _exiguus_ to _lineatus_
