### ISSUE TITLE
[Bug]: There´s a bug from the Filter Image Task throug unified filters to the Filter Collecting Event. 

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3567]
### Steps to reproduce the bug

```bash
1. when I have a list of results in the filter image task I use the unified filters to see the collecting data for those images.
2. I click on the collecting event slice but get no results.



### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/8fa2f94a-1f3f-49c0-b1df-bf0b12f55c5d)


### Expected behavior

I expect to see the collecting data associated to the collection objects those images represent. If there is no link between them because these are images but not depictions, I expect to have a unified filter with no option to go to collecting events.

### Additional Screenshots

_No response_

### Environment

Production

### Sandbox Used

_No response_

### Version

v0.34.4 

### Browser Used

chrome

**Comment by mjy** [comment]
This only works if the image is an depiction of the collecting event.  I don't see any data like this in OSF.  If you want to find CollectingEvents related to CollectionObjects that have image first goto CollectionObjects then from there goto CollectingEvents.

<img width="1019" alt="Screenshot 2023-09-25 at 3 55 15 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/f4f386f2-b71d-4fb0-86b7-ad807cb1ed8c">

**Comment by mabecabrera** [comment]
No, we have no images linked to collecting events in OSF. They were all linked to specimens.
Then, my question is... How do I get the collecting information from an image. An image of a specimen collected. When I get to images of those Collection objects collected in a certain area... I can not find the way to know where is that image from unless I go to the Collection object form (that I have to do by copy-pasting the code of that specimen.



Or going to Related and there clicking on the Collection Object. I know it is how the data is related. Images are linked to specimens... and specimens to collecting info... But it would be very usefull to have a bridge that connects the image with the locality so we could do comparations of images knowing where they came from.






    El lunes, 25 de septiembre de 2023, 17:56:04 ART, Matt ***@***.***> escribió:  
 
 


This only works if the image is an depiction of the collecting event. I don't see any data like this in OSF. If you want to find CollectingEvents related to CollectionObjects that have image first goto CollectionObjects then from there goto CollectingEvents.

**Comment by mjy** [comment]
Image Filter -> Select the images in question -> Pass to Collection object filter -> Immediately pass to Collecting Event filter.  

Does this work for you?
