### ISSUE TITLE
Custom Layout Preferences in Filters, functionality questions

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3568]
### Feature or enhancement

I find the option to costumize the resulting table very useful for showing data by takeing a screenshot of the table with results anda pasting it somewhere. But as I refresh I loose my preferences. Is there anyway to keep my costum preferences... so I do not need to choose them every single time?

Also, What would be the use to select this option in de scroll down if when I choose it there is no costumed selection saved? Different from just clicking on the pencil and checking on the checkboxes I want.

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/c3011ad1-2c33-449c-a235-003d7caaa87e)

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/e827f0f6-cd4a-4192-ad96-62c9570ce1ab)

### Location

Task Filters in general

### Your role

Curator

**Comment by mjy** [comment]
@mabecabrera there is no way to save custom layout.  Essentially we wanted to have people test if this functionality was good enough (you can not order individual columns, for example).  If it is good enough then we will extend with saved custom searches.

**Comment by mabecabrera** [comment]
I do not mind the order of the columns... I love it. Makes it much easier to look at the results. But yes! I would love to have it saved.  And also would love to be able to download it the way is usefull for me.  With just the columns I need.

**Comment by jlpereira** [comment]
This was added today #3756
