### ISSUE TITLE
Task 'Report DWCA table' does not display the list of collection objects

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#357]
Apparently missing from the display of the first page is the first 25(?) list of collection objects.

**Comment by mjy** [comment]
It only displays records for those that have been indexed.  Solution is to indicate this isn the list.

**Comment by TuckerJD** [comment]
I see that the list itself is empty, but the page navigation details say that there are a lot more pages. This is why I thought that the objects just were not being displayed.  This information should reflect the information related to the intended list.
![screen shot 2018-03-23 at 12 36 15](https://user-images.githubusercontent.com/1838610/37844958-467f8000-2e97-11e8-941a-9a05075acfdc.png)

**Comment by mjy** [comment]
Mmm- are you saying you do not see a table?  Give it a second- it's indexing line by line.

**Comment by mjy** [comment]
Confirmed the bug- individual row indexing is not firing for non-index records.
