### ISSUE TITLE
depictions - license and copyright holder organization.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3577]
I got a critic from a data provider, that full information about copyright is not displayed on the public pages.

This is the current attribution:
Holotype: NHRS-GULI000105271. Depicts Habitus, lateral view, an Observation. (c)2023 . Created by Gunvi Lindberg. Attribution

The provider stated, that the copyright of the image is not spelled out
The license "CC-BY 4.0" is not displayed,
The copyright of the image belongs to the institution, and this information is also not displayed.

What needs to be done.
 [] Spell the license
 [] Add attribution to the organisation
 [] Remoe "an Observation" statement.

This is the page which have all of this information in TW.

**Comment by mjy** [comment]
Attribution should already reference organizations.
