### ISSUE TITLE
Soft validations for missing homonym relationship between species and superspecies ranks

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3578]
### Steps to reproduce the bug

```bash
It seems that the soft validation is confusing rank levels maybe? I could not understand the reason for this Soft validation in https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=930920

This is one case. There seems to be more cases.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/d8a486bd-de27-41e7-9567-172fef61882b)

### Environment

Production

### Version

v0.34.5

**Comment by mjy** [comment]
`supersp.` is genus group level or species group?  I vaguely remember it being the former.

**Comment by mabecabrera** [comment]
**Species group** was the name we used in OSF for this "superspecies" rank in TW.

**Comment by mjy** [comment]
Since they are both species group names they compete for homonomy, only group matters, not specific rank.

**Comment by proceps** [comment]
make sure that species name is using the superspecies as a parent, in this case, you should not see the messaege. If those two used independantly, yes, the are competing for homonymy. The same will apply to species and subspecies.

**Comment by mabecabrera** [comment]
The species is a child of the superspecies! That is why I did not understand the soft validation... the relationship is set...

<img width="1292" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/4aba7de7-3d14-4034-b612-aa00d60d7aac">

I see now there is no Author for that superspecies...  That might be the problem... I will look further into it.

**Comment by proceps** [comment]
the difference is in the original combination. In one case the name is called tarsata, in another case it is called tarsatum, they are not recognized as the coordinate taxa. See the name field for both species and superspecies

**Comment by mabecabrera** [comment]
I added the authorship but have not solved anything...

<img width="1265" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/93f558c6-bb60-4ee4-b936-d1b8dbbe4b30">

I see other supersp have their type same as the species... this one does not. I would like to know what is the procedure of creating a superspecies from zero... so I could understand better this.

This is another case of supersp. with the complete data and no homonym soft validation... https://sfg.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=909815


I do not think we will work with species groups the same as UCD does... 
<img width="684" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/20cacd8f-8ce2-42e3-a113-4c63b3b29af6">

**Comment by mabecabrera** [comment]
I will try to fix it. If not I will ask for help tomorrow in the session. Thank you for your help!!!

**Comment by mabecabrera** [comment]
Ok! fixed it. Now the only thing left is the type specimen panel for the supersp. is empty. I can't find the way to associate the holotype of Z. tarsata also to the supersp. Should it occur automatically when setting the species Zoniopoda tarsata as a child of the supersp?

**Comment by proceps** [comment]
Look at the soft validation panel on the superspecies side. Use fix button.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/ddf758d8-e1dd-4098-804f-d7910266bb6d)
