### ISSUE TITLE
Comprehensive task - Add buttons color in Citation, Determination and Type material

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3579]
### Feature or enhancement

We find it very useful to have the Add button on some panels in green, such as in the Type Material panel. But the Citation and Determination panels have the Add button in blue.
Could all the Add buttons in this task be green? It helps us not forget to press them before saving.

### Location

Comprehensive specimen digitization task

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/4b5b5890-89ae-48e0-b11e-108ec4b7f947)

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/e037acf1-9866-4279-b0f4-b9faf4cf6f7b)

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/374ef48d-7171-4f34-8cca-0a2373da71f5)

### Your role

Curator

**Comment by mjy** [comment]
@jlpereira if the add button touches the DB it should indeed be green, if not, blue.
