### ISSUE TITLE
Cannot fix Original combination and rank of subspecies

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3580]
The protonym of _Mecopoda javana javana_ is _Gryllus javanus_. How can I get rid of the wrong combination _Gryllus javanus javana_? 

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/223b3267-881d-49b2-9951-743b50f206ed)

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/67c72d30-2fae-4ae4-a194-49f423a46765)

(This taxon suffered various migration errors.)

**Comment by proceps** [comment]
The real problem here is, you have a duplicate record "Gryllus javanus" and "Gryllus javana", The first is used as a part of original combination. Delete javanus in the original combination section and replace it with javana. Look also at the soft validation part, it does indicate that the name is homonym. UCD group spent their time resolving homonym or removing potential duplicats. The should be a priority and will resolve many related issues.

**Comment by typophyllum** [comment]
Thanks. I was pretty sure to have deleted the duplicate yesterday. Now I deleted it for sure and the problem remains, I cannot get rid of  _Gryllus javanus javana_.

**Comment by typophyllum** [comment]
Now I noticed that one of the soft validation fixed created the duplicate again. This is driving me crazy.

**Comment by proceps** [comment]
problem is similar to the other issue you have different spelling of the name for species and subspecies, the system does not recognize those two as coordinated taxa. Put javanus in both places, after that, you should be able to resolve the problem with soft_validation fix.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/2fe2d4ba-17f9-46f4-a856-e51c3d7475a1)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/8a5b0b67-f912-4d79-9390-a5147b4da9c5)

**Comment by typophyllum** [comment]
The soft validation fixes keep creating a duplicate and the _Gryllus javanus javana_ doesn't go away.

**Comment by typophyllum** [comment]
It doesn't let me put _javanus_ at _M. javana javana_. If I select the subspecies it remains _javana_ and if I select the species it takes me to editing the species instead of the subspecies. And I don't want to create a duplicate nominotypical subspecies but fix the one that is already there with all the citations and the synonym.

**Comment by typophyllum** [comment]
Problem was to put in _javanus_ and click on save (not select any of the names that might show at left, which would take you to edit that name).

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/44f9efcc-799c-41f7-a5bd-7d2d23e431c8)
