### ISSUE TITLE
Need help with a Taxon Name of a subspecies all terms non latin

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3587]
I want the citations to be correct, when this taxon was cited completely non latin... Cranaë kükenthali kükenthali
But I am having a lot of trouble with the original combination and rank panel.
I know that the best practice is to create the taxon name well spelled and then clone it and create the originaly misspelled. But that is easy with the genus. Then when I create the species what do I use in the original combination? and then when I create the subspecies?

This is what I need to recreate
<img width="1311" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/4f043390-59aa-4dfc-bf51-4e5dd8bd4018">

Right now... trying to solve this I have two Taxon Names duplicated... one Taxon Name with the types associated and no other info in its OTU and other taxon name, with all the citations an OTU with images but no types... Loosing my mind here.

### Location

Edit taxon name

**Comment by mabecabrera** [comment]
Sorry about the label... can't erase it... It is just a question.

**Comment by proceps** [comment]
I updated the record for you to use as an example
https://sfg.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=927555

**Comment by mabecabrera** [comment]
You fixed it??? Wow! I will see all the details!!! Thank you so much!

**Comment by mabecabrera** [comment]
Kirby cited the name as Cranaë kuekenthali. Still I am unable to create this combiantion. I will save this example for a TW session.

**Comment by proceps** [comment]
Go to the Edit page for the protonym of kuekenthali. Go down to Subsequent combination section. Drag the name kuekenthali to the species level. In the genus field, add 'Cranaë'. Add the citation. Click Save.
