### ISSUE TITLE
[Bug]: TDWG Level 3 for Newfoundland also selects Central African Republic

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#3588]
### Steps to reproduce the bug

```bash
1.When asserting a distribution for Newfoundland
2.And then selecting the tdwg_l3 choice
3.Central African Republic will also be asserted as a distribution
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/61740366/452a14da-8a05-45f5-86c5-8d42a5605001)

### Expected behavior

I would expect only Newfoundland to be asserted as a distribution.

### Environment

Production

### Version

 version 0.34.5

### Browser Used

Chrome

**Comment by mjy** [comment]
<img width="753" alt="Screenshot 2023-11-07 at 4 07 33 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/8739f8f4-ecdc-420c-9086-4808253b06b6">
