### ISSUE TITLE
Task - Filter nomenclature - search epithet name only

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3589]
I would like to have a checkbox below the name filed to restrict the search to the specific epithet only (name field) vs. full cached name search.

**Comment by proceps** [comment]
This one we discussed today

**Comment by jlpereira** [comment]
Done https://github.com/SpeciesFileGroup/taxonworks/commit/cfe957599867439c68a8822416143dcd4a355e75
