### ISSUE TITLE
[Bug]: Can no longer use Collecting Event Radial to Change Bulk Geographic Areas

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3590]
### Steps to reproduce the bug

```bash
1. When I am in Filter Collecting Events
1a. And I search for something that goes over 250 results.
2. And I select any number of CEs
3. Then I go to Radial Collecting Event
4. Then it gives me a "Too many records selected, maximum 250" message.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/4931b466-6038-4509-a27d-40b1fe3d4ef0)

### Expected behavior

Should be able to select more than 1, and up to at least 1000. Prefer 5000-10000 with job completing in background. 

### Environment

Production

### Version

0.34.6

### Browser Used

Chrome

**Comment by mjy** [comment]
Manually updating over 250 collecting events at a time seems exceedingly dangerous?  Seems we need the nuclear-key feature here where requests are made, then confirmed by a second party?

**Comment by tmcelrath** [comment]
Matt - I have 2500 CE just for a single county that need updated. Not exceeding dangerous.

**Comment by tmcelrath** [comment]
Do you want to approve dozens and dozens of requests for county level additions that are already secondarily validated by historical data?

**Comment by tmcelrath** [comment]
I don't

**Comment by tmcelrath** [comment]
Either - we trust curators/CMs with their data, or we don't, and we start instituting project-wide administrative levels where individuals have different permissions levels. We can't have it both ways.

**Comment by tmcelrath** [comment]
I have 164428 CEs to assign Geographic Areas to. I'm NOT going to do them 250 at a time.

**Comment by tmcelrath** [comment]
Works for me.
