### ISSUE TITLE
Need more "Favorites"

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3600]
### Feature or enhancement

I need to be able to favorite more tasks. Right now the limit is 16. I easily use more than that on a monthly basis. 

I would recommend upping it to 30. 

### Location

Hub

### Your role

Collections manager

**Comment by mjy** [comment]
@jlpereira I don't think we have a limit (I can hit 18).  Is this a POST size limit issue?

**Comment by mjy** [comment]
And, @tmcelrath this is an open issue (can't favourite anything) that should be fixed today.

**Comment by mjy** [comment]
Gonna be today, we get emails...
