### ISSUE TITLE
[Bug]: Unable to delete DOI from a source

### ISSUE THREAD

**Issue by sdjbrown** [SpeciesFileGroup/taxonworks#3601]
### Steps to reproduce the bug

```bash
1.Make a new source
2. Add a DOI (not necessarily a valid one) in the appropriate field
3. Save the source
4. Open the source again
5. Delete the DOI
6. Click "Save"
7. Watch the DOI reappear 

Editing the DOI works as expected.
```

### Screenshot

DOI entered:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/1320161/446f8e5b-d28a-4e50-8c0e-560dbec9834c)

DOI deleted:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/1320161/ecbf9f4f-dcb0-40af-8878-9a5729261b4e)

DOI returns:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/1320161/e3b7ac74-0016-456b-a463-bb4680df807a)

### Expected behavior

When I delete the DOI from the field, I expect the field to be blank after I save it.

### Environment

Production

### Version

0.35.1

### Browser Used

Firefox

**Comment by proceps** [comment]
Adding DOI to a field automatically creates an identifier. Please delete using radial.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/63c2cbe2-5ee5-4c32-9539-8dd72657c21b)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/79c5fd6c-3c6e-4a0e-b987-bd44b91f3c99)

**Comment by sdjbrown** [comment]
Thanks for showing me that process @proceps. 

Unfortunately, attempting to delete the DOI using the radial isn't working either---clicking the red trash icon brings up a dialogue box saying "You're trying to delete this record. Are you sure want to proceed?", and after clicking "OK" the identifier remains visible.

**Comment by proceps** [comment]
@jlpereira I confirm, I cannot delete doi as identifier from the Source. not from the task, not from radial.

**Comment by jlpereira** [comment]
It's a backend issue, it seems global identifiers doesn't belong to a project. That could be the problem why we can't access to them, if you try to access directly it gives you a 404 response, same if you try to delete them.

I'm going to assign this one to Matt
