### ISSUE TITLE
Task - Uniqify sources

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#364]
As a community curator I'd like to help disambiguate duplicate sources.

* [ ] Filter sources that are unused (no project association, no data)
* [ ] Filter sources created prior to `some time`
* [ ] Select a set of seeming identical sources, step through the diffs of the fields one at a time, allowing merge/edit of the base, and destroy of the compared 
* [ ] Integrate verbatim breakdown via Crossref

**Comment by proceps** [comment]
I would start with something simple, when I already know that two sources are the same

**Comment by mjy** [comment]
Resolved in https://github.com/SpeciesFileGroup/taxonworks/issues/970.
