### ISSUE TITLE
[Bug]: Sometimes Moving Asserted Distributions fails but no reason given

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3641]
### Steps to reproduce the bug

```bash
1. When I move a number of asserted distributions in Filter ADs.
2. Then sometimes a number fail. 
3. And I can individually go to each and move it manually without it failing. 

Replicate: "Darjiling (https://sfg.taxonworks.org/geographic_areas/34188)" moving to "West Bengal (https://sfg.taxonworks.org/geographic_areas/32499)"
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/02587cba-6b12-4586-b6e9-f9ce1253b083)

### Expected behavior

Should generate a report of _why_ not moved at least. 

### Environment

Production

### Version

0.35.3

### Browser Used

Chrome

**Comment by proceps** [comment]
I have usually fail, when the second geographic area is already used for a particular OTU. It would be nice to move the citations, and delete the AssertedDistribution after.

**Comment by mjy** [comment]
Duplicate/handled in https://github.com/SpeciesFileGroup/taxonworks/issues/3690.
