### ISSUE TITLE
[Bug]: Loan form addresses not rendering correctly

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3645]
### Steps to reproduce the bug

```bash
1. When I add addresses with line breaks to a loan. 
2. And they show as formatted correctly in Browse Loan.
3. Then I generate a "Recipient Loan Form"
4. And they are not formatted correctly. 

Also, recipient is included twice. Should only be once.
```

### Screenshot

Correctly formatted in Browse Loan:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/f50036ae-32d2-4524-bdd8-aba1c08bf853)

Weird line breaks (ignored?) in Recipient loan form:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/a9c415cb-350f-4799-8b7d-f883916f6717)

### Expected behavior

Should format with line breaks as included in Browse Loan. 

### Environment

Production

### Version

0.35.3

### Browser Used

Chrome

**Comment by mjy** [comment]
Does this have closed duplicates, I think it might?

**Comment by tmcelrath** [comment]
Kinda: #2641 is similar but not exactly the same.
