### ISSUE TITLE
Model - Collecting Event - deleting geographic area should reset cached.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3668]
When I delete a geographic area associated with Collecting Event, I expect cached values to be nil, but they are not. So the label does not get updated:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/196c40af-134e-4b94-8c0e-40935b027787)
![Screen Shot 2023-11-28 at 12 38 58 PM](https://github.com/SpeciesFileGroup/taxonworks/assets/5597748/cee0f61a-c8fe-484c-b836-eb1fe6c8f041)

**Comment by mjy** [comment]
Are you sure this isn't done with a delayed job?
