### ISSUE TITLE
Open many collection objects all at once

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3672]
### Feature or enhancement

When I am in Filter CO.
And I want to clean data in TW
Then I want to search for a set of objects
Then I want to open ALL of those objects in different tabs. 
Otherwise, I have to click twice (Radial CO, then Comprehensive) to open every single thing that needs edited. 

### Location

Filter CO

### Screenshot, napkin sketch of interface, or conceptual description

Need an addition somewhere in radials to "Batch Open". NOT batch edit, because every object is different in this case, and I need to open every one. 

### Your role

Collection manager

**Comment by proceps** [comment]
Yes, I asked for the same for filter nomenclature and filter sources...

**Comment by tmcelrath** [comment]
Alternative is being able to create a "set" of objects and pin it - which can then be browsed with "next" and "previous" in Browse or Edit tasks.

**Comment by LordFlashmeow** [comment]
No, this is 100% doable if the user enables "popups and redirects" in site settings.

You can run `window.open(url, '_blank')` in a loop—every call will open a new tab.

**Comment by mjy** [comment]
@jlpereira Maybe we cap this at 25 for now?

**Comment by tmcelrath** [comment]
Would prefer at least 50.

**Comment by mjy** [comment]
@jlpereira likely need to pause between records.
