### ISSUE TITLE
[Bug]: generated DWC tsv file misses taxonomic hyerarchy for collection objects with valid otu/taxon names

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3674]
### Steps to reproduce the bug

```bash
1.DWC dashboard
2.download
3. https://docs.google.com/spreadsheets/d/1hctt_BuKuuQslfJCuUCk4rknZZczcci0nS9FRCphI2g/edit?usp=sharing
...
```

### Screenshot

<img width="699" alt="Screenshot 2023-11-29 at 5 04 24 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/9273125/b9a4579b-49a9-4ce4-8a8f-5bdd60cf1172">

### Expected behavior

Taxonomic hierarchy in DWC tsv should be listed if OTU/Taxonname is provided for a collection object. It is missing for numerous collection objects like UNHC 0036015 (https://sfg.taxonworks.org/collection_objects/1320716). 

I just cannot figure out what is missing or what we did incorrectly.

### Environment

Production

### Browser Used

Chrome

**Comment by teleaslamellatus** [comment]
you were right, resave solved the issue. What would be the next step?

**Comment by mjy** [comment]
Closing as outdated.  Reflects rebuilding DwC Index issues.
