### ISSUE TITLE
[Bug]: DwC-A Checklist importer: Subsequent combinations fail to import if the originalNameUsageID is unknown

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#3680]
### Steps to reproduce the bug

1. When importing a DwC-A Checklist
2. If the originalNameUsageID is unknown, subsequent combinations fail to import with the error, "Could not determine if name is protonym or combination"

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/8573609/9d1035ed-e884-4ff5-b330-c46a8a275a9a)

### Expected behavior

It would be preferable to still import subsequent combination records in which the originalNameUsageID is unknown, and use the verbatim author field to set the bracket on the authorship like (Walsh), because after the import is completed it will be easier to filter for incomplete combination relationships with the Filter Nomenclature Task and fill in the missing original combination data with the taxon name editing tools instead of trying to correct it in the import task in which you'd have to fill in a large number of IDs. Often the names missing the originalNameUsageID are really old names in which it's hard to find/access the original genus because the literature has been long out of print, so importing the currently used subsequent combination seems more important than having the original combination data.

### Environment

Sandbox

### Sandbox Used

sandbox

### Version

4a941a139

### Browser Used

Firefox

**Comment by proceps** [comment]
@LordFlashmeow, could you please address this issue, we are trying to import taxonomy, and about 1/3 of the name fail, because originalNameUsageID is blank in the dataset.
