### ISSUE TITLE
DwC importer: only show settings for current import type

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3693]
### Feature or enhancement

Right now, the settings page in the DwC Importer has settings for both Checklist and Occurrence datasets. I think it would make the interface more user-friendly if only the settings that applied to the current import type were shown.

<img width="613" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/33206210/1342c32f-83f9-4182-beaf-a3af4c0f44bf">

### Location

DwC Importer

**Comment by LordFlashmeow** [comment]
Nomenclature code is used by both checklist and occurrence, but taxon names without parentNameUsageID is Checklist-specific.

I expect we'll be adding more settings in the future, so I think setting this up now is a good idea.

**Comment by jlpereira** [comment]
Pushed a refactor of this, and settings splitted depending of dataset type

**Comment by LordFlashmeow** [comment]
Implemented by ab034ea0564857e1929974f9d792272d5663f47f
