### ISSUE TITLE
[Bug]: Cannot add note to a specific loan

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3697]
### Steps to reproduce the bug

```bash
1. When I try to access this loan in the INHS insect collection project:
https://sfg.taxonworks.org/loans/1872 
2. And then I try to add a new note
3. Then it gives me an error.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/bb5fb4dd-2cb0-44c4-805a-b99c0cd343fc)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/197a9016-5b95-431a-b34a-e3458131afdb)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/8683b315-d988-4cca-b917-fd0f41b4b562)

### Expected behavior

Should be able to add another note

### Environment

Production

### Version

0.36.0

### Browser Used

Chrome

**Comment by mjy** [comment]
@tmcelrath somehow the Loan is invalid, go to the loan, save it, get the message, fix problem, and it will work.

**Comment by mjy** [comment]
... aaaaand it turns out there are 2173 of these.  Not sure what todo.

**Comment by tmcelrath** [comment]
Loan is invalid b/c it didn't have a "Date Returned Expected." Fixed by fixing this and then adding note.

**Comment by tmcelrath** [comment]
I can't search for this, but are there 2172 loans without a "Date Return Expected" which is now required?

**Comment by tmcelrath** [comment]
If so, can we programmatically  add a due date of two years after the "Date Sent" Date, if one exists?

**Comment by tmcelrath** [comment]
Yeah, can confirm 644 records as "Is Overdue", with 69 records as "Not Overdue", but 3547 loans total. Those do not add up and they should be one or the other.
