### ISSUE TITLE
How make a genus with two subgenera and 40 species a subgenus of a different genus?

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3698]
_Metioche_ had two subgenera _M_. (_Metioche_) and _M._ (_Superstes_). I temporarily moved the latter with its two species as full genus under Trigonidiini. _Metioche_ will become a subgenus of _Trigonidium_. Do I have to move all the around 40 species of subgenus _M_. (_M_.) one by one to the genus _M_. before I can delete the subgenus and move the genus as subgenus under _Trigonidium_? Synonymizing the subgenus under the genus doesn't seem to help.

**Comment by proceps** [comment]
I would do oposite, I would move the subgenus with all include species, and delete generic name after.

**Comment by typophyllum** [comment]
That's what I tried first, but it didn't let me separate the  
nominotypical subgenus from the genus. Maybe it will work if I delete  
or modify some of the corresponding data.



___________________________

Dr. Holger Braun

División Entomología
Museo de La Plata
Paseo del Bosque s/nº
1900 La Plata
ARGENTINA

e-mail:
***@***.***
***@***.***

Orthoptera Species File Online
http://Orthoptera.SpeciesFile.org

TETTIGONIIDAE Argentina & Uruguay
https://biodar.unlp.edu.ar/tettigoniidae/

**Comment by proceps** [comment]
I think you need to make it spelled one letter different, after that, you should be able to move it out.

**Comment by typophyllum** [comment]
This worked. Thank you.

**Comment by typophyllum** [comment]
I renamed the genus and deleted everything it had, but when I try to delete it, this error message shows up:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/6e90748a-ba39-4ee3-b191-9b7bd20e455c)

**Comment by typophyllum** [comment]
I renamed the genus "Metioch", deleted everything it had, and moved two generic synonyms to _Trigonidium_, but it doesn't let me delete it:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/abae6da9-b7e4-4450-a2df-f6ba103800bb)

Apparently it has 66 children.

**Comment by typophyllum** [comment]
The 66 children were combinations where the soft validation fix could change the parent to _Trigonidium_. Now there remains a relationship that seems to be indestructible.

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/f0b38e73-4de1-4137-a01c-d2a7813fdefd)
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/8b407d28-c445-4ce8-987e-508d06b2e87b)

**Comment by typophyllum** [comment]
Finally I could destroy it. I thing we urgently need an automatic handling of subgenera and subspecies. What SFS could have done in a minute took me around an hour and a half.
