### ISSUE TITLE
LepIndex - Can the link to the depiction launch the fuller sized image directly

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#37]
On a taxon names record when selecting a depiction it navigates to an intermediate resolution of the image (depiction_1.jpg), requiring a further click to see the fuller version of the image (depiction_2,jpg). Can the first selection navigate _immediately_ through to the fuller resolution. It's an additional unnecessary click.

![depiction_1](https://cloud.githubusercontent.com/assets/22223106/19495680/4b633a40-957c-11e6-98a9-75d00c237548.jpg)
![depiction_2](https://cloud.githubusercontent.com/assets/22223106/19495686/4f1fadf8-957c-11e6-8a61-68d6d979655d.jpg)

**Comment by mjy** [comment]
Sandbox is update with this proposed solution, let us know if this works for you.
