### ISSUE TITLE
Disable "saved" sound?

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3706]
### Feature or enhancement

When I am entering COs or updating fields at a high rate, I am constantly saving. This initiates a twinkling-like sound as well as a very visible prompt confirming the save every time.

Is there an easy fix or option to disable the sound and only use the prompt? I do not want to mute my speaker if I am listening to music/podcasts, etc. and I do not want the sound to constantly interrupt the music/podcasts, etc. 

Hoping it's an easy thing.

### Location

Task - Comprehensive Specimen Digitization

**Comment by jlpereira** [comment]
Right click on tab -> Mute Tab

**Comment by AntWeb-org** [comment]
Thanks!
