### ISSUE TITLE
[Bug]: Cannot edit this collecting event because identifiers push editing screen off page

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3715]
### Steps to reproduce the bug

```bash
1. https://sfg.taxonworks.org/tasks/collecting_events/browse?collecting_event_id=109600
2. try to open identifiers pane
3. cannot scroll down to edit because too much text makes it so I can't edit anything
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/030d80eb-166b-47a9-b7a1-3406a465b42b)

### Expected behavior

Need to be able to scroll, or these kinds of CEs need to show less text in annotator wheel mode

### Environment

Production

### Version

0.36.0

### Browser Used

Chrome

**Comment by mjy** [comment]
Very rare case @jlpereira, but still needs handling I suppose.  Truncating results might be a possibility.
