### ISSUE TITLE
New relationship and name formatting for Emendavit

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#3716]
### Feature or enhancement

When the circumscription of a taxon is significantly changed ('emendavit') by a subsequent author, but the type still remains in the new concept, botanical names may take the form (e.g.):  _Centaurea jacea_ L. _emend._ Coss. & Germ. ([ICN 47.1](https://www.iapt-taxon.org/nomen/pages/main/art_47.html#Art47.1)). It would be great to model this in TW as two names related by 'emend.'. The newer name would have identical epithets to the older but would have the publication or author of the new concept. The 'computed', final name string would be as above. This seems an analogous capability to the addition of '_ex._ Author' for the relationship 'validly published as'. Thanks!  

### Location

/tasks/nomenclature/new_taxon_name

### Screenshot, napkin sketch of interface, or conceptual description

In the Relationship block, click 'Show All' and see 'emend.' in a green bubble under the 'Validly published as; bubble.

### Your role

Taxonomic researcher

**Comment by proceps** [comment]
I am looking at the ICN code. For me, 'Emendavit' is rather status, than relationship. The name does not change, The author does not change. I would not suggest to create a new protonym. It is rather be defined by adding a status to the name, the final result will look similar.

**Comment by camwebb** [comment]
But if it's a status rather than a relationship how do we link the original name to the name _emend._ LaterAuthor?  I guess that's what the concept (OTU) relationship is for: we could create a second OTU for the same original name, and call the second 'name OriginalAuthor emend. LaterAuthor'. This accomplishes the _meaning_ of the Emendavit. But, that said, we would still like to be able to use the name '_taxon_ OriginalAuthor _emend._ LaterAuthor' as well as the name '_taxon_ OriginalAuthor'.  In your vision/solution, how would we create these two forms of the same name?

**Comment by proceps** [comment]
This is esentially the same name, the analogy would be sensu lato and sensu stricto. Those are two separate concepts, but still resolved to the same name. In the case of emendit, the way I understand it, the scope of the name is reduced, but it is the same name. If the question to put two different determination, you can create two OTUs attached to the same TaxonName. Ultimately, this situation should be resolved by OTU relationships, and I believe we have some tools available in TW already for that. @mjy could probably put more comments on OTU relationships.

**Comment by camwebb** [comment]
Agree about handling this with OTUs and taxon concepts - we're already employing these (thanks again!). The additional question however is whether 'emend.' and 'sensu stricto/lato' are _just_ concepts, or names too. For example, if we find a synonym statement (= nomenclature) that involves an 'emend.' or a 'sensu' (e.g. [here](http://panarcticflora.org/#paf-340104c)), we need to add these to the names list, so we can create name relationships. We could of course just use the `verbatim` authorship, but it seems to me that would be valuable for 'emend.' to also have this 'computed' via the relationship between two names which have the same protonym, but different authors and a relationship of 'emend.'

How are other users handling sensu lato, sensu stricto now?

**Comment by mjy** [comment]
> How are other users handling sensu lato, sensu stricto now?

Good quesiton, I don't think we've seen a lot of it nor requests for it  This is definitely not nomenclature in my mind, and needs to be OTU Relationships or annotations in some other way.  I.e. if I asserte 'sensu lato" nothing in the nomenclature changes, or there is no rule that says "now we have to do x" (but maybe there is in Botany?!).

Not sure if this addresses the key issue, but throwing it out there. TW nomenclature is setup to let us infer actions, rather than record data as actions.  So we record in the form of, "X is a synonym of Y", as opposed to "X was synonymized with Y".  If we have a complete record (citations, facts), then we could infer, based on inspection of the facts, the roles, a classic example "X was removed from synonymy". 

> t0o use the name 'taxon OriginalAuthor emend. LaterAuthor' as well as the name 'taxon OriginalAuthor'.

Sounds like a cool modelling problem.

If we have 

Otu1 -> TaxonName
Otu1 > TaxonNameRelationship -> Otu2 (Tnr1)

Then what is a citation on Tnr1?  It says that some or all of the assertion is documented in that paper.  Can we take the authors of that citation and _inferr_ that they are emmending, and thus render a label on demand?

**Comment by camwebb** [comment]
@mjy Agree about emend., sensu lato not being nomenclature, in principal. 

The issue I see is in practice when we need to transcribe a NameRelationship (e.g., synonymy) between a name and its emend. form. ([E.g.](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=53335)). Unless there is a way to create a _name_ string that includes 'emend.' we cannot do this, because we cannot make a NameRelationship to an OTU. For the moment, we could just use 'Author1 emend. Author2' as the _verbatim author_ of a second name with the same epithets as the first.  

This said, I think we would agree that it is probably a taxonomic error to use an 'emend.' in a synonymy statement in the first place, and so we should not need to model this in TW, unless we are slavishly trying to transcribe existing synonymy statements from an existing source into TW.  Better to avoid this case if possible.

(Re: cool modeling problem: Not sure I understand your model, how Source1 can lead to both Authors1 and Authors2.)
