### ISSUE TITLE
Model - Uniquify sources

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#373]
Create Source methods and specs that produce reasonable results for 

* [ ] `#similar`
* [ ] `#identical`

May need to subclass specific methods for Verbatim vs. BibTeX.

Should follow similar pattern to #288, but potentially much more complicated given the many more attributes.

**Comment by TuckerJD** [comment]
Is this to return a scope of similar/identical, or as methods returning Booleans for comparing two specific sources?

**Comment by mjy** [comment]
Scope ideally, but that might be tricky

**Comment by mjy** [comment]
Pertinent fast finding with postgres

* https://stackoverflow.com/questions/28156795/how-to-find-duplicate-records-in-postgresql
* https://gist.github.com/rob-murray/b3528ffcd71040a9fdf1

You can just pass in model.attributes.keys - HOUSEKEEPING_ATTRIBUTES - MODEL_ATTRIBUTES to the latter.

**Comment by mjy** [comment]
Closing and cross-referencing https://github.com/SpeciesFileGroup/taxonworks/issues/970.
