### ISSUE TITLE
[Bug]: "DataAttributes" view in Filters shows nothing

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3733]
### Steps to reproduce the bug

```bash
1. When I go to Filter COs
1a. And I search by a data attribute. 
2. And I select "DataAttributes" view
3. Then nothing shows up.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/9c6826d8-d0f3-4870-8df1-12f37b3ad818)

### Expected behavior

Should see DataAttributes laid out like a table

### Environment

Production

### Version

0.37.0

### Browser Used

Chrome

**Comment by jlpereira** [comment]
@tmcelrath project? and filter url?

**Comment by tmcelrath** [comment]
Insect Collection. Was this filter:
https://sfg.taxonworks.org/tasks/collection_objects/filter?per=50&data_attribute_wildcard_pair%5B%5D=492%3ARobertson&collecting_event_id%5B%5D=125413&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1

But now they are showing up? 

Was this due to lag in loading?

**Comment by jlpereira** [comment]
May be. I can't replicate it. But when you see an empty table, the records may not have data attributes, which is not the case in your example, of course. Let me know if you can replicate it

**Comment by tmcelrath** [comment]
I'm going to close until I can replicate.
