### ISSUE TITLE
New task/workflow: Batch update collectors from verbatimCollectors or buffered_collecting_event

### ISSUE THREAD

**Issue by LordFlashmeow** [SpeciesFileGroup/taxonworks#3735]
### Feature or enhancement

The DwC importer's name parsing isn't perfect, and a portion of the CEs don't have Collectors assigned.

I want to be able to set the collectors of many CEs at once. Configuring a `batch_update` endpoint is the faster approach, but a new stepwise task would be more effective in the long run.

It should support assigning multiple collectors to the events respect the order of People provided.

### Location

Filter CE or a new task

**Comment by tmcelrath** [comment]
Related to #1836 as well. 

I support the creation of this. Right now I can't batch update collectors from the data I get from Bionomia because I do not have this functionality.

**Comment by LordFlashmeow** [comment]
Implemented in #3745. `buffered_collecting_event` isn't supported yet, but could be in the future.
