### ISSUE TITLE
Display tiff images in Images pages

### ISSUE THREAD

**Issue by rogerburks** [SpeciesFileGroup/taxonworks#374]
For pages like this: http://sandbox.speciesfile.org/images/3790
that contain tiff images,

expected behavior is to display the tiff image after uploading.

Current behavior is that it displays jpegs, but does not display tiffs.

Alternative idea: maybe a jpeg could be generated during upload, if it is not desirable to display tiffs.

**Comment by mjy** [comment]
@rogerburks You're exactly right.  We already generate alternate sizes, just have to change the reference.
