### ISSUE TITLE
Contributing Guidelines link that github suggests to new contributors is broken

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3752]
The first time I go to submit an issue or a pull request on this repository, github gives me a little popup saying "Be sure to review the [contributing guidelines](https://github.com/SpeciesFileGroup/taxonworks/blob/beb32a896a4e860c02ca7b0b9de3303f32a4554d/CONTRIBUTING.md) and [code of conduct](https://github.com/SpeciesFileGroup/taxonworks/blob/beb32a896a4e860c02ca7b0b9de3303f32a4554d/CODE_OF_CONDUCT.md)." 

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/b087d5fb-cf9d-4a5e-894c-1c12ba91b999)

When I follow the "contributing guidelines" link the file says "See [here](https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/CONTRIBUTING.md)." and that link is broken.

Could the initial contributing guidelines link be updated to https://docs.taxonworks.org/develop/contributing.html at this point? (The code of conduct link seems fine.)

**Comment by mjy** [comment]
Thanks @kleintom
