### ISSUE TITLE
Bug - Task - Filter CE - layout preferences: times out

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3756]
### Steps to reproduce the bug

```bash
1. Filtered for CEs
2. used Custom option for Layout preferences
3. after some time (an hour?) Layout preferences reverted back to All preferences but the Filter parameters remained.
...
@bpescador, @ChrisGrinter, @rich-keller
```

### Expected behavior

If there is a time limit for Layout preferences in Filter tasks, can that be removed or extended? 
If I am working on multiple tasks, including the data results from a Filter, I would like the custom Layout preference to remain for the duration of the day so I do not have to keep customizing the Layout preferences for the same Filter parameters. The Filter parameters seem to remain intact. Layout preferences will revert back to All once the Filter is reset.

### Environment

Production

### Version

v0.37.0

### Browser Used

Chrome Version 120.0.6099.130

**Comment by jlpereira** [comment]
After a few months of testing it seems that the tables are stable. I will add functionality to save layout changes.

**Comment by AntWeb-org** [comment]
Thanks!
