### ISSUE TITLE
Bug - Uniquify: reverting back/not merging

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3758]
### Steps to reproduce the bug

```bash
1.Uniquify - current project, last name, "de la Réunion", Selected person
2.Match people - results include 49 collectors of "de la Rθunion, Insectarium" that I want to merge with "de la Réunion"
3.Check all 49 and merge with Selected person - it works

Some time later the matched name shows up on Filter CE (I am updating verbatim_collector) and I do another Uniquify check. All 49 matched names are there again.
I have merged the same 49 names multiple times and the merge always reverts/unmerges at some point
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/1ea11161-a8b6-499e-bb3b-e9ccb3886db9)

### Expected behavior

After merging collector's names I would like the merge to stick. I initially thought this was due to resetting the task - perhaps undoing the merge - but it unmerges regardless

### Environment

Production

### Browser Used

Chrome Version 120.0.6099.130

**Comment by AntWeb-org** [comment]
I know that some results "may be truncated" but since the total number displayed was always 49 it seemed like the same batch. Thanks for clarifying.

**Comment by mjy** [comment]
@jlpereira can we more prominently display the *total* results or something like `49 selected (of XXX)` to help us understand this?
