### ISSUE TITLE
Bug - CSD - cannot save VerbatimTypeStatus: data attribute value taken

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3762]
### Steps to reproduce the bug

```bash
1. I am adding type data into a CO in a CSD.
2. TW provided the correct taxon name (see screenshot 2)
3. I get an error stating that the data attribute value has already been taken (see screenshot 1)
...
```

### Screenshot

screenshot 1
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/535c3078-c065-4fb8-a5ea-516731c5d677)

screenshot 2
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/b723a56e-bb9e-42bb-920f-b18b3bc83a42)

screenshot 3
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/0d3d23ac-e1a0-471b-aa90-f189b67dc601)

### Expected behavior

I would like to save the data attribute in the VerbatimTypeStatus field. 

If the error is due to the attribute being taken for another paratype of the same taxon name, multiple paratypes of the same taxon should be allowed. BUT, when I filter for COs with that VerbatimTypeStatus, the result is that same CO with the incorrect VerbatimTypeStatus (see screenshot 3).

I was having saving issues yesterday so perhaps this glitch is connected.

### Environment

Production

### Version

 v0.37.1

### Browser Used

Chrome Version 120.0.6099.200

**Comment by AntWeb-org** [comment]
I deleted and repasted the data into the field and it saved without the error prompt.

Please let me know if I should continue to submit tickets for issues such as these or if there is another route to take.
Thanks

**Comment by jlpereira** [comment]
@AntWeb-org I'm almost positive this commit will fix this issue, you will see these changes on the next update.
If the problem persist, please reopen this issue
