### ISSUE TITLE
Bug - CSD task - saving prompt to affect CO record

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3764]
### Steps to reproduce the bug

```bash
1.In the CSD task
2.Made update/added data to Attributes/Custom Attributes field and pressed Save
3.Prompt suggesting that the collecting event was modified and will affect all CO records associated with that CE.
4.Went to Edit collecting event for good measure and did not make any changes
5.Pressed Save although no updates/changes were made
6.Another prompt suggesting changes to CE will affect associated COs.
...
```

### Screenshot

**Prompt in CSD record/no updates made to CE record:**
![CSD](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/663d500b-fac0-4b51-b29d-96f3f5b11740)

**Prompt in CE records/no updates made to CE record:**
![EditCE](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/e2b91af2-6cbc-47b7-b9bc-e7f2702cb367)

### Expected behavior

It seems that there is an issue with one specific (as far as I know) CO and associated CE (CASENT0042899/BLF09800). I tested and saved other records and did not experience that issues.

I did not make any updates to that CE record and cancelled the updates to the CO record. I am wary of that prompt and do not know if anything will affect the CO records for that CE.

### Environment

Production

### Version

v0.37.1

### Browser Used

Chrome Version 120.0.6099.131

**Comment by AntWeb-org** [comment]
Update: happening in other CO records in the CSD when I attempt to add data into a Custom Attribute field.

**Comment by tmcelrath** [comment]
Weirdly - even though you are prompted that it will "edit >100 records" it does not actually do so.

**Comment by AntWeb-org** [comment]
So can I click Edit and hope for the best or should I hold off until the issue is fully resolved? I'm still a little hesitant.

**Comment by AntWeb-org** [comment]
That's great! Thank you!

**Comment by jlpereira** [comment]
@AntWeb-org where do you add the custom attributes? To the collection object or to the collection event?

**Comment by AntWeb-org** [comment]
I was adding to the CO in the CSD, specifically for CASENT0042899 under Attributes.
Thanks!

**Comment by jlpereira** [comment]
Were you editing other collection objects without leaving the interface? Does this happen if it is the first collection object you load when you open the interface?

**Comment by AntWeb-org** [comment]
Someone else was making an update to that specific specimen initially. I checked to see if it was done. When I realized it was not done I made the update and then received the Edit message. I was not happening previously for other COs I updated and I do not think I was updating in separate tabs. It was not happening on the first CO.

**Comment by tmcelrath** [comment]
For me - it gives me the warning if I go to any CO that has a CE with >100 records. If I edit anything on the record (even if not in CE), then I get warning.

**Comment by tmcelrath** [comment]
Secondarily - if I remove the CE with >100 objects, and create a new one - it tells me that I am editing the CE with >100 COs. If I save, it even looks like the CE has been edited. If I refresh the page however, that disappears.

**Comment by AntWeb-org** [comment]
I guess I was editing COs with CEs that have fewer than 100 COs associated. Weird.

**Comment by jlpereira** [comment]
I think I found the problem and already solved it, in a moment I will be pushing it.

**Comment by AntWeb-org** [comment]
Thank you!

**Comment by mjy** [comment]
Can someone confirm if this is visual, of if it could really affect the data because of editing a record you didn't think you should be editing?

**Comment by tmcelrath** [comment]
Visual.

**Comment by mjy** [comment]
Heard.  I panicked big time on somethign like this the other day too...

**Comment by AntWeb-org** [comment]
Unfortunately, the problem has returned even before I add any collecting event to a new CSD that I am entering. Notice the Attributes as still locked. It began happening steadily at this point on my fifth or sixth entry.

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/38a85b56-58a4-4f6c-ac65-ad935ff89dc4)

**Comment by jlpereira** [comment]
@AntWeb-org this fix is not yet in production
