### ISSUE TITLE
[Bug]: Red overlay on return from validation errors

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3767]
### Steps to reproduce the bug

```bash
I've seen varying results over the time I've been playing around with this, so since I'm new I'll just add initial setup steps here, in case I'm overlooking something:
* Update to latest development 2262c10c2c30c70a9552d5c829d6a63c7bcb9639 (this includes the zeitwerk merge).
* I'm using the docker setup, so run `docker-compose build` since there are updated dependancies and then of course `docker-compose up`. I'll put the rest below where it's easier to read.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/f7f1a18e-5fd2-448c-b62a-4bbd05597b25)

### Environment

Development (docker)

### Version

2262c10c2c30c70a9552d5c829d6a63c7bcb9639

### Browser Used

firefox and chrome

**Comment by kleintom** [comment]
As I said, I've gotten varying results from steps similar to the following, but right now steps to reproduce are:
3. Go to the 'Edit loans' task and create a new loan by filling in the minimal Lender Address and Date Return Expected (don't use Gift instead, there's a bug related to that, which is why I was working here).
4. Once the loan is created, clear the Date Return Expected field and click Update Loan.

Actual results: A red overlay screen saying 'Uncaught runtime errors' - see the screenshot. Underneath the overlay you do get the expected temporary 'date_return_expected: or gift status is required' validation error at the bottom of the screen.
In the developer tools the network tab shows a 422 returning the validation error, and the console shows the 422 XHR return as well as an 'Uncaught (in promise)' error.

Expected results: No red overlay and no 'Uncaught (in promise)' errors.

**Comment by kleintom** [comment]
If I add a `catch` block after the `then` at https://github.com/SpeciesFileGroup/taxonworks/blob/2262c10c2c30c70a9552d5c829d6a63c7bcb9639/app/javascript/vue/tasks/loans/new/store/actions/updateLoan.js#L11-L13 then the red overlays go away (but you still get the 422s, which I think is expected). I assume that's catching the source of the 'Uncaught (in promise)' error, which I assume is what was leading to the red overlay screen.

**Comment by kleintom** [comment]
(I'll say something about what I was seeing earlier; it's just been confusing to me - it's different behavior than what I describe above - but maybe someone more knowledgeable will be able to make sense of it, or if the STR above don't work maybe these will. I was setting out to update one of the validation functions for the Loan model here: https://github.com/SpeciesFileGroup/taxonworks/blob/2262c10c2c30c70a9552d5c829d6a63c7bcb9639/app/models/loan.rb#L263-L265 With unaltered code I wasn't getting any red overlay screens, even when I produced validation fails as in the STR above. But as soon as I changed that validation function at all, I would get a red overlay. I wanted to change `is_gift.nil?` to `is_gift.blank?` but that change was producing red overlays where the original code was not. Any other change I made to the validation function, even just removing the `if` all together, would produce a red overlay, and then when I changed the source back to the original the red overlay would go away. Maybe I was just missing something though!)

**Comment by kleintom** [comment]
You can also get a red overlay screen and 'Uncaught (in promise)' from a validation error by going to the New Namespace task and clicking `Create` without filling anything in.
On sandbox today, both the New Namespace and the Edit Loan STR show a 422 in the Network tab and an 'Uncaught (in promise)' in the Console (more confusion for me!).

**Comment by jlpereira** [comment]
@kleintom both overlay messages should be fixed now. Also now you should see a more informative message about the error and not "[Object object]"

Reopen if you still getting the same error

**Comment by kleintom** [comment]
Thanks @jlpereira!
