### ISSUE TITLE
[Bug]: QR Codes overlap each other when attempting to print

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3776]
### Steps to reproduce the bug

```bash
1. As a user I want to print QR codes
2. So I generate many
3. Then I try to print
4. And the QR codes generate on top of each other so I can't print them.
5. I adjust settings but nothing makes it so they are not on top of each other.

See missing "T" in screenshot.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/061de15f-d773-4c2f-b5bc-6576f3d9b2c8)

### Expected behavior

Needs more space between columns. Adjusting number of columns has no effect on this once there are enough QR codes to automatically make two columns. 

### Environment

Production

### Version

0.37.1

### Browser Used

Chrome

**Comment by tmcelrath** [comment]
No. Still looks bad on Sandboxes at least. 
<img width="346" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/910ec3a2-6080-4335-a141-08f1c1bf976f">

**Comment by tmcelrath** [comment]
Not only are the lines overflowing past the QR Codes (need to stay within the "boundary" of the QR code), but the next column is overlapping and obscuring the previous one.

**Comment by mjy** [comment]
So we're not applying the right class in this case.

@jlpereira perhaps we should refactor in anticipation of more generalized work.  Maybe we do something like this:

* inherit and organize based on size (cm dimensions) classes, place each size category in its own folder, e.g 'insect', '4_dram_etoh'
* Within that seperate styles for font/spacing
