### ISSUE TITLE
[Bug] Checklist importer fails quietly (raises) when `taxonomicStatus` is nill.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3783]
`.dig` and nil checks might be better.  In general can we catch this on a first pass and error rows?

```ruby
if record[:src_data]['taxonomicStatus'].include?('misspelling')
        oc_index = index
      end
end
```

**Comment by mjy** [comment]
Ping @LordFlashmeow @gdower

**Comment by LocoDelAssembly** [comment]
Somewhat related, nothing will be imported if `acceptedNameUsageID`. Perhaps assume it is identical to `taxonID` unless something else contradicts validity (e.g. `taxonomicStatus` == `synonym`)?

**Comment by mjy** [comment]
Please take a look at the proposed fix.

**Comment by mjy** [comment]
Well- actions did for me, checking the failure.
