### ISSUE TITLE
Rails 5.2 

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#379]
* [x] Branch
* [ ] Update .travis to CI branch
* [ ] Update gemfile (in particular gis gems IIRC)
* [ ] test ...

**Comment by mjy** [comment]
Blocking issues:

* [ ] https://github.com/ClosureTree/closure_tree/issues/305
* [ ] https://github.com/collectiveidea/delayed_job/pull/1023

**Comment by TuckerJD** [comment]
Other than a couple of typos, and an issue with postgis 2.2.2 vs 2.4.4, there seem to be these four constants unavailable:
`TAXON_NAME_CLASS_NAMES_VALID`
`TAXON_NAME_RELATIONSHIP_NAMES_SYNONYM`
`TAXON_NAME_CLASSIFICATION_NAMES`
`TAXON_NAME_RELATIONSHIP_NAMES`
