### ISSUE TITLE
[Bug]: Issues with the Status filter for the Task hub

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3791]
### Steps to reproduce the bug

```bash
1. Go to the tasks tab at /hub?list=tasks
2. Turn on the `Status` filter at the lower left (at the bottom of the filters panel on the left side of the screen).
3. There seem to be many ways to confuse the state of the status. For example, click the red dot, that works. Now click the yellow dot: all tasks disappear. Or turn on the Status, then click the yellow dot - that works - now click the yellow dot again to turn off the yellow dot: still only shows yellow cards, no red. In general after the first click things seem to get confused.
```

### Environment

Development (docker)

**Comment by kleintom** [comment]
Maybe it's a different issue, but I also expected to be able to click, say the yellow and the green dot at the same time, so that I could choose from any task that wasn't red.

**Comment by jlpereira** [comment]
I will take a look

**Comment by mjy** [comment]
As a side note we deperately need to update the semantics (and likely colors) on that experiment.  We had initial goals:

* Red - data will save, but everything might change (literaly)
* Yellow - rough UI/UX is stable, additions/tuning possible, but conceptually stable
* Green - will never change, you can write a manual.  Changes will be added to new tasks.

I'm not sure how useful these semantics have been, there are definitely Reds that need update to Yellow (and some Reds need to be completely removed).  And there are no(?) greens.

We've tossed around the idea of moving to a "gamer' color schema (as used in things like common, uncommon, legendary, epic, godly) reflecting 1) time spent in development (tuning, etc.); 2) stability; 3) number of people using it; 4) importance to workflows etc. etc.   This would remove the green/red from the UI, which has very specific meaning (always touches DB).
