### ISSUE TITLE
[Bug]: Left and right arrow keys on task hub don't work as expected

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3792]
### Steps to reproduce the bug

```bash
1. Go to the task hub /hub?list=tasks
2. On my standard screen I see 3 columns of tasks by 4 rows of tasks.
3. Now press the right arrow key.

Actual results:
The black squares representation at the top of the screen of what tasks I'm currently viewing only moves ahead by 4 squares (which matches the tasks I see on screen). i.e. I'm now viewing tasks 5-16. See the screenshot.

Expected results:
Tasks 13-24 are displayed.

The left arrow key has the same issue, it only moves by 4 tasks at a time.
```

### Screenshot

![Screenshot 2024-01-22 at 11-18-21 TaxonWorks - Hub](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/edd1832b-c5a3-46c1-927a-6b3edebc102b)

### Environment

Development (docker)

**Comment by jlpereira** [comment]
@mjy how was this expected to work? Move one column at a time or change all cards?

**Comment by mjy** [comment]
Initial intent was to page columns one at a time.  I think @LordFlashmeow commented on related behaviour too in another issue IIRC.  I'm pretty impartial to 1 colum vs 1 page, so if there are a couple more votes for this let's change it.

**Comment by kleintom** [comment]
I don't have a strong preference either, but I'll just add that, although current behavior is to shift by the size of a column, it actually does that across rows (not column); in other words if there are 4 rows (so a column has length 4) and each row has 3 items then when you press the right arrow the top row shifts off and the first item in the second row shifts off (a total of 4 items, the length of a column, gets shifted off). So the red in the screenshot will shift away when you press the right arrow:
 
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/a90088e2-d0b6-48c8-ac18-fba01c660c82)


To me that makes it kind of difficult to track how far you need to look through the current cards to see all of the ones that are going to disappear the next time you press the right arrow. The rows vs. columns: number of each vs length of each is confusing to me, was it maybe intended to shift off an entire row for each arrow press?

**Comment by jlpereira** [comment]
Aha, now I understand what you mean. I think this started happening when we changed the direction of the flex grid from column to row, so that the alphabetical order of the cards starts from left to right. I think the "easiest" ways to fix this might be to move by row instead of column, or swap all the cards.
