### ISSUE TITLE
LepIndex - searching for a source returns an erroneous record at end of list

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#38]
When searching for a source the last one on the returned list does not match the search criteria (and is always a Chalcid reference). See attached screenshot examples (sources_erroneous_search_return_1.jpg & sources_erroneous_search_return_2.jpg).
![sources_erroneous_search_return_2](https://cloud.githubusercontent.com/assets/22223106/19535147/840c982e-963e-11e6-9c3d-a91c81c26a6b.jpg)
![sources_erroneous_search_return_1](https://cloud.githubusercontent.com/assets/22223106/19535148/84130b50-963e-11e6-9fda-0d0b78c5c124.jpg)

**Comment by mjy** [comment]
Sources are shared across projects, and referenced as belong to a particular project (Project Sources).  Here you are searching through all sources, so the behaviour is expected, but see #58
