### ISSUE TITLE
DarwinCore Exporter - DataAttributes are not aligning to their objects

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#3802]
Tommy has found a bug where DataAttributes are not aligning with their corresponding objects.  Clearly a major missalignment.  We'll have to re-visit how DAs are aligning to the row they are being exported on, perhaps row order is not being perserved, etc. 

Steps to replicate - choose all data attributes for some reasonablly sized record set (10k), export.  Notice that data attributes for one record are offset to another row.

This was probably introduced with the refactor that added the ResourceRelationship table as that is the last time it was touched.

@LordFlashmeow if you are interpretting DataAttributes on Export you're going to want to check this for AntWeb.

**Comment by mjy** [comment]
I think I have it, where is not properly scoped in a couple places.

**Comment by tmcelrath** [comment]
Needs re-opened. Not fixed.
