### ISSUE TITLE
[Bug]: CSD-data attributes auto-filled

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3805]
### Steps to reproduce the bug

```bash
1. From CSD task
2. Click Save before entering any CO data
3. Scroll down to Attributes under Collection Objects
4. Scroll down to Custom Attributes under Collecting Event
...
The Attributes and Custom attributes fields are auto-filled when they should be blank.
If I refresh the page the Attributes data may disappear but the Custom Attributes are still auto-filled.
```

### Screenshot

Collection Object section not filled in: I only clicked Save:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/a27ddf6a-4d2a-473b-8e38-360861ad90d3)

Attributes auto-filled:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/d920d4ef-dd19-41a6-b973-54296da300d9)

Custom attributes auto-filled:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/0cb13582-cdb8-4de9-b0be-3a3ea6a3743f)

For good measure, here's a screenshot that shows no OTU or CE data has been entered:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/6c40f8fc-7edd-4dcc-b4dd-028c3dc13a36)

### Expected behavior

When I start a CSD record there should be no auto-filled data in any of the attributes field.

### Environment

Production

### Version

v0.38.0

### Browser Used

Chrome Version 121.0.6167.86 (Official Build) (64-bit)

**Comment by mjy** [comment]
Thanks- hoping for a fix in a couple hours.  This is a bad one.

**Comment by mjy** [comment]
The CHANGELOG once numbered indicates when the release is live, not when
the issue is closed. We are in the process of deploying.
