### ISSUE TITLE
Radial annotator: citation count no longer updates

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3806]
In Browse nomenclature: Every time a new citation was added, the number in the blue segment was updated. This is no longer happening (here displaying 2 instead of 3)

![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/84e1e2a9-340d-4d16-b425-66c67b46c17d)

**Comment by typophyllum** [comment]
I still doesn't update.

**Comment by jlpereira** [comment]
It is not in production yet
https://github.com/SpeciesFileGroup/taxonworks/blob/development/CHANGELOG.md
