### ISSUE TITLE
As a component user of a radial annotator, I'd like to be able to get notifications when depictions are added or updated

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3817]
### Feature or enhancement

Maybe this is possible and I'm just not aware how. I think this is an issue for multiple task components that want to display depictions (in this case, but could be citations or other things) that are maintained on an object via a radial annotator - one example is Browse CO, which displays depictions associated with the CO (my interest is in the new Leads task).
Steps to reproduce:
1. Go to Browse CO and load a CO.
2. Open the radial annotator and change depictions in any way, by adding, removing, or editing.
3. Close the radial annotator.

Expected results: The section in Browse CO dsiaplying depictions reflects the changes you made in radial annotator.

Actual restuls: The depictions section is stuck at whatever state depictions were in when you loaded the page. If you reload the page then you can see the updates.

### Location

Several tasks I think over different radial attributes, Browse CO being one for depictions

**Comment by kleintom** [comment]
RadialAnnotator itself emits `close`, so you could update every panel that displays anything the annotator might alter when it closes, but that feels a little inefficient.

I noticed RadialAnnotator emits a custom browser-level event `radialAnnotator:update`, and that gives more specific information about what changed (depictions, citations, etc) when something is added or deleted (well, your component would have to keep a running count to compare the emitted value against), but I don't think it's triggered when say a caption or figure associated with a depiction is edited. (Plus it doesn't feel great to me to be listening in on those events, is that frowned upon or are they 'available for the public to use'?)

I'm not keyed into all the things a radial annotator can alter and whether or not what I'm requesting is even reasonable.

**Comment by jlpereira** [comment]
Hello

Don't use that event when working directly on Vue.
TaxonWorks has 2 asset pipeline that work separately. Both pipelines are separate and compiled differently.

At the time, that event was added to be able to access this information from the other pipeline. In this specific case, this event was created to communicate an interface where there is only a single radial menu, so the listening is carried out only for this menu. The events contain information that specifies the object to which it corresponds, not just the count of each one. There was a time when we used counting to update an interface where annotation information was displayed.

I can add an `update` event for you to use in your Vue app, if that's what you need

**Comment by jlpereira** [comment]
@kleintom new events: `add`, `delete`, `change`. all of them will send the object as `item`, in the case of `change` it will send the metadata too.

Currently it will works only on Depictions slice, I will extend it to the others

**Comment by kleintom** [comment]
Oh wow, thanks @jlpereira, that was fast! I hope I didn't mislead you though... This is very nice, but just update (when an add, delete, or change occurs) would be enough for what I had in mind. If these more general events are what makes the best sense for annotator in general, cool, I just didn't want you to go the extra mile just for my use case (my original title was probably misleading because I already had the add/remove events using the custom radialAnnotator:update and it was just the change events I wasn't able to get - of course now I won't use that custom event).
I just took a quick look, but the other question I had is: will you be able to tell which slice the events are coming from? If not it may be hard to tell whether you need to update the depictions list of your component or the citations list or...
Thanks again!

**Comment by jlpereira** [comment]
I pushed `slice` to the event, but maybe you don't really need it. Each object has the type:

Using object type:
```vue
<RadialAnnotator
  @add="({item}) => {
    if (item.base_class === 'Depiction') {
      myDepictionList.push(item)
    }
  }"
/>
```

I will leave you a simple example of how you can use each event:

`add`, `delete`, `update`(I forgot to mention this one in the previous comment):

```vue
<RadialAnnotator
  @add="handleRadialUpdate"
  @update="handleRadialUpdate"
  @delete="handleDelete"
  @change="doSomething"
/>
...
<script>
import { addToArray, removeFromArray } from '@/helpers' 

function handleRadialUpdate({ item, slice }) {
  if (slice === 'depictions') {
    addToArray(myDepictionList.value, item)
  }
}

function handleDelete({ item, slice }) {
  if (slice === 'depictions') {
    removeFromArray(myDepictionList.value, item)
  }
}

function doSomething() {
  console.log("Something has changed")
}
</script>
```
