### ISSUE TITLE
[Bug]: Cached level0 GAs filtering as cached level1

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3821]
### Steps to reproduce the bug

```bash
Chose Nord-Kivu, DRC for geographic area for CE
DRC does not show up as cached level0 in filterd results
DRC shows as cached level1
Same with Ivory Coast
```

### Screenshot

**Nord-Kivu GA used showing DRC as cached level0:**
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/5a52cd75-5df3-4e24-88f3-6fb06eae9f3f)

**Filtered results showing DRC as cached level1 (see Ivory Coast too):**
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/f7bb0648-05ad-408a-b1bd-ebee99f27947)

**Filtered results showing DRC as state/province (see Ivory Coast too):**
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/83bbb13b-0e36-4c93-9a61-2f4005ac90d1)

**CE with Nord-Kivu chosen as GA:**
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/8652ee99-59d4-4610-be75-77d17397f6f8)

Same issue with Eritrea
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/cf4420a2-0c67-43e1-ba05-a2fbebe27d6c)

### Expected behavior

The geographic areas for the DRC/Ivory Coast should all be at cached level0 in filter results as well. Not sure why it has moved over to cached level1

### Environment

Production

### Version

 v0.38.2

### Browser Used

Chrome Version 121.0.6167.161 (Official Build) (64-bit)

**Comment by mjy** [comment]
In testing the current tweaks (not deployed, see the link for the current values, not the values you see below which were tested locally) seems to improve things:

https://sfg.taxonworks.org/collecting_events/677976 
```
:cached_level0_geographic_name => "Democratic Republic of the Congo",
:cached_level1_geographic_name => "Nord-Kivu",
:cached_level2_geographic_name => nil,
```

https://sfg.taxonworks.org/collecting_events/600470
```
:cached_level0_geographic_name => "Ivory Coast",
:cached_level1_geographic_name => "Bas-Sassandra",
 :cached_level2_geographic_name => nil,
```

https://sfg.taxonworks.org/collecting_events/582356 is trickier because it's TDWG _and_ has no Georeference, but I got it todo this:
```
:cached_level0_geographic_name => "Eritrea",
:cached_level1_geographic_name => nil,
:cached_level2_geographic_name => nil,
```

**Comment by mjy** [comment]
Some existing CEs will have to be rebuilt, but I'm going to close this for now.
