### ISSUE TITLE
[Bug]: Issues with the Filter tab of the Depictions annotator for Browse CO and Browse OTUs

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3824]
### Steps to reproduce the bug

```bash
Steps for Browse CO - similar for Browse OTUs.
1. Go to browse CO for a particular CO, say /tasks/collection_objects/browse?collection_object_id=1
2. Click on the radial annotator and choose Depictions.
3. Click on the Filter tab.

Actual results: get a red overlay saying `coIds.map is not a function`. Dev tools says the error is at `FacetCollectionObject.vue:56`. I'll continue the rest below.
```

### Environment

Development (docker)

### Sandbox Used

No red overlay on sandbox, but you can see the error in devtools

**Comment by kleintom** [comment]
FacetCollectionObject.vue:56 is
https://github.com/SpeciesFileGroup/taxonworks/blob/f5e3a0c74a3b6a324bbc6cd366fce9ac677ea77e/app/javascript/vue/components/Filter/Facets/CollectionObject/FacetCollectionObject.vue#L53-L56
`coIds` is assumed to be an array, whereas in this case it's the number `1`. If I fix that the red overlay goes away, but I think maybe the filter function is still not working?

If I'm reading things correctly it looks like the filter tab is loading a `FilterImage` that's listening for a `parameters` event and calling `loadList` to load images matching the filter, but FilterImage doesn't emit a parameters event and I don't see loadList ever getting called. I could easily just be confused though.
https://github.com/SpeciesFileGroup/taxonworks/blob/f5e3a0c74a3b6a324bbc6cd366fce9ac677ea77e/app/javascript/vue/components/radials/annotator/components/depictions/depiction_annotator.vue#L128-L132

**Comment by kleintom** [comment]
The corresponding Browse OTUs issue is at
https://github.com/SpeciesFileGroup/taxonworks/blob/f5e3a0c74a3b6a324bbc6cd366fce9ac677ea77e/app/javascript/vue/components/Filter/Facets/Otu/FacetOtu.vue#L87-L90

**Comment by jlpereira** [comment]
Yah, you're right. Event shouldn't be there, this was implemented before we refactor filters and we forgot to update it. Otu Facet was fine, by default it was defining an empty array, the problem was CO facet, which it doesn't define anything by default. Anyway I've refactored to reduce request with multiple ids
