### ISSUE TITLE
[Bug]: Layout issues on all model list views?

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3828]
### Steps to reproduce the bug

```bash
Visit any page that displays a list of model items using the app/views/shared/data/all/list/_list_header.html.erb partial (I'm guessing that's what triggers it?), e.g. `/otus/1` or `/loans/1`.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/f4ffdbbb-5b5a-4505-bdab-1722c8a8f63b)
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/a77c3dc7-b8ab-4931-bc25-eb1b346f5f04)

### Environment

Development (docker)

### Sandbox Used

Doesn't occur on sandbox

**Comment by kleintom** [comment]
Woops, hold up, this might be me, sorry, I'll check back once I dig a little more.

**Comment by kleintom** [comment]
Yup, this was me!

This was apparently caused by my adding a `horizontal` class in a new component I'm writing - _show.html.erb also uses a `horizontal` class, I guess my definition was overwriting/mixing with another.
I'm still pretty clueless on some rails stuff, is that because of
> The third feature of the asset pipeline is to concatenate all CSS files into one main .css file

from https://guides.rubyonrails.org/asset_pipeline.html

Does this mean every css class I define in a vue component is used globally? So I should be really careful with naming css things I guess. How does a person avoid unintentional css overwrites when naming new classes aside from checking every other css file? Thanks.

**Comment by jlpereira** [comment]
You can define your CSS in your vue component using `<style></style>` tags, if you don't want to make it global, use `<style scoped>`
