### ISSUE TITLE
Edit taxon name: delete combination doesn't work

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#3831]
There I want to delete the penultimate one (Acrida hungarica mediterranea Dirsh, 1949):
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/930bf123-2708-4a25-a070-56e6d6a28f03)

After clicking on the dustbin and accepting destruction it disappears:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/21ee10d0-0a3a-4f71-a2d0-ead73f1d8d6f)

However, after refreshing the page it is still there:
![imagen](https://github.com/SpeciesFileGroup/taxonworks/assets/33210201/cbcaa66f-9be1-403b-9e30-be350724a7c5)

**Comment by jlpereira** [comment]
Is this one: https://sfg.taxonworks.org/combinations/1089044.json

@mjy Response code is 204, but it's not destroying it.

**Comment by proceps** [comment]
combination has an associated OTU. Please, delete or reassign the OTU first.

**Comment by typophyllum** [comment]
Thanks. OTU and combination destroyed.
