### ISSUE TITLE
[Bug]: Cannot customize new OTU in the "new image" tab without creating a taxon name.

### ISSUE THREAD

**Issue by teleaslamellatus** [SpeciesFileGroup/taxonworks#3836]
### Steps to reproduce the bug

```bash
1.go to new image
2.go to taxon determination and type in something that is not in the system.
3. choose customize a new otu...
4.fill out "name"
5.hit create (green)

Nothing will happen, only if you add something to the taxon name field
...
```

### Screenshot

<img width="586" alt="tututu" src="https://github.com/SpeciesFileGroup/taxonworks/assets/9273125/2e444d2f-1a71-422b-99ca-c1871522782e">

### Expected behavior

Reate new OTU name without assigning it to any taxon name

### Environment

Sandbox, Production

### Sandbox Used

https://sandworm.taxonworks.org/tasks/images/new_image/index

### Version

build a0c770317

### Browser Used

chrome

**Comment by jlpereira** [comment]
This was already fixed a few days ago, it should work correctly in the next release

**Comment by teleaslamellatus** [comment]
Can you tell me when the next release is out? Or should we do something on our side to get this feature back?

Thanks!

István

**Comment by mjy** [comment]
Week of Feb. 20.  You can always check the CHANGELOG.md to see when something is live.  You will also see 0.38.3 in TW when it is live.

**Comment by teleaslamellatus** [comment]
It is this week, thanks!

István
