### ISSUE TITLE
Task - Observation matrix dashboard - OTUs with depiction param does not work

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3839]
When I request OTUs and what to restrict the results to observations which has depictions, the filter return me all OTUs.

**Comment by mjy** [comment]
Can't replicate. https://sfg.taxonworks.org/tasks/otus/filter?per=50&depictions=true&extend%5B%5D=taxonomy&page=1

**Comment by jlpereira** [comment]
That's Filter OTU @mjy 
Dimitry is talking about https://sfg.taxonworks.org/tasks/observation_matrices/dashboard

**Comment by mjy** [comment]
Duplicate #3686.
