### ISSUE TITLE
Radial Annotator - Data atributes - smart selector is not visible

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3847]
When a model is set for custom attributes in project preference, the smart selector for keyworks is not visible. I would expect to see both. I can select custom attributes for the model, but occasionally I may want to use something different. Also I came to a case where I do not have any custom attributes on OTU in the project, in this case I have completely blank page in the radial annotator, the smart selector for the keyword should still be available for me.

**Comment by jlpereira** [comment]
@mjy We have a data_attribute slice for quick forms and another one for radial annotator. What do you think about unifying this on radial annotator?

**Comment by mjy** [comment]
The point is to have a focused precise list on Object Radial and global options on Radial Annotator. Not all models have the former.  Merging the two brings increased complexity to those who want to quickly see the object radial list without further complexity.
