### ISSUE TITLE
Add source by DOI

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#385]
When I need to create or reference a source, then I want to add a DOI and have the source created automatically, and referenced inline if needed.

**Comment by mjy** [comment]
Basic approach: 

* [ ] Use CrossRef API to resolve a DOI, see source by citation for a starting point
* [ ] Provide model method that returns Source::BibTeX from the result
* [ ] *extend* `New from citation task` to detect and request by DOI rather than Just the full citation.

**Comment by TuckerJD** [comment]
[CrossRef REST api doc](https://github.com/CrossRef/rest-api-doc)
[Ruby gem `serrano`](https://github.com/sckott/serrano)

**Comment by mjy** [comment]
We have our own gem that could be extended too- but abandoning it for serrano might be a good idea.
