### ISSUE TITLE
Request for new task to merge OTU's

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#3855]
### Feature or enhancement

I thought we had an open issue on this, but I can't find it.  

We need a task to merge information from two or more OTU's.  For example, check out Prochiloneurus dactylopii and P. dactylopiione (the latter renamed by me to simplify telling which is which) in the UCD.  These are two taxon names with the same author and date, with two (actually three) OTU's with non-overlapping data.  There is a Merge Taxon Names task which I applied to them and which seemed to work in part but not completely.  This is a rather complicated case that would be difficult to resolve manually.

We also created numerous OTU's with identical names tied to the same taxon name when we were eliminating ghosts caused by verbatim host records in UCD.  

### Location

Task - merge OTU's

### Your role

Curator of UCD project in TW

**Comment by mjy** [comment]
Now duplicated and covered in https://github.com/SpeciesFileGroup/taxonworks/issues/970
