### ISSUE TITLE
[Bug]: Edit CE and Print labels task - labels remain in CE record and Print labels queue after deleting

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3878]
### Steps to reproduce the bug

```bash
1. In the edit CE record with Verbatim label data filled in, I click "copy from verbatim" and added 4 labels to the que to print
2. The labels are available in the Print labels task
3. Now I would like to remove the labels
4. In the edit CE record I deleted the "copy from verbatim" and zeroed out the que to print
5. Refreshing the page and/or clicking Save shows the "copy from verbatim" and zeroed out que to print

The labels are still available in the Print labels task queue.
If I delete Verbatim label and delete all label information and Save the labels are still in the Print labels queue.
And if I type that CE into another task to bring it up anew the  "copy from verbatim" and 4 labels added to the que to print still exist in the CE record and in the Print labels queue.

...
```

### Expected behavior

If I delete the label information from the CE record, I would expect the label information to be fully deleted and also be deleted from the print queue.

### Additional Screenshots

**Cleared Verbatim label field:**

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/6e5d7a74-7460-449e-97a0-ff2d925dbfb0)

**Cleared Print label fields:**

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/3b7cf572-bfea-4619-b716-f26cbfec890f)

**Still in Print queue:**

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/0788bb25-3753-410a-a564-01faffbee16c)

### Environment

Production

### Version

 v0.39.0

### Browser Used

Chrome Version 122.0.6261.128

**Comment by jlpereira** [comment]
@AntWeb-org  When the textarea is empty, the label will be destroyed

You will see this on the next update

**Comment by AntWeb-org** [comment]
Thanks!

**Comment by AntWeb-org** [comment]
@jlpereira Just to confirm, the text in the Print labels box should be empty to destroy the label? Not the Verbatim label text box?

**Comment by jlpereira** [comment]
> @jlpereira Just to confirm, the text in the Print labels box should be empty to destroy the label? Not the Verbatim label text box?

You will only have to clear the print label text input, not the verbatim label
