### ISSUE TITLE
Add a hub task for dichotomous keys

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3881]

**Comment by proceps** [comment]
I would prefer to have it as a part of Observation Matrices Hub. Which could potentially be renamed.

**Comment by mjy** [comment]
> I would prefer to have it as a part of Observation Matrices Hub. Which could potentially be renamed.

Disagree here.  One might transcribe historical keys and never use Observations.  I suspect you're thinking of other ways to visualize connections b/w the two that we'll work out later.

**Comment by proceps** [comment]
I am thinking in terms of grouping OTUs into a key or matrix. It is the same process, I select a group of OTUs (or Collection objects) to add to a key, and do some operation on the group of those OTUs (Adding scores). I may use the same group of OTUs to build a matrix, dichotomous key, or the image matrix. I prefer to do all those operations in a single place. Historical keys is just one of many possible use cases.

**Comment by mjy** [comment]
Hub is just a hub to guide you for context, it's not where we do work like adding things to a key.
