### ISSUE TITLE
Filter Collection Object >  Batch Annotate > add ability to add/set Preparation Type 

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3889]
### Feature or enhancement

When looking at my Collection Objects, I note that Preparation Type is not set.
For (most) of them, the Preparation Type = pin.

I'd like to be able:
- Go to Filter Collection Object
- Select all of my desired objects (in this case, all of them)
- Choose Mass Annotate > pick Preparation Type

This would (of course) add the desired value where value for a given CO was null, and overwrite any other existing value that might be there.

This request comes from @pbrockPhas at the [20 March Open Session (early)](https://docs.google.com/document/d/1uKnFdxP-fpA4tGdPWdhf8wJr9co3C6jpM_svzZYYsos/edit#heading=h.1wkfvxszhvdx)

### Location

Filter Collection Object > Mass Annotate

### Your role

Community Liaison

**Comment by debpaul** [comment]
@jlpereira has this been pushed to production yet? @pbrockPhas and I don't see it?

**Comment by debpaul** [comment]
> Yes, it should be there

@jlpereira we don't see Prep Type in the annotator options.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/cdb071de-71de-495b-865e-b6c058f558f4)

**Comment by mjy** [comment]
Wrong radial, you need the one to the right.  You are showing annotations, you want object.

**Comment by debpaul** [comment]
Thanks @mjy, much appreciated. We also note that the limit is 50 and @pbrockPhas has 10K to change.
