### ISSUE TITLE
[Bug]: Leads order issues on updates

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3890]
### Steps to reproduce the bug

```bash
STR below.
```

### Environment

Development (docker)

### Version

0385006ade5f94b109d00518bfee891935c3ead0

**Comment by kleintom** [comment]
STR:
1) Create a new key.
2) Give the newly created left and right nodes some text so you can tell which is which in the ui.
3) Click Update.

See the text you entered switch sides. Everytime you click Update the sides switch, and in the database you can see the positions switch.

Here's a test that fails by replicating what we do in leads_controller#update:
```ruby
specify "'ui update' doesn't change order of chidren" do
  # Simulate a ui update saving all three nodes of a couplet.
  l = FactoryBot.create(:valid_lead, parent: lead, text: 'bottom left')
  r = FactoryBot.create(:valid_lead, parent: lead, text: 'bottom right')
  lead.update! text: lead.text
  l.update! text: l.text
  r.update! text: r.text
  expect(l.reload.position).to be < r.reload.position
end
```

**Comment by kleintom** [comment]
Replacing https://github.com/SpeciesFileGroup/taxonworks/blob/d2d20b2ea82b04104cf0911a7223733a32a8695f/app/controllers/leads_controller.rb#L123-L125 with
```ruby
@lead.update!(lead_params)
@left.reload.update!(lead_params(:left))
@right.reload.update!(lead_params(:right))
```
seems to fix the issue (and changing the spec to follow that pattern makes it pass). Is this a case where it would be better to use a controller spec though, so that we're still testing in case the controller update changes?

;tldr I ran into this issue when we had:
  switched to acts_as_list
    turned off numeric order on has_closure_tree
So acts_as_list was the only one updating positions - I restored the version of my database from when has_closure_tree was setting positions with values 0,1, whereas acts_as_list (currently) wants 1,2, so newly created couplets were fine (they had positions 1,2) but everytime I updated a couplet where the child positions were 0,1 acts_as_list was trying to change them, but did it in a way that just wound up flipping positions (iirc it changed 0 to 1 and then decreased the other positions by 1...). Actually, yes, that's what I'm seeing happening in the current output now as well.

So long story short I suspect this is acts_as_list trying to fix a position with 0.
If I add `top_of_list: 0` to the `acts_as_list` declaration - which seems like we should probably do - then I no longer need the `reload`s in the controller #update or the new update spec. But two of the delete specs then fail.

For what it's worth, my vote would be to remove acts_as_list entirely as long as we're using `numeric_order` on has_closure_tree. It's scary to me to think that both has_closure_tree and acts_as_list are trying to update positions at the same time. If I do that then the same two delete specs fail (but in a different way).

If that's what we want to do, feel free to let me know and I can work on getting the tests passing again (though I understand if with the unexplained weirdness going on it's better to do it yourself).

**Comment by mjy** [comment]
> For what it's worth, my vote would be to remove acts_as_list entirely as long as we're using numeric_order on has_closure_tree.

Your observations are definitely worthwhile!

>  It's scary to me to think that both has_closure_tree and acts_as_list are trying to update positions at the same time. If I do that then the same two delete specs fail (but in a different way).

I concur.

What I am not certain of is that `closure_tree` is ordering as we need.  Can we independantly move siblings back and forth (including multifurcations, i.e. siblings sets of 2+).

Thought just crossed my mind.  Not documented well, but what happens when we start from 0?:

 https://github.com/brendon/acts_as_list/blob/master/test/test_list.rb#L108C31-L108C45

Will think about this more.

**Comment by mjy** [comment]
@kleintom Feel free to take a stab at removing acts_as_list.
