### ISSUE TITLE
[Bug]: including data attributes in DWC export causes it to never process, fails indefinitely

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3897]
### Steps to reproduce the bug

```bash
1. When I want to export COs with data attributes
2. And I generate a DWCA download
3. Then it never generates.
4. If I do same download without data attributes
5. Then it generates.
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/70e5689b-c5fb-4c5a-b488-ac076d872787)

### Expected behavior

Example screenshot is with data attributes on CE and COs (earliest, processing for >12 hours), data attributes just on CO (second, processing >10 minutes), and without data attributes (done in <1 minute) 

### Environment

Production

### Version

0.40.0

### Browser Used

Firefox

**Comment by mjy** [comment]
Mmmarg.   @tmcelrath can you send me link to the filter query you are sending for download just to ensure I can replicate.  We will make this a blocker.

**Comment by tmcelrath** [comment]
https://sfg.taxonworks.org/tasks/collection_objects/filter?per=50&collecting_event_id%5B%5D=125413&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1&data_attribute_predicate_id%5B%5D=491

As always, it's this one. 

I tried to download the "AccessionNumberLabel" and "SpecialCollection" Data Attributes and that caused it to never download.
