### ISSUE TITLE
[Bug]: Filter CO-data attribute search function not working

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3903]
### Steps to reproduce the bug

```bash
1. Want to search COs from Mayotte using Data Attributes
2. Scroll down to Data Attributes
3. Under Predicate, type country
4. Add Mayotte
5. Filter
Zero results filtering for any data attribute under Predicate
...
```

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/28f2f558-ad14-48a5-be9b-a39d751dd339)

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/1345ffb3-a30f-4b9f-adef-c866de49b518)

### Expected behavior

When I filter collection objects using data attributes, I would expect results similar to those in the CE filter.

Filtering data attributes work in the CE filter but it is an extra step to then filter the CEs to COs.

### Environment

Production

### Version

v0.40.0

### Browser Used

Chrome Version 123.0.6312.86

**Comment by mjy** [comment]
I can't replicate this.

**Comment by mjy** [comment]
My data are not the same as production (I've been messing with it offline), but see:
<img width="1118" alt="Screenshot 2024-04-02 at 3 58 38 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/8b6e4f26-88ca-4695-a9ec-30cb8af344c9">

**Comment by AntWeb-org** [comment]
Those are filter results for the CE records I believe. The CO filter is not returning results.

**Comment by mjy** [comment]
Oh, I see. The data attributes there are for CollectionObjects, `country` is a Predicate used on CollectingEvents, so that's why you see nothing here.  The DataAttribute search only searches on Predicates used on this object type, not on predicates linked through other object types.  You'll have to search on CEs first, then pass that here.

**Comment by AntWeb-org** [comment]
It would be extremely valuable to have all of the predicates linked to the COs as well so we do not have to do a two-step filter. One of our most used filters would be finding COs for countries. The GA sort of works but our country predicate is more accurate with regards to filtering.

@bpescador

**Comment by mjy** [comment]
We added a note via the orange ? help to clarify this function of facet.  At this time, as we don't plan to extend this functionality further becaused of the conceptual and implementation complexity it would introduce I'm going ot close this.
