### ISSUE TITLE
[Bug]: Task - CSD: Save and New copies attribute to next CSD record

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3910]
### Steps to reproduce the bug

```bash
1. Entering a record into the CSD task
2. In the Attributes panel, I added data to the LifeStageSex field and the SpecimenNotes field.
3. Save and New copied over the "SpecimenNotes" data but not the LifeStageSex data.


...
```

### Screenshot

SpecimenNotes field should be blank:

<img width="277" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/1fea2f7b-1aad-45c0-9520-0c8acaa982d2">

### Additional Screenshots

Save and New should not copy over attributes or data attributes to the next CSD record

### Environment

Production

### Version

 v0.40.1

### Browser Used

Chrome Version 123.0.6312.105

**Comment by AntWeb-org** [comment]
I will have to keep you posted. It happened one one carry over record but not the next one.

**Comment by AntWeb-org** [comment]
Still holds true. When I added a new trip code namespace, identifier and verbatim collection code, I clicked Save and the  custom attributes filled in with data from a previous trip code. This is still within the CSD if that helps. Thanks

**Comment by jlpereira** [comment]
Hello. Could you provide the exact steps of everything(fill input, click button, etc) you do to replicate it? Because I can't replicate this on my environment, I will need more details

**Comment by AntWeb-org** [comment]
Entering a new CSD
1.	Namespace, identifier number, repository, preparation - Save
2.	OTU, determiner, determined date - Save
3.	Attributes – custom attributes: lifestagesex, specimennotes - Save
4.	Collecting Event: verbatim trip identifier, tripcode namespace, identifier
5.	Custom attributes: verbatimcollection code – Save
This seems to be when those attributes fill in with the previous tripcode data
Hope this helps. Let me know if you need more information.

**Comment by jlpereira** [comment]
Did you enter/load other collection object before replicate it? You did get this problem from the first record, right? 

I can replicate this but after edit/create/load another record. Could you confirm your issue doesn't happen on the first time you open the interface and create the first record?

**Comment by AntWeb-org** [comment]
It did not autofill on the very first record CSD I entered. 

Only if I am entering multiple CSD records where I am also entering new collecting events in the CSD record, the issue persists. But it is intermittent. I can figure out consistencies as to when it happens.

I am not loading or editing other CEs while entering another CSD.

**Comment by AntWeb-org** [comment]
Just to clarify, I am first entering the trip codes and identifiers, clicking Save, then entering the rest of the collecting event data all from within the CSD. Perhaps that is what you mean by editing or modifying the CE.

**Comment by AntWeb-org** [comment]
It happened on the following CSD record again after entering the new verbatim trip code, namespace, identifier and verbatimcollectioncode in the custom attributes fields after Save. Here is a screenshot of the new trip code saved but before entering the rest of the verbatim and parsed collecting event data. You can see the data autofilled from the previous trip code into the custom attributes fields in the second screen shot.

<img width="367" alt="Screenshot 2024-04-11 075216" src="https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/be3e1ac3-ad42-4d2c-a470-42263c684445">

<img width="294" alt="Screenshot 2024-04-11 075310" src="https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/6f1f62ed-66a7-421c-a59f-402ac8fba88c">

**Comment by AntWeb-org** [comment]
Thanks José!

**Comment by jlpereira** [comment]
@AntWeb-org just to let you know, a new version was released today.
