### ISSUE TITLE
[Bug]: Error on radial navigate on filter results from some Filter tasks

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3911]
### Steps to reproduce the bug

```bash
I'm seeing errors in some of the Filter tasks when I run the filter, select one or more rows, and then click the navigator radial. I'll give a couple examples below.
```

### Environment

Sandbox, Development (docker)

### Version

64b5def5e94d6eedf2aeabff3f4e7853e419264a

**Comment by kleintom** [comment]
For the Filter Otus task, I get `undefined method '+' for nil` at app/helpers/workbench/navigation_helper.rb:18:in `block in class_navigation_json'

For the Filter Images task, I get `undefined method '[]' for nil` at app/helpers/workbench/navigation_helper.rb:17:in `class_navigation_json' 

Browse COs was fine I think, I haven't checked any others.

**Comment by mjy** [comment]
Didn't follow this to conclusion but believe this is fixed now.
