### ISSUE TITLE
add sort by term (name) or count to project vocabulary task

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3915]
### Feature or enhancement

When using the Project Vocabulary Task, I would like to be able to sort by:
- **term** or
- **count**
by clicking on the words `term` or `count`.

I'm not sure it will be useful yet for ALL possible fields in every model. However, it will be quite useful for others.

Example:
Model: Collecting Event
Attribute: verbatim_trip_identifier

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/d9d6db85-3b13-4de6-b458-34cf2e9d34cd)

### Location

Task - Project vocabulary

### Your role

Informatics Liaison

**Comment by jlpereira** [comment]
Done
