### ISSUE TITLE
[Bug]: BibTeX Batch Upload Error

### ISSUE THREAD

**Issue by alexpaleo** [SpeciesFileGroup/taxonworks#3917]
### Steps to reproduce the bug

```bash
1. BibTeX Batch Load Sources
2. Uploaded .bib file with some invalid entries highlighted in the preview
3. Upon selecting "create", I received the 500 error.
...
(Upon trying to recreate this issue today, the valid source entries were created.)
```

### Screenshot

[Cenozoic-Mollusca-Types_Zotero-Export_20240326 copy.txt](https://github.com/SpeciesFileGroup/taxonworks/files/14936125/Cenozoic-Mollusca-Types_Zotero-Export_20240326.copy.txt)

(this is a text version of the .bib file which is not supported in this box)

### Expected behavior

When I upload a batch of sources with some invalid, I expect the valid entries to be created.

### Environment

Sandbox

### Sandbox Used

SANDBOX - build b12beec67

### Browser Used

Chrome

**Comment by debpaul** [comment]
@alexpaleo note that one entry in the file, when using the **preview** you can see that it has a formatting error.
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/d5d4db40-22a2-4a85-869a-dd56773e5357)

So, all entries except any in red ought to upload.

Testing: to upload (after you do a **Preview**) you need to click to get the file again, then click **Create**

Result:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/2990155/12871759-c0bb-4e39-811d-43201c89c828)

BibTeX Batch Load Sources
Imported 115 records.
Failed to import 3 records

You can see the errors for the entries that failed to upload.

You can
a) try to fix these errors manually if you can figure them out, then use the individual BibTeX import route
b) use a BibTeX linter (like https://flamingtempura.github.io/bibtex-tidy/index.html?) for these three entries
c) enter these manually
d) try to find the entries with a full-text search (as we demoed for you) in the New Source task

Hope this helps?

**Comment by debpaul** [comment]
@alexpaleo I'm closing this ticket because I think this is solved ... by noting that after the _preview step_ you have to go and click to (browse to) the file again, then click **create** to get the "green" sources to upload. If you still have an issue, with the same task, you can reopen the ticket.

**Comment by alexpaleo** [comment]
Thank you!! Yes, I definitely have a greater understanding of entering the publications now.
