### ISSUE TITLE
[Bug]: DwC export - associatedMedia not matching correct collection object

### ISSUE THREAD

**Issue by LauraPorturas** [SpeciesFileGroup/taxonworks#3918]
### Steps to reproduce the bug

```bash
1. Filter collection objects
2. Select collection objects, download DwC 
3. Go to DwC Dashboard
4. Download data from "Recently created DwC Archives" section
5. Choose an occurrence record
6. Follow URL from the "associatedMedia" field, which takes you to a page like the screenshot attached
7. Follow URL from this page associated with the "original", "thumb", and "medium" size options, and the images are of different collection objects than the chosen occurrence record


...
```

### Screenshot

<img width="663" alt="Screen Shot 2024-04-10 at 3 01 09 PM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/62353864/853323f4-9517-4ce7-b881-e428ff5584df">

### Expected behavior

When I download DwC archive, I expect the associatedMedia field to map to the correct collection object/occurrence record

### Environment

Production

### Browser Used

Chrome

**Comment by mjy** [comment]
@LauraPorturas Can you please also share the URL you used to filter the results? You can copy/paste the browser URL after the filter, or use the eyeball on the right, click the "JSON" option, and copy what pops up there.

**Comment by mjy** [comment]
Note to myself- another potential issue is DwC not re-indexing when depictions on object change.

**Comment by LauraPorturas** [comment]
@mjy Here it is:
?per=50&keyword_id_or%5B%5D=1822&keyword_id_or%5B%5D=555&keyword_id_or%5B%5D=757&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1

**Comment by mjy** [comment]
Finally fixed this by cross-referncing another bug.  Will be live on the next release. Thanks @LauraPorturas.
