### ISSUE TITLE
[Bug]: DwC export - otu_name not included with large exports

### ISSUE THREAD

**Issue by LauraPorturas** [SpeciesFileGroup/taxonworks#3919]
### Steps to reproduce the bug

```bash
1. Filter collection objects
2. Select collection objects, download DwC (select 'Include biological associations as resource relationship' & select all 'Internal values')
3. Go to DwC Dashboard
4. Download data from "Recently created DwC Archives" section
5. Look at generated data.tsv file, and sometimes the 'Internal values' fields (i.e., TW:Internal:otu_name, TW:Internal:collecting_event_id, TW:Internal:elevation_precision, TW:Internal:collection_object_id) are not there. 

Note: This problem was not present when downloading small datasets (1 & 4 collection object records) but WAS present when downloading a very large dataset (>22k collection objects, associated with the TPT project)
```

### Expected behavior

When I download a DwC archive, I expect Internal values to be present

### Environment

Production

### Browser Used

Chrome

**Comment by mjy** [comment]
@LauraPorturas Does it export a `tw_extension_data.tsv'` file?    I see that the otu_name field is mapped to a separate file.  Exploring further.

**Comment by mjy** [comment]
@LauraPorturas When I use this query: `/tasks/collection_objects/filter?per=50&descendants=true&taxon_name_id%5B%5D=684487&extend%5B%5D=dwc_occurrence&extend%5B%5D=repository&extend%5B%5D=current_repository&extend%5B%5D=collecting_event&extend%5B%5D=taxon_determinations&extend%5B%5D=identifiers&exclude%5B%5D=object_labels&page=1` Then I see the column.  Can you copy/paste the URL of a query that does not display the data?

**Comment by LauraPorturas** [comment]
@mjy I apologize, I just used the same query as before and I see the column now. It is entirely possibly that I thought I clicked the all "Internal values" option, but missed. If the "bug" resurfaces again, I'll reopen this report.

**Comment by mjy** [comment]
Zero worries, sorry for not following up on this earlier.
