### ISSUE TITLE
How to extract IMAGE Notes and Attribution from the API?

### ISSUE THREAD

**Issue by adrik29** [SpeciesFileGroup/taxonworks#3920]
I couldn't find in the API documentation how I get **Notes** and **Attribution** for use with the **images**.
A little help would be lovely.

**Comment by jlpereira** [comment]
Hello @adrik29 

For notes the route is: `/api/v1/notes`
You can use `note_object_id` and `note_object_type` parameters to filter by id and type

For attributions I think we don't have a public route, but you could get them from images using `/api/v1/images?extend[]=attribution`

**Comment by adrik29** [comment]
José Luis, that's lovely. Will try it right away. Thanks for the attention!

**Comment by jlpereira** [comment]
@adrik29 np :D

Have you been able to get the data?

**Comment by adrik29** [comment]
@jlpereira -- Oh yeah. Thanks to you!
