### ISSUE TITLE
Task - Browse taxon names - Combinations erroroneously showing as valid on right side

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#393]
When I browse a combination, then sometimes(?) I see a combination with an invalid species being shown as valid on the right side summary box.

**Comment by proceps** [comment]
@jlpereira Could you check this. All combinations are now as valid. When I click on the combination entry, it should always be shown as invalid entry. Or preferably it should be clearly marked as combination entry, and not as a valid species entry

**Comment by jlpereira** [comment]
@proceps could you give me an example of this on Sandbox?

**Comment by proceps** [comment]
http://sandstorm.taxonworks.org/tasks/nomenclature/browse/49784
Only one project is there, I added you as a member
in this species, only when you have the first line, marked with a green checkmark, you should see the status of the valid name on the right side. When I click on the synonym, I statement changes that the name is not valid. But when I click on a combination, it shows me the status of valid. I think, when we click on any combination name the status on the right should change to the "Cobmination of ..."

**Comment by jlpereira** [comment]
Mmmmm, i dont have an account there

**Comment by proceps** [comment]
I added you as a database user, but not as a project user. I added you as a project member with a ellocodelassembler address.

**Comment by jlpereira** [comment]
That's my brother email.

jlpereira[at]speedy.com.ar

**Comment by proceps** [comment]
done

**Comment by jlpereira** [comment]
Aha, I think I see what you mean.

<img width="1405" alt="captura de pantalla 2018-06-13 a la s 15 07 06" src="https://user-images.githubusercontent.com/16530364/41369571-a78b602a-6f1b-11e8-9abb-7c68e09c50eb.png">

**Comment by jlpereira** [comment]
Try now, @proceps

**Comment by jlpereira** [comment]
Just to clarify something, Combinations should be displayed always as invalid?

**Comment by proceps** [comment]
Sorry, was out for the rest of the day. I can check it only tomorrow. I think it would be better if we can display Combinations as Combination instead of invalid. Invalid will sound little bit confusing.

**Comment by proceps** [comment]
@jlpereira, combinations should not be marked with a green check mark. Only one taxon on the left side has a green check mark, the same rule should be applied to the left side. So when we click on a synonym we have a message: "This name is not valid/accepted. The valid name is Orientus ishidae (Matsumura, 1902)."
When we click on a combination we should have the same yellow warning triangle and a message "This name is subsequent combination for..." and the name of the taxon.

**Comment by jlpereira** [comment]
Can you take a look if this change is okay, @proceps ?

**Comment by proceps** [comment]
Perfect!!!
