### ISSUE TITLE
Bug: CSD - locking mechanisms not carrying to next record

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3941]
### Steps to reproduce the bug

```bash
1.Namespace: choose "CASENT" for namespace and select the locking mechanism
2.Repository: choose "California Academy of Sciences" and select the locking mechanism
3.Preparation: choose "pin" and select the locking mechanism
4.click Save to reveal rest of record for data entry
5.proceed to enter rest of data for CSD record
6.click Save and New for the next CSD record

Sometimes the option for repository returns to blank but the locking mechanism is still selected

Sometimes the option for preparation returns to blank but the locking mechanism is still selected

Sometimes the option for repository or preparation returns to blank and the locking mechanism is also unlocked
...
```

### Screenshot

This time "pin" under preparation is _not_ selected but still locked
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/16856423-5b86-4411-84e3-86823850c3c4)

### Expected behavior

When the locking mechanisms are selected, they should lock in the current namespace, repository and preparation and carry over to the next CSD record.

The locking mechanisms are not consistent and there is no rhyme or reason as to which locked panel will carry over as a blank to the next CSD record.

### Environment

Production

### Version

v0.41.0

### Browser Used

Version 124.0.6367.119

**Comment by jlpereira** [comment]
Hello! I can't replicate it following these steps. I will need more information to see what could be the issue, for example, what is the rest of the data you're loading. Are you only locking those 3? Could it be that maybe you pressed "Reset" instead of "Save and New"?

**Comment by AntWeb-org** [comment]
It is random but I do fill out the full CSD record including all custom attributes. 

I am only locking those 3 options since they remain the same. So basically, I enter the 3 top options, click Save, enter the rest of the data then click Save and New. 

I was wondering if minimizing the window had anything to do with it. I do not recall this happening on full screen.

**Comment by jlpereira** [comment]
@AntWeb-org  I couldn't replicate the problem, but I did a refactoring of a part of the save and reset process that could perhaps cause this. Still, I can't promise that the issue has been resolved. If it happens again, please reopen the issue. Remember that you will see the change once a new version is released, so you will not see this patch in production yet.

**Comment by AntWeb-org** [comment]
This was happening for another researcher here too. Hopefully the fix will work. Thanks!
