### ISSUE TITLE
Task - Filter Nomenclature - with/without identifiers

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#3942]
Adriano wants to filter for taxa with or without identifiers.

**Comment by adrik29** [comment]
@proceps -- Thanks. I think such a filter would be useful. We are employing various kinds of identifiers in our project.  Which taxa have LSID...
And, thinking beyond, not only for taxa. For example, which sources have DOI or LSID.

**Comment by jlpereira** [comment]
@adrik29 added local and global identifiers with/without facets to Filter nomenclature.

Filter source already have them

**Comment by adrik29** [comment]
@jlpereira Fantastic! Thanks a lot -- I'll be alert.
