### ISSUE TITLE
Auto-ranking for namespaces should be by Project use

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3948]
### Feature or enhancement

When i am in a place where I am adding a namespace (e.g. comprehensive, or identifier menus)
And I search for a namespace
Then the most used one in the project should show up at the top. 

### Location

Identifier wheel, comprehensive, collecting event edit, etc ...

### Your role

Collections manager

**Comment by mjy** [comment]
In the interm, consider pinning Namespaces, do we have that form integration working?
