### ISSUE TITLE
[Bug]: PDF Document Viewer not working?

### ISSUE THREAD

**Issue by JimWoolley** [SpeciesFileGroup/taxonworks#3950]
### Steps to reproduce the bug

```bash
The PDF Document viewer does not seem to load a paper, no matter which task it is invoked in.  I am clicking on the round blue pdf icon, for example, with a paper loaded in Sources (in this case, source 213716.
```

### Environment

Production

### Browser Used

Chrome

**Comment by jlpereira** [comment]
Hello Jim! I can't find the source, could you paste the link here?

**Comment by JimWoolley** [comment]
José, not sure what source I was referring to now, as I must have mistyped the number.  However, PDF document viewer doesn't work for me no matter which source I choose.  For example: Aalaoui, M.E. & Sbaghi, M. (2022) Parasitism potential of four Moroccan local parasitoids species against three invasive scale pest species of agricultural importance. International Journal of Tropical Insect Science. https://doi.org/10.1007/s42690-022-00926-z

**Comment by jlpereira** [comment]
<img width="1099" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/16530364/cc3b4443-9a5f-4ce7-aa01-99d4fb11cc3f">

It works for me
Did you tried using a different browser? If it works in that case, try cleaning your browser cache

**Comment by mjy** [comment]
Jim's settings:

<img width="565" alt="Screenshot 2024-05-22 at 10 38 08 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/4cb5560f-e18d-4bfd-af8a-7d4bf4065962">

<img width="683" alt="Screenshot 2024-05-22 at 10 39 08 AM" src="https://github.com/SpeciesFileGroup/taxonworks/assets/22600/dadede15-633c-4ac3-9ef5-6bc4436fa410">

**Comment by mjy** [comment]
It is working on Matt's v. 126.

**Comment by jlpereira** [comment]
@JimWoolley This problem seems to be related to the version of your browser, you could try updating MacOS and installing a more modern version of Chrome, or try another browser like Firefox that allows you to install a modern version on your system
