### ISSUE TITLE
[Bug]: Some red "trash can" icons don't delete from the database

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3954]
### Steps to reproduce the bug

```bash
Maybe I'm being too literal, but my interpretation of the docs is that red should mean the thing being deleted is being removed from the database.

In filter facets and similar lists of records that have been selected from search the trash can means (as far as I can tell) "delete from this list I'm showing/delete these items you've selected", not delete from db, so I'd expect blue instead of red in those cases.
```

### Environment

Sandbox, Development (native)

**Comment by kleintom** [comment]
As an example, in filter CEs, one of the facets shows a blue delete icon, another shows red:
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/632915/a276cafc-2517-4067-a9fe-9527e7b4f674)

The red one doesn't actually delete the CE from the database. As a new user this used to give me pause, wondering what was going to happen.

**Comment by mjy** [comment]
100% Tom, we'll change this color.

**Comment by jlpereira** [comment]
Solved by https://github.com/SpeciesFileGroup/taxonworks/pull/3955
