### ISSUE TITLE
[Bug]: Error on NeXML export View

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3961]
### Steps to reproduce the bug

```bash
1. View an OM /tasks/observation_matrices/view/31
2. Click on the View NeXML link

On View NeXML get a 500 error 'Missing partial observation_matrices/export/nexml/_nexml.rdf.builder'.

I don't personally have any need for this, just filing since I noticed it.
```

### Environment

Sandbox, Development (docker)

**Comment by mjy** [comment]
Confirmed. We've been triaging our raise emailer with the University and this was the first thing we got since the tweaks.

**Comment by kleintom** [comment]
FWIW the Download NeXML link seems to work (as far as I can tell), but if I install the Mesquite nexml plugin from here: https://github.com/nexml/nexml/wiki/NeXML-Manual#user-content-Applications_that_support_NeXML_for_input_or_output and try to load the exported NeXML file in Mesquite I get an error `java.lang.NoClassDefFoundError: org/nexml/model/DocumentFactory` (maybe the plugin is out of date wrt to my Mesquite version, or vice versa), so I'm not sure how to verify that.

**Comment by mjy** [comment]
IIRC Mesquite largely dropped support for NeXML.
