### ISSUE TITLE
[Bug]: 500 on /tasks/administrator/project_classification

### ISSUE THREAD

**Issue by kleintom** [SpeciesFileGroup/taxonworks#3964]
### Steps to reproduce the bug

```bash
1. As an administrator, go to Administration/Project Classification: /tasks/administrator/project_classification

Get a 500 error saying 'The asset "chartjs.js" is not present in the asset pipeline.' at http://localhost:3000/tasks/administrator/project_classification#

I tried this on sandbox and after a long while got an internal error (though I expected it to be a permissions error).
```

### Environment

Sandbox, Development (docker)

**Comment by LocoDelAssembly** [comment]
This problem is new, latest release is fine so we don't have Rails 7 setup fully OK @mjy @jlpereira. There is potential fix in https://github.com/SpeciesFileGroup/taxonworks/pull/3965 but there might be other places with problems as well?

**Comment by jlpereira** [comment]
I looked at other places where we use javascript_include_tag and they seem to be fine. We don't have `chartjs` in the Rails assets pipeline, I think that was the issue.

Merged
