### ISSUE TITLE
[Bug]: Task: Browse nomenclature and classification - cannot escape Validation

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#3974]
### Steps to reproduce the bug

```bash
1. from within the Browse nomenclature and classification task for a species
2. click Validation under the eye icon
3. click one of the caution icons to view validations

A window with all validations pops up but you cannot click out or escape from this pop up window. You have to refresh the page.
...
```

### Screenshot

<img width="590" alt="Screenshot 2024-06-13 124054" src="https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/80b04292-5d3e-40e6-9341-497d56cd2aa9">

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/74991451/d824c6f0-6109-4e67-8a83-fecf65d58ffc)

### Expected behavior

I would like to be able to escape this screenshot

### Environment

Production

### Version

v0.41.1

### Browser Used

Chrome Version 125.0.6422.142

**Comment by jlpereira** [comment]
Fixed by https://github.com/SpeciesFileGroup/taxonworks/commit/c886cea427b0e5d89c9a53cfcabc4f63b1955583
