### ISSUE TITLE
Meaning of the legend "Project use: " in Repository panel search results in the Collection Object Filter task.

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#3981]
### Feature or enhancement

When I search for a repository, each possible result has a Project use number associated. 
![image](https://github.com/SpeciesFileGroup/taxonworks/assets/63611746/bb8ee882-4363-47be-a6e5-9e9dc1b281c1)

If I select the one with the  UVCO acronym the results are those 450 in the Project use: number. Also happens with the 52 of MUSENUV. But the ones with the CUVC, UV or the UVAL acronym give 0 results. 

I would really like to understand if that number could also belong to different projects. I do not understand.

### Location

Task - Filter Collection Object

### Your role

Curator

**Comment by debpaul** [comment]
@mabecabrera great question. I wonder if the "0" results could be a need for (re)indexing? @mjy @LocoDelAssembly @jlpereira ?

**Comment by LocoDelAssembly** [comment]
Do you say that those with zero project use return at least one CO @mabecabrera?

**Comment by jlpereira** [comment]
@mabecabrera I'm pushing a change to the way we create these tags from the server.

If the repository is used in the project, the 'uses' count will show the total uses in it. If the repository is not in the project, the count will show the total used in other projects.

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/16530364/c9a679ad-b737-47ac-9f22-de294b998187)

<img alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/16530364/8173a18c-757f-4a70-9801-e3df46471159">
