### ISSUE TITLE
[Bug]: Some hotkeys don't work on Firefox on Linux

### ISSUE THREAD

**Issue by gdower** [SpeciesFileGroup/taxonworks#3988]
### Steps to reproduce the bug

1. On Arch Linux with X11 KDE 6.1.2-1 desktop environment using Firefox 127.0.2 in the [edit nomenclature task](https://sandbox.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=2250744), a lot of the hotkey shortcuts do not work including: alt+d, alt+f, alt+l, alt+n, alt+p, alt+s, alt+b, alt+c
2. Some of these hotkeys are bound to Firefox functions: alt+d highlights the URL in the location bar. alt+f opens the Firefox file menu. alt+s opens the browser history menu. alt+b opens the Firefox bookmark menu. alt-c, alt-l, alt-n, alt-p don't seem to trigger anything in Firefox.
3. Other the other shortcuts like alt+h do work.
4. While writing this bug report, I was momentarily able to trigger both the Firefox and TaxonWorks function calls with some of the above nonfunctioning TW hotkeys but now can't reproduce it. For example, alt+e momentarily both opened the Firefox edit menu and navigated to comprehensive specimen digitization.
5. This might be a Linux Firefox bug and not a TaxonWorks bug.

Possibly there is [a related issue with shortcuts being bound to other functions](
https://github.com/SpeciesFileGroup/taxonworks/issues/1925)?

### Screenshot

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/8573609/e416326d-1490-44ed-8efe-7250f753f827)

### Expected behavior

Ideally if it is possible to override the Firefox hotkeys and bind them to the TaxonWorks functions that might be ideal. At least I don't usually use those alt Firefox keyboard shortcuts. I do use ctrl Firefox shortcuts like ctrl+f, ctrl+l and ctrl+j a lot.

### Environment

Sandbox

### Sandbox Used

sandbox

### Version

bd8bdeb8d

### Browser Used

Arch Linux with KDE 6.1.2-1 using Firefox 127.0.2

**Comment by gdower** [comment]
I also noticed in Firefox that sometimes after triggering an alt shortcut (like alt+o), when hitting the browser back button after triggering the alt+o shortcut, if you click alt again by itself with no other keys pressed it would re-trigger the last called alt+o shortcut. I'm also testing it on Chromium 126.0.6478.126 (Official Build) Arch Linux (64-bit) and it does the same behavior, so maybe it is a TaxonWorks bug.

On Chromium all the shortcuts work except alt+d (highlights URL in location bar), alt+f (opens browser hamburger menu), and these hotkeys all seem to trigger nothing in the browser or TW: alt+l, alt+s, alt+m, alt+c, alt+shift+l. Some of the other shortcuts that do work, sometimes don't work and I'm not sure yet what causes the inconsistent behavior.

Sometimes a bunch of the alt shortcuts stop working until I reload the edit nomenclature page, so it seems to be a conflict between the browser binding shortcuts and TW binding shortcuts.

**Comment by gdower** [comment]
I found that you can do [page-specific Firefox permissions](https://superuser.com/questions/168087/how-to-forbid-keyboard-shortcut-stealing-by-websites-in-firefox) including allowing overriding keyboard shortcuts but most of the shortcuts still don't work and still trigger the Firefox alt menus:

![image](https://github.com/SpeciesFileGroup/taxonworks/assets/8573609/7995d9c6-7c4b-473a-9db6-bbedab0b4852)

I found an actual [workaround that works](https://www.reddit.com/r/firefox/comments/129w85w/is_there_a_way_to_disable_firefox_alt_keyboard/).

In Firefox `about:config` set these keys:
```
ui.key.menuAccessKeyFocuses = false
ui.key.menuAccessKey = 0
```
That fixes all hotkeys except alt+l and alt+e and this likely TW bug still exists:

> I also noticed in Firefox that sometimes after triggering an alt shortcut (like alt+o), when hitting the browser back button after triggering the alt+o shortcut, if you click alt again by itself with no other keys pressed it would re-trigger the last called alt+o shortcut. I'm also testing it on Chromium 126.0.6478.126 (Official Build) Arch Linux (64-bit) and it does the same behavior, so maybe it is a TaxonWorks bug.

**Comment by gdower** [comment]
alt+e works at the species group level. So it's just alt+l (clone taxon name) that doesn't work after disabling the Firefox alt shortcuts.

**Comment by jlpereira** [comment]
I'm going to prevent default behavior for these events

**Comment by jlpereira** [comment]
@gdower pushed changes for New taxon name, let me know if it works.

**Comment by gdower** [comment]
@debpaul helped test this on Windows. The back button alt bug is reproducible on Windows. Almost all of the TW hotkeys work on Windows (except alt+l clone taxon name) but they also almost always also trigger opening the Firefox menus which may discourage use of the hotkeys by Windows users. Although perhaps the solution is to just document the above about:config workaround because the power users that are using hotkeys will probably be comfortable with modifying keys in about:config (unless they routinely use the Firefox alt key shortcuts to access the browser menus).

**Comment by jlpereira** [comment]
Did she test it on local env after pull last commit? or sandbox/production?

**Comment by gdower** [comment]
It was on sandbox

**Comment by jlpereira** [comment]
I was able to replicate it on Windows using FF Development edition , but after last commit it seems to work now.

**Comment by gdower** [comment]
So there's 2 hotkey bugs. 

1) Do you want steps to reproduce the back button alt bug or does what I put above make sense? 
2) After disabling the Firefox alt shortcuts, the only other bug is alt+l not cloning a taxon name.

I'll test the development branch locally.

**Comment by jlpereira** [comment]
I will check alt+l

**Comment by gdower** [comment]
Awesome, you fixed the alt browser back button bug! alt+l doesn't work though.
