### ISSUE TITLE
[Bug]: Wikidata Global Identifers not exported in DWCA export

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#3989]
### Steps to reproduce the bug

```bash
1. When I export COs that have a Person with Wikidata Global Identifier
2. And the export is a DWCA.
3. Then when I open those COs in the DWCA.
4. Then the Wikidata Global Identifiers are missing, but ORCIDs are there (e.g. in recordedByID).
```

### Expected behavior

Should also export in recordedByID

### Environment

Production

### Version

0.42.0

### Browser Used

Firefox

**Comment by mjy** [comment]
@tmcelrath can you do a quick test and resave the CO in question (or post a URL here)?

**Comment by tmcelrath** [comment]
https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=210004
<img width="1236" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/7328d2b4-af76-4000-863f-bbdce017057b">
<img width="1372" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/c52c1fbc-7c01-41c7-8056-0aa0f93bc741">
<img width="1444" alt="image" src="https://github.com/SpeciesFileGroup/taxonworks/assets/11411328/0a2ed0d4-11eb-4497-98ce-40bf5ef10693">

Note nothing in recordedByID
