### ISSUE TITLE
[Bug]: collectionCode and basisOfRecord in DwC Imported dataset not present in DarwinCore output for TW CO

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/taxonworks#3994]
### Steps to reproduce the bug

```bash
1. Using DwC Importer
2. One column is collectionCode (from Darwin Core)
3. This property and its values do not show up in the Darwin Core view of CO in TW.
4.  Same for basisOfRecord
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/93a4953b-7e70-4d6c-be0c-d20006050f73)

### Expected behavior

Upon upload of a dataset that includes the **collectionCode** column, that this term and the values provided would be in the Darwin Core output that one sees in Browse CO.

Work done here by Davide Dal Pos to test the DwC Importer
Where: Sandbox, https://sandbox.taxonworks.org, project = UCF Collection - The Bug Closet
Which DwC Importer dataset? either **Final2** and **Final_parsing**

### Environment

Sandbox

### Sandbox Used

sandbox

### Version

fbfe6cb54

**Comment by LocoDelAssembly** [comment]
Do we actually have a place for that @mjy? The importer is not importing that (although it can as data attribute), however the exporter has no `collectionCode`. The closest thing I now TW supports is looking up identifiers of type `Identifier::Local::CatalogNumber` (hopefully only one of them) and assume that the namespace's short name is the collectionCode (not always the case).

**Comment by debpaul** [comment]
@LocoDelAssembly I guess we could put them in as data attributes? dwc:basisOfRecord (or similar) will be needed as we publish different types of data (field/human observation data, paleo, biological specimens, etc).

**Comment by LocoDelAssembly** [comment]
You may import as data attributes by following https://docs.taxonworks.org/guide/import.html#mappings-to-dwc-predicates (only `<term>` part needs to be in column name). This is a project-wide setting, not something you set up on every import.

**Comment by mjy** [comment]
From @LocoDelAssembly on `collectoinCode`

> No prediction, you have to set it up. The importer offers a list of distinct collectionCode values and you have to manually map the namespace for each one. There is also mappings for institutionCode:collectionCode, which are also manual (this one was the only mapping possible, then Dash added the possibility to map just by collectionCode)
