### ISSUE TITLE
[Bug]: Hotkey not working in CSD

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#3999]
### Steps to reproduce the bug

```bash
In CSD the Save hotkey is not working. I am using Chrome, I am on a PC. When I hit Alt S in CSD, nothing hapens. I am able to save my work by clicking the save button, but the hotkey does not work.
```

### Expected behavior

When I hit alt S on a PC, I expect it to save.

### Environment

Production

### Browser Used

Chrome

**Comment by jlpereira** [comment]
Hello @mmkohler 

I can't replicate this. 
Shortcuts are:

MacOS: `Ctrl + S`
Windows/Linux: `Alt + S`

I tested this on Windows/Chrome and it works for me, can you provide a link to try it? Did you try it in incognito mode? You may have an extension that is interfering with the shortcuts working.

**Comment by mmkohler** [comment]
When I load CSD to put in new specimens I still have this issue. When I load the CSD from the filter, I did not have the issue.

**Comment by jlpereira** [comment]
I still can't replicate it @mmkohler 
Can you try on another computer to make sure the problem is not related to your computer?

**Comment by tmcelrath** [comment]
I have this issue too. It popped up after the update to 0.43.0. At first, it works, but then after working in CSD for awhile (not sure the exact trigger), all hotkeys stop working.

**Comment by tmcelrath** [comment]
When I refresh, hotkeys are working again.

**Comment by tmcelrath** [comment]
For me, after working in the task (editing/saving), suddenly the "control" key starts opening the collecting event in a new window when pressing control by itself. That may be related. I'm in Firefox.

**Comment by jlpereira** [comment]
I'm going to need more specific steps to replicate this, and if you have the exact link where you're trigger this it would be great. 

But the most important are all the steps you're doing to trigger this issue, each click you make, everything you're opening(Including radials)

**Comment by jlpereira** [comment]
> For me, after working in the task (editing/saving), suddenly the "control" key starts opening the collecting event in a new window when pressing control by itself. That may be related. I'm in Firefox.

I see what happens in this case, hotkey manager event can't remove pressed keys from the stack because it's focus a new window. I will change this shortcut to open in the same window
