### ISSUE TITLE
Provide recommendation on sharing Dockerfile or image for Taxonworks

### ISSUE THREAD

**Issue by jstirnaman** [SpeciesFileGroup/taxonworks#4]
I've added a [Dockerfile](https://github.com/jstirnaman/taxonworks/blob/master/Dockerfile) for Taxonworks in my fork and [blogged](https://jstirnaman.wordpress.com/2015/03/13/docker-containers-for-taxonworks-biodiversity-software/) instructions for getting started. I suppose the next step would be to share it as an image repository, similar to https://github.com/sameersbn/docker-redmine. Any recommendations or feedback appreciated. Thanks.

**Comment by mjy** [comment]
Thanks for taking the time to do this and write about it, we had just been talking about Docker in some other contexts so it's amazing to see this now. I think a reasonable approach might be to create SpeciesFileGroup/taxonworks-docker as the image repo?  We could translate your blog to a README there etc. I think if it gains traction in the community we (SFG) would be happy to officially support it. @LocoDelAssembly do you have any thoughts on the matter?

**Comment by dimus** [comment]
great that you started to use Docker guys, one thing that I found -- you
can make container much smaller (so it takes less space an downloads
faster) combine apt-get install and subsequent clean statements under one
RUN command, -- this way you do not create a new image until all is done.
In some cases it changes size from 1 GB to 50MB

like for example
https://github.com/EolDocker/solr/blob/master/Dockerfile

**Comment by mjy** [comment]
@dimus Docker branch is merged into development.  `docker-compose up` should work for development purposes based on my testing. The only outstanding issue on this branch is figuring out the strategy for pushing sfgrp/taxonworks-development to docker hub.

**Comment by mjy** [comment]
See https://github.com/SpeciesFileGroup/install_taxonworks/blob/master/development/docker/README.md
