### ISSUE TITLE
CSD task [Bug]: entering waterBody value, then saving, causes forever buffering

### ISSUE THREAD

**Issue by lvhart2** [SpeciesFileGroup/taxonworks#4000]
### Steps to reproduce the bug

```bash
Submitting on behalf of Theodore Cook
1. When I save a collection object in CSD task, and I have added a value for waterBody (data attribute), it doesn't allow me to save and it buffers forever (TW logo loading).
2. If I refresh the page while buffering, sometimes an incomplete collection object will be saved. For example: without a catalog number, or without biocuration.
3. I am needing to filter and delete these incomplete collection objects.
4. This has been happening for about a week. (Noticed the week of 2024-07-26)
...
```

### Environment

Production

### Version

v0.43.0

### Browser Used

chrome

**Comment by jlpereira** [comment]
Hello @lvhart2 

I can't replicate it. I'm going to need more information about this. Can you provide an example that allows us to replicate it? The exact data you use in the forms to try to replicate the issue. The task saves different objects at the same time, and it could be one of them is failing, in order to investigate this correctly I will need the exact data they are putting in the forms. Also the name of the project and if you have the ID of a collectible that has this problem could also help.

**Comment by tcookplecoptera** [comment]
![Screenshot 2024-08-02 123451](https://github.com/user-attachments/assets/642d77fe-a0c6-46fb-bb35-1c0c8ec6a45a)
![Screenshot 2024-08-02 123555](https://github.com/user-attachments/assets/f72cc278-b551-46bd-a033-d5ade6c2ca51)
![Screenshot 2024-08-02 123610](https://github.com/user-attachments/assets/e481f091-5097-4ddb-90e4-6470f8a42111)
![Screenshot 2024-08-02 123625](https://github.com/user-attachments/assets/13751646-8991-49d9-a066-fad617c7a70b)
![Screenshot 2024-08-02 123648](https://github.com/user-attachments/assets/0e40e318-11f0-4715-9068-b0da286fdee0)

This is an example of the kind of collection object that I am trying to submit. As long as I do not enter anything in the waterbody space, the object saves normally, but if I enter a name under waterBody then press save, the taxonworks "saving changes" logo appears and circles perpetually (it eventually times out). If I refresh the page then go back to find the object that I was working on, I usually find a half-completed entry. 
Another example of a collectible that has this problem would by BYUC 168251. I have not entered a waterbody name for that one. The name of the project is INHS Insect Collection. 

![Screenshot 2024-08-02 123649](https://github.com/user-attachments/assets/bd685de3-3b59-4833-abcd-cd1f90b9f3fe)

**Comment by jlpereira** [comment]
Apparently the bug is present when filling out the data attributes form found in the collection events panel, in collection objects it works fine.

@mjy At the console I see that we have a loop creating delayed jobs
