### ISSUE TITLE
Field Syncronize - when object hasn't used a predicate then it's not available for selection

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#4005]

**Comment by mjy** [comment]
@jlpereira I think the suggestion to add a button with "All" that does a modal popup with the full Predicate list is the way to try implementing this.

**Comment by AntWeb-org** [comment]
Is it possible to allow a replace option to match an empty cell and replace with text? 
In this case I want to add the VerbatimTypeStatus' into blank fields but I think the field synchronize tool is not recognizing the blanks to replace - the replace fields are grayed out.

![image](https://github.com/user-attachments/assets/73fea190-0384-4c83-8c79-7f802a511a15)

**Comment by jlpereira** [comment]
Click on pencil icon in the column header, there you can fill all empty cells

**Comment by AntWeb-org** [comment]
Ah, got it. Thanks
