### ISSUE TITLE
[Bug]: Superspecies Edit Taxon Name Page - Can not drag in the Subsequent Combination panel

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#4009]
### Steps to reproduce the bug

```bash
Superspecies can not drag in subsequent combination.
```

### Environment

Production

### Browser Used

chrome

**Comment by mjy** [comment]
I don't think the drag is live yet.

**Comment by mabecabrera** [comment]
When the drag would be live, will I be able to Create it? Because that button does not turn available yet neither.
