### ISSUE TITLE
Task: Filter CO - increase field synchronize request number

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#4017]
### Feature or enhancement

Attempting to update 162 filtered COs using the field synchronize tool, I receive an error message. See screenshot.
Can the field synchronize tool be modified to handle thousands of COs at a time? We depend upon tools to update data attributes, verbatim fields, etc. in the thousands.

### Location

Task - Filter Collection Objects

### Screenshot, napkin sketch of interface, or conceptual description

![image](https://github.com/user-attachments/assets/1b00e5ce-535d-48f4-afad-0790967eeef4)

**Comment by mjy** [comment]
@jlpereira POST?

**Comment by jlpereira** [comment]
sessionStorage I think, we handle this from the client side
