### ISSUE TITLE
[Bug]: Control button in CSD open collecting event editor

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#4034]
### Steps to reproduce the bug

```bash
1. When I am in CSD
2. And I have a CE selected
3. Then I try to use hotkeys
4. Ctrl key opens the collecting event selected.

On Mac OS X
```

### Expected behavior

Should let me use hotkeys

### Environment

Production

### Version

0.43.3

### Browser Used

Firefox

**Comment by jlpereira** [comment]
@tmcelrath I can't replicate this, could you provide the exactly steps for it? thanks

**Comment by mjy** [comment]
Maybe this was alt- fix related?
