### ISSUE TITLE
Add a "Confidences" block to the New asserted distribution interface

### ISSUE THREAD

**Issue by cicadina1** [SpeciesFileGroup/taxonworks#4044]
### Feature or enhancement

Could you add a "Confidences" block to the New asserted distribution interface. The confidences should concern the asserted distribution not the citation.
If it possible to add also a lock option for the confidence will be great.

### Location

Task - New asserted distribution

### Screenshot, napkin sketch of interface, or conceptual description

![confidence_Distribution](https://github.com/user-attachments/assets/92b92214-c2e7-4f03-a885-e56af3d98877)

**Comment by jlpereira** [comment]
Done, you will see the change on the next release.

**Comment by cicadina1** [comment]
Thank you!
