### ISSUE TITLE
CE Match similar to CO Match

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#4049]
### Feature or enhancement

I would like to be able to match Collecting Events similar to the CO match. At least for starters be able to copy and past batches of CEs to see if they're in the database then perhaps in the future make batch updates to CEs.

### Location

Task - CE Match

**Comment by mjy** [comment]
@AntWeb-org When you say "copy and paste CEs" what format would that text look like?

**Comment by AntWeb-org** [comment]
Copy and paste a list of text such as the following CEs:
ANTC48955
ANTC48956
ANTC48957
ANTC48958
ANTC48960
ANTC48961
ANTC48962
ANTC48963
ANTC48964
ANTC48965
ANTC48966
ANTC48967
ANTC48968
ANTC48969

**Comment by mjy** [comment]
You can do that now by proxy.  Paste them in Filter CO, then navigate to Filter CE.

**Comment by mjy** [comment]
Ah- but maybe those are field numbers, not CatalogNumbers, right?

**Comment by AntWeb-org** [comment]
Yes, they are field numbers/trip identifiers for the CE record.

**Comment by AntWeb-org** [comment]
By the way, where can you copy and paste COs into the CO Filter? I pasted a number of catalog numbers into the Matching Identifiers field and received zero results.
![image](https://github.com/user-attachments/assets/0447a78f-ed9b-42c1-b95d-16a895573be3)

**Comment by AntWeb-org** [comment]
Forget my last comment, I figured it out. The list has to be more like a paragraph with identifiers separated by a comma.

![image](https://github.com/user-attachments/assets/f03aea96-bb28-4636-aaf4-396a9ab624b9)

**Comment by mjy** [comment]
If you want to use one per line you can use `\n` as the delimiter (see the note below).

**Comment by AntWeb-org** [comment]
I tried that before and it didn't seem to work. I am copying and pasting the list of identifiers from a column in excel so the delimiters are paragraph marks.

**Comment by AntWeb-org** [comment]
Again, forget my last comment - I got it :)

**Comment by mjy** [comment]
This presently available on the CE filter, I don't anticipate adding an individual match task, but rather add downstream reports based on the match as needed.
