### ISSUE TITLE
Task - browse nomenclature - year letter

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#405]
Year letter ("1999a") is not shown together with the citation

**Comment by mjy** [comment]
Which citation?  At the bottom or inline in the list?

**Comment by mjy** [comment]
Within the list.

**Comment by proceps** [comment]
in line in the list!

**Comment by mjy** [comment]
<img width="467" alt="Screen Shot 2019-11-21 at 2 33 39 PM" src="https://user-images.githubusercontent.com/22600/69374564-ee768480-0c6b-11ea-92e8-54f255926158.png">

Close?

**Comment by proceps** [comment]
The letter should be part of the citation in the synonymy list (or the author and year should bring a citation or a mouth click or on mouth over). Imaging you you both Ding, 2006a and Ding 2006b in the list of synonyms. There is no way to distinguish those two citations.
List of References looks OK.

**Comment by mjy** [comment]
I think we should then mouse-over or hyperlink or some such.  I really really don't want to perpetuate letters, we should use modern tech to totally get rid of them.
