### ISSUE TITLE
CollectingEvent - rename `verbatim_trip_code` `verbatim_field_number` and do not auto-populate from Identifier fields in DwC import

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#4058]

**Comment by bpescador** [comment]
We have DwC imports ready to import but are waiting for this bug fix. There doesn't seem to be a workaround, so we need to wait.

**Comment by mjy** [comment]
Closing this as done, @LocoDelAssembly if we missed something please re-open.
