### ISSUE TITLE
[Bug]: DwC verbatimEventDate import

### ISSUE THREAD

**Issue by bpescador** [SpeciesFileGroup/taxonworks#4059]
### Steps to reproduce the bug

```bash
1. a Dwc import with verbatimEventDate and EventDate
2. if verbatim and Evendate are in formate YYYY-MM-DD, then verbatim is not imported [field is blank] 
3. If verbatim is in a different format, then it is imported into the verbatim date field. 
...
```

### Environment

Sandbox

### Sandbox Used

Sandwitch

### Browser Used

chrome

**Comment by mjy** [comment]
This is probably intended.  If we can processes it as ISO then we keep as is, if we can't, then we stuff it in verbatim.  The alternative is to error if we can't process.

**Comment by mjy** [comment]
@LocoDelAssembly re-reading this I think this is a bug

> if verbatim and Evendate are in formate YYYY-MM-DD

If verbatim is provided it should always be popuplated.  I will post a spec.
