### ISSUE TITLE
Task CO Filter - Pasting Matching Identifiers; results not in order of paste

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#4065]
### Feature or enhancement

When I paste a number of Matching Identifiers in the CO filter in a specific order, I would expect the results to be in the same order. This would be very helpful to our workflow especially since the identifier order will most likely match physical specimen order in unit trays.

### Location

Task-CO Filter

### Screenshot, napkin sketch of interface, or conceptual description

List of identifiers in order expected:

![image](https://github.com/user-attachments/assets/b86f2be4-2fa6-4535-9db2-5f5b7f0c8ac6)

Results not in identifier paste order:

![image](https://github.com/user-attachments/assets/d40fafea-f43d-42fe-9aab-face13878817)

**Comment by mjy** [comment]
Understood, but we will have to think about this, it's quite hard to do with all other parameters potentially interacting.  @jlpereira we might have to make it a client side option.
