### ISSUE TITLE
Filter Loans: Date fields names are confusing

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#4068]
### Feature or enhancement

![image](https://github.com/user-attachments/assets/b3702be4-33f0-471e-a3f1-b0a4657fe851)

Should delete "With" from these four fields. Otherwise you are searching a field "With Date Received" "Without". Doesn't make sense. 

### Location

Filter Loans

### Your role

Collections manager

**Comment by mjy** [comment]
We generalize in code this across all with/out, so yes there is a little redundancy, but this generalization facilates adding new facets and not having to customize the label for all of them in one-fell swoop.
