### ISSUE TITLE
Request: 'blue box' label from record number

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#4074]
Following on from #4016 (I could not seem to reopen it):

The recordNumber additions are excellent. Thank you! Just one more ask... Could the 'blue box' label be allowed to draw from `Identifier::Local::RecordNumber`. At the moment it will only use `Identifier::Local::CatalogNumber` even if I drag the record number into primary place. As mentioned in the linked issue, being able to to use the record number (in the form of Name+number, e.g. "Smith 2345") as the main 'blue box' label is just so useful for us.

**Comment by mjy** [comment]
Aha, you mean the object tag/label for the specimen?

**Comment by jlpereira** [comment]
<img width="402" alt="image" src="https://github.com/user-attachments/assets/99773d35-4b28-4ce2-ae09-f04bb00f80c7">

@camwebb you mean this?

**Comment by camwebb** [comment]
Yes... sorry was not sure what to call it

**Comment by camwebb** [comment]
Thank you!
