### ISSUE TITLE
[Bug]: Task Dochotomus Keys

### ISSUE THREAD

**Issue by mabecabrera** [SpeciesFileGroup/taxonworks#4076]
### Steps to reproduce the bug

```bash
When editing a Dichotomus key I create depictions for many couplets. If I what to edit the depictions of a couplet, I see the depictions of the previous one, unless I refresh the page.

I expect to see the correct depictions without having to refresh the page.
```

### Screenshot

I want to edit this depictions of the Couplet 1.
![image](https://github.com/user-attachments/assets/d809821b-7e74-44e6-9513-1dc2b58a80d3)

But when I enter to see and edit them, the list only shows me the ones I worked before.
![image](https://github.com/user-attachments/assets/d5136f18-2a1b-431f-818f-b9b89d938d7e)
 

### Environment

Production

### Version

 v0.44.3 

### Browser Used

chrome

**Comment by mabecabrera** [comment]
is it possible to choose also the order of the images? Edit it?

**Comment by mjy** [comment]
@jlpereira If you drag/drop them as we do elsewhere there is a position, I think we have a seperate endpoint to reorder.
