### ISSUE TITLE
[Bug]: Images attached to Coordinate OTUs are not transferring to TaxonPages

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#4091]
### Steps to reproduce the bug

```bash
1. When an image is attached to a coordinate OTU (eg. junior synonym)
2. That image does not appear on Taxon Pages (ie. under the senior synonym)
3. In the example below, the image of Symploce dispar, now synonymized with Episymploce dimorpha, does not appear under Episymploce dimorpha on TaxonPages.
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/f7dfd942-483b-4fe8-9c04-f4f6eec6b2dd)
![image](https://github.com/user-attachments/assets/ee196a0d-2785-4292-a657-4c0a8484ee1f)

### Expected behavior

I expect images on coordinate OTUs to appear on the appropriate TaxonPage.

### Environment

Production

### Version

44.3

### Browser Used

Chrome

**Comment by mjy** [comment]
@jlpereira try to add `&otu_scope[]=coordinate_otus` as well to the params.

**Comment by hhopkins77** [comment]
Thank you!
