### ISSUE TITLE
LepIndex - are the better labels for 'as subject of' and 'as object of'

### ISSUE THREAD

**Issue by AdrianHine** [SpeciesFileGroup/taxonworks#41]
I'm wondering if there are there better descriptors for 'as subject of' and 'as object of'. I think this terminology may be confusing to users of TaxonWorks. I haven't got a suggestion yet but I will have a think and get back to you.

**Comment by mjy** [comment]
Yes, there definitely are.  Those are technical.  In the browse/filter modes we'll be using the actual "english" names spelled out across the relationships, and largely hiding this abstraction.

**Comment by mjy** [comment]
In discussion I think we are planning to leave those labels there for now in the low-level debug view (taxon names->show).  The labels won't appear anywhere else, being replaced with the text description elsewhere, for example in the task "Browse nomenclature", or in the editing interfaces being planned, and documented in InVision (navigate right from https://invis.io/2G5K1Z39M#/199963912_New_Taxon_Name_-_Task_Card_Mockup).  Comment here if you think of a suggestion for the debug view.  Note that you should now see a much more understandable statement describing the relationships in the show view, such that you can largely gloss over those labels.
