### ISSUE TITLE
Task - Unify - I can select the same object on both sides. Remove the right object from the left search results.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#4100]

**Comment by mjy** [comment]
It won't let you unify.  The overhead of catching this across all the smart selectors may not be worth it.

**Comment by proceps** [comment]
When I make a search, I see two identical items. It is a lot of guess work which one to select. It would be nice if one is already selected, the other one is not visible in the list (what we have in the unify people interface).

**Comment by jlpereira** [comment]
We already handle this, smart selectors and autocompletes won't allow you to pick the same option that was selected on the other side, but it wasn't working because a prop misspelling
