### ISSUE TITLE
[Bug]: Loan items with "Loaned On" should be removed/checked

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#4104]
### Steps to reproduce the bug

```bash
1. INHS Insect Collection has objects that have the status "Loaned On"
2. This is calculated from "date"?
3. Cannot be cleared. All INHS collection objects should be cleared of this status. 

E.g. https://sfg.taxonworks.org/loans/3324
```

### Screenshot

![image](https://github.com/user-attachments/assets/3f8a2b21-f7ff-4e90-8835-ecb0fd49168e)

### Environment

Production

### Version

0.45.0

### Browser Used

Firefox

**Comment by jlpereira** [comment]
@tmcelrath you need a `none` status option? that will remove the status. I pushed this change on https://github.com/SpeciesFileGroup/taxonworks/commit/5e1f3bbdd3fa2a32473a49903446a2417ab8a99b

Let me know if that is what you need

**Comment by tmcelrath** [comment]
@mjy this needs to be done backend right? I need a report of all loan items that have "loaned on" status. Cannot currently search for that. If small, I can do/fix this with @jlpereira fix. If 1000s, I would prefer a backend wipe.

**Comment by mjy** [comment]
Set all `Loaned on` to nil in production.
