### ISSUE TITLE
Radial annotator/Citations: duplication of New button

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#4107]
When a new citation is saved (hitting the green button) appears a second blue New button:

![imagen](https://github.com/user-attachments/assets/c17305fd-eaef-4df6-a592-473b0f4bc361)

![imagen](https://github.com/user-attachments/assets/bbe34bbd-399e-4ec7-83a1-c4cf672ea316)

**Comment by jlpereira** [comment]
This has been fixed today
