### ISSUE TITLE
[Bug] cannot create new combination (under ICN)

### ISSUE THREAD

**Issue by camwebb** [SpeciesFileGroup/taxonworks#4127]
Following on from our discussion of #4088 last Friday, this was identified as a bug: the inability to create new combinations under ICN.

[Example](https://sandbox.taxonworks.org/tasks/nomenclature/new_taxon_name?taxon_name_id=2323741#basionym):

 * (Create name _Salix barclayi_  Andersson)
 * Create name _Salix pseudomonticola_ C.R.Ball (OK)
 * Set this name as basionym (OK)
 * Try to create new combination: _Salix barclayi_ var. _pseudomonticola_ (C.R.Ball) Kelso:
    * Drag `Salix pseudomonticola` down to Variety (OK)
    * Set `Salix` as Genes (OK)
    * Try to find `Salix barclayi` to set as Species - the autosearch find nothing, typing "Salix barcl..." or just "barc..." (see pic below; FAIL)

![pseudomonticola_fail](https://github.com/user-attachments/assets/d3323dd4-ce7b-4cef-b935-56fe301c7ffc)

@mjy said this would be fixed in the Sandbox the same day, but it is still not working, so I'm opening this issue. Thanks

**Comment by mjy** [comment]
Thanks for prompting again @camwebb Indeed it got snowed under.

@jlpereira In the Homotypic synonyms bit- We need to update the autocomplete params from 

https://sandbox.taxonworks.org/taxon_names/autocomplete.json?term=barc&type=Protonym&nomenclature_group[]=speciesGroup

to 

https://sandbox.taxonworks.org/taxon_names/autocomplete.json?term=barc&type=Protonym&nomenclature_group[]=SpeciesAndInfraspeciesGroup

where they exist as `speciesGroup`.

**Comment by camwebb** [comment]
@mjy @jlpereira Yay! The process works well now. Thank you.

But... the rendering is still not quite correct. When I created a variety, the name is rendered as: _Salix barclayi_ sp. _pseudomonticola_ (C.R.Ball) Kelso: 'sp.' need to be 'var.' See [here](https://sandbox.taxonworks.org/tasks/nomenclature/browse?taxon_name_id=2323741)

**Comment by proceps** [comment]
I am not sure where you see this. This is browse nomenclature interface:
![image](https://github.com/user-attachments/assets/d972ca40-207b-46a1-8d32-47bba041c154)
