### ISSUE TITLE
Authors like last_name `d'Acier` fail to render

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#4132]
`Coeur d' acier` is the confirmed (known in person) way to spelling it

See also `Passerin d' Entrèves `

**Comment by mjy** [comment]
https://sfg.taxonworks.org/people/209774

**Comment by kleintom** [comment]
See also #3597

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/4132
