### ISSUE TITLE
[Bug]Name endings on species do not autocorrect in the subsequent combination box when form is entered or corrected AFTER subsequent combination has already been entered.

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#4141]
### Steps to reproduce the bug

```bash
1. After a subsequent combination has been entered (with incorrect name ending because form was not indicated)
2. And then a user goes in and indicates or corrects the form
3. The ending on the already entered subsequent combination does not correct in the subsequent combination box. (It does correct in panel on the upper right.)
4. The only way I can find to fix it in the subsequent combination box is to delete and re-enter.
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/aca608c6-770b-40f3-8cf4-2e96ae7f1adf)

Note on this screenshot that the subsequent combination was already entered. I went in and checked the adjective box, which should change the ending on the already entered subsequent combination from nigra to niger. It corrects it in the upper right, but not in the subsequent combination box.

Also note that the "Fix" in this instance does not work, which is correct--it shouldn't work. We do not want a new combination; we want the subsequent combination that was already entered and cited to correct.

### Expected behavior

When a form is indicated for the first time, or corrected, I expect the endings on the species names in any subsequent combinations that are NOT verbatim to autocorrect in the subsequent combination box as well as the upper right panel.

### Environment

Production

### Version

46.1

### Browser Used

Chrome

**Comment by proceps** [comment]
Combination has a verbatim name which needs to be deleted.

**Comment by hhopkins77** [comment]
I checked for that. No verbatim name that I can find.

**Comment by mjy** [comment]
Side note- soft validation messages that reference VerbatimName should reference VerbatimName as a possible issue.

**Comment by hhopkins77** [comment]
I have been just deleting and reentering the subsequent combination to fix this, but I know Matt that you have said we should not be deleting and reentering.

**Comment by proceps** [comment]
You can just delete the verbatim name if this is the case. If the verbatim spelling does not match with current prediction, you will not see a soft-validation message.

**Comment by typophyllum** [comment]
I think already present combinations should not be automatically modified. Authors frequently use combinations with incorrect gender suffixes and these should be cited as such.

**Comment by hhopkins77** [comment]
@typophyllum : Agreed, but I am not talking about that situation, which I believe is handled by the Verbatim field. There has to be a way to correct things that are incorrect simply because the form box wasn't checked upon initial entry. Maybe the only solution is deleting and reentering, and this is not a bug.

**Comment by typophyllum** [comment]
I assume that the already present combinations with wrong gender suffix migrated duly from the old species files.

Of course, such incorrect combinations need to be entered verbatim, and to enter correct combinations the form needs to be selected.

**Comment by mjy** [comment]
Deleteing and re-adding to achieve something is almost certainly not the solution.  If the correct data are in place, through editing, then the result should be correct.

**Comment by proceps** [comment]
The present assumption in TW that the combination was entered correctly to the DB at the first time. The string you see on the screen. If you add adjective status after the combination is already in the DB, the script validates that the combination string is preserved after adjective added. If script detect that the combination will be affected, a verbatim string is added to combination to preserve the correct spelling (assuming it was entered correctly to the system at the first place). If combination was entered incorrectly, please edit combination and delete verbatim string (if not visible, please reload the page).
