### ISSUE TITLE
[Bug]: CSD: change of namespace not updating

### ISSUE THREAD

**Issue by AntWeb-org** [SpeciesFileGroup/taxonworks#4147]
### Steps to reproduce the bug

```bash
1.I am entering a new record in the CSD
2.I added the namespace, identifier (catalog #), repository and preparation
3.I clicked Save then realized that the namespace was incorrect.
Deleting, retyping, saving the namespace did not change the namespace to the correct one. The prompt indicated changes were saved but the namespace did not update. See screenshot of incorrect namespace (IISc) and correct (ANTWEB) both showing.
...
```

### Screenshot

![image](https://github.com/user-attachments/assets/d1b35b32-67dc-420e-931b-19cdeb1c855a)

### Expected behavior

When I update the namespace and click Save or delete and update the namespace and click Save, I expect the change to update.

### Environment

Production

### Version

 build v0.46.1

### Browser Used

Chrome Version 131.0.6778.109

**Comment by mjy** [comment]
I think it did save, if you reload the page it would confirm that?

@jlpereira Probably a trigger to always reload header on save clicks?

**Comment by AntWeb-org** [comment]
Will this be fixed in the next build? It's still reloading back to the incorrect namespace.

**Comment by typophyllum** [comment]
I ran into something possibly related:

Deleting Namespace and Identifier doesn't work. It seems to save, but upon refreshing the data is still there. For example CO "NHMUKimprint II 2087" and "NHMUKHolotype formerly in ZRC Singa" (from incorrect catalog number data in old OSF).

[NHMUKimprint II 2087](https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=1596502)
[NHMUKHolotype formerly in ZRC Singa](https://sfg.taxonworks.org/tasks/collection_objects/browse?collection_object_id=1516625)

**Comment by jlpereira** [comment]
@AntWeb-org It will be fixed on the next release, but for the moment you can try this:

1- Remove identifier
2- Save
3- Refresh
4- Add it again

Other solution could be use the radial annotator

**Comment by AntWeb-org** [comment]
I deleted the record and started over. The identifier (for me anyway) was not the issue but if I have this problem again I will try this. Thanks!

**Comment by typophyllum** [comment]
Radial annotator works in my case too.

**Comment by AntWeb-org** [comment]
Deleting the identifier from here? I'll try that next time - thanks!

![image](https://github.com/user-attachments/assets/3ad886e0-3bdd-49f8-8bbb-ff0e04175bb5)
