### ISSUE TITLE
[Bug]: Authors difficult to order for cloned source

### ISSUE THREAD

**Issue by dhobern** [SpeciesFileGroup/taxonworks#4153]
### Steps to reproduce the bug

```bash
1.Select a source with multiple authors
2.Clone the source
3.Edit the authorship so two of the original authors are included in a different order - e.g. Chen, Simpson & Garcia -> Hunter, Garcia, Simpson & Jones
4.In most cases, the order of the authors will be incorrect when the source is saved. It seems that Garcia and Simpson somehow retain integer positions that are hard to flush
5.I usually have to remove all authors, add at least as many authors, save the source (which seems to set the new set of authors in the contested positions, add all the correct authors in order, save the source, remove the unwanted scaffolding authors and save again

This often happens when I go through all papers in a single issue of a journal in turn. Cloning the papers normally saves much time, but there are often multiple papers in a single issue that involve the same authors.

The fact that sources can't be deleted means that I either need to go through the hoops above or else cannibalise the source by changing the whole thing so it represents something completely unrelated.
...
```

### Expected behavior

If I remove an author from a source and add it back, it should appear as the last in the list.

### Environment

Production

### Version

It's always happened

### Browser Used

Firefox

**Comment by mjy** [comment]
@jlpereira Are we sending `position` with `roles_attributes`?

**Comment by jlpereira** [comment]
@dhobern I can't replicate this. Could you provide the exactly steps to reproduce it? Everything you do using the interface

**Comment by dhobern** [comment]
@jlpereira Here is one that failed for me yesterday. I was entering new species and combinations from this issue of Tinea:

http://publ.moth.jp/tinea/tinea22-5.pdf

In particular these two papers, both including Owada and Wang but in different orders:

Gong, Y. N., M. Owada and M. Wang: The supplement of moths to Guangdong Nanling
National Natural Reserve (1) .................................................................................................................303
Wu, S., W. C. Chang, M. Wang and M. Owada: Monema rubriceps (Matsumura, 1931)
stat. rev., a bona species endemic to Taiwan (Limacodidae) ................................................................307

I created the first here:

https://sfg.taxonworks.org/tasks/sources/new_source?source_id=220969

![image](https://github.com/user-attachments/assets/c3915cb1-f583-4300-a6c3-36db658b545e)

Cloned:

![image](https://github.com/user-attachments/assets/d40d1738-7e21-424a-9aca-cd6a9b5b4905)

Changed title and pages, then deleted the three authors and added the first three for the new paper in the correct order (i.e., Shipher Wu, then Wei-Chun Chang, then Min Wang).

![image](https://github.com/user-attachments/assets/7c757255-07af-4bfc-b173-ed592201c987)

You can see that Min Wang has been inserted before the two other authors in the list below the selection tools.

Added Mamoru Owada - he appears first.

![image](https://github.com/user-attachments/assets/c66bfdd6-411a-47f8-b7b8-db92a7491909)

Click Save - the order is as in the display rather than as I added them.

![image](https://github.com/user-attachments/assets/0aa72830-d98d-4b21-92f4-5556f8f31261)

This is now https://sfg.taxonworks.org/tasks/sources/new_source?source_id=220986 - I'll leave it for your diagnostics but it is a duplicate of https://sfg.taxonworks.org/sources/220970

It sometimes takes a very long time to find a way to get the UI to forget the original author order and offer them in the correct one. I have assumed that each name is tied to an integer position and that I need to force them all to be added to new integer positions by blocking their remembered positions and adding them again. In some cases, no amount of playing around fixes it, so I am forced to overwrite the entire record as something completely different and then start from scratch for what I originally tried to clone.

**Comment by proceps** [comment]
Do you know that you can just drag the authors up and down to change the order? Yes, I think I remember that after clonnign adding a new author add it at the top, not at the bottome. But I just changed the order manually.

**Comment by jlpereira** [comment]
@dhobern I thought the issue was with the dragging function. As @proceps said, you can drag the authors to change the order on the list by pressing your left mouse button and drag the author to a different position. You don't need to remove and add them again

**Comment by dhobern** [comment]
Ah - the UI does not make that clear - there is no visible sign that anything is draggable. Could you add the same up/down arrows you use in the name combination editing tool? I must admit that I would still expect the names to appear in the order I add them. That's what happens in all cases when the authors weren't already there in a different position.

**Comment by jlpereira** [comment]
Sure, we could add a drag icon when you hover the list

**Comment by mjy** [comment]
Hmm- we can make new authors (roles) added to the end if they are not.  I'll look.
