### ISSUE TITLE
[Bug]: Tested Pinpoint and all works well but endpoints of key don't show (?), ie. species names

### ISSUE THREAD

**Issue by hhopkins77** [SpeciesFileGroup/taxonworks#4158]
### Steps to reproduce the bug

```bash
1. As I work through the key
2. When I get to the point that a taxon is identified
3. The name of the taxon does not show.
NB: I didn't know what to put under "Environment". I just picked "Development (native)".
```

### Screenshot

![image](https://github.com/user-attachments/assets/b06c4c31-9a89-4fcd-9b02-e596166e870b)

### Expected behavior

When I get to any endpoint in a key, I expect the name of the identified taxon.

### Environment

Development (native)

### Browser Used

Chrome

**Comment by jlpereira** [comment]
Done
