### ISSUE TITLE
Task - New taxon name - impossible to set as incertae sedis

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#420]
Because relatations are "smart" the limit choices from group to group, so a) you couldn't relate a genus to a family group name, and b) if you could then the "Incertae Sedis" relationship still doesn't show up.

Potential solution: 

* [ ] Create a new section "Misc".  
* [ ] Add a button "Set as Incerate sedis of <current parent name>" Clicking it creates the relatinship necessary and display the outcome, with an undo, as a list item

**Comment by proceps** [comment]
Alternative solution, think of a way to make the relationship always visible. So that you can start with a taxon, or with a relationship.

**Comment by mjy** [comment]
Right now I can't see the relationship at all though- probably we have a bug with the applicability of it in the model.

**Comment by proceps** [comment]
I found a name in the 3i dataset assigned to incertae sedis. And it is properly validated.

**Comment by proceps** [comment]
Potentially the button could be a good solution. The subject is always self, the object is always the parent. If you try to change the parent without removing the relationship, you should get a hard error.

**Comment by mjy** [comment]
@proceps Still an issue?

**Comment by proceps** [comment]
This is impossible to set up, because the related taxon search is restricted to the same rank. And you have to add a relationship to a family group name. The subject of this relationship is always self, and the object is always a parent. We discussed to implement a button next to the parent, to be able to set this relationship.

**Comment by proceps** [comment]
please prioritize

**Comment by mjy** [comment]
Implemented as a button "Set as parent" in relationships.
