### ISSUE TITLE
ctrl shortcuts not working

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#43]
I tried all the shortcuts on this page:
....org/tasks/accessions/breakdown/sqed_depiction/978
On previous pages it would work once - the first time i tried it - but then not again
Mac OSX in Chrome

**Comment by mjy** [comment]
Having a hard time replicating.  What keys were you trying.  Was this on the OCR when you drag drop?  Can you list the steps, something like:

        when I click on X
            and I do Y
               and I click my browsers reload
                   then ctrl-Q doesn't work

**Comment by mjy** [comment]
Our group will be testing extensively very shortly, but would still be good to hear from your team @adeans

**Comment by adeans** [comment]
I got two people in right now - are there specific tasks they should do/try?

**Comment by mjy** [comment]
Not really, this specific issue was just about ctrl-keys failing to work in
the task, I couldn't find a concrete pattern to replicate this.

**Comment by mjy** [comment]
Can't replicate for now, closing.  Reopen if issue can be documented as repeatable.
