### ISSUE TITLE
Add asserted distribution annotation 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#431]
Add geographical annotation to assorted distribution.

When I say that this biological relationship is recorded in this publication from this geographic area.

**Comment by mjy** [comment]
@proceps started working on this conceptually.  Going to take a bit to refactor AssertedDistribution, but I have the direction figured out.

**Comment by mjy** [comment]
Now duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/4025
