### ISSUE TITLE
Tasks - Biological associations - records hidden

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#436]
When I open the biological associations with existing records, I got a list of records hidden in the lower window margin.

**Comment by reptalus** [comment]
@ jlpereira Could you please the relationships visible? thank you

![image](https://user-images.githubusercontent.com/40214162/41439694-110ae208-702c-11e8-80ef-71de0189bc18.png)

**Comment by proceps** [comment]
Either the content should be condensed, or the size of the frame should be increased, or the scroll bar should be active

**Comment by jlpereira** [comment]
Sure, I will take a look at this

**Comment by jlpereira** [comment]
Try now, @reptalus . You should see the scroll now. Let me know if the problem persist

**Comment by proceps** [comment]
looks better
