### ISSUE TITLE
Data - OTU - related data

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#437]
When I see biological relationships in related data for OTU, it shows subject on both sides of the relationships. It should be Subject - Relationship name - Object 
See the screen
![qip shot - screen 071](https://user-images.githubusercontent.com/5597748/41363508-b6ae219a-6ef9-11e8-8988-7d9630dce8f5.png)

**Comment by reptalus** [comment]
Another view of the same above

![image](https://user-images.githubusercontent.com/40214162/41439617-c2b52352-702b-11e8-86ff-739305e12d0e.png)
