### ISSUE TITLE
OTU data page

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#439]
Please add "OTU radial" in the OTU data page

**Comment by proceps** [comment]
@jlpereira could you check this one, this should be easy to fix. OTU page has one radial annotator, it should have two. OTU annotator is missing.
<img width="1440" alt="screen shot 2018-06-15 at 1 36 41 pm" src="https://user-images.githubusercontent.com/5597748/41484306-f255c442-70a1-11e8-9773-66aa710c6fd0.png">

**Comment by jlpereira** [comment]
Its a shared view, not sure if there is a "clean" way to add it in this case, I will look the code

**Comment by proceps** [comment]
It is fine if it is in the Attributes or Annotations section. As long as it is accessible.

**Comment by jlpereira** [comment]
Try now

**Comment by proceps** [comment]
Great!
