### ISSUE TITLE
Radial annotator - Citations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#441]
Radial annotator is missing in the list of citations. See the picture. There is an option to edit citations, but not to see the annotations.
![screen shot 2018-06-14 at 5 35 37 pm 2](https://user-images.githubusercontent.com/5597748/41441766-aec3a652-6ff9-11e8-84f4-1d1b5e5ff815.png)

**Comment by jlpereira** [comment]
Try now

**Comment by proceps** [comment]
looks good. How difficult to implement with the radial annotator a return one step back. I can open annotator, citations, annotator, when I close, I close everything. could it be a button to close the last frame only. Probably a cross doing it, but I can barely see it.

**Comment by proceps** [comment]
@jlpereira That was just a suggestion, you can close the issue.

**Comment by jlpereira** [comment]
Not sure in this case if it would be a good idea to close everything, the user could want close only one annotator

**Comment by proceps** [comment]
Yes, it is exactly what I say. If I click outside of the box or if I click Esc, All annotators are closed simultaneously. There is a X close side, but it is so small and obscured with the background, that I could barely see it. At the moment it is easier for me to click Esc, close all windows and reopen those which I need, than to find the X sign to close an individual window. X sign should be more pronounced.

**Comment by jlpereira** [comment]
Right, but if you click outside it won't close both radial, only if you press Esc both will be close. I could make the X more prominent too

**Comment by proceps** [comment]
That would be great. Thanks.

**Comment by jlpereira** [comment]
Pushed, let me know
