### ISSUE TITLE
Radial annotator - delete buttons.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#442]
When I click a delete button on any element of the radial annotator, it deletes the item (citation, annotation, etc.) without any working. Today, I deleted thing by mistakes. There should be some working. Or may be we should do an option, that the item is marked as deleted, but the red button turns green to reverse the deletion.

**Comment by jlpereira** [comment]
Perhaps it would be better just add a dialog box to confirm the delete. You're okay with that?

**Comment by jlpereira** [comment]
I found the problem why the delete are not working in some cases(tested with citation and tags). Im getting this error: undefined method `reference_count' for nil:NilClass↵↵app/models/observation_matrix_column_item.rb, line 67↵

**Comment by proceps** [comment]
Yes it will work. Hope delete is not a common thing in the database. Yesterday, I clicked delete by mistake (it is close enough to other buttons).

**Comment by jlpereira** [comment]
Now each time you want to delete something, you will have to confirm it

**Comment by proceps** [comment]
Perfect

**Comment by proceps** [comment]
I just deleted a data attribute without a warning

**Comment by proceps** [comment]
same for identifier and citation

**Comment by jlpereira** [comment]
Did you pulled?
<img width="1440" alt="captura de pantalla 2018-06-15 a la s 15 35 07" src="https://user-images.githubusercontent.com/16530364/41484058-bd7229cc-70b1-11e8-9805-ee0436a6abf6.png">

**Comment by proceps** [comment]
This is strange. I pulled, but did not refresh the page, an it looks that it was working using the old code. I do not understand how it is possible. I reloaded the page, and it works now.

**Comment by jlpereira** [comment]
Works okay for me. Check if you pulled the last changes

<img width="1440" alt="captura de pantalla 2018-06-15 a la s 15 36 36" src="https://user-images.githubusercontent.com/16530364/41484113-e7c02210-70b1-11e8-8058-b0ff8ea94f37.png">

**Comment by jlpereira** [comment]
Great :D
