### ISSUE TITLE
CharacterState/Descriptor - add key and document (description) parallels to name

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#443]
As background to a more andvanced rendering/layout system include new fields that represent `name` as it should be seen in 1) keys, and 2) taxon descriptions.

**Comment by mjy** [comment]
@proceps You only need the alternate names for Descriptor?  Not CharacterState?

**Comment by proceps** [comment]
@mjy I need for both. I put two separate issues.

**Comment by mjy** [comment]
Closing, will add new issue for where they appear.
