### ISSUE TITLE
Drag-drop files - catching failures on radial annotator dropzones

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#457]
May need additional confirmatino.

When I add a PDF via the annotator and the PDF already exists, then the record appears to freeze and not successfully load.   

Catch the response and indicate that the image exists, then fade the message(?)

**Comment by jlpereira** [comment]
Can't replicate this. I tried to upload the same pdf several times and works okay.

**Comment by mjy** [comment]
Closing- I believe this was due to the permissions issue in Docker.
