### ISSUE TITLE
tag popup

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#46]
The behaviour should be more or less identical to standard mobile features that allow tags to be linked to data.  The main difference is that we require a definition to be provided, so the user must match a pattern (see below).  Wireframes are at the end of our InVision project https://projects.invisionapp.com/share/2G5K1Z39M#/screens/209978896.

Controller code goes in the tags and keywords controller, almost certainly some tweaks to both tag and keyword model are required, and perhaps the tags concern (to handle global_id as an attribute, if it's not already there).

    if I use tags_helper#new_tag_tag(object) 
       then a link/icon appears in the view
          that link is 
             wrapped in a div
               that has a unique UUID for the dive (js timestamp perhaps), *think* this is necessary for downstream interactions, might be wrong
               that references the object by object#global_id
             optionally styled with a class that indicates that this object already has tags

    when I click that link
       then I get a popup text box,
         with a prompted instruction inside
         or a list of existing tags on that object
         with a undo icon to the right, that aborts *all* actions
       
    when I type some letters
      then those letters get a background color bubble
      then I search through Keywords#name and #definition for a match, via a keywords_controller method
         when I find matches then I display them below the colored bubble
            when I click on a match
                then I display that match in the bubble
                   with an (x) at the end of it for deletion of that keyword
                then I move the cursor to the right of the bubble
                then I inject the hidden fields into object#tags_attributes{} necessary to create a new tag
         when I can not find a match
           then I keep typing
              if I type a phrase like /(keyword\s*)+\s*:\s*some definition for foo\s*,/ (term : definition ,)
                 then I create a new bubble, hiding the definition, shown only when I mouse back over (tooltip style behaviour)
                 then I append hidden fields to create a new keyword AND tag (tags_attributes: [{keywords_attributes: {name: value, definition: value}}, ... ]
                 and I move the cursor for the next keyword

    when I find or "create" a new tag
      then I see a "create" button to the right
        when I click this button
          then an call gets made to save the data
             if it succeeds
                then a message is pulsed inside the text area
                   and the popup is collapsed 
             if it fails
                then a message is pulsed inside the popup
                   and the popup remains open

**Comment by mjy** [comment]
Some of this is now handled with the behavior in tags#new.  The popup/modal version remains to be done.

**Comment by jrflood** [comment]
This issue was subsumed into changes made in overall user interface paradigm by @jlpereira
