### ISSUE TITLE
Tag options in 'Collection object image breakdown'

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#463]
When transcribing in  "Collection object image breakdown" , in the TODO list, items are either white or green. If I make any changes to an item, it changes it to green. I need a third option for partly done or incomplete items. Then I need to be able to tag or mark said items.

**Comment by tmcelrath** [comment]
This is important. Please assign.

**Comment by mjy** [comment]
How should the partially done flag be computed?

**Comment by tmcelrath** [comment]
If no identifier is listed, or no number of specimens is inputted, automatically color yellow. 

In addition, we should have a tag or checkbox that marks as "unfinished" or "flag for review" that turns it yellow, for when someone comes upon an issue that a curator or collections manager needs to solve.
