### ISSUE TITLE
Collection object image breakdown, Namespace

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#464]
‘Collection object image breakdown’ in Taxon works: Some of the images are of spiders that have a Unique identifier that says” INHS Araneae ####”
These are already databased and the images will eventually be linked, but for now, I need a “namespace” label that says: “INHS Araneae”.

**Comment by mjy** [comment]
HI @mmkohler, you can create namespaces as necessary in the data->namespace form.
