### ISSUE TITLE
Task - Nomenclature By Source - List of taxa

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#468]
* Extend the list of taxa (OTUs) to all taxa (OTSu) from the source, including all taxa associated with asserted distribution, biological relationships (both sides, subject and object).

* Next to each taxon add a radio annotator and OTU annotator

* Add a search box for a TaxonName to add new taxon to the list

Endpoints: 
* [x] `source/:id.json`
* [x] `taxon_names/select_options` (smart selector)

* [x] Merge filter/index in controller, add `lib/queries/citation/filter.rb`

The following gives you citations on all the classes you need:
* [x] `citations?citation_object_type=TaxonName&source_id=:id`

To fill the matching Otu, create `/lib/queries/otu/filter.rb`

* [x] `/otus.json?taxon_name_id=123`
* [x] `/otus.json?taxon_name_ids[]=132&taxon_name_ids[]=456`

**Comment by proceps** [comment]
For the first part, could be a new task should be created

**Comment by mjy** [comment]
<img width="1284" alt="screen shot 2018-08-08 at 11 26 13 am" src="https://user-images.githubusercontent.com/22600/43850579-f0edb00c-9afd-11e8-8e86-a625d7bb0dcc.png">

**Comment by mjy** [comment]
Refinements:

* [ ] Change "Nomenclatural source" to "Source"
* [ ] Make Source autocomplete 2x as wide
* [ ] Add spinners(?) to sections while queries being run
* [ ] Make pages box 2x as wide as current
* [ ] Major bonus- Make tables sortable, by value in Pages
* [ ] Bonus - after page update make corresponding row a spinner one exit while PATCH running
* [ ] When I click a Blue OTU radial, and it turns green after I close it, then the OTUs list is not updated (tricky)
