### ISSUE TITLE
Task - otu/character - image matrix

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#479]
A new task is needed to quickly populate the matrix of OTU x characters
* [x] Create a subclass of characters to work with images only (no character states)
* [x] generate a matrix table (characters as headers of the columns, taxa as headers for rows)
* [x] Each cell of the matrix should have a drag-and-drop box to quickly add an image from a folder.
* [x] Image brought to the cell is stored to the database as a depiction for this cell.
* [x] Each cell may have multiple characters (variations). 
* [x] Each image get a radial annotator to add label, citation, etc. Preferably the citation is added automatically if the source is selected as default.

advanced features
* [ ] images could be cropped, rotated and mirrored (minimal editing).
* [x] images could be moved from one cell to another within a row if it was placed into a cell by mistake.
* [ ] images should have. Publick vs. private option, to be able to disable images, but do not remove them from the cell.

**Comment by mjy** [comment]
@proceps Blocker has a specific meaning- see https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/CONTRIBUTING.md

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/48017345-abdf1a00-e0f3-11e8-8fee-8b5232c637b8.png)

**Comment by mjy** [comment]
Landed in development.  Closing this for more specific issues.
