### ISSUE TITLE
Edit OTU - remove taxon_name

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#482]
It is impossible to delete a TaxonName from OTU through the web interface. If I delete the taxon name and click Save button, TaxonName comes back.

**Comment by mjy** [comment]
You must select the `-- None --` option in those autocompletes to clear the field.  Type '--' in that one, then select it. Probably we need a reset button beside them.  If you think so add a new issue.

**Comment by mjy** [comment]
I don't think we can just do clear and save, this is a select.  Just like an html select field you actually have to select a (blank) value.  THe problem arrises when a user partially deletes the text- what then? What about deleting the text then typing the exact text back in again, should user have to select again? 

We didn't have much issue with this in mx when everybody learned the idiosyncracies.  We actually tried the clear too- with timeouts etc. it just didn't work well.  The autocompletes there worked slightly different (maybe we can do this here) and `-- NONE --` was appended to every result (@jlpereira maybe you can do that here for a temporary fix)

**Comment by mjy** [comment]
Closing this, the autocomplete selects work by selecting things, there is a long history of people getting used to this (in TW, and mx, etc.), and the ubiquitous nature of this element is fine.  Adding a button means clutter and space.
