### ISSUE TITLE
Task - Edit Taxon Name - status

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#483]
If I am on the species page and select show me all applicable statuses, "Official List of Specific Names in Zoological Nomenclature" is not available as a valid option, instead 'Official List of Generic Names in Zoological Nomenclature' is provided.
The same for the genus: 'Official List of Generic Names in Zoological Nomenclature' is not a valid option, instead 'Official List of Family Group Names in Zoological Nomenclature' is offered.

In both cases "applicable_ranks" are properly set up in the TaxonNameClassification classes.

**Comment by mjy** [comment]
Status/relatinoships are now scoped to ranks and fixed.
