### ISSUE TITLE
Task - Otu browse

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#484]
1. [x] Task OTU browse not on the list of Tasks in the hub
2. [x] Add a hyperlink to Edit OTU in the Browse OTU task
3. [x] Should Edit OTU return result to Browse OTU page?
4. [x] rename "OTU browse" to "Browse OTU" to be similar with all other tasks
5. [ ] Add search functionality (this is already available in the OTU data page)

**Comment by mjy** [comment]
Browse otu is "Browse taxa".  Changes are on "Page" branch.  Closign to open individual issues in the "Page" project.
