### ISSUE TITLE
Task - Show all (valid) rank X for clade Y

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#494]
As a user I want a report of all the valid names of some rank for some clade.  

Bonus - use species/genus/family group "levels" as ranks.

**Comment by mjy** [comment]
@proceps I think this is handled in Nomenclature stats or filter nomenclature?

**Comment by mjy** [comment]
Yes, is.

**Comment by proceps** [comment]
Yes, I think it is covered.
