### ISSUE TITLE
New user - Password reset

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#495]
When a new user is created and the password reset is unchecked. The newly created user is still required to reset the password.

**Comment by proceps** [comment]
No, when you change the password to an existing user, it works fine. When you create a new user, and the user is next to you, he types the password, and I make sure that the checkbox for resetting password is unchecked. But when the user tries to login first time, he is still propmted to reset the password. It is very consistent and easy to replicate.

**Comment by mjy** [comment]
@TuckerJD I suspect this is just a badly named form param, or permitted param, check that first.
