### ISSUE TITLE
Update API wrapper to GeoLocate to reflect their changes

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#498]
Tulane seems to have moved the geo-locate stuff around a bit:
Old url: [www.museum.tulane.edu/geolocate/web/webgeoreflight.aspx](http://www.museum.tulane.edu/geolocate/web/webgeoreflight.aspx)
New url: [www.geo-locate.org/web/webgeoreflight.aspx](http://www.geo-locate.org/web/webgeoreflight.aspx)

This does not seem to be a simple string substitution.

**Comment by mjy** [comment]
Is there an API documented now?

**Comment by TuckerJD** [comment]
I have not dug any deeper into this than to see the RSpec errors, and see the different url.

**Comment by mjy** [comment]
Looks like their domain is messed up in several ways, broken links etc.  Might have to email them for support, seems like they are in transition.

**Comment by mjy** [comment]
Mmm- not messed up, just a hyperlink to a pdf it appears: http://www.geo-locate.org/files/glcJSON.pdf
