### ISSUE TITLE
OTU Radial - Biological associations

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#503]
In OTU Radial > Biological associations : when I click on the Radial Annotator of a biological relationship and then on Citations, list of References do not show up on the right window.
As an example:
![image](https://user-images.githubusercontent.com/40214162/45230787-9f734800-b28f-11e8-93f4-cd7740d5fd98.png)

**Comment by jlpereira** [comment]
Hi @reptalus 

I tried to replicate this following your steps but i can't. Could check this again and see if you're getting the same error?

**Comment by proceps** [comment]
hi @jlpereira 
does not seams to work.
could you try to open page in the sandstorm:
https://sandstorm.taxonworks.org/tasks/nomenclature/browse?utf8=%E2%9C%93&id=&%5Bid%5D=60152
Click OTU radial. There should be single biological relationship there. When you click on the sector, you open an annotator for this relationship, and see that one citation is listed, but when you click on the sector, nothing shows up. 
When I try to add a new citation, it works, and seams that the citation is added, but if I close and open the annotator for the biological relationship, the citation is not there...

**Comment by proceps** [comment]
@jlpereira This is in 3i project.

**Comment by jlpereira** [comment]
Replicated, but not sure this is a frontend error.

https://sandstorm.taxonworks.org/biological_associations/28139/citations.json

This is the json endpoint, should be sending the citations and it comes as an empty array

**Comment by mjy** [comment]
The endpoint is confirmed broken.  Happened when citations.json endpoint
moved to a filter.  I'll fix ASAP.
