### ISSUE TITLE
Protonym sort failing

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#506]
I think we're just missing a human label for OriginalSection?  Or maybe there is some bad data here?

```
An ActionView::Template::Error occurred in taxon_names#original_combination:

  comparison of TaxonNameRelationship::OriginalCombination::OriginalGenus with TaxonNameRelationship::OriginalCombination::OriginalSection failed
  app/models/protonym.rb:337:in `sort'
```

**Comment by proceps** [comment]
Ok. There is a bug in the system. Not sure if this is related though. OriginalSection applies to the botanical names only (original intention). Then we realized, that botanical names do not use original combination. We removed OriginalSection, etc. from the codes, but files were not deleted. I deleted them and running spec tests now.

**Comment by proceps** [comment]
Problem with NewTaxonName task now. Original combination section is hidden for the botanical name in the species rank. But if I create a new genus in botany, I still have an access to the Original combination (I did not check subspecies or subgenus). And this is a real bug.

**Comment by proceps** [comment]
Second thought, we cannot create a plant basionym without original combination. In fact may be we need original combination for all plant names... But this is an open question. No Original combination for all plant names, or present Original combination, again for all plant names?

**Comment by proceps** [comment]
Display original combination option for all plant names

**Comment by mjy** [comment]
@proceps What about the other codes?

**Comment by proceps** [comment]
Yes, open original combination for all codes.

**Comment by jlpereira** [comment]
Original combination is open for all codes. In the case of botany this could be related with the kind of group. Original Combination its set to work with `'SpeciesGroup` and `GenusGroup`

So, to clear this thing. We need to hide original combination for genus and species group in botany code?

**Comment by mjy** [comment]
No- open for all nomenclature codes.  @proceps Does this mean we're not populating SpeciesGroup and GenusGroup correctly likely?

**Comment by mjy** [comment]
THis is (likely) because some constant is incorrect- can you check?

**Comment by jlpereira** [comment]
@proceps I added SpeciesAndInfraspeciesGroup to the filter. Now original combination should be present there.
