### ISSUE TITLE
Editing Source

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#514]
When I try to edit Source, I have a message "Month is not a valid month"
I did not touch the field, and the value in the field is blank.

**Comment by mjy** [comment]
I can not repeat this.

**Comment by proceps** [comment]
may be related to different branch of the code introduced to Sandstorm. I cannot repeat it now with the same record.

**Comment by mjy** [comment]
Did you put in empty strings in the data maybe, that we didn't catch?

**Comment by proceps** [comment]
no, I do not have date of publication data in my db. I tried to modify the data yesterday, and could not save the record using web interfaces yesterday. I tried the same records today, and it just work...
