### ISSUE TITLE
Task - Citations by source - small enchancements

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#515]
* [x] 1- Taxon name: add author, year and status. Status in parentheses (at lease basic, valid, invalid, protonym, combination)
* [ ] 2- Make page number after the name in the Taxon Names table
* [x] 3- For the source, show the list of authors
* [x] 4- TaxonName, make clickable with a redirect to the browse page. May be two separate buttons to browse and edit
* [x] 5- search taxon field: make longer, as long as source search field
* [x] 6- from browse source, make a direct link to Citations by source
* [x] 7- from Browse nomenclature, make a direct link to Citations by source
* [ ] 8- add links to the New Taxon task and New combination task

**Comment by mjy** [comment]
@proceps some thoughts-

1 - The table is generic, it uses object_tag, so this is request would make us produce a new non-generic response.  We need to discuss possible ramifications.
2 - Disagree- all results should align, especially pages.  We discussed doing a global page sort in another possible view (pivoting titles to columns)
3 - Linked, or?  Aren't they in the citation?  What is purpose?
4 - See 1, we should do it, but it's a fairly major change to make it non-generic.

7 - You mean at the bottom of the list where citations are listed?
8 - Yes, but we should consider a generic navigation mechanism whereby related tasks are linked to automagically (we have something like this for data tabs)

**Comment by proceps** [comment]
most is already fixed
