### ISSUE TITLE
Radial Annotator - display citations throughout

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#521]
When I look at an annotation, then I want see a reference to citations.

Make citatble (add "default source" and source/page subform to these, inline):

* [ ] Protocol
* [x] Confidence
* [x] Data attribute

* [x] In the list of each of the above, add a column "Citations" for these, it contains a count of citations (e.g. '4'), when mouse over you see a tooltip listing all the citations on the object.  

* Besides each item in the tooltip list there is a trash can, user can destroy (not edit) a given citation, which collapses the tooltip.

**Comment by jlpereira** [comment]
It's already done. I think we can close this?
