### ISSUE TITLE
Task - Citation by source - OTUs by match or proxy

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#524]
OTU by proxy does not check the OTU name, only the taxon name. Instead of finding me exact OTU (by unique combination of TaxonName and Name) it gives me long list of OTUs attached to a single TaxonName.

**Comment by jlpereira** [comment]
Just to clarify this. @proceps the long list you refer is displayed in the modal?

**Comment by proceps** [comment]
@jlpereira So we have two lists, the left one is for taxonNames. In that list, we have OTU annotators, and it is done correct. One taxonName may have several OTU, so you get a picker.

On the right list  - we have a list of OTUs. And now we have all individual OTUs listed with their own OTU.ids. But if I click on OTU radial, I still receive a list of OTU, which means that OTU radial does not use OUT.id, instead it is searching for OTU by taxon_name.id. So all items on the right list should go by OTU.id and be mapped one to one, not by taxon_name.id

**Comment by jlpereira** [comment]
Ahhh now I get it.
Pushed @proceps let me know if this fix the problem. I didn't test it

**Comment by proceps** [comment]
@jlpereira did you do it on development? (development branch look the same).

**Comment by jlpereira** [comment]
No, Citation by source branch. But was merged right now in dev, pull and check again. Let me know if you still seeing the same

**Comment by proceps** [comment]
@jlpereira Perfect!
