### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#527]
when I create a new source, regardless if by BibTex or Verbatim, I would like that some Data attributes in the Radial annotator are going to be automatically filled, e.g Authors.

Below and example in Data attributes for a Source already in Taxonworks (fig1) and for a Source I create as new (fig 2). 
Moreover, if i try to add a new data attributes, Authors does not appear in the list
Fig1
![image](https://user-images.githubusercontent.com/40214162/46088470-16567f00-c172-11e8-827c-709bcf7124fb.png)

Fig2
![image](https://user-images.githubusercontent.com/40214162/46088563-400fa600-c172-11e8-91af-56f5fda645af.png)

**Comment by proceps** [comment]
Authors is not a data attribute. It is handled by People and Role. May be some additional interfaces are needed to show all roles for a particular person.

**Comment by reptalus** [comment]
The only thing I suggest is to have the same pattern/possibilities/visualization for similar entry. If some citation have Authors in data attributes and some other do not have it is not coherent.

**Comment by mjy** [comment]
@proceps I agree with @reptalus, it seems you're using a lot fo fairly redundant data attributes.  Could you just use one or two that contain the IDS back to your records, and crosslink that way?
