### ISSUE TITLE
Citations by source- Add new Taxon names

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#528]
when I add new taxon names (10 for example), and then I decide to cancel some of those, then I want to use Otu Radial it is actually linked to a wrong taxon names (apparently that one related to the taxon name was canceled).
See an example below I click on Neoaliturus lituratus OTU  Radial and I got that one from Reptalus panzeri. the same for the others.
The problem disappear only if I reload the page and the order of the taxonn names is refreshed. What about to have an automatic refresh?

![image](https://user-images.githubusercontent.com/40214162/46090273-fcb73680-c175-11e8-925f-2a172d795610.png)

**Comment by proceps** [comment]
Probably related to #525

**Comment by mjy** [comment]
@proceps @reptalus Is this still an issue?

**Comment by proceps** [comment]
probably not, but 100% sure

**Comment by reptalus** [comment]
I'm I did not check, as you know I'm not testing anymore TW in this period. But probably if issue #525 is closed, then also this should be.

**Comment by mjy** [comment]
Appears OK.  Likely resolved with global ids settings.
