### ISSUE TITLE
Citations by source - Cite taxon name

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#529]
In the Cite Taxon name Search Tab, when I spell a taxon name which have valid and non valid name option, I got different suggested results according how much letter I put in the search. This is a problem because I cannot understand which is the valid name and select that one. In this particular case I would like to have the valid name because if I select something else (e.g. combination or whatever) I got empty OTU annotator. 
For example using Anaceratagallia ribauti:
if you search for "Anacera ribauti" you get two identical results: one is valid and one non valid name, so one bring info on OTU aRadial and one Do not.

if you serach for "anacer rib" you get just a result, unfortunately the non valid name

Could you please improve the searching, maybe in a way I can recognize which is the valid name? Plus Could "the searching" behaviiour in the same way regardless how many letters you use?

**Comment by reptalus** [comment]
Moreover, when you add Taxon names would be nice to have in the list something to distinguish valid and non valid name that often look like identical, see in the picture example for Reptalus fidus
![image](https://user-images.githubusercontent.com/40214162/46092416-76512380-c17a-11e8-869a-3aacae92d00f.png)

**Comment by proceps** [comment]
Similar to the case #515.1

**Comment by reptalus** [comment]
@mjy not sure to understand what you are asking me

**Comment by jrflood** [comment]
Covered by issue #515
