### ISSUE TITLE
Confidence level

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#530]
when I open the confidences in Radial annotator and I have the list of citations I would like to be able to click on them to check the details of citations (titles, journal ...). 
![image](https://user-images.githubusercontent.com/40214162/46104163-431d8d00-c198-11e8-8aca-4f5cfbe478b8.png)

**Comment by jlpereira** [comment]
@mjy in place or redirect to `/citations/xxx"` ?

**Comment by mjy** [comment]
In place

**Comment by jlpereira** [comment]
@reptalus let me know if this change is what you looking for or if you prefer something different

**Comment by reptalus** [comment]
@jlpereira this nice! What about now the possibility to click on the citation to open that one on the Citations by source page? If it is possible would be nice because I will have the possibility to add extra info on that specific citation by Citations by source tasks.

**Comment by mjy** [comment]
We might want an icon for citations by source, seems we will use it in
different places.

**Comment by jlpereira** [comment]
Try now @reptalus , the citation icon will works like a button. When you click it another tab will be open with the citation by source task

**Comment by reptalus** [comment]
@jlpereira Perfect!
