### ISSUE TITLE
Taxa browser - asserted distributions matching not showing?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#532]
When I have an asserted distribution, for say "texas", and I draw a big polygon around texas, then it does not return the OTU associated with that OTU. 

@TuckerJD can you look into this.  I could have conceivably broken the filter with my changes to OTU filter.  Note that that code is basically forked into tow methods, I haven't reconciled your result from the new attributes.

**Comment by TuckerJD** [comment]
This issue goes deeper than first imagined: the javascript has to be modified, because it **only** asks for CollectionObjects, although `selection_object` as a parameter is not actually used in the filter. Additionally, It should be possible to find both `CollectionObject`s and `AssertedDistribution`s through named GeographicArea, even though that area may not have a shape.

**Comment by mjy** [comment]
Let's focus on the models/unit tests that let us return the data, then we'll get to the implementation.

You're right with 2 ways of finding things:

* Through the controlled vocabulary/parent-child (geographic_area#id -> children)
* Through the spatial calculations.

Focus on the latter, by default it should resolve most cases because most people will use GAs *with* GIs.

**Comment by TuckerJD** [comment]
While testing this with the user interface, I have found what looks to be a performance issue WRT finding a small number of objects in one project, when another project has a very large population of objects. I am hoping that `project_id` can be accounted for earlier in the query chain. In addition, there seems to be a limit of 65535 items (in this case, `id`)  passable through to the query engine, and I have a (reasonable) example of this failing with no indication at the user interface.

**Comment by mjy** [comment]
@TuckerJD Can we close this?

**Comment by TuckerJD** [comment]
Given that we have not exhausted the ways in which we might search, and that the specific complaint has been resolved, I think so, yes.
