### ISSUE TITLE
Source - Autocomplete tuning?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#533]
The existing autocomplete is fairly sophisticated already:

https://github.com/SpeciesFileGroup/taxonworks/blob/development/lib/queries/source/autocomplete.rb#L160

But we'll leave this open for tuning suggestions.

**Comment by proceps** [comment]
One thing which is missing, If I enter a single word, The search should return me the Source where this word is the first Author, and this source should be at the top.
For example, I search for "Lee", in the results, I get "Lee" as the second or third author, and the sources where Lee is the first author are not even in the list of results.

**Comment by mjy** [comment]
* [ ] prioritize exact matches of first author with single word to top

**Comment by mjy** [comment]
@proceps let me know if the behaviour is better for you, it's a tricky optimization

**Comment by proceps** [comment]
No, The author I am searching not among the first results, I still have results on the top where the author is the second author of the paper.

**Comment by proceps** [comment]
If this is an author, I think it is reasonable. For example, in 3i data, I search for "Knull", but get results for "DeLong & Knull" first, and only after that, I have listing for Knull as a first author.

**Comment by mjy** [comment]
I think we can prioritize by excluding some searches when only one word present.

**Comment by mjy** [comment]
@proceps if you want to see this issue progress please add xspecified spec(s) to spec/lib/queries/source/autocomplete_specs.rb.
