### ISSUE TITLE
Add add an item to pinboard

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#534]
Would it make sense if I add something to pinboard to make it default. In most cases, if I add something to pinboard, is when I want to use it right away in other content. For example, use a source as a default source. Every time I do it, I have to do at least 4 mouth clicks (Add to pinboard, Open pinboard, Mouse over the source, Click to make default, Close pinboard). 
What is the down side if the item is set as default when I add it to the pinboard? I would rather uncheck it as not default if this destructs. 
Alternative solution, make a second button to add to pinboard and make default at the same time.

**Comment by mjy** [comment]
* I don't mind the auto to set to preferred option. 
* I don't like the second buttonoption.

**Comment by jlpereira** [comment]
Now adding new object to pinboard will set as default

**Comment by proceps** [comment]
Thanks
