### ISSUE TITLE
Sandstorm: An ActionView::Template::Error occurred in citations#index:

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#535]
` undefined local variable or method 'predicate' for #<DataAttribute:0x00007f70d883ace8>
Did you mean?  predicate_name
  app/models/data_attribute.rb:56:in 'predicate_name'`

**Comment by TuckerJD** [comment]
`type == 'InternalAttribute' ? predicate.name : import_predicate`
For ImportAttribute, fails what `predicate` is evaluated.

**Comment by mjy** [comment]
OK to close?

**Comment by TuckerJD** [comment]
Fixed in two different ways.
