### ISSUE TITLE
Browse Nomenclature - New Filter for citations

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#539]
I would like to have a new filter where only those citations referring to a particular taxon name, synonym

**Comment by mjy** [comment]
Do you mean only those on a specific protonym, not it's synonyms?  Maybe we can highlight those in the list as being directly linked to that protonym?

**Comment by mjy** [comment]
Sounds good.

**Comment by proceps** [comment]
duplicate
