### ISSUE TITLE
unify existing #download code in module or concern

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#54]
Was Jira TW-388. All the existing download code is nearly identical, make a lib/download library or model/concern and include the download code there.

**Comment by mjy** [comment]
@TuckerJD This is mostly(?) done.  Many existing examples in controllers.  Systematically go through models and remove `.download`, replacing with the shared method you see in controllers like otus.

**Comment by TuckerJD** [comment]
Models which still have their own download method (by any name):
- Serial (#generate_download)

**Comment by mjy** [comment]
Remove them please, follow pattern in OTU controller.
