### ISSUE TITLE
New Combination - type species

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#543]
It allows creating a new combination even if the species is the type of another genus, without sending any warning

**Comment by mjy** [comment]
Not sure I understand, species can be used in combiantion with any genera, regardless of their type status? @proceps does doing this mean we should fire a soft validation warning?

**Comment by proceps** [comment]
This is legal action. People move species from one genus to another (in some cases moving a type species). But creating a new combination, does not change the classification of the species. You still have to go to the taxon and change the parent. I remember we discussed changing a parent according to newly created combination. I do not remember if this was implemented. And yes, the taxon will be flagged with a soft validation warning. I do not know if you see this in the context of a new combination page or not. But this is soft validation. This is still a legal movement. It would be a suggestion that genera should be marked as synonyms.

**Comment by MMCigliano** [comment]
Sure, I was referring to fire a soft validation warning, while saving the new combination. 
I did not know that we still have to go to the taxon and change the parent according to the newly created combination. It does not seem very practical to me.. two steps for the new combination...
Anyway, I just tried changing the parent according to the newly created combination, but the taxon was not flagged with a soft validation warning either.

**Comment by proceps** [comment]
I just tried moving type species from the genus. Both the species and genus get a validation warnings. Those are not pop ups, those do not prevent changes, just warning on the right side of the web page.

**Comment by MMCigliano** [comment]
There are some modifications that I would suggest doing. We can continue discussing this issue personally next week.

**Comment by mjy** [comment]
Believe this is resolved.  Re-open with specifics if not.
