### ISSUE TITLE
Summarize ranges of data by soft validation status

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#553]
Columns are soft validations, rows are say, taxon names.  Show me all the taxon names that need Etymology filled out, for example.

**Comment by mjy** [comment]
* probably need an asynchronous load to keep feeding records one by one

**Comment by proceps** [comment]
If we cache soft_validation. we should be able to browse and filter them.

**Comment by proceps** [comment]
We also may want restrict validation to a particular branch of the tree

**Comment by mjy** [comment]
Do mean 1) dynamically change validation outcomes based on the content
of a clade OR 2) only show validations for a certain clade?

**Comment by proceps** [comment]
I tend to say 2) only show validations for a certain clade. But 1) is also an interesting idea.

**Comment by mjy** [comment]
Duplicate of #72
