### ISSUE TITLE
alphabetical list of localities--page does not exist message

### ISSUE THREAD

**Issue by chdietri** [SpeciesFileGroup/taxonworks#557]
Selecting from the list of letters of the alphabet at the top of the page returns an error, page not found message: https://sandstorm.taxonworks.org/tasks/gis/list#C

**Comment by mjy** [comment]
Looking at what we have here I suspect this task should be redone from scratch, in Vue, with proper endpoints worked up.

**Comment by jrflood** [comment]
Current list of links homogenizes similar, but distinguishable localities, albeit with same coordinates.
Enumeration of empty alphabetic zones seems unnecessary .
Current scoping of result count in lib queries seems to return less relevant results. (in uniquify people)

**Comment by mjy** [comment]
@jrflood let's open a new issue, if you feel its worth pursuing, for uniquify people, keep this one focused on the task listed.

**Comment by mjy** [comment]
@jrflood @TuckerJD seems there is still an error with the tweaks you made. 

Steps to reproduce:

* *Draw* polygon
* Click 'Show' (records return)
* Click 'C'
* Get error 

<img width="1370" alt="screen shot 2018-11-06 at 9 59 16 am" src="https://user-images.githubusercontent.com/22600/48076388-b27c9880-e1aa-11e8-8bd1-a7c925dfe69d.png">

**Comment by jrflood** [comment]
New / different features implemented under #643.
