### ISSUE TITLE
Task - New Source from Citation or Bibtex - Unify authors in people table.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#562]
When list of people created. Match if people with the same name already exists in the database (both by name and alternative value).

**Comment by dshorthouse** [comment]
How do you evaluate "sameness"? If you're dealing with abbreviations in incoming given names and trying to assess a candidate match to an existing record, the scoring logic (albeit culturally insensitive) I use in the dwc_agent gem for the structure of given names (assumes you're comparing the "John" vs. the "John F." parts of "John F. Bain") might help: https://github.com/dshorthouse/dwc_agent/blob/master/lib/dwc_agent/similarity.rb#L17. Likewise, the gem itself for parsing names might also be useful.

**Comment by proceps** [comment]
in this particular case, I am asking about exact match. If there is already "John F. Bain" in the database, do not create a second one with the same name.
