### ISSUE TITLE
Clipboard that keeps the data through different screens

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#570]
When I use the clipboard in the 'Collection object image breakdown (sqed) TODO list'; The clipboard does not keep the data between screens.
I type the info into the Buffered determination box, then I copy and paste that info into the clipboard. 
Then click on Save and next.
When I get to the next label, I open the clipboard, and there is no data there.

**Comment by mjy** [comment]
@mmkohler Can you confirm the browser you are using?

**Comment by mmkohler** [comment]
Hey,
Both my work computer and my laptop  are running Chrome on Windows 7 Professional

Michelle

**Comment by mjy** [comment]
@mmkohler What about the tabs?  You're only doing this in one window, right?

**Comment by mmkohler** [comment]
Yes

**Comment by mjy** [comment]
After testing this appears to be isolated to the master branch.  Closing here, will be fixed when we roll development in.  Updated versions should be on sandbox shortly.
