### ISSUE TITLE
New combination

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#571]
```
when I create a new combination, and I type a genus which contains subgenus also, 
   I get a list of choice on the left with identical name

I would like the subgenus displayed in the option list to be able to discern them.
```
![image](https://user-images.githubusercontent.com/40214162/47114204-cd4d9400-d220-11e8-986d-6bd8e4492014.png)

**Comment by mjy** [comment]
Solution is to provide present rank of name to right of label

**Comment by proceps** [comment]
this is also part of my #496 request. Rank and status are important everywhere we search for the taxonomic name. The same issue we had with Citation by source. 
My solution is retain only one name in the list. After save, all relationships for coordinated taxa like this one are moved to the subgenus taxon name. So, returning two names as a result is only confusing. I think, that one of those two names should be hidden from the proposed result, and by default, the system should lock one possible name.
