### ISSUE TITLE
Model - CommonName - attribute is_accepted

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#582]
Include a boolean.   Curators may want to have many accepted names for a taxon?  Synonym is tracked at the OTU level.

**Comment by proceps** [comment]
Add common name to OTU radial.

**Comment by mjy** [comment]
That is another issue that already exists ;)

**Comment by mjy** [comment]
In thinking about this I think we won't add this attribute, we'll just use Citations to do -> Citations according to X, i.e. accepted by according to some source.
