### ISSUE TITLE
Task - Citations by Source - enchansments

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#584]
* [x] Make taxon name with a hyperlink in bold (like in Browse nomenclature page) 
* [x] move invalid marker after the name 
* [x] - optional. The invalid marker itself have different meaning on the Browse nomenclature page. I would say if you put something like "Name Author, Year - invalid" it would be better. But different marker will work as well
* [x] add "is original" check-box for original citations (in all sections of the page.

**Comment by mjy** [comment]
@proceps As much as it is painful I'd suggest we start moving away from the checklist format for issues, and break out these issues one at a time.  More painful to submit, less painful to manage as we close them?  Will raise the isse on Gitter at some point.

**Comment by jlpereira** [comment]
> Make taxon name with a hyperlink in bold (like in Browse nomenclature page)

@proceps not sure what you mean with this, you want to see the names in bold?

**Comment by proceps** [comment]
@jlpereira Yes, in Browse nomenclature page all TaxonNames are bold (the hyperlink), only the name string (not the author and year) but in the citation by Source name, TaxonName string is not bold. It should be the same formatting in both pages.

**Comment by jlpereira** [comment]
@proceps I don't see the bold there, just italics in some names

**Comment by jlpereira** [comment]
@proceps can you provide an screenshot to clarified this?

**Comment by proceps** [comment]
@jlpereira  It is strange. on the other computer they looked different to me. But when I see them now, it looks the same. Some thing with my vision ;)
Could you please just move the invalid marker after the name? Thank

**Comment by jlpereira** [comment]
Should be already moved
