### ISSUE TITLE
Source cached value.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#585]
Source cached value should include volume(number) not just volume. I understand that is part of the Zootaxa format rendering, but for me, this is missing data, and to see if this is true or not, I have to open sources one by one.

**Comment by mjy** [comment]
Propose an alternative- https://github.com/citation-style-language/styles.
It *MUST* be one of those, we will 100% not be comign up with our own
general format.

**Comment by proceps** [comment]
Non of the zoological or entomological stiles render neither volume(number) or stated_year.

**Comment by mjy** [comment]
Could you check for missing data with some other task or
functionality, in a more systematic manner?
