### ISSUE TITLE
New Taxon Name - Common Status options

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#591]
In New Taxon Name, the status box is showing a few “Common” options that are not the most common (while the most common ones, such as Valid are missing). I would prefer showing Valid or add another tab to customize a list of options

**Comment by proceps** [comment]
@MMCigliano you should not use "Valid" status. All names are valid in the database in default. Valid is reserved for very specific cases. For example. If you have a record in the database "Species 1 is a synonyms of Species 2" But later revision reconfirmes that both species are valid. You do not want to delete the relationship for historical reasons. But, you can put a status "Valid" to species one, and this will override the synonym relationship. But you absolutely should not use this status for all names in the database.

**Comment by MMCigliano** [comment]
Ok, I understand what you are saying. But that was not my point. My issue is referring to the list of options present at the "Common"  tab. 
It is not obvious that all names are valid in the database in default; and the list under "Common" suggests that have to select one to proceed.

**Comment by mjy** [comment]
@MMCigliano Knowning this this issue might just come down to help/training in this interface?  What do you think?

**Comment by MMCigliano** [comment]
I agree that all of these points can be quickly addressed in training. But, the more intuitive the software less time is needed to invest in training 
Re Status: valid - I strongly suggest to indicate that all names are valid by default. You may even include this message in the orange string help 
ok with the other issues

**Comment by mjy** [comment]
As a side note there is a whole field of discussion re simple/intuitive interfaces, we've done a lot of reading on these topics, for example this crossed my desk last night: https://www.interaction-design.org/literature/article/hick-s-law-making-the-choice-easier-for-users

One thing we might ultimately do for TW is to write a (very) short design guide, outlining rules that describe why we do things a certain way.  This may let us address this type of feedback more effectively in the long run.   From a development perspective we have to all be very careful that we do not over-optimize things without major use by multiple users with different perspectives.  All that minute optimization time/energy might be re-focused to adding new core functionality in other areas.

**Comment by proceps** [comment]
"Re Status: valid - I strongly suggest to indicate that all names are valid by default. You may even include this message in the orange string help" 
I agree on this. We should probably include a message in the status section, which disappears if something else is selected.
