### ISSUE TITLE
New Taxon Name - Original Combination

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#592]
In case you enter a new genus this is confusing, since original combinations usually refer to species-group names. Here "rank" or "placement" would perhaps be more appropriate.

Or another alternative: Original Combination (if species name) Original rank (if genus name or above/higher)?

**Comment by mjy** [comment]
I personally think it's the same thing, just a "combination" of two, versus a combination of 4? It's not just rank in the case of the genus, the "parent" could be different, just as in the species case. Keeping the semantics as is also reflects the fact that the data are being stored in the same way, there isn't two different things going on.  What do you think?

**Comment by typophyllum** [comment]
For me this section is not really clear and it took me a while to understand it. Not only the wording "original combination", which I too relate only to species-group names.

Less ambiguous than "Set as current" would perhaps be "Set like entered", i.e. record the newly submitted new-name-parent combination as original. Perhaps even less confusing would be to collapse this section, to be opened by a button saying something like "record original combination/rank/placement different from like entered". Since this would apply mostly to overlooked taxa that meanwhile have changed rank or parent. When adding newly described taxa, the entered parent and rank usually are the original ones.

**Comment by proceps** [comment]
For me setting original combination for every single species and genus is a must. Strictly nomenclaturally, only genus and species count in the combination (new or original). But if we look at catalogues, most of them prefer to report the name exactly as it was published in the original publication. The same with the subgeneric placement. Is it a new combination, nomenclaturally not, but again, most of the catalogues prefer to report it. What is the better word to define all different alternative strings associated with each name? In TaxonWorks they called combinations (original or not original). An the way they are produced in combining several different protonyms into a single string. I am absolutely for better wording, but I do not like "set like entered"... We will always have problem with binomial names, starting with Linnaeus, who combined two entities into a single species name: unique identifier for a taxonomic concept and classification (the genus part of the name). We know that this is bad practice. But we have to work on this. So for every species name in Zoology we have two strings attached to each name (sometimes just one). The original spelling of the name and current spelling of the name.

**Comment by MMCigliano** [comment]
I fully agree that setting original combination for every single species and genus is a must. My comment is mostly related for a better wording when entering a genus name.  So, maybe "Original Combination" can be replaced by "Original Classification" , as explained in the orange help.

**Comment by mjy** [comment]
What kind of words does the ICZN (and other codes) use?  Remember that we
are trying to encode logic here, that ties closely to the concepts
therein.  Does it, and other codes, use classification, or combination?
IMO it's not really a classification, it really is the combination, as it
is the nature of that combination that has nomenclatural consequences, not
the nature of the classification of the name, but maybe we are using the
different words to mean the same thing.

**Comment by proceps** [comment]
I believe it is the most close to the definition of Original Combination in the ICZN sense.
It is also comparable to the Original genus in species file. But it TaxonWorks we establish entire string not just original genus.

**Comment by mjy** [comment]
I like Holger's suggestion of "Original combination and classification"

**Comment by MMCigliano** [comment]
Me too

**Comment by proceps** [comment]
we do not use Combinations for family-group names

**Comment by jlpereira** [comment]
Changed to "Original combination and classification"
