### ISSUE TITLE
New Taxon Name - Synonimize genus

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#593]
New synonym genus level: If genus A is made a synonym of genus B, then all species of genus A need to be moved automatically under genus B and the new combinations be made automatically

**Comment by proceps** [comment]
It could be the behavior. It is already codded in the system, but not tested well. (Probably only as a part of soft validation fix, which we do not trigger using the web interfaces yet). On the other hand, A new combination make sense for me when it is associated with a citation.

**Comment by typophyllum** [comment]
Currently I find it totally confusing.
When I synonymize genus A under B, 
B becomes a synonym, but keeps appearing in the hierarchy below a tribe
And the species of B appear as valid with their original combination, although B is no longer valid and they in fact are now classified as species of genus A.
(Of course ideally a citation using the new combination should be added subsequently to all species formerly associated with genus B, but independent of that they should be moved automatically under genus A).

**Comment by typophyllum** [comment]
Currently I find it totally confusing.
When I synonymize genus A under B,
A becomes a synonym, but keeps appearing in the hierarchy below a tribe
And the species of A appear as valid with their original combination, although A is no longer valid and they in fact are now classified as species of genus B.
(Of course ideally a citation using the new combination should be added subsequently to all species formerly associated with genus A, but independent of that they should be moved automatically under genus B).

**Comment by typophyllum** [comment]
Perhaps I misunderstood Dmitry's response. In the soft validation of the species of the synonymized genus A of course it says: "Parent should be a valid taxon". But these species should really be automatically trasferred to genus B.

Suppose genus A has 20 species.  Here an automatic transfer of these species to genus B would save a lot of work. An automatic transfer would also be indispensable with regard to the robustness of the data, since a valid species should never be under an invalid genus.

**Comment by mjy** [comment]
There is significant difference in opinion as to what to do with children of invalid parents.  To start, we will address this with a new section and option in the New/Edit nomenclature task.

![Screen Shot 2019-05-25 at 8 09 01 AM](https://user-images.githubusercontent.com/22600/58369839-dfce3100-7ec5-11e9-9100-dc516ac3f00a.png)

1 - "Parent mode
* [ ] If a name is invalid, and it has valid children, then a new section appears in New taxon name task, it appears below the Relationships task
* [ ] The section lists all immediate children that are attached to this invalid name.  Get this list by using `/taxon_names` filter setting the parent_id variable
* [ ] User has option to select rows with checkbox one by one
* [ ] User has option to select all rows with a button
* [ ] User has option to deselect all rows with a button
* [ ] No name is moved until user clicks 'Save'
* [ ] When save is clicked a confirmation dialog pops up.
* [ ] !! If more than 10 names are selected the user must additionally type the word "move" to confirm the move.
* [ ] When the names are moved, then they disappear from the list.
* [ ] If all names are moved, then the whole section disappears.
* [ ] The table has an Pen for edit.  If clicked then the user is prompted to confirm they want to move away from this record.  New taxon name task is loaded in the current window.
* [ ] Each row has a radial annotator.
* [ ] BONUS: In the parent column, the parent is not a string, but a autocomplete pre-set to the valid name.  User can select a new parent prior to clicking save.
* [ ] Back end: For now, imply repeat PATCHs, one per name to /taxon_name/123, rows can dissapear on each successful PATCH.  If this become very problematic (big lists of names) we'll write a different function.

![Screen Shot 2019-05-25 at 8 08 48 AM](https://user-images.githubusercontent.com/22600/58369840-e8266c00-7ec5-11e9-9c87-7f71413ae27d.png)

2 - "Child" mode
* [ ] Activated when name has an immediate parent that is invalid
* [ ] Adds a single warning symbol beside the parent. 
* [ ] It has a tooltip that when you hover on it displays a message
* [ ] It has a button that will set the parent to the current valid name for that parent. It does this immediately, without warning.  
* [ ] If the record already has an ID, then the record is auto-saved on click.
* [ ] If the record is not saved, i.e. the parent was just picked, then the parent is just updated in the form, but the form is not saved.

**Comment by MMCigliano** [comment]
I find useful this new implementation that deals with children of invalid parents. 

However, I still cannot understand why it was not possible to move automatically under the valid genus all the species and the new combinations be made automatically?

**Comment by mjy** [comment]
As noted it is possible, it's just not preferred by everybody.  When we
have the time we will implement a project wide setting that makes this
optional.

**Comment by MMCigliano** [comment]
I like the new section, I was just curious which was the need for it.

**Comment by mjy** [comment]
Imaging a synonymy involving 100+ species, some of which will end up
under different genera.  In this case we can selectively move species.
This kind of thing is apparently fairly common in the 3i dataset.

**Comment by MMCigliano** [comment]
Sure, in the case you mention above the new implementation will be very useful. 
thanks for the example

**Comment by jlpereira** [comment]
This implementation it's already done, should be available in next update of Sandcastle. Close?

**Comment by mjy** [comment]
Awesome job, thanks.

**Comment by proceps** [comment]
Section to change parent for species included in the synonimized genus does not pop up any more. Tested on development.

**Comment by proceps** [comment]
It still works on production database

**Comment by jlpereira** [comment]
@proceps steps to replicate? because it works for me in development branch

**Comment by proceps** [comment]
In sandcastle.taxonworks.org, I loged into 3i database. 
In Browse nomenclature, I found the genus Aaka, switched to EditTaxon
Created a new subjective synonym relationship with the subgenus Zygina (Zygina)
Relationship is created, but the section is not visible.
I did the same on development and in sandstorm.taxonworks.org, the section do not show up.
When I tried the same genus Aaka and made it a synonym in Production (same browser, same computer, same taxa). The new section to resolve species names pops up.

**Comment by proceps** [comment]
The problem was reported by Maria Marta, she said, that she could not find this section. So we experimented with different databases.

**Comment by jlpereira** [comment]
I think i found the problem, and its related with some delay retrieving the names. Could you try again and wait a few minutes to see if the section is displayed? Because i found this problem on dev, and could be the same

**Comment by proceps** [comment]
Yes, it pop up in a couple of minutes, but it shows now completely unrelated taxa. Aaka has only one species, and the list now have species and genera from different groups... This is a real problem now...

**Comment by jlpereira** [comment]
The results are different in production? because in this case, something has changed at the backend. We should check this before to update production

**Comment by mjy** [comment]
@proceps  is cached_valid_taxon name_id not being built correctly in production?  @jlpereira are you refreshing the attributes after save of synonym to reload `cached_valid_taxon_name_id` (assuming you need it for the query).

**Comment by jlpereira** [comment]
Yes, the problem persist even if you reload the page.
The endpoint is: `/taxon_names?parent_id[]=<taxonId>`

**Comment by proceps** [comment]
production works correct. And I am also testing in in development against the production database. The data are the same.
Why do we do in by cached_valid_taxon_name_id, not by parent_id. We are changing only parent. Do I miss something?

**Comment by mjy** [comment]
I'm grasping at straws...

**Comment by mjy** [comment]
Where are we at with this one?  Things to check?

**Comment by MMCigliano** [comment]
Quoting Matt <notifications@github.com>:

**Comment by mjy** [comment]
There are still problems with this- the list of children returned is not right.

**Comment by mjy** [comment]
Fixed now, was API param rename issue.
