### ISSUE TITLE
Task - Matrix row coder - condense lines

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#597]
@jlpereira, could you please try to condense the intervals between the characters and states. It is too much on the scrolling on the page.

**Comment by jlpereira** [comment]
Not sure what you mean @proceps , can you provide an image of this?

**Comment by jlpereira** [comment]
Looking the task i think what you mean, but not sure if we could condense it more. I could suggest add a fixed bar at the top like we have in New taxon name to click and scroll it automatically?

**Comment by mjy** [comment]
We might want to plan a CSS swap here? Remember that we can expect a lot of
images etc. to ultimately fill in those rows, with other metadata.  I think
we might want a gmail condensed, medium, lots whitespace mode rather than
messing with the current layout?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/47594281-2663a900-d940-11e8-932c-e85f1ca01f30.png)

**Comment by proceps** [comment]
too much of the white space between characters and states.

**Comment by proceps** [comment]
Even check box and the state sentence are not aligned.

**Comment by jlpereira** [comment]
Need to look this on FF, its weird the checkbox its not inline with the label.

**Comment by jlpereira** [comment]
Anyway, I could reduce the space there, but the radial annotator still taking some space between the states created. Perhaps we gonna need an expand icon there

**Comment by proceps** [comment]
Thanks. I noticed, that radial annotator take some space, but this is minor compared to the rest.

**Comment by mjy** [comment]
I disagree with the whitepace in this basic view.  Remember we wil need to show images inline, etc. etc.  

Regardless- whitespace/alignments etc. aren't top priority here yet.  Focus on the functionality.

**Comment by jlpereira** [comment]
Try now @proceps , the problem with the alignment is fixed now, so some whitespace will be removed. Not much but its something. Let me know

**Comment by proceps** [comment]
@jlpereira Thanks, I will try on Monday, for now I wiped the db from my computer.

**Comment by proceps** [comment]
@jlpereira It is better now. We may want to consider CSS swap in the future, as Matt suggested, but I close the issue for now
