### ISSUE TITLE
Task - Matrix row coder - copy scorings from another otu

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#598]
Add functionality do copy scoring for one otu from another one recently/previously scored.

For example a drop box with the list of all otu in this matrix and a button "Copy scores"

**Comment by mjy** [comment]
@jlpereira We could in theory do this with client side code, but that would be a lot of async code.  Probably better to write a backend `clone` method?

**Comment by proceps** [comment]
Could you please add an option do copy the scores directly to the row scoring page?
So the expected behavior, when I open an OTU for scoring, on the top, I should have a search box and an a button to search for another existing OTU and bring the values dirrectly to the page (the page should reload after the values are added). In this way, I am already in a scope of a recipient OTU, and just need to find a donor OTU.

**Comment by mjy** [comment]
* [ ] make clone endpoint JSON 
* [ ] move functionality to MRC
