### ISSUE TITLE
Task - new source

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#599]
Need a card in the hub for sources/new.

**Comment by mjy** [comment]
Agreed, this needs better description and workflow clarification.  In part we want to filter people *away* from the form on Data->Source->new towards the automatic parsing tasks (citation, and bibtex parse related, integrated with batch bibtex).

**Comment by anadm** [comment]
I know it's not elegant, but I think we definitely need the card for this
form. We may discourage with a disclaimer (e.g. "try to import
automatically" or embed the citation form on top of the screen). Once
people start finding out about the automated ways it will be preferred, but
there will be an assortmnt of cases that will need to be typed in and this
is the best way to prevent imperfect entries.

**Comment by mjy** [comment]
Just to confirm, you have seen the Data -> Source -> New form?  Are you basically wanting to replicate that functionality "officially" as a task?

**Comment by anadm** [comment]
Yes, I've seen it... just feel it is missed as a task as a card. Is it redundant? Yes, but I think most people will be accessing things through the cards and not through Data

**Comment by mjy** [comment]
Closing this for the source hub that was added.  Refiniments can come as individual issues.
