### ISSUE TITLE
Task - individual bibtex source

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#600]
sources/individual_bibtex_source/index
After a reference is parsed, it would be better to be able to touch-up parsed fields before committing/ "create source".
Also, should have a disclaimer remembering people they still have to "create source" after fields are parsed.

**Comment by mjy** [comment]
@anadm thanks! I agree the first issue would be good, but it also makes the task significantly more complicated to implement.  The work around right now is that the user can jump to edit the record via the recently created list- we'll try to make this a one click option/table (right click-> 'Edit').  Not super satisfactory, but not too bad.  We'll leave an issue open with this suggestion.

Will try and address the second issue. @jlpereira See screenshot below.

@anadm Side note- feel free to add multiple individual issues, that makes it a little easier for us to manage in the long run, for example in this case we'll resolve the second, but the first will likely not be a priority for some time.

<img width="1364" alt="screen shot 2018-10-30 at 8 48 54 am" src="https://user-images.githubusercontent.com/22600/47722836-4980a800-dc21-11e8-9ebf-3142a5dbc464.png">

**Comment by anadm** [comment]
Created https://github.com/SpeciesFileGroup/taxonworks/issues/613 for first issue
