### ISSUE TITLE
New taxon name: incorrect original spelling

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#601]
It seems to be impossible to add an "incorrect original spelling".
This month was described Dolichopoda christos-nifoni. I added the emendation Dolichopoda christosnifoni, but when I try to add christos-nifoni, to subsequenly make a relationship to the valid name, a red message appears and I cannot proceed:
"Name must be latinized, no digits or spaces allowed" (here is missing "no hyphen")

**Comment by proceps** [comment]
@mjy we need to find way to access verbatim_name field which is specifically designed for cases like this. As for now, I can enter cases like this only programmaticaly.

**Comment by mjy** [comment]
I think the better solution is to prompt the user to create a name with the Not Latin status.  Harder to implement, but much safer.  We only want to expose verbatim_name if... well, never really.  Way to big a can of worms.

**Comment by mjy** [comment]
@typophyllum First off, thanks very much for using the issue tracker, welcome here!  How does this solution sound:

We add a project level preference that is 'allow creation of non latinized (A-Z) names with auto-added status "Not Latinized"'.  When the project curators have this checked as "on", then creating the name like `aus-bus` is permitted, and the status is automatically applied to it.

**Comment by typophyllum** [comment]
@mjy Thank you, this sounds good. It will probably also cover umlaut signs and other diacritics.

**Comment by mjy** [comment]
Great.  It will take a bit of time to get it done, the preferences are
combing in another branch.

@proceps noted that you can sneak a work around in the present interface.
1) Create the name normally, without the problems.  2) Add the not-latin
status. 3) Edit the name to reflect the original form.

**Comment by proceps** [comment]
Non-latin status is optional now. Incorrect original combination relationship also allow to save a name with diacritical marks and other non standard characters

**Comment by mjy** [comment]
What does "Non-latin" status is optional mean?

**Comment by proceps** [comment]
if you put incorrect original spelling or misspelling, you do not need non-latin status.

**Comment by mjy** [comment]
You mean you can use non-latin characters in TaxonName.name?  If so a) when did this happen and b) change it back.
