### ISSUE TITLE
Task - Edit Matrix - add option to display full matrix

### ISSUE THREAD

**Issue by chdietri** [SpeciesFileGroup/taxonworks#607]
From this interface there should be an option to display the entire matrix as a matrix with all the columns and rows showing the actual data, i.e, with OTU names in the first column and characters in subsequent columns displayed either as natural language state descriptions or labels (state codes). The top row should display a label for each column consisting of the OTU name for the first column and character names for subsequent columns.

**Comment by mjy** [comment]
Thanks MM.   As we start getting more and more feedback on the issue
tracker I'll mention a little point of order- if the comment on the issue
is only to agree with the issue it's best to not add a message, but rather
select the +1 or other emoticon for that message.  Thanks!
