### ISSUE TITLE
Can't use 'destroy' button on Collection Object 'show' page if it has a taxon_determination.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#614]
`PG::ForeignKeyViolation at /collection_objects/913221

ERROR:  update or delete on table "collection_objects" violates foreign key constraint "taxon_determinations_biological_collection_object_id_fkey" on table "taxon_determinations"
DETAIL:  Key (id)=(913221) is still referenced from table "taxon_determinations".`

**Comment by mjy** [comment]
Need to make a decision as to whether to cascade destroy determinations with CO, seems reasonable, just need client warnings? @proceps thoughts?

**Comment by proceps** [comment]
I would delete with a warning.
