### ISSUE TITLE
Task - Browse Nomenclature - Combination edit.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#628]
If in Browse Nomenclature, I select a combination (not Protonym) and click Edit button, I am redirected to a blank page. No edit option is available.

**Comment by mjy** [comment]
Can you replicated this?

**Comment by proceps** [comment]
in sandstorm go to https://sandstorm.taxonworks.org/tasks/nomenclature/browse/91370
Than click Edit button.

**Comment by proceps** [comment]
OK, may be response take too long again (about 20 sec). I though this issue was already resolved...

**Comment by mjy** [comment]
Close #628.  Will open new issue to provide spinner while waiting.
Need to poke around vs. speed issues.
