### ISSUE TITLE
Implement Vue search localities task

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#643]
Continuation of #557. New methods for finding and listing localities.

**Comment by jrflood** [comment]
Geographic Area search (drawn shape TBD) functions as previous.
Autocomplete verbatim locality used to produce list of CollectingEvent IDs whose verbatim locality string matches other collecting events localities.

**Comment by jrflood** [comment]
![screen shot 2018-11-15 at 5 56 49 pm](https://user-images.githubusercontent.com/5349955/48589503-6e536b80-e901-11e8-941d-cf663a95f729.png)

**Comment by mjy** [comment]
@jrflood I think it's important to ask the question *why*.  Why does the user want to search and find localities?  What will they do with them before/after?  What process are they in the middle of.  What functionality does this envision that doesn't exist in the prior form?

**Comment by mjy** [comment]
@jrflood Spamming some tweaks here:

* [ ] Make map maybe 2x as wide as currentea
* [ ] Make the Find button Blue
* [ ] Add a Blue "Now" button beside the second date row, clicking it set the date to Today (see digitize form)
* [ ] Make the result table 100%
* [ ] Add a "Reset" button beside "Find", it clears everything
* [ ] Make the trash can forremove all a button outside the table, i.e. not in the rows
* [ ] Add a "Check all" button beside the above
* [ ] Is the query result scoping to Project events only correctly?

**Comment by jrflood** [comment]
There is a disconnect between the collection event dates section of the tasks/accessions/comprehensive form and some of the other filter date sections (including this one):  the dates are (reasonably) laid out as year month day as numbers.  Do you want to adopt this same layout?

**Comment by mjy** [comment]
In which form are they reasonable?

**Comment by jrflood** [comment]
Compromised, by switching from month dropdownlist to numeric month

**Comment by jrflood** [comment]
All known defects (and a few recently uncovered ones) fixed to this evolution of specification.

**Comment by jrflood** [comment]
Summary of progress to 01APR2019:  Concentration on leaflet map interaction has left certain issues unresolved in overall page functionality, particularly in the area of result list management and visualization. 
Corresponding shapes are removed from the map when collecting events are removed from the list.

What should be the relationship between the list and the map for non-drawn-shape based searches?
What would be required to effect a map display (or addition) from the named geographic area section of the search selector?
Should each of the selectors be able to render either a map or list result?

**Comment by jrflood** [comment]
![Screen Shot 2019-04-03 at 12 35 52 PM](https://user-images.githubusercontent.com/5349955/55500268-953edf80-560d-11e9-8dfd-9a13b7a352fa.png)

**Comment by jrflood** [comment]
To consolidate mapping of other selectors' results, the map will probably have to be refactored into the <collecting-event> component (as was the result list previously)

**Comment by mjy** [comment]
Closing as out of date/redunant with CE filter.
