### ISSUE TITLE
parents of synonyms / display of synonyms in the hierarchy

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#646]
In TW the rationale seems to be that synonym names have the same parent as the corresponding valid names.

Examples:
The name Abilae (synonym of Phaeopariini) appears in the hierarchy directly below Romaleinae (a subfamily with altogether 10 tribes).
Parapoecilimon (as synonym of genus Poecilimon) directly under Barbitistini (a tribe with 22 genera).
Typophyllum lunatum (synonym of species T. mortuifolium) directly under genus Typophyllum.

I find this very confusing for several reasons. First it is strange that a synonym is listed under a valid name with a larger taxonomic scope. Then, if I look in the hierarchy at a particular taxon, I am interested what possible synonyms it encompasses, or looking at the list of species of a genus, to which ones particular invalid names correspond.

I think for the OSF project we need to be able to customize the hierarchy in such a way that the invalid names appear below the corresponding valid ones (and that the status of invalid names is clearly signalized in the hierarchy).

**Comment by mjy** [comment]
@typophyllum  Thanks for your observation. What you see is indeed true, from a data perspective the parent of a name is completely "agnostic", i.e. it's where you'd find the name in the absence of any other data.  For example if I gave you a synonymous name, and you didn't know it was a synonym, where would you put it?

This is critical in that it lets us separate the logic for synonym into the same place, code-wise, as all the other code that describes synonymy, homonymy etc (relationships/status).  So, what were saying is that _data_ wise that's not going to change, the parent will remain as is currently implemented.

What can/will change is the _view in different contexts, as you allude to.  For example we envision a tree browser that would let you toggle between not only the "synonyms under X" view you mention, but also other possible classifications of names.

**Comment by typophyllum** [comment]
Thank you. A more elaborate tree browser sounds good. One of the things I currently miss most in TW, is, when you move to a particuar taxon in the hierarchy, to be able o assess at one glance the taxonomic situation (being also able to spot possible irregularities or errors).

**Comment by mjy** [comment]
@typophylum does the New nomenclature stats task help in this regard?

**Comment by typophyllum** [comment]
No. I was thinking about a hierarchy along which I can move up and down, with the synonyms below the directly corresponding valid names, where I can directly move to a particular taxon and see all information belonging to it. And then move to another taxon, and so on.

Maybe a few screenshot fragments from OSF make it clearer (in the short form display, my custom setting is to display complete titles of the cited references). Here we are at the subfamily Pterochrozinae, see the synonyms of the family-group name, the included genera (the synonyms of the genera), the species, etc. (the number of displayed subordinate ranks is customizable).

![imagen](https://user-images.githubusercontent.com/33210201/66675274-6009ee80-ec3b-11e9-8dea-39266cea2b77.png)

I can move down to a particular genus and see the included species and clearly separated the synonyms:

![imagen](https://user-images.githubusercontent.com/33210201/66675627-1372e300-ec3c-11e9-88c1-feca3e6c53c8.png)

I can move up to the subfamily again, and then further down to another genus, e.g. Typophyllum, with 35 valid species names and 15 synonyms, where ist is really important to see easily which names are valid and which ones are considered synonyms, and which synonym belongs to which valid species.

![imagen](https://user-images.githubusercontent.com/33210201/66676056-0dc9cd00-ec3d-11e9-8adf-4c3b2e1530d6.png)

When I'm at species T. mortuifolium is see only citations referring to this name, and the synonym T. lunatum separately below:

![imagen](https://user-images.githubusercontent.com/33210201/66676202-4d90b480-ec3d-11e9-8cb4-733b668c82a9.png)

When I go to this synonym, only references treating this name are listed, the two most recent ones treating it as synonym of T. mortuifolium:

![imagen](https://user-images.githubusercontent.com/33210201/66676278-7618ae80-ec3d-11e9-8531-771c25e0d80a.png)

And from this synonym I can direcly move up to the valid name again, or directly to the genus, or to the subfamily, and keep exploring the hierarchy. And see at each name the corresponding information.
