### ISSUE TITLE
Task - Edit TaxonName - Etymology does not autosave

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#649]

**Comment by jlpereira** [comment]
Should we do this or discard the autosave idea?

**Comment by proceps** [comment]
I really love autosave on this page

**Comment by jlpereira** [comment]
OK, in a couple of weeks we can add this as a preference. We need to do first a new slide panel for user preferences

**Comment by jlpereira** [comment]
@proceps added checkbox for autosave, disabled by default. Its using sessionStorage, so the preference should be store until you close the tab or browser.

A couple of things: 

1- If the autosave is triggered and you want to stop it, just uncheck the checkbox.
2- It will be trigger for everything that makes a change, and only works if the taxon its already created.
3- Pages still using a silent autosave, but its linked with the same configuration
4- Autosave will be trigger after 5 secs, you will see a green bar at the top to know how much time left before save

I hope the new changes works for everyone
