### ISSUE TITLE
Newly created source

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#654]
* [x] When I created source, I should have a link from the Source page to Citation by Source
* [ ] If I pinned the source, in the Citation by Source page, I should have an option to use pinned source.

**Comment by mjy** [comment]
The first request is available through 'Report'.  I'm not sure we want to customize Data show forms too much.

Working on this:

![Uploading Screen Shot 2019-02-26 at 2.09.59 PM.png…]()

**Comment by jlpereira** [comment]
The source needs to be set as default at pinboard panel
