### ISSUE TITLE
Task - Browse nomenclature - order

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#656]
If Protonym and Relationship comming from the same source, taxon name should be listed before the relationship.

**Comment by mjy** [comment]
Screenshot example with annotation?

**Comment by proceps** [comment]
need some time to find one example again.

**Comment by mjy** [comment]
Ping

**Comment by proceps** [comment]
TaxonID: 373983 in 3i database.

![image](https://user-images.githubusercontent.com/5597748/78458369-5a371800-7676-11ea-8cd4-be29996a1dd6.png)

The same will apply to synonyms
