### ISSUE TITLE
Task - Radial annotator - confidence level is not editable.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#657]
I tried it from New Taxon task

**Comment by mjy** [comment]
I think we specifically did this, edit is just as hard as destroying and adding a new one, not?  Since it's 1:many.  Don't think we need it here.

**Comment by proceps** [comment]
I cannot create a new one. I have a blank form without any option to create.

**Comment by proceps** [comment]
levels are created on migration. I can see levels for those taxa which come from the migration. But only with a single option, to delete the level

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/48749965-b1d01180-ec42-11e8-9c0f-bc4b01f8babd.png)

**Comment by mjy** [comment]
You only have one confidence level created, 'Verfified'.  You need to create other confidence levels first before you add new ones.  Create a new confidence level in CVTs, and you'll see how it works.  This is the intended/fixed behaviour, we should not edit existing assertions with a single data point.

**Comment by proceps** [comment]
Does non have much sense to me. But added new confidence level. Behavior still the same
![image](https://user-images.githubusercontent.com/5597748/48778460-d6f06e80-ec9a-11e8-8957-8b30a9cd3be2.png)

**Comment by jlpereira** [comment]
The confidence levels could be created directly from there, if you don't found what you're looking for with the autocomplete, just write the name there for the confidence level and fill the texture with a definition.

This will create a new one.

Anyone, the intention is add an edit option here?

**Comment by mjy** [comment]
No edit option, makes no sense.  There is something broken in @proceps
browser, he can't see create new, or the modal popup.

**Comment by jlpereira** [comment]
Right, I saw it now in the screenshot.

@proceps could you check the browser console to see if you're getting an error?

**Comment by proceps** [comment]
It works in sandstorm (same computer, same browser) for me and in development, but not in the production. See picture above. It is just blank.

**Comment by proceps** [comment]
application-9281aada1c1be918f55fbd3ab339f89abc971eaf21a9d601ccfb9144050f30e9.js:43 The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.
i @ application-9281aada1c1be918f55fbd3ab339f89abc971eaf21a9d601ccfb9144050f30e9.js:43

**Comment by jlpereira** [comment]
Those lines shouldn't be a problem, its related with the pdf library.

The console is not showing another error when you open the confidence slice?

**Comment by proceps** [comment]
Not any more, it seams like some random error which disappeared after page reload. But Confidences are still blank. Could it be some CSS overlap. In Firefox it looks little bit different
![image](https://user-images.githubusercontent.com/5597748/48801081-0fab3a80-ecd1-11e8-9e9c-761a60bd2fa8.png)

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/48801695-a7f5ef00-ecd2-11e8-9d1b-3f8b49f141cf.png)

**Comment by jlpereira** [comment]
I gonna need access to your project to use the vue debugger tool

**Comment by proceps** [comment]
you are a project member of 3i database on sfg.taxonworks.org

**Comment by jlpereira** [comment]
for some reason im not receiving the email to reset my password

**Comment by proceps** [comment]
could you verify email I should use?

**Comment by jlpereira** [comment]
jlpereira@speedy.com.ar

**Comment by proceps** [comment]
I have it, you probably just need to do a password reset. Not sure why there is no notification

**Comment by jlpereira** [comment]
Now works, looking

**Comment by jlpereira** [comment]
I think I found the problem

https://sfg.taxonworks.org/confidence_levels/select_options?klass=TaxonName

The request is pending and never finish. This call should be returning the result to populate the smart selector. @mjy any idea what could be happen to get this behavior?

**Comment by jlpereira** [comment]
After a long time, finished showing this message:

> Error 503 Backend fetch failed
> Backend fetch failed
> 
> Guru Meditation:
> XID: 2032165
> 
> Varnish cache server

**Comment by mjy** [comment]
This may be a kubernetes issue, or actually a screwed up query.  Pinging @dimus.  Will poke at query.

**Comment by mjy** [comment]
@proceps Is working for me, can you confirm?

**Comment by proceps** [comment]
It works. Thanks
