### ISSUE TITLE
Task - Edit taxon Name - hyperlink to browse nomenclature

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#659]
Do not redirect to a new window. replace with a regular hyperlink

**Comment by mjy** [comment]
Ctrl-T toggles between tasks very nicely.

**Comment by proceps** [comment]
Hyperlink already exist (top right corner of the page), just remove the redirect to the new tab, and open Browse page in the same tab.

**Comment by mjy** [comment]
I think that's what he did.

**Comment by jlpereira** [comment]
Yes, already done it. Closing
