### ISSUE TITLE
Task - Edit TaxonName - Combination section is required

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#666]
It is impractical doing nomenclature changes with present interfaces. I have constantly jump between browse nomenclature, edit nomenclature. Edit new combination. Ending up with too many tabs open on the browser window. To simplify editing, I propose:
1. Add new section: List of TaxonName Combination.
2. The interface should be similar to add Original combination with multiple fields.
3. Drag existing taxon to the proper level and fill other ranks as needed
4. Once combination is created it is added to the bottom of the section generating a list of historical combinations.
5. Each combination have a radio annotator and a delete button (which became inactive after several citations are added.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/48749935-9cf37e00-ec42-11e8-8352-2bc8624bc7fb.png)

**Comment by mjy** [comment]
Are you using the hotkeys to navigate between edit and browse?

**Comment by proceps** [comment]
it is impractical. Loading page takes time. I often have to go back and force to compare. If there is more than one protonym, I have too many combinations to review. I want to be always in scope of one particular protonym. Browse on the other hand give very good overview of the entire history. It is useful but not in term of editing.

**Comment by mjy** [comment]
Hmm- we might need to use websockets to live update pages across the 3
edits, i.e. eliminate page reloads.

**Comment by proceps** [comment]
Please prioritize, this will also fix #748
