### ISSUE TITLE
Task - Edit TaxonName - basic information

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#668]
When I enter name and parent, calculating the rank takes about 3-5 second. It is unacceptable delay.

**Comment by mjy** [comment]
I haven't seen it either.  Might be turbolinks stacking up between his multiple pages etc.?

**Comment by proceps** [comment]
could it be related to amount of data in the DB?

**Comment by mjy** [comment]
It should be- it's post selection, so there isn't any querying going on.

**Comment by mjy** [comment]
Closing this.  Re-open with specifics to reproduce if it exists.
