### ISSUE TITLE
Task - type material - type

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#670]
for the type (holotype, paratype) replace drop-down with a radio button. It will be faster selection.

**Comment by jlpereira** [comment]
You mean the task "New type specimen", right?

**Comment by proceps** [comment]
I think it is. When you on the Edit TaxonName page, there is a hyperlink to add type specimen. It opens a new page. Also, when a type specimen is created, there is no indication on Edit TaxonName page. At least it should show that there is Holotype record or something like that. May be the holotype and repository. But there should be also a separate issue on that in GitHub.
