### ISSUE TITLE
Task - Edit taxon name - relationship or status deletion

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#675]
Relationship and status are deleted without warning

**Comment by mjy** [comment]
@proceps THis is almost worthless to us as is.  Please try to add steps to replicate.

**Comment by proceps** [comment]
In the Edit TaxonName page, you create a new relationship, you may even put citations on it, but once you click delete button (next to the relationship name). The relationship just disappears without any working. The same with the status.
![image](https://user-images.githubusercontent.com/5597748/48798152-96f4b000-ecc9-11e8-8ed5-77dba294c861.png)

**Comment by jlpereira** [comment]
This should be already fixed now.

**Comment by proceps** [comment]
@jlpereira thanks. it works
