### ISSUE TITLE
Task - Edit TaxonName - relationship and status, edit hyperlink

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#676]
On the relationship and status, I need direct hyperlink to edit page of each of them Data > TanonNameRelationship > Edit and Data >TaxonNameClassification > Edit

**Comment by proceps** [comment]
As an idea on Browse TaxonName and Edit TaxonName task add an edit icon to each line. For the Browse nomenclature, eliminate synonym pages (they are confusing for most of the users).
Steps to implement:
* [ ] Edit TaxonName page, add an edit icon next to each relationship.
* [ ] Edit TaxonName page, add an edit icon next to each status
* [ ] Edit TaxonName page, add an edit icon to each Type species or Type genus relationship
* [ ] Browse TaxonName page, add edit button to each line
* [ ] Browse TaxonName page, add OTU radial button to each line (tricky, there could be multiple OTUs)
* [ ] Browse TaxonName, if the TaxonName is invalid, redirect to the page with a valid TaxonName

**Comment by mjy** [comment]
Closing.  Opened #913 to finish this out.  

The invalid/valid options are described in other issues.
