### ISSUE TITLE
tasks/gis/match_georeference Collecting Events filter search on identifier does not return any results

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#678]
Entering a known Collecting Event identifier (either partially or exactly) does not result in any found collecting_events.  [This appears to have been a known issue omitted originally]
Tags autocomplete doesn't work either.

**Comment by mjy** [comment]
@jrflood Is this still an issue?

**Comment by jrflood** [comment]
This is fixed, as also obliquely confirmed by Marilyn.
