### ISSUE TITLE
Task - Edit TaxonName - alphabetize part of speech

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#682]
for species alphabetize parts of speech. At the moment for different taxa they show in different order.

**Comment by mjy** [comment]
Screenshot?  Same as the prior masculine/feminine issue?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/49027209-4cf64900-f165-11e8-86a1-815fcc609656.png)

**Comment by typophyllum** [comment]
Maybe combine "Participle" and "Adjectibve" to  "Adjective or participle", since the two cases are often difficult to distinguish.
