### ISSUE TITLE
Task - New combination - distinguish valid and invalid taxa.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#683]
When I create new combination, I cannot distinguish valid taxa from invalid.
![image](https://user-images.githubusercontent.com/5597748/49027111-115b7f00-f165-11e8-84f4-aa5e0dd5e797.png)
In this example, one of the generic names is nomen nudum, but I cannot find out which one from the list. The status of the taxon is needed.

**Comment by mjy** [comment]
Wherever we show a list we need an indicator (perhaps the triangle alert).

<img width="1241" alt="Screen Shot 2019-04-18 at 10 06 07 AM" src="https://user-images.githubusercontent.com/22600/56370870-a23d0080-61c1-11e9-8b21-80413ac8171b.png">
