### ISSUE TITLE
Color semantics for nomenclature

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#685]
We have multiple requests for highlighting valid, invalid, etc. names in many places.  I propose we come up with a semantic color palette based off of statuses in NOMEN.

I.e.:
```
When I am browsing nomenclature
   then I would like to see some highlights on my data
        these would help me more quickly understand their semantics
```

@proceps Can you sugget a per NOMEN class set of colors in this issue?  Remember that we want to stay away from Green, Red, Blue as we have them since these indicate actionable buttons/links that have a specific purpose.  

See also #85.  @jlpereira at some point we need a unified CSS sheet or SASS rules that we can start poking at.  

Blocks #683

**Comment by anadm** [comment]
keep in mind not everyone pays attention to color semantics or uses NOMEN. An icon like an exclamation mark, or more informative something like a square with [n.n.] (and so on for different cases of problem names) would be a stronger visual cue. 
![image](https://user-images.githubusercontent.com/1326839/49173048-c048b800-f329-11e8-9055-87e4d158768f.png)

**Comment by mjy** [comment]
@anadm if you use TaxonWorks then you use NOMEN, you just don't know it ;).  This is not to replace other options, it's to enhance.

We have the new `.feedback` classes that can be used now, at least as a baseis.

**Comment by proceps** [comment]
I think we mostly implemented this using "X", "C", "V" indicators.
