### ISSUE TITLE
Edit matrix - Matrix row coder

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#686]
It should possible to modify the order of the characters as appear in the list

![image](https://user-images.githubusercontent.com/40214162/49057938-662fe180-f1c7-11e8-8795-14c92bde4bf3.png)

**Comment by proceps** [comment]
it seams that you can change the order of characters in the Edit matrix interface (simply drag and drop the character), but it does not change the order of the characters in the Matrix Row Coder

**Comment by mjy** [comment]
Should be an easy fix, likely just not sorting by positoin in the matrix
coder.

**Comment by reptalus** [comment]
Has been the issue fixed? I still cannot see changes

**Comment by mjy** [comment]
Fixed means fixed in the code base, not necessarily live :)
