### ISSUE TITLE
Data: image preview broken

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#691]
When I go to data> images> list and select an image, I get 3 urls. The one for web medium leads nowhere.
The preview is broken, and the thumbnail is really too small.

![image](https://user-images.githubusercontent.com/1326839/49174880-757d6f00-f32e-11e8-8fd5-ba9e760dca78.png)

**Comment by mjy** [comment]
There are a series of thumbnails and mediums that we need to regenerate, a known issue.

**Comment by anadm** [comment]
Thanks... I'd expect the following, though:
![image](https://user-images.githubusercontent.com/1326839/49222839-271aaf80-f3c4-11e8-8da2-86da37774163.png)
- in (1) I assume (**) is a web version, ie a jpg generated from a larger JPG or TIFF. That seems to be broken
- in (1) I assume (*) is the web thumbnail that should be loading in the popup, and also being displayed in (3). Something is wrong, because the thumbnail in (3) is being displayed fine
