### ISSUE TITLE
Task - Matrix Row coder - position changes after a state was selected

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#694]
Reported by C. Dietrich.
When you use your mouse and click a check box to select a character state, you see the indicator like changing from red to green and indicating that the state was saved. After the line changes the color, there is slight shift of the position of the check boxes (they shift down little bit). And if you do quick selection of state after state, there is always a chance that you select a wrong one (because all check boxes get shifted. The form should not shift the position of check boxes after save.
![image](https://user-images.githubusercontent.com/5597748/49251887-2e53b480-f3e8-11e8-8969-94a458b116d9.png)

**Comment by mjy** [comment]
@proceps Can you confirm the browsers being used?

**Comment by proceps** [comment]
Chris is using Firefox (I believe), I am using Chrome

**Comment by jlpereira** [comment]
I can't replicate this, no order is changed after create or remove states

**Comment by proceps** [comment]
Click a checkbox to select a character state and keep the mouse on in not moving. After save, the checkbox moves little bit.

**Comment by mjy** [comment]
@proceps fixed on dev, can you confirm?
