### ISSUE TITLE
Source -> New - syncronizing of serials after an update doesn't clear verbatim

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#696]
When I have saved a source with a picked serial, then the title is copied to verbatim.  When I pick a new serial, then the serial is set, but the verbatim remains.  Verbatim trumps serial, so my source is rendered incorrectly.

Probably we should get rid of the verbatim, or, more likely decouple it from syncronization.  Suggestions?

**Comment by proceps** [comment]
I do not think it is an issue. Both journal filed and book title field can replace serial. This is the way styles work. Depanding on the BibTex type, the rendering behaviour is slightly different. There is some interference only when the "Book" is rendered. I would prefer to keep as many fields as possible, and let the style to render cached.
