### ISSUE TITLE
Task - new taxon name - number of letters

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#704]
When I try to add a new name, I go to basic information and as I enter the first character of the name, TW starts searching for identical names. 
When I enter 2 characters, it still searches, but does not let me add a name.
The "create" button is only available after the 3rd character is input. However, ICZN says

> 11.9.1. A species-group name must be a word of two or more letters, or a compound word (see Article 11.9.5), (...)

Meaning it is possible (although not recommendable if I got this correctly) that names have 2 characters. 
This also applies to genus: 

> 11.8. Genus-group names. A genus-group name (see also Article 10.3) must be a word of two or more letters and must be, or be treated as, a noun in the nominative singular.

i.e. I wouldn't be able to create genus [Aa ](https://species.wikimedia.org/wiki/Aa_(ICZN)) if I had to.

**Comment by mjy** [comment]
@jlpereira Can you fix this?

**Comment by proceps** [comment]
We have the same problem with the original combination fields

**Comment by proceps** [comment]
same with the relationships...
