### ISSUE TITLE
Task - Edit descriptor - long short name prevents update button from unlocking

### ISSUE THREAD

**Issue by reptalus** [SpeciesFileGroup/taxonworks#709]
I try to modify the name of the character but the "update" button does not turn on green when I should update it, and the modification fails. Could you please check it?

![image](https://user-images.githubusercontent.com/40214162/49519325-5a4abc00-f866-11e8-8c4c-239a9fd73dce.png)

**Comment by mjy** [comment]
Confirmed on production, can not replicate in development currently.

**Comment by mjy** [comment]
I see the problem.  @jlpereira we should not lock the update button when Short name is too long, just show the message.  @reptalus we should have this fixed and live this AM.
