### ISSUE TITLE
Task - TaxonName - alphabetize statuses

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#712]
Statuses and Relationships need to be alphabetized. They pop up in different order:
![image](https://user-images.githubusercontent.com/5597748/49597484-2644c900-f942-11e8-9079-e117316c54e9.png)
![image](https://user-images.githubusercontent.com/5597748/49599879-9d309080-f947-11e8-9d4b-8b534cabe215.png)

**Comment by mjy** [comment]
@jlpereira I think this is going to have to be done client side, not sure how.

**Comment by jlpereira** [comment]
I will look how the response come, but I'm pretty sure we can sort the list from the client side

**Comment by jlpereira** [comment]
This should be fixed now, can you confirm @proceps ?

**Comment by proceps** [comment]
I is hard to replicate. I close it for now.

**Comment by proceps** [comment]
Still problem, TaxonNameRelationships show up in different order

**Comment by jlpereira** [comment]
I think this was related with the issue #962 . Now displaying all the classes in all levels the order should be OK.
Closing
