### ISSUE TITLE
Data - New Source - Duplicate people

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#714]
If I create a new source manually. And add two people associated with source as authors (may be the same behavior for editors as well). One of those people is an existing person found in the DB, and another one is created as new. The New people records are created for both of them, so that the first Person is getting duplicated.
Only one new person should be created.

**Comment by mjy** [comment]
@jlpereira A bit of a priority here.  We need to check and see that we're not sending along the one set of nested params for selected authors.

**Comment by proceps** [comment]
I did it again, the page saves without warning or anything. I do not know if this is the only source, I just occasionally find that there are duplicate people appear in the system. Only today, I was able to replicate this with two people added to the source.

**Comment by mjy** [comment]
Closing until exact steps can be replicated.  There are some new cleanups that might have helped.
