### ISSUE TITLE
Task - unify people

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#717]
After I unified people, the authors get disappeared from the source authors!!! At this point I do not even know, how many sources got affected. I just noticed with the new source I created, two authors was duplicated, because of the #714. After I merged people, Authors was not there. Are there any tests in the TW? how about TaxonName authors?

**Comment by proceps** [comment]
I checked some of the previous sources, authors are missing as well!

**Comment by proceps** [comment]
I checked, same with TaxonNames... Authors disappear

**Comment by mjy** [comment]
There are tests IIRC.  So you are saying roles are being destroyed not
moved over, right?

**Comment by proceps** [comment]
Yes, roles are destroyed. I believe in the People model, the cascade deleting should be disabled. People only could be deleted if they do not have any roles.

**Comment by mjy** [comment]
You might be right, but- there is only one role spec, that currently
passes, we need to add more to start to capture the problem.

There were some tweaks to who gets merged into what on the interface, it
could be possible that somethign went wrong there and the people are
switched, the wrong one being merged?

**Comment by proceps** [comment]
I believe that deleted the right one, but the roles are were transferred. The simple prevention would be to make impossible to delete a person if there are any roles attached to it.

**Comment by mjy** [comment]
I'm working on it now.  We transfer roles *before* we delete people, so
that shouldn't be the problem.  It might be an in-memory thing though,
where roles not being updated for the person who is deleted.  Writing specs
to try and capture it first.
