### ISSUE TITLE
NomenclaturalRank::Icnb::HigherClassificationGroup::Kingdom is missing parent?

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#724]
undefined method `parent' for "NomenclaturalRank::Icnb::HigherClassificationGroup::Kingdom":String
  app/models/protonym/soft_validation_extensions.rb:286:in `sv_primary_types'

**Comment by mjy** [comment]
Remember we have signficant data in the system, changes like the constant renaming require more care!

**Comment by proceps** [comment]
I know that I have problem with my data on sandstorm. Does speciesfile handle bacteria as well? If so, some changes are definitely needed. I do not think any of the production databases have ICNB records. At least not in my version of the database which I am testing.

**Comment by mjy** [comment]
@proceps can we close this?

**Comment by proceps** [comment]
@mjy I have not experience this problem. Probably we can close it and reopen if needed.
