### ISSUE TITLE
Task - Type specimen - lectotype and neotype citation

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#731]
Lectotype and Neotype designation require a citation of the source where the type was designated. Please add a citation field to the form.

**Comment by mjy** [comment]
Use the is_origin via the radial annotator beside the pertinent row.

**Comment by anadm** [comment]
the system should probably not allow the creation of the lectotype/neotype
entry without a citation attached

**Comment by proceps** [comment]
It is harder to enforce. Sometime I get this information from a revisionary study, not from the original designation

**Comment by mjy** [comment]
You can add a source from the radial annotator on the type specimen row.

**Comment by proceps** [comment]
I think it is fixed.
