### ISSUE TITLE
Task - type species designation of genus

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#733]
I can select from three categories: 
1) original designation
2) original monotypy
3) subsequent monotypy

It is not possible to select both 1 and 2 together. According to the Code "original designation" has priority over "original monotypy". Sometimes the information on type species is unknown and the corresponding paper is not accessible. In these cases it is often possible to determine whether the genus was originally monospecific. The author might have explicitly designated the species as type of the genus, but this remains unknown, and I would select "original monotypy".

What I am getting at: The monotypy part is important information, even in case of additional original designation. In OSF we have around 300 genera with type species data "by monotypy and original designation". If this is converted into simply "original designation", we lose information.

Among the categories this one is missing: "subsequent designation".
(I deleted the type species data of a genus that was correctly imported with "subsequent designation", and then only the three above-mentioned ones are offered.)

**Comment by proceps** [comment]
I think the safest solution would be to convert those name to just "type species" without specification and require additional verification against the original source (may be a note attached to the species). Because you are right, the ICZN states that determination of the type have priority from the original designation over the original monotypy.
For other categories, please open show all, to see many other categories of the type designation (including generic one: type species).

**Comment by typophyllum** [comment]
Thanks, I overlooked "show all".
I do not agree to conceal with obviously monospecific genera this often easily verifiable fact (own database, subsequent references, tiny fragments displayed on Google Books) in cases where it is unknown whether there was also an original designation.
My main point is to document the monotypy information in cases with a trumping original designation. In OSF we would lose this important information at around 300 genera.

**Comment by typophyllum** [comment]
Monotypy can be inferrable by database contents plus other sources as I mentioned above. In OSF we usually don't record a source for "original monotypy", since it is sort of redundant. I mentioned this situation, practically certain original monotypy combined with uncertainty about original designation, only to make my point of allowing the combination of two categories.

Monotypy is an important fact, regardless of original designation. This fact, recorded in OSF as "monotypy and original designation", for 300+ genera, should be preserved when we move OSF to TW.

**Comment by proceps** [comment]
@typophyllum if we do changes as I described above, you will be able to select "Original" without specification if this Original designation or original monotypy.

**Comment by mjy** [comment]
Is subsequent monotypy a real thing?  I don't think it is.

**Comment by proceps** [comment]
It is. The genus was described without species. And one species later placed into it. Most typical scenario when the paper is published in parts. The first part include a key to genera (which validates generic name) and next part include the genus name and one species associated with it.

**Comment by mjy** [comment]
Remember though that NOMEN is about how the name can be interpreteted
legally.  Whether or not it is monotypic subsequently means nothing, right?

**Comment by proceps** [comment]
It looks like we do not have types in NOMEN...

**Comment by proceps** [comment]
That is what I am saying, nomenclaturally important that the type is designated in the original publication (as monotypy, or designated). It could be less important. SF is a good example.
