### ISSUE TITLE
Object radial (source eg)

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#737]
As a user I want to use a radial navigator, displayed near an object label, to navigate to common functions and tasks for that object.  The options on this navigator should be navigation, NOT reading/writing/annotating (no tagging, pinning, etc), i.e. the tool is meant to lead the user out of the current context, to a new context.  Ultimately a mixed UI modal  could lead users to either the navigation or annotation or X radials.

To start, test the concept using Sources.  

* Annotator is initialized with a global_id
* Slice content/configuration is via a JSON or JS hash, it should be standardized and customizable relatlively simply.  Basic CRUD (create, update destroy) links should be configurable (able to be turned on) with a single option in the customization.
* Navigating to a task includes passing the required ID to that task as a param- ensure that task endpoints start with param named un a unified fashion (`:id`, etc).

<img width="1172" alt="screen shot 2019-01-09 at 9 22 34 am" src="https://user-images.githubusercontent.com/22600/50908818-211ae400-13f0-11e9-929f-fd516ebffddc.png">

**Comment by jlpereira** [comment]
This is already done, can we close it?
