### ISSUE TITLE
Project preferences - Customizing interfaces per model with default attribute sets

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#741]
Blocker/dependency of full #377 

As a user I want to select Predicates and assign them to class sets.  These predicate sets will appear as blocks in the forms/tasks that use them.

* Preferences can be set by a project admin or admin
* Data is stored in Project(?)#preferences:

```json
  'model_predicate_sets':  
    'Otu': [1,2,3]
    'CollectingEvent': [4,5,6]
```

In this case 1-6 are the IDs of Predicates.

* We need a new task to build the assignments.  Hard code the list of models that can make use of these sets in interfaces (at present CollectionObject and CollectingEvent).
* Select model
* Smart select predicate?  Or just show all and let user select into list.
* Include a link, or modal popup to create Predicate inline.

**Comment by mjy** [comment]
![screen shot 2019-01-10 at 9 38 10 pm](https://user-images.githubusercontent.com/22600/51011895-0e073180-1520-11e9-9d37-b160527db9ad.png)

**Comment by jlpereira** [comment]
Done
