### ISSUE TITLE
Task: new taxon name, not finding genus in parent list

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#744]
When I go to create a new taxon, suppose it is a species name. 
Under "name", it automatically starts searching for similar names, but that display is clunky as it doesn't disappear after I hit the spacebar or tab (it should understand none of the displayed names is what I want).
Then, when I go to select the parent, suppose I am searching for the parent genus. It continues to load species lists. In this particular case it doesn't even load the genus name: 
![image](https://user-images.githubusercontent.com/1326839/51392492-56c07b00-1b1c-11e9-9910-7ccd6cf38165.png)

**Comment by mjy** [comment]
Calling this a bug- since it's a real problem.

**Comment by mjy** [comment]
Remembered- this is fixed in development.  Will deploy ASAP.
