### ISSUE TITLE
Task - new taxon name - confusing message on assignment of original genus

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#745]
I create a new species name, and select a parent genus. 
The soft validation immediately recognizes no original genus was assigned. 
If I go to "original combination and classification" and select "use current", it seems that the genus I chose is correctly marked as original (expected behavior), but a message saying the genus is unassigned is also displayed:
![image](https://user-images.githubusercontent.com/1326839/51393219-56c17a80-1b1e-11e9-9cf0-9be340d74b4f.png)

**Comment by mjy** [comment]
Thanks @anadm. @proceps Appears to be an issue with cached_original_combination, though our tests should certainly be catching this.  It might somethign to do with how the "Use current" triggers POSTs, we'll see.  Working to independently confirm, though anadm states that the issue remains on page reload, so it's likely real.

**Comment by mjy** [comment]
It is *not* a problem with the cached build, but rather page load (if a problem at all, might have been a broken connection).  Re-assigning to @jlpereira

**Comment by proceps** [comment]
I cannot confirm it. Make sure that the genus is assigned as original genus (and parent) of the species. Not a genus-group or something else. In my experiments, the original genus is always properly displayed.

**Comment by mjy** [comment]
I suspect it might be lag/latency based.  The data are fine, what she sees is not.

**Comment by jlpereira** [comment]
I can't replicate it

**Comment by mjy** [comment]
This may be related to the bug Holger found.  When we push to sandbox we'll get Ana do recheck.

**Comment by mjy** [comment]
@anadm can we close this?
