### ISSUE TITLE
Task - new taxon name - status message

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#746]
When I go to new taxon name, I create it and then I go to assign the status. 
Under "show all" I can select "valid". 
If I do so, the soft validation displays a helpful message saying I shouln't do that, because everything I add is valid by default. 
That message would be more helpful if displayed under "status" permanently, not as soft validation, instead of simply "valid as default". (or a question mark right next to it)
![image](https://user-images.githubusercontent.com/1326839/51393705-7a38f500-1b1f-11e9-8c9f-e2902dc408f1.png)

**Comment by mjy** [comment]
Closing as outdated.
