### ISSUE TITLE
Task - new taxon name - Type

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#747]
When I create a new taxon name (a new species), soft validation tells me I haven't assigned a type specimen (expected).
The type dialog box is a link that opens in a new window, where the type specimen is created (ok).
Then if I come to the original new taxon name screen and reload, the soft validation warning is gone (ok). 
However, no type information is displayed under "type".
(for reference, this is new taxon name 175231, a test name)

**Comment by mjy** [comment]
@anadm - can you clarify, with a screenshot perhaps, what you mean by "However, no type information is displayed under "type"."  On which interface?

**Comment by proceps** [comment]
the Edit Taxon Name page does not show any type information for species, even if the type specimen is created.

**Comment by proceps** [comment]
Duplicates #411

**Comment by mjy** [comment]
Can be closed, right?
