### ISSUE TITLE
Task - New combination - Subgenus

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#748]
Cannot create a new combination for a subgenus in a format:
* [ ] "Genus (Subgenus)" (doesn't show subgenus as choice)
<strike>* [ ]  "Genus Subgenus" </strike> (can't be done, must have parens)
* [ ] Subgenus (at genus group rank)

Only generic rank is recognized.

**Comment by mjy** [comment]
This is a limitation of Biodiversity gem and will need to be fixed there.
@dimus maybe new gnparser can have a subgenus mode.

**Comment by mjy** [comment]
Blocked by switching from Biodviersity to Dima's new parser.

**Comment by proceps** [comment]
Please prioritize this one!

**Comment by mjy** [comment]
This is a major rewrite, swapping in a new gem and result.  I expect we might get to it in a couple weeks.

**Comment by tmcelrath** [comment]
We also need this!

**Comment by mjy** [comment]
Likely going to have to decouple auto-match of original combination to allow for user combinations to be added ... maybe.

* [ ] 'Original_combination' - fix string

**Comment by tmcelrath** [comment]
Woohoo! I want a demo of this in nomenclature meeting when live @mjy

**Comment by proceps** [comment]
@tmcelrath I just checked, works the same as genus/species combination, but now you can also do genus/subgenus combination (when the rank of the genus-group name changes, or when subgenus moved from one genus to another).
