### ISSUE TITLE
Edit taxon name / Original combination and classification (suffix wrong) / adjective vs. participle

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#750]
I added the new species Hexacentrus bifurcatus Farooqi & Usmani 2018.
The name in the original desription is Hexacentrus bifurcata (referring to bifurcate female subgenital plate).
According to ICZN Article 34.2. the name needs to be adapted to the masculine name Hexacentrus.

I cannot edit "Original combination" accordingly. Impossible to enter anything in the field "Species". Does the original combination with the incorrect suffix need to be entered as a separate taxon name?

And is "bifurcatus" an adjective or a participle? For me it is both.
The Code uses the combination "adjective or participle" (e.g. Articles 31.1. and 31.2.) and perhaps the two categories should be combined here as well.

**Comment by proceps** [comment]
I do not like the idea combining "Adjective" and "participle". If people do not care and need just functionality, everything could be recorded as "adjective", but in my case, I took time to separate those, and it is relatively easy. Wiktionary is an a great and fast source. My biggest problem is not to separate adjective from participle, but to separate nouns from adjectives. The name endings -a, -us, -um do not guaranty adjective status. About a third of names ending with those are actually the nouns, so you still need to check the dictionary to make a decision. If I do not have time, and do not know the word, I prefer not to decide and leave the part of speech blank.

**Comment by typophyllum** [comment]
Thank you.

Setting genus name to masculine and selecting adjective for the species name works. And I am starting to understand the functionality of the section "Original combination and classification". The help text has a typo: "was originally found it" (should be "in").

The origin of my confusion is that many adjectives can also be interpreted as participles, like "bifurcatus" of the verb "bifurcare". But you are right, there are also "pure" particples.
