### ISSUE TITLE
Task - Edit loan form - missing policies information

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#755]
Task - when I edit a loan
     then there is nowhere to add custom loan policies or a link to loan policies
     this will vary by museum
     this should default to the loan policy listed by the lending museum

**Comment by mjy** [comment]
@tmcelrath Still an issue?

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/68963318-46107e00-079c-11ea-954f-4a2243e4fa78.png)

Mock-up here

Note that I don't want to have to add a Note for "Loan Policies" every time I create a loan. It would be acceptable if this was added by default though. 

Not a blocker issue. Maybe wait? Finding loans is more important.

**Comment by tmcelrath** [comment]
I think this is done with Notes.

**Comment by mjy** [comment]
Closing as done/outdated.
