### ISSUE TITLE
Issue - code displaying in hub page of sandbox

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#765]
Running Chrome 71.0.3578.98, Mac OSX 10.13.6 
When I go to account page in sandbox (click on account button at top left) 
then a bunch of code shows at bottom of screen.

![image](https://user-images.githubusercontent.com/11411328/51922702-2ea00a00-23af-11e9-945d-8f643233dd5d.png)

Issue is not present in production (see second image)
![image](https://user-images.githubusercontent.com/11411328/51922776-54c5aa00-23af-11e9-99d1-216909380f2d.png)

**Comment by mjy** [comment]
Not a bug, but rather a quick view of the new preferences for us to debug with.  It will get cleaned up later.

**Comment by tmcelrath** [comment]
Great. Wanted to make sure.
