### ISSUE TITLE
New taxon name: "Gender and form" gets greyed out

### ISSUE THREAD

**Issue by typophyllum** [SpeciesFileGroup/taxonworks#767]
This seems to happen consistently:
I add a new species name.
Then I select a source.
Then I set "Original combination and classification" to current.
When I then select in  "Gender and form" one of the four categories, the section gets greyed out.

So it is not possible to change the category, or edit the proposed two additional forms in case "adjective" is selected (sometimes they are incorrect). The selected category is saved though and the section is displayed normally after refresh or coming back to the page later.

However, if I enter something to "Etymology" while "Gender and form" is greyed out, this will not be saved, even if I click on the green save button on the upper right hand, and below appears the confirmation that the taxon was successfully updated. When "Gender and form" appears normally again, the etymology text is gone.

**Comment by mjy** [comment]
@jlpereira These are the errors we've been getting emails the autosave on Source in Author is failing, and the JS is locking somehow ` "citation_object_id"` is null

**Comment by jlpereira** [comment]
Fixed @typophyllum 
The change will be reflected in the next update of sandcastle
