### ISSUE TITLE
Can't add depiction of accession book images

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#769]
When I go to a collection object tagged with what was originally an accession code "e.g. a single label with a number that referred to a handwritten accession book data entry instead of a fully written label" 

Then I want to see the depiction of the scanned accession book image (e.g. https://www.biodiversitylibrary.org/item/253124#page/26/mode/2up) as a depiction of the label of that specimen or of the original collecting event. 

But I cannot get to the identifier itself to add a depiction.

**Comment by mjy** [comment]
Blocked by #1163 I think.

**Comment by tmcelrath** [comment]
@mjy this was closed by adding metadata depictions. Close?

**Comment by mjy** [comment]
@tmcelrath Yes, I think so, display/other issues are covered in #1163.
