### ISSUE TITLE
Depiction validation taking too much time on some cases

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#770]
So far discovered on Orthoptera project in sandcastle. Reproducible on dev machine using the following script on rails console:
```
otu = Otu.find(84)
otu.taxon_name

$project_id = 2
$user_id = 1

9.times do |i|
	otu = Otu.find(84) # Important: Having this outside the loop won't trigger the problem.
	puts "[#{Time.now}] CREATING DEPICTION #{(i+1).to_s}"
	Benchmark.bm do |x|
		File.open('./public/images/missing.jpg') do |file|
			# Using depiction_object_id and setting type manually also triggers the problem.
			x.report { Depiction.create! image_attributes: { image_file: file }, depiction_object: otu }
		end
	end
end
```
(test_case.rb)

The problem is that with every new Depiction created for a given Otu, each one takes longer and longer to `create!` (presumably stuck at validation).

Example output on dev machine (stdout only):
`rake db:drop && rake db:create && pg_restore --format=custom --username=taxonworks_development --dbname=taxonworks_development --no-acl --disable-triggers ../taxonworks_data/import_checkpoints/citations_create_otu_cites.dump && rake db:migrate && rails c < test_case.rb | tee output.txt`
```
Loading development environment (Rails 5.2.2)
Switch to inspect mode.
irb: warn: can't alias context from irb_context.
otu = Otu.find(84)
#<Otu id: 84, name: nil, created_at: "2019-01-26 04:18:22", updated_at: "2019-01-26 04:18:22", created_by_id: 5, updated_by_id: 5, project_id: 2, taxon_name_id: 128>
otu.taxon_name
#<Protonym id: 128, name: "biloba", parent_id: 127, cached_html: "<i>Mirhipipteryx biloba biloba</i>", cached_author_year: "(Hebard, 1928)", cached_higher_classification: nil, created_at: "2013-02-12 18:23:00", updated_at: "2019-01-26 04:18:22", year_of_publication: nil, verbatim_author: nil, rank_class: "NomenclaturalRank::Iczn::SpeciesGroup::Subspecies", type: "Protonym", created_by_id: 5, updated_by_id: 5, project_id: 2, cached_original_combination_html: "<i>Ripipteryx </i>[SPECIES NOT SPECIFIED] <i>bilob...", cached_secondary_homonym: "Mirhipipteryx biloba", cached_primary_homonym: "Ripipteryx biloba", cached_secondary_homonym_alternative_spelling: "Mirhipipteryx biloba", cached_primary_homonym_alternative_spelling: "Ripipteryx biloba", cached_misspelling: nil, masculine_name: nil, feminine_name: nil, neuter_name: nil, cached_classified_as: nil, cached: "Mirhipipteryx biloba biloba", verbatim_name: nil, cached_valid_taxon_name_id: 128, etymology: nil, cached_original_combination: "Ripipteryx [SPECIES NOT SPECIFIED] biloba">

$project_id = 2
2
$user_id = 1
1

9.times do |i|
	otu = Otu.find(84) # Important: Having this outside the loop won't trigger the problem.
	puts "[#{Time.now}] CREATING DEPICTION #{(i+1).to_s}"
	Benchmark.bm do |x|
		File.open('./public/images/missing.jpg') do |file|
			# Using depiction_object_id and setting type manually also triggers the problem.
			x.report { Depiction.create! image_attributes: { image_file: file }, depiction_object: otu }
		end
	end
end
[2019-01-30 14:36:15 -0300] CREATING DEPICTION 1
       user     system      total        real
   0.140972   0.070768   0.346870 (  0.400344)
[2019-01-30 14:36:15 -0300] CREATING DEPICTION 2
       user     system      total        real
   0.040017   0.027008   0.201147 (  0.227124)
[2019-01-30 14:36:16 -0300] CREATING DEPICTION 3
       user     system      total        real
   0.048299   0.028695   0.211436 (  0.239366)
[2019-01-30 14:36:16 -0300] CREATING DEPICTION 4
       user     system      total        real
   0.069881   0.029991   0.234926 (  0.260481)
[2019-01-30 14:36:16 -0300] CREATING DEPICTION 5
       user     system      total        real
   0.198630   0.037301   0.370774 (  0.397854)
[2019-01-30 14:36:16 -0300] CREATING DEPICTION 6
       user     system      total        real
   1.091137   0.066668   1.291739 (  1.319259)
[2019-01-30 14:36:18 -0300] CREATING DEPICTION 7
       user     system      total        real
   7.502627   0.079058   7.720568 (  7.746726)
[2019-01-30 14:36:26 -0300] CREATING DEPICTION 8
       user     system      total        real
  63.614160   0.165716  63.911439 ( 63.979282)
[2019-01-30 14:37:30 -0300] CREATING DEPICTION 9
       user     system      total        real
 597.459559   0.840084 598.431064 (598.609815)
9
```
(Last one took almost ten minutes)

[logs/development.log](https://github.com/SpeciesFileGroup/taxonworks/files/2813898/development.log)

**Comment by mjy** [comment]
@LocoDelAssembly 

* [ ] can you try File.read instead of File.open?
* [ ] Does it only ever happen when a taxon_name_id is present in the Otu?

**Comment by LocoDelAssembly** [comment]
@mjy I've changed the test. Comment out https://github.com/SpeciesFileGroup/taxonworks/blob/8c85736956cca510497a80d261461c51a19bb7ee/spec/models/depiction_spec.rb#L24 to see the test pass again (just to confirm the expectation works).

Now I noticed you had an expect in the loop. Is that safe? In that case the ratio expectation can be moved in and simplified a bit.

**Comment by mjy** [comment]
I just left the expect in there for spec purposes, it's not necessary.

**Comment by mjy** [comment]
Nice modification to the test, that makes more sense.  We can remove the other expectation.

**Comment by LocoDelAssembly** [comment]
But if it is safe to repeatedly call `expect` then we can move the ratio test inside the loop and avoid using `break`. Cleaner, but unsure if it is OK.

**Comment by mjy** [comment]
Typically you'd want only one expectation per test, but we do use loops
in some cases.  This is an exceptional case, so I think it's OK either way,
whaterver is cleaner and get's the idea across.

**Comment by LocoDelAssembly** [comment]
There is a warning in [here](https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validates_associated), however in our case there is no infinite recursion as it eventually completes the validation and couldn't fine `validates_associated` on both ends either (though I might not be looking for it right). BTW, the actual complexity is more like `O(n!)` than `O(b^n)` since `b^n/b^(n-1) = b` but in the test `bm.utime/last_utime` always increase (like `n!/(n-1)! = n` would do).

I would imagine it is brute forcing all paths (i.e. `depiction_0 > otu > depiction_1 > otu > ...`, `depiction_0 > otu > depiction_2 > otu > ...`, etc.), or something like that to have such complexity, but I don't know why it does this. Do you @mjy?

**Comment by mjy** [comment]
Found the problem:

* https://apidock.com/rails/ActiveModel/Validations/ClassMethods/validates_associated

As implemented here:

* https://github.com/SpeciesFileGroup/taxonworks/blob/development/app/models/concerns/shared/depictions.rb#L16
* https://github.com/SpeciesFileGroup/taxonworks/blob/development/app/models/depiction.rb#L36

Looks like we need to check `validates_associated` throughout.
