### ISSUE TITLE
Go to next unfinished CO image breakdown TODO button

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#771]
When I go to "Collection object image breakdown (sqed) TODO list" task,
Then I want to see a button that says "Go to first unfinished collection object",
Instead of having to click potentially many times or remember where I last left off. 

Potentially enhancement.

**Comment by mjy** [comment]
FYI - `skip to next` should jump you to the next record that needs to be worked on?

**Comment by tmcelrath** [comment]
Yes but that's not a button on the landing page. You have to click into an already completed record currently and then click that.

**Comment by mjy** [comment]
Got it.  What I should do is make a hub that provides some other metadata.

M
