### ISSUE TITLE
Finding data for a taxon

### ISSUE THREAD

**Issue by klausriede** [SpeciesFileGroup/taxonworks#772]
help wanted Hello, I am new on taxonworks, and my experience on github is limited. In the sandcastle I managed to find Euplectrotettix ferrugineus. My final aim is to upload a song, as I did in OSF. However, first I wanted to solve the simple task of visualising associated data, like localities, specimens and some songs I already uploaded. Is this working already for the sandcastle? If so: How do I access these data? I only see https://sandcastle.taxonworks.org/taxon_names/7183
without any option for recall of associated data

**Comment by mjy** [comment]
Hi @klausriede.  Very nice to hear from you, and thanks very much for reaching out via Github, we appreciate you jumping through this hurdle. Some answers:

* We don't have a media model done yet, the songs have not been added to the sandbox (you can track progress when it begins here: https://github.com/SpeciesFileGroup/taxonworks/issues/244)
* All the SFG data is sandboxes is in various stages of flux as we debug issues, I expect and update sometime next week, though it will not yet have songs
* We similarly don't have the taxon pages built to give you the summaries that I think you are looking for, we're *just* about to get that going now that we have all the precursor editing bits "working" (perhaps you saw the manual I wrote for paper processing to get an idea of where we are)
* To get to that taxon page from the nomenclature page you would use the "Otu navigator button", it's the solid hexagon with the right pointing arrow. 
* We will actually have a little information starting to appear on the taxon page in sandboxes, in a crude and rudimentary manner sometime next week, but again it won't reflect what it will look like in the long term

So- a very unsatisfying answer for you, but your interaction here pushes your/these priorities closer to the top of the big-old TODO list, thanks so much.

**Comment by klausriede** [comment]
Thanks @mjy - this helps me to understand what goes on right now, and even though you ar not yet ready for multimedia, I will explore some of the other issues you mention - OTUs are extremely interesting for me, because I have many specimens waiting to be re determined and/or properly described. 
I have some additional ideas about connecting sound analysis and taxonomy using R, taxize seems to be a very active and promising approach. To this end taxize needs an API, and I see that you are working on this. But that´s probably in the category Vision, best wishes, Klaus

**Comment by mjy** [comment]
@klausriede sounds interesting, we are definitely interested in integration of complex data. 

I'm going to close this as a "duplicate" of https://github.com/SpeciesFileGroup/taxonworks/issues/160, that is the precursor to us working on taxon pages.  Not quite related, but in the same vein.
