### ISSUE TITLE
Sources: seemingly not detecting duplicates

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#779]
I was able to create a new source from a citation that was already in the database. Apparently the DOI is present in both, but still there were no duplication warnings. 
Refs are 19117 and 62267.

**Comment by mjy** [comment]
There is no DOI on the first record.   Not sure if this was prevented, or if it wasn't there and therefor the record was caught as duplicate on create.

**Comment by anadm** [comment]
also seems weird, crossref seems to give a different year. noticing now

**Comment by anadm** [comment]
this could be one of the things to add to a soft validation: "likely duplicate reference, check year"
