### ISSUE TITLE
Sources: author names imported by crossref when original is in caps

### ISSUE THREAD

**Issue by anadm** [SpeciesFileGroup/taxonworks#783]
When I "create a new source from citation", and the original source has the full name of the authors in capitals, CrossRef interprets it all as initials. Likely important problem because a large number of descriptions comes from Magnolia Press, which uses this format (Zootaxa).
Issue is partially solved because it seems TW is recognizing this problem exists and correctly matching the author against "people". However, the display is still confusing: 
![image](https://user-images.githubusercontent.com/1326839/52574799-28c11480-2e04-11e9-987e-1f03ba53149d.png)

![image](https://user-images.githubusercontent.com/1326839/52574729-0b8c4600-2e04-11e9-9318-6255169b51a4.png)

**Comment by typophyllum** [comment]
I find this confusing too. 
If I create the "source from citation" search it by the DOI and then "Create a source in BibTex format" it afterwards gets parsed correctly it the authors are already known (except for the page range, it records only the number of the first page).
With new authors it seems to work as well, however, if I then search the reference (browse sources) the names are again displayed as decribed by anadm (when I go to "Editing source" the display is correct again).

**Comment by mjy** [comment]
For the record all authors are created as new at present.
