### ISSUE TITLE
`CollectingEvent` needs accessors for start and stop date/time.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#800]
It would be handy if `CollectingEvent` had accessors which used `Date` and/or `Time` to populate start and end date and time attributes (write) and composite the start and end date and time attributes to return a `Date` or `Time` class object. (also `DateTime` class)
Maybe like 
`start_date = Date.parse('2001-02-03')` 

or 
`start_date = DateTime.new(2007, 1, 2, 3, 4, 5, 6) **NOTE** the inclusion of a real time when processing `xxxx_date`.

or
`end_time = Time.rfc2822("Wed, 05 Oct 2011 22:26:12 -0400")`  **NOTE** the inclusion of a real date when processing `xxxx_time`.

**Comment by mjy** [comment]
On further thought we will not add these features and force our users/developers to include their own middle layer, thus eliminating possible unintended consequences (e.g. storing month/day as 1/1 when none was provided).
