### ISSUE TITLE
Pinboard - Source

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#804]
Source is not added to the pinboard. When I click on the pin next to the source, it changes from green to red and stay so, but the source does not show up in the pinboard.

**Comment by mjy** [comment]
What context?  In some cases it shows up on next reload of the pinboard
(i.e. from data cards, that aren't Vue based).


M

**Comment by proceps** [comment]
I am working with taxonomy. None of several sources which I added to the pinboard are there. Page was reloaded multiple times. Since the source is not selected as default, I cannot use in any of the interfaces (TaxonName original source, radial citation, etc.). Two days ago, when I deleted numerous sources which get accumulated in the pinboard at that time, some error was generated (I received an authomatic report). Since than, I cannot add anything new. I tried to add a taxon name to the pinboard, and it worked.

**Comment by mjy** [comment]
```

**Comment by mjy** [comment]
It appears something happened during a reposition, maybe?  We should experiment with drag dropping rows.

```
  PG::TRDeadlockDetected: ERROR:  deadlock detected
DETAIL:  Process 2956 waits for ShareLock on transaction 3110307; blocked by process 2953.
Process 2953 waits for ShareLock on transaction 3110306; blocked by process 2956.
HINT:  See server log for query details.
CONTEXT:  while updating tuple (0,6) in relation "pinboard_items"
: UPDATE "pinboard_items" SET "position" = ("pinboard_items"."position" - 1), "updated_at" = '2019-02-20 02:52:02.434275' WHERE "pinboard_items"."project_id" = $1 AND "pinboard_items"."pinned_object_type" = $2 AND ("pinboard_items"."position" > 2)
  app/controllers/pinboard_items_controller.rb:46:in `destroy'

```

**Comment by jlpereira** [comment]
I can't replicate it @proceps, it works fine for me. 
Steps to reproduce it?

**Comment by proceps** [comment]
could be something in my browser. I checked the other computer, all sources I selected are in the pinboard.  I will check the other computer again. But even if this is browser related it is strange. Because on the first computer, I could add taxonname and see it in the pinboard, but not the source.

**Comment by proceps** [comment]
it is still something. I had to clear browser history, only after that I could see the content of the pinboard. Something definitely went wrong.

**Comment by mjy** [comment]
Mmm- I suspect nothing wrong, just a bad cookie that wasn't updated.
That's going to happen until preferences stabilize.

**Comment by mjy** [comment]
Closing, noting fix was "clear cookies".
