### ISSUE TITLE
Otu autocomplete enhancements

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#807]
When I search for related OTU, e.g. host plant, I can find only by full name of the genus and may be abbreviated name of the species. I cannot find it by partial genus name search

**Comment by mjy** [comment]
Can you provide query string examples in pairs?  

query string | otu name | taxon name 
-------------|----------|-------------
a | b | c

**Comment by proceps** [comment]
So, I start with an insect and click to OTU radial to add "Populus alba" as a host plant.
I can find is in two cases (assuming the OTU exists), if I search for:
1. "Populus alba"
2. "Populus alb"

But I cannot if I search for:
1. "P alba"
2. "popu alba"
3. "Pop alb"
4. "opulus lba"

**Comment by mjy** [comment]
@proceps Is this still the case?

**Comment by proceps** [comment]
Yes
