### ISSUE TITLE
OTU finder - create on fly if does not exist

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#808]
when I am adding new biological association, I am trying to add an otu for the host plant. I know that the host plant is in the database, but it does not show up in the list, because the OTU was not created. Suggested behavior.
1. Search OTU and return the list (already done)
2. If nothing return, search for taxon names, and if exist, create an OTU on try for this taxon and return it.

This would be useful in many interfaces: biological associations, matrices, browse OTU, etc.

**Comment by mjy** [comment]
Already exists, you have to search for somethign that doesn't exist, and you will get the new button.

**Comment by proceps** [comment]
I checked it. It works. But I have to make a second search to find if the taxon name, which does not have an OTU, exists, it would be nice to have an indication, that this taxon name already in the DB, so I do not have to create another anonymous OTU

**Comment by mjy** [comment]
Not sure I understand.  The initial search, prior to new, already searches both Otu#name and TaxonName.  If you don't have a hit there, you don't have an Otu.  You can then go to the TaxonName search and search there first, if that doesn't hit, you add an anonymous Otu, right?  There isn't much more magic we can do.

**Comment by proceps** [comment]
Yes, it searches for both, but only in OTUs, if it has taxonnameID, I will find it in the search. I am talking about searching for actual TaxonName. So when I search for an OTU, and none is available, but there is a taxon with exactly the same name (or partial name), which does not have any OTU. It would be good to return that as an option to create a new OTU, instead of going to the New section, and making another search, if the taxon actually exists, because by default when you go to New OTU section, the name appears in the name section (and have to be deleted from there) and TaxonNameID is still blank, and I have to do a second search to find if the name already exist. It is OK, when I recently created taxon name, and know that it is in the DB, but when it is not, it is not intuitive how to proceed. The best solution would be to return the TaxonName (not OTU) in the OTU search box (when OTU does not exists) and if it is selected, automatically generate OTU for it.

**Comment by proceps** [comment]
Please prioritize, this is also an issue in The asserted distribution task. If TaxonName is in the DB, but it does not have an OTU created, I cannot find it using the search interface. I have to go to browse nomenclature page to create OTU first.

**Comment by proceps** [comment]
Same problem reported by Chris today. When he finds taxon name in the Matrix Dashboard and wants to add this name to the matrix, he get unspecific error message ("can't be black"), because this taxon name does not have OTU.

**Comment by proceps** [comment]
The new feature is functional now. The small problem. When options are offered to create a new OTU, the interface is partially blocked to search window:
![image](https://user-images.githubusercontent.com/5597748/83343284-d6885900-a2bd-11ea-986b-2c4afe90efc9.png)

**Comment by proceps** [comment]
This was in comprehensive digitization task, when I tried to add determination. Not sure about other places.
