### ISSUE TITLE
Task - TaxonName - OTU create

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#809]
When I create a new taxon name and also want create an OTU, I can click on the OTU radial, and this will create OTU and also open an Radial selector for it, but if I just want to create an OTU, it is little bit annoying, that I have to close the radial selector after. Proposed behavior 2 options:
1: clicking on OTU radial, when OTU does not exist, just creates an OTU, the radial changes the color. Second click will pop up the selector.
2. Add project preferences to create OTU every time a new taxon name is created.

**Comment by mjy** [comment]
1 - is a matter of preference - I want this button in many places, so I don't think we'll change it.

2 - is already an issue added somewhere here I think

3 - user, not project preference to always create OTU

4 - a boolean/checkbox on the taxon name form that says "also create OTU'.  

5 - a seperate icon/button that has create only functionality.

I suspect 4 is the most clear and transparent behaviour.
