### ISSUE TITLE
Collection object by otu/date/area filter UI

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#81]
* ~~Filter button on left side, slides out from left analogous to right side slides-outs?!~~
* ~~Disable find unless some result ???? is set and > 0~~
* ~~Disable Download button until 'Find' has been clicked ~~
* When I open the filter again, and perform a second search, the results of the first search are still displayed, clear them.
* ~~"Collection objects" in top bar seems odd, maybe strike that whole section, and place the download/icons on a single line in the find/result panel?~~
* Add help to partial overlap checkbox
* Add help to Descendants checkbox
* Add help to Result ??? boxes
* Add help to toggle map/list

**Comment by mjy** [comment]
* Reset slider behavior -> should *not* draw a new graph, but just remove it, and also return Result to '????'.
* Partial overlap should not fire when result = ????
* Tweak the look of the find button- seems like we want to semantically differentiate it to be a standard button, rather than mix up the round shape = slide out?

**Comment by mjy** [comment]
@jlpereira should we close this and re-open specific issues?  @jrflood, @proceps  IIRC you may have had specific bugs outstanding, or were they just feature tweaks?

**Comment by jlpereira** [comment]
Yes, I think we should close it
