### ISSUE TITLE
Resolve rmagick/travis configuration.

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#814]
* See existing blocking logs
* It is unclear whether this `IMAGEMAGICK_VERSION=6.8.9` does what we need

**Comment by LocoDelAssembly** [comment]
@mjy would you agree migrating to Xenial? `bundle install` works flawlessly on my setup here (Ubuntu 16.04.6 LTS - Xenial)

**Comment by mjy** [comment]
Think so!  See `Dockerfile` for our target Ubuntu.  That makes good
sense though.

M

**Comment by LocoDelAssembly** [comment]
Solved by upgrading to xenial builds.
