### ISSUE TITLE
Support Rails 6.0

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#815]
https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

**Comment by LocoDelAssembly** [comment]
Deprecation warnings to solve:

- [ ] acts_as_list. https://github.com/brendon/acts_as_list/pull/363 fixes but the gem maintainer says it needs to be solved differently (using https://github.com/meetcleo/acts_as_list/tree/silence-deprecation-warning-in-rails-6 directly in Gemfile [works](https://travis-ci.org/SpeciesFileGroup/taxonworks/builds/620295279))
- [ ] shortener gem. https://github.com/jpmcgrath/shortener/issues/117. Note that there might be maintainability problems with this gem. Using develop branch directly seems to [also work](https://travis-ci.org/SpeciesFileGroup/taxonworks/builds/620295279) in fixing Model.unscoped deprecation warning, but there are problems with it: https://github.com/jpmcgrath/shortener/issues/124.

Looks like we could proceed with merging and tolerate the deprecation warning until above problems get officially solved by the gems maintainers.

**Comment by debpaul** [comment]
@mjy are these deprecation warnings solved / no longer relevant?

**Comment by mjy** [comment]
shortener says its done in the issue, I haven't seen deprecations for acts_as_list for a long time.
