### ISSUE TITLE
Task - type material - new record

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#816]
I have a student, who does not have administrative privileges. Every time he opens a "Type material" task from Edit taxon name page. He has a pop up message "You have to sign as an administrator". Besides this message, everything seams to work correct.

**Comment by mjy** [comment]
* The only step is to open the the page? 
* Nothing more is clicked on or added? 
* The student can still change data?

**Comment by proceps** [comment]
Opening the page is triggering the pop up.
No other clicking.
It seams does not affect data editing process.
And I cannot replicate this with my data editing privileges.

**Comment by mjy** [comment]
@proceps can you replicate this in sandbox?

**Comment by jlpereira** [comment]
Backend issue, probably already fixed. Reopen if not
