### ISSUE TITLE
Slide panels - replace js animation by css animation

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonworks#817]

**Comment by mjy** [comment]
@jlpereira  Side note, I want to not show (or call endpoints for) all right side slideouts on any `/user(s)`, `/project(s)`, and `/administration`.

**Comment by jlpereira** [comment]
This should be a user/project preference or depending of the user privilages?

**Comment by mjy** [comment]
No- just on those specific route prefixes, it's not a preference.

**Comment by mjy** [comment]
Probably this is back end- btw.  If I simply do not render the side bar, it shouldn't be an issue, right? Just not sure how you are hooking in with JS.
