### ISSUE TITLE
Crossref not working when creating citation from doi

### ISSUE THREAD

**Issue by MMCigliano** [SpeciesFileGroup/taxonworks#818]
I've introduced 10.1111/syen.12317 in "citation to find" text box. After approximately 30 seconds I get "CrossRef did not find a match.". However manually searching in Crossref metadata is found: https://search.crossref.org/?q=10.1111%2Fsyen.12317 (takes lots of time to respond, like a minute or so).

Maybe TW timeouts too soon?

**Comment by mjy** [comment]
I have  various fixes done to that form yesterday,some inputs were crashing.  Should be better when sandbox updates.

**Comment by mjy** [comment]
@MMCigliano sandbox is updated if you want to test

**Comment by MMCigliano** [comment]
Perfect, returned "CrossRef found a match above the default score 50." status and the metadata is correct. Thanks.
