### ISSUE TITLE
OTU List Download

### ISSUE THREAD

**Issue by gilliandubin** [SpeciesFileGroup/taxonworks#822]
The download button on the list display of OTUs (under data) does not work.

**Comment by mjy** [comment]
Steps to reproduce?  It works for me.  Your browser may be saving the file automatically depending on what your settings are.  Make sure it's not appearing in your recent downloads.

**Comment by gilliandubin** [comment]
Dear Matt,

Thanks.

Sincerely,
Gillian Dubin

**Comment by mjy** [comment]
Does this mean we can close the issue? :)

**Comment by gilliandubin** [comment]
Dear Matt,

Yes. Sorry for the trouble.

Sincerely,
Gillian Dubin
