### ISSUE TITLE
Task - comprehensive specimen - TaxonCode

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#827]
TaxonCode field should not be in the form. The only place you need it, is in Determination search.
Instead of searching by TaxonName, I should be able only to enter a taxonCode and return the name.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/53761672-bdf77c00-3e8b-11e9-826d-e1639d64b60f.png)

![image](https://user-images.githubusercontent.com/5597748/53761726-d5cf0000-3e8b-11e9-94d5-0fdfe9814694.png)

**Comment by proceps** [comment]
TaxonCode is an OTU.identifier. I should be able to be able find by identifier.

**Comment by mjy** [comment]
That's a different (and second) issue ;).  You're looking at custom attributes, which are not related to determinations or taxon names. Closing this for specifics elsewhere.
