### ISSUE TITLE
Task - Comprehensive specimen - value-based autocomplete [EDIT]

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#828]
Special collection should give me a dropdown list of available special collections, or bring a list once I started typing.

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/53761632-a61ff800-3e8b-11e9-8a25-71d84545f03e.png)

**Comment by jlpereira** [comment]
@proceps should we close this? did you saw the changes?

**Comment by mjy** [comment]
@proceps Ping again- close?

**Comment by proceps** [comment]
@mjy In the preferences, I added special collection as a default predicate for the collection object. But I still do not see in in the comprehensive form. What else should I do to add it to the form?

**Comment by mjy** [comment]
@proceps I think we can close?  Is the value-autocomplete working?

**Comment by proceps** [comment]
I will check what it looks like
