### ISSUE TITLE
Task - comprehensive specimen - UI to Parse and extract from Verbatim label directly

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#829]
Once I entered the label data, automatically parse at least the dates and coordinates, and put values into proper fields.

**Comment by mjy** [comment]
This was part of the original spec.  It's somethign we'll work on after the task stabilizes in production for a while. For now remember that you can enter verbatim here, and use the lat-long and date parsers to walk through data.
