### ISSUE TITLE
Task - biocurations - update UI/UX - add style/layout

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#83]
@jlpereira can you minimally style this up (Manage biocuration types and groups)?

/tasks/controlled_vocabularies/biocuration/build_collection

**Comment by tmcelrath** [comment]
Mock-up link here:
https://docs.google.com/drawings/d/1qKg4_pM284O4nr6kl5j1c_igmdEta1E52KUtHOj0chA/edit

**Comment by tmcelrath** [comment]
![image](https://user-images.githubusercontent.com/11411328/149198433-3d5073dc-a7da-455a-83c5-95cf649cc6b2.png)

**Comment by jlpereira** [comment]
It's done

**Comment by jlpereira** [comment]
@debpaul I think this was already shown, it was done months ago.
