### ISSUE TITLE
Task - comprehensive specimen - Save button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#830]
Duplicate save button at the bottom of the page, so I do not have to scroll back and force.

**Comment by mjy** [comment]
I think the hotkeys makes it so we don't need this?

**Comment by mjy** [comment]
@proceps We still need?  (see hotkeys)

**Comment by proceps** [comment]
I would prefer to have a key. I know Ctrl-S, but still use it very rarely, and more often scroll the page. The same with most of the students I was working, although, I tried to teach some hotkeys...

**Comment by mjy** [comment]
@jlpereira Let's echo the full bar, minus the search at the bottom of the task.
<img width="923" alt="screen shot 2019-03-06 at 1 03 06 pm" src="https://user-images.githubusercontent.com/22600/53906312-3c7d2680-4010-11e9-864b-4e7e091ffb06.png">
