### ISSUE TITLE
Task - comprehensive specimen - buffered fields

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#831]
On the top of the page change the order of buffered fields: 1: collecting event, 2: determination; 3: others. That is how you normally see the labels on the specimen.
![image](https://user-images.githubusercontent.com/5597748/53762249-33b01780-3e8d-11e9-8784-97635d25269b.png)

**Comment by mjy** [comment]
The fields are aligned that way to correspond to the subforms below.  Moving them into another order will make comparing values more difficult.

**Comment by mjy** [comment]
Think we will not fix.  They are there for reference, and reference should align with existing data.

If you are using this task, then you should be entering non-verbatim data, in fact we may actually lock the buffered fields and only allow them to be unlocked if the user clicks through a warning (will add new issue).
