### ISSUE TITLE
Task - comprehensive specimen - Determination, OTU search

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#833]
Search both for taxonName and OTU.identifer, to make it easy finding the species. In the Insect collection we widely use taxon codes assigned to the Taxa, and in most cases, this is the fastest way finding the right taxon

**Comment by jlpereira** [comment]
Fixed @proceps, now the taxon name will be append to the quick option as a first element in smart selector

**Comment by jlpereira** [comment]
Sorry, this is not fixed. I closed it fixing other issue

**Comment by mjy** [comment]
Otu autocomplete now can search by identifier fragment.
