### ISSUE TITLE
Task - comprehensive specimen - Type name button from determination

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#835]
1. Type name, add a button: same as determination.

**Comment by mjy** [comment]
<img width="439" alt="screen shot 2019-03-06 at 10 40 20 am" src="https://user-images.githubusercontent.com/22600/53898037-efdc2000-3ffc-11e9-8e20-52957b57628b.png">

**Comment by mjy** [comment]
Button - "Same as determination"

**Comment by jlpereira** [comment]
Fixed @proceps, now the taxon name will be append to the quick option as a first element in smart selector
