### ISSUE TITLE
Task - comprehensive specimen - map

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#836]
Map should show show 3 things:
1. Geographic area shape
2. specimen dot.
3. Error radius or error shape (if both available, the error shape should have a preference)

**Comment by mjy** [comment]
Right.  We are waiting for new map stuff to do this.

**Comment by jrflood** [comment]
Find mechanism or tile layer that allows English (vs, say, Arabic) legending.
