### ISSUE TITLE
Task - comprehensive specimen - Recent button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#837]
Recent button takes forever. Did not return the result.

**Comment by mjy** [comment]
@jrflood, @proceps Can you provide steps to replicate this, I can't.  Check your developement server log to see if you can track it down further, likely due to some bad view rendering.

**Comment by jrflood** [comment]
I don't observe this phenomenon.

**Comment by mjy** [comment]
This is not an issue with TaxonWorks but rather sandbox back end. Will be fixed when http:// resolves to https://.  Temporary fix is to use https:// to start.
