### ISSUE TITLE
Task - comprehensive specimen - special characters.

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#839]
Somewhere we have to add a pop-up window to pick (copy and paste) special characters. Most problematic one is the degree characters, which is not on the keyboard. Most useful probably would be a side bar (next to pin board). to add few dozen common characters which could be copied in pasted anywhere in the form. Besides the locality label, it could be used in Source, People, etc. Something like an add a special character in the Word document.

**Comment by mjy** [comment]
Duplicate of https://github.com/SpeciesFileGroup/taxonworks/issues/4114
