### ISSUE TITLE
Slideout buttons

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#84]
When I mouse over a slideout (right side)
    *before* the click
         then can the circle slide out till it is just showing (not all the way to full view
             and a label (underneath?) is displayed describing what it is

**Comment by mjy** [comment]
Or... myabe just slide out the label beside it, rather than moving the circle out?

**Comment by jlpereira** [comment]
Yes, i thinking to make it in that form. Box with a little arrow and the description. Like the MacOS dock, for example
