### ISSUE TITLE
Task - comprehensive specimen - type specimen

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#841]
Selected 3 fields: Type name, Type type, Locality label. After saving, I got to the spinner mode and nothing happening.

**Comment by mjy** [comment]
Can not replicate. This is off a clean reload of the page?

**Comment by proceps** [comment]
It freezes page in both Chrome and FireFox. I tried to clean cookies and reload the page. The results are the same. I tried to use Alt-S. In one run, it actually saved the record, but once I tried again, the record get frozen again.

**Comment by jlpereira** [comment]
Check the browser console please, probably you're reaching a problem when you're trying to save the data

**Comment by proceps** [comment]
This is when I just load the page, did nothing:
![image](https://user-images.githubusercontent.com/5597748/53916702-71957300-4028-11e9-9036-d69c5b92745e.png)

**Comment by jlpereira** [comment]
can you expand the red errors?

**Comment by proceps** [comment]
There is only a reference to the line 217 there.

**Comment by mjy** [comment]
@proceps We need more info.  What project, what environment?

**Comment by proceps** [comment]
It is the sandbox server and InsectCollection DB.

**Comment by mjy** [comment]
Can you replicate? I can not.

**Comment by mjy** [comment]
This is not an issue with TaxonWorks but rather sandbox back end. Will be fixed when http:// resolves to https://
