### ISSUE TITLE
Task - comprehensive specimen - Radial annotator

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#842]
Missing radial annotator (sometimes I need to add alternative identifier).

**Comment by mjy** [comment]
Exists aready, just save the record.
<img width="1602" alt="screen shot 2019-03-06 at 10 29 08 am" src="https://user-images.githubusercontent.com/22600/53896963-c1f5dc00-3ffa-11e9-87de-124380340077.png">
