### ISSUE TITLE
Smart selectors - ability to pin selected elements

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#846]
Specifically, found repositories but also about every other search autocomplete,

**Comment by mjy** [comment]
Steps to replicate please.

**Comment by jrflood** [comment]
This is really a comment on the inability to pin something just searched for on various autocompletes.  I was just looking for a pin icon.  The lock icon seems to allow a short term carry over of the selected items, but it would maybe be nice to be able to pin more than one thing.

**Comment by mjy** [comment]
@jrflood I understand now.  This is a good idea.

**Comment by proceps** [comment]
recent tab keep track of last uses of the search. Do we still need this functionality?

**Comment by mjy** [comment]
I think we can close for specific suggestsions of places to add the `Pin` icon.
