### ISSUE TITLE
Task - comprehensive specimen: Red trash icon on determiner and type designator

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#849]
This would seem to imply removal of the entry from the database.  Use gray icon instead for removing from the list?

**Comment by mjy** [comment]
No, this is real data, added to the system!

**Comment by jrflood** [comment]
I may be wrong, but it seems like until thisperson selected is actually saved, shouldn't the behavior be like the blue undo icon?

**Comment by mjy** [comment]
In TW red means clicking will touch the database immediately.  This is the case here.  This is a metadata row being created or destroyed, independent of the other related data (collection object).

**Comment by jrflood** [comment]
To my relatively uninformed viewpoint. it looks like it is going to remove the person ... whereas the undo icon seemed more intuitive for a list item from the autocomplete...
