### ISSUE TITLE
Task - comprehensive specimen: transcribed coordinates from label outlined in red

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#851]
The map indicates the correct position, but the user is left thinking something is worng.

**Comment by mjy** [comment]
@jrflood Please screenshot

**Comment by jrflood** [comment]
![screen shot 2019-03-06 at 1 40 34 pm](https://user-images.githubusercontent.com/5349955/53908675-80265f00-4015-11e9-9250-59955d9e3717.png)

**Comment by jlpereira** [comment]
Pushed, can you test again and see if still getting the validation error?

**Comment by jrflood** [comment]
This fixed the issue :)

**Comment by jlpereira** [comment]
Thanks!
