### ISSUE TITLE
Task - comprehensive specimen: Selected Collecting event; strange display.

### ISSUE THREAD

**Issue by TuckerJD** [SpeciesFileGroup/taxonworks#855]
Selecting a Collecting event which has a geographic area associated with it can result in a strange display.
![screen shot 2019-03-05 at 09 18 54](https://user-images.githubusercontent.com/1838610/53815876-285dfa00-3f28-11e9-93b8-9b996395666b.png)

**Comment by jlpereira** [comment]
I think this is more associate with a missing stylesheet. Have you tried running npm install?

**Comment by TuckerJD** [comment]
First, that is not something which I regularly do: At what point should I consider it a requirement (i.e., what just changed such that this process is required?)
Second, after having done that which you suggest, the display is not markedly changed, but changes when Ctrl+ and Ctrl- are used to change the size.

**Comment by jlpereira** [comment]
Sometimes we include external packages thats needs to be installed. But if you're already done this, I will investigate what could make this happen.

**Comment by mjy** [comment]
@tuckerjs Please list specific steps to reproduce.

**Comment by mjy** [comment]
@tuckerjd please list specific steps to replicate.

**Comment by jlpereira** [comment]
Rebuild styles by removing cached assets
