### ISSUE TITLE
Otu radial - asserted distribution

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#856]
Add a map preview for the distribution.
Expected behavior, I add a new shape, and the map get reloaded with all shapes included.

**Comment by mjy** [comment]
I don't think we want this in Otu radial, too much space and not enough room?  Most people have the annotator already filling their screens.  Seems like this is part of a different task.

**Comment by tmcelrath** [comment]
Actually, I agree with @proceps - a small map for validation would be nice.
