### ISSUE TITLE
Task - comprehensive specimen: map is not reactive to change of collecting event context

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#857]
map appears to only react to verbatim lat/long fields

**Comment by proceps** [comment]
same as #836 ?

**Comment by mjy** [comment]
Not the same.  

@jrflood Itemize steps to reproduce please.

**Comment by jlpereira** [comment]
Pushed a change for this, now inputs accept text and not numbers, so it will display the degrees coordinates and decimals. I think we need to make a conversion to handle the coordinates correctly in most cases

**Comment by mjy** [comment]
@jrflood can you confirm a fix?

**Comment by jrflood** [comment]
This is still bent -- the new representation of lat/long does not effect reaction of the map.  when I manually edit the collecting event's coordinates to +/- degrees without the degree symbol, the map reacts.

**Comment by jlpereira** [comment]
Pushed a new packages for this. Now should works with decimal or degrees.

Please reopen if the problem persist
