### ISSUE TITLE
tasks/collection_objects/filter/index edited search polygon fails to use new polygon.

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#86]
This page DOES still have the edited polygon problem I mentioned to @mjy last week. Creating a new polygon and hitting [Set area] works correctly, but adjusting the polygon does not. This is a previously known problem that wasn't fixed due to late detection and lower priority in view of added functionality in searches.  @jrflood has a pretty good idea how to fix it, mainly by altering .overlaycomplete() handling.  This issue is/may be present in other places: Match_georeferences (2 instances), _initialize_google_maps_georeference_widget in .../views.georeferences/google_maps/new.js, and function loadDrawableMap in .../views/shared/data/gis/_drawable_map.js.

**Comment by mjy** [comment]
@jrflood If all the issues are to be fixed it seems like they need to be refactored into a single place, right?

**Comment by mjy** [comment]
@jrflood @TuckerJD  Status?

**Comment by jrflood** [comment]
All known instances of this function have been tested and work as expected for polygons without error.  Circles are a functional disconnect in the drawn map functionality in that the radius is not persisted, such that the center point is persisted as a marker.
