### ISSUE TITLE
Task - comprehensive specimen / Model TypeMaterial - type designator roles not needed

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#861]
Type designator section does not make much sense to me. I need to select the source, which make the lectotype or neotype designation, not the person. I could not think of any example when only one person in the paper where the lectotype is designated is responsible for the type designation. For the holotype and syntype, it is always the same as the original source.

I propose to replace this section with the source picker.

**Comment by mjy** [comment]
We can back this out and nuke the type designation role, let's let it stew for a bit, but I agree with your assment as far as I can see.

**Comment by mjy** [comment]
Done, needs testing.
