### ISSUE TITLE
Task - collecting event term analyzer

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#864]
As a curator I want to see a tag cloud of values from all values in my collecting event fields.

Sensu use case from Deb Paul.

**Comment by debpaul** [comment]
Note related request to "Open an issue on column based word clouds"

@mjy is this a separate feature / function in your mind than what you specifically entered above for "Collecting Event" fields? Or would a cloud be a function that we could also apply for given fields in other modules?

**Comment by mjy** [comment]
@debpaul the software component would indeed be generic.  We'd likely configure an generic endpoint so that you could do something like `/cloud?model=Ce&attribute[]=verbatim_locality` in the backend, this would return JSON, @jlpereira would consume it into a pretty cloud.

**Comment by mjy** [comment]
Endpoint:

* [ ]  /metadata/vocabulary?model=CollectingEvent&attribute=verbatim_locality

* [ ] some endpoint to get visible models
* [ ] some endpoint to get fields for each model (maybe we have this as used in CE fields selector facet)

Optional params:

* `minimum`, `maximum`  # the number of times the word must be present
* `containing` # match terms containing
* `begining_with` # only match terms begining with
* `limit` # maximum number of records to return

To make it very visual we could provide
* A single slider for min/max setting, needs to scale to over 25k though
* A dispayed alphabet to allow for clicking a litter to populate `begining_with`

To make it very resonsive
* Every setting adjustment fires after short delay
