### ISSUE TITLE
Task - Edit Taxon Name - Source pages

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#871]
If I find a source and add source pages, and after that click on People button. the pages do not save and just disappear. The pages saved only if I go somewhere else on the form for few seconds.
I also do not receive confirmation message that the page was saved
![image](https://user-images.githubusercontent.com/5597748/54153557-e47a6180-440d-11e9-8857-5c38a818b053.png)

**Comment by mjy** [comment]
I hit this as well.  This is because of the auto-save behaviour and when it is triggered!  It's based on the lag between when the record is saved off the first time and second time. I suggest we get rid of the auto-save.

**Comment by jlpereira** [comment]
@proceps I cant replicate this in development branch. 

As far I understand what you have done to reach this, I followed this steps:
1- First select a source
2- Fill pages input
3- Changed to Person tab bofore trigger the autosave

After done that, the autosave still working.

Where do you tried this? sandbox or production?

**Comment by proceps** [comment]
That is exactly how you described it. In my workflow I change to people right after entering source. So after I change the page, I click to People tab. And If I click to source back, the page is get lost.
I work in production with Chrome.

**Comment by jlpereira** [comment]
I bet production its not updated with the last changes, @proceps. Could you try this in sandbox or other dev server?

**Comment by jlpereira** [comment]
I tried it in sandcastle and it seems to be okay. Can we close this?

**Comment by proceps** [comment]
I checked the sandbox, and it works, but it takes about 5 seconds to save the page, and during this period the screen turns white, and I cannot do anything. Could the save be done on the background?

**Comment by jlpereira** [comment]
The idea of the spinner is prevent the user modify the information in the process.
It turns white without the spinner logo and the legend? The idea of this let the user know the information was saved or is in the process to do it. How much time is taking? The save process should take 2 or 3 secs i suppose

**Comment by proceps** [comment]
it takes about 5 sec. For the citation update, Same for the source create. In production it works much faster. What is the difference? Can we optimize it?

**Comment by jlpereira** [comment]
Perhaps a sandboxes use a debug mode that makes it run a little more slowly. But to be honest I dont really know. I think @mjy could answer this.
