### ISSUE TITLE
geoJSON for a collecting event does not include its intrinsic geographic area.

### ISSUE THREAD

**Issue by jrflood** [SpeciesFileGroup/taxonworks#872]
Only georeferences are displayed. To replicate issue, construct a collecting event with georeferences, then edit it to add a geographic area (with a shape) to the collecting event.  The intrinsic geographic area is not represented in the geoJSON feature collection.

**Comment by mjy** [comment]
What's the URL context?

**Comment by mjy** [comment]
Closing for more specific need/use of the updated response.
