### ISSUE TITLE
Bulk upload creates author names in wrong order, not order originally uploaded

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#878]
**Describe the bug**

When I bulk upload names as a .TSV they are added to the name in reverse, not original, author order. E.g. uploading Aus buus Smith & Jones, 1900 gives me a name of Aus buus Jones & Smith, 1900. And uploading Aus buus Jones & Smith, 1900 gives me a name of Aus buus Smith & Jones, 1900.

**To Reproduce**
1. When I successfully upload a TSV file containing a list of names as a bulk upload and the names are correct authorship order. 
2. Then I go to "Browse Nomenclature" or to "Edit Taxon Names" for one of those names.
3. See error that any authors with two names are reversed.

Original TSV list:
![image](https://user-images.githubusercontent.com/11411328/54373338-13c9e200-464b-11e9-853f-91389e53fd86.png)

Resulting name:
![image](https://user-images.githubusercontent.com/11411328/54373305-03196c00-464b-11e9-9904-44e8251577a3.png)

"Person" tab under "Authors"
![image](https://user-images.githubusercontent.com/11411328/54373401-31974700-464b-11e9-90f0-c550f66d3f80.png)

**Expected behavior**
Authors should be listed as they are provided in TSV file, and not rearranged. 

Environment 
- Sandbox - Cucujoidea Species File
- Production - Cucujoidea Species File
- Browser - Chrome
- Mac OS High Sierra 10.13.6

**Comment by mjy** [comment]
What happens when you edit (make a trivial change) and save the name, does the authorship re-order itself correctly?

**Comment by tmcelrath** [comment]
Thanks! I tried hard. The bug form makes it a lot easier to remember what I need to add. 

I edited the verbatim year and only the year changed. I can't edit the names directly without deleting and readding them, or if I drag them into the correct order.

**Comment by tmcelrath** [comment]
Now I think that it uploads two names in reverse, not necessarily alphabetical. See screenshots below:
Original TSV:
![image](https://user-images.githubusercontent.com/11411328/54394177-227bbd80-467a-11e9-86ea-76bd4f051892.png)

Viewing in TW (no editing):
![image](https://user-images.githubusercontent.com/11411328/54394234-522ac580-467a-11e9-9737-1e8476cee3bd.png)

**Comment by mjy** [comment]
Fixed, tagged incorrectly as fix for 881.
