### ISSUE TITLE
Names with diacritics not returned when searching

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#879]
**Describe the bug**

When I search for people with diacritics (e.g. Tomaszewska & Ślipiński) without including those diacritics, the names do not appear and are not selectable. 

**To Reproduce**
1. When I am editing a taxon name.
2. Then I go to the "Person" tab under "Author"
3. And I search "Name"
4. Then I only see "Name" without diacritics, instead of "Náme". 

Name searched without diacritics:
![image](https://user-images.githubusercontent.com/11411328/54377418-0f092c00-4653-11e9-9efe-3e81d7df8054.png)

Names searched with diacritics:
![image](https://user-images.githubusercontent.com/11411328/54377456-247e5600-4653-11e9-87ec-0fc77a40753b.png)

**Expected behavior**
Searching the name with or without diacritics should return both names with and without diacritics for selection.

**Environment (please identify where you experience this bug:**

- Production - Cucujoidea Species File
- Chrome

**Comment by mjy** [comment]
Technically not working incorrectly, it could just be working differently. It may be difficult to enable this without a different indexing backend.

**Comment by tmcelrath** [comment]
I'd be a good thing to have to keep undergrads or data entry folks from adding duplicate names.

**Comment by mjy** [comment]
Duplicates are more effective in some ways because they let the user concentrate on data entry, and curators concentrate on curation.  Remember Uniquify people and other data objects will be possible.

**Comment by tmcelrath** [comment]
Still ... it's better to not have the duplication at all right? I can see this being a problem if we increase the number of foreign users of TaxonWorks. If it's an underlying indexing problem, better to solve it now rather than later right?

**Comment by mjy** [comment]
Normalized data is of course nice for many reasons.  Out of curiousity have you ever interacted with *any* curatorial system that did this well?

Links for devs (you can see how infinitely more complicated back end bits get).

* https://thoughtbot.com/blog/optimizing-full-text-search-with-postgres-tsvector-columns-and-triggers
* https://gist.github.com/rach/9289959

**Comment by tmcelrath** [comment]
I have not, but it would be great if one did.

**Comment by mjy** [comment]
Exactly ;)

**Comment by mjy** [comment]
https://www.postgresql.org/docs/current/unaccent.html

**Comment by mjy** [comment]
If you add as alternate values, then search should work at present.  Still not the guessing/fuzzy, but for common names this is a good solution.

**Comment by mjy** [comment]
See - https://blog.crunchydata.com/blog/postgres-full-text-search-a-search-engine-in-a-database

**Comment by tmcelrath** [comment]
Honestly this issue isn't an issue for me with alternate values. Not sure if still an issue with indexing or search calls? If not, then I think closing is fine.
