### ISSUE TITLE
CodeClimate score very low

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#88]
At the moment of reporting this issue the score shown in the CodeClimate badge is an orange-almost-red 1.3.

Code needs revision and vendor code needs to be moved out of the source tree and deployed in some other way so our score is not penalized by vendors. Haven't explored if it is possible to instruct CodeClimate to ignore selected files, but still would be better if the repository had only the code that we actually maintain.

**Comment by mjy** [comment]
True, especially re maintaining only our code.  I have also read various
blogs that indicate that CodeClimate becomes less useful for large projects.

**Comment by mjy** [comment]
Manually added webhook. Not sure it will work, open source related info a little scarce.  Summaries seem to have died out around June as well?

**Comment by mjy** [comment]
Requested that codeclimate switch their target branch from 'master' to 'development'

**Comment by mjy** [comment]
Current score should be much closer.  Add tweaks to .codeclimate.yml to better represent our code if found.
