### ISSUE TITLE
Task - New taxon name - edit taxon name relationship

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#880]
When I create a relationship, then I see a green edit button.  Clicking it lets me edit the relationship type and the object taxon name.  

* Bonus - I should be presented options that are "finer" than the level I have selected in the smart selector

**Comment by proceps** [comment]
Same should also be applied to the type relationships

**Comment by mjy** [comment]
@proceps Please don't append todos to issues.  Can we close this issue?

**Comment by proceps** [comment]
When I make a selection, the relationship is get updated, but the selector options do not disappear. After saving new relationship, the subform should reset
