### ISSUE TITLE
Bulk upload of taxon names doesn't preserve all names in "Verbatim" Author field

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#881]
**Describe the bug**

When I upload a bulk TSV of Taxon names with Authors, the verbatim authors are not preserved if author is not in parentheses or if there are multiple authors

**To Reproduce**
1. When I upload a TSV list of taxon names and associated authors.
2. Then I go to edit one of the created taxon names.
3. And those authors are not in parentheses or there are multiple authors not in parentheses.
4. Nothing is created in the "Authors" "Verbatim" field except for year. 

Original TSV:
![image](https://user-images.githubusercontent.com/11411328/54446618-5ce66880-4715-11e9-9199-fa3d0e6be097.png)

Resulting name in Verbatim Author section in "Edit Taxon Names" - one author
![image](https://user-images.githubusercontent.com/11411328/54446706-928b5180-4715-11e9-8b5a-f0b31b78ccb4.png)

Resulting name in Verbatim Author section in "Edit Taxon Names" - multiple authors
![image](https://user-images.githubusercontent.com/11411328/54446752-adf65c80-4715-11e9-88ee-d18615b384af.png)

**Expected behavior**
Author names should be verbatim parsed from original TSV to that field to save time

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by mjy** [comment]
This is currently expected behaviour.  When People are creatable and can represent the full name, then verbatim name is not stored.  When parens are required we store verbatim to over-ride people.

**Comment by tmcelrath** [comment]
I like and don't like this. Is there harm in storing it anyway?

**Comment by mjy** [comment]
I understand I think. The verbatim_author field overrides calculable values, it's not really what you think of as "value that I started with when I imported", a subtly different concept.  Storing it, when representation is not in doubt, defeats the purpose in many ways.  Taxonomists need to give up the past in some ways ;).

**Comment by tmcelrath** [comment]
Fair enough. I'm okay with this, now that I know Source and People linkages are connected more.
