### ISSUE TITLE
OTU radial - asserted distribution - add locks

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#882]
When I annotate something with the OTU radial - asserted distributions
Then I want to be able to lock source and OTU like in "Task - New Asserted distributions from Geography".

**Comment by mjy** [comment]
Did you try and pin Otus and Sources and set them as default?

**Comment by tmcelrath** [comment]
I tried pinning sources - it helps between OTUs, but within a single OTU keeping it there would be SUPER useful because often a single source will have dozens of asserted distributions. Clicking it every time adds a lot of time that adds up.

**Comment by mjy** [comment]
Second question- did you try the Asserted Distribution task?  It has locks
at all levels.  Only available in sandbox, but we expect sandbox to be
moved to production within two weeks.

M

**Comment by tmcelrath** [comment]
I just did and I like it. Would still like to see at least some of that functionality added to radial annotator though. Is there a bug report for not being able to add a new Asserted Distribution after the first one? Cause I just ran into that.

**Comment by mjy** [comment]
Unsure.  We need documentaiton on AD and what it means for sure.  Unique combination of Source, Area, OTU.
