### ISSUE TITLE
Syncronizing GeographicAreas / asserted distributions

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#883]
When an asserted distribution shapefile source, e.g. https://gadm.org/download_country_v3.html is updated, and/or a new province/country is created, then we need to update those sources in TaxonWorks. This has already happened, e.g. Provinces in Chile have grown recently, so some that are listed now as Provinces (e.g. Ñuble [https://en.wikipedia.org/wiki/Provinces_of_Chile]) are not up to date in TaxonWorks. 

How do we update regularly updated standard shapefile datasets?

**Comment by mjy** [comment]
Cross-referencing and closing for https://github.com/SpeciesFileGroup/taxonworks/issues/3627.
