### ISSUE TITLE
Data - TaxonName - sorting

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#884]
I need an interface to sort taxa by the date created (may be some other field). I need to see all taxon names related for the last few month.

**Comment by mjy** [comment]
@proceps can we close this?  It exists in the taxon name filter.

**Comment by proceps** [comment]
When I set filter for updated within last 100 days and click filter, it does not return me any record.

**Comment by mjy** [comment]
@jlpereira I think the date is getting set incorreclty- as future, not past

Today, if I ask for 100 days ago, I get: `updated_since=2019-08-02`

**Comment by jlpereira** [comment]
This is already fixed
