### ISSUE TITLE
Can't create new user because of invalid email but email is valid

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#886]
**Describe the bug**

Can't create a new user, returns error "invalid email" but email is valid

**To Reproduce**
1. When I  create a new user with the email example.user.a@gmail.com
2. Then I give them a default password and name
3. And I hit submit
4. Then I see error "email is invalid" even though email is valid

![image](https://user-images.githubusercontent.com/11411328/54722246-12f4ec80-4b32-11e9-885d-c72fb2d2db9c.png)

**Expected behavior**
Be able to create a new user

**Environment (please identify where you experience this bug:**
- Production
- Chrome

**Comment by LocoDelAssembly** [comment]
@tmcelrath Could be possible that you had your input misplaced? In your screen capture looks like you supplied the email in the **name** field and the name in the **email** field which produced a validation error because there was not a single occurrence of "@"

**Comment by jlpereira** [comment]
@tmcelrath tested and works. I think you should look what @LocoDelAssembly told you. It seems you're writing the name in the email input

**Comment by tmcelrath** [comment]
That's end of day brain for ya. Sorry about that.
