### ISSUE TITLE
Task - Source from Citation - no create button

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#887]
When I search for a new source, and use only the title "Two new species in the genus Kuvera Distant, 1906 (Hemiptera, Cixiidae, Cixiinae) from China". CrossRef find the source, but the button to create the source is not available.
![image](https://user-images.githubusercontent.com/5597748/54885590-ce2bc700-4e4b-11e9-905c-d9979a94bb38.png)

Tested both in production and sandbox.
Using Chrome browser.

**Comment by mjy** [comment]
Can't replicate. @jlpereira can you?

**Comment by jlpereira** [comment]
No, tested in sandcastle and works fine. Close?
