### ISSUE TITLE
Task - Search and list localities - result section

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#909]
The result section should have 3 "states" of display, these are configured by toggling two icons (map/table):

* A - Table only
* B - Map only
* C - "Split screen" (table, or an abreviated table on the left, map on the right)

<img width="1085" alt="Screen Shot 2019-04-08 at 1 22 02 PM" src="https://user-images.githubusercontent.com/22600/55747236-6a83cb00-5a01-11e9-9dda-ec15c01cf6a1.png">

**Comment by jrflood** [comment]
Known shortcomings: clearing of map highlight on mouseout from table row broken; select all broken; last derived feature removed from list not removed from map; move action controls from table header to above-table buttons.

**Comment by jrflood** [comment]
TODO:  Older buttons: [Clear map] disjoint from maps; [Add to Map] adds features to map, but seems redundant now; [Reset] needs rework due to changed relationships between maps and table.
Map interactions:  copy drawn shape to found map; highlight reset still broken;

**Comment by jrflood** [comment]
Checklist for #908, #909
- [ ] `fix row hover un-highlight`
- [ ] `object count` @mjy
- [X] `fix transcribe drawn shape to results map` -- polygons ok.  circle anomaly,  postpone
- [X] `fix [Reset] - does not clear search map, (or added shapes on results map)`
- [ ] `issue TBD`
