### ISSUE TITLE
Loan Search

### ISSUE THREAD

**Issue by mmkohler** [SpeciesFileGroup/taxonworks#917]
**Describe the bug**
I can search loans by people, but not by loan number

**To Reproduce**
1. When I  '...' Go to 'Data' : 'Loans'
2. Then I '....'type a number in the search bos
3. And I '....' wait for the popup menu, I get nothing

<provide a screenshot>

**Expected behavior**
I expected loans to be listed
**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
**- Sandbox - <name>** Snadbox.speciesfile.org
- Production

**Comment by mjy** [comment]
Fixed.  You can search by:
* Any identifier, whole or part
* Id
* recipient email address
* dates, in format YYYY-MM-DD
