### ISSUE TITLE
Browse Object radial

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#919]
Make all sectors right clickable. Sometime I would like to open related data in the new window (but not always).

**Comment by mjy** [comment]
Already works? You need to use your alt/option key when you left click, or have your mouse buttons mapped accordingly.

**Comment by proceps** [comment]
No it does not, it only give my a "Save image" option.

**Comment by mjy** [comment]
That's not holding the option key, right? Works with option-left click key for me.  

Steps to replicate?  Browser?

**Comment by mjy** [comment]
@jlpereira not sure if you can do this, but we need the right click, open link in new tab behaviour if possible.

**Comment by jlpereira** [comment]
Sure, won't be a problem
