### ISSUE TITLE
Task - New type specimen - 

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#921]
**Describe the bug**

**To Reproduce**
1. When I  '...'
2. Then I '....'
3. And I '....'

<provide a screenshot>

**Expected behavior**

**Screenshots**

**Environment (please identify where you experience this bug:**
*** One of ***
- Development (native|docker : shaw)
- Sandbox - <name>
- Production

**Comment by jlpereira** [comment]
@proceps ? this is only the template

**Comment by proceps** [comment]
Probably submitted by mistake
