### ISSUE TITLE
Task - Comprehensive specimen digitization - biocurations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#924]
Biocurations do not show up

**Comment by jlpereira** [comment]
I think this is a backend problem @proceps . The response is sending an empty array. Could you take a look at this @mjy ?

**Comment by jlpereira** [comment]
Sorry, I was looking this in a wrong project. @proceps biocurations are there

**Comment by mjy** [comment]
@proceps You need to make a biocuration group for them to show up. tasks/controlled_vocabularies/biocuration/build_collection
