### ISSUE TITLE
Task - Browse nomenclature - Eye filter

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#930]
Unexpected behavior to replicate:
1. Click on taxon name
2. click to open eye selector (do not close)
3. click on taxon name (page reloaded with eye selector is closed)
4. click on taxon name second time (page reloaded with eye selector open)

As a short addition, add a tool tip to the eye filter.

**Comment by mjy** [comment]
Can no longer replicate- it is briefly open on the third click, then closes for me (FF).  @proceps can we close?

**Comment by proceps** [comment]
Yes, it reopens for me for about a second, than get closed.
Tool tip still should be added to the eye filter.

**Comment by mjy** [comment]
@proceps - still an issue?
