### ISSUE TITLE
Object Radial for TN - add Comprehensive task to the list

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#934]

**Comment by mjy** [comment]
What do you mean here?

**Comment by proceps** [comment]
Just to add additional sector to OTU Object Radial (comprehensive digitization task).

**Comment by mjy** [comment]
But what is affect?  Just straight navigation?

**Comment by proceps** [comment]
Yes, add a new specimen for this OTU.

**Comment by mjy** [comment]
That's a very different thing :)
