### ISSUE TITLE
Image thumb previewer - large size images of Tiff format do not display

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#942]
**Describe the bug**

Tiff imags do not display at large size on image click through preview.

**To Reproduce**
1. When I drop a Tiff (probably also BMP etc.) image on the type specimen form
2. Then I get a thumbnail
3. And when I click it 2x
4. Then I see a broken image link

**Expected behavior**
A large format image is displayed

**Environment (please identify where you experience this bug:**
*** One of ***
- Sandfly
- FF Deb

## Solution

Create a large size image in png/jpg format on request only.

**Comment by jlpereira** [comment]
Task?

**Comment by mjy** [comment]
This is me, back end I think.

**Comment by mjy** [comment]
This is resolved.  Need to regenerate thumbs for early images.
