### ISSUE TITLE
Task - Comprehensive collecting event - # symbol

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#953]
When I try to modify Verbatim Label field, and add a "#" symbol, the record does not save. I got a spinner, which does not stop. Adding any other symbol does not cause the problem. When I create a new record with the symbol, it seems that it also does not create a problem.

![image](https://user-images.githubusercontent.com/5597748/56525626-de999500-6510-11e9-8308-985e30f68bf3.png)

**Comment by mjy** [comment]
@proceps Can't replicate, neither can José. Please document browser and environment.
