### ISSUE TITLE
Radials - Add initialization option to check for existing data

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#957]
As a developer, when I instantiate a radial annotator, then I want to pass a parameter that will:
* Perform the load of existing annotations in the background
* Cause the annotator to glow

The default of this param should be *false*.

I can imagine this useful for all radials that use the green numbered border.

**Comment by jlpereira** [comment]
Done param for this: data-show-count="true" 
Helper:
```
radial_annotator(object, true)
```
