### ISSUE TITLE
Task - Edit TaxonName - missing relationships

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#962]
validating and potentially validating relationships are missing from the ListAll

**Comment by mjy** [comment]
Nomenclatural code?  Class?

**Comment by proceps** [comment]
ICZN. TaxonNameRelationships. I was on a species page. But I assume this is true for all codes.

**Comment by proceps** [comment]
All ICZN (and other code) TaxonNameRelationships should be listed. At the moment, I can still access them using the search interface.

**Comment by mjy** [comment]
@proceps You must set the `assignable` property for them to be included in the all list.

**Comment by proceps** [comment]
I pushed changes. It is partially resolve the issue. The problem now is that the relationships are now listed, but their parent (for the hierarchy reason is not). Parent should always be visible and greyed out if self.assignable is false.

**Comment by jlpereira** [comment]
@proceps which parents are not visible? and what is the const value of those?

**Comment by proceps** [comment]
![image](https://user-images.githubusercontent.com/5597748/58922362-24e13700-8700-11e9-9307-1c4c445b75d8.png)
@jlpereira We have a hierarchy of classes (relationships and classification). Each class and subclass have property self.assignable. That is how you filter classes to display. When the subclass .assignable is true, it is displayed on the tree (for example conserved). But the parent of this class (Validating) has .assignable is false. It is out of the tree, so, conserved subclass does not have a parent on the tree. Could you please add all classes and subclasses to the tree, and permanently grey out all those which have self.assignable = false.

**Comment by mjy** [comment]
@Dmitriev, Dmitry A <proceps@illinois.edu> We need to have you configure
the JSON response (taxon_name_relationships/relationship_types.json IIRC)
so that @jlpereira can work with response.  If it doesn't look right the
constants are in config/initializers/constants/...

**Comment by jlpereira** [comment]
The reason why some classes are not displaying in the tree view is because it didn't have subject_status_tag or object_status_tag, this is needed to display the name in the tree. Otherwise it won't be included.

<img width="846" alt="Captura de Pantalla 2019-06-05 a la(s) 18 41 12" src="https://user-images.githubusercontent.com/16530364/58992600-a947be80-87c1-11e9-93bd-c4a732baa306.png">

Here is an example with TaxonNameRelationship::Iczn::Validating

**Comment by jlpereira** [comment]
OK, I create the label based in the last part of the class type. For example, in the case of 'TaxonNameRelationship::Iczn::Validating' the label will be 'Validating'. This will be done everytime the class is not founded in 'all' list.

**Comment by jlpereira** [comment]
Let me know @proceps if now you're getting the correct list

**Comment by proceps** [comment]
Thanks @jlpereira, will be able to check in few days. Out of town now.

**Comment by jlpereira** [comment]
I think this is already solved. Closing.
