### ISSUE TITLE
color wheel for collection object image breakdown

### ISSUE THREAD

**Issue by adeans** [SpeciesFileGroup/taxonworks#964]
**Describe the bug**

The color wheel for some depictions shows that the buffered collecting event (blue wedge) is missing, when in fact there is a CE.

**To Reproduce**
1. I click on the TODO map ../tasks/accessions/breakdown/sqed_depiction/todo_map
2. Then I click on one with missing blue wedge ../tasks/accessions/breakdown/sqed_depiction/21
3. And I see it has a buffered collecting event

<provide a screenshot>

**Expected behavior**
I expected it to have no buffered collecting event, but one is present

**Screenshots**
![Screen Shot 2019-04-30 at 9 21 32 PM](https://user-images.githubusercontent.com/8043009/57002581-74c36000-6b8e-11e9-9f5a-1f31d4da62d0.png)

**Environment (please identify where you experience this bug:**
*** One of ***

- Production
- Browser [Chrome]

**Comment by mjy** [comment]
That should be no collecting event, not no *buffered* collecting event?  Can you confirm?

**Comment by adeans** [comment]
Ahhhhh. right. Yup, my mistake. Maybe I should actually read the color
wheel key.
