### ISSUE TITLE
Dates problem with specs

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#968]
There are some specs that are not system-locale invariant. In particular failures happen with https://github.com/SpeciesFileGroup/taxonworks/blob/ce0766f7f44e783185c372b4762895f181ee26e3/spec/lib/housekeeping/timestamps_spec.rb#L35 and https://github.com/SpeciesFileGroup/taxonworks/blob/ce0766f7f44e783185c372b4762895f181ee26e3/spec/lib/housekeeping/timestamps_spec.rb#L43

Failure example:
```
  1) Housekeeping::Timestamps Timestamps class scopes created_in_date_range
     Failure/Error: expect(GeographicItem.created_in_date_range('12-31-16', '12/31/17').count).to eq(2)
     
     ActiveRecord::StatementInvalid:
       PG::DatetimeFieldOverflow: ERROR:  date/time field value out of range: "12-31-16"
       LINE 1: ...phic_items" WHERE (geographic_items.created_at >= '12-31-16'...
                                                                    ^
       HINT:  Perhaps you need a different "datestyle" setting.
       : SELECT COUNT(*) FROM "geographic_items" WHERE (geographic_items.created_at >= '12-31-16' and geographic_items.created_at <= '12/31/17')
```

Setting the offending dates to YY-MM-DD changes the problem to "expected 2 got 0" and using YYYY-MM-DD works (but not fixing at this time as I might be hiding a deeper problem if I do so).

Related issue: https://github.com/SpeciesFileGroup/taxonworks/issues/610

**Comment by mjy** [comment]
@LocoDelAssembly I'd suggest making a branch with the date changes on it and adding it to .travis in this case (letting the tests fail), and we can go from there.

**Comment by mjy** [comment]
@LocoDelAssembly is this fixed with the procs changes?

**Comment by LocoDelAssembly** [comment]
@mjy I believe, yes. Also, regarding #610, given it was supposed to cover backend only I guess it can be closed, I couldn't find anything else that wasn't working with the intended date format because our goal is the standard already.

On the frontend side however some date inputs display dates in user's locale (but browsers send the data to the backend in the correct format, it is a display issue only).

Will open a pull request on dates branch.
