### ISSUE TITLE
Task - Edit TaxonName - duplicate taxon

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#973]
We already have option to add a child taxon or add a sister taxon. Another option is needed: duplicate a taxon.
This is extremely useful in cases of original misspelling or genus and subgenus:
 The attributes which need to be duplicated:
1. name
2. parent
3. rank.
4. author
5. year
6. original source
8. original combination relationships

**Comment by mjy** [comment]
@jlpereira steps:

* [ ] Add Green 'Clone' button b/w Save and New.  it is always present, but disabled until there is an ID for this record
* [ ] When user clicks clone, then they are prompted with confirmation dialog
* [ ] When user accepts POST with the params listed above to create a new record
* [ ] Then navigate to that record
* [ ] Add hotkey combination to trigger, hotkey also brings up dialog 

Confirmation dialog can not be disabled.
