### ISSUE TITLE
Radial annotator - Confidences

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#974]
I am in 3i project in production. Every time, I am trying to set up Confidence for a taxon (Browse Nomenclature). It takes about 3 seconds to get Radial annotator to refresh the page and find recently used confidences. 
Please optimize the search and refresh the page faster.

**Comment by mjy** [comment]
I can't replicate.  There is a half second pause.  Does this still exist?  Browser?

**Comment by proceps** [comment]
most likely this related to the data accumulation in the 3i database. Now the delay is more than 5 sec. It seems that query is not optimized.

**Comment by mjy** [comment]
I am doing the exact same thing you are, your project,  in production.
