### ISSUE TITLE
task - OTU Radial - biological associations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#976]
Make it is scrollable. When multiple relationships reported, They go below the edit form, and there is no way to see them.

![image](https://user-images.githubusercontent.com/5597748/57638077-9a7b3c80-7572-11e9-8952-5fbf82bf7665.png)

**Comment by jlpereira** [comment]
I think we need to split this interface in 2 tabs, one for create/edit and another to display the list. What you think?

**Comment by proceps** [comment]
we had a second stroller which was disactivated.  If it is active, it should resolve the issue. May be you already did it....

**Comment by jlpereira** [comment]
I removed the table scroll, now you should be able to scroll the form and see the complete list below

**Comment by proceps** [comment]
@jlpereira The existing biological associations have disappeared from the form entirely. You can create one. But no list at the bottom

**Comment by jlpereira** [comment]
The list and the existing objects are there as you can see in the image, you have to scroll the container

<img width="1440" alt="Captura de Pantalla 2019-05-17 a la(s) 18 27 26" src="https://user-images.githubusercontent.com/16530364/57957078-7b154400-78d1-11e9-8217-877abfdc66a3.png">

**Comment by proceps** [comment]
This is from production database, which should be updated yesterday...

![image](https://user-images.githubusercontent.com/5597748/57957648-9a58a500-78c2-11e9-85b4-adf70ca474e7.png)

**Comment by jlpereira** [comment]
It seems to be other problem then, this was fixed before of that, and it seems to work okay for me in localhost. Can you check the browse console to see if you're getting errors?

**Comment by proceps** [comment]
﻿
undefined:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by proceps** [comment]
1558149423640	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: mozillaAddons
1558149423640	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: resource://pdf.js/
1558149423640	addons.webextension.screenshots@mozilla.org	WARN	Loading extension 'screenshots@mozilla.org': Reading manifest: Invalid extension permission: about:reader*
WebExtensions: new intermediate certificate added api.js:32
WebExtensions: signatures re-verified api.js:42
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 230"  data: no]
1558149456404	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
1558149456416	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
1558149456427	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 230"  data: no]
Unkown category for SetEventRecordingEnabled.
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 230"  data: no]

1558149483948	Toolkit.Telemetry	WARN	TelemetryStorage::_scanArchive - have seen this id before: ee4d3223-5817-45ec-9975-6c107fcc085e, overwrite: false
1558149483948	Toolkit.Telemetry	WARN	TelemetryStorage::_scanArchive - have seen this id before: 99294155-ea34-41ec-9dfe-ee8f42b6469b, overwrite: false
Use of nsIFile in content process is deprecated.
NetUtil.jsm:259:12
Successfully compiled asm.js code (total compilation time 67ms) demangle.js
Use of nsIFile in content process is deprecated. NetUtil.jsm:259:12
uncaught exception: 2147500033 browser-custom-element.js:1086:7
[Exception... "Method not implemented'Method not implemented' when calling method: [nsIWebNavigation::sessionHistory]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://global/content/elements/browser-custom-element.js :: construct :: line 1086"  data: no]
uncaught exception: 2147500033 browser-custom-element.js:1086:7
[Exception... "Method not implemented'Method not implemented' when calling method: [nsIWebNavigation::sessionHistory]"  nsresult: "0x80004001 (NS_ERROR_NOT_IMPLEMENTED)"  location: "JS frame :: chrome://global/content/elements/browser-custom-element.js :: construct :: line 1086"  data: no]
[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIContentSniffer.getMIMETypeFromContent]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 230"  data: no]

**Comment by jlpereira** [comment]
> ﻿
> undefined:1 Failed to load resource: the server responded with a status of 404 ()

This is okay, its related with the slice icons. 
The other log probably are related with an plugin in your browser.

Here is another image taken from sandcastle. I recommend to try again with a different browser or computer. If the problem persist, then we need to look if this could be a problem with a bad data.

![taxonworks](https://user-images.githubusercontent.com/16530364/57968666-bf412c80-7943-11e9-83f3-ad8cd6bae320.jpg)

**Comment by proceps** [comment]
2 different computers, two different browsers...

**Comment by proceps** [comment]
You have an access to Auchenorrhyncha db in production. Check Zygina hyperici for example (I also checked other species, and newly created biological association).

**Comment by jlpereira** [comment]
url?

**Comment by proceps** [comment]
https://sfg.taxonworks.org/tasks/nomenclature/browse?utf8=%E2%9C%93&id=&%5Bid%5D=376420

**Comment by jlpereira** [comment]
The problem should be fixed now with the last commit, only left update production
