### ISSUE TITLE
Task - OTU radial - biological associations

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#977]
The quick list shows the name of insects, not the list of related host plants (which would be expected from previous entries)

![image](https://user-images.githubusercontent.com/5597748/57642049-1463f380-757c-11e9-851e-53acf4c3dbd4.png)

**Comment by mjy** [comment]
Are you saying it should match biological_association_object_id?

**Comment by proceps** [comment]
Well, I do not know which one is which. So we have a title on the top of the page, if it is subject, than related one should be object. If it is object, the related one should be subject. Now they are the same.
