### ISSUE TITLE
API - Map taxon name filter to endpoint

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#978]
@LocoDelAssembly here we want to simply map 1:1 routes from the API prefix to `/taxon_names` (`def index`).

It should be a nice test for you, once we have this we'll grind out many other `/<model>` mappings.

If you want bonus points we'll copy over the documentation from lib/queries/filter for the attributes in question to the API RAML doc.

**Comment by LocoDelAssembly** [comment]
@mjy can be considered closed?

**Comment by mjy** [comment]
We added two new facets yesterday, leaves, and
taxon_name_relationship_type. Once we update api doc let's close.
