### ISSUE TITLE
Incorrect author (first/last name) rendering

### ISSUE THREAD

**Issue by tmcelrath** [SpeciesFileGroup/taxonworks#983]
**Describe the bug**

Some authors with multiple last names do not render correctly in citations

**To Reproduce**
1. When I batch upload a name (e.g. Baudi di Selve)
2. Then I add that name to a source
3. And I modify the name to have the full name in the Data:Persons area, e.g. First: Flaminio, Last: Baudi di Selve
4. Source lists author incorrectly, e.g. Selve, F. Baudi di
![image](https://user-images.githubusercontent.com/11411328/58124641-53292780-7bd4-11e9-9cd2-36884cb8a90b.png)

<provide a screenshot>

![image](https://user-images.githubusercontent.com/11411328/58124543-16f5c700-7bd4-11e9-94be-e05ba9a0019d.png)

**Expected behavior**
The source should be rendered correctly as Baudi di Selve, F.

Weirdly, this is not the case for persons created de novo - the name renders correctly. 

**Environment (please identify where you experience this bug:**
*** One of ***
- Production
- Chrome

**Comment by mjy** [comment]
Perhaps related #332

**Comment by proceps** [comment]
resolved.
