### ISSUE TITLE
Hash of hashes query param in lib/queries/taxon_name

### ISSUE THREAD

**Issue by LocoDelAssembly** [SpeciesFileGroup/taxonworks#990]
Param taxon_name_relationship of the filter is using a hash of hashes when it seems it could potentially work with an array of hashes instead. According to @mjy this is an old pattern.

The description is here: https://github.com/SpeciesFileGroup/taxonworks/blob/62215143578795609b79a1cdcf585741757c6d71/lib/queries/taxon_name/filter.rb#L46

Please note that https://github.com/SpeciesFileGroup/taxonworks/tree/taxon-names-api branch has more tests than development (including extra tests for taxon_name_relationship). Consider merging those tests into development (which are fully compatible).

**Comment by mjy** [comment]
Reviewed.  Not really old pattern, just first that came  up.

@jlpereira Let's go ahead and change the format to an Array.

```
[ { 'type' => 'TaxonNameRelationship::<>', 'subject|object_taxon_name_id' => '123' } ... {} ] 
```

Looks like this in URL:

```
?taxon_name_relationship[]type=TaxonNameRelationship::Iczn::Invalidating&taxon_name_relationship[]subject_taxon_name_id=21
```

**Comment by LocoDelAssembly** [comment]
```ruby
[ { 'type' => 'TypeOne', 'subject' => 42 }, { 'type' => 'TypeTwo', 'object' => 13 }, { 'type' => 'Gamma', 'subject' => 2019} ].to_query('taxon_name_relationship')
 => "taxon_name_relationship%5B%5D%5Btype%5D=TypeOne&taxon_name_relationship%5B%5D%5Bsubject%5D=42&taxon_name_relationship%5B%5D%5Btype%5D=TypeTwo&taxon_name_relationship%5B%5D%5Bobject%5D=13&taxon_name_relationship%5B%5D%5Btype%5D=Gamma&taxon_name_relationship%5B%5D%5Bsubject%5D=2019"
```
The pattern seems to be `query_name`[][`hash_key`]=`value`? @mjy @jlpereira

**Comment by mjy** [comment]
That's what we have here.

**Comment by mjy** [comment]
To clarify- above has [] translated, so:
```
?taxon_name_relationship[][type]=a&taxon_name_relationship[][subject_taxon_name_id]=22
```

Look OK @LocoDelAssembly?

**Comment by LocoDelAssembly** [comment]
@mjy yes I think that is the correct pattern.
