### ISSUE TITLE
Task - Nomenclatural stats

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/taxonworks#991]
As a user I would like to know several aggregate statistics about the *nomenclature* in my project.  This will be a quick static report, their won't be dynamic options here to start.

* [x] number of valid [species group, genus group, family group] names
* [x] number of in/valid species group names that are leaves (tips)

Ping @anadm, @MMCigliano, @proceps

**Comment by MMCigliano** [comment]
Do you mean by dynamic options, that you can not search for the number of in/valid species within genus A; number of in/valid genera or species within family B, etc.

**Comment by mjy** [comment]
Right.  Dynamic feedback should be through the Filter (in fact most of
these may just become things you can get from the filter).
