### ISSUE TITLE
Task - Merge people - Error validating duplicates

### ISSUE THREAD

**Issue by proceps** [SpeciesFileGroup/taxonworks#999]
When I have a source with two people, for example "Li Hu & Hu Li" and I try to unify those two, the merge script fails, because of the uniqueness test, the same source could not has the same role twice. If I unify, the task fails, but no error message is displayd, only error e-mail is sent.
Please add a validation, before merge, that two people has unique roles and not associated with the same object. Two people could be an editor and author of the source, but two of them could not be authors of the same source.

**Comment by mjy** [comment]
The error message exists already.  I will fix the check.
